using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class AlbertCamus
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il n'y a pas de honte à être heureux. Mais aujourd'hui l'imbécile est roi, et j'appelle imbécile celui qui a peur de jouir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le contraire d'un peuple civilisé, c'est un peuple créateur.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Quand il m'arrive quelque chose, je préfère être là.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Mais tout le monde sait que la vie ne vaut pas la peine d'être vécue.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Du moment qu'on meurt, comment et quand, cela n'importe pas, c'était évident.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Si près de la mort, maman devait s'y sentir libérée et prête à tout revivre.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Comme si les chemins familiers tracés dans les ciels d'étés pouvaient mener aussi bien aux prisons qu'aux sommeils innocents.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il n'était même pas sûr d'être en vie puisqu'il vivait comme un mort.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les hommes meurent et ils ne sont pas heureux.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Tous les hommes ont une douceur dans la vie. Cela les aide à continuer. C'est vers elle qu'ils se retournent quand ils se sentent trop usés.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "On croit qu'un homme souffre parce que l'être qu'il aime meurt en un jour. Mais sa vraie souffrance est moins futile : c'est de s'apercevoir que le chagrin non plus ne dure pas. Même la douleur est privée de sens.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Oui. Enfin ! Mais je ne suis pas fou et même je n’ai jamais été raisonnable. Simplement, je me suis senti tout d’un coup un besoin d’impossible. Les choses, telles qu’elles sont, ne me semblent pas satisfaisantes.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Une manière commode de faire la connaissance d'une ville est de chercher comment on y travaille, comment on y aime et comment on y meurt.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "À Oran comme ailleurs, faute de temps et de réflexion, on est bien obligé de s'aimer sans le savoir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La presse, si bavarde dans l'affaire des rats, ne parlait plus de rien. C'est que les rats meurent dans la rue et les hommes dans leur chambre. Et les journaux ne s'occupent que de la rue.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "On se fatigue de la pitié quand la pitié est inutile.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le mal qui est dans le monde vient presque toujours de l'ignorance, et la bonne volonté peut faire autant de dégâts que la méchanceté, si elle n'est pas éclairée.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "[…], le vice le plus désespérant [est] celui de l'ignorance qui croit tout savoir et qui s'autorise alors à tuer.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "[…] il vient toujours une heure dans l'histoire où celui qui ose dire que deux et deux font quatre est puni de mort.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Je suis content de le savoir meilleur que son prêche.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "[…] il peut y avoir de la honte à être heureux tout seul.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "A mon âge, on est forcément sincère. Mentir est trop fatigant.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il tenait le milieu, voilà tout, et c'est le type d'homme pour lequel on se sent une affection raisonnable, celle qui fait qu'on continue.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il savait ce que sa mère pensait et qu'elle l'aimait en ce moment. Mais il savait aussi que ce n'est pas grand-chose que d'aimer un être ou du moins qu'un amour n'est jamais assez fort pour trouver sa propre expression.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "...qu'il y a dans les hommes plus de choses à admirer que de choses à mépriser.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La liberté est un bagne aussi longtemps qu'un seul homme est asservi sur la terre.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il dit que la poésie est révolutionnaire.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Tout le monde ment. Bien mentir, voilà ce qu'il faut.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Chacun sert la justice comme il peut. Il faut accepter que nous soyons différents. Il faut nous aimer, si nous le pouvons.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Et si l'humanité entière rejette la révolution ? Et si le peuple entier, pour qui tu luttes, refuse que ses enfants soient tués ? Faudra-t-il le frapper aussi ?", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Alors choisissez la charité et guérissez seulement le mal de chaque jour, non la révolution qui veut guérir tous les maux, présents et à venir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Même dans la destruction, il y a un ordre, il y a des limites.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les hommes ne vivent pas que de justice.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "L'honneur est un luxe réservé à ceux qui ont des calèches. — Non. Il est la dernière richesse du pauvre.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Mais non, c'est l'éternel hiver. Nous ne sommes pas de ce monde, nous sommes des justes. Il y a une chaleur qui n'est pas pour nous. Ah ! pitié pour les justes !", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Pour nous qui ne croyons pas à Dieu, il faut toute la justice ou c'est le désespoir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "On commence par vouloir la justice et on finit par organiser une police.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "J'ai lancé la bombe sur votre tyrannie, non sur un homme. — Sans doute. Mais c'est l'homme qui l'a reçue.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Si la seule solution est la mort, nous ne sommes pas sur la bonne voie. La bonne voie est celle qui mène à la vie, au soleil. On ne peut avoir froid sans cesse.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Marche ! Nous voilà condamnés à être plus grands que nous-mêmes. Les êtres, les visages, voilà ce qu'on voudrait aimer. L'amour plutôt que la justice !", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le bonheur ? — Sentir la main d'un homme avant de mourir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Toute valeur n'entraîne pas la révolte, mais tout mouvement de révolte invoque tacitement une valeur.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "L'intelligence dans les chaînes perd en lucidité ce qu'elle gagne en fureur.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "[Marx a] pu mêler dans sa doctrine la méthode critique la plus valable et le messianisme utopique le plus contestable.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La vraie générosité envers l'avenir consiste à tout donner au présent.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le fascisme, c'est le mépris, en effet. Inversement, toute forme de mépris, si elle intervient en politique, prépare ou instaure le fascisme.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Heureusement, il y a la genièvre, la seule lueur dans ces ténèbres.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "L'homme est ainsi, cher monsieur, il a deux faces : il ne peut pas aimer sans s'aimer.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les martyrs, cher ami, doivent choisir d’êtres oubliés, raillés ou utilisés. Quant à être compris, jamais.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "N'attendez pas le Jugement dernier. Il a lieu tous les jours.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Mal nommer un objet, c'est ajouter au malheur de ce monde.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les vrais artistes ne méprisent rien ; ils s'obligent à comprendre au lieu de juger.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Chaque génération, sans doute, se croit vouée à refaire le monde. La mienne sait pourtant qu'elle ne le refera pas. Mais sa tâche est peut-être plus grande. Elle consiste à empêcher que le monde se défasse.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Oui, j'ai une patrie : la langue française.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Toute société est basée sur l'aristocratie, car celle-ci, la vraie, est exigence à l'égard de soi-même et sans cette exigence toute société meurt.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Ceux qui ont vraiment quelque chose à dire, ils n'en parlent jamais.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Je ne peux pas vivre longtemps avec les êtres. Il me faut un peu de solitude, la part d'éternité.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La démocratie ce n’est pas la loi de la majorité mais la protection de la minorité.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "C'est déjà beaucoup de savoir qu'à énergie égale, la vérité l'emporte sur le mensonge.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les mots prennent toujours la couleur des actions ou des sacrifices qu'ils suscitent.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Je continue à croire que ce monde n'a pas de sens supérieur. Mais je sais que quelque chose en lui a du sens et c'est l'homme, parce qu'il est le seul être à exiger d'en avoir.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le goût de la vérité n'empêche pas la prise de parti.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La justice, c'est de juger les hommes sur eux-mêmes et non sur leur nom ou leurs idées.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Les doctrines, comme les nations et les individus, ne meurent qu'en refusant de s'engager.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Il n'y a ni justice ni liberté possibles lorsque l'argent est toujours roi.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Une société basée sur l'argent ne peut prétendre à la grandeur ou à la justice.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Notre monde, demain, sera ce que nous voudrons qu'il soit. Mais il faut le vouloir durement et longtemps.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "La civilisation mécanique vient de parvenir à son dernier degré de sauvagerie. Il va falloir choisir, dans un avenir plus ou moins proche, entre le suicide collectif ou l'utilisation intelligente des conquêtes scientifiques.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Ce que je sais de la morale, c'est au football que je le dois.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "L'Afrique commence aux Pyrénées.", Author = "Albert Camus" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Albert_Camus", Text = "Le bien-être du peuple en particulier a toujours été l'alibi des tyrans, et il offre de plus l'avantage de donner bonne conscience aux domestiques de la tyrannie.", Author = "Albert Camus" },
        };
    }
}