using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class AlexandreDumas
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Le soir, je rentrai assez tard, comme c'est ma coutume. Aux premiers pas que je fis dans ma chambre, je sentis que quelque chose craquait sous ma botte. Je levai vitement le pied, rejetant tout le poids de mon corps sur l'autre jambe : le même craquement se fit entendre de nouveau ; je cru que je marchais sur des œufs. Je baissai ma bougie... Mon tapis était couvert d'escargots.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Il faut avoir vu la plaine Saint-Denis un jour d'ouverture, pour se faire une idée du spectacle insensé qu'elle présente. Pas une alouette, pas un moineau franc ne passe, qu'il ne soit salué d'un millier de coups de fusil.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Le capitaine avait reconnu, la veille, un navire marchand, et s'était endormi là-dessus en fumant sa pipe à opium ; mais voilà que, dans la nuit, le chat était devenu tigre, et qu'il montrait ses griffes de fer et ses dents de bronze.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Le capitaine Pamphile, en passant à la hauteur du cap des Palmes, en vue de la Guinée supérieure, avait attrapé dans sa chambre un magnifique papillon, véritable fleur volante des tropiques, aux ailes diaprées et étincelantes comme la gorge d'un colibri.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Aucune route n'était tracée dans la forêt ; mais, avec l'instinct du chasseur et la science du marin, il n'eût qu'à jeter un coup d’œil sur la terre et le ciel pour s'orienter à l'instant ; il s'avança donc sans hésitation, comme s'il eût été familier avec ces immenses solitudes ; plus il pénétrait dans la forêt, plus elle prenait un caractère grandiose et sauvage.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Toute cette immense étendue, qui conservait, même pendant la nuit, ses teintes chaudes et tranchées, était éclairée par cette lune brillante des tropiques, qui seule sait ce qui se passe au milieu des grandes solitudes du continent africain ; de temps en temps, le silence était troublé par les rugissements des hyènes et des chacals qui suivaient les deux armées, et au-dessus desquels s'élevait, comme le roulement du tonnerre, le rauquement lointain de quelque lion.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Jusqu'au jour où Dieu daignera dévoiler l'avenir à l'homme, toute la sagesse humaine sera dans ces deux mots : Attendre et espérer !", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Par sa réponse à monsieur de Dreux-Brézé, Mirabeau avait frappé la royauté au visage. Par la prise de la Bastille, le peuple venait de la frapper au cœur.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "À chaque pas on rencontre, en ce monde, une chose inexplicable ; c’est pour ceux qui ne peuvent pas les expliquer et qui ne veulent pas y croire que le doute a été inventé.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Les hommes de génie sont parfois atteints de ces niaiseries sublimes qui font que les derniers goujats politiques de l’avenir ont le droit de rire au nez de leur mémoire.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Et cependant la voiture roulait toujours, poussant devant elle un flot de peuple et un nuage de poussière, comme un vaisseau en dérive pousse devant lui les flots de l’Océan et un nuage d’écume ; et la comparaison est d’autant plus exacte, que jamais naufragés ne furent menacés par une mer plus hurlante et plus agitée que celle qui se préparait à engloutir la malheureuse famille au moment où elle tenterait de gagner les Tuileries, qui étaient pour elles le rivage.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Toutes raisons suffisantes, jointes surtout à l’aigreur naturelle de son caractère, pour que tante Angélique haït les Billot en général et Catherine en particulier. Et quand tante Angélique haïssait, elle haïssait bien, elle haïssait en dévote.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "J'avais dans la tête un drame bien intime, bien sombre, bien terrible, que je voulais faire passer de ma tête sur le papier [...]. Mais je remarquai une chose : c'est que, pour le travail profond et assidu, il faut les chambres étroites, les murailles rapprochées, et le jour éteint par des rideaux de couleur sombre.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Les vastes horizons, la mer infinie, les montagnes gigantesques, surtout lorsque tout cela est baigné de l'air pur et doré du Midi, tout cela vous mène droit à la contemplation, et rien mieux que la contemplation ne vous éloigne du travail [...].", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Il est vrai que la nuit, quand je pouvais prendre sur moi de fermer mes volets aux rayons tentateurs de la lune ; quand je pouvais détourner mes regards de ce ciel tout scintillant d'étoiles ; quand je pouvais m'isoler avec ma propre pensée, je ressaisissais quelque empire sur moi-même.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "Puis il y avait les jours de tempête, les jours où le ciel si pur se voilait de nuages sombres, où cette Méditerranée si azurée devenait couleur de cendre, où cette brise si douce se changeait en ouragan.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "— Mais qu'est-ce donc que ce manant-là, qui croit qu'on est obligé de donner à des gens comme nous des soufflets pour les faire battre ?", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "— Ah çà ! mon cher Olivier, lui dis-je, vous êtes donc un Saint-Georges pour parler comme cela d'avance.", Author = "Alexandre Dumas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alexandre_Dumas", Text = "— Oui, je l'ai insulté ; mais je voulais me battre avec lui, et quand on veut se battre avec les gens il faut bien les insulter.", Author = "Alexandre Dumas" },
        };
    }
}