using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class AlfreddeMusset
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Tous les hommes sont menteurs, inconstants, faux, bavards, hypocrites, orgueilleux et lâches, méprisables et sensuels ; toutes les femmes sont perfides, artificieuses, vaniteuses, curieuses et dépravées ; le monde n'est qu'un égout sans fond où les phoques les plus informes rampent et se tordent sur des montagnes de fange ; mais il y a au monde une chose sainte et sublime, c'est l'union de deux de ces êtres si imparfaits et si affreux. On est souvent trompé en amour, souvent blessé et souvent malheureux ; mais on aime, et quand on est sur le bord de sa tombe, on se retourne pour regarder en arrière ; et on se dit : \" J'ai souffert souvent, je me suis trompé quelquefois, mais j'ai aimé. C'est moi qui ai vécu, et non pas un être factice créé par mon orgueil et mon ennui.\"", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Les grands artistes n'ont pas de patrie.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Les plus désespérés sont les chants les plus beaux,\nEt j'en sais d'immortels qui sont de purs sanglots.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Oui, j’écris rarement, et me plais de le faire.\nNon pas que la paresse en moi soit ordinaire,\nMais, sitôt que je prends la plume à ce dessein,\nJe crois prendre en galère une rame à la main.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "L'hypocrisie est morte ; on ne croit plus aux prêtres;\nMais la vertu se meurt, on ne croit plus à Dieu.\nLe noble n'est plus fier du sang de ses ancêtres ;\nMais il le prostitue au fond d'un mauvais lieu.\nOn ne mutile plus la pensée et la scène,\nOn a mis au plein vent l'intelligence humaine ;\nMais le peuple voudra des combats de taureau.\nQuand on est pauvre et fier, quand on est riche et triste,\nOn n'est plus assez fou pour se faire trappiste ;\nMais on fait comme Escousse, on allume un réchaud.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Tu me disais toujours, voilà toute ma vie revenue, il faut me traiter en convalescente, je vais renaître, et en disant cela, tu écrivais ton testament.\nMoi, je me disais : voilà ce que je ferai ; je la prendrai avec moi, pour aller dans une prairie ; je lui montrerai les feuilles qui poussent, les fleurs qui s'aiment, le soleil qui échauffe tout dans l'horizon plein de vie ; je l'assoirai sur du jeune chaume, elle écoutera, et elle comprendra bien ce que disent tous ces oiseaux, toutes ces rivières avec les harmonies du monde — elle reconnaîtra tous ces milliers de frères, et moi pour l'un d'entre eux ; elle nous pressera sur son cœur ; elle deviendra blanche comme un lys, et elle prendra racine dans la sève du monde tout-puissant.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Retenez ceci : il n'y a de bon, de vrai, de gai, de triste, d'aimable, de variable, de désirable, de potable, de chantable, de célébrable, d'idolâtrable, que le delta qui existe depuis la ceinture d'une femme jusqu'à ses jarretières. La […] motte est faite en triangle, il est clair que c'est le symbole de la divinité. On dit que Mme Sand est à Baden. Si vous la voyez, dites-lui que je l'aime de tout mon cœur, que c'est encore la femme la plus femme que j'aie jamais connue, et que je donnerais toutes mes maîtresses au diable pour être cocu de sa façon.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Est-ce que ta haute destinée te faisait peur ? Est-ce que l'esprit de Dieu était passé devant toi sous des traits trop sévères ? L'ange de la poésie, qui rayonne à sa droite, s'était penché sur ton berceau pour te baiser au front ; mais tu fus effrayé sans doute de voir si près de toi le géant aux ailes de feu. Tes yeux ne purent soutenir l'éclat de sa face, et tu t'enfuis pour lui échapper. A peine assez fort pour marcher, tu voulus courir à travers les dangers de la vie, embrassant avec ardeur toutes ses réalités et leur demandant asile et protection contre les terreurs de ta vision sublime et terrible. Comme Jacob, tu luttas contre elle, et comme lui tu fus vaincu. Au milieu des fougueux plaisirs où tu cherchais vainement ton refuge, l'esprit mystérieux vint te réclamer et te saisir. Il fallait que tu fusses poète, tu l'as été en dépit de toi-même.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Musset est de ceux qui d'emblée, passent les bornes et plaident coupable. Race de Caïn, et pas seulement par convention byronienne. Un cannibale, au fond, cet éphèbe dandy, cet enfant perdu, qui ne va pas tarder à s'asseoir au festin, pour finir dévoré par sa légende ? Mais d'abord, et comme elle aussi, un vrai théâtre en liberté à soi tout seul.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Il y avait dans ce jeune talent une connaissance prématurée de la passion humaine, une joute furieuse avec elle. Amour, fléau du monde, exécrable folie, n'avait jamais été étreint plus au vif et, pour ainsi dire, plus au sang. Le poète de dix-neuf ans remuait l'âme dans ses abîmes, il en arrachait la vase impure à une étrange profondeur ; il culbutait du pied le couvercle de la tombe : à lui les femmes en cette vie, et le néant après ! La vieillesse était apostrophée, foulée en maint endroit, secoué par le menton, comme décrépite.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Quel était donc le cœur de ce poète qui avait tant de pitié de la blancheur des marbres ? Poète, il l'était manifestement, même au fort de sa débauche. Dans ses plus mauvais chemins, la vérité rayonnante, l'image inespérée, l'éclat facile et prompt jaillissaient de la poussière de ses pas. Ce que ne donnent ni l'effort, ni l'étude, ni la logique d'un goût attentif et perfectible, il l'atteignait au passage ; il avait dans le style cette vertu d'ascension merveilleuse qui transporte en un clin d'œil là où nul n'arrive en gravissant.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "A relire ainsi bon nombre des pièces et des personnages d'Alfred de Musset, on arriverait à découvrir en cet enfant de génie le contraire de Goethe, de ce Goethe qui se détachait à temps de ses créations, même les plus intimes à l'origine, qui ne pratiquait que jusqu'à un certain point l'œuvre de ses personnages, qui coupait à temps le lien, les abandonnait au monde, en étant déjà lui-même partout ailleurs. Pour Alfred de Musset, la poésie, c'était lui-même, il s'y précipitait à corps perdu ; c'était son âme juvénile, c'était sa chair et son sang qui s'écoulaient; et quand il avait jeté aux autres ces lambeaux, ces membres éblouissants du poète, il gardait encore son lambeau à lui, son cœur saignant, son cœur brûlant et ennuyé ; il avait hâte de condenser et de dévorer les saisons.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Il n'était pas de ceux que la critique console de l'art, qu'un travail littéraire distrait ou occupe et qui sont capables d'étudier, même avec emportement, pour échapper à des passions qui cherchent encore leur proie et qui n'ont plus de sérieux objet. Lui, il n'a su que haïr la vie, du moment, pour parler son langage, qu'elle n'était plus la jeunesse sacrée. Il ne la concevait digne d'être vécue, il ne la supportait qu'entourée et revêtu d'un léger délire.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Les pièces de Musset ont un tremblé spécial. Funambule sur son fil, la barre penche, le funambule s'arrête, la pièce va-t-elle tomber dans le mélodrame ? Non, elle repart, légère. Et, juste à la fin, quand nous nous sommes persuadés que nous aurons bientôt assisté à une comédie légère, voici le drame, comme une flèche. Quelle grâce, vraiment.", Author = "Alfred de Musset" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Alfred_de_Musset", Text = "Musset crée ses proverbes plutôt que d'en prendre d'existants : On ne badine pas avec l'amour, ça n'existait pas avant lui, pas plus qu'Il faut qu'une porte soit ouverte ou fermée. Et c'est très habile, car cela donne au public l'impression de déjà connaître l'œuvre.", Author = "Alfred de Musset" },
        };
    }
}