using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class AntoinedeSaintExupéry
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "La vérité d'hier est morte, celle de demain est encore à bâtir. Aucune synthèse valable n'est entrevue, et chacun d'entre nous ne détient qu'une parcelle de vérité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Il faut allaiter longtemps un enfant avant qu'il exige. Il faut longtemps cultiver un ami avant qu’il réclame son dû d’amitié. Il faut s'être ruiné durant des générations à réparer le vieux château qui croule, pour apprendre à l’aimer.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Du pilote Guillaumet, le dernier ami que j'ai perdu et qui s'est fait abattre en service postal aérien, mon Dieu ! J'ai accepté de porter le deuil. Guillaumet ne changera plus. Il ne sera plus jamais présent, mais il ne sera jamais absent non plus. J'ai sacrifié son couvert à ma table, ce piège inutile, et j'ai fait de lui un véritable ami mort.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Celui qui, cette nuit-ci, hante ma mémoire est âgé de cinquante ans. Il est malade. Et il est juif. Comment survivrait-il à la terreur allemande ? Pour imaginer qu'il respire encore j'ai besoin de le croire ignoré de l'envahisseur, abrité en secret par le beau rempart de silence des paysans de son village.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Cette qualité de la joie n'est-elle pas le fruit le plus précieux de la civilisation qui est nôtre ? Une tyrannie totalitaire pourrait nous satisfaire, elle aussi, dans nos besoins matériels. Mais nous ne sommes pas un bétail à l'engrais.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Je suis si las des polémiques, des exclusives, des fanatismes ! Je puis entrer chez toi sans m'habiller d'un uniforme, sans me soumettre à la récitation d'un Coran, sans renoncer à quoi que ce soit de ma patrie intérieure.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Le disparu si l’on vénère sa mémoire est plus présent et plus puissant que le vivant.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "C'est pourquoi je désire qu'ils épaulent solidement les maîtres couples du navire. Afin de les sauver de génération en génération, car je n'embellirai point un temple si je le recommence à chaque instant.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais n'espère rien de l'homme s'il travaille pour sa propre vie et non pour son éternité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Tu veux qu'ils s'aiment ? Ne leur jette point le grain du pouvoir à partager. Mais que l'un serve l'autre. Et que l'autre serve l'empire. Alors ils s'aimeront de s'épauler l'un l'autre et de bâtir ensemble.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Préparer l'avenir ce n'est que fonder le présent. […] Il n'est jamais que du présent à mettre en ordre. À quoi bon discuter cet héritage. L'avenir, tu n'as point à le prévoir mais à le permettre.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ta pyramide n'a point de sens si elle ne s'achève en Dieu. Car Celui-là se répand sur les hommes après les avoir transfigurés.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Moi qui sais bien […] que la sagesse ce n'est point réponse, mais guérison des vicissitudes du langage […].", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Seule compte la démarche. Car c'est elle qui dure et non le but qui n'est qu'illusion du voyageur quand il marche de crête en crête comme si le but atteint avait un sens.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "J'interdis aux marchands de vanter trop leurs marchandises. Car ils se font vite pédagogues et t'enseignent comme but ce qui n'est par essence qu'un moyen, et te trompant ainsi sur la route à suivre les voilà bientôt qui te dégradent.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Si ton amour n'a point l'espoir d'être reçu, tu dois le taire. Il peut couver en toi s'il est silence. Car il crée une direction dans le monde et toute direction t'augmente qui te permet de t'approcher, de t'éloigner, d'entrer, de sortir, de trouver, de perdre.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ayant découvert qu'il n'est rien qui soit faux pour la simple raison qu'il n'est rien qui soit vrai […]", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Car nous ne nous entendons pas sur la réalité. Et moi je dénomme réalité non ce qui est mesurable dans une balance. Mais ce qui pèse sur moi.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et m'apparaissait peu à peu cette vérité pourtant éclatante que, qui aime le bien, est indulgent au mal.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Connaître une vérité peut-être n'est-ce que la voir en silence.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "C'est en graissant ton fusil avec respect et pour le fusil et pour la graisse, c'est en comptant tes pas sur le chemin de ronde, c'est en saluant ton caporal et pour le salut que tu prépares en toi l'illumination de la sentinelle.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Si je désire fonder en toi la pente vers la mer je décris le navire en marche, les nuits d'étoiles et l'empire que se taille une île dans la mer par le miracle des étoiles.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ta femme te noircit dans ta vie passée, dans tes souhaits, dans tes croyances. Ne sert de rien de lutter contre les griefs. Accorde-lui le bracelet d'émeraude. Ou bien fouette-la.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Je vaux ce que je suis dans chaque instant et le fruit ne naît point qui a négligé quelque étape.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Moi je recrée dans les montagnes les champs de force. Je construis des barrages dans les montagnes pour soutenir les eaux. Je m'oppose ainsi, injuste, aux pentes naturelles. Je rétablis les hiérarchies là où les hommes se rassemblaient comme les eaux.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ils croupissaient dans l'illusion du bonheur qu'ils tiraient de bien possédés. Alors que le bonheur n'est que chaleur des actes et contentement de la création.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Votre armée est semblable à une mer qui ne pèserait point contre sa digue. Vous êtes une pâte sans levain. Une terre sans graine. Une foule sans souhait.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Sentinelle, sentinelle, c'est en marchant le long des remparts dans l'ennui du doute qui vient des nuits chaudes, c'est en écoutant les bruits de la ville quand la ville ne te parle pas, c'est en surveillant les demeures des hommes quand elles sont morne assemblage.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Je regagnai mon wagon. Je me disais : « Ces gens ne souffrent pas de leur sort. Et ce n'est point la charité ici qui me tourmente. Il ne s'agit point de s'attendrir sur une plaie éternellement ouverte. »", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Un homme, dans son grenier, s'il nourrit un désir assez fort, communique de son grenier le feu au monde.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et c'est pourquoi, sans doute, cette guerre prend une forme si terrible : on fusille plus qu'on ne combat. La mort, ici, c'est le lazaret d'isolement.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ah ! Ce départ nocturne sous la pluie est le seul qui réponde à la vérité de cette guerre. Ces homme m'entourent et me regardent, et je lis dans leurs yeux je ne sais quelle gravité un peu triste.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "J'ai bien touché ici la contradiction que je ne saurais point résoudre. Car la grandeur de l'homme n'est pas faite de la seule destinée de l'espèce : Chaque individu est un empire.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Les hommes ne se respectent plus les uns les autres. Huissiers sans âme, ils dispersent au vent un mobilier sans savoir qu'ils anéantissent un royaume...", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais il n'y avait rien là qu'un paquet de boue. Évanouie, la faible dorure qui fait la qualité humaine !", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ne comprenez-vous pas que le don de soi, le risque, la fidélité jusqu'à la mort, voilà des exercices qui ont largement contribué à fonder la noblesse de l'homme ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ne comprenez-vous pas que, quelque part, nous avons fait fausse route ? La termitière humaine est plus riche qu'auparavant, nous disposons de plus de biens et de loisirs, et, cependant, quelque chose d'essentiel nous manque que nous savons mal définir.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et voici que nous découvrons avec surprise qu'il est des conditions mystérieuses qui nous fertilisent. Liés aux autres par un but commun, et qui se situe en dehors de nous, alors seulement nous respirons.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et le simple berger lui même qui veille ses moutons sous les étoiles, s'il prend conscience de son rôle, se découvre plus qu'un berger. Il est une sentinelle.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Si nous tendons vers cette conscience de l’Univers, nous rentrons dans la destinée même de l’homme. Seuls l’ignorent les boutiquiers qui se sont installés en paix sur la rive, et ne voient pas couler le fleuve.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais il est déjà grand ce berger qui se découvre sentinelle.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Quand nous marcherons dans la bonne direction, celle que nous avons prise dès l’origine, en nous éveillant de la glaise, alors seulement nous serons heureux.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Français, réconcilions-nous ! Quand nous nous trouverons en litige, à bord d'un bombardier, contre cinq ou six Messerschmitt, nos litiges anciens nous feront sourire.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "De la tragédie grecque, l'humanité, dans sa décadence, est tombée jusqu'au théatre de M. Louis Verneuil. Siècle de la publicité, du système Bedeau, des régimes totalitaires et des armées sans clairons ni drapeaux ni messe pour les morts.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Il n'y a qu'un problème, un seul, de par le monde. Rendre aux hommes une signification spirituelle. Des inquiétudes spirituelles.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "On ne peut plus. On ne peut plus vivre sans poésie, couleur ni amour. Rien qu'à entendre un chant villageois du XVe siècle, on mesure la pente descendue.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais si je rentre vivant de ce « job nécessaire et ingrat », il ne se posera pour moi qu'un problème : que peut-on, que faut-il dire aux hommes ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais j'ai aussi compris, ce qui m'avait toujours étonné : pourquoi Platon (ou Aristote ?) place le courage au dernier rang des vertus. Ce n'est pas fait de bien beaux sentiments : un peu de rage, un peu de vanité, beaucoup d'entêtement et un plaisir sportif vulgaire.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Au Mans, quand nous étions couchés, quelquefois vous chantiez en bas. Ça nous arrivait comme les échos d'une fête immense. Ça me semblait ainsi.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ma mère, vous vous penchiez sur nous, sur ce départ d'anges et pour que le voyage soit paisible, pour que rien n'agitât nos rêves, vous effaciez du drap ce pli, cette ombre, cette houle...", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "C'est un peu pour Consuelo que je suis rentré, mais c'est par vous, maman, que l'on rentre. Vous si faible, vous saviez-vous à ce point ange gardienne, et forte, et sage, et si pleine de bénédictions, que l'on vous prie, seul, dans la nuit ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "J'ai tellement de chagrin. J'ai infiniment besoin de votre tendresse, Maman chérie, ma petite Maman. Pourquoi faut-il que tout ce que j'aime sur terre soit menacé ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Peu m'importe que Dieu n'existe pas ! Dieu donne à l'homme de la divinité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "La vertu c'est de sauver le patrimoine spirituel français en demeurant conservateur de la bibliothèque de Carpentras.", Author = "Antoine de Saint-Exupéry" },
        };
    }
}