using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class AntoinedeSaintExupéry
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "La vérité d'hier est morte, celle de demain est encore à bâtir. Aucune synthèse valable n'est entrevue, et chacun d'entre nous ne détient qu'une parcelle de vérité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Le disparu si l’on vénère sa mémoire est plus présent et plus puissant que le vivant.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais n'espère rien de l'homme s'il travaille pour sa propre vie et non pour son éternité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Préparer l'avenir ce n'est que fonder le présent. […] Il n'est jamais que du présent à mettre en ordre. À quoi bon discuter cet héritage. L'avenir, tu n'as point à le prévoir mais à le permettre.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ta pyramide n'a point de sens si elle ne s'achève en Dieu. Car Celui-là se répand sur les hommes après les avoir transfigurés.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Moi qui sais bien […] que la sagesse ce n'est point réponse, mais guérison des vicissitudes du langage […].", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Seule compte la démarche. Car c'est elle qui dure et non le but qui n'est qu'illusion du voyageur quand il marche de crête en crête comme si le but atteint avait un sens.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ayant découvert qu'il n'est rien qui soit faux pour la simple raison qu'il n'est rien qui soit vrai […]", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Car nous ne nous entendons pas sur la réalité. Et moi je dénomme réalité non ce qui est mesurable dans une balance. Mais ce qui pèse sur moi.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et m'apparaissait peu à peu cette vérité pourtant éclatante que, qui aime le bien, est indulgent au mal.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Connaître une vérité peut-être n'est-ce que la voir en silence.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Si je désire fonder en toi la pente vers la mer je décris le navire en marche, les nuits d'étoiles et l'empire que se taille une île dans la mer par le miracle des étoiles.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ta femme te noircit dans ta vie passée, dans tes souhaits, dans tes croyances. Ne sert de rien de lutter contre les griefs. Accorde-lui le bracelet d'émeraude. Ou bien fouette-la.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Je vaux ce que je suis dans chaque instant et le fruit ne naît point qui a négligé quelque étape.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ils croupissaient dans l'illusion du bonheur qu'ils tiraient de bien possédés. Alors que le bonheur n'est que chaleur des actes et contentement de la création.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Votre armée est semblable à une mer qui ne pèserait point contre sa digue. Vous êtes une pâte sans levain. Une terre sans graine. Une foule sans souhait.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Un homme, dans son grenier, s'il nourrit un désir assez fort, communique de son grenier le feu au monde.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et c'est pourquoi, sans doute, cette guerre prend une forme si terrible : on fusille plus qu'on ne combat. La mort, ici, c'est le lazaret d'isolement.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ah ! Ce départ nocturne sous la pluie est le seul qui réponde à la vérité de cette guerre. Ces homme m'entourent et me regardent, et je lis dans leurs yeux je ne sais quelle gravité un peu triste.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "J'ai bien touché ici la contradiction que je ne saurais point résoudre. Car la grandeur de l'homme n'est pas faite de la seule destinée de l'espèce : Chaque individu est un empire.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Les hommes ne se respectent plus les uns les autres. Huissiers sans âme, ils dispersent au vent un mobilier sans savoir qu'ils anéantissent un royaume...", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais il n'y avait rien là qu'un paquet de boue. Évanouie, la faible dorure qui fait la qualité humaine !", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ne comprenez-vous pas que le don de soi, le risque, la fidélité jusqu'à la mort, voilà des exercices qui ont largement contribué à fonder la noblesse de l'homme ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Et le simple berger lui même qui veille ses moutons sous les étoiles, s'il prend conscience de son rôle, se découvre plus qu'un berger. Il est une sentinelle.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais il est déjà grand ce berger qui se découvre sentinelle.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Quand nous marcherons dans la bonne direction, celle que nous avons prise dès l’origine, en nous éveillant de la glaise, alors seulement nous serons heureux.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Français, réconcilions-nous ! Quand nous nous trouverons en litige, à bord d'un bombardier, contre cinq ou six Messerschmitt, nos litiges anciens nous feront sourire.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Il n'y a qu'un problème, un seul, de par le monde. Rendre aux hommes une signification spirituelle. Des inquiétudes spirituelles.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "On ne peut plus. On ne peut plus vivre sans poésie, couleur ni amour. Rien qu'à entendre un chant villageois du XVe siècle, on mesure la pente descendue.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Mais si je rentre vivant de ce « job nécessaire et ingrat », il ne se posera pour moi qu'un problème : que peut-on, que faut-il dire aux hommes ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Au Mans, quand nous étions couchés, quelquefois vous chantiez en bas. Ça nous arrivait comme les échos d'une fête immense. Ça me semblait ainsi.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Ma mère, vous vous penchiez sur nous, sur ce départ d'anges et pour que le voyage soit paisible, pour que rien n'agitât nos rêves, vous effaciez du drap ce pli, cette ombre, cette houle...", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "J'ai tellement de chagrin. J'ai infiniment besoin de votre tendresse, Maman chérie, ma petite Maman. Pourquoi faut-il que tout ce que j'aime sur terre soit menacé ?", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "Peu m'importe que Dieu n'existe pas ! Dieu donne à l'homme de la divinité.", Author = "Antoine de Saint-Exupéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Antoine_de_Saint-Exupéry", Text = "La vertu c'est de sauver le patrimoine spirituel français en demeurant conservateur de la bibliothèque de Carpentras.", Author = "Antoine de Saint-Exupéry" },
        };
    }
}