using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class EmmanuelLevinas
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "On conviendra aisément qu’il importe au plus haut point de savoir si l’on n’est pas dupe de la morale.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La lucidité — ouverture de l’esprit sur le vrai — ne consiste-t-elle pas à entrevoir la possibilité permanente de la guerre ?", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Mourir pour l’invisible — voilà la métaphysique. […] Folle prétention à l’invisible alors qu'une expérience aiguë de l’humain enseigne, au vingtième siècle, que les pensées des hommes sont portées par les besoins, lesquels expliquent société et histoire; […] Mais être homme, c'est savoir qu'il en est ainsi. La liberté consiste à savoir que la liberté est en péril.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Être moi, c'est, par-delà toute individuation qu'on peut tenir d'un système de références, avoir l'identité comme, contenu. Le moi, ce n'est pas un être qui reste toujours le même, mais l'être dont l'exister consiste, à s'identifier, à retrouver son identité à travers tout ce qui lui arrive. […] L'identité universelle où l'hétérogène peut être embrassé, a l'ossature d'un sujet, de la première personne. Pensée universelle, est un « je pense »,[…] le moi qui pense s'écoute penser ou s'effraie de ses profondeurs et, à soi, est un autre.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La relation du Même et de l'Autre — ou métaphysique — se joue originellement comme discours, où le Même, ramassé dans son ipséité de « je » — d'étant particulier unique et autochtone — sort de soi.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "On appelle cette mise en question de ma spontanéité par la présence d'Autrui, éthique. L'étrangeté d'Autrui — son irréductibilité à Moi — à mes pensées et à mes possessions, s'accomplit précisément comme une mise en question de ma spontanéité, comme éthique.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Notons la différence entre besoin et Désir. Dans le besoin, je puis mordre sur le réel et me satisfaire, assimiler l’autre. Dans le Désir, pas de morsure sur l’être, pas de satiété, mais avenir sans jalons devant moi.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La familiarité du monde ne résulte pas seulement d’habitudes prises dans ce monde, qui lui enlèvent ses rugosités et qui mesurent l’adaptation du vivant à un monde dont il jouit et dont il se nourrit. La familiarité et l’intimité se produisent comme une douceur qui se répand sur la face des choses.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Le statut même de l’humain implique la fraternité et l’idée du genre humain.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La relation avec autrui peut être recherchée comme intentionnalité irréductible, même si l'on doit finir par y voir la rupture de l'intentionnalité.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "L'existence elle-même, comme par l'effet d'une intentionnalité, est animée d'un sens, du sens ontologique primordial du néant. Il ne dérive pas de ce qu'on peut savoir ''sur'' la destinée de l'homme, ou ''sur'' ses causes, ou ''sur'' ses fins; l'existence dans son événement même d'existence signifie, dans l'angoisse, le néant, comme si le verbe exister avait un complément direct.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Dans le vide absolu, qu'on peut imaginer, d'avant la création — il y a.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Ma première idée était que peut-être l'« étant », le « quelque chose » qu'on peut désigner du doigt, correspond à une maîtrise de l'« il y a » qui effraie dans l'être.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "D'où un tout autre mouvement : pour sortir de l'« il y a », il faut non pas se poser, mais se déposer; faire un acte de déposition, au sens où l'on parle de rois déposés. Cette déposition de la souveraineté par le ''moi'', c'est la relation sociale avec autrui, la relation dés-inter-essée.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "En réalité, le fait d'être est ce qu'il y a de plus privé; l'existence est la seule chose que je ne puisse communiquer; je peux la raconter, mais je ne peux partager mon existence. La solitude apparaît donc ici comme l'isolement qui marque l'événement même d'être. Le social est au-delà de l'ontologie.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La conscience de soi est en même temps la conscience du tout.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "C'est alors la vision panoramique du réel qui est la vérité et qui donne toute sa satisfaction à l'esprit.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Le terme de « transcendance » signifie précisément le fait qu'on ne peut penser Dieu et l'être ensemble. De même, dans la relation interpersonnelle, il ne s'agit pas de penser ensemble moi et l'autre, mais d'être en face. La véritable union ou le véritable ensemble n'est pas un ensemble de synthèse, mais un ensemble de face à face.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "le visage est ce qui nous interdit de tuer. […]Le visage est signification, et signification sans contexte.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Autrui est visage.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La relation interpersonnelle que j'établis avec autrui, je dois l'établir aussi avec les autres hommes; il y a donc nécessité de modérer ce privilège d'autrui; d'où la justice. Celle-ci, exercée par les institutions, qui sont inévitables, doit toujours être contrôlée par la relation interpersonnelle initiale.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La relation à l'Infini n'est pas un savoir, mais un Désir.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Le lien avec autrui ne se noue que comme responsabilité, que celle-ci, d'ailleurs, soit acceptée ou refusée, que l'on sache ou non comment l'assumer, que l'on puisse ou non faire quelque chose de concret pour autrui.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Mais la justice n'a de sens que si elle conserve l'esprit du dés-inter-essement qui anime l'idée de la responsabilité pour l'autre homme. […] La subjectivité, se constituant dans le mouvement même où à elle incombe d'être responsable pour l'autre, va jusqu'à la substitution pour autrui. […] L'humanité dans l'être historique et objectif, la percée même du subjectif, du psychisme humain, dans son originelle vigilance ou dégrisement, c'est l'être qui se défait de sa condition d'être : le dés-inter-essement. […] La condition ontologique se défait, ou est défaite, dans la condition ou l'incondition humaine", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Le visage ''signifie'' l'Infini.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Le témoignage éthique est une révélation qui n'est pas une connaissance.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "La gloire de Dieu, c'est cela l' « autrement qu'être ».", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Je pense le [[prophétisme]] comme un moment de la condition humaine elle-même. Assumer la responsabilité pour autrui est pour tout homme une manière de témoigner de la gloire de l'Infini, et d'être inspiré.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Oui, la vérité éthique est commune. La lecture de la Bible, même si elle est diverse, exprime dans sa diversité ce que chaque personne apporte à la Bible. La condition subjective de la lecture est nécessaire à la lecture du prophétique.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "L'exigence éthique est universelle.", Author = "Emmanuel Levinas" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Emmanuel_Levinas", Text = "Par conséquent, la question importante du sens de l'être n'est pas : pourquoi y a-t-il quelque chose et non rien — question leibnizienne tant commentée par Heidegger — mais : est-ce que je ne tue pas en étant ?", Author = "Emmanuel Levinas" },
        };
    }
}