using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class FrançoisMauriac
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Je n'aime que ce qui se dévore.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "la défaite d'un adolescent vient de ce qu'il se laisse persuader de sa misère.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "elle ne savait pas que l'amour, dans les vies les plus pleines, sait toujours se creuser sa place ; qu'un homme d'État surmené, autour de l'heure où sa maîtresse l'attend, arrête le monde. Cette ignorance l'empêchait de souffrir.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "la contemplation délivre.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "ce qui est inaccessible ne vaut pas qu'on s'y sacrifie.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Ah ! l'importunité de ces êtres, à qui notre cœur ne s'intéresse pas et qui nous ont choisis, et que nous n'avons pas choisis ! – si extérieurs à nous, dont nous ne désirons rien savoir, dont la mort nous serait aussi indifférente que la vie… et pourtant ce sont ceux-là qui remplissent notre existence.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "C'est la grand misère des femmes que rien ne les détourne de l'obscur ennemi qui les ronge.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "On ne pense jamais que ce sont les passions des pères qui le plus souvent les séparent de leurs fils.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Un bouquin bouleverse la vie d'un homme quelquefois, et encore ! ça se dit… mais d'une femme ? Allons donc ! Nous ne sommes jamais troublés profondément que par ce qui vit – que par ce qui est sang et chair. Un bouquin ?", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Au plus brûlant d'une passion, nos gestes d'instinct la dissimulent ; mais lorsque nous avons renoncé à sa joie, que nous acceptons une faim et une soif éternelles, c'est bien le moins, songeons-nous, de ne plus nous exténuer à donner le change.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Au seuil de notre jeunesse, les jeux sont faits, rien ne va plus ; peut-être sont-ils faits depuis l'enfance : telle inclination, enfouie dans notre chair avant qu'elle fût née, a grandi comme nous, s'est combinée avec la pureté de notre adolescence, et, lorsque nous avons atteint l'âge d'homme, a fleuri brusquement sa monstrueuse fleur.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "C’est qu’il ne fut pas donné à tout homme d’avoir été un jeune homme. […] Il en est, parmi ces jeunes êtres, qui meurent, à peine nés.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "À ceci, d’abord, nous reconnaîtrons le jeune homme : l’indétermination. Il est une force vierge qu’aucune spécialité ne confisque : il ne renonce à rien encore ; toutes les routes l’appellent. Voilà le bref espace de temps où nous ne sommes condamnés à l’immolation d’aucune part de nous-mêmes, où Dieu peut-être consent à nous aimer, bien que nous servions deux maîtres — et ce n’est pas assez dire — d’innombrables maîtres. C’est le temps de la débauche et de la sainteté, le temps de la tristesse et de la joie, de la moquerie et de l’admiration, de l’ambition et du sacrifice, de l’avidité, du renoncement… Ce qui s’appelle un homme fait s’obtient au prix de quelles mutilations !", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Nous aimons dans un très jeune homme ce que jamais on ne verra deux fois.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Tous les mouvements sociaux, politiques, religieux ont marqué notre époque dans la mesure où ils ont été des amitiés.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Il n'y a nulle correspondance entre notre déchéance physique et notre cœur qui ne vieillit pas.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Mais la jeunesse n'est pas le temps des arrangements, des compromis ; le jeune homme exige l'absolu. D'où folies et ces demi-folies, ces suicides et demi-suicides : combien, s'ils ne se tuent pas d'un coup, se détruisent lentement ! La drogue est une mort pendant des années savourée.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Notre vie vaut ce qu'elle nous a coûté d'efforts.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Ils ne savent pas ce qu'est la vieillesse. Vous ne pouvez imaginer ce supplice : ne rien avoir eu de la vie et ne rien attendre de la mort. Qu'il n'y ait rien au-delà du monde, qu'il n'existe pas d'explication, que le mot de l'énigme ne nous soit jamais donné…", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "(…) il n'y a pas d'ombre sans réalité ; l'ombre est une réalité.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "A mon âge, le sommeil attire l'attention de la mort, il ne faut pas faire semblant d'être mort. Tant que je resterai debout, il me semble qu'elle ne peut pas venir. Ce que je redoute d'elle, est-ce l'angoisse physique, l'angoisse du dernier hoquet ? Non, c'est parce qu'elle n'existe pas, ce qui peut se traduire par le signe -.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Ce que j'ai pris pour un signe d'attachement à la propriété n'est que l'instinct charnel du paysan, fils de paysan, né de ceux qui depuis des siècles interrogent l'horizon avec angoisse. La rente que je dois toucher chaque mois s'accumulera chez le notaire : je n'ai jamais eu besoin de rien. J'ai été prisonnier pendant toute ma vie d'une passion qui ne me possédait pas. Comme un chien aboie à la lune, j'ai été fasciné par un reflet. Se réveiller à soixante-huit ans ! Renaître avant de mourir !", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Ce qui m'étouffe, ce soir, en même temps que j'écris ces lignes, ce qui fait mal à mon cœur comme s'il allait se rompre, cet amour dont je connais enfin le nom ador…", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Au pays des forêts, on ne voit pas monter les orages. Ils demeurent longtemps dissimulés par les pins; leur souffle seul les trahit, et ils surgissent comme des voleurs. Parfois le front cuivré de l'un d’eux apparaissait au sud, sans que sa fureur éclatât. Le vent plus frais faisait dire aux enfants qu'il avait dû pleuvoir ailleurs.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Mais une angoisse l'attendait, et comment Yves Frontenac en eût-il pressenti l'horreur, à la fenêtre de sa chambre, en cette nuit de septembre humide et douce ? Plus sa poésie rallierait de cœurs, et plus il se sentirait appauvri ; des êtres boiraient de cette eau dont il devait être seul à voir la source se tarir […]. Il attendait tout, il appelait tout, et même la souffrance, mais non cette honte de survivre pendant des années à son inspiration ; d'entretenir par des subterfuges sa gloire.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Quelle folie d’avoir cru que le résultat apparent de nos efforts importe tant soit peu... Ce qui compte, c’est ce pauvre effort lui-même pour maintenir la barre, pour la redresser, — surtout pour la redresser... Et les fruits inconnus, imprévisibles, inimaginables de nos actes se révéleront un jour dans la lumière, ces fruits de rebut, ramassés par terre, que nous n’osions pas offrir...", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "La mort ne nous livre pas seulement aux vers, mais aussi aux hommes, ils rongent une mémoire, ils la décomposent […].", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Et là-bas, au pays des Frontenac et des Péloueyre, au-delà du quartier perdu où les routes finissent, la lune brillait sur les landes pleines d’eau; elle régnait surtout dans cette clairière que les pignadas ménagent a cinq ou six chênes très antiques, énormes, ramassés, fils de la terre et qui laissent aux pins déchirés l'aspiration vers le ciel […]. Hors un sanglot de nocturne, une charrette cahotante, rien n’interrompait la plainte que, depuis l’Océan, les pins se transmettent pieusement dans leurs branches unies.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Le mystère Frontenac échappait à la destruction, car il était un rayon de l'éternel amour réfracté à travers une race. L'impossible union des époux, des frères et des fils serait consommée avant qu'il fût longtemps, et les derniers pins de Bourideys verraient passer, non plus à leurs pieds, dans l'allée qui va au gros chêne, mais très haut et très loin au-dessus de leurs cimes, le groupe éternellement serré de la mère et de ses cinq enfants.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "(…) sous la couche épaisse de nos âmes, notre âme d'enfant demeure, inchangée ; l'âme échappe au temps.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "(…) la mort, ce qui par essence n'est pas …", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Elle avait vécu seule sans se douter de ce qu'est la solitude. On parle de la solitude, mais on ne la connaît pas.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Il ne discerna que peu à peu ce qui restait du visage : l'arête du nez, l'ossature du front et des mâchoires. Mais qu'il était vivant, ce regard dont il lui fallait encore soutenir la fixité intolérable !", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "A ce moment de son existence, il fléchissait sous la pire épreuve qui pût accabler un prêtre : cette certitude que la masse des hommes n'ont pas besoin de lui et que ce n'est pas assez dire qu'ils se moquent du Royaume de Dieu : ils ne se doutent pas de ce qu'il est, et n'ont jamais été touchés par la bonne nouvelle. A leurs yeux, il existe une organisation des rites prévus pour certaines circonstances de la vie et dont le clergé a l'entreprise. Cela ne va pas au-delà.", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "« Aime et fais ce que tu veux ». Qu'y a t-il à ajouter à cette consigne de saint Augustin, ce bougnoule ?", Author = "François Mauriac" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/François_Mauriac", Text = "Dieu, monsieur, se soucie peu de ce que nous écrivons ; mais lorsque c'est bien écrit, il s'en sert.", Author = "François Mauriac" },
        };
    }
}