using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class GeorgesBernanos
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "L'impuissance aime refléter son néant dans la souffrance d'autrui.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Que craindre au monde, sinon la solitude et l'ennui ?", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Et ce chaume croulant, au milieu des belles tuiles vernies, c'est encore un autre mendiant, un autre homme libre.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Dans la haine que les pécheurs se portent les uns aux autres, dans le mépris, ils s’unissent, ils s’embrassent, ils s’agrègent, ils se confondent, ils ne seront plus un jour, aux yeux de l’Éternel, que ce lac de boue toujours gluant sur quoi passe et repasse vainement l’immense marée de l’amour divin, la mer de flammes vivantes et rugissantes qui a fécondé le chaos.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Et qu’est-ce que vous avez fait de l’enfer, vous autres ? Une espèce de prison perpétuelle, analogue aux vôtres, et vous y enfermez sournoisement par avance le gibier humain que vos polices traquent depuis le commencement du monde — les ennemis de la société. Vous voulez bien y joindre les blasphémateurs et les sacrilèges. Quel esprit sensé, quel cœur fier accepterait sans dégoût une telle image de la justice de Dieu ?", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "« Si la vie me déçoit, n’importe ! Je me vengerai, je ferai le mal pour le mal. » — « À ce moment-là, lui dis-je, vous trouverez Dieu. Oh ! je ne m’exprime sans doute pas bien, et vous êtes d’ailleurs un enfant. Mais enfin, je puis vous dire que vous partez en tournant le dos au monde, car le monde n’est pas révolte, il est acceptation, et il est d’abord l’acceptation du mensonge. Jetez-vous donc en avant tant que vous voudrez, il faudra que la muraille cède un jour, et toutes les brèches ouvrent sur le ciel. »", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Je ne crois qu'à ce qui me coûte. Je n'ai rien fait de passable en ce monde qui ne m'ait d'abord paru inutile, inutile jusqu'au ridicule, inutile jusqu'au dégoût.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Je ne suis pas un écrivain. La seule vue d'une feuille de papier blanc me harasse l'âme. L'espèce de recueillement physique que m'impose un tel travail m'est si odieux que je l'évite autant que je puis.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "L'imbécile est d'abord un être d'habitude et de parti pris. Arraché à son milieu il garde, entre ses deux valves étroitement closes, l'eau du lagon qui l'a nourri. Mais la vie moderne ne transporte pas seulement les imbéciles d'un lieu à un autre, elle les brasse avec une sorte de fureur.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "La prière est, en somme, la seule révolte qui se tienne debout.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "comprendre c'est déjà aimer.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "les souvenirs de guerre ressemblent aux souvenirs de l'enfance.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Les dictateurs font de la force le seul instrument de la grandeur.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Pour être un héros, il faut avoir au moins une fois en sa vie senti l'inutilité de l'héroïsme et de quel poids infime pèse l'acte héroïque dans l'immense déroulement des effets et des causes, réconcilié son âme avec l'idée de la lâcheté, bravé par avance la faible, l'impuissante, l'oublieuse réprobation des gens de bien, senti monter jusqu'à son front la chaleur du plus sûr et du plus profond repaire, l'universelle complicité des lâches, toujours béante, avec l'odeur des troupeaux d'hommes. Qui n'a pas une fois désespéré de l'honneur ne sera jamais un héros.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Qui n'est pas sur le plan de l'honneur est au-dessous.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Le diable, voyez-vous, c'est l'ami qui ne reste jamais jusqu'au bout.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "L'homme c'est bien malaisé à définir. Admettons que ça reste un enfant. Gentil et câlin à ses heures, mais plein de vices.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "La haine qu'on se porte à soi-même est probablement celle entre toutes pour laquelle il n'est pas de pardon.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Le berceau est moins profond que la tombe.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "On a dit parfois de l'homme qu'il était un animal religieux. Le système l'a défini une fois pour toute un animal économique, non seulement l'esclave mais l'objet, la matière presque inerte, irresponsable, du déterminisme économique, et sans espoir de s'en affranchir, puisqu'il ne connaît d'autre mobile certain que l'intérêt, le profit. Rivé à lui-même par l'égoïsme, l'individu n'apparaît plus que comme une quantité négligeable, soumise à la loi des grands nombres ; on ne saurait prétendre l'employer que par masses, grâce à la connaissance des lois qui le régissent. Ainsi, le progrès n'est plus dans l'homme, il est dans la technique, dans le perfectionnement des méthodes capables de permettre une utilisation chaque jour plus efficace du matériel humain.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Il ne s’agit pas de savoir si cette liberté rend les hommes heureux, ou si même elle les rend moraux. Il ne s’agit pas de savoir si elle favorise plutôt le mal que le bien, car Dieu est maître du Mal comme du Bien. Il me suffit qu’elle rende l’homme plus homme, plus digne de sa redoutable vocation d’homme, de sa vocation selon la nature, mais aussi de sa vocation surnaturelle, car celui que la Liturgie de la Messe invite à la participation de la Divinité — divinitatis consortes — ne saurait rien renoncer de son risque sublime.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Capitalistes, fascistes, marxistes, tous ces gens là se ressemblent. Les uns nient la liberté, les autres font encore semblant d'y croire, mais qu'ils y croient ou n'y croient pas, cela n'a malheureusement plus beaucoup d'importance, puisqu'ils ne savent plus s'en servir. Hélas ! le monde risque de perdre la liberté, de la perdre irréparablement, faute d'avoir gardé l'habitude de s'en servir… Je voudrais avoir un moment le contrôle de tous les postes de radio de la planète pour dire aux hommes : « Attention ! Prenez garde ! La Liberté est là, sur le bord de la route, mais vous passez devant elle sans tourner la tête. »", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Ils trouvent la liberté belle, ils l’aiment, mais ils sont toujours prêts à lui préférer la servitude qu’ils méprisent, exactement comme ils trompent leur femme avec des gourgandines. Le vice de la servitude va aussi profond dans l’homme que celui de la luxure, et peut-être que les deux ne font qu’un. Peut-être sont-ils une expression différente et conjointe de ce principe de désespoir qui porte l’homme à se dégrader, à s’avilir, comme pour se venger de lui-même, se venger de son âme immortelle.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "La civilisation des machines n'a nullement besoin de notre langue, notre langue est précisément la fleur et le fruit d'une civilisation absolument différente de la civilisation des machines. Il est inutile de déranger Rabelais, Montaigne, Pascal, pour exprimer une conception sommaire de la vie, dont le caractère sommaire fait précisément tout l'efficience. La langue française est une œuvre d'art, et la civilisation des machines n'a besoin pour ses hommes d'affaires, comme pour ses diplomates, que d'un outil, rien davantage.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Obéissance et irresponsabilité, voila les deux Mots Magiques qui ouvriront demain le Paradis de la Civilisation des Machines. La civilisation française, héritière de la civilisation hellénique, a travaillé pendant des siècles pour former des hommes libres, c'est-à-dire pleinement responsables de leurs actes : La France refuse d'entrer dans le paradis des robots.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Méfions-nous de tout ce qui pourrait nous détourner de la prière, méfions-nous même du martyre. La prière est un devoir, le martyre est une récompense. Lorsqu'un grand Roi, devant toute sa cour, fait signe à la servante de venir s'asseoir avec lui sur son trône, ainsi qu'une épouse bien-aimée, il est préférable qu'elle n'en croie d'abord ses yeux ni ses oreilles, et continue à frotter les meubles.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Quand les sages sont au bout de leur sagesse, il convient d'écouter les enfants.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Le malheur, ma fille, n'est pas d'être méprisée, mais de se mépriser soi-même.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Cette simplicité de l'âme, nous consacrons notre vie à l'acquérir, ou à la retrouver si nous l'avons connue, car c'est un don de l'enfance qui le plus souvent ne survit pas à l'enfance… il faut très longtemps souffrir pour y rentrer, comme tout au bout de la nuit on découvre une autre aurore…", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Il n'existe pas de race française. La France est une nation, c'est-à-dire une œuvre humaine, une création de l'homme; notre peuple [...] est composé d'autant d'éléments divers qu'un poème ou une symphonie.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Je ne méprise nullement l'idée de race, je me garderais plus encore de la nier. Le tort du racisme n'est pas d'affirmer l'inégalité des races, aussi évidente que celle des individus, c'est de donner à cette inégalité un caractère absolu, de lui subordonner la morale elle-même, au point de prétendre opposer celle des maîtres à celle des esclaves.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Le pouvoir de la misère ne se juge pas au nombre apparent de misérables, c’est-à-dire au nombre d’hommes qui manquent absolument du nécessaire. Il est possible que la société moderne en finisse avec la pauvreté, ne serait-ce qu’en éliminant à chaque génération les pauvres-nés, les inadaptés, les inadaptables, grâce à une réglementation des naissances et à une stricte sélection. Je ne crois nullement qu’en réduisant le nombre de pauvres on réduise du même coup celui des misérables. Je pense au contraire que le miséricordieux sacerdoce de la pauvreté fut précisément établi en ce monde pour le racheter de la misère, du féroce et contagieux désespoir des misérables. Si nous pouvions disposer de quelque moyen de détecter l’espérance comme le sourcier découvre l’eau souterraine, c’est en approchant des pauvres que nous verrions se tordre entre nos doigts la baguette de coudrier.", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Le pauvre n'est pas un homme qui manque, par état, du nécessaire, c'est un homme qui vit pauvrement, selon la tradition immémoriale de la pauvreté, qui vit au jour le jour, du travail de ses mains, qui mange dans la main de Dieu, selon la vieille expression populaire. Il vit non seulement de l'ouvrage de ses mains, mais aussi de la fraternité des autres pauvres, des mille petites ressources de la pauvreté, du prévu et de l'imprévu. Les pauvres ont le secret de l'espérance…", Author = "Georges Bernanos" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Georges_Bernanos", Text = "Se connaître est la démangeaison des imbéciles.", Author = "Georges Bernanos" },
        };
    }
}