using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class GuydeMaupassant
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Puis, un calme profond, une attente épouvantée et silencieuse avait plané sur la cité. Beaucoup de bourgeois bedonnants, émasculés par le commerce, attendaient anxieusement les vainqueurs, tremblant qu’on ne considérât comme une arme leurs broches à rôtir ou leurs grands couteaux de cuisine.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Mais Cornudet releva brusquement la tête, et parcourant la société d’un luisant et terrible : — « Je vous dis à tous que vous venez de faire une infamie » ! — Il se leva, gagna la porte, répéta encore une fois : « Une infamie ! » et disparut.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Est-ce que nous voyons la cent millième partie de ce qui existe?", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "J’aime ce pays, et j’aime y vivre parce que j’y ai mes racines, ces profondes et délicates racines, qui attachent un homme à la terre où sont nés et morts ses aïeux, qui l’attachent à ce qu’on pense et à ce qu’on mange, aux usages comme aux nourritures, aux locutions locales, aux intonations des paysans, aux odeurs du sol, des villages et de l’air lui-même.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "D’où viennent ces influences mystérieuses qui changent en découragement notre bonheur et notre confiance en détresse ?", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Comme il est profond, ce mystère de l’Invisible !", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Au lieu de conclure sur ces simples mots : « Je ne comprends pas parce que la cause m’échappe », nous imaginons aussitôt des mystères effrayants et des puissances surnaturelles.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "On dirait que l’homme, depuis qu’il pense, a pressenti et redouté un être nouveau, plus fort que lui, son successeur en ce monde, et que, le sentant proche et ne pouvant prévoir la nature de ce maître, il a créé, dans sa terreur, tout le peuple fantastique des êtres occultes, fantômes vagues nés de la peur.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Eh bien... on y voyait comme en plein jour... et je ne me vis pas dans ma glace ! Elle était vide, claire, profonde, pleine de lumière !", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Non… non… sans aucun doute, sans aucun doute… il n’est pas mort… Alors… alors… il va donc falloir que je me tue, moi !", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Le cœur a des mystères qu’aucun raisonnement ne pénètre.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "La vie, voyez-vous, ça n’est jamais si bon ni si mauvais qu’on croit.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "La vie est une côte. Tant qu’on monte, on regarde le sommet, et on se sent heureux ; mais, lorsqu’on arrive en haut, on aperçoit tout d’un coup la descente, et la fin qui est la mort. Ça va lentement quand on monte, mais ça va vite quand on descend.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Une vie ! quelques jours, et puis plus rien ! On naît, on grandit, on est heureux, on attend, puis on meurt. Adieu ! homme ou femme, tu ne reviendras point sur la terre ! Et pourtant chacun porte en soi le désir fiévreux et irréalisable de l’éternité, chacun est une sorte d’univers dans l’univers, et chacun s’anéantit bientôt complètement dans le fumier des germes nouveaux. Les plantes, les bêtes, les hommes, les étoiles, les mondes, tout s’anime, puis meurt pour se transformer. Et jamais un être ne revient, insecte, homme ou planète !", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "les femmes n’espèrent point toujours autre chose que ce qui est !", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "C’était un de ces hommes politiques à plusieurs faces, sans conviction, sans grands moyens, sans audace et sans connaissances sérieuses, avocat de province, joli homme de chef-lieu, gardant un équilibre de finaud entre tous les partis extrêmes, sorte de jésuite républicain et de champignon libéral de nature douteuse, comme il en pousse par centaines sur le fumier populaire du suffrage universel.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "se servir de la religion comme on se sert d’un en-tout-cas. S’il fait beau, c’est une canne ; s’il fait du soleil, c’est une ombrelle ; s’il pleut, c’est un parapluie, et, si on ne sort pas, on le laisse dans l’antichambre.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "les paroles d’amour, qui sont toujours les mêmes, prennent le goût des lèvres dont elles sortent.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Le réaliste, s’il est un artiste, cherchera, non pas à nous montrer la photographie banale de la vie, mais à nous en donner la vision plus complète, plus saisissante, plus probante que la réalité même.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Les grands artistes sont ceux qui imposent à l’humanité leur illusion particulière.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "J’en conclus que les Réalistes de talent devraient s’appeler plutôt des Illusionnistes.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Nos yeux, nos oreilles, notre odorat, notre goût différents créent autant de vérités qu’il y a d’hommes sur la terre.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "La langue française, d’ailleurs, est une eau pure que les écrivains maniérés n’ont jamais pu et ne pourront jamais troubler. Chaque siècle a jeté dans ce courant limpide ses modes, ses archaïsmes prétentieux et ses préciosités, sans que rien surnage de ces tentatives inutiles, de ces efforts impuissants. La nature de cette langue est d’être claire, logique et nerveuse. Elle ne se laisse pas affaiblir, obscurcir ou corrompre.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Les hommes de guerre sont des fléaux du monde. Nous luttons contre la nature, l'ignorance, contre les obstacles de toute sorte, pour rendre moins dure notre misérable vie. Des hommes, des bienfaiteurs, des savants, usent leur existence à travailler à ce qui peut aider, ce qui peut secourir, ce qui peut soulager leurs frères. Ils vont, acharnés, à leur besogne utile, entassant les découvertes, agrandissant l'esprit humain, élargissant la science, donnant chaque jour à l'intelligence une somme de savoir nouveau, donnant chaque jour à leur patrie du bien-être, de l'aisance, de la force. La guerre arrive. En six mois, les généraux ont détruit vingt ans d'efforts, de patience et de génie.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Si les peuples comprenaient, s'ils faisaient justice eux-mêmes des pouvoirs meurtriers, s'ils refusaient de se laisser tuer sans raison, s'ils se servaient de leurs armes contre ceux qui les leur ont données pour massacrer, ce jour-là, la guerre serait morte.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "J’ai quitté Paris et même la France, parce que la tour Eiffel finissait par m’ennuyer trop. Non seulement on la voyait de partout, mais on la trouvait partout, faite de toutes les matières connues, exposée à toutes les vitres, cauchemar inévitable et torturant. Ce n’est pas elle uniquement d’ailleurs qui m’a donné une irrésistible envie de vivre seul pendant quelque temps, mais tout ce qu’on a fait autour d’elle, dedans, dessus, aux environs.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Dès le jour, les rues sont pleines, les trottoirs roulent des foules comme des torrents grossis. Tout cela descend vers l’Exposition, ou en revient, ou y retourne. Sur les chaussées, les voitures se tiennent comme les wagons d’un train sans fin. Pas une n’est libre, pas un cocher ne consent à vous conduire ailleurs qu’à l’Exposition, ou à sa remise quand il va relayer.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "pas un ami qui dîne chez lui ou qui consente à dîner chez vous. Quand on l’invite, il accepte à la condition qu’on banquettera sur la tour Eiffel. C’est plus gai. Et tous, comme par suite d’un mot d’ordre, ils vous y convient ainsi tous les jours de la semaine, soit pour déjeuner, soit pour dîner. Dans cette chaleur, dans cette poussière, dans cette puanteur, dans cette foule de populaire en goguette et en transpiration, dans ces papiers gras traînant et voltigeant partout, dans cette odeur de charcuterie et de vin répandu sur les bancs, dans ces haleines de trois cent mille bouches soufflant le relent de leurs nourritures, dans le coudoiement, dans le frôlement, dans l’emmêlement de toute cette chair échauffée, dans cette sueur confondue de tous les peuples semant leurs puces sur les sièges et par les chemins, je trouvais bien légitime qu’on allât manger une fois ou deux, avec dégoût et curiosité, la cuisine de cantine des gargotiers aériens, mais je jugeais stupéfiant qu’on pût dîner, tous les soirs, dans cette crasse et dans cette cohue, comme le faisait la bonne société, la société délicate, la société d’élite, la société fine et maniérée qui, d’ordinaire, a des nausées devant le peuple qui peine et sent la fatigue humaine.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "N’allez point dans ce port, canotiers-caboteurs qui aimez garder sans tache les voiles blanches de vos petits navires. Savone est gentille pourtant, bien italienne, avec des rues étroites, amusantes, pleines de marchands agités, de fruits étalés par terre, de tomates écarlates, de courges rondes, de raisins noirs ou jaunes et transparents comme s’ils avaient bu de la lumière, de salades vertes épluchées à la hâte et dont les feuilles semées à foison sur les pavés ont l’air d’un envahissement de la ville par les jardins.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "En revenant à bord du yacht j’aperçois tout à coup, le long du quai, dans une balancelle napolitaine, sur une immense table tenant tout le pont, quelque chose d’étrange comme un festin d’assassins. Sanglants, d’un rouge de meurtre, couvrant le bateau entier d’une couleur et, au premier coup d’œil, d’une émotion de tuerie, de massacre, de viande déchiquetée, s’étalent, devant trente matelots aux figures brunes, soixante ou cent quartiers de pastèques pourpres éventrées.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Gênes, de la haute mer. Au fond du golfe, la ville se soulève comme si elle sortait des flots, au pied de la montagne. Le long des deux côtes qui s’arrondissent autour d’elle pour l’enfermer, la protéger et la caresser, dirait-on, quinze petites cités, des voisines, des vassales, des servantes, reflètent et baignent dans l’eau leurs maisons claires.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "On pénètre dans l’avant-port, énorme bassin admirablement abrité où circulent, cherchant pratique, une flotte de remorqueurs, puis, après avoir contourné la jetée Est, c’est le port lui-même, plein d’un peuple de navires, de ces jolis navires du Midi et de l’Orient, aux nuances charmantes, tartanes, balancelles, mahonnes, peints, voilés et mâtés avec une fantaisie imprévue, porteurs de madones bleues et dorées, de saints debout sur la proue et d’animaux bizarres, qui sont aussi des protecteurs sacrés. Toute cette flotte à bonnes vierges et à talismans est alignée le long des quais, tournant vers le centre des bassins leurs nez inégaux et pointus. Puis apparaissent, classés par compagnies, de puissants vapeurs en fer, étroits et hauts, avec des formes colossales et fines. Il y a encore au milieu de ces pèlerins de la mer des navires tout blancs, de grands trois-mâts ou des bricks, vêtus comme les Arabes d’une robe éclatante sur qui glisse le soleil.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "On éprouve à Gênes ce qu’on éprouve à Florence et encore plus à Venise, l’impression d’une très aristocrate cité tombée au pouvoir d’une populace. Ici surgit la pensée des rudes seigneurs qui se battaient ou trafiquaient sur la mer, puis, avec l’argent de leurs conquêtes, de leurs captures ou de leur commerce, se faisaient construire les étonnants palais de marbre dont les rues principales sont encore bordées.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Quand on pénètre dans ces demeures magnifiques, odieusement peinturlurées par les descendants de ces grands citoyens de la plus fière des républiques, et qu’on compare le style, les cours, les jardins, les portiques, les galeries intérieures, toute la décorative et superbe ordonnance, avec l’opulente barbarie des plus beaux hôtels du Paris moderne, avec ces palais de millionnaires qui ne savent toucher qu’à l’argent, qui sont impuissants à concevoir, à désirer une belle chose nouvelle et à la faire naître avec leur or, on comprend alors que la vraie distinction de l’intelligence, que le sens de la beauté rare des moindres formes, de la perfection des proportions et des lignes, ont disparu de notre société démocratisée, mélange de riches financiers sans goût et de parvenus sans traditions.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Entrez dans les vieux palais de Gênes, vous y verrez une succession de cours d’honneur à galeries et à colonnades et d’escaliers de marbre incroyablement beaux, tous différemment dessinés et conçus par de vrais artistes, pour des hommes au regard instruit et difficile. Entrez dans les anciens châteaux de France, vous y trouverez les mêmes efforts vers l’incessante rénovation du style et de l’ornement. Entrez ensuite dans les plus riches demeures du Paris actuel, vous y admirerez de curieux objets anciens soigneusement catalogués, étiquetés, exposés sous verre suivant leur valeur connue, cotée, affirmée par des experts, mais pas une fois vous ne resterez surpris par l’originale et neuve invention des différentes parties de la demeure elle-même.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Quand je relève les yeux sur les rochers du rivage, j’y aperçois des groupes de gamins nus, au corps bruni, étonnés de ce rôdeur. Ils sont innombrables aussi, comme une autre progéniture de la mer, comme une tribu de jeunes tritons nés d’hier qui s’ébattent et grimpent aux rives de granit pour boire un peu l’air de l’espace. On en trouve cachés dans toutes les crevasses, on en aperçoit debout sur les pointes, dessinant dans le ciel italien leurs formes jolies et frêles de statuettes de bronze.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "En vérité, Tunis n’est ni une ville française, ni une ville arabe, c’est une ville juive. C’est un des rares points du monde où le juif semble chez lui comme dans une patrie, où il est le maître presque ostensiblement, où il montre une assurance tranquille, bien qu’un peu tremblante encore. C’est lui surtout qui est intéressant à voir, à observer dans ce labyrinthe de ruelles étroites où circule, s’agite, pullule la population la plus colorée, bigarrée, drapée, pavoisée, miroitante, soyeuse et décorative, de tout ce rivage oriental. Où sommes-nous ? sur une terre arabe ou dans la capitale éblouissante d’Arlequin, d’un Arlequin qui s’est amusé à costumer son peuple avec une fantaisie étourdissante. Il a dû passer par Londres, par Paris, par Saint-Pétersbourg, ce costumier divin qui, revenu plein de dédain des pays du Nord, bariola ses sujets avec un goût sans défaillances et une imagination sans limites. Non seulement il voulut donner à leurs vêtements des formes gracieuses, originales et gaies, mais il employa, pour les nuancer, toutes les teintes créées, composées, rêvées par les plus délicats aquarellistes.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Un de ces souks a un caractère si bizarre, que le souvenir en reste extravagant et persistant comme celui d’un songe. C’est le souk des parfums. En d’étroites cases pareilles, si étroites qu’elles font penser aux cellules d’une ruche, alignés d’un bout à l’autre et sur les deux côtés d’une galerie un peu sombre, des hommes au teint transparent, presque tous jeunes, couverts de vêtements clairs, et assis comme des bouddhas, gardent une rigidité saisissante dans un cadre de longs cierges suspendus, formant autour de leur tête et de leurs épaules un dessin mystique et régulier. Les cierges d’en haut, plus courts, s’arrondissent sur le turban ; d’autres, plus longs viennent aux épaules ; les grands tombent le long des bras. Et, cependant, la forme symétrique de cette étrange décoration varie un peu de boutique en boutique. Les vendeurs, pâles, sans gestes, sans paroles, semblent eux-mêmes des hommes de cire en une chapelle de cire. Autour de leurs genoux, de leurs pieds, à la portée des mains si un acheteur se présente, tous les parfums imaginables sont enfermés en de toutes petites boites, en de toutes petites fioles, en de tout petits sacs.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "La ville arabe d’Alger est pleine d’agitation nocturne. Dès que le soir vient, Tunis est mort. Les petites rues étroites, tortueuses, inégales, semblent les couloirs d’une cité abandonnée, dont on a oublié d’éteindre le gaz, par places.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Nous songions à regagner l’hôtel quand l’agent de police indigène nous proposa de nous conduire tout simplement dans un bouge, dans un lieu d’amour dont il ferait ouvrir la porte d’autorité. Et nous voici encore le suivant à tâtons dans des ruelles noires inoubliables, allumant des allumettes pour ne pas tomber, trébuchant tout de même en des trous, heurtant les maisons de la main et de l’épaule et entendant parfois des voix, des bruits de musique, des rumeurs de fête sauvage sortir des murs, étouffés, comme lointains, effrayants d’assourdissement et de mystère. Nous sommes en plein dans le quartier de la débauche.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Elles chantent en tapant sur la darbouka avec leurs mains rougies par le henné, et les musiciens juifs les accompagnent sur de petites guitares, des tambourins et des flûtes aiguës. Tout le monde écoute, sans parler, sans jamais rire, avec une gravité auguste. Où sommes-nous ? Dans le temple de quelque religion barbare, ou dans une maison publique ? Dans une maison publique ? Oui, nous sommes dans une maison publique, et rien au monde ne m’a donné une sensation plus imprévue, plus franche, plus colorée que l’entrée dans cette longue pièce basse, où ces filles parées dirait-on pour un culte sacré attendent le caprice d’un de ces hommes graves qui semblent murmurer le Coran jusqu’au milieu des débauches. On m’en montre un, assis devant sa minuscule tasse de café, les yeux levés, pleins de recueillement. C’est lui qui a retenu l’idole ; et presque tous les autres sont des invités. Il leur offre des rafraîchissements et de la musique, et la vue de cette belle fille jusqu’à l’heure où il les priera de rentrer chacun chez soi. Et ils s’en iront en le saluant avec des gestes majestueux. Il est beau, cet homme de goût, jeune, grand, avec une peau transparente d’Arabe des villes que rend plus claire la barbe noire, soyeuse et un peu luisante, rare sur les joues.", Author = "Guy de Maupassant" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Guy_de_Maupassant", Text = "Ah ! la surprenante et délicieuse sensation qui se glissa dans mon cœur avec les premières notes si légères, si bizarres, si inconnues, si imprévues, des deux petites voix de ces deux petits tubes poussés dans l’eau. C’était fin, doux, haché, sautillant : des sons qui volaient, qui voletaient l’un après l’autre sans se rejoindre, sans se trouver, sans s’unir jamais ; un chant qui s’évanouissait toujours, qui recommençait toujours, qui passait, qui flottait autour de nous, comme un souffle de l’âme des feuilles, de l’âme des bois, de l’âme des ruisseaux, de l’âme du vent, entré avec ces deux grands bergers des montagnes kabyles dans cette maison publique d’un faubourg de Tunis.", Author = "Guy de Maupassant" },
        };
    }
}