using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class GérarddeNerval
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Plus loin que Louvre est un chemin bordé de pommiers dont j'ai vu bien des fois les fleurs éclater dans la nuit comme des étoiles de la terre.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Vous êtes une nymphe antique qui vous ignorez. D'ailleurs les bois de cette contrée sont aussi beaux que ceux de la campagne romaine. Il y a là-bas des masses de granit non moins sublimes, et une cascade qui tombe du haut des rochers comme celle de Terni. Je n'ai rien vu là-bas que je puisse regretter ici.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Voici les peuplier de l'île, et la tombe de Rousseau, vide de ses cendres. Ô sage ! tu nous avais donné le lait des forts, et nous étions trop faibles pour qu'il pût nous profiter. Nous avons oublié tes leçons que savaient nos pères, et nous avons perdu le sens de ta parole, dernier écho des sagesses antiques. Pourtant ne désespérons pas, et comme tu fis à ton suprême instant, tournons nos yeux vers le soleil !", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Quelquefois j'ai besoin de revoir ces lieux de solitude et de rêverie. J'y relève tristement en moi-même les traces fugitives d'une époque où le naturel était affecté ; je souris parfois en lisant sur le flanc des granits certains vers de Roucher, qui m'avaient paru sublimes, — ou des maximes de bienfaisance au-dessus d'une fontaine ou d'une grotte consacrée à Pan. Les étangs, creusés à si grands frais, étalent en vain leur eau morte que le cygne dédaigne.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Ce fut au printemps de l'année 1835 qu'un vif désir me prit de voir l'Italie. Tous les jours en m'éveillant j'aspirais d'avance l'âpre senteur des maronniers alpins ; le soir, la cascade de Terni, la source écumante du Teverone jaillissaient pour moi seul entre les portants éraillés des coulisses d'un petit théâtre... Une voix délicieuse, comme celle des syrènes, bruissait à mes oreilles, comme si les roseaux de Trasimène eussent tout à coup pris une voix...", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "La chambre où j'étais entré avait quelque chose de mystique par le hasard ou par le choix singulier des objets qu'elle renfermait. Une madone noir couverte d'oripeaux, et dont mon hôtesse était chargée de rajeunir l'antique parure, figurait sur une commode près d'un lit aux rideaux de serge verte ; une figure de sainte Rosalie, couronnée de roses violettes, semblait plus loin protéger le berceau d'un enfant endormi ; les murs, blanchis à la chaux, étaient décorés de vieux tableaux des quatre éléments représentant des divinités mythologiques. Ajoutez à cela un beau désordre d'étoffes brillantes, de fleurs artificielles, de vases étrusques ; des miroirs entourés de clinquant qui reflétaient vivement la lueur de l'unique lame de cuivre, et sur une table un Traité de la divination et des songes qui me fit penser que ma compagne était un peu sorcière ou bohémienne pour le moins.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Ses cheveux épais et longs, terminés en boucles, inondent en flottant ses divines épaules ; une couronne multiforme et multiflore pare sa tête, et la lune argentée brille sur son front ; des deux côtés se tordent des serpents parmi de blonds épis, et sa robe aux reflets indécis passe, selon le mouvement de ses plis, de la blancheur la plus pure au jaune de safran, ou semble emprunter sa rougeur à la flamme ; son manteau, d'un noir foncé, est semé d'étoiles et bordé d'une frange lumineuse ; sa main droite tient le sistre, qui rend un son clair, sa main gauche un vase d'or en forme de gondole.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Le bonheur me rend triste ; il me force à penser au malheur qui le suit toujours de près.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Il est sage d'aimer dans la belle saison de l'âge ; plus sage de n'aimer pas.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Le rêve est une seconde vie.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Rien n'est indifférent, rien n'est impuissant dans l'univers ; un atome peut tout dissoudre, un atome peut tout sauver.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "Il est des gens qui crient très haut qu'ils n'ont jamais voulu se vendre ; c'est peut-être qu'on ne se serait jamais soucié de les acheter.", Author = "Gérard de Nerval" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Gérard_de_Nerval", Text = "La vertu, chez les uns, c'est peur de la justice ; chez beaucoup c'est faiblesse ; chez d'autres, c'est calcul.", Author = "Gérard de Nerval" },
        };
    }
}