using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class HenriBergson
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Or, il n'est pas douteux que nous nous sentions libres, que telle soit notre impression immédiate. À ceux qui soutiennent que ce sentiment est illusoire incombe donc l'obligation de la preuve. Et ils ne prouvent rien de semblable, puisqu'ils ne font qu'étendre arbitrairement aux actions volontaires une loi vérifiée dans des cas où la volonté n'intervient pas.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Que nous dit en effet l'expérience ? Elle nous montre que la vie de l'âme ou, si vous aimez mieux, la vie de la conscience, est liée à la vie du corps, qu'il y a solidarité entre elles, rien de plus. Mais ce point n'a jamais été contesté par personne, et il y a loin de là à soutenir que le cérébral est l'équivalent du mental, qu'on pourrait lire dans un cerveau tout ce qui se passe dans la conscience correspondante.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "En réalité, l'art de l'écrivain consiste surtout à nous faire oublier qu'il emploie des mots. L'harmonie qu'il cherche est une certaine correspondance entre les allées et les venues de son esprit et celles de son discours, correspondance si parfaite que, portées par la phrase, les ondulations de sa pensée se communiquent à la nôtre et qu'alors chacun des mots, pris individuellement, ne comptent plus : il n'y a plus rien que le sens mouvant qui traverse les mots, plus rien que deux esprits qui semblent vibrer directement, sans intermédiaire, à l'unisson l'un de l'autre.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Si vous me demandiez de l'exprimer dans une formule simple, nécessairement grossière, je dirais que le cerveau est un organe de pantomime, et de pantomime seulement. Son rôle est de mimer la vie de l'esprit, de mimer aussi les situations extérieures auxquelles l'esprit doit s'adapter. L'activité cérébrale est à l'activité mentale ce que les mouvements du chef d'orchestre sont à la symphonie. La symphonie dépasse de tous côtés les mouvements qui la scandent ; la vie de l'esprit déborde de même la vie cérébrale.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Or, je crois bien que notre vie intérieure toute entière est quelque chose comme une phrase unique entamée dès le premier éveil de la conscience, phrase semée de virgules, mais nulle part coupée par des points.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Vivre, pour l'esprit, c'est essentiellement se concentrer sur l'acte à accomplir. C'est donc s'insérer dans les choses par l'intermédiaire d'un mécanisme qui extraira de la conscience tout ce qui est utilisable pour l'action, quitte à obscurcir la plus grande partie du reste.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Tel est le rôle du cerveau dans l'opération de la mémoire : il ne sert pas à conserver le passé, mais à le masquer d'abord, puis à en laisser transparaître ce qui est pratiquement utile. Et tel est aussi le rôle du cerveau vis-à-vis de l'esprit en général. Dégageant de l'esprit ce qui est extériorisable en mouvement, insérant l'esprit dans ce cadre moteur, il l'amène à limiter le plus souvent sa vision, mais aussi à rendre son action efficace. c'est dire que l'esprit déborde le cerveau de toutes parts, et que l'activité cérébrale ne répond qu'à une infime partie de l'activité mentale.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "D'où venons-nous ? Que faisons-nous ici-bas ? Où allons-nous ? Si vraiment la philosophie n'avait rien à répondre à ces questions d'un intérêt vital, ou si elle était incapable de les élucider progressivement comme on élucide un programme de biologie ou d'histoire, si elle ne pouvait pas les faire bénéficier d'une expérience de plus en plus approfondie, d'une vision de plus en plus aiguë de la réalité, si elle devait se borner à mettre indéfiniment aux prises ceux qui affirment et ceux qui nient l'immortalité pour des raisons tirées de l'essence hypothétique de l'âme et du corps, ce serait presque le cas de dire, en détournant de son sens le mot de Pascal que toute la philosophie ne vaut pas une heure de peine.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Au fur et à mesure que la réalité se crée, imprévisible et neuve, son image se réfléchit derrière elle dans le passé indéfini; elle se trouve ainsi avoir été, de tout temps, possible; mais c'est à ce moment précis qu'elle commence à l'avoir toujours été, et voilà pourquoi je disais que sa possibilité qui ne précède pas sa réalité, l'aura précédée une fois la réalité apparue. Le possible est donc le mirage du présent dans le passé; et comme nous savons que l'avenir finira par être du présent, comme l'effet du mirage continue sans relâche à se produire, nous nous disons que dans notre présent actuel, qui sera le passé de demain, l'image de demain est déjà contenue quoique nous n'arrivions pas à la saisir. Là est précisément l'illusion.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Il faut agir en homme de pensée et penser en homme d'action.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Au fond de la vraie politesse vous trouverez un sentiment qui est l'amour de l'égalité. Mais il y a bien des manières d'aimer l'égalité et de la comprendre. La pire de toute consiste à ne tenir aucun compte de la supériorité de talent et de valeur morale. C'est une forme de l'injustice, issue de la jalousie, de l'envie, ou d'un inconscient désir de domination. L'égalité que la justice réclame est une égalité de rapport, et par conséquent une proportion, entre le mérite et la récompense. Appelons politesse des manières, si vous voulez, un certain art de témoigner à chacun, par son attitude et ses paroles, l'estime et la considération auxquelles il a droit. Ne dirions-nous pas que cette politesse exprime à sa manière l'amour de l'égalité ?", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "La politesse est donc autre chose qu'un luxe ; ce n'est pas seulement une élégance de la vertu. À la grâce elle joindrait la force, le jour où, se communiquant de proche en proche, elle substituerait partout la discussion à la dispute, amortirait le choc des opinions contraires, et amènerait les citoyens à mieux se connaître et à mieux s'aimer les uns les autres. C'est sur ce conseil, jeunes élèves, que je termine. Dites-vous bien qu'en cultivant votre intelligence, en élargissant votre pensée, en vous exerçant, pour tout dire, à la politesse supérieure de l'esprit, vous travaillez à resserrer ces liens et à fortifier cette union d'où dépendent l'avenir et la grandeur de la Patrie.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "D'une manière générale, la réalité est ordonnée dans l'exacte mesure où elle satisfait notre pensée. L'ordre est donc un certain accord entre le sujet et l'objet. C'est l'esprit se retrouvant dans les choses.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Le comique, c'est du mécanique plaqué sur le vivant.", Author = "Henri Bergson" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Henri_Bergson", Text = "Le rire est une espèce de brimade sociale.", Author = "Henri Bergson" },
        };
    }
}