using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class JeanJacquesRousseau
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Le premier qui, ayant enclos un terrain, s’avisa de dire : Ceci est à moi, et trouva des gens assez simples pour le croire, fut le vrai fondateur de la société civile.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Gardez-vous donc de confondre le nom sacré de l'honneur avec ce préjugé féroce qui met toutes les vertus à la pointe d'une épée, et n'est propre qu'à faire de braves scélérats.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Quels moments ! ah ! pardonne ! j'ose te voir même t'occuper de moi : je vois tes yeux attendris parcourir une de mes lettres ; je lis dans leur douce langueur que c'est à ton amant fortuné que s'adressent les lignes que tu traces ; je vois que c'est de lui que tu parles à ta cousine avec une si tendre émotion.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Mais je le vois, tu me méprises comme un insensé, parce que ma raison s'égare au sein des délices : mes emportements t'effrayent, mon délire te fait pitié, et tu ne sens pas que toute la force humaine ne peut suffire à des félicités sans bornes.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Dieux ! quel ravissant spectacle, ou plutôt quelle extase, de voir deux beautés si touchantes s'embrasser tendrement, le visage de l'une se pencher sur le sein de l'autre, leurs douces larmes se confondre, et baigner ce sein charmant comme la rosée du ciel humecte un lis fraîchement éclos !", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Chacun commença à regarder les autres et à vouloir être regardé soi-même, et l’estime publique eut un prix. Celui qui chantait ou dansait le mieux ; le plus beau, le plus fort, le plus adroit ou le plus éloquent devint le plus considéré.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Je sais qu'on n'aime pas le spectacle de la misère qu'on ne peut soulager, et que le riche même détourne les yeux du pauvre qu'il refuse de secourir ; mais ce n'est pas d'argent seulement qu'ont besoin les infortunés.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "L'impulsion du seul appétit est esclavage, et l'obéissance à la loi qu'on s'est prescrite est liberté.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Les peuples ainsi que les hommes ne sont dociles que dans leur jeunesse, ils deviennent incorrigibles en vieillissant ; quand une fois les coutumes sont établies et les préjugés enracinés, c’est une entreprise dangereuse et vaine de vouloir les réformer.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "La véritable pénitence de l'homme lui est imposée par la nature : s'il endure patiemment tout ce qu'il est contraint d'endurer, il a fait à cet égard tout ce que Dieu lui demande.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Mais au fond, que penses-tu qu'on apprenne dans ces conversations si charmantes ? A juger sainement des choses du monde ? à bien user de la société ? à connaître au moins les gens avec qui l'on vit ? Rien de tout cela.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Il y a ainsi un petit nombre d'hommes et de femmes qui pensent pour tous les autres, et pour lesquels tous les autres parlent et agissent ; et comme chacun songe à son intérêt, personne au bien commun.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Jamais on ne corrompt le peuple, mais souvent on le trompe, et c'est alors seulement qu'il paraît vouloir ce qui est mal.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "J'ai toujours remarqué que les gens faux sont sobres, et la grande réserve de la table annonce assez souvent des mœurs feintes et des âmes doubles.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "L’homme est né libre, et partout il est dans les fers.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Le plus fort n’est jamais assez fort pour être toujours le maître, s’il ne transforme sa force en droit et l'obéissance en devoir.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Convenons donc que force ne fait pas droit, et qu’on n’est obligé d’obéir qu’aux puissances légitimes.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Renoncer à sa liberté, c'est renoncer à sa qualité d'homme.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Quiconque refusera d’obéir à la volonté générale y sera contraint par tout le corps : ce qui ne signifie pas autre chose sinon qu’on le forcera à être libre.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Sans doute il est une justice universelle émanée de la raison seule ; mais cette justice pour être admise entre nous doit être réciproque.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Si l’on recherche en quoi consiste précisément le plus grand bien de tous, qui doit être la fin de tout système de législation, on trouvera qu’il se réduit à ces deux objets principaux, la liberté et l’égalité.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "La loi judaïque toujours subsistante, celle de l’enfant d’Ismaël qui depuis dix siècles régit la moitié du monde, annoncent encore aujourd’hui les grands hommes qui les ont dictées.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Il est pour les Nations comme pour les hommes un temps de maturité qu’il faut attendre avant de les soumettre à des lois ; mais la maturité d’un peuple n’est pas toujours facile à connaître.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Je ne suis pas un ange, il est vrai ; mais j'habiterai leur demeure, j'imiterai leurs exemples : on les fuit quand on ne leur veut pas ressembler.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Il faut que les écrits fait pour les solitaires parlent la langue des solitaires : pour les instruire, il faut qu'ils leur plaisent, qu'ils les intéressent.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Vous avez, vous autres qui brillez dans la capitale, des préjugés dont il faut vous guérir ; vous croyez donner le ton à toute la France, et les trois quarts de la France ne savent pas que vous existez.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Attends, et tu seras guéri. Que demandes-tu davantage ?", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Pour moi je pense que le signe le plus assuré du vrai contentement d'esprit est la vie retirée et domestique, et que ceux qui vont sans cesse chercher leur bonheur chez autrui ne l'ont point chez eux-mêmes.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Si vous songez combien au fond d'un bois on est charmé quelquefois de voir un fruit sauvage et même de s'en rafraîchir, vous comprendrez le plaisir qu'on a de trouver dans ce désert artificiel des fruits excellents et mûrs.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Je ne suis pas un ange, il est vrai ; mais j'habiterai leur demeure, j'imiterai leurs exemples : on les fuit quand on ne leur veut pas ressembler.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Un catholique mourant n'est environné que d'objets qui l'épouvantent, et de cérémonies qui l'enterrent tout vivant.", Author = "Jean-Jacques Rousseau" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean-Jacques_Rousseau", Text = "Ce n’est pas sur les idées d’autrui que j’écris ; c’est sur les miennes. Je ne vois point comme les autres hommes ; il y a longtemps qu’on me l’a reproché.", Author = "Jean-Jacques Rousseau" },
        };
    }
}