using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class JeanGiono
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Il lui prend soudain le doux désir de s'abandonner dans le vent du destin comme une bourrasque qui colle aux reins et emporte.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Un peu de repos ! Du repos, et des seuils chauds pour boire le soleil et fumer la pipe.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "De la peau qui tourne au vent de nuit et bourdonne comme un tambour, des larmes de sang noir pleurent dans l'herbe.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Angèle, je la voyais toute entière, maintenant, toute sortie de la nuit. je la voyais dans ses prolongements de ce qui avait été et dans ses prolongements de ce qui serait. Une femme comme ça, c'était un morceau de terre, le pareil d'un arbre, d'une colline, d'une rivière, d'une montagne. Ça faisait partie du rond ensemble. Ça durerait autant que les étoiles.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Moi, j'ai dans moi Baumugnes tout entier, et c'est lourd, parce que c'est fait de grosse terre qui touche le ciel, et d'arbres d'un droit élan; mais c'est bon, c'est beau, c'est large et net, c'est fait de ciel tout propre, de bon foie gras et d'arbres aiguisés comme un sabre. Baumugnes ! La montagne des muets ; le pays où on ne parle pas comme les hommes.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Les choses de la terre, mon vieux, j'ai tant vécu avec elles, j'ai tant fait ma vie dans l'espace qu'elles laissaient, j'ai tant eu d'amis arbres, le vent s'est tant frotté contre moi que, quand j'ai de la peine, c'est à elles que je pense pour la consolation.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je me souviens de l'atelier de mon père. Je ne peux pas passer devant l’échoppe d'un cordonnier sans croire que mon père est encore vivant, quelque part dans l'au-delà du monde, assis devant une table de fermée, avec son tablier bleu, son tranchet, ses ligneuls, ses alènes, en train de faire des souliers en cuir d'ange pour quelque dieu à mille pieds.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Fils, s'il t'est donné de vivre, tu rencontreras sur ta route des hommes qui sont suivis par des troupeaux de montagnes. Des hommes qui arrivent dans des pays, nus et crus. On remarque à peine que leurs mains ouvertes éclairent l'ombre comme des veilleuses. Quand on le remarque. Et voilà que les montagnes se lèvent et marchent à leur suite. Et voilà que tous les mécaniciens de raison tapent du poing sur leurs tables. Voilà qu'ils crient : « Il y a dix ans que je cherche des formules, dix ans que je noircis du papier, dix ans que j'use des arithmétiques. Dix ans que je cherche le bouton secret ». Et celui-là est arrivé et il a dit tout simplement : « Montagne » et puis la montagne s'est dressée. Où est la justice ? « Elle est là, fiston la justice. L'espérance… »", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Dans toi il n'y a déjà plus d'homme, il n'y a plus que la matière de cent sauterelles neuves, de dix lézards, de trois serpents, d'un beau rectangle d'herbe drue et peut-être le cœur d'un arbre.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "A ce moment, il y avait du lait dans le ciel et la journée s'annonçait belle. Comme nous arrivions à la poterie, la jeune sorcière y arrivait aussi, efflanquée, poudrée de poussière, tassée sur ses mollets maigres par une longue course de nuit. Je compris qu'elle avait couru derrière notre charrette.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "On écorcha l'anguille encore vive et la peau se gonflait au vent. On mit le bardeau sur un gril de fer et, dans un feu de sarment, tout ça se mit à cuire; court-bouillon de fenouil et grillades. La jeune fille arrosait le poisson d'un huile minutieuse.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "C'était une nuit extraordinaire. Il y avait eu du vent, il avait cessé, et les étoiles avaient éclaté comme de l'herbe. Elles étaient en touffes avec des racines d'or, épanouies, enfoncées dans les ténèbres et qui soulevaient des mottes luisantes de nuit. Jourdan ne pouvait pas dormir. Il se tournait, il se retournait. – Il a fait un clair de toute beauté, se disait-il. Il n'avait jamais vu ça. Le ciel tremblait comme un ciel de métal. On ne savait pas de quoi puisque tout était immobile, même le plus petit pompon d'osier. Ça n'était pas le vent. C'était tout simplement le ciel qui descendait jusqu'à toucher la terre, racler les plaines, frapper les montagnes et faire sonner les corridors des forêts. Après, il remontait au fond des hauteurs.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "« Le monde se trompe, dit Bobi. Vous croyez que c'est ce que vous gardez qui vous fait riche. On vous l'a dit. Moi je vous dis que c'est ce que vous donnez qui vous fait riche.»", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "« Vous n'avez d'autre grange que cette grange-là, dit-il en frappant la poitrine. Tout ce que vous entassez hors de votre cœur est perdu.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Pour ceux qui sont nés en captivité, la liberté n'est plus un aliment.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je suis le compagnon en perpétuelle révolte contre ta captivité, qui que tu sois, et si tu n'es pas révolté en toi-même, soit que le travail ait tué toutes tes facultés de révolte, soit que tu aies pris goût à tes vices, je suis révolté pour toi malgré tout pour t'obliger à l'être.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Et voilà les anciennes méthodes avec lesquelles la grande communauté des hommes a d'abord vécu, […] voilà ces anciens gestes qui faisaient si bien dans le monde. Les voilà revenus. Ils sont toujours pleins de la même force — peut-être plus grande encore. Ils sont toujours faits par des hommes et femmes têtus — peut-être encore plus têtus parce que du temps a passé — têtus et plus durs, et plus limpides que ce qu'on croyait, car le temps a passé sans toucher leur pureté. Et voilà que ces gestes arrivent à un moment où nous avons tous besoin de nous sauver si nous voulons vivre. C'est pourquoi je dis : c'est grave, avec un grand bonheur qui presque m'étouffe et me fait redevenir moi-même l'homme premier, le paysan, si bien que je ne pense plus comme avant mais lourdement pour essayer d'éclaircir par la bonne méthode. Parce que Mme Bertrand a pris la levure, de la farine, de l'eau, et qu'elle a fait du pain, non pas pour le vendre, mais pour le manger.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Ainsi, les hommes et les femmes restent sous l'auvent du four, cet auvent qui, lui aussi, a exigé une soigneuse orientation du tout le temple : c'est là qu'on pose sur des tréteaux les longues « mannes » pleines de pâtes, c'est de là qu'on enfourne les pains, c'est là qu'on passe le temps en attendant que le pain cuise. Le dos au four, la face vers les champs où dort la buée d'automne ; les nuages ont effacé les montagnes et égalisé le pays ; pour chaque objet de la terre on peut avoir cent pensées toutes différentes avant de se dire : c'est un arbre, c'est la maison de Jean Laine, c'est le chêne ou c'est l'ormeau car, le chêne, l'ormeau, la maison, l'arbre, tout le pays est dans la brume ; on a chaud, on a le temps, on est tranquille, puisqu'un beau travail se fait paisiblement tout seul à cet endroit même : on a le temps de s'occuper de soi-même et de rêver. Joie magnifique des travaux naturels où jamais rien n'est esclavage, où tout est à la mesure de l'homme, lui laissant son temps (ce temps qui est l'habitation de Dieu).", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "L’extraordinaire de notre condition d'homme n'est pas cette intelligence que nous nous sommes composée nous-mêmes, que nous dirigeons comme un rayon à notre gré, croyons-nous (car toujours l'inconnu la réfracte). L'extraordinaire est notre puissance de mélange, cette partie divine de nous-mêmes, toujours insoumise, et qui fait de nous l'expression du monde.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Nous vivons en des temps d'impureté et de désespérance si grandes qu'on a cru parfois que nous avions atteint les temps d'absinthe marqués par les prophètes. Vous autres, séparés de ces temps par l'absence d'illogiques désirs, maîtres d'un travail qui suffit à entretenir l'admirable pauvreté, vous ne pouvez vous imaginer la misère morale des meilleurs d'entre-nous, la misère physique d'un peuple soumis à des lois arbitraires.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Car la richesse de l'homme est dans son cœur. C'est dans son cœur qu'il est le roi du monde. Vivre n'exige pas la possession de tant de choses.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Nous sommes dans l'extrême multiplication des générations que la technique industrielle a entassées dans les villes.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Car, qui envisage le gain doit envisager la perte. Ça n'est pas marqué dans le prospectus mais si vous réclamez après on vous dira : « Voyons, ça allait de soi. On avait pensé qu’il était inutile de vous le dire ; c’est si naturel ! »", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Il ne suffit pas d’être pacifiste, même si c’est du fond du cœur et dans une farouche sincérité ; il faut que ce pacifisme soit la philosophie directrice de tous les actes de votre vie.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Dans les temps modernes, l’humble sagesse est la pensée la plus révolutionnaire du monde.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je suis né à Manosque et je n'en suis jamais parti. Le charme de ce pays ne s'épuise pas. Quand je dis Manosque, je ne veux pas dire strictement la ville, mais tout ce théâtre de collines et de vallées où elle est assise, où elle vit, cette architecture de terres ou elle a pris ses habitudes. Pour un voyage aussi court que celui d'ici à Marseille, quand je rentre, je retrouve sur le quai de ma gare cet air vif des Basses-Alpes, et, avec lui, mon pays, comme revenant d'un dépaysement extraordinaire. C'est que l'air d'ici a un goût particulier.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Celui qui ne connaît pas Manosque et y arrive pour la première fois peut être enchanté, quoique, convenons-en, la ville elle-même a beaucoup perdu de son caractère et de sa beauté, mais celui qui a tous ses souvenirs faits avec les territoires qui ont organisé cette ville entend ou goûte, dans la grondante profondeur de la nuit, dans une qualité de l'air qu'il respire, la vie magique des vastes espaces.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Voilà ce qui a fait Manosque. Qu'on la veuille ronde, triangulaire ou carrée, une ville a ses raisons qui ignore les raisons diverses, et elle a la forme qui lui plaît. Qu'on la taille, qu'on la pousse, qu'on lui greffe je ne sais quoi, qu'on la peigne, qu'on l’étrille, qu'on la pomponne et qu'on la brosse, elle a une âme qui ne s'en soucie pas et avec laquelle elle fait sa vie. Qu'on la déguise et qu'on la farde, si elle parle, c'est avec la voix de son âme qu'on ne change pas.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "C'était la ''pauvre'' Manosque, semblable, dans ses murs, à une couronne de roi. Ces rues mal pavées ne parlaient pas de comptes en banque. C'était une ville de couvent, une ville de jardin intérieur, de cours, de puits, de magnifiques fontaines. Je ne peux guère oublier ces décors ou, pour la première fois, j'ai lu Shakespeare et Calderón. On s'éclairait au pétrole. Nous n'avons eu chez moi l'électricité qu'en 1919. Ce fut la surprise que ma mère me réservait pour fêter mon retour de la guerre. J'avoue que c'était pratique. J'avoue que maintenant, en cas de panne de secteur, je retourne volontiers à la lampe de pétrole.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "En cinquante et quelques années, Manosque a changé. En bien, en mal, il ne m'appartient pas de le dire : je ne suis pas administrateur, et ce que je vous donne ici, c'est le point de vue de Sirius. D'autant qu'elle a changé cinquante fois, et que personne n'est responsable ni du bien ni du mal : ce sont les temps qui ont changé. Mais l’âme est restée la même, car les terres sauvages qui sont à peine à quelques kilomètres d'ici n'ont pas changé. On n’y peut pas innover ; on est obligé d'y vivre avec les vieux moyens, ce que j'appelle virgule moi, ''les jeunes moyens de vivre''. Au travers de tout ce que vous allez voir dans Manosque, chercher son âme, c'est un travail qui vous paiera.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je pris par les champs. C’était le crépuscule le plus clair du monde. Le vent était de noroît et d’une violence royale : un mistral bien établi dans son septième jour, glacé, tranchant, et dont les coups allumaient dans mes yeux des lueurs vermeilles. Le ciel était vert d’un bord à l’autre, les premières étoiles s’allumaient dans un air si pur qu’elles semblaient nouvelles.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "A peine sortis de la cour de l’auberge, le vent nous enveloppa. Nous étions encore protégés par le massif de la Sainte-Victoire, mais le ciel grondait et étincelait comme il n’est pas permis à un ciel chrétien. Il y avait mille fois plus d’étoiles qu’à l’ordinaire, et la voix de l’univers n’était certainement pas celle de l’enfant de la crèche.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Rentré à Aubagne, je repris mon cheval. Il faisait une nuit d’été somptueuse ; dans les vallons frais, des rossignols attardés multipliaient les étoiles. J’aime ce chant qui est comme un silence et ce fourmillement de lumière qui est la nuit. La route montait. J’allais au pas. A y réfléchir, Costa avait disparu vers minuit, je n’avais plus revu le « bon vieillard » : les hostilités avaient dû s’engager ; étions-nous gagnants ou perdants ? Restait aussi à définir le regard qu’avait eu la marquise en dansant avec moi. Je l’ai dit : son habilité la rendait semblable à du vent. Qui peut se flatter de tenir le vent dans ses bras ? Son regard n’était pas un regard de victoire mais un regard intelligent. C’est autre chose ; et qui ne m’apportait pas la paix dans ces vallons sonores.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "J’avais l’habitude de ces détrousseurs de grands chemins : ils ne sont pas courageux ; s’ils étaient courageux, ils travailleraient.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je venais de m’apercevoir que tout le pays était truqué. Les fermes n’étaient plus des fermes, les bois n’étaient plus des bois, les routes n’étaient plus des routes, les enfants n’étaient plus des enfants, dès qu’on mettait le pied dans ce pays, on tombait dans un appareil à tuer et à dévaliser. Il devait même fonctionner automatiquement, à la façon d’un estomac qui digère tout ce qui tombe dans sa panse ; en tout cas, qui s’attaque à tout ce qui tombe dans sa panse, car je n’avais pas du tout envie d’être digéré.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Je crois à la vertu de l’homme à cheval, mais il faut qu’il reste muet. S’il prononce un mot, c’est comme s’il mettait pied à terre.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Mais j’ai sur l’avenir du soldat des idées personnelles. Ce qui l’attend de mieux à mon avis, c’est la mort. Brigou avait cherché et trouvé. Il ne me restait qu’à faire de même. Ce n’est pas que je sois un héros. Je ne les aime guère et je m’arrange fort bien de la vie ordinaire. Mais le travail bien fait est encore ce que j’ai de mieux pour me distraire.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "J’étais seul. Le calme absolu qui précède les lourdes chutes de neige m’environnait étroitement. Aussi loin que mes yeux pouvaient voir, j’apercevais autour de moi des landes désertes dont l’aspect renouvelé par la neige m’était parfaitement étranger. Les lointains étaient de ce bleu sombre un peu funèbre que prend la mer sur de grands fonds.", Author = "Jean Giono" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Jean_Giono", Text = "Quand la solitude a ce visage, mon âme est en paix. Pour si paradoxal que soit mon sentiment, étant donné mon état, je déteste la loi. Je n’ai d’appétit que pour les lois qui sortent en éclair du sein même des événements. Il serait trop long d’expliquer à la suite de quelles expériences j’en suis arrivé à construire mon bonheur avec ces matériaux.", Author = "Jean Giono" },
        };
    }
}