using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class JosephJoubert
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il est impossible que Voltaire contente, et impossible qu’il ne plaise pas.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Quand mes amis sont borgnes, je les regarde de profil.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Nous voyons tout à travers nous-mêmes. Nous sommes un milieu toujours interposé entre les choses et nous.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il y a, dans les langues, quelque chose de fatidique et d’inspiré.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Chaque esprit a sa lie.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il est des esprits dont on peut dire : il y fait clair, et d’autres, seulement : il y fait chaud.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il est des esprits tellement chauds que leurs pensées s’exhalent en fumée et se consument en eux dès le moment qu’elles s’y forment.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les passions ne sont que nature ; c’est le non repentir qui est corruption.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les hommes trouvent des motifs de défiance dans leur ignorance et dans leurs vices, et des motifs de confiance dans leurs lumières et leurs vertus. La défiance est le partage des aveugles.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il entre dans la composition de tout bonheur l’idée de l’avoir mérité.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les orgueilleux me semblent avoir, comme les nains, la taille d’un enfant et la contenance d’un homme.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les cadets sont en général les plus beaux ; leur moulage est plus net et plus sûr.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "On est dispensé d’être instrument dans la société, quand on y est modèle.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Le but de la dispute ou de la discussion ne doit pas être la victoire, mais l’amélioration.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il faut savoir entrer dans les idées des autres et savoir en sortir, comme il faut savoir sortir des siennes et y rentrer.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il vaut mieux remuer une question, sans la décider, que la décider, sans la remuer.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La médisance est le soulagement de la malignité.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Ne coupez pas ce que vous pouvez dénouer.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Nos haines et nos amours, nos colères et notre douceur, notre force et notre faiblesse, notre paresse et notre activité, la morale a tout cela à diriger.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Chacun ne peut voir qu’à sa lampe ; mais il peut marcher ou agir à la lumière d’autrui.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Ce qu’il y a de pire dans l’erreur, ce n’est pas ce qu’elle a de faux, mais ce qu’elle a de volontaire, d’aveugle et de passionné.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Ceux qui ne se rétractent jamais s’aiment plus que la vérité.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Ne confondez pas ce qui est spirituel avec ce qui est abstrait, et souvenez-vous que la philosophie a une muse, et ne doit pas être une simple officine à raisonnement.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La métaphysique est bonne pour ceux qui s’égarent dans les régions supérieures ; ceux qui ne quittent pas la terre n’en ont pas besoin : la morale leur en tient lieu.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Défiez-vous, dans les livres métaphysiques, des mots qui n’ont pas pu être introduits dans le monde, et ne sont propres qu’à former une langue à part.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il y a, pendant la pluie, une certaine obscurité qui allonge tous les objets.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les rochers sont l’excuse et l’ornement de la stérilité.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Le châtiment des mauvais princes est d’être crus pires qu’ils ne sont.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il n’y a pas de peuple au monde qui fasse le mal avec aussi peu de dignité que nous. Notre cupidité n’a que de l’étourderie, et nos apprêts de ruse ne sont qu’une fanfaronnade.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "C’est de l’Angleterre que sont sorties, comme des brouillards, les idées métaphysiques et politiques qui ont tout obscurci.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Nous vivons dans un siècle où les idées superflues surabondent, et qui n’a pas les idées nécessaires.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les esprits propres à gouverner, non-seulement les grands états, mais même leur propre maison, ne se rencontrent presque plus. Aucun temps ne les vit si rares.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il n’y a plus aujourd’hui d’inimitiés irréconciliables, parce qu’il n’y a plus de sentiments désintéressés : c’est un bien né d’un mal.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Un excès en amène un autre. à cette opinion : tout accusé est innocent, succéda bientôt celle-ci : tout accusateur est vertueux.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les enfants ont plus besoin de modèles que de critiques.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Un bon approbateur est aussi nécessaire qu’un bon correcteur.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Le mot sage dit à un enfant, est un mot qu’il comprend toujours, et qu’on ne lui explique jamais.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Le soin du corps et l’apprentissage des arts, la négligence de l’esprit et l’ignorance des devoirs, sont les caractères de l’éducation nouvelle.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il faut apprendre aux enfants le terme propre, et leur laisser trouver le terme figuré.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Enseigner, c’est apprendre deux fois.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Loin de reléguer les arts dans la classe des superfluités utiles, il faut les mettre au nombre des biens les plus précieux et les plus importants de la société humaine.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il y a dans l’art beaucoup de beautés qui ne deviennent naturelles qu’à force d’art.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Dans une œuvre de l’art, quelle qu’elle soit, la symétrie apparente ou cachée est le fondement visible ou secret du plaisir que nous éprouvons.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "L’adolescence de l’art est élégante, sa virilité pompeuse, et sa vieillesse riche, mais surchargée d’ornements qui en dissimulent le dépérissement.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Chez eux [les Anciens], la difformité offrait à la pensée une image invisible de la beauté absente.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Un crucifiement devrait à la fois représenter la mort d’un homme et la vie d’un dieu.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Tout bruit modulé n’est pas un chant, et toutes les voix qui exécutent de beaux airs ne chantent pas.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La mélodie consiste en une certaine fluidité de sons coulants et doux comme le miel d’où elle a tiré son nom.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Dans le style poétique, chaque mot retentit comme le son d’une lyre bien montée, et laisse toujours après lui un grand nombre d’ondulations.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les mots s’illuminent, quand le doigt du poëte y fait passer son phosphore.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "On enrichit les langues en les fouillant. Il faut les traiter comme les champs : pour les rendre fécondes, quand elles ne sont plus nouvelles, il faut les remuer à de grandes profondeurs.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Nous devons reconnaître, pour maîtres des mots, ceux qui savent en abuser, et ceux qui savent en user ; mais ceux-ci sont les rois des langues, et ceux-là en sont les tyrans.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Dans ses ouvrages [Racine], tout est de choix, et rien n’est de nécessité. C’est là ce qui constitue son excellence.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il y a des pensées lumineuses par elles-mêmes ; il en est d’autres qui ne brillent que par le lieu qu’elles occupent : on ne saurait les déplacer, sans les éteindre.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Quand on écrit avec facilité, on croit toujours avoir plus de talent qu’on n’en a. Pour bien écrire, il faut une facilité naturelle et une difficulté acquise.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Quand un ouvrage sent la lime, c’est qu’il n’est pas assez poli ; s’il sent l’huile, c’est qu’on a trop peu veillé.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Trois choses sont nécessaires pour faire un bon livre : le talent, l’art et le métier, c’est-à-dire, la nature, l’industrie et l’habitude.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La critique sans bonté trouble le goût et empoisonne les saveurs.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La critique est un exercice méthodique du discernement.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "La connaissance des esprits est le charme de la critique ; le maintien des bonnes règles n’en est que le métier et la dernière utilité.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les critiques de profession ne sauraient distinguer et apprécier ni les diamants bruts, ni l’or en barres. Ils sont marchands, et ne connaissent, en littérature, que les monnaies qui ont cours.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "L’exception est de l’art aussi bien que la règle. L’une en défend et l’autre en étend le domaine.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Les livres qu’on se propose de relire dans l’âge mûr sont assez semblables aux lieux où l’on voudrait vieillir.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il faut se faire un lointain, se créer une perspective, se choisir un point de vue, quand on veut juger d’un ouvrage, même d’un ouvrage d’esprit, d’un mot, d’un livre, d’un discours.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Platon trouva la philosophie faite de brique, et la fit d’or.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Dans Platon, l’esprit de poésie anime les langueurs de la dialectique.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Dans le style de Bossuet, la franchise et la bonhomie gauloises se font sentir avec grandeur. Il est pompeux et sublime, populaire et presque naïf.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Fénelon laisse plus souvent tomber sa pensée qu’il ne la termine. Rien en lui n’est assez moulé.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "De Saci a rasé, poudré, frisé la bible ; mais au moins il ne l’a pas fardée.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Il est impossible que Voltaire contente, et impossible qu’il ne plaise pas.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Buffon a du génie pour l’ensemble, et de l’esprit pour les détails. Mais il y a en lui une emphase cachée, un compas toujours trop ouvert.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Condorcet, il est vrai, ne dit que des choses communes ; mais il a l’air de ne les dire qu’après y avoir bien pensé, et c’est là ce qui le distingue.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Racine est le Virgile des ignorants.", Author = "Joseph Joubert" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Joseph_Joubert", Text = "Molière est comique de sang-froid ; il fait rire et ne rit pas ; c’est là ce qui constitue son excellence.", Author = "Joseph Joubert" },
        };
    }
}