using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class LouisFerdinandCéline
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Je sentais de la vie qu’il en restait encore beaucoup en dedans, qui se défendait pour ainsi dire. J’aurais jamais cru ça possible si on m’avait raconté. Je marchais même pas trop mal à présent, enfin deux cent mètres à chaque coup. C’était abominable partout comme souffrance, du bas du genou au dedans de la tête. L’oreille c’était la bouillie sonore à part ça, les choses n’étaient pas tout à fait les mêmes ni plus comme avant. Elles avaient l’air en mastic, les arbres pas fixés du tout, la route sous mes godasses faisait des montées et des petites descentes. j’avais plus rien sur moi que ma tunique et de la pluie. Toujours personne. Ma torture de tête je l’entendais bien fort dans la campagne si grande et si vide.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Y avait bien encore quatre heures de marche à cloche-pied comme on allait, à travers les sentiers et surtout les champs. Je voyais plus très clair mais je voyais rouge par dessus. Je m’étais divisé en parties tout le corps. La partie mouillée, la partie qu’était saoule, la partie du bras qu’était atroce, la partie de l’oreille qu’était abominable, la partie de l’amitié pour l’anglais qu’était bien consolante, la partie du genou qui s’en barrait comme au hasard, la partie du passé déjà qui cherchait, je m’en souviens bien, à s’accrocher au présent et qui pouvait plus — et puis alors l’avenir qui me faisait plus peur que tout le reste, enfin une drôle de partie qui voulait par dessus les autres me raconter une histoire. C’était plus même du malheur qu’on peut appeler ça, c’était drôle.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Les deux jetées sont devenues toutes minuscules au-dessus des mousses cavaleuses, pincées contre leur petit phare. La ville s’est ratatinée derrière. Elle a fondu dans la mer aussi. Et tout a basculé dans le décor des nuages et l’énorme épaule du large. C'est fini cette saloperie, elle avait tout son fumier de paysage la terre de France, enfoui ses millions d’assassins purulents, ses bosquets, ses charognes, ses villes multichiots et ses fils infinis de frelons myriamerdes. Y en avait plus, la mer avait tout pris, tout recouvert. Vive la mer !", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Si tu savais Ferdinand combien certains martyrs m'inspirent d'inquiétude et de doutes. Dans une révolution le zèle des provocateurs est plus utile que la générosité des militants, les provocateurs savent ce qu’ils font, les militants l’ignorent.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "La consolation d’avoir trouvé Yugenbitz et la route et la manière qu’il m’avait donné l’espoir de comprendre son beau boulot, ça m’avait grisé je l’admets. Je suis un peu trop enthousiaste pour les choses de l’esprit. J’aurais voulu je crois guérir toutes les maladies des hommes, qu’ils souffrent plus jamais les charognes. On est étrange, si on l’avouait. Bien.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Au fond, ça me transformait la mentalité aussi moi, ce boulot-là. J’aimais ça moi me trouver là où tout devient sensible. C’est là à Tabard Street que je m’ai rendu compte bien profondément. J’ai jamais voulu depuis aller ailleurs qu’au bord de l’âme. Et pourtant on m’a offert bien des occasions. C’est marrant au fond. C’est comme une petite maison dans la campagne, les âmes, j’y vais chaque fois que je peux. Je peux plus aller ailleurs. C’est peut-être pas très bien.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Ce qui m’angoisse, et pour toujours je crois, c’est la façon qu’un petit enfant cesse de jouer pour s’en aller tout de suite, si vite, c’est presque rien à trépasser, le temps de lever un deux trois son petit pinceau, de rire bien encore deux ou trois fois, quatre, et puis voilà. Cette façon de n’être entré dans nos ombres que pour y porter un petit peu de lumière, comme un papillon entre au soir au jardin et s’en va devant la nuit. Vingt ans sont passés depuis, cependant bien des choses encore, des biens étranges et biens lourdes, et petit Peter qu’est toujours là, pour un dixième, pour un petit soupir.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "C’est bon de parler de progrès. Ça fait des beaux télégrammes, des articles qu’on lit avec bien du plaisir. Au fond c’est comme l’Armée du Salut les mecs du progrès. Ça chante, et ça passe le temps. C’est des âmes un peu fainéantes.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "On a sa poésie quand même, du moment qu’on vit encore. La mienne elle est forte. Elle est plus violente que la mort en somme. J’ai toujours été violé par elle au nom d’une connerie quelconque, chaque fois que je voulais terminer la chose. C’est pas tant que j’étais lâche, mais j’étais surtout sensible aux petites attentions. Je me disais que tout allait changer, la nature des hommes, d’un moment à l’autre. On sait pas à vingt ans que rien ne change. On a peur de rater la grande représentation qui va commencer, avec un triomphe sûrement tout au bout. On se croit tombé dans les moments d’un grand miracle.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "J’ai repensé en voyant le square si joliment fleuri en face moi, à tous les amis qu’étaient là-bas, si violent alors j’ai pensé à eux que j’y tenais plus. C’est comme ça la poésie, de la torture pire que la mort quand ça s’y met. Je reste pas en place, je fais un petit paquet des quatre chaussettes, de mes quatre chemises, mon savon. Je ficelle. Je dévale l’escalier, je suis dans la rue. J’ai peur qu’on me retienne, me voilà barré. Je prends la direction. L’autobus Poplar le 416 passe juste au coin. C’est bon ça seulement de retourner d'où qu’on vient.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Hier encore on devait travailler ici, ce matin même peut-être. Un atelier, l’endroit des hommes, devient adorable, irrésistible, dès que les hommes sont partis. Toute la tendresse qu’on n’ose pas vient sans crainte alors prendre leur place. L’Humble, dès qu’il s’en va, n’est ni vivant ni mort, il est tout.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Ah certes vous avez bien raison Paulhan ce « Voyage » est un véritable « Classique ». Mais foutre qui n'en veut ? le me réédite et le douille ? Je meurs de « soif auprès de la fontaine »! Cent là qui se tâtent se touchent et ne se finissent pas!… même la Voilier toute Julotte qu'elle est, flageole au but… Le Fasquelle flanelle… fiasque… et la nénéref ? Ils ne veulent traiter qu'avec ma veuve.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Les Romains trop métissés se sont donné deux capitales, j’en ferais tout autant. Marseille et Paris. L’une pour la France méridionale, latine si l’on veut, byzantine, « Suralgérique », tout aux métis, tout aux zazous […]. L’autre pour la France « nord de la Loire » la France travailleuse et raciste,[…], c’est à tenter. Je crois qu’il est peut-être temps que s’opèrent quelques grandes réformes.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Une prison c'est toujours un endroit assez noble, alors qu'une foire est toujours un endroit très vulgaire. L'homme ne sait pas être distingué en s'amusant. Tandis que, on peut pas dire, une prison, c'est un endroit distingué, les hommes y souffrent, ça vaut la peine. C'est distingué une prison, mais pas un endroit commun, tandis que la foire à Neuilly, enfin quand elle existait, ou la foire du Trône, c'est une chose horripilante de vulgarité.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "Je vois dans ces flots d'invectives, je vois surtout des gens qui boivent, qui mangent, qui dorment, qui font toutes les fonctions humaines qui sont toutes assez vulgaires. Je dirais qu'ils sont lourds, leur esprit est lourd, c'est ça qui me semble surtout. Il n'a jamais cessé d'être lourd. Je l'ai remarqué, j'ai lu… tellement de vers, et particulièrement des vers du XVIIe, des vers soi-disant galants, j'en ai trouvé trois quatre de bons, sur des milliers n'est-ce pas ? Il y a très peu de légèreté chez l'homme, il est lourd, n'est-ce pas ? Et alors maintenant il est extraordinaire de lourdeur, depuis l'auto, l'alcool, l'ambition, la politique, le rendent lourd, encore plus lourd. Ce qui fait qu'il est extrêmement lourd. Nous verrons peut-être un jour une révolte de l'esprit contre… le poids, n'est ce pas ? mais c'est pas pour demain.", Author = "Louis-Ferdinand Céline" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis-Ferdinand_Céline", Text = "D'abord la France n'est pas une race. C'est un pays, une nation. A l'heure actuelle, il y a moins de Français que sous Louis XIV. Quatorze millions au plus sur quarante millions. Le reste, c'est du métis. C'est de l'italote, de l'espagnote, du germinote, etc. Les genres sont tellement mêlés qu'on pourrait retrouver à la rigueur une chose qui ressemblerait à une ethnie au nord de la Loire et encore…", Author = "Louis-Ferdinand Céline" },
        };
    }
}