using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class LouisAragon
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "La parole n’a pas été donnée à l'homme : il l'a prise.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "La nuit de nos villes ne ressemble plus à cette clameur des chiens des ténèbres latines, ni à la chauve-souris du Moyen Age, ni à cette image des douleurs qui est la nuit de la Renaissance. C'est un monstre immense de tôle, percé mille fois de couteaux.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Le sang de la nuit moderne est une lumière chantante. Des tatouages, elle porte des tatouages mobiles sur son sein, la nuit. Elle a des bigoudis d'étincelles, et là où les fusées finissent de mourir, des hommes sont montés sur des astres glissants.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "La nuit a des sifflets et des lacs de lueurs. Elle pend comme un fruit au littoral terrestre, comme un quartier de bœuf au poing d'or des cités. Ce cadavre palpitant a dénoué sa chevelure sur le monde, et dans ce faisceau, le dernier, le fantôme incertain des libertés se réfugie, épuise au bord des rues éclairées par le sens social son désir insensé de plein air et de péril.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Me voici dans l'excellence du destin. L'air est sauvage, et brûle aux yeux. Il faut que l'évènement tourne à ma folie. Je sais contre la raison que ma folie a pour elle un pouvoir irrépressible, qui est au-dessus de l'humain. Ombre ou tourbillon c'est tout comme : la nuit ne reprend pas ses vaisseaux.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "On sait que le propre du génie est de fournir des idées aux crétins une vingtaine d'années plus tard.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "C'est au sens de Virgile que je dis je chante quand je le dis. Arma virumque cano… \"Je chante les armes et les hommes…\" ainsi commence l'Énéide, ainsi devrait commencer toute poésie.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Pourquoi écrivez-vous ? Ma réponse, elle est dans Virgile. Et mon chant ne peut se refuser d'être ; parce qu'il est une arme lui aussi pour l'homme désarmé, parce qu'il est l'homme même, dont la raison d'être est la vie. Je chante parce que l'orage n'est pas assez fort pour couvrir mon chant, et que quoi que demain l'on fasse, on pourra m'ôter cette vie, mais on n'éteindra pas mon chant.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "L'enfant accaparé par les belles images Équarquille les siens moins démesurément Quand tu fais les grands yeux je ne sais si tu mens On dirait que l'averse ouvre des fleurs sauvages", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Pour qui chanter vraiment en vaudrait-il la peine Si ce n'est pas pour ceux dont tu rêves souvent Et dont le souvenir est comme un bruit de chaînes La nuit s'éveillant dans tes veines Et qui parle à ton cœur comme au voilier le vent", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Qu'importe comment s'appelle Cette clarté sur leurs pas Que l'un fût de la chapelle Et l'autre s'y dérobât Celui qui croyait au ciel Celui qui n'y croyait pas Tous les deux étaient fidèles Des lèvres du cœur des bras Et tous les deux disaient qu'elle Vive et qui vivra verra Celui qui croyait au ciel Celui qui n'y croyait pas Quand les blés sont sous la grêle Fou qui fait le délicat Fou qui songe à ses querelles Au cœur du commun combat Celui qui croyait au ciel Celui qui n'y croyait pas", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Je réclame le droit de rêver au tournant De la route Aux grands charmes de la promenade Le droit de m’émouvoir du monde maintenant Que s’approche la canonnade", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Sur le Pont-Neuf j'ai rencontré Fumée aujourd'hui comme alors Celui que je fus à l'orée Celui que je fus à l'aurore", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Un front qui s'appuie À moi dans la nuit Deux grands yeux ouverts Et tout m'a semblé Comme un champ de blé Dans cet univers", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Mais toutes les comparaisons ici paraissent inutiles Vous pouvez brûler tous les mots sans expliquer ce qu'est le feu Le bonheur et la flamme sont ce qui danse au fond de nos yeux Pour qui ne les a jamais vus comment se ressembleraient-ils", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Vous retrouverez dans mon sang ses pleurs Vous retrouverez dans mon chant sa voix Ses yeux dans mes veines Et tout l'avenir de l'homme et des fleurs Toute la tendresse et toute la joie Et toutes les peines", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "L’avenir de l’homme est la femme Elle est la couleur de son âme Elle est sa rumeur et son bruit Et sans elle il n’est qu’un blasphème Il n’est qu’un noyau sans le fruit Sa bouche souffle un vent sauvage Sa vie appartient aux ravages Et sa propre main le détruit", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Même s’il pleut sur mon visage Croire au soleil quand tombe l'eau S’il pleut tant pis tant pis l’orage Les mots dans moi meurent si fort Qui si fortement me meurtrissent Les mots que je ne forme pas Est-ce leur mort en moi qui mord Le malheur c’est savoir de quoi Je ne parle pas à la fois Et de quoi cependant je parle C’est en nous qu’il nous faut nous taire", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Le parfum d'une femme, c'est son secret. Le dévoiler, c'est se déshabiller devant le premier venu.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Les paroles servent à masquer les sentiments, non à les exprimer.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Je ne crois pas qu'on puisse comprendre quoi que ce soit de moi, si l'on omet de dater mes pensées ou mes écrits.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "[…] la poésie est la mathématique de toutes les écritures.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Une grande commisération indifférente entoure le fauteuil des impotents. Imbéciles spectateurs, vous ne comprendrez jamais rien. Je ne donnerais pas ma place pour tout l'or du monde. Soustrait à toutes les considérations puériles des hommes, je consacre ici tout mon temps à la volupté. Mes sens réduits se sont affinés à l'extrême, et c'est dans sa pureté que je connais enfin le plaisir. La vieillesse a peu touché mon corps. Si mes cheveux ont blanchi, je n'ai point usé mes jours dans le lit d'une femme que chaque nuit fait agoniser dans sa peau ridée. Dans mon esclavage apparent, quelle liberté véritable. Du temps que j'avais le pouvoir de marcher, de parler, il me fallait tenir compte des autres. Je n'osais pas penser, tout me semblait criminel. Je me limitais. Je redoutais les questions qui se posaient à moi. Une grande injustice met à l'aise.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Qu'est-ce qu'un proverbe sioux ? Dans la danse blanche et bleue qu'aperçoit au milieu des efforts de la défécation l'homme qui fixe le carrelage des cabinets il y a plus de beauté que dans une pure aurore - est un proverbe sioux.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Le développement de l'individu reproduit celui de l'espèce. Les gens regardent ces métamorphoses sans les comprendre et baptisent contradictions les fruits d'une logique supérieure. Quand il eut écrit des poèmes plus séduisants que les plumes des oiseaux mâles, André Breton se mit résolûment à prendre l'observation de l'esprit humain. Cette action sacrilège lui valut de déplaire à ceux-là même qui avaient applaudi à ses premières expériences. Nul ne fit jamais si bon marché du succès : il abandonna aux chercheurs d'or les filons qu'il mettait négligemment au jour et devint prospecteur de radium. Quelqu'un de ses aînés bénéficiera plus tard de ses découvertes. Il sourit à cette idée et laisse aux autres le soin de faire figure dans l'histoire. Il sait qu'on reconnaîtra toujours son sillage comme un paraphe au milieu des contemporains. Avez-vous lu un livre merveilleux qui s'appelle \"Le Phare du Bout du Monde\" ?", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Voici des années mortes. On vit au jour le jour. De temps à autre, on tourne la page et ce qu'on lit au verso n'est pas pour effrayer. A force de monter les escaliers et de les descendre, je me suis fait une philosophie. Quelques pays, quelques amis : tout passe, et parfois il y a des colères bleues, des injures, des gifles, un peu de sang sur les doigts. Mais ce qui revient toujours, c'est le décor de Paris que traversent la Seine et le métropolitain comme deux poignards tatoués.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Il cultivait dans des verres d'eau ces oignons cendrés dont naissent les belles jonquilles. Un jour la fleur qui s'ouvrit fut, comme une flèche indicatrice, un revolver braqué.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Pour se retrouver lui-même, il lui suffisait de revenir s'accouder aux marbres des cafés dont on suit d'un œil idiot les veines jolîment entrelacées. Là, les mots entendus prennent des inflexions subites et on lit par désœuvrement les inscriptions de porcelaine des vitres qui tournent le dos.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Je ne voudrais pas dire de mal de ce livre. Je n'en dirai d'ailleurs pas, mais je voudrais bien retrouver en Philippe Soupault le personnage de Chansons, l'espèce d'humour qu'il sut créer et qu'il abandonne trop pour un mirage ridicule. Je ne vous connaissais pas, cher ami, à l'époque où vous construisiez le monde, mais j'ai appris que cela existait et je voudrais bien vous revoir ainsi. Je me fiche pas mal que vous collaboriez à la Vie des Lettres ou aux Feuilles libres. Je vous reproche seulement d'avoir changé de point de vue puisque vous n'ajoutez rien à vous-même. C'est triste au fond. Si au moins vous deveniez ministre.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Puisqu’au nom de la France on peut envoyer des hommes à la mort, que cette idée, comme toutes les idées nationales, disparaisse de la terre. Le fanatisme des patriotes toujours menaçant, je le combattrai partout où je le rencontrerai. Athée de leur religion (la religion du nationalisme), qu’ils me brûlent, puisque nous en sommes encore au temps de l’Inquisition et de la Censure.", Author = "Louis Aragon" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Louis_Aragon", Text = "Plus encore que le patriotisme qui est une hystérie comme une autre, mais plus creuse et plus mortelle qu’une autre, ce qui nous répugne c’est l’idée de Patrie qui est vraiment le concept le plus bestial, le moins philosophique dans lequel on essaie de faire entrer notre esprit.", Author = "Louis Aragon" },
        };
    }
}