using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class MargueriteYourcenar
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "On n'est jamais tout à fait seul : par malheur, on est toujours avec soi-même.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Un grossissement de plus, et ces visages se décomposeraient en mouvements d'atomes, aussi indifférents à ce baiser que nous pouvons l'être aux amours démesurées des astres.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "La lettre écrite m'a enseigné à écouter la voix humaine, tout comme les grandes attitudes immobiles des statues m'ont appris à apprécier les gestes.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "L'une des meilleures manières de recréer la pensée d'un homme : reconstituer sa bibliothèque.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Faire de son mieux. Refaire. Retoucher imperceptiblement encore cette retouche. « C’est moi-même que je corrige, disait Yeats, en retouchant mes œuvres. »", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Qui serait assez insensé pour mourir sans avoir fait au moins le tour de sa prison ?", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "(…) je m’arrête, prise de vertige devant l’inextricable enchevêtrement d’incidents et de circonstances qui plus ou moins nous déterminent tous.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Le fait reste que, même pour les moins gourmets, les moins gourmands ou les moins goinfres, vivre ensemble, c’est en partie manger ensemble.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Pendant ce temps, la terre tournait.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "J’avais l’imperceptible recul du chien qui détourne le cou quand on lui présente un collier.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Cette femme assurément douée d’agréments (…)", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Ce qui surnage comme toujours, c’est l’infinie pitié pour le peu que nous sommes, et, contradictoirement, le respect et la curiosité de ces fragiles et complexes structures, posées comme sur pilotis à la surface de l’abîme, et dont aucune n’est tout à fait pareille à aucune autre.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Comme toujours, chaque fois qu’il se tourne vers le monde extérieur, la vie est là, avec son imprévu, sa foncière tristesse, sa décevante douceur, et sa presque insupportable plénitude.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Il se souvient d’avoir écrit quelque part qu’il n’y avait devant la vie et la mort que deux attitudes valables, le christianisme et le stoïcisme.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "(…) cette époque qui nous semble à distance épaisse et inerte, suspendue comme un énorme remblai au bord de l’abîme du XXè siècle.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Mon visage commence à se dessiner sur l’écran du temps.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Nos livres d'école nous ressassaient que ces Gaulois au grand cœur ne craignaient rien, sinon que le ciel ne tombât. Plus courageux ou plus désespérés qu'ils ne l'étaient, nous avons pris l'habitude, depuis 1945, de nous attendre à voir le ciel tomber.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "De temps en temps, comme un cortège passant dans une rue tranquille jette les reflets de ses torches sur les vitres d'une maison endormie, et les fait tressaillir du bruit de ses tambours et de ses fifres, l'histoire ainsi projette ses feux sur une famille à peu près sans histoire.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "À la vérité, toutes les sociétés, quelles qu'elles soient, sont basées sur la possession des choses ; une bonne partie des gens qui se font peindre ont toujours exigé qu'on mît près d'eux leurs bibelots favoris, tout comme aux temps antiques ils auraient demandé qu'on les plaçât dans leurs tombes.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Pour ces pharisiens qui se croient des chrétiens, aimer autrui comme soi-même est un de ces préceptes qui font du bien quand le curé les débite en chaire ; ceux qui ont faim et soif de la justice sont des émeutiers qui finissent au bagne.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Les yeux de l'enfant et ceux du vieillard regardent avec la tranquille candeur de qui n'est pas encore entré dans le bal masqué ou en est déjà sorti. Et tout l'intervalle semble un tumulte vain, une agitation à vide, un chaos inutile par lequel on se demande pourquoi on a dû passer.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Il est beau d’espérer que sous une forme ou sous une autre, que la plupart des religions ont choisie féminine, comme Marie, ou androgyne comme Kwannon, la douceur et la compassion nous accompagneront, peut-être invisiblement à l’heure de notre mort.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Quoi qu'il arrive, j'apprends. Je gagne à tout coup.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Solitude… Je ne crois pas comme ils croient, je ne vis pas comme ils vivent, je n’aime pas comme ils aiment… Je mourrai comme ils meurent.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "L'alcool dégrise. Après quelques gorgées de cognac, je ne pense plus à toi.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Il n’y a pas d’amour malheureux : on ne possède que ce qu’on ne possède pas. Il n’y a pas d’amour heureux : ce qu’on possède, on ne le possède plus.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Rien à craindre. J’ai touché le fond. Je ne puis tomber plus bas que ton cœur.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Un cœur, c'est peut-être malpropre. C'est de l’ordre de la table d’anatomie et de l’étal de boucher. Je préfère ton corps.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Rien de plus sale que l'amour-propre.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Je me refuse à faire de toi un objet, même quand ce serait l'Objet Aimé.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Aimer les yeux fermés, c’est aimer comme un aveugle. Aimer les yeux ouverts, c’est peut-être aimer comme un fou : c’est éperdument accepter. Je t’aime comme une folle.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "On arrive vierge à tous les événements de sa vie. J’ai peur de ne pas savoir m’y prendre avec ma Douleur.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Brûlé de plus de feux… Bête fatiguée, un fouet de flammes me cingle les reins. J’ai retrouvé le vrai sens des métaphores de poètes. Je me réveille chaque nuit dans l’incendie de mon propre sang.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Je ne tomberais pas. J’ai atteint le centre. J’écoute le battement d’on ne sait quelle divine horloge à travers la mince cloison charnelle de la vie pleine de sang, de tressaillements et de souffles. Je suis près du noyau mystérieux des choses comme la nuit on est quelquefois près du cœur.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Quand je te revois, tout redevient limpide. J’accepte de souffrir.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Et tu t’en vas ? Tu t’en vas ?… Non, tu ne t’en vas pas : je te garde. Tu me laisses dans les mains ton âme comme un manteau.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "On dit : fou de joie. On devrait dire : sage de douleur.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Il y’a six jours, il y’a six mois, il y eu six ans, il y aura six siècles… Ah ! mourir pour arrêter le temps…", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "L’amour est un châtiment. Nous sommes punis de n’avoir pas pu rester seuls.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Tes cheveux, tes mains, ton sourire rappellent de loin quelqu’un que j’adore. Qui donc ? Toi-même.", Author = "Marguerite Yourcenar" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Marguerite_Yourcenar", Text = "Qu'il eût été fade d'être heureux !", Author = "Marguerite Yourcenar" },
        };
    }
}