using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class MichelFoucault
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il me semble qu'il y a là, depuis la souveraineté infâme jusqu'à l'autorité ridicule, tous les degrés de ce que l'on pourrait appeler l'indignité du pouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'exclusion de la lèpre, c'était une pratique sociale qui comportait d'abord un partage rigoureux, une mise à distance, une règle de non-contact entre un individu (ou un groupe d'individus) et un autre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il me semble qu'en ce qui concerne le contrôle des individus, au fond, l'Occident n'a eu que deux grands modèles : l'un, c'est celui de l'exclusion du lépreux; l'autre, c'est le modèle de l'inclusion du pestiféré.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste, c'est le moment où le quadrillage d'une population se fait jusqu'à son point extrême, où rien des communications dangereuses, des communautés confuses, des contacts interdits ne peut plus se produire.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste a pris la relève de la lèpre comme modèle de contrôle politique, et c'est là l'une des grandes inventions du XVIIIe siècle, ou en tout cas de l'âge classique et de la monarchie administrative.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Celui qui est à corriger se présente comme étant à corriger dans la mesure où toutes les techniques, toutes les procédures, tous les investissements familiers et familiaux de dressage par lesquels on a pu essayer de les corriger, ont échoué.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Puisque presque tout le monde se masturbe, ceci vous explique que certains tombent dans les maladies extrêmes que personne d'autre ne présente.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Selon une tradition que vous trouvez chez Montesquieu, mais qui remonte au XVIe siècle, au Moyen Âge et au droit romain aussi, le criminel et la fréquence surtout des crimes représentent, dans une société, comme la maladie du corps social.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "C'est par un état de violence permanente que le despote peut faire valoir sa volonté sur le corps social tout entier.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le couplage anthropophagie-inceste, les deux grandes consommations interdites, me paraît caractéristique de cette première présentation du monstre sur l'horizon de la pratique, de la pensée et de l'imagination juridique de la fin du XVIIIe siècle.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'autodestruction de la nature, qui est un thème fondamental chez Sade, cette autodestruction dans une sorte de monstruosité déchaînée, n'est jamais effectuée que par la présence d'un certain nombre d'individus qui détiennent un surpouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste a pris la relève de la lèpre comme modèle de contrôle politique, et c'est là l'une des grandes inventions du XVIIIe siècle, ou en tout cas de l'âge classique et de la monarchie administrative.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La grande revendication d'une éducation d'État, ou contrôlée par l'État, vous la trouvez exactement au moment où commence la campagne de la masturbation en France et en Allemagne, vers les années 1760-1780.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le châtiment est passé d'un art des sensations insupportables à une économie des droits suspendus.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Un supplice bien réussi justifie la justice, dans la mesure où il publie la vérité du crime dans le corps même du supplicié.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Tout au long du XVIIIe siècle, à l'intérieur et à l'extérieur de l'appareil judiciaire, dans la pratique pénale quotidienne comme dans la critique des institutions, on voit se former une nouvelle stratégie pour l'exercice du pouvoir de châtier.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le droit de punir a été déplacé de la vengeance du souverain à la défense de la société.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "En un sens le pouvoir de normalisation contraint à l'homogénéité ; mais il individualise en permettant de mesurer des écarts, de déterminer les niveaux, de fixer les spécialités et de rendre les différences utiles en les ajustant les unes aux autres.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il n'y a pas d'exercice du pouvoir sans une certaine économie des discours de vérité fonctionnant dans, à partir de et à travers ce pouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Nous sommes soumis par le pouvoir à la production de la vérité et nous ne pouvons exercer le pouvoir que par la production de la vérité.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La théorie de la souveraineté est liée à une forme de pouvoir qui s'exerce sur la terre et les produits de la terre, beaucoup plus que sur les corps et sur ce qu'ils font.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La théorie de la souveraineté est, si vous voulez, ce qui permet de fonder le pouvoir absolu dans la dépense absolue du pouvoir, et non pas de calculer le pouvoir avec le minimum de dépense et le maximum d'efficacité.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "C'est la guerre qui est le moteur des institutions et de l'ordre : la paix, dans le moindre de ses rouages, fait sourdement la guerre. Autrement dit, il faut déchiffrer la guerre sous la paix : la guerre, c'est le chiffre même de la paix.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Un entrecroisement de corps, de passions et de hasards : c'est cela qui, dans ce discours, va constituer la trame permanente de l'histoire et des sociétés.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Jupiter, dieu hautement représentatif du pouvoir, dieu par excellence de la première fonction et du premier ordre dans la tripartition indo-européenne, c'est à la fois le dieu aux liens et le dieu aux foudres.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'histoire, c'est le discours du pouvoir, le discours des obligations par lesquelles le pouvoir soumet ; c'est aussi le discours de l'éclat par lequel le pouvoir fascine, terrorise, immobilise.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Liant et immobilisant, le pouvoir est fondateur et garant de l'ordre ; et l'histoire est précisément le discours par lequel ces deux fonctions qui assurent l'ordre vont être intensifiées et rendues plus efficaces.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Dans l'histoire de type romain, la mémoire avait essentiellement à assurer le non-oubli — c'est-à-dire le maintien de la loi et la majoration perpétuelle de l'éclat du pouvoir à mesure qu'il dure.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au contraire, la nouvelle histoire qui apparaît va avoir à déterrer quelque chose qui a été caché, et qui a été caché non seulement parce que négligé, mais aussi parce que soigneusement, délibérément, méchamment, travesti et masqué.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au fond, ce que la nouvelle histoire veut montrer, c'est que le pouvoir, les puissants, les rois, les lois, ont caché qu'ils étaient nés dans le hasard et dans l'injustice des batailles.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La guerre, c'est l'effet immédiat d'une non-différence ou, en tout cas, de différences insuffisantes.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'indifférenciation naturelle crée donc des incertitudes, des risques, des hasards et, par conséquent, la volonté, de part et d'autre, de s'affronter ; c'est l'aléatoire dans le rapport primitif des forces qui crée cet état de guerre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "On est sur le théâtre des représentations échangées, on est dans un rapport de peur qui est un rapport temporellement indéfini ; on n'est pas réellement dans la guerre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il faut et il suffit, pour qu'il y ait souveraineté, que soit effectivement présente une certaine volonté radicale qui fait qu'on veut vivre même lorsqu'on ne le peut pas sans la volonté d'un autre.", Author = "Michel Foucault" },
        };
    }
}