using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class MichelHouellebecq
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Tout comme le libéralisme économique sans frein, et pour des raisons analogues, le libéralisme sexuel produit des phénomènes de paupérisation absolue. Certains font l'amour tous les jours; d'autres cinq ou six fois dans leur vie, ou jamais. Certains font l'amour avec des dizaines de femmes ; d'autres avec aucune. C'est ce qu'on appelle la « loi du marché ».", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Le libéralisme économique, c’est l’extension du domaine de la lutte, son extension à tous les âges de la vie et à toutes les classes de la société. De même, le libéralisme sexuel, c’est l’extension du domaine de la lutte, son extension à tous les âges de la vie et à toutes les classes de la société.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Certains êtres éprouvent très tôt une effrayante impossibilité à vivre par eux-mêmes; au fond ils ne supportent pas de voir leur propre vie en face, et de la voir en entier, sans zones d'ombre, sans arrière-plans. Leur existence est j'en conviens une exception aux lois de la nature, non seulement parce que cette fracture d'inadaptation fondamentale se produit en dehors de toute finalité génétique mais aussi en raison de l'excessive lucidité qu'elle présuppose, lucidité évidemment transcendante aux schémas perceptifs de l'existence ordinaire. Il suffit parfois de placer un autre être en face d'eux, à condition de le supposer aussi pur, aussi transparent qu'eux-mêmes, pour que cette insoutenable fracture se résolve en une aspiration lumineuse, tendue et permanente vers l'absolument inaccessible. Ainsi, alors qu'un miroir ne renvoie jour après jour que la même désespérante image, deux miroirs parallèles élaborent et construisent un réseau net et dense qui entraîne l'œil humain dans une trajectoire infinie, sans limites, infinie dans sa pureté géométrale, au-delà des souffrances et du monde.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "D'abord révélée à l'animal sous la forme de la douleur physique, l'existence individuelle n'accède dans les sociétés humaines à la pleine conscience d'elle-même que par l'intermédiaire du ''mensonge'', avec lequel elle peut en pratique se confondre.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Le désir sexuel se porte essentiellement sur les corps jeunes, et l'investissement progressif du champ de la séduction par les très jeunes filles ne fut au fond qu'un retour à la normale, un retour à la vérité du désir analogue à ce retour à la vérité des prix qui suit une surchauffe boursière anormale.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Dans un monde qui ne respecte que la jeunesse, les êtres sont peu à peu ''dévorés''.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Adolescent, Michel croyait que la souffrance donnait à l'homme une dignité supplémentaire. Il devait maintenant en convenir : il s'était trompé. Ce qui donnait à l'homme une dignité supplémentaire, c'était la télévision.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Les relations familiales persistent quelques années, parfois quelques dizaines d'années, elles persistent en réalité beaucoup plus longtemps que toutes les autres ; et puis, finalement, elles aussi s'éteignent.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "La possibilité de vivre commence dans le regard de l'autre.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Considérant les événements présents de notre vie, nous oscillons sans cesse entre la croyance au hasard et l'évidence du déterminisme.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "La traditionnelle ''lucidité des dépressifs'', souvent décrite comme un désinvestissement radical à l'égard des préoccupations humaines, se manifeste en tout premier lieu par un manque d'intérêt pour les questions effectivement peu intéressantes. Ainsi peut-on, à la rigueur, imaginer un dépressif amoureux, tandis qu'un dépressif patriote paraît franchement inconcevable.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Notre malheur n'atteint son plus haut point que lorsque a été envisagée, suffisamment proche, la possibilité pratique du bonheur.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "De tous les biens terrestres, la jeunesse physique est à l'évidence le plus précieux ; et nous ne croyons plus aujourd'hui qu'aux biens terrestres.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "De toute façon, les Français méprisent les Belges, dit-il pour conclure ; et le pire est qu'ils ont raison. La Belgique est un pays déliquescent et absurde, un pays qui n'aurait jamais dû exister.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L'audition du monde réel était déjà en soi une souffrance.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "C'est dans le rapport à autrui qu'on prend conscience de soi ; c'est bien ce qui rend le rapport à autrui insupportable.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "C'est avec facilité qu'on renonce à la vie, qu'on met soi-même sa vie de côté.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Pour la masochiste manipulateur, il ne suffit pas que lui-même soit malheureux ; il faut encore que les autres le soient.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L'homme n'est décidément pas fait pour le bonheur.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Je suis pris dans un système qui ne m'apporte plus grand-chose, et que je sais au demeurant inutile; mais je ne vois pas comment y échapper.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Ce n'est pas aussi compliqué qu'on le raconte, les relations humaines: c'est souvent insoluble, mais c'est rarement ''compliqué''.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Tout peut arriver dans la vie, et surtout rien.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "S'il n'y avait pas, de temps à autre, un peu de sexe, en quoi consisterai la vie?", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Non seulement [les Occidentaux] ont honte de leur propre corps, qui n'est pas à la hauteur des standards du porno, mais, pour les mêmes raisons, ils n'éprouvent plus aucune attirance pour le corps de l'autre.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L'absence d'envie de vivre, hélas, ne suffit pas pour avoir envie de mourir.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Loin d’être un effort d’abstraction, comme on le prétend parfois, le passage au monothéisme n’est qu’un élan vers l’abrutissement.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Quand les gens parlent de « droits de l’homme », j’ai toujours plus ou moins l’impression qu’ils font du ''second degré''.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Les hommes vivent les uns à côté des autres comme des bœufs ; c’est tout juste s’ils parviennent, de temps en temps, à partager une bouteille d’alcool.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Quant aux droits de l'homme, bien évidemment, je n'en avais rien à foutre ; c'est à peine si je parvenais à m'intéresser aux droits de ma queue.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "La liberté, à titre personnel, j'étais plutôt contre ; il est amusant de constater que ce sont toujours les adversaires de la liberté qui se trouvent, à un moment ou à un autre, en avoir le plus besoin.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L'enfant est une sorte de nain vicieux, d'une cruauté innée, chez qui se retrouvent immédiatement les pires traits de l'espèce, et dont les animaux domestiques se détournent avec une sage prudence.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Jeunesse, beauté, force : les critères de l'amour physique sont exactement les mêmes que ceux du nazisme.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L'amour non partagé est une hémorragie.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Sans doute l'amour n'avait-il jamais été, comme la pitié selon Nietzsche, qu'une fiction inventée par les faibles pour culpabiliser les forts, pour introduire des limites à leur liberté et à leur férocité naturelles.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Que l'histoire politique puisse jouer un rôle dans ma propre vie continuait à me déconcerter, et à me répugner un peu. Je me rendais bien compte pourtant, et depuis des années, que l'écart croissant, devenu abyssal, entre la population et ceux qui parlaient en son nom, politiciens et journalistes, devait nécessairement conduire à quelque chose de chaotique, de violent et d'imprévisible. La France, comme les autres pays d'Europe occidentale, se dirigeait depuis longtemps vers la guerre civile, c'était une évidence ; mais jusqu'à ces derniers jours j'étais encore persuadé que les Français dans leur immense majorité restaient résignés et apathiques - sans doute parce que j'étais moi-même passablement résigné et apathique. Je m'étais trompé.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "La religion la plus con, c'est quand même l'islam. Quand on lit le Coran, on est effondré... effondré !", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "L’islam est une religion dangereuse, et ce depuis son apparition. Heureusement, il est condamné. D’une part, parce que Dieu n’existe pas, et que même si on est con, on finit par s’en rendre compte. A long terme, la vérité triomphe. D’autre part, l’Islam est miné de l’intérieur par le capitalisme. Tout ce qu’on peut souhaiter, c’est qu’il triomphe rapidement. Le matérialisme est un moindre mal. Ses valeurs sont méprisables, mais quand même moins destructrices, moins cruelles que celles de l’islam.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "La lecture du Coran est une chose dégoûtante. Dès que l’islam naît, il se signale par sa volonté de soumettre le monde. Sa nature, c’est de soumettre. C’est une religion belliqueuse, intolérante, qui rend les gens malheureux.", Author = "Michel Houellebecq" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Nous sommes tous atrocement prisonniers de la plateforme où nous sommes montés sans être capables d'en redescendre.", Author = "Frédéric Beigbeder" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Ce que je partage peut-être de plus profond avec Houellebecq : comprendre la littérature comme un programme de survie.", Author = "Maurice G. Dantec" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Michel Houellebecq est un extraordinaire sismographe des mutations qui ont affecté la France et l'Occident depuis les années 1960, mais c'est à tort, me semble-t-il, qu'on le réduit à un romancier sociologique. Il est doué d'un don de vision, il pressent les forces qui travaillent souterrainement nos sociétés et possède ce pouvoir de révélation qui distingue les œuvres importantes. ''Soumission'' en est un remarquable exemple.", Author = "Bérénice Levet" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Ses livres relèvent de la santé publique. Voir que notre époque est quadrillée par la science et la statistique, laquelle est étymologiquement au cœur de la raison d'État et de sa volonté de normer par la « loi normale » le monde est une chose ; approcher ensuite les deux raisons de vivre, ou survivre, houellebecquiennes – la bonté et l'amour – en est une autre, autrement oxygénante.", Author = "Bernard Maris" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Houellebecq", Text = "Houellebecq estime que les amuseurs publics sont ce qu'il y a de plus bas dans la société : des cyniques qui font commerce de leur cynisme.", Author = "Bernard Maris" },
        };
    }
}