using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class MichelFoucault
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il me semble qu'il y a là, depuis la souveraineté infâme jusqu'à l'autorité ridicule, tous les degrés de ce que l'on pourrait appeler l'indignité du pouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'exclusion de la lèpre, c'était une pratique sociale qui comportait d'abord un partage rigoureux, une mise à distance, une règle de non-contact entre un individu (ou un groupe d'individus) et un autre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il me semble qu'en ce qui concerne le contrôle des individus, au fond, l'Occident n'a eu que deux grands modèles : l'un, c'est celui de l'exclusion du lépreux; l'autre, c'est le modèle de l'inclusion du pestiféré.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La ville en état de peste — et là je vous cite toute une série de règlements, d'ailleurs absolument identiques les uns aux autres, qui ont été publiés depuis la fin du Moyen Âge jusqu'au début du XVIIIe siècle — était partagée en districts, les districts étaient partagés en quartiers, puis dans ces quartiers on isolait les rues, et il y avait dans chaque rue des surveillants, dans chaque quartier des inspecteurs, dans chaque district des responsables de district et dans la ville elle-même soit un gouverneur nommé à cet effet, soit encore les échevins qui avaient reçu, au moment de la peste, un supplément de pouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il ne s'agit pas d'une exclusion, il s'agit d'une quarantaine. Il ne s'agit pas de chasser, il s'agit au contraire d'établir, de fixer, de donner son lieu, d'assigner des places, de définir des présences, et des présences quadrillées. Non pas rejet, mais inclusion.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste, c'est le moment où le quadrillage d'une population se fait jusqu'à son point extrême, où rien des communications dangereuses, des communautés confuses, des contacts interdits ne peut plus se produire.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste a pris la relève de la lèpre comme modèle de contrôle politique, et c'est là l'une des grandes inventions du XVIIIe siècle, ou en tout cas de l'âge classique et de la monarchie administrative.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Ce que le XVIIIe siècle a mis en place par le système « discipline à effet de normalisation », par le système « discipline-normalisation », il me semble que c'est un pouvoir qui, en fait, n'est pas répressif, mais productif — la répression n'y figurant qu'à titre d'effet latéral et secondaire, par rapport à des mécanismes qui, eux, sont centraux par rapport à ce pouvoir, des mécanismes qui fabriquent, des mécanismes qui créent, des mécanismes qui produisent.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Celui qui est à corriger se présente comme étant à corriger dans la mesure où toutes les techniques, toutes les procédures, tous les investissements familiers et familiaux de dressage par lesquels on a pu essayer de les corriger, ont échoué.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Puisque presque tout le monde se masturbe, ceci vous explique que certains tombent dans les maladies extrêmes que personne d'autre ne présente.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Selon une tradition que vous trouvez chez Montesquieu, mais qui remonte au XVIe siècle, au Moyen Âge et au droit romain aussi, le criminel et la fréquence surtout des crimes représentent, dans une société, comme la maladie du corps social.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "C'est par un état de violence permanente que le despote peut faire valoir sa volonté sur le corps social tout entier.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "A l'origine de l'humanité, il y avait deux catégories de gens : ceux qui se vouaient à l'agriculture et à l'élevage, et puis ceux qui étaient bien obligés de protéger les premiers, parce que les animaux sauvages et féroces risquaient de manger les femmes et les enfants, détruire les récoltes, dévorer les troupeaux, etc.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le couplage anthropophagie-inceste, les deux grandes consommations interdites, me paraît caractéristique de cette première présentation du monstre sur l'horizon de la pratique, de la pensée et de l'imagination juridique de la fin du XVIIIe siècle.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'autodestruction de la nature, qui est un thème fondamental chez Sade, cette autodestruction dans une sorte de monstruosité déchaînée, n'est jamais effectuée que par la présence d'un certain nombre d'individus qui détiennent un surpouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il n'y a pas de monstre chez Sade qui soit politiquement neutre et moyen : ou il vient de la lie du peuple et il a redressé l'échine contre la société établie, ou il est un prince, un ministre, un seigneur qui détient sur tous les pouvoirs sociaux un surpouvoir sans loi.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La peste a pris la relève de la lèpre comme modèle de contrôle politique, et c'est là l'une des grandes inventions du XVIIIe siècle, ou en tout cas de l'âge classique et de la monarchie administrative.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La grande revendication d'une éducation d'État, ou contrôlée par l'État, vous la trouvez exactement au moment où commence la campagne de la masturbation en France et en Allemagne, vers les années 1760-1780.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Dans cet échange, vous comprenez bien où est le leurre, parce que la tâche que l'on donne aux parents, c'est précisément de prendre possession du corps des enfants, de le recouvrir, d'y veiller d'une manière si continue qu'ils ne puissent jamais se masturber.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le châtiment est passé d'un art des sensations insupportables à une économie des droits suspendus.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au lieu que la folie efface le crime au sens de l'article 64, tout crime maintenant, et à la limite toute infraction, porte en soi, comme un soupçon, légitime, mais aussi comme un droit qu'ils peuvent revendiquer, l'hypothèse de la folie, en tout cas l'anomalie.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Un supplice bien réussi justifie la justice, dans la mesure où il publie la vérité du crime dans le corps même du supplicié.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Tout au long du XVIIIe siècle, à l'intérieur et à l'extérieur de l'appareil judiciaire, dans la pratique pénale quotidienne comme dans la critique des institutions, on voit se former une nouvelle stratégie pour l'exercice du pouvoir de châtier.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Le droit de punir a été déplacé de la vengeance du souverain à la défense de la société.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "En un sens le pouvoir de normalisation contraint à l'homogénéité ; mais il individualise en permettant de mesurer des écarts, de déterminer les niveaux, de fixer les spécialités et de rendre les différences utiles en les ajustant les unes aux autres.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Que la prison cellulaire, avec ses chronologies scandées, son travail obligatoire, ses instances de surveillance et de notation, avec ses maîtres en normalité, qui relaient et multiplient les fonctions du juge, soient devenue l'instrument moderne de la pénalité, quoi d'étonnant ?", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au constat que la prison échoue à réduire les crimes, il faut peut-être substituer l'hypothèse que la prison a fort bien réussi à produire la délinquance, type spécifié, forme politiquement ou économiquement moins dangereuse - à la limite utilisable - d'illégalisme.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il n'y a pas d'exercice du pouvoir sans une certaine économie des discours de vérité fonctionnant dans, à partir de et à travers ce pouvoir.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Nous sommes soumis par le pouvoir à la production de la vérité et nous ne pouvons exercer le pouvoir que par la production de la vérité.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Pour marquer simplement non pas le mécanisme même de la relation entre pouvoir, droit et vérité, mais l'intensité du rapport et sa constance, disons ceci : nous sommes astreints à produire la vérité par le pouvoir qui exige cette vérité et qui en a besoin pour fonctionner ; nous avons à dire la vérité, nous sommes contraints, nous sommes condamnés à avouer la vérité ou à la trouver.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La bourgeoisie se moque totalement des délinquants, de leur punition ou de leur réinsertion, qui n'a économiquement pas beaucoup d'intérêt. En revanche, de l'ensemble des mécanismes par lesquels le délinquant est contrôlé, suivi, puni, réformé, il se dégage, pour la bourgeoisie, un intérêt qui fonctionne à l'intérieur du système économico-politique général.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La théorie de la souveraineté est liée à une forme de pouvoir qui s'exerce sur la terre et les produits de la terre, beaucoup plus que sur les corps et sur ce qu'ils font.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La théorie de la souveraineté est, si vous voulez, ce qui permet de fonder le pouvoir absolu dans la dépense absolue du pouvoir, et non pas de calculer le pouvoir avec le minimum de dépense et le maximum d'efficacité.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Je veux dire, plus précisément, ceci : je crois que la normalisation, les normalisations disciplinaires, viennent buter de plus en plus contre le système juridique de la souveraineté ; de plus en plus nettement apparaît l'incompatibilité des unes et de l'autre ; de plus en plus est nécessaire une sorte de discours arbitre, une sorte de pouvoir et de savoir que sa sacralisation scientifique rendrait neutre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "C'est la guerre qui est le moteur des institutions et de l'ordre : la paix, dans le moindre de ses rouages, fait sourdement la guerre. Autrement dit, il faut déchiffrer la guerre sous la paix : la guerre, c'est le chiffre même de la paix.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Nous sommes donc en guerre les uns contre les autres ; un front de bataille traverse la société tout entière, continûment et en permanence, et c'est ce front de bataille qui place chacun de nous dans un camp ou dans un autre. Il n'y a pas de sujet neutre. On est forcément l'adversaire de quelqu'un.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "C'est l'appartenance à un camp — la position décentrée — qui va permettre de déchiffrer la vérité, de dénoncer les illusions et les erreurs par lesquelles on vous fait croire — les adversaires vous font croire — que l'on est dans un monde ordonné et pacifié.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Ou la vérité donne la force, ou la vérité déséquilibre, accentue les dissymétries et fait pencher finalement la victoire d'un côté plutôt que de l'autre : la vérité est un plus de force, tout comme elle ne se déploie qu'à partir d'un rapport de force.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Un entrecroisement de corps, de passions et de hasards : c'est cela qui, dans ce discours, va constituer la trame permanente de l'histoire et des sociétés.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Jupiter, dieu hautement représentatif du pouvoir, dieu par excellence de la première fonction et du premier ordre dans la tripartition indo-européenne, c'est à la fois le dieu aux liens et le dieu aux foudres.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'histoire, c'est le discours du pouvoir, le discours des obligations par lesquelles le pouvoir soumet ; c'est aussi le discours de l'éclat par lequel le pouvoir fascine, terrorise, immobilise.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Liant et immobilisant, le pouvoir est fondateur et garant de l'ordre ; et l'histoire est précisément le discours par lequel ces deux fonctions qui assurent l'ordre vont être intensifiées et rendues plus efficaces.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Dans l'histoire de type romain, la mémoire avait essentiellement à assurer le non-oubli — c'est-à-dire le maintien de la loi et la majoration perpétuelle de l'éclat du pouvoir à mesure qu'il dure.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au contraire, la nouvelle histoire qui apparaît va avoir à déterrer quelque chose qui a été caché, et qui a été caché non seulement parce que négligé, mais aussi parce que soigneusement, délibérément, méchamment, travesti et masqué.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Au fond, ce que la nouvelle histoire veut montrer, c'est que le pouvoir, les puissants, les rois, les lois, ont caché qu'ils étaient nés dans le hasard et dans l'injustice des batailles.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Ils essaient, ces rois injustes et partiels, de se faire valoir pour tous et au nom de tous ; ils veulent bien que l'on parle de leurs victoires, mais ils ne veulent pas que l'on sache que leurs victoires étaient la défaite des autres, c'était « notre défaite ».", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "La guerre, c'est l'effet immédiat d'une non-différence ou, en tout cas, de différences insuffisantes.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "S'il y avait des différences naturelles marquées, visibles, massives, de deux choses l'une : ou bien il y aurait effectivement affrontement entre le fort et le faible — mais cet affrontement et cette guerre réelle se solderaient aussitôt par la victoire du fort sur le faible, victoire qui serait définitive à cause même de la force du fort ; ou bien il n'y aurait pas affrontement réel, ce qui veut dire, tout simplement, que le faible, sachant, percevant, constatant sa propre faiblesse, renoncerait avant même l'affrontement.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "L'indifférenciation naturelle crée donc des incertitudes, des risques, des hasards et, par conséquent, la volonté, de part et d'autre, de s'affronter ; c'est l'aléatoire dans le rapport primitif des forces qui crée cet état de guerre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il n'y a pas de batailles dans la guerre primitive de Hobbes, il n'y a pas de sang, il n'y a pas de cadavres. Il y a des représentations, des manifestations, des signes, des expressions emphatiques, rusées, mensongères ; il y a des leurres, des volontés qui sont travesties en leur contraire, des inquiétudes qui sont camouflées en certitudes.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "On est sur le théâtre des représentations échangées, on est dans un rapport de peur qui est un rapport temporellement indéfini ; on n'est pas réellement dans la guerre.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Domination, direz-vous, et pas souveraineté. Eh bien non, dit Hobbes ; on est bien encore et toujours dans le rapport de souveraineté. Pourquoi ? Parce que, dès lors que les vaincus ont préféré la vie et l'obéissance, ils ont par la même reconstitué une souveraineté, ils ont fait de leurs vainqueurs leurs représentants, ils ont restauré un souverain à la place de celui que la guerre avait abattu.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Ce n'est donc pas la défaite qui fonde une société de domination, d'esclavage, de servitude, d'une manière brutale et hors du droit, mais ce qui s'est passé dans cette défaite, après même la bataille, après même la défaite, et d'une certaine manière indépendamment d'elle : c'est quelque chose qui est la peur, la renonciation à la peur, la renonciation aux risques de la vie.", Author = "Michel Foucault" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Michel_Foucault", Text = "Il faut et il suffit, pour qu'il y ait souveraineté, que soit effectivement présente une certaine volonté radicale qui fait qu'on veut vivre même lorsqu'on ne le peut pas sans la volonté d'un autre.", Author = "Michel Foucault" },
        };
    }
}