using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class PaulValéry
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "La bêtise n'est pas mon fort.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Trouver n'est rien. Le difficile est de s'ajouter ce qu'on trouve.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'expression d'un sentiment est toujours absurde.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "— Et le démon lui dit : donne-moi une preuve. Montre que tu es ''encore'' celui que tu as cru être.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Ce toit tranquille, où marchent des colombes, Entre les pins palpite, entre les tombes; Midi le juste y compose de feux La mer, la mer, toujours recommencée ! Ô récompense après une pensée Qu’un long regard sur le calme des dieux !", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le vent se lève ! … Il faut tenter de vivre ! L’air immense ouvre et referme mon livre", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Patience, patience, Patience dans l’azur ! Chaque atome de silence Est la chance d’un fruit mûr !", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Je n’aime pas trop les musées. Il y en a beaucoup d’admirables, il n’en est point de délicieux. Les idées de classement, de conservation et d’utilité publique, qui sont justes et claires, ont peu de rapport avec les délices.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L’Europe deviendra-t-elle ce qu’elle est en réalité, c’est-à-dire : un petit cap du continent asiatique, ou bien l’Europe restera-t-elle ce qu’elle paraît, c’est-à-dire : la partie précieuse de l’univers terrestre, la perle de la sphère, le cerveau d’un vaste corps ?", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Nous ne supportons plus la durée. Nous ne savons plus féconder l'ennui. Notre nature a horreur du vide, — ce vide sur lequel les esprits de jadis savaient peindre les images de leurs idéaux, leurs Idées, au sens de Platon.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Ce n'est qu'un jeu pour l'amateur de symétries historiques, c'est-à-dire imaginaires, que de démontrer que ces deux figures littéraires sont des figures semblables.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Dans les domaines de la création, qui sont aussi les domaines de l'orgueil, la nécessité de se distinguer est indivisible de l'existence même.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le poète se consacre et se consume donc à définir et à construire un langage dans le langage.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Mais un homme excité ne se paie pas de logique. Mon ami regardait mon calme comme un beau vase qui donne envie de le mettre en morceaux.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Nous autres, civilisations, nous savons maintenant que nous sommes mortelles.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "En vérité, il n’est pas de théorie qui ne soit un fragment, soigneusement préparé, de quelque autobiographie.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le moi est haïssable... mais il s'agit de celui des autres.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Celui qui n'a pas nos répugnances nous répugne.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Chacune des qualités d'un esprit apporte des chances particulières d'erreur à la représentation du réel. Si tu es vif, le lent t'échappe.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le mensonge et la crédulité s'accouplent et engendrent l'Opinion.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Les vilaines pensées viennent du cœur.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Nous ne pensons que par hasard aux circonstances permanentes de notre vie ; nous ne les percevons qu'au moment où elles s'altèrent tout à coup.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'accomplissement de nos désirs ne nous éloigne pas toujours de notre perte.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Une guerre dont l´issue n'a été due qu'a l'inégalité des puissances totales des adversaires est une guerre suspendue.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "La politique fut d'abord l'art d'empêcher les gens de se mêler de ce qui les regarde. À une époque suivante, on y adjoignit l'art de contraindre les gens à décider sur ce qu'ils n'entendent pas.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'historien fait pour le passé ce que la tireuse de cartes fait pour le futur. Mais la sorcière s'expose à une vérification et non l'historien.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'existence des voisins est la seule défense des nations contre une perpétuelle guerre civile.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Il est des hommes dont l'oreille, toute saine qu'elle est, ne distingue pas les sons d'avec les bruits.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Les petits faits inexpliqués contiennent toujours de quoi renverser toutes les explications des grands faits.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le réveil fait aux rêves une réputation qu'ils ne méritent pas.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "La richesse est une huile qui adoucit les machines de la vie.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Dieu créa l'homme, et ne le trouvant pas assez seul, il lui donne une compagne pour lui faire mieux sentir sa solitude.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Vieillir consiste à éprouver le changement du stable.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "La vie est à peine un peu plus vieux que la mort.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Les livres ont les mêmes ennemis que l'homme : le feu, l'humide, les bêtes, le temps; et leur propre contenu.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Crois, ou je te tue éternellement.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le pouvoir sans abus perd le charme.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Il est impossible de dire au Monde, au Corps : je ne veux rien de toi, mais ne veuille rien de moi.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le poème — cette hésitation prolongée entre le son et le sens.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "On n'est jamais assez content de soi pour se livrer à fond.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le sujet d'un ouvrage est à quoi se réduit un mauvais ouvrage.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Pamphlétaires, orateurs, violents, forcenés, qui vociférez, dites, ne sentez-vous jamais que tout homme qui crie est sur le point de faire semblant de crier ?", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le plaisir qu'il y a à comprendre certains raisonnements délicats dispose l'esprit en faveur de leurs conclusions.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Par le moyen de l'homme, l'impossible presse sur le réel.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Entendez la parole la plus étrange : ''Il y aura des hommes après nous''.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Être soi-même!... Mais soi-même en vaut-il la peine?", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Offense-moi, - pour me donner la force de te tuer.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Tous nos ennemis sont mortels.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Quand nous parvenons au but, nous croyons que le chemin a été le bon.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Un homme absorbé dans la plus profonde méditation. Son visage est vide, rien n'est écrit par ses traits. Comment peut-on être si loin de ce que l'on a de plus près?", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le simple est toujours faux. Ce qui ne l'est pas est inutilisable.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L´espoir fait vivre, mais comme sur une corde raide.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Nous avons de quoi saisir ce qui n'existe pas et de quoi ne pas voir ce qui nous crève les yeux.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'homme de génie est qui m'en donne.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Le pauvre est le produit d'une transformation facile effectuée sur le riche; le riche, celui d´une transformation difficile effectuée sur le pauvre.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Un homme compétent est un homme qui se trompe selon les règles.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Proverbe pour les puissants: Si quelqu'un te léche les bottes, mets-lui le pied dessus avant qu'il ne commence à te mordre.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "L'individu est la plus étrange création de l´homme.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Dieu a tout fait de rien. Mais le rien perce.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Il y a de la pauvreté d'esprit à être toujours d'accord avec soi-même.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Il reste d’un homme ce que donnent à songer son nom et les œuvres qui font de ce nom un signe d’admiration, de haine ou d’indifférence.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "C’est à l’univers qu’il songe toujours, et à la rigueur.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Il y eut une fois Quelqu’un qui pouvait regarder le même spectacle ou le même objet, tantôt comme l’eût regardé un peintre, et tantôt en naturaliste ; tantôt comme un physicien, et d’autres fois, comme un poète : et aucun de ces regards n’était superficiel.", Author = "Paul Valéry" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Paul_Valéry", Text = "Les recherches insensées sont parentes des découvertes imprévues.", Author = "Paul Valéry" },
        };
    }
}