using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class RolandBarthes
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Toute l'histoire repose, en dernière instance, sur le corps humain.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La Femme commence là où finit l'Histoire.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Ce que le public réclame, c'est l'image de la passion, non la passion elle-même.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "L'altérité est le concept le plus antipathique au « bon sens ».", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Un peu de mal \"avoué\" dispense de reconnaître beaucoup de mal caché.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Est pittoresque tout ce qui est accidenté.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Je crois que l'automobile est aujourd'hui l'équivalent assez exact des grandes cathédrales gothiques : je veux dire une grande création d'époque, conçue passionnément par des artistes inconnus, consommée dans son image, sinon dans son usage, par un peuple entier qui s'approprie en elle un objet parfaitement magique.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La notoriété est la première forme de naturalisation.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Le toucher est le plus démystificateur de tous les sens, au contraire de la vue, qui est le plus magique.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La littérature ne commence pourtant que devant l'innommable, face à la perception d'un ''ailleurs'' étranger au langage même qui le cherche.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Le mythe est un système idéographique pur, où les formes sont encore motivées par le concept qu'elles représentent, sans cependant, et de loin, en recouvrir la totalité représentative.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Le petit-bourgeois est un homme impuissant à imaginer l'Autre. Si l'autre se présente à sa vue, le petit-bourgeois s'aveugle, l'ignore et le nie, ou bien il le transforme en lui-même. Dans l'univers petit-bourgeois, tous les faits de confrontation sont des faits réverbérants, tout autre est reduit au même.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La tautologie atteste une profonde méfiance à l'égard du langage : on le rejette parce qu'il vous manque. Or, tout refus du langage est une mort. La tautologie fonde un monde mort sur un monde immobile.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "J'en viens alors à me demander si la belle et touchante iconographie de l'abbé Pierre n'est pas l'alibi dont une bonne partie de la nation s'autorise, une fois de plus, pour substituer impunément les signes de la charité à la réalité de la justice.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Quand je me sais photographié, je me transforme en image...", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La langue, comme performance de tout langage, n'est ni réactionnaire ni progressiste ; elle est tout simplement fasciste ; car le fascisme, ce n'est pas d'empêcher de dire, c'est d'obliger à dire.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La vertu du catch, c'est d'être un spectacle excessif.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Il suffit de visiter aujourd'hui la Grèce pour comprendre la violence de la petitesse, et combien la tragédie racinienne, par sa nature \"contrainte\", s'accorde à ces lieux que Racine n'avait jamais vus : Thèbes, Buthrot, Trézène, ces capitales de la tragédie sont des villages.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Dans ''Iphigénie'', tout un peuple reste prisonnier de la tragédie parce que le vent ne se lève pas.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "L'enjeu tragique est ici beaucoup moins le sens de la parole que son apparition, beaucoup moins l'amour de Phèdre que son aveu.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Phèdre est son silence même : dénouer ce silence, c'est mourir, mais aussi mourir ne peut être qu'avoir parlé.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "N'exigeons pas de l'histoire ce qu'elle ne peut nous donner : l'histoire ne nous dira jamais ce qui se passe dans un auteur au moment où il écrit.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La beauté (contrairement à la laideur) ne peut vraiment s’expliquer : elle se dit, s’affirme, se répète en chaque partie du corps mais ne se décrit pas.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Autrement dit, la beauté ne peut s’alléguer que sous forme d’une citation.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "J'observe avec horreur un futur antérieur dont la mort est l'enjeu.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Tokyo nous redit cependant que le rationnel n'est qu'un système parmi d'autres. Pour qu'il y ait maîtrise du réel (en l'occurrence celui des adresses), il suffit qu'il y ait système, ce système fût-il apparemment illogique, inutilement compliqué, curieusement disparate : un bon bricolage peut non seulement tenir très longtemps, on le sait, mais encore il peut satisfaire des millions d'habitants, dressés d'autre part à toutes les perfections de la civilisation technicienne.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Chez nous, une soupe claire est une soupe pauvre; mais ici [au Japon], la légèreté du bouillon, fluide comme de l'eau, la poussière de soja ou de haricots qui s'y déplace, la rareté des deux ou trois solides (brin d'herbe, filament de légume, parcelle de poisson) qui divisent en flottant cette petite quantité d'eau, donnent l'idée d'une densité claire, d'une nutritivité sans graisse, d'un élixir d'autant plus réconfortant qu'il est pur : quelque chose d'aquatique (plus que d'aqueux), de délicatement marin amène une pensée de source, de vitalité profonde.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "L'écriture est précisément cet acte qui unit dans le même travail ce qui ne pourrait être saisi ensemble dans le seul espace plat de la représentation.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "[Le sumo] Le combat ne dure qu’un éclair : le temps de laisser choir l’autre masse. Pas de crise, pas de drame, pas d’épuisement, en un mot pas de sport : le signe de la pesée, non l’éréthisme du conflit.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Pourquoi, en Occident, la politesse est-elle considérée avec suspicion ? Pourquoi la courtoisie y passe-t-elle pour une distance (sinon même une fuite) ou une hypocrisie ? Pourquoi un rapport « informel » (comme on dit ici avec gourmandise) est-il plus souhaitable qu'un rapport codé ?", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Le haïku a cette propriété quelque peu fantasmagorique, que l'on s'imagine toujours pouvoir en faire soi-même facilement.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Tout en étant intelligible, le haïku ne veut rien dire, et c'est par cette double condition qu'il semble offert au sens, d'une façon particulièrement disponible, serviable, à l'instar d'un hôte poli qui vous permet de vous installer largement chez lui, avec vos manies, vos valeurs, vos symboles.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Vous avez le droit, dit le haïku, d'être futile, court, ordinaire; enfermez ce que vous voyez, ce que vous sentez dans un minci horizon de mots, et vous intéresserez; vous avez le droit de fonder vous-même (et à partir de vous-même) votre propre notable; votre phrase, quelle qu'elle soit, énoncera une leçon, libérera un symbole, vous serez profond; à moindre frais, votre écriture sera pleine.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La mesure du langage est ce à quoi l'Occidental est le plus impropre; ce n'est pas qu'il fasse trop long ou trop court, mais sa rhétorique lui fait un devoir de disproportionner le signifiant et le signifié, soit en « délayant » le second sous les flots bavards du premier, soit en « approfondissant » la forme vers les régions implicites du contenu.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "La justesse du haïku (qui n'est nullement peinture exacte du réel, mais adéquation du signifiant et du signifié, suppression des marges, bavures et interstices qui d'ordinaire excèdent ou ajourent le rapport sémantique), cette justesse a « évidemment quelque chose de musical (musique de sens, et non forcément de sons; le haïku a la pureté, la sphéricité et le vide même d'une note de musique; c'est peut-être pour cela qu'il se dit deux fois, en écho.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Comme une boucle gracieuse, le haïku s'enroule sur lui-même, le sillage du signe qui semble avoir été tracé, s'efface: rien n'a été acquis, la pierre du mot a été jetée pour rien : ni vagues ni coulée du sens.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "C'est par la papeterie, lieu et catalogue des choses nécessaires à l'écriture, que l'on s'introduit dans l'espace des signes ; c'est dans la papeterie que la main rencontre l'instrument et la matière du trait ; c'est dans la papeterie que commence le commerce du signe, avant même qu'il soit tracé.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "(…) le trait excluant ici la rature ou la reprise (puisque le caractère est tracé alla prima), aucune invention de la gomme ou de ses substituts (la gomme, objet emblématique du signifié que l'on voudrait bien effacer ou dont, tout au moins, on voudrait bien alléger, amincir la plénitude; mais en face de chez nous, du côté de l'Orient, pourquoi des gommes, puisque le miroir est vide ?).", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Qu'est-ce donc que notre visage, sinon une citation ?", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "L'ascèse (la velléité d'ascèse) s'adresse à l'autre : retourne-toi, regarde-moi, vois ce que tu as fait de moi.", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "\"Suis-je amoureux ? - Oui, puisque j'attends.\"", Author = "Roland Barthes" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Roland_Barthes", Text = "Le système [amoureux] est un ensemble où tout le monde a sa place, même si elle n’est pas bonne…", Author = "Roland Barthes" },
        };
    }
}