using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class SimoneWeil
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le mot de révolution est un mot pour lequel on tue, pour lequel on meurt, pour lequel on envoie les masses populaires à la mort, mais qui n'a aucun contenu.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La bonne volonté éclairée des hommes agissant en tant qu'individus est l'unique principe possible du progrès social.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La démocratie, le pouvoir du plus grand nombre, ne sont pas des biens. Ce sont des moyens en vue du bien, estimés efficaces à tort ou à raison.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Pour apprécier les partis politiques selon le critère de la vérité, de la justice, du bien public, il convient de commencer par en discerner les caractères essentiels.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Un parti politique est une machine à fabriquer de la passion collective.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Un parti politique est une organisation construite de manière à exercer une pression collective sur la pensée de chacun des êtres humains qui en sont membres.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La première fin, et, en dernière analyse, l'unique fin de tout parti politique est sa propre croissance, et cela sans aucune limite.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Par ce triple caractère, tout parti est totalitaire en germe et en aspiration.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Les partis sont des organismes publiquement, officiellement constitués de manière à tuer dans les âmes le sens de la vérité et de la justice.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Presque partout - et même souvent pour des problèmes purement techniques - l'opération de prendre parti, de prendre position pour ou contre, s'est substituée à l'opération de la pensée.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "C'est là une lèpre qui a pris origine dans les milieux politiques, et s'est étendue, à travers tout le pays, presque à la totalité de la pensée.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il est douteux qu'on puisse remédier à cette lèpre, qui nous tue, sans commencer par la suppression des partis politiques.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ce vide pesant fait beaucoup souffrir. Il est sensible même à beaucoup de ceux dont la culture est nulle et l'intelligence faible.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Une seule chose rend supportable la monotonie, c'est une lumière d'éternité ; c'est la beauté.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'arbitraire humain contraint l'âme, sans qu'elle puisse s'en défendre, à craindre et à espérer.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Job loue la mort de ce que l'esclave n'y entend plus la voix de son maître.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Toutes les fois que la voix qui commande se fait entendre alors qu'un arrangement praticable pourrait y substituer le silence, c'est un mal.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il tue dans l'âme la faculté qui y constitue la racine même de toute vocation surnaturelle.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La basse espèce d'attention exigée par le travail taylorisé n'est compatible avec aucune autre, parce qu'elle vide l'âme de tout ce qui n'est pas le souci de la vitesse.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ce genre de travail ne peut pas être transfiguré, il faut le supprimer.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Quiconque a éprouvé cet épuisement et ne l'a pas oublié peut le lire dans les yeux de presque tous les ouvriers qui défilent le soir hors de l'usine.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Les choses jouent le rôle des hommes, les hommes jouent le rôle des choses ; c'est la racine du mal.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ainsi chaque condition malheureuse parmi les hommes crée une zone de silence où les êtres humains se trouvent enfermés comme dans une île.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'usine devrait être un lieu de joie, un lieu où, même s'il est inévitable que le corps et l'âme souffrent, l'âme puisse aussi pourtant goûter des joies, se nourrir de joies.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le temps est une image de l'éternité, mais c'est aussi un ersatz de l'éternité.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Un critérium du réel, c'est que c'est dur et rugueux. On y trouve des joies, non de l'agrément. Ce qui est agréable est rêverie.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "C'est un grand danger que celui d'aimer Dieu comme un joueur aime le jeu.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'amour est un signe de notre misère. Dieu ne peut aimer que soi. Nous ne pouvons aimer qu'autre chose.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Aimer un étranger comme soi-même implique comme contrepartie: s'aimer soi-même comme un étranger.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Parmi les êtres humains, on ne reconnaît pleinement l'existence que de ceux qu'on aime.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Aimer purement, c'est consentir à la distance, c'est adorer la distance entre soi et ce qu'on aime.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Je ne dois pas aimer ma souffrance parce qu'elle est utile, mais parce qu'elle 'est'.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le malheur contraint à reconnaître comme réel ce qu'on ne croit pas possible.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Là est la véritable preuve que le christianisme est quelque chose de divin.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Dieu ne peut être présent dans la création que sous la forme de l'absence.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Essayer de remédier aux fautes par l'attention et non par la volonté.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'attention, à son plus haut degré, est la même chose que la prière. Elle suppose la foi et l'amour.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Considérer toujours les hommes au pouvoir comme des 'choses' dangereuses.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il faut éliminer le malheur autant qu'on le peut de la vie sociale, car le malheur ne sert qu'à la grâce et la société n'est pas une société d'élus.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il y aura toujours assez de malheur pour les élus.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Écarter les croyances combleuses de vides, adoucisseuses des amertumes.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Aimer Dieu à travers la destruction de Troie et de Carthage, et sans consolation.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'amour n'est pas consolation, il est lumière.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La connaissance de la misère humaine est difficile au riche, au puissant, parce qu'il est presque invinciblement porté à croire qu'il est quelque chose.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Elle est également difficile au misérable parce qu'il est presque invinciblement porté à croire que le riche, le puissant est quelques chose.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Nous savons au moyen de l'intelligence que ce que l'intelligence n'appréhende pas est plus réel que ce qu'elle appréhende.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La foi ne doit-elle pas être adhésion de cette espèce ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On dégrade les mystères de la foi en en faisant un objet d'affirmation ou de négation, alors qu'ils doivent être un objet de contemplation.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le beau est le nécessaire, qui, tout en demeurant conforme à sa loi propre et à elle seule, obéit au bien.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Faire l'inventaire ou la critique de notre civilisation, qu'est-ce à dire ? Chercher à tirer au clair d'une manière précise le piège qui a fait de l'homme l'esclave de ses propres créations.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Par où s'est infiltrée l'inconscience dans la pensée et l'action méthodiques ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'évasion dans la vie sauvage est une solution paresseuse.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il faut retrouver le pacte originel entre l'esprit et le monde dans la civilisation où nous vivons.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "C'est une tâche au reste impossible à accomplir à cause de la brièveté de la vie et de l'impossibilité de la collaboration et de la succession.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ce n'est pas une raison pour ne pas l'entreprendre.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'homme est esclave pour autant qu'entre l'action et son effet, entre l'effort et l'œuvre, se trouve placée l'intervention de volontés étrangères.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le totalitarisme moderne est au totalitarisme catholique du XIIe siècle ce qu'est l'esprit laïque et franc-maçon à l'humanisme de la renaissance.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'humanité se dégrade à chaque oscillation. Jusqu'où cela ira-t-il ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Après l'écroulement de notre civilisation, de deux choses l'une : ou elle périra tout entière comme les civilisations antiques, ou elle s'adaptera à un monde décentralisé.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il dépend de nous, non pas de briser la centralisation (car elle fait automatiquement boule de neige jusqu'à la catastrophe) mais de préparer l'avenir.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Notre époque a détruit la hiérarchie intérieure. Comment laisserait-elle subsister la hiérarchie sociale qui n'en est qu'une image grossière ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Tu ne pourrais être née à une meilleure époque que celle-ci où on a tout perdu.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Faire effort par nécessité et non pour un bien — poussé, non attiré — pour maintenir son existence telle qu'elle est — c'est toujours servitude.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "En ce sens, la servitude des travailleurs manuels est irréductible.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Effort sans finalité.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "C'est terrible — ou plus beau que tout — si c'est finalité sans fin.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Le beau seul permet d'être satisfait de ce qui est.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Les travailleurs ont besoin de poésie plus que de pain. Besoin que leur vie soit une poésie. Besoin d'un lumière d'éternité.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Seule la religion peut être source de cette poésie.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ce n'est pas la religion, c'est la révolution qui est l'opium du peuple.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La privation de cette poésie explique toutes les formes de démoralisation.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Un homme qui serait seul dans l'univers n'aurait aucun droit, mais seulement des obligations.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Des obligations identiques lient tous les êtres humains, bien qu'elles correspondent à des actes différents selon les situations.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'imperfection d'un ordre social se mesure à la quantité de situations de ce genre qu'il enferme.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Pour un tel voyageur, il y a une grande espérance.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Aider la France à trouver au fond de son malheur une inspiration conforme à son génie et aux besoins actuels des hommes en détresse.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Répandre cette inspiration, une fois retrouvée ou du moins entrevue, à travers le monde.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'unique source de salut et de grandeur pour la France, c'est de reprendre contact avec son génie au fond de son malheur.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Si l'on admire l'Empire romain, pourquoi en vouloir à l'Allemagne qui essaie de le reconstituer, sur un territoire plus vaste, avec des méthodes presque identiques ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La vérité n'est pas un objet d'amour.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Ce qu'on aime, c'est quelque chose qui existe, que l'on pense, et qui par là peut être occasion de vérité ou d'erreur.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Une vérité est toujours la vérité de quelque chose.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La vérité est l'éclat de la réalité.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Désirer la vérité, c'est désirer un contact avec une réalité, c'est l'aimer.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On ne désire la vérité que pour aimer dans la vérité.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On désire connaître la vérité de ce qu'on aime.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Au lieu de parler d'amour de la vérité, il vaut mieux parler d'un esprit de vérité dans l'amour.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Jamais en aucun cas je ne consentirai à juger convenable pour un de mes semblables, quel qu'il soit, ce que je juge moralement intolérable pour moi-même.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On dit souvent que la force est impuissante à dompter la pensée ; mais pour que ce soit vrai, il faut qu'il y ait pensée.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Là où les opinions irraisonnées tiennent lieu d’idées, la force peut tout.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "En réalité c’est l’absence de pensée libre qui rend possible d’imposer par la force des doctrines officielles entièrement dépourvues de signification.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "De nos jours toute tentative pour abrutir les êtres humains trouve à sa disposition des moyens puissants.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "En revanche une chose est impossible, quand même on disposerait de la meilleure des tribunes ; à savoir diffuser largement les idées claires, des raisonnements corrects, des aperçus raisonnables.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'Église commet un abus de pouvoir quand elle prétend contraindre l'amour et l'intelligence à prendre son langage pour norme.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Cet abus de pouvoir ne procède pas de Dieu.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il vient de la tendance naturelle de toute collectivité, sans exception, aux abus de pouvoir.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On est toujours barbare envers les faibles.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Sauf au prix d'un effort de générosité aussi rare que le génie, on est toujours barbare envers les faibles.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Peut-on dire que nous avons apporté la culture aux Arabes, eux qui ont conservé pour nous les traditions grecques pendant le moyen âge ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "La civilisation européenne est une combinaison de l'esprit d'Orient avec son contraire, combinaison dans laquelle l'esprit d'Orient doit entrer dans une proportion assez considérable.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Nous avons besoin d'une injection d'esprit oriental.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'hitlérisme consiste dans l'application par l'Allemagne au continent européen, et plus généralement aux pays de race blanche, des méthodes de la conquête et de la domination coloniales.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Je n'oublierai jamais le moment où, pour la première fois, j'ai senti et compris la tragédie de la colonisation.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Depuis ce jour, j'ai honte de mon pays.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Car leur oppresseur, c'est l'État français, il le fait au nom de tous les Français, donc aussi, pour une petite part, en mon nom.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "C'est pourquoi, en présence de ceux que l'État français opprime, je ne peux pas ne pas rougir, je ne peux pas ne pas sentir que j'ai des fautes à racheter.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il n'y a pas de 'France éternelle', tout au moins en ce qui concerne la paix et la liberté.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Napoléon n'a pas inspiré au monde moins de terreur et d'horreur qu'Hitler, ni moins justement.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Oublie-t-on ce que la France a fait subir à la Hollande, à la Suisse, à l'Espagne ?", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il nous fait à présent horreur, et cette horreur est juste ; n'oublions pas pourtant qu'il est venu de chez nous.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L’influence de l’Ancien Testament et celle de l’Empire Romain, dont la tradition a été continuée par la papauté, sont à mon avis les deux causes essentielles de la corruption du christianisme.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "On ne peut pardonner que ce que l'on peut punir.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "L'enracinement reste peut-être le besoin le plus important de l'âme humaine.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Chaque être humain a besoin d'avoir de multiples racines.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il a besoin de recevoir la presque totalité de sa vie morale, intellectuelle, spirituelle par l'intermédiaire des milieux dont il fait naturellement partie.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Les échanges d'influence entre milieux très différents ne sont pas moins indispensables que l'enracinement dans l'entourage naturel.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Mais un milieu déterminé doit recevoir une influence extérieure non pas comme un apport mais comme un stimulant qui rende sa vie propre plus intense.", Author = "Simone Weil" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Simone_Weil", Text = "Il ne doit se nourrir des apports extérieurs qu'après les avoir digérés.", Author = "Simone Weil" },
        };
    }
}