using System;

namespace StdbModule;

public static partial class FrenchQuotes
{
    public static class ÉmileZola
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La haine est sainte. Elle est l'indignation des cœurs forts et puissants, le dédain militant de ceux que fâchent la médiocrité et la sottise. Haïr c'est aimer, c'est sentir son âme chaude et généreuse, c'est vivre largement du mépris des choses honteuses et bêtes. La haine soulage, la haine fait justice, la haine grandit.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Si je vaux quelque chose aujourd'hui, c'est que je suis seul et que je hais.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Je n'ai guère de souci de beauté ni de perfection. Je me moque des grands siècles. Je n'ai souci que de vie, de lutte, de fièvre. Je suis à l'aise parmi notre génération.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "J'aime les ragoûts littéraires fortement épicés, les œuvres de dédacence où une sorte de sensibilité maladive remplace la santé plantureuse des époques classiques. Je suis de mon âge.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La science du beau est une drôlerie inventée par les philosophes pour la plus grande hilarité des artistes.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Une œuvre d'art est un coin de la création vu à travers un tempérament.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La mort n'était bonne que parce qu'elle supprimait l'être d'un coup, pour toujours. Oh ! dormir comme les pierres, rentrer dans l'argile, n'être plus !", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La science a-t-elle promis le bonheur ? Je ne le crois pas. Elle a promis la vérité, et la question est de savoir si l’on fera jamais du bonheur avec de la vérité.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Paris flambait, ensemencé de lumière par le divin soleil, roulant dans sa gloire la moisson future de vérité et de justice.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Et c’est fini, la France a sur la joue cette souillure, l’histoire écrira que c’est sous votre présidence qu’un tel crime social a pu être commis. Puisqu’ils ont osé, j’oserai aussi, moi. La vérité, je la dirai, car j’ai promis de la dire, si la justice, régulièrement saisie, ne la faisait pas, pleine et entière. Mon devoir est de parler, je ne veux pas être complice. Mes nuits seraient hantées par le spectre de l’innocent qui expie là-bas, dans la plus affreuse des tortures, un crime qu’il n’a pas commis.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "L’idée supérieure de discipline, qui est dans le sang de ces soldats, ne suffit-elle à infirmer leur pouvoir d’équité ? Qui dit discipline dit obéissance.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "C’est un crime d’avoir accusé de troubler la France ceux qui la veulent généreuse, à la tête des nations libres et justes, lorsqu’on ourdit soi-même l’impudent complot d’imposer l’erreur, devant le monde entier. C’est un crime d’égarer l’opinion, d’utiliser pour une besogne de mort cette opinion qu'on a pervertie jusqu'à la faire délirer. C'est un crime d’empoisonner les petits et les humbles, d’exaspérer les passions de réaction et d’intolérance, en s’abritant derrière l’odieux antisémitisme, dont la grande France libérale des droits de l’homme mourra, si elle n’en est pas guérie. C’est un crime que d’exploiter le patriotisme pour des œuvres de haine, et c’est un crime, enfin, que de faire du sabre le dieu moderne, lorsque toute la science humaine est au travail pour l’œuvre prochaine de vérité et de justice.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La vérité est en marche et rien ne l’arrêtera.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Quand on enferme la vérité sous terre, elle s’y amasse, elle y prend une force telle d’explosion, que, le jour où elle éclate, elle fait tout sauter avec elle. On verra bien si l’on ne vient pas de préparer, pour plus tard, le plus retentissant des désastres.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Quant aux gens que j’accuse, je ne les connais pas, je ne les ai jamais vus, je n’ai contre eux ni rancune ni haine. Ils ne sont pour moi que des entités, des esprits de malfaisance sociale. Et l’acte que j’accomplis ici n’est qu’un moyen révolutionnaire pour hâter l’explosion de la vérité et de la justice. Je n’ai qu’une passion, celle de la lumière, au nom de l’humanité qui a tant souffert et qui a droit au bonheur. Ma protestation enflammée n’est que le cri de mon âme. Qu’on ose donc me traduire en cour d’assises et que l’enquête ait lieu au grand jour ! J’attends.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La vérité et la justice sont souveraines, car elles seules assurent la grandeur des nations.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Je veux expliquer comment une famille, un petit groupe d’êtres, se comporte dans une société, en s’épanouissant pour donner naissance à dix, à vingt individus, qui paraissent, au premier coup d’œil, profondément dissemblables, mais que l’analyse montre intimement liés les uns aux autres. L’hérédité a ses lois, comme la pesanteur.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Les sanglots d'un homme ont des sécheresses navrantes.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "L'Empire allait faire de Paris le mauvais lieu de l'Europe. Il fallait à cette poignée d’aventuriers qui venaient de voler un trône, un règne d’aventures, d’affaires véreuses, de consciences vendues, de femmes achetées, de soûlerie furieuse et universelle. Et, dans la ville où le sang de décembre était à peine lavé, grandissait, timide encore, cette folie de jouissance qui devait jeter la patrie au cabanon des nations pourries et déshonorées.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Sa vie se déroulait devant elle. Elle assistait à son long effarement, à ce tapage de l'or et de la chair qui était monté en elle, dont elle avait eu jusqu'aux genoux, jusqu'au ventre, puis jusqu'aux lèvres et dont elle sentait maintenant le flot passer sur sa tête, en lui battant le crâne à coups pressés. C'était comme une sève mauvaise.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Mon idéal, ce serait de travailler tranquille, de manger toujours du pain, d’avoir un trou un peu propre pour dormir, vous savez un lit, une table et deux chaises, pas davantage…", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "On peut bien mettre ce qu'on voudra, un roi, un empereur, rien du tout, ça ne m'empêchera pas de gagner mes cinq francs, de manger et de dormir, pas vrai ?… Non, c'est trop bête !", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Ah ! la crevaison des pauvres, les entrailles vides qui crient la faim, le besoin des bêtes claquant des dents et s'empiffrant de choses immondes, dans ce grand Paris si doré et si flambant !", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "La religion tolérait bien des faiblesses, quand on gardait les convenances.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "On n'aime bien que les femmes qu'on n'a pas eues.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Chaque fois que la science avance d'un pas, c'est qu'un imbécile la pousse, sans faire exprès.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Tout n'est que rêve.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Mais les bêtes sauvages restent des bêtes sauvages, et on aura beau inventer des mécaniques meilleures encore, il y aura quand même des bêtes sauvages dessous.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Il y avait là, en un groupe tumultueux, toute une juiverie malpropre, de grasses faces luisantes, des profils desséchés d’oiseaux voraces, une extraordinaire réunion de nez typiques, rapprochés les uns des autres, ainsi que sur une proie, s’acharnant au milieu de cris gutturaux, et comme près de se dévorer entre eux.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Elle ignorait [...] les histoires de sa royale fortune [...], toute une vie de vols effroyables, non plus au coin des bois, à main armée, comme les nobles aventuriers de jadis, mais en correct bandit moderne, au clair soleil de la Bourse, dans la poche du pauvre monde crédule, parmi les effondrements et la mort.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "L'idée de charité le blessait, le jetait hors de lui : la charité c'était l'aumône, l'inégalité consacrée par la bonté ; et il n'admettait que la justice, les droits de chacun reconquis, posés en immuables principes de la nouvelle organisation sociale.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Oui, demain est aux grands capitaux, aux efforts centralisés des grandes masses. Toute l'industrie, tout le commerce, finiront par n'être qu'un immense bazar unique, où l'on s'approvisionnera de tout.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Voyez-vous, il faut comprendre papa. II n'est pas, mon Dieu! pire que les autres. Seulement, ses enfants, ses femmes, enfin tout ce qui l'entoure, ça ne passe pour lui qu'après l'argent... Oh! entendons-nous, il n'aime pas l'argent en avare, pour en avoir un gros tas, pour le cacher dans sa cave. Non! s'il en veut faire jaillir de partout, s'il en puise à n'importe quelles sources, c'est pour le voir couler chez lui en torrents, c'est pour toutes les jouissances qu'il en tire, de luxe, de plaisir, de puissance... Que voulez-vous? il a ça dans le sang. Il nous vendrait, vous, moi, n'importe qui, si nous entrions dans quelque marché. Et cela en homme inconscient et supérieur, car il est vraiment le poète du million, tellement l'argent le rend fou et canaille, oh! canaille dans le très grand !", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "L'argent [est] le fumier dans lequel pousse l'humanité de demain. [...] L'argent, empoisonneur et destructeur, devenait le ferment de toute végétation sociale, servait de terreau nécessaire aux grands travaux dont l'exécution rapprocherait les peuples et pacifierait la terre.", Author = "Émile Zola" },
            new Quote { Id = "https://fr.wikiquote.org/wiki/Émile_Zola", Text = "Aucun bonheur n'est possible dans l'ignorance, la certitude seule fait la vie calme.", Author = "Émile Zola" },
        };
    }
}