export enum RelicType {
  EmbercrestBlade,
  BriarthornSaber,
  RavenplumeEdge,
  RubyguardGreatsword,
  SunfireScimitar,
  CloudveilLongsword,
  VoidthornBlade,
  GildedPlumeblade,
  GlacialCrusader,
  BloodthornDirk,
  TwinflareCrossblades,
  MoltenZweihander,
  FrostfangClaymore,
  SporesparkGlaive,
  AzureCrescent,
  RosevineRapier,
  CrystalbreakSaber,
  CinderstoneBlade,
  EmeraldFang,
  StarfallStiletto,
  CrimsonCleaver,
  TigerstripeFalchion,
  DawnfireCutlass,
  JadecrossBroadsword,
  ChainlinkEstoc,
  PermafrostGreatsword,
  MistralSabre,
  TidecallerBlade,
  SolarisEdge,
  InfernalRavager,
  SteelBattleaxe,
  MoonlitHatchet,
  ObsidianReaver,
  RubyflareGreataxe,
  GildedWaraxe,
  CopperheadCleaver,
  BonecrestAxe,
  DarkwoodHatchet,
  DuskforgeHalberd,
  RosegoldBroadaxe,
  FrostbiteCleaver,
  BloodmoonReaver,
  TidebreakAxe,
  IronwoodTomahawk,
  GreystoneBroadaxe,
  SandstoneHatchet,
  CrimsonWaraxe,
  GoldscarHalberd,
  FlamecrestGreataxe,
  WroughtIronChopper,
  SpectralCleaver,
  BloodruneAxe,
  PearlsteelHatchet,
  EmberstrikeTomahawk,
  NightbloomReaver,
  BlackironSplitter,
  VerdantWaraxe,
  AshenBroadaxe,
  PrismaticGreataxe,
  HellforgedCleaver,
  GraniteWaraxe,
}

export interface RelicTypeConfig {
  charsToFire: number;
  projectileSpeed: number;
  damage: number;
  bleedApplicationChance: number;
  plasmaStacks: number;
  slowStacks: number;
  freezeStacks: number;
  chargesNeighbors: boolean;
  chainCount: number;
  explosionRange: number;
  multiShotCount: number;
  damageBuffIndexes: number[];
  damageBuffAll: boolean;
  damageBuffMultiplier: number;
}

export const RELIC_DEFAULTS: RelicTypeConfig = {
  charsToFire: 4,
  projectileSpeed: 800,
  damage: 10,
  bleedApplicationChance: 0,
  plasmaStacks: 0,
  slowStacks: 0,
  freezeStacks: 0,
  chargesNeighbors: false,
  chainCount: 0,
  explosionRange: 0,
  multiShotCount: 1,
  damageBuffIndexes: [],
  damageBuffAll: false,
  damageBuffMultiplier: 0,
};

function relic(overrides: Partial<RelicTypeConfig>): RelicTypeConfig {
  return { ...RELIC_DEFAULTS, ...overrides };
}

export const RELIC_CONFIGS: Record<RelicType, RelicTypeConfig> = {
  [RelicType.EmbercrestBlade]: relic({ damage: 0, bleedApplicationChance: 0.50, plasmaStacks: 3 }),
  [RelicType.BriarthornSaber]: relic({ damage: 0, slowStacks: 4, plasmaStacks: 2 }),
  [RelicType.RavenplumeEdge]: relic({ charsToFire: 2, damage: 3, projectileSpeed: 1200 }),
  [RelicType.RubyguardGreatsword]: relic({ charsToFire: 8, damage: 35 }),
  [RelicType.SunfireScimitar]: relic({ damage: 0, bleedApplicationChance: 0.80, projectileSpeed: 600 }),
  [RelicType.CloudveilLongsword]: relic({ damage: 0, slowStacks: 8 }),
  [RelicType.VoidthornBlade]: relic({ damage: 0, chainCount: 3, plasmaStacks: 3 }),
  [RelicType.GildedPlumeblade]: relic({ damage: 0, damageBuffAll: true, damageBuffMultiplier: 0.15 }),
  [RelicType.GlacialCrusader]: relic({ charsToFire: 6, damage: 0, freezeStacks: 6 }),
  [RelicType.BloodthornDirk]: relic({ charsToFire: 2, damage: 0, bleedApplicationChance: 0.25, chainCount: 1 }),
  [RelicType.TwinflareCrossblades]: relic({ charsToFire: 6, damage: 5, multiShotCount: 3 }),
  [RelicType.MoltenZweihander]: relic({ charsToFire: 10, damage: 20, explosionRange: 80 }),
  [RelicType.FrostfangClaymore]: relic({ charsToFire: 7, damage: 0, freezeStacks: 4, slowStacks: 6 }),
  [RelicType.SporesparkGlaive]: relic({ damage: 0, plasmaStacks: 8 }),
  [RelicType.AzureCrescent]: relic({ damage: 5, chainCount: 3 }),
  [RelicType.RosevineRapier]: relic({ charsToFire: 2, damage: 0, slowStacks: 2 }),
  [RelicType.CrystalbreakSaber]: relic({ charsToFire: 5, damage: 0, explosionRange: 60, freezeStacks: 2 }),
  [RelicType.CinderstoneBlade]: relic({ damage: 5, chargesNeighbors: true, bleedApplicationChance: 0.20 }),
  [RelicType.EmeraldFang]: relic({ damage: 0, plasmaStacks: 6, slowStacks: 2 }),
  [RelicType.StarfallStiletto]: relic({ charsToFire: 2, damage: 2, chainCount: 1 }),
  [RelicType.CrimsonCleaver]: relic({ charsToFire: 6, damage: 15, bleedApplicationChance: 0.40 }),
  [RelicType.TigerstripeFalchion]: relic({ charsToFire: 3, damage: 4, chargesNeighbors: true, projectileSpeed: 1200 }),
  [RelicType.DawnfireCutlass]: relic({ damage: 0, damageBuffAll: true, damageBuffMultiplier: 0.12 }),
  [RelicType.JadecrossBroadsword]: relic({ charsToFire: 7, damage: 25, slowStacks: 3 }),
  [RelicType.ChainlinkEstoc]: relic({ charsToFire: 5, damage: 3, chainCount: 4 }),
  [RelicType.PermafrostGreatsword]: relic({ charsToFire: 9, damage: 0, freezeStacks: 10 }),
  [RelicType.MistralSabre]: relic({ damage: 0, slowStacks: 5, projectileSpeed: 1200 }),
  [RelicType.TidecallerBlade]: relic({ charsToFire: 5, damage: 0, slowStacks: 4, plasmaStacks: 4 }),
  [RelicType.SolarisEdge]: relic({ charsToFire: 6, damage: 0, damageBuffAll: true, damageBuffMultiplier: 0.25 }),
  [RelicType.InfernalRavager]: relic({ charsToFire: 10, damage: 15, explosionRange: 90, bleedApplicationChance: 0.60 }),
  [RelicType.SteelBattleaxe]: relic({ damage: 12 }),
  [RelicType.MoonlitHatchet]: relic({ charsToFire: 2, damage: 0, freezeStacks: 1 }),
  [RelicType.ObsidianReaver]: relic({ charsToFire: 6, damage: 10, chainCount: 2, bleedApplicationChance: 0.30 }),
  [RelicType.RubyflareGreataxe]: relic({ charsToFire: 8, damage: 12, explosionRange: 70, bleedApplicationChance: 0.50 }),
  [RelicType.GildedWaraxe]: relic({ damage: 5, damageBuffIndexes: [-1, 1], damageBuffMultiplier: 0.20 }),
  [RelicType.CopperheadCleaver]: relic({ damage: 0, bleedApplicationChance: 0.60, plasmaStacks: 2 }),
  [RelicType.BonecrestAxe]: relic({ damage: 0, chainCount: 2, plasmaStacks: 4 }),
  [RelicType.DarkwoodHatchet]: relic({ charsToFire: 3, damage: 4, chargesNeighbors: true }),
  [RelicType.DuskforgeHalberd]: relic({ charsToFire: 7, damage: 28 }),
  [RelicType.RosegoldBroadaxe]: relic({ damage: 0, damageBuffAll: true, damageBuffMultiplier: 0.12 }),
  [RelicType.FrostbiteCleaver]: relic({ damage: 0, freezeStacks: 3, slowStacks: 3 }),
  [RelicType.BloodmoonReaver]: relic({ charsToFire: 6, damage: 0, bleedApplicationChance: 0.80, chainCount: 2 }),
  [RelicType.TidebreakAxe]: relic({ charsToFire: 5, damage: 0, slowStacks: 10 }),
  [RelicType.IronwoodTomahawk]: relic({ charsToFire: 2, damage: 4, projectileSpeed: 1200 }),
  [RelicType.GreystoneBroadaxe]: relic({ charsToFire: 7, damage: 30, projectileSpeed: 500 }),
  [RelicType.SandstoneHatchet]: relic({ charsToFire: 3, damage: 0, chargesNeighbors: true, slowStacks: 2 }),
  [RelicType.CrimsonWaraxe]: relic({ damage: 0, bleedApplicationChance: 0.70, slowStacks: 2 }),
  [RelicType.GoldscarHalberd]: relic({ charsToFire: 8, damage: 8, chainCount: 4 }),
  [RelicType.FlamecrestGreataxe]: relic({ charsToFire: 9, damage: 10, explosionRange: 80, bleedApplicationChance: 0.40 }),
  [RelicType.WroughtIronChopper]: relic({ damage: 10, bleedApplicationChance: 0.15 }),
  [RelicType.SpectralCleaver]: relic({ charsToFire: 5, damage: 0, chainCount: 2, freezeStacks: 3 }),
  [RelicType.BloodruneAxe]: relic({ damage: 0, bleedApplicationChance: 0.40, plasmaStacks: 5 }),
  [RelicType.PearlsteelHatchet]: relic({ charsToFire: 2, damage: 0, plasmaStacks: 2 }),
  [RelicType.EmberstrikeTomahawk]: relic({ charsToFire: 2, damage: 2, bleedApplicationChance: 0.15 }),
  [RelicType.NightbloomReaver]: relic({ charsToFire: 5, damage: 0, chainCount: 3, plasmaStacks: 3 }),
  [RelicType.BlackironSplitter]: relic({ charsToFire: 8, damage: 5, multiShotCount: 5 }),
  [RelicType.VerdantWaraxe]: relic({ damage: 0, plasmaStacks: 4, slowStacks: 4 }),
  [RelicType.AshenBroadaxe]: relic({ charsToFire: 5, damage: 6, chargesNeighbors: true, bleedApplicationChance: 0.20 }),
  [RelicType.PrismaticGreataxe]: relic({ charsToFire: 10, damage: 5, multiShotCount: 6 }),
  [RelicType.HellforgedCleaver]: relic({ charsToFire: 7, damage: 12, explosionRange: 60, bleedApplicationChance: 0.30 }),
  [RelicType.GraniteWaraxe]: relic({ charsToFire: 6, damage: 20, projectileSpeed: 400 }),
};

export interface RelicDisplayInfo {
  spriteSheet: 'swordtember' | 'axetober';
  frameName: string;
}

export const RELIC_DISPLAY: Record<RelicType, RelicDisplayInfo> = {
  [RelicType.EmbercrestBlade]: { spriteSheet: 'swordtember', frameName: 'Embercrest Blade' },
  [RelicType.BriarthornSaber]: { spriteSheet: 'swordtember', frameName: 'Briarthorn Saber' },
  [RelicType.RavenplumeEdge]: { spriteSheet: 'swordtember', frameName: 'Ravenplume Edge' },
  [RelicType.RubyguardGreatsword]: { spriteSheet: 'swordtember', frameName: 'Rubyguard Greatsword' },
  [RelicType.SunfireScimitar]: { spriteSheet: 'swordtember', frameName: 'Sunfire Scimitar' },
  [RelicType.CloudveilLongsword]: { spriteSheet: 'swordtember', frameName: 'Cloudveil Longsword' },
  [RelicType.VoidthornBlade]: { spriteSheet: 'swordtember', frameName: 'Voidthorn Blade' },
  [RelicType.GildedPlumeblade]: { spriteSheet: 'swordtember', frameName: 'Gilded Plumeblade' },
  [RelicType.GlacialCrusader]: { spriteSheet: 'swordtember', frameName: 'Glacial Crusader' },
  [RelicType.BloodthornDirk]: { spriteSheet: 'swordtember', frameName: 'Bloodthorn Dirk' },
  [RelicType.TwinflareCrossblades]: { spriteSheet: 'swordtember', frameName: 'Twinflare Crossblades' },
  [RelicType.MoltenZweihander]: { spriteSheet: 'swordtember', frameName: 'Molten Zweihander' },
  [RelicType.FrostfangClaymore]: { spriteSheet: 'swordtember', frameName: 'Frostfang Claymore' },
  [RelicType.SporesparkGlaive]: { spriteSheet: 'swordtember', frameName: 'Sporespark Glaive' },
  [RelicType.AzureCrescent]: { spriteSheet: 'swordtember', frameName: 'Azure Crescent' },
  [RelicType.RosevineRapier]: { spriteSheet: 'swordtember', frameName: 'Rosevine Rapier' },
  [RelicType.CrystalbreakSaber]: { spriteSheet: 'swordtember', frameName: 'Crystalbreak Saber' },
  [RelicType.CinderstoneBlade]: { spriteSheet: 'swordtember', frameName: 'Cinderstone Blade' },
  [RelicType.EmeraldFang]: { spriteSheet: 'swordtember', frameName: 'Emerald Fang' },
  [RelicType.StarfallStiletto]: { spriteSheet: 'swordtember', frameName: 'Starfall Stiletto' },
  [RelicType.CrimsonCleaver]: { spriteSheet: 'swordtember', frameName: 'Crimson Cleaver' },
  [RelicType.TigerstripeFalchion]: { spriteSheet: 'swordtember', frameName: 'Tigerstripe Falchion' },
  [RelicType.DawnfireCutlass]: { spriteSheet: 'swordtember', frameName: 'Dawnfire Cutlass' },
  [RelicType.JadecrossBroadsword]: { spriteSheet: 'swordtember', frameName: 'Jadecross Broadsword' },
  [RelicType.ChainlinkEstoc]: { spriteSheet: 'swordtember', frameName: 'Chainlink Estoc' },
  [RelicType.PermafrostGreatsword]: { spriteSheet: 'swordtember', frameName: 'Permafrost Greatsword' },
  [RelicType.MistralSabre]: { spriteSheet: 'swordtember', frameName: 'Mistral Sabre' },
  [RelicType.TidecallerBlade]: { spriteSheet: 'swordtember', frameName: 'Tidecaller Blade' },
  [RelicType.SolarisEdge]: { spriteSheet: 'swordtember', frameName: 'Solaris Edge' },
  [RelicType.InfernalRavager]: { spriteSheet: 'swordtember', frameName: 'Infernal Ravager' },
  [RelicType.SteelBattleaxe]: { spriteSheet: 'axetober', frameName: 'Steel Battleaxe' },
  [RelicType.MoonlitHatchet]: { spriteSheet: 'axetober', frameName: 'Moonlit Hatchet' },
  [RelicType.ObsidianReaver]: { spriteSheet: 'axetober', frameName: 'Obsidian Reaver' },
  [RelicType.RubyflareGreataxe]: { spriteSheet: 'axetober', frameName: 'Rubyflare Greataxe' },
  [RelicType.GildedWaraxe]: { spriteSheet: 'axetober', frameName: 'Gilded Waraxe' },
  [RelicType.CopperheadCleaver]: { spriteSheet: 'axetober', frameName: 'Copperhead Cleaver' },
  [RelicType.BonecrestAxe]: { spriteSheet: 'axetober', frameName: 'Bonecrest Axe' },
  [RelicType.DarkwoodHatchet]: { spriteSheet: 'axetober', frameName: 'Darkwood Hatchet' },
  [RelicType.DuskforgeHalberd]: { spriteSheet: 'axetober', frameName: 'Duskforge Halberd' },
  [RelicType.RosegoldBroadaxe]: { spriteSheet: 'axetober', frameName: 'Rosegold Broadaxe' },
  [RelicType.FrostbiteCleaver]: { spriteSheet: 'axetober', frameName: 'Frostbite Cleaver' },
  [RelicType.BloodmoonReaver]: { spriteSheet: 'axetober', frameName: 'Bloodmoon Reaver' },
  [RelicType.TidebreakAxe]: { spriteSheet: 'axetober', frameName: 'Tidebreak Axe' },
  [RelicType.IronwoodTomahawk]: { spriteSheet: 'axetober', frameName: 'Ironwood Tomahawk' },
  [RelicType.GreystoneBroadaxe]: { spriteSheet: 'axetober', frameName: 'Greystone Broadaxe' },
  [RelicType.SandstoneHatchet]: { spriteSheet: 'axetober', frameName: 'Sandstone Hatchet' },
  [RelicType.CrimsonWaraxe]: { spriteSheet: 'axetober', frameName: 'Crimson Waraxe' },
  [RelicType.GoldscarHalberd]: { spriteSheet: 'axetober', frameName: 'Goldscar Halberd' },
  [RelicType.FlamecrestGreataxe]: { spriteSheet: 'axetober', frameName: 'Flamecrest Greataxe' },
  [RelicType.WroughtIronChopper]: { spriteSheet: 'axetober', frameName: 'Wrought Iron Chopper' },
  [RelicType.SpectralCleaver]: { spriteSheet: 'axetober', frameName: 'Spectral Cleaver' },
  [RelicType.BloodruneAxe]: { spriteSheet: 'axetober', frameName: 'Bloodrune Axe' },
  [RelicType.PearlsteelHatchet]: { spriteSheet: 'axetober', frameName: 'Pearlsteel Hatchet' },
  [RelicType.EmberstrikeTomahawk]: { spriteSheet: 'axetober', frameName: 'Emberstrike Tomahawk' },
  [RelicType.NightbloomReaver]: { spriteSheet: 'axetober', frameName: 'Nightbloom Reaver' },
  [RelicType.BlackironSplitter]: { spriteSheet: 'axetober', frameName: 'Blackiron Splitter' },
  [RelicType.VerdantWaraxe]: { spriteSheet: 'axetober', frameName: 'Verdant Waraxe' },
  [RelicType.AshenBroadaxe]: { spriteSheet: 'axetober', frameName: 'Ashen Broadaxe' },
  [RelicType.PrismaticGreataxe]: { spriteSheet: 'axetober', frameName: 'Prismatic Greataxe' },
  [RelicType.HellforgedCleaver]: { spriteSheet: 'axetober', frameName: 'Hellforged Cleaver' },
  [RelicType.GraniteWaraxe]: { spriteSheet: 'axetober', frameName: 'Granite Waraxe' },
};

export const RELIC_SLOT_COUNT = 8;
export const RELIC_ORBIT_RADIUS = 160;
