import type { EntityType } from "./types";

export interface GunPosition {
  x: number;
  y: number;
}

export interface ShipWeaponConfig {
  range: number;
  fireRate: number;
  damage: number;
  projectileSpeed: number;
  projectileType: number;
  gunPositions: GunPosition[];
}

const SHIP_SCALE = 3;

function gun(x: number, y: number): GunPosition {
  return { x: x * SHIP_SCALE, y: y * SHIP_SCALE };
}

function weapon(overrides: Partial<ShipWeaponConfig> & { projectileType: number; gunPositions: GunPosition[] }): ShipWeaponConfig {
  return {
    range: 150,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 200,
    ...overrides,
  };
}

export const SHIP_WEAPON_CONFIGS: Partial<Record<EntityType, ShipWeaponConfig>> = {
  Vanguard: weapon({
    range: 260,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 250,
    projectileType: 6,
    gunPositions: [gun(14, -6), gun(14, 6)],
  }),
  Sentinel: weapon({
    range: 250,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(9, -8)],
  }),
  Corsair: weapon({
    range: 240,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(15, -5), gun(15, 5)],
  }),
  Falcon: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(14, 0)],
  }),
  Scout: weapon({
    range: 160,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Dart: weapon({
    range: 150,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Wasp: weapon({
    range: 140,
    fireRate: 2.5,
    damage: 1,
    projectileSpeed: 210,
    projectileType: 3,
    gunPositions: [gun(11, 0)],
  }),
  Phoenix: weapon({
    range: 250,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(12, -6), gun(12, 6)],
  }),
  Hawk: weapon({
    range: 190,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(12, 0)],
  }),
  Sparrow: weapon({
    range: 140,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Gnat: weapon({
    range: 100,
    fireRate: 3.5,
    damage: 1,
    projectileSpeed: 180,
    projectileType: 1,
    gunPositions: [gun(8, 0)],
  }),
  Stinger: weapon({
    range: 140,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 210,
    projectileType: 3,
    gunPositions: [gun(11, 0)],
  }),
  Needle: weapon({
    range: 130,
    fireRate: 2.5,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 2,
    gunPositions: [gun(10, 0)],
  }),
  Mite: weapon({
    range: 90,
    fireRate: 4,
    damage: 1,
    projectileSpeed: 170,
    projectileType: 1,
    gunPositions: [gun(7, 0)],
  }),
  Titan: weapon({
    range: 260,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 250,
    projectileType: 6,
    gunPositions: [gun(15, -7), gun(15, 7)],
  }),
  Raptor: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 230,
    projectileType: 4,
    gunPositions: [gun(12, 0)],
  }),
  Lance: weapon({
    range: 220,
    fireRate: 3,
    damage: 2,
    projectileSpeed: 250,
    projectileType: 5,
    gunPositions: [gun(16, 0)],
  }),
  Javelin: weapon({
    range: 230,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 260,
    projectileType: 5,
    gunPositions: [gun(18, 0)],
  }),
  Pip: weapon({
    range: 80,
    fireRate: 4,
    damage: 1,
    projectileSpeed: 160,
    projectileType: 1,
    gunPositions: [gun(6, 0)],
  }),
  Raven: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(12, 0)],
  }),
  Osprey: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(10, -6)],
  }),
  Leviathan: weapon({
    range: 270,
    fireRate: 2,
    damage: 2,
    projectileSpeed: 260,
    projectileType: 6,
    gunPositions: [gun(22, -8), gun(24, 0), gun(22, 8)],
  }),
  Talon: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(12, 0)],
  }),
  Hornet: weapon({
    range: 140,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 210,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Behemoth: weapon({
    range: 260,
    fireRate: 2.2,
    damage: 2,
    projectileSpeed: 250,
    projectileType: 6,
    gunPositions: [gun(15, -8), gun(15, 8)],
  }),
  Dreadnought: weapon({
    range: 270,
    fireRate: 1.8,
    damage: 2,
    projectileSpeed: 260,
    projectileType: 6,
    gunPositions: [gun(27, -8), gun(28, -3), gun(28, 3), gun(27, 8)],
  }),
  Marauder: weapon({
    range: 230,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 5,
    gunPositions: [gun(18, -6), gun(18, 6)],
  }),
  Eagle: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(13, 0)],
  }),
  Pike: weapon({
    range: 150,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 2,
    gunPositions: [gun(9, 0)],
  }),
  Arrow: weapon({
    range: 150,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 3,
    gunPositions: [gun(11, 0)],
  }),
  Juggernaut: weapon({
    range: 260,
    fireRate: 2.2,
    damage: 2,
    projectileSpeed: 250,
    projectileType: 6,
    gunPositions: [gun(17, -8), gun(17, 8)],
  }),
  Warden: weapon({
    range: 250,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(15, -7), gun(15, 7)],
  }),
  Specter: weapon({
    range: 210,
    fireRate: 3,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(9, 0)],
  }),
  Harrier: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(13, 0)],
  }),
  Viper: weapon({
    range: 210,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(11, 0)],
  }),
  Flea: weapon({
    range: 100,
    fireRate: 3.5,
    damage: 1,
    projectileSpeed: 180,
    projectileType: 1,
    gunPositions: [gun(7, 0)],
  }),
  Broadside: weapon({
    range: 250,
    fireRate: 2.2,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(16, -8), gun(18, 0), gun(16, 8)],
  }),
  Kestrel: weapon({
    range: 190,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(12, 0)],
  }),
  Finch: weapon({
    range: 130,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 2,
    gunPositions: [gun(9, 0)],
  }),
  Striker: weapon({
    range: 210,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(13, 0)],
  }),
  Robin: weapon({
    range: 120,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 190,
    projectileType: 2,
    gunPositions: [gun(10, 0)],
  }),
  Cricket: weapon({
    range: 120,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 190,
    projectileType: 2,
    gunPositions: [gun(10, 0)],
  }),
  Moth: weapon({
    range: 110,
    fireRate: 3.5,
    damage: 1,
    projectileSpeed: 180,
    projectileType: 2,
    gunPositions: [gun(9, 0)],
  }),
  Colossus: weapon({
    range: 270,
    fireRate: 1.8,
    damage: 2,
    projectileSpeed: 260,
    projectileType: 6,
    gunPositions: [gun(18, -10), gun(19, 0), gun(18, 10)],
  }),
  Cutlass: weapon({
    range: 230,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 5,
    gunPositions: [gun(16, -5), gun(16, 5)],
  }),
  Sabre: weapon({
    range: 230,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 5,
    gunPositions: [gun(16, -6), gun(16, 6)],
  }),
  Mantis: weapon({
    range: 200,
    fireRate: 2.8,
    damage: 1,
    projectileSpeed: 220,
    projectileType: 4,
    gunPositions: [gun(11, 0)],
  }),
  Speck: weapon({
    range: 80,
    fireRate: 4,
    damage: 1,
    projectileSpeed: 160,
    projectileType: 1,
    gunPositions: [gun(7, 0)],
  }),
  Crest: weapon({
    range: 170,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 210,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Piston: weapon({
    range: 210,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(11, 0)],
  }),
  Vulture: weapon({
    range: 210,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(12, 0)],
  }),
  Orb: weapon({
    range: 160,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 3,
    gunPositions: [gun(10, 0)],
  }),
  Flicker: weapon({
    range: 100,
    fireRate: 3.5,
    damage: 1,
    projectileSpeed: 180,
    projectileType: 1,
    gunPositions: [gun(9, 0)],
  }),
  Barb: weapon({
    range: 110,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 190,
    projectileType: 2,
    gunPositions: [gun(12, 0)],
  }),
  Sliver: weapon({
    range: 120,
    fireRate: 3.2,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 2,
    gunPositions: [gun(11, 0)],
  }),
  Flagship: weapon({
    range: 270,
    fireRate: 1.5,
    damage: 3,
    projectileSpeed: 270,
    projectileType: 6,
    gunPositions: [gun(17, -8), gun(19, 0), gun(17, 8)],
  }),
  Aegis: weapon({
    range: 250,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(12, 0)],
  }),
  Bolt: weapon({
    range: 120,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 200,
    projectileType: 2,
    gunPositions: [gun(11, 0)],
  }),
  Spur: weapon({
    range: 110,
    fireRate: 3,
    damage: 1,
    projectileSpeed: 190,
    projectileType: 2,
    gunPositions: [gun(12, 0)],
  }),
  Dot: weapon({
    range: 80,
    fireRate: 4,
    damage: 1,
    projectileSpeed: 160,
    projectileType: 1,
    gunPositions: [gun(9, 0)],
  }),
  Rampart: weapon({
    range: 250,
    fireRate: 2.5,
    damage: 2,
    projectileSpeed: 240,
    projectileType: 6,
    gunPositions: [gun(13, -5), gun(13, 5)],
  }),
  Clipper: weapon({
    range: 210,
    fireRate: 2.8,
    damage: 2,
    projectileSpeed: 230,
    projectileType: 5,
    gunPositions: [gun(10, 0)],
  }),
};
