using System;

namespace StdbModule;

public static partial class DutchQuotes
{
    public static class DimitriVerhulst
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Geen geluk ontslaat de mens van zijn verdriet.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Mijn moeder had een zeer Vlaamse en poëtische smaak wat mannen betrof, hoewel ik mij kan voorstellen dat ze dat zelf moet hebben betreurd. Op vrijersvoeten sloeg ze steeds een postbode aan de haak. Vijf postbodes zijn aan mijn vader voorafgegaan, hij was de zesde facteur in haar leven en diegene waardoor ze haar lotsbestemming eindelijk leek te hebben aanvaard. Tien jaar en een hoop aframmelingen later hertrouwde ze met een een kermiscourreur uit het op alle vlakken ontgoochelende geslacht van de familie Bloemkool.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "In de hoek van de kroeg staat een nagemaakt oerwoud in een glazen bak, volgens de uitbater zitten er twee leguanen in. Perfect gecamoufleerd.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Er overvalt mij een gevoel van dinsdagheid. Hier is het dinsdag, alle dagen, ik weet het zeker. Dit is een dinsdags land.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Het lekkere wijf dat ze in het vizier kregen, waar ze het meteen over hadden en die ze best eens manhaftig op hun knie wensten te leggen, stond aan de deur, en was toevallig mijn lief.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Mijn vader was een prachtige vrouw, zijn benen waren die van een passer maar ze dichthouden kon hij niet.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Alles wat de Aalstenaar op de maag ligt moet eruit, langs alle gaten, in alle geuren, tegen gevels en deuren.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Wanneer Aalst, het Aalst dat ik liefheb, mijn Aalst dat ik haat, zich opmaakt voor carnaval, trek ik de kleerkast van een ander open, en keer ik weer.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Het is waar dat mijn tante Rosie een zeldzaam mooie vrouw was en dat het veel prestige opleverde met haar naar bed te zijn geweest.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "In een cafetaria vol lekkende mensen, en jengelende kinderen die andere bezoekers hadden meegebracht, ter compensatie, of om er de nadruk op te leggen dat het leven van de oude doorgegeven was, als stokjes in een eeuwige estafette waar niemand de zin van kent maar waar men zich aan vastklampt in de grote helaasheid der dingen.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "De schaaltjes met rattenvergif werden dagelijks bijgevuld; meer dan wij de indruk hadden deze nesten ongedierte uit te moorden kregen wij het gevoel uitstekend voor deze beestjes te zorgen.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Palmier had alles van een zeemeermin: ze was slank en stonk naar vis.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Herinnering is de troostende stuiptrek van een leven, een hogere soort van nageboorte.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "U moet me maar vergeven dat ik het zo cru stel, maar uw man zou het mij gemakkelijker gemaakt hebben door zich op te hangen aan een spar.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "zij maakte de stap van maagd naar moeder in één veel te kortstondige omstrengeling.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Omdat de wereld in die richting was geëvolueerd dat men een cijfercombinatie had te onthouden om z’n eigen geld uit een muur te halen.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Liefdeslang en niet langer zou een leven mogen duren.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "In alle goeie herinneringen groeiden gloriasas en stonden de ganzeriken perzikroze.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Hoewel zijn vader zich op vrij jonge leeftijd aan een tak had opgeknoopt, bezat Meneer Pottenbakker aandoenlijk weinig verstand van bomen.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Het bospad, waarvan de hellingsgraad en de onbegaanbaarheid van dien aard waren, dat ’s weekends allerlei gekken zich er op een mountainbike naar boven werkten, kerels die meenden dat het afbeulen van het lichaam de prijs was die de dood kwam beuren voor een lang en lenig leven. Eenmaal boven zagen ze bleek en dronken ze sterkende limonades in vieze kleuren, maar de inspanning had hun ongetwijfeld de moed gegeven om weer een week plaats te nemen aan een bureau waar de kamerplanten herinneringen opriepen aan de natuurdocumentaires waarmee ze ’s avonds hun atavismen troosten.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Alle begin is moeilijk. Kijk maar. ’t Kruipt uit het water zonder om te zien. ’t Zou nog een laatste blik kunnen werpen op de oceanen, heimwee voelen uit eerbied, maar dat doet ’t niet.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "’t Moet zich ontdoen van alle sentimentaliteit, want het ene wezen drinkt het bloed van het andere, zo steekt de natuur tenslotte ineen, en waar het op aankomt is de drinker te zijn, niet de drank.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Is de put dichtgesmeten, dan is de dode alreeds vergeten en sjeest ’t verder op het spoor van de evolutie.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Zo gaat dat in de moderne tijd; is de voorraad op dan boort ’t elders wel een nieuwe aan.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Want eens de stromen met woorden zullen zijn opgedroogd, zal ’t zijn eigen einde ruiken. Het einde van de woorden, dat is de dood.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Als er achter iets een groot en sterk karakter kon worden bevroed, dan zeker achter het vermogen om te kunnen zwijgen. De geschiedeniskronieken mochten eventueel nog wel een opeenstapeling zijn van grote redenaars en hun speeches, en wijsgeren mochten misschien met veel stelligheid beweren dat mondigheid het middel is waarmee de mens zich van zijn verstand bedient; de staat van waarachtige grootheid wordt pas bereikt door te zwijgen. Dat wisten tevens de kartuizers die hun dagen dan ook in volkomen stilte sleten. Niet uit devote nederigheid, ook al lijkt het daar op het eerste zicht heel sterk op, maar net vanuit een zekere pretentie boven het gewauwel te kunnen staan.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Hoewel volkomen opzettelijk, is het zeer tegen mijn zin dat ik iedere dag opnieuw in mijn bed schijt.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Jouw kapsel, voor zover dat nog een kapsel mocht worden genoemd, had veel weg van zo’n in die dagen in zwang rakende ecologische tuin, waarin elke menselijke ingreep als een misdaad tegen de natuur werd beschouwd", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Op het gevaar af sarcastisch te worden: het zien van een lijkwagen voor de kerk was een bevrijding. Een mooie wagen, een Daimler, en vast de mooiste waarin Gianna ooit moet zijn vervoerd. (…) Een mestkar ware wat haar betrof ook prima, en misschien zelfs betekenisdragender geweest.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Kenden jullie een belachelijker woord dan ‘mama’? Alles was goed voor jullie: moeder, mater, moesje, moer, hoer, mère. Het mens diende ergens mee te worden aangesproken. Desnoods met haar botte burgernaam. Maar ‘mama’ was er over.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Ieder hotel ter wereld zou elders kunnen staan, ze sluiten de stad uit waarin ze liggen, ze zijn universeel omdat ze overal ergens een stuk nergens zijn.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Vlamingen lezen niet. Ja, alleen in november, dan is het Boekenbeurs en doen ze alsof ze zot zijn op boeken. Kookboeken, bij de meesten.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Ik moet niet nastreven dat ik in het Nederlands schrijf, maar in het Verhulsts.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Geluk is een van de weinige grote uitdagingen die er nog liggen in de literatuur.", Author = "Dimitri Verhulst" },
            new Quote { Id = "https://nl.wikiquote.org/wiki/Dimitri_Verhulst", Text = "Ik kan sociaal zijn, maar ik kan ook intens schijten op de mens.", Author = "Dimitri Verhulst" },
        };
    }
}