using System;

namespace StdbModule;

public static partial class HindiQuotes
{
    public static class परमचद
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दुनिया में हर चीज़ का मोल हो सकता है, सिवाए अपनी आबरू के।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज़िंदगी और मौत पर किसी का अख़्तियार नहीं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "इंसान सिर्फ़ अपनी ख़ूबी से नहीं, बल्कि अपनी खराबी से भी पहचाना जाता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी वह चीज़ है जिसे खरीदा नहीं जा सकता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सांसारिक प्रेम से बढ़कर कोई प्रेम नहीं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चा दोस्त वही है जो आपको आपकी असलियत बताए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईश्वर महान है, पर वह भी तुम्हारी रक्षा न कर सकेगा, जो तुम खुद अपनी रक्षा नहीं करते।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "कर्तव्य को ही धर्म समझकर उसका पालन करना चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो मनुष्य अपने सुख के लिए दूसरों को कष्ट देता है, वह महापापी है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "गरीबी, अमीरी की दौड़ में ज़िक्ऱाँ बन जाती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य के कर्म ही उसकी पहचान हैं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान ही ऐसा धन है जिसे कोई छीन नहीं सकता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन एक संघर्ष है, और इस संघर्ष में जो जीत जाता है, वही महान होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चाई का रास्ता हमेशा कठिन होता है, पर अंत में वही विजयी होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मोह-माया के जाल में फँसकर मनुष्य अपना विवेक खो बैठता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो स्वयं को नहीं पहचानता, वह ईश्वर को क्या पहचानेगा।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सब्र का फल मीठा होता है, यह कहावत सत्य है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "न्याय की देवी हमेशा अपनी आँखें बंद रखती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "शिक्षा वह हथियार है जिससे हम दुनिया बदल सकते हैं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "खुशी वहीं है जहाँ संतोष है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच को कभी दबाया नहीं जा सकता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अन्याय के विरुद्ध आवाज़ उठाना हर मनुष्य का धर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "बुराई को अच्छाई से जीतना ही सच्चा धर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मानवीयता सबसे बड़ा धर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "कर्महीन जीवन व्यर्थ है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो दूसरों के दुःख से दुखी नहीं होता, वह मनुष्य नहीं, पत्थर है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "संघर्ष ही जीवन का सार है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सफलता के लिए आत्मविश्वास आवश्यक है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "समय किसी का इंतज़ार नहीं करता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम में त्याग का होना आवश्यक है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान ही शक्ति है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मानव का सबसे बड़ा शत्रु उसका अहंकार है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सादा जीवन, उच्च विचार।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अंधविश्वास मनुष्य का सबसे बड़ा दुश्मन है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "खुशी दूसरों को खुशी देने में है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन में उम्मीद कभी नहीं छोड़नी चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो अपना कर्तव्य भूल जाता है, वह कभी सुख नहीं पाता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य का प्रकाश अंधकार को चीर देता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईश्वर हर प्राणी में निवास करता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जब तक साँस है, तब तक आस है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी पर चलने वाला अक्सर अकेला होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम वह शक्ति है जो असंभव को संभव बना देती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अपने कर्मों का फल हमें अवश्य भोगना पड़ता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य को हमेशा सत्य के मार्ग पर चलना चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दया ही सबसे बड़ा गुण है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "परिवर्तन ही संसार का नियम है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "साहस ही विजय की पहली सीढ़ी है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो व्यक्ति दूसरों की मदद करता है, ईश्वर उसकी मदद करता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "धैर्य मनुष्य का सबसे बड़ा साथी है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी सबसे अच्छी नीति है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चाई कड़वी होती है, पर हितकर होती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चा धर्म वही है जो मनुष्य को इंसान बनाए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम में अंधा होना नहीं, विवेक से काम लेना चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "भाग्य उसी का साथ देता है, जो कर्म करता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "निराशा सबसे बड़ा पाप है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य के कर्म ही उसका भविष्य तय करते हैं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम का दीपक तभी जलता है जब उसमें त्याग की आहुति दी जाती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दूसरों के साथ वैसा ही व्यवहार करो, जैसा तुम अपने लिए चाहते हो।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन का आनंद दूसरों के आनंद में ही है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान वह प्रकाश है जो अज्ञानता के अंधकार को दूर करता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अहंकार मनुष्य को पतन की ओर ले जाता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "संतोष सबसे बड़ी दौलत है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जब तक आदमी उम्मीद नहीं छोड़ता, तब तक वह जीवित है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "कर्म ही पूजा है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईश्वर में विश्वास रखना अच्छी बात है, पर उस पर निर्भर रहना मूर्खता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मानव प्रेम से ही देवत्व प्राप्त कर सकता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चा सुख कर्म करने में है, फल की इच्छा में नहीं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो अन्याय सहता है, वह भी अन्याय करने वाले के बराबर है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "आत्मविश्वास सबसे बड़ी शक्ति है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान की कोई सीमा नहीं होती।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी से बढ़कर कोई दौलत नहीं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "क्रोध मनुष्य का सबसे बड़ा शत्रु है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन का लक्ष्य प्रेम और सेवा होना चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सादा जीवन और उच्च विचार ही मनुष्य का आदर्श होना चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दुनिया का सबसे बड़ा धर्म इंसानियत है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अंधेरे में दीपक जलाना ही सच्चा कर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य की विजय अवश्य होती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सब्र का फल हमेशा मीठा नहीं होता, कभी-कभी कड़वा भी होता है, पर वह तुम्हें मजबूत ज़रूर बनाता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जिस देश में अन्याय होता है, वह देश कभी तरक्की नहीं कर सकता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईश्वर तुम्हें तभी मदद करेगा जब तुम खुद की मदद करोगे।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मानवीयता से बढ़कर कोई धर्म नहीं।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान ही वह धन है जिसे कोई छीन नहीं सकता और न ही कोई चुरा सकता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्चाई में बड़ी शक्ति होती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दूसरों की भलाई में ही अपनी भलाई है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन का असली अर्थ कर्म और प्रेम है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो व्यक्ति स्वयं को नहीं पहचानता, वह किसी को नहीं पहचानता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य को कभी झुकाया नहीं जा सकता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी से किया गया कर्म हमेशा फलदायक होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम ही जीवन का आधार है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान की प्यास कभी नहीं बुझनी चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अंधकार के बाद प्रकाश अवश्य आता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "संयम ही मनुष्य का सबसे बड़ा गुण है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य की जीत हमेशा होती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य वही है जो दूसरों का दुःख समझता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम में कोई स्वार्थ नहीं होता।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान ही मुक्ति का मार्ग है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मानवता का सबसे बड़ा धर्म प्रेम है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "कर्म ही जीवन का आधार है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो व्यक्ति दूसरों के लिए जीता है, वही सच्चा मनुष्य है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सांसारिक मोह मनुष्य को अंधा बना देता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईश्वर हर जगह है, बस उसे महसूस करने की आवश्यकता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सच्ची दोस्ती अनमोल होती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान वह दीपक है जो जीवन का मार्ग रोशन करता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "संतोष ही परम सुख है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम ही सच्चा धर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य का सबसे बड़ा धन उसका चरित्र है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अन्याय का विरोध करना ही न्याय का समर्थन करना है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सादा जीवन और उच्च विचार ही आदर्श है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जब तक इंसानियत बाकी है, तब तक उम्मीद बाकी है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान वह प्रकाश है जो जीवन के हर अंधकार को दूर कर देता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम एक ऐसी शक्ति है जो टूटे दिलों को जोड़ सकती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "कर्म ही मनुष्य की पहचान है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी का मार्ग कठिन हो सकता है, पर अंत में वही सफल होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य कभी छिपता नहीं, वह सदा उजागर होता है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "दूसरों का भला चाहना ही सच्चा धर्म है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य का सबसे बड़ा बल उसका विवेक है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "प्रेम का सच्चा स्वरूप त्याग में ही है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ज्ञान वह कुंजी है जो हर दरवाजे को खोल सकती है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जीवन का सच्चा अर्थ प्रेम करना और सेवा करना है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "अंधकार में भी आशा की किरण ढूँढनी चाहिए।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "जो दूसरों के दर्द को समझता है, वही सच्चा इंसान है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "ईमानदारी ही सबसे बड़ा गुण है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "सत्य ही परमेश्वर है।", Author = "प्रेमचंद" },
            new Quote { Id = "https://hi.wikiquote.org/wiki/प्रेमचंद", Text = "मनुष्य का सबसे बड़ा शत्रु उसका लालच है।", Author = " प्रेमचंद" },
        };
    }
}