using System;

namespace StdbModule;

public static partial class GermanQuotes
{
    public static class FriedrichSchiller
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Auch die Freiheit muß ihren Herrn haben. Ohne Oberhaupt gieng Rom und Sparta zu Grunde.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das Gesetz hat zum Schneckengang verdorben, was Adlerflug geworden wäre. Das Gesetz hat noch keinen großen Mann gebildet, aber die Freyheit brütet Koloße und Extremitäten aus.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Deine Weisheit sei die Weisheit der grauen Haare, aber dein Herz - dein Herz sey das Herz der unschuldigen Kindheit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Muth wächst mit der Gefahr; Die Kraft erhebt sich im Drang.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich bin mein Himmel und meine Hölle.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich fühle eine Armee in meiner Faust - Tod oder Freyheit!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mir ekelt vor diesem Tintenklecksenden Jahrhundert.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sag ihnen, mein Handwerk ist Wiedervergeltung - Rache ist mein Gewerbe.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wer nichts fürchtet, ist nicht weniger mächtig als der, den alles fürchtet.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Feigen waren mehr, denn der Streitbaren, der Dummen mehr, denn der Klugen - Mehrheit setzte durch.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Leben heißt träumen; weise sein, Lomellin, heißt angenehm träumen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Daß die Zärtlichkeit noch barbarischer zwingt, als Tyrannenwuth! — Was soll ich? Ich kann nicht! Was muß ich thun?", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Lüge muß hier gangbare Münze seyn, wenn die Wahrheit so wenig Glauben findet.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich fürchte nichts - nichts - als die Gränzen deiner Liebe.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "In meinem Herzen liegen alle meine Wünsche begraben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mein bist du, und wärfen Höll' und Himmel sich zwischen uns!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mein Verstand steht still.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Seligkeit zerstören ist auch Seligkeit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sünden und böse Geister scheuen das Licht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wenn die Küsse deines Majors heißer brennen als die Tränen deines Vaters — stirb!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Beim wunderbaren Gott! - Das Weib ist schön!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Liebe ist der Liebe Preis.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Doch große Seelen dulden still.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ein Augenblick, gelebt im Paradiese wird nicht zu theuer mit dem Tod gebüßt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ein Federzug von dieser Hand, und neu erschaffen wird die Erde. Geben Sie Gedankenfreiheit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Große Seelen macht die Liebe größer.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich bin verzagt, wenn Weiber vor mir zittern.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich habe das Meinige gethan. Thun Sie das Ihre.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Liebe Kennt der allein, der ohne Hoffnung liebt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "O der Einfall war kindisch, aber göttlich schön.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und was ist Zufall anders, als der rohe Stein, der Leben annimmt unter Bildners Hand? Den Zufall gibt die Vorsehung - Zum Zwecke muß ihn der Mensch gestalten -", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wer mich entbehren kann, wird Wahrheit für mich haben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Zu überzeugen fällt keinem Überzeugten schwer.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Dem Mimen flicht die Nachwelt keine Kränze.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ernst ist das Leben, heiter ist die Kunst.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es wächst der Mensch mit seinen größern Zwecken.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hinter dem U kommt gleich das Weh, das ist die Ordnung im Alphabet.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und setzet ihr nicht das Leben ein, nie wird euch das Leben gewonnen sein.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und wenn die Muse heut, Des Tanzes freie Göttin und Gesangs, Ihr altes deutsches Recht, des Reims Spiel, Bescheiden wieder fordert - tadelt's nicht!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das eben ist der Fluch der bösen Tat, dass sie, fortzeugend, immer Böses muss gebären.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Des Dienstes immer gleichgestellte Uhr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Fabel ist der Liebe Heimatwelt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Uhr schlägt keinem Glücklichen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "O! nimm der Stunde wahr, eh sie entschlüpft. So selten kommt der Augenblick im Leben, Der wahrhaftig wichtig ist und groß.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Spät kommt Ihr - doch Ihr kommt! Der weite Weg entschuldigt Euer Säumen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Verstellung ist der Offenheit Seele fremd.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Vor Tische las man's anders.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Was ist der langen Rede kurzer Sinn?", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wer nicht ist mit mir, der ist wider mich.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Da steh' ich, ein entlaubter Stamm!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Daran erkenn' ich meine Pappenheimer.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das war kein Heldenstück, Octavio! Nicht deine Klugheit siegte über meine...", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Den Saamen legen wir in ihre Hände, ob Glück, ob Unglück aufgeht, lehrt das Ende.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Denn aus Gemeinem ist der Mensch gemacht, und die Gewohnheit nennt er seine Amme.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Denn nur vom Nutzen wird die Welt regiert.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Tag bricht an, und Mars regiert die Stunde.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Sterne lügen nicht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Eng ist die Welt, und das Gehirn ist weit. Leicht beieinander wohnen die Gedanken, doch hart im Raume stoßen sich die Sachen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es ist der Geist, der sich den Körper baut.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hab ich des Menschen Kern erst untersucht, so weiß ich auch sein Wollen und sein Handeln.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich hab' hier bloß ein Amt und keine Meinung.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Leutselig macht das Missgeschick.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Man soll den Tag nicht vor dem Abend loben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht deiner Treu, der Ohnmacht nur wird's zugeschrieben werden.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht hoffe, wer des Drachen Zähne Sä't, Erfreuliches zu ärnten. Jede Unthat trägt ihren Rache-Engel schon, die böse Hoffnung, unter ihren Herzen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nur zwischen Glaube und Vertraun ist Frieden.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "O, hättest du vom Menschen besser stets gedacht, du hättest besser auch gehandelt!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Schnell fertig ist die Jugend mit dem Wort.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sein Geist ist's, der mich ruft.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und ich erwart' es, daß der Rache Stahl Auch schon für meine Brust geschliffen ist.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wenn's nur dein Spiel gewesen, glaube mir, Du wirst's in schwerem Ernste büßen müssen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wir handeln, wie wir müssen. So lasst uns das Notwendige, mit Würde, mit festem Schritte tun.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es denkt der Mensch die freie Tat zu tun, umsonst! Er ist das Spielwerk nur der blinden Gewalt, die aus der eignen Wahl ihm schnell die furchtbare Notwendigkeit erschafft.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Den Menschen macht sein Wille groß und klein, und weil ich meinem treu bin, muss er sterben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Denn ein gebrechlich Wesen ist das Weib.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Ring macht Ehen, Und Ringe sind's, die eine Kette machen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Für Alles werde Alles frisch gewagt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich bin besser als mein Ruf.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Laß mich ein Kind seyn, sey es mit!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht Stimmenmehrheit ist des Rechtes Probe,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht Strenge legte Gott in's weiche Herz Des Weibes.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Spart mir den Anblick seiner rohen Sitten.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Was man nicht aufgiebt, hat man nie verloren.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Geh hin! Du sollst auf Erden für mich zeugen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "In raues Erz sollst du die Glieder schnüren.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Kurz ist der Abschied für die lange Freundschaft.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mit der Dummheit kämpfen Götter selbst vergebens.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sein Maß ist voll, er ist zur Ernte reif", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und Hochmut ists, wodurch die Engel fielen, Woran der Höllengeist die Menschen fasst.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wie kommt mir solcher Glanz in meine Hütte?", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Auf den Bergen ist Freiheit! Der Hauch der Grüfte Steigt nicht hinauf in die reinen Lüfte, Die Welt ist vollkommen überal, Wo der Mensch nicht hin kommt mit seiner Qual.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das Leben ist der Güter höchstes nicht, Der Übel größtes aber ist die Schuld.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Siege göttlichster ist das Vergeben!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Neigung giebt Den Freund, es giebt der Vortheil den Gefährten, Wohl dem, dem die Geburt den Bruder gab, Ihn kann das Glück nicht geben!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Noth gehorchend, nicht dem eignen Trieb,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ein ewig Räthsel bleiben will ich mir, Ich weiß genug, ich lebe dir!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hinter den großen Höhen Seht auch der tiefe, der donnernde Fall.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht an die Güter hänge dein Herz, Die das Leben vergänglich zieren, Wer besitzt, der lerne verlieren, Wer im Glück ist, der lerne den Schmerz.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Uns aber treibt das verworrene Streben Blind und sinnlos durchs wüste Leben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Schaamhafte Demuth ist der Reize Krone,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Allzu straff gespannt zerspringt der Bogen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "An’s Vaterland, an’s theure, schließ dich an, Das halte fest mit deinem ganzen Herzen. Hier sind die starken Wurzeln deiner Kraft, Dort in der fremden Welt stehst du allein, Ein schwankes Rohr, das jeder Sturm zerknickt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Auf dieser Bank von Stein will ich mich setzen", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Da Es ras’t der See und will sein Opfer haben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das Alte stürzt, es ändert sich die Zeit, Und neues Leben blüht aus den Ruinen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das ist Tells Geschoß.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Dem Muthigen hilft Gott!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Dem Schwachen ist sein Stachel auch gegeben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Denn herrenlos ist auch der Freiste nicht. Ein Oberhaupt muß seyn, ein höchster Richter, Wo man das Recht mag schöpfen in dem Streit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der brave Mann denkt an sich selbst zulezt, Vertrau auf Gott und rette den Bedrängten.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der kluge Mann baut vor.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Axt im Haus erspart den Zimmermann.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Schlange sticht nicht ungereizt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die schnellen Herrscher sind’s, die kurz regieren.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Durch diese hohle Gasse muß er kommen, Es führt kein andrer Weg nach Küßnacht", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ein furchtbar wüthend Schreckniß ist Der Krieg, die Heerde schlägt er und den Hirten.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ein rechter Schütze hilft sich selbst.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ertragen muß man, was der Himmel sendet, Unbilliges erträgt kein edles Herz.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es hebt die Freiheit siegend ihre Fahne.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es kann der Frömmste nicht im Frieden bleiben, Wenn es dem bösen Nachbar nicht gefällt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es lächelt der See, er ladet zum Bade,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es lebt ein Gott zu strafen und zu rächen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Früh übt sich, was ein Meister werden will.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hohl ist der Boden unter den Tyrannen, Die Tage ihrer Herrschaft sind gezählt, Und bald ist ihre Spur nicht mehr zu finden.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich bin der Letzte meines Stamms.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich hab’ gethan, was ich nicht lassen konnte.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ihm gehört das Weite Was sein Pfeil erreicht, Das ist seine Beute, Was da kreucht und fleugt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ihr wart in Straf’ gefallen, mußtet euch, Wie schwer sie war, der Buße schweigend fügen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "In gärend Drachengift hast du Die Milch der frommen Denkart mir verwandelt,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mach deine Rechnung mit dem Himmel Vogt, Fort mußt du, deine Uhr ist abgelaufen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mir fehlt der Arm, wenn mir die Waffe fehlt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nein, eine Grenze hat Tyrannenmacht, Wenn der Gedrückte nirgends Recht kann finden, Wenn unerträglich wird die Last – greift er Hinauf getrosten Muthes in den Himmel, Und hohlt herunter seine ewgen Rechte, Die droben hangen unveräuserlich Und unzerbrechlich wie die Sterne selbst –", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Rache trägt keine Frucht! Sich selbst ist sie Die fürchterliche Nahrung", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Rasch tritt der Tod den Menschen an, Es ist ihm keine Frist gegeben, Es stürzt ihn mitten in der Bahn, Es reißt ihn fort vom vollen Leben,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Redlichkeit gedeiht in jedem Stande.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sie alle ziehen ihres Weges fort An ihr Geschäft – und Meines ist der Mord!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sieh den Hut dort auf der Stange.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "So ernst, mein Freund? Ich kenne dich nicht mehr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Steh zu deinem Volk, Es ist dein angebohrner Platz.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und auf den Schützen springt der Pfeil zurück.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Vater schieß zu, ich fürcht’ mich nicht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Verbunden werden auch die Schwachen mächtig.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wann wird der Retter kommen diesem Lande?", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Was Hände bauten, können Hände stürzen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wer gar zu viel bedenkt, wird wenig leisten.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wer Tränen ärnten will, muß Liebe säen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wir sind eins Volk, und einig wollen wir handeln.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wir wollen seyn ein einzig Volk von Brüdern, In keiner Noth uns trennen und Gefahr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Zum lezten Mittel, wenn kein andres mehr Verfangen will, ist ihm das Schwert gegeben", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Mehrheit? Was ist die Mehrheit? Mehrheit ist der Unsinn, Verstand ist stets bei wen'gen nur gewesen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Euch öffnen sich des Glückes goldne Tore.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Man soll die Stimmen wägen und nicht zählen; Der Staat muß untergehn, früh oder spät, Wo Mehrheit siegt und Unverstand entscheidet.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mit vollen Segeln lief ich in das Meer Des Lebens.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Nicht deinen Arm bloß will ich, auch dein Auge.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Brüder fliegt von euren Sitzen, wenn der volle Römer kraißt, Laßt den Schaum zum Himmel sprützen: Dieses Glas dem guten Geist.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Duldet mutig, Millionen! Duldet für die beßre Welt! Droben überm Sternenzelt wird ein großer Gott belohnen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Freude heißt die starke Feder in der ewigen Natur. Freude, Freude treibt die Räder in der großen Weltenuhr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Freude, schöner Götterfunken, Tochter aus Elisium, Wir betreten feuertrunken Himmlische, dein Heiligthum.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Seid umschlungen, Millionen! Diesen Kuß der ganzen Welt! Brüder – überm Sternenzelt muß ein lieber Vater wohnen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Unser Schuldbuch sei vernichtet! ausgesöhnt die ganze Welt!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wem der große Wurf gelungen, eines Freundes Freund zu seyn; wer ein holdes Weib errungen, mische seinen Jubel ein!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wollust ward dem Wurm gegeben, und der Cherub steht vor Gott.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Dreifach ist der Schritt der Zeit: Zögernd kommt die Zukunft hergezogen, Pfeilschnell ist das Jetzt entflogen, Ewig still steht die Vergangenheit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mußt ins Breite dich entfalten, soll sich dir die Welt gestalten; In die Tiefe mußt du steigen, Soll sich dir das Wesen zeigen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Rastlos vorwärts musst du streben, Nie ermüdet stille stehn.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Immer strebe zum Ganzen und kannst du selber kein Ganzes Werden, als dienendes Glied schließ’ an ein Ganzes dich an.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Kannst du nicht allen gefallen durch deine That und dein Kunstwerk, Mach es wenigen recht, vielen gefallen ist schlimm.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Keiner sey gleich dem andern, doch gleich sey jeder dem höchsten, Wie das zu machen? Es sey jeder vollendet in sich.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Warum kann der lebendige Geist dem Geist nicht erscheinen! Spricht die Seele so spricht ach! schon die Seele nicht mehr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Welche Religion ich bekenne? Keine von allen, Die du mir nennst! Und warum keine? Aus Religion.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Willst du dich selber erkennen, so sieh wie die andern es treiben, Willst du die andern verstehn, blick in dein eigenes Herz.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Da speit das doppelt geöffnete Haus Zwei Leoparden auf einmal aus. Die stürzen mit mutiger Kampfbegier Auf das Tigertier.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Des Lebens ungemischte Freude ward keinem Irdischen zuteil.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Du hast der Götter Gunst erfahren!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hier wendet sich der Gast mit Grausen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Noch keinen sah ich fröhlich enden, Auf den mit immer vollen Händen Die Götter ihre Gaben streun.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Mensch ist frei geschaffen, ist frei, Und würd' er in Ketten geboren.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Vor dem Sklaven, wenn er die Kette bricht, Vor dem freien Menschen erzittert nicht!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Du kerkerst den Geist in ein tönend Wort, Doch der freie wandelt im Sturme fort.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Es ist nicht draußen, da sucht es der Tor, Es ist in dir, du bringst es ewig hervor.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Mut zeiget auch der Muslim, Gehorsam ist des Christen Schmuck;", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ich sei, gewährt mir die Bitte, In eurem Bunde der Dritte.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Was wolltest du mit dem Dolche, sprich!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Zurück! du rettest den Freund nicht mehr, So rette das eigene Leben!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das Auge des Gesetzes wacht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Da werden Weiber zu Hyänen Und treiben mit Entsetzen Scherz,", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der ersten Liebe goldne Zeit", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Mann muss hinaus In's feindliche Leben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Blume verblüht, Die Frucht muß treiben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Doch mit des Geschickes Mächten Ist kein ew'ger Bund zu flechten, Und das Unglück schreitet schnell.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Drum prüfe, wer sich ewig bindet, Ob sich das Herz zum Herzen findet! Der Wahn ist kurz, die Reu ist lang.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Erröthend folgt er ihren Spuren.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Freude dieser Stadt bedeute, Friede sey ihr erst Geläute.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Gefährlich ist's, den Leu zu wecken, Und grimmig ist des Tigers Zahn, Jedoch der schrecklichste der Schrecken, Das ist der Mensch in seinem Wahn.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Von der Stirn'e heiß Rinnen muß der Schweiß, Soll das Werk den Meister loben, Doch der Segen kommt von oben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wehe, wenn sie losgelassen.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wenn gute Reden sie begleiten Dann fließt die Arbeit munter fort.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wohlthätig ist des Feuers Macht, Wenn sie der Mensch bezähmt, bewacht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wo rohe Kräfte sinnlos walten, Da kann sich kein Gebild gestalten.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Aber hat Natur uns viel entzogen, War die Kunst uns freundlich doch gewogen, Unser Herz erwarmt an ihrem Licht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Alles wiederholt sich nur im Leben, Ewig jung ist nur die Phantasie; Was sich nie und nirgends hat begeben, Das allein veraltet nie!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Sehn wir doch das Große aller Zeiten Auf den Brettern, die die Welt bedeuten, Sinnvoll still an uns vorübergehn.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ach wie glücklich sind die Toten!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Alle andern Dinge müssen; der Mensch ist das Wesen, welches will.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Alles freuet sich und hoffet, Wenn der Frühling sich erneut.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Menschheit Würde ist in eure Hand gegeben, Bewahret sie!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Der Schein regiert die Welt, und die Gerechtigkeit ist nur auf der Bühne.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Des Lebens Mai blüht einmal und nicht wieder, Mir hat er abgeblüht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Die Welt wird alt und wird wieder jung, Doch der Mensch hofft immer Verbesserung!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Dunkel war der Rede Sinn", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Ehret die Frauen! sie flechten und weben Himmlische Rosen ins irdische Leben.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Genieße, wer nicht glauben kann. Die Lehre ist ewig wie die Welt. Wer glauben kann, entbehre.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Glücklicher Säugling! Dir ist ein unendlicher Raum noch die Wiege, Werde Mann, und dir wird eng die unendliche Welt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Hast du etwas, so teile mir's mit, und ich bezahle, was recht ist; Bist du etwas, o dann tauschen die Seelen wir aus.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Philosophen verderben die Sprache, Poeten die Logik, und mit dem Menschenverstand kommt man durchs Leben nicht mehr.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Siehe! Da weinen die Götter, es weinen die Göttinnen alle, dass das Schöne vergeht, dass das Vollkommene stirbt.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Soll ich darum das Veilchen unter die Füße treten, weil ich die Rose nicht erlangen kann?", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Suchst du das Höchste, das Größte? Die Pflanze kann es dich lehren. Was sie willenlos ist, sei du es wollend - das ist's!", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Und so saß er, eine Leiche.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wanderer, kommst du nach Sparta, verkündige dorten, du habest Uns hier liegen gesehn, wie das Gesetz es befahl.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "»Was tun?«, spricht Zeus.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Wenn die Könige baun, haben die Kärrner zu tun.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "»Woran erkenn ich den besten Staat?« Woran du die beste Frau kennst; daran mein Freund, daß man von beiden nicht spricht.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Zwischen Sinnenglück und Seelenfrieden Bleibt dem Menschen nur die bange Wahl.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Anmut ist eine bewegliche Schönheit.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Billig erwartest Du, daß ich Dir meine Schiksale unter fremdem Himmel mittheile, denn mein Leben hat ohnehin die Farbe eines Romans, und mein sonderbarer Kopf läßt freilich auf sonderbare Situazionen schließen – aber für Briefe ist dieses Thema zu weitläuftig, und vielleicht auch zu gefärlich.", Author = "Friedrich Schiller" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Friedrich_Schiller", Text = "Das erste Gesetz des guten Tones ists: Schone fremde Freiheit. Das zweyte: zeige selbst Freiheit. Die pünktliche Erfüllung beider ist ein unendlich schweres Problem, aber der gute Ton fodert sie unerlaßlich, und sie macht allein den vollendeten Weltmann.", Author = "Friedrich Schiller" },
        };
    }
}
