using System;

namespace StdbModule;

public static partial class GermanQuotes
{
    public static class Novalis
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der Mensch vermag in jedem Augenblick ein übersinnliches Wesen zu sein. Ohne dies wäre er nicht Weltbürger - er wäre ein Tier.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der wahre Brief ist seiner Natur nach poetisch.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Ganz begreifen werden wir uns nie, aber wir werden und können uns weit mehr, als begreifen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Ihre sogenannte Religion wirkt blos, wie ein Opiat: reizend, betäubend, Schmerzen aus Schwäche stillend.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jeder geliebte Gegenstand ist der Mittelpunkt eines Paradieses.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jede Stufe der Bildung fängt mit Kindheit an. Daher ist der am meisten gebildete, irdische Mensch dem Kinde so ähnlich.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Nach Innen geht der geheimnißvolle Weg. In uns, oder nirgends ist die Ewigkeit mit ihren Welten, die Vergangenheit und Zukunft.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Vieles ist zu zart, um gedacht, noch mehreres, um besprochen zu werden.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wir sind auf einer Mißion: zur Bildung der Erde sind wir berufen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wir suchen überall das Unbedingte, und finden immer nur Dinge.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wir träumen von Reisen durch das Weltall: Ist denn das Weltall nicht in uns?", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wo Kinder sind, da ist ein goldnes Zeitalter.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Liebe wirkt magisch.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Philosophie ist eigentlich Heimweh - Trieb überall zu Hause zu sein.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Glück ist Talent für die Historie, oder das Schicksal.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jede Wissenschaft hat ihren Gott, der zugleich ihr Ziel ist.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jeder Engländer ist eine Insel.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Weisheit ist Harmonie.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Auf alles, was der Mensch vernimmt, muss er seine ungeteilte Aufmerksamkeit oder sein Ich richten.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Das Denken ist nur ein Traum des Fühlens, ein erstorbenes Fühlen, ein blassgraues, schwaches Leben.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Naturforscher und Dichter haben durch eine Sprache sich immer wie ein Volk gezeigt.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Alle geistige Berührung gleicht der Berührung eines Zauberstabs. Alles kann zum Zauberwerkzeug werden.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Alles Mystische ist personell - und mithin eine Elementarvariation des Weltalls.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Alles ist Materie was mittels der Organe zu uns kommt.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Aus Bequemlichkeit suchen wir nach Gesetzen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Das höchste Leben ist Mathematik.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der echte Dichter ist allwissend - er ist eine wirkliche Welt im Kleinen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Tischzeit ist die merkwürdigste Periode des Tages und vielleicht der Zweck, die Blüte des Tages. Das Frühstück ist die Knospe.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die individuelle Seele soll mit der Weltseele übereinstimmen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Poësie lößt fremdes Dasein in Eignen auf.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Ein Kind ist eine sichtbar gewordene Liebe.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Je mehr man lernt, nicht mehr in Augenblick, sondern in Jahren zu leben, desto edler wird man.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Nichts ist dem Geist erreichbarer als das Unendliche.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Reine Mathematik ist Religion.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Romantik. Alle Romane, wo wahre Liebe vorkommt, sind Märchen - magische Begebenheiten.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Spielen ist Experimentieren mit dem Zufall.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Unser ganzes Leben ist Gottesdienst.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wenn man einen Riesen sieht, so untersuche man erst den Stand der Sonne - und gebe acht, ob es nicht der Schatten eines Pygmäen ist.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Geschichte erzeugt sich selbst.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Die Poesie heilt die Wunden, die der Verstand schlägt.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Glück ist Talent für die Historie, oder das Schicksal.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Gott will Götter.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jeder Staatsbürger ist ein Staatsbeamter.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Jeder Mensch sollte Künstler sein. Alles kann zur schönen Kunst werden.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Was man liebt, findet man überall und sieht überall Ähnlichkeit.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wo junge Leute sind, ist Republik.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Nicht die Schätze sind es, die ein so unaussprechliches Verlangen in mir geweckt haben, sagte er zu sich selbst; fern ab liegt mir alle Habsucht: aber die blaue Blume sehn' ich mich zu erblicken.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Er sah nichts als die blaue Blume, und betrachtete sie lange mit unnennbarer Zärtlichkeit.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Frühe Hochzeiten, lange Liebe.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Überhaupt können die Dichter nicht genug von den Musikern und Malern lernen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wo gehen wir denn hin? Immer nach Hause.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Alle Wissenschaft sollen Mathematik werden. Die bisherige Mathematik ist nur die erste und leichteste Äußerung oder Offenbarung des wahrhaft wissenschaftlichen Geistes.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Das Zahlensystem ist Muster eines ächten Sprachzeichensystems - Unsre Buchstaben sollen Zahlen, unsre Sprache Arithmetik werden.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der Grund aller Verkehrtheit in Gesinnungen und Meinungen ist Verwechslung des Zwecks mit dem Mittel.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Republik ist das fluidum deferens der Jugend. Wo junge Leute sind, ist Republik.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der Geist führt einen ewigen Selbstbeweis.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Der wahre Leser muss der erweiterte Autor sein.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Wir sind dem Aufwachen nah, wenn wir träumen, daß wir träumen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Durch Gebet erlangt man alles. Gebet ist eine universale Arznei.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Freunde, der Boden ist arm, wir müssen reichlichen Samen ausstreun, dass uns doch nur mäßige Ernten gedeihn.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Hier ist Amerika oder Nirgends.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Himmlischer, als jene blitzenden Sterne, dünken uns die unendlichen Augen, die die Nacht in uns geöffnet.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Hypothesen sind Netze, nur der wird fangen, der auswirft.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Soll nicht die dichterische Leier tönen // Dem König der den Frieden liebt // An Kriegesschall nicht kann sein mildes Ohr gewöhnen // Und sich bei Mord betrübt.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Trägt nicht alles, was uns begeistert, die Farbe der Nacht?", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Zur Welt suchen wir den Entwurf - dieser Entwurf sind wir selbst.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Für das Lebendige ist kein Ersatz.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Alle göttlichen Gesandten müssen Mathematiker sein.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Bosheit ist nichts als eine Gemütskrankheit.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Das Herz ist der Schlüssel der Welt und des Lebens.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Ein Charakter ist ein vollkommen gebildeter Willen.", Author = "Novalis" },
            new Quote { Id = "https://de.wikiquote.org/wiki/Novalis", Text = "Schlafen ist Verdauen der Sinneneindrücke. Träume sind Exkremente.", Author = "Novalis" },
        };
    }
}