namespace StdbModule;

public static partial class IndonesianQuotes
{
    public static class NajwaShihab
    {
        private const string Source = "https://id.wikiquote.org/wiki/Najwa_Shihab";

        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = Source, Text = "Hanya pendidikan yang bisa menyelamatkan masa depan, tanpa pendidikan Indonesia tak mungkin bertahan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan sejati bukan tentang seberapa banyak yang kita tahu, tapi seberapa bijak kita menggunakannya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Sekolah bukan sekadar gedung dan kelas — itu adalah ruang di mana jiwa dibentuk.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ketika pendidikan dilakukan hanya untuk nilai, maka mahasiswa menjadi angka, bukan manusia.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan membuka pintu — tetapi manusialah yang harus melangkah melewatinya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Belajar bukan hanya menghafal, tapi memahami dan bertanya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Investasi terbesar suatu bangsa adalah ketika ia mendidik rakyatnya dengan hati.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan yang memanusiakan manusia adalah pendidikan yang berhasil.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan harus menumbuhkan rasa ingin tahu — bukan menutupnya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Anak-anak kita bukan produk — mereka adalah masa depan yang perlu kita rawat.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Bukan seberapa pintar, tapi seberapa peduli — itu yang dibentuk pendidikan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Sekolah yang baik tumbuh dari kegigihan, bukan dari keberuntungan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ketika kita mendidik generasi, kita tidak hanya mempersiapkan pekerja — kita mempersiapkan manusia.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan yang hebat mengajari kita untuk tidak takut salah — karena salah adalah guru yang paling jujur.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Hanya dengan pendidikan kita bisa mendobrak batas yang dibuat oleh kebodohan dan ketidakpedulian.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ketika seorang guru berhenti percaya pada mimpi muridnya — maka kita semua sudah kehilangan harapan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ilmu jangan jadi objek hafalan. Ilmu itu untuk memahami dan menuntaskan persoalan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Tindakan perempuan diilhami hidup sehari-hari, langkahnya panjang sebab tak hanya mengurus diri sendiri.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Mumpung masih muda, jangan ragu untuk mencoba hal baru karena kita tidak akan pernah tahu apa yang kita suka kalau tidak mencoba. Jangan anggap enteng hal-hal kecil sekalipun. Jika itu dirawat, dapat menjadi besar dan menjadi keahlianmu.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Buat apa wilayah seluas Sabang sampai Merauke, jika pemudanya kehilangan idealisme.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Tanpa perubahan cara berpikir, pindah ibu kota hanya pindah masalah.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kenyamanan jauh lebih menggoda, kemapanan dianggap lebih utama.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Dalam narasi-narasi hidup yang nyata, perempuan menjadi kekuatan tak terbatas.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kekurangan jangan terlalu dikhawatirkan, selama kepemimpinan berjalan penuh keterbukaan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Media selalu punya kesempatan emas, membangun keterlibatan sosial dan solidaritas.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Harta dan takhta memang dua sisi yang tak bisa dipisahkan. Perputaran uang menjadi bahan bakar kekuasaan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kemampuan membaca medan, kecerdikan melihat kesempatan dibutuhkan di tengah persaingan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Selama ini, raga koruptor terpenjara, tapi bisnis dan hidup sosialnya lancar jaya. Ada yang salah dalam sistem hukum kita, terutama bobot hukuman dan efek jera.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Keadilan jadi barang sukar, ketika hukum hanya tegak pada yang bayar.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kepemimpinan adalah keteladanan, inspirasi yang sanggup menggerakkan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Demokrasi tidak untuk melayani penguasa; demokrasi ditujukan untuk memuliakan warga negara.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Budaya ketimuran harus jadi kebanggaan, bukan dengan ancaman dan paksaan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Menikmati kehidupan bukanlah tentang memiliki segalanya, tapi merasa bahagia dengan apa yang telah ada.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kehidupan yang menyenangkan adalah ketika kita bisa menjadi diri sendiri tanpa pretensi.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Hidup tidak selalu indah, tapi setiap detiknya layak untuk disyukuri.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Jangan biarkan kesuksesan membuat kita sombong, dan jangan biarkan kegagalan membuat kita patah semangat.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Agama seharusnya menjadi penerang, bukan bahan untuk saling menghakimi.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ibadah tidak hanya tentang ritual, tetapi tentang bagaimana kita memperlakukan manusia lain.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kesalehan tidak diukur dari penampilan, tetapi dari kelapangan hati dan keluhuran budi.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Agama hadir untuk memanusiakan manusia, bukan membuat kita merasa paling benar.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Perbedaan keyakinan bukan alasan untuk saling menjauh, melainkan undangan untuk saling memahami.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Yang beragama itu manusia, maka janganlah keangkuhan menggantikan ketulusan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Ketakwaan seharusnya memunculkan kerendahan hati, bukan keterpisahan dari sesama.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Jangan jadikan agama sebagai senjata untuk melukai; jadikan ia sebagai jembatan untuk merangkul.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Doa adalah kekuatan, tetapi tindakan baik adalah wujud paling nyata dari doa itu sendiri.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Agama tidak pernah memerintahkan permusuhan; manusia yang kerap salah menafsirkannya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Iman tidak membutuhkan panggung; ia tumbuh dalam keheningan dan praktik hidup sehari-hari.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Belajarlah memahami sebelum menilai, karena ajaran agama tidak lahir dari prasangka.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Yang penting bukan seberapa sering kita berbicara tentang Tuhan, tetapi seberapa besar kita menebarkan kebaikan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Fanatisme membutakan, sementara pemahaman membuka jalan bagi kedamaian.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Keberagaman adalah keniscayaan; agama mengajarkan kita untuk menjadikannya kekuatan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Hidup beragama berarti menjaga diri, menjaga lisan, dan menjaga hubungan antarsesama.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kebijaksanaan tidak lahir dari hafalan ayat, tetapi dari penghayatan terhadap maknanya.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kita tidak perlu memaksakan keyakinan, karena hidayah adalah hak Tuhan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Agama adalah jalan menuju kebaikan; jika ia membuatmu membenci, mungkin kau sedang tersesat.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Yang berharga dari agama bukan perdebatan, tetapi nilai kasih sayang yang ia ajarkan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Yang menjadi pena adalah kebaikan, yang menjadi tinta adalah kemanusiaan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Nyawa manusia bukan tragedi tontonan dan statistik belaka.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Yang harus dibabat adalah egoisme dan kebencian, yang mesti dirajut ialah solidaritas dan kepedulian.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Pendidikan seharusnya memanusiakan manusia, bukan mengerdilkan siapa pun.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kita tak boleh membiarkan orang kecil terus menjadi korban dan hanya tercatat sebagai catatan kaki.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Kemanusiaan menuntut kita untuk hadir, bukan sekadar melihat dari kejauhan.", Author = "Najwa Shihab" },
            new Quote { Id = Source, Text = "Apa arti ijazah yang bertumpuk, jika kepedulian dan kepekaan tidak ikut dipupuk?", Author = "Najwa Shihab" },
        };
    }
}
