using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class BenedettoCroce
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "A questi poveri e fallaci teorizzamenti si deve l'origine dell'erronea credenza che liberalismo sia individualismo utilitario (o, come lo si definisce, riecheggiando Hegel, «atomismo»), e che abbassi lo Stato a strumento dell'edonismo dei singoli.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Accanto o di fronte agli uomini che stimano Parigi valer bene una messa, sono altri pei quali l'ascoltare o no una messa è cosa che vale infinitamente più di Parigi perché è affare di coscienza. Guai alla società, alla storia umana, se uomini che così diversamente sentono, le fossero mancati o le mancassero.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Anche nella vendetta, insomma, non si gode del male di altri, ma del nostro bene [...].", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Credo che, a guerra finita, si giudicherà che il suolo d'Europa, non solo ha tremato per più mesi o per più anni sotto il peso delle armi, ma anche sotto quello degli spropositi. E Francesi, Inglesi, Tedeschi e Italiani si vergogneranno e chiederanno venia poi giudizi che hanno pronunciati, e diranno che non erano giudizi ma espressioni di affetti. E anche più arrossiremo noi, neutrali, che molto spesso abbiamo parlato, come di cosa evidente, della \"barbarie germanica\". Fra tutti gli spropositi, frutti di stagione, questo otterrà il primato, perché certo è il più grandioso.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "È appunto l'opposizione che ringiovanisce. Se fossi rimasto senatore, avrei avuto una vita troppo comoda, sarei da un pezzo diventato di mente pigra ed inconseguente. Nulla è di danno all'intelletto quanto la mancanza di opposizione; solo da quando sono solo e non ho più giovani intorno a me, mi sento costretto a ringiovanire io stesso.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "E stimo un tal grande beneficio la cura a cui il fascismo ha sottoposto l'Italia che mi do pensiero piuttosto che la convalescente non si levi troppo presto dal letto a rischio di qualche grave ricaduta.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Eliminando le case chiuse non si distruggerebbe il male che rappresentano, ma si distruggerebbe il bene con il quale è contenuto, accerchiato e attenuato quel male.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Il bisogno pratico, che è nel fondo di ogni giudizio storico, conferisce a ogni storia il carattere di \"storia contemporanea\", perché, per remoti e remotissimi che sembrino cronologicamente i fatti che vi entrano, essa è, in realtà, storia sempre riferita al bisogno e alla situazione presente, nella quale quei fatti propagano le loro vibrazioni.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Il filosofo, oggi, deve non già fare il puro filosofo, ma esercitare un qualche mestiere, e in primo luogo, il mestiere dell'uomo.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Il monumentoparlato del buon senso si trova nella stessa letteratura popolare, e sono i proverbi, la sapienza (come la chiamano) di tutte le età, la sapienza del mondo di cui tante volte è stata lodata l'incrollabile saldezza; e tuttavia nessuno, pur ridicendoli con assenso, li scambierà mai con la serie delle opere della critica, della scienza e della filosofia, con le indagini, le discussioni, i trattati e i sistemi. Molte indagini filosofiche si possono conchiudere con la formola di qualche antico e comune detto o proverbio; ma questo proverbio, fungendo da conclusione di un'indagine, non è più l'antico e comune.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Io, modestamente, so di vivere in un continuo colloquio con Dio, così serio e intenso che molti cattolici e molti preti non hanno mai sentito nella loro anima.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "L'impedimento che urge rimuovere è la persona del re, Vittorio Emanuele III, che ha aperto le porte al fascismo, lo ha favorito, sostenuto, servito per oltre vent'anni, lo ha seguito in tutte le sue azioni e persecuzioni più contrarie alla moralità... Pretendere che l'Italia conservi il presente re, è come pretendere che un redivivo resti abbracciato con un cadavere.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "L'Italia di Volpe cammina ma non pensa.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La conoscenza umana ha due forme: è o conoscenza \"intuitiva\" o conoscenza \"logica\"; conoscenza per la \"fantasia\" o conoscenza per l'\"intelletto\"; [...] è, insomma, o produttrice di \"immagini\" o produttrice di \"concetti\".", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La critica è un fucile molto bello: deve sparare raramente!", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La giustizia vera è fatta di compassione.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La iettatura è una cosa che non esiste, ma della quale bisogna tener conto.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La libertà al singolare esiste soltanto nelle libertà al plurale.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La morte sopravverrà a metterci in riposo, a toglierci dalle mani il compito a cui attendevamo; ma essa non può fare altro che così interromperci, come noi non possiamo fare altro che lasciarci interrompere, perché in ozio stupido essa non ci può trovare.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La poesia solo in piccola parte si trova negli innumeri libri detti di poesia.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La realtà è spiritualità e creatività, e non si lascia opprimere da concezioni naturalistiche, che si rivolgono sempre in fantastiche e pessimistiche.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La sovranità in una relazione non è di nessuno dei componenti singolarmente preso, ma della relazione stessa, cioè dell'incontro.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La storia non è mai giustiziera, ma sempre giustificatrice; e giustiziera non potrebbe farsi se non facendosi ingiusta, ossia confondendo il pensiero con la vita, e assumendo come giudizio del pensiero le attrazioni e le repulsioni del sentimento.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La storia nostra è storia della nostra anima; e storia dell'anima umana è la storia del mondo.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La violenza non è forza ma debolezza, né mai può essere creatrice di cosa alcuna, ma soltanto distruggerla.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Le verità definite dai filosofi non si abbattono a vicenda, ma si sommano e si integrano le une con le altre, e dominano il pensiero e la vita, se anche il volgo di questo non si avveda e non si avvede di esserne anch'esso dominato.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Molta parte dell'anima nostra è dialetto.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Napoli è un paese in cui è impossibile promuovere un pubblico interesse senza rimetterci il cervello e la salute.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Nessuno pensava che i arii di Germania avessero avuto bisogno di tanto aiuto e tanto avessero accettato dai non arii. Quale vergogna sfruttare il lavoro dell'estraneo e adornarne, come hanno fatto finora, la loro storia! E quale animo dignitoso e disdegnoso e fiero è quel Julius Streicher, che adesso viene chiedendo che non si curino più gl'infermi cristiani coi ritrovati medici dei Wassermann, dei Neisser, dei Fraenkel e di altri scienziati ebrei, e piuttosto li si lasci morire che accettare la lurida elemosina! Bravo: questa è rinunzia eroica, degna di un vero ario: alla quale si potrebbe solo obiettare (ma è obiezione che non conta) che, per questa via, la parola \"ario\" finirà a prendere il significato d'imbecille.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Noi vogliamo, in fatto di scuola, a preferenza di sterminati eserciti di Serse, piccoli eserciti ateniesi e spartani, di quelli che vinsero l'Asia e fondarono la civiltà europea.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Non è vero, ma ci credo.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Non possiamo distaccarci dal bene e dal male della nostra Patria, né dalle sue vittorie né dalle sue sconfitte.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Non possiamo non essere cristiani, anche se non seguiamo più le pratiche del culto, perché il cristianesimo ha modellato il nostro modo di sentire e di pensare in guisa incancellabile; e la diversità profonda che c'è fra noi e gli antichi [...] è proprio dovuta a questo gran fatto, il maggior fatto senza dubbio della storia universale, cioè il verbo cristiano.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Non sarebbe il tempo di smettere di aver fiducia nelle opposizioni e distinzioni dei partiti politici, tanto più che l'esperienza politica ci mostra che il partito che governa o governa è sempre uno solo e ha il consenso di tutti gli altri, che fanno le finte di opporsi? Non sarebbe meglio contare sugli uomini saggi, lavoratori e consapevoli del loro dovere verso la patria, i quali in Italia sono in maggior numero che non credano i pessimisti?", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Non si poteva aspettare e neppure desiderare che il fascismo cadesse a un tratto. Esso non è stato un infatuamento o un giochetto. Ha risposto a seri bisogni e ha fatto molto di buono.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Ogni vera storia è sempre autobiografica.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Qual nome di autore nostro di tragedie, di commedie e drammi possiamo pronunciare con vanto, nel secolo passato e per la prima metà del presente? L'importanza che Napoli non ha avuto nel teatro letterario, l'ha avuta invece nella commedia popolare e dialettale, nell'opera buffa, nelle rappresentazioni all'improvviso, negli attori e nei personaggi comici che ha messo in circolazione.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Scocciatore è uno che ti toglie il piacere della solitudine e non ti dà quello della compagnia.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Un'altra manifestazione della volgare inintelligenza circa le cose della politica è la petulante richiesta che si fa della \"onestà\" nella vita politica. [...] L'onestà politica non è altro che la capacità politica: come l'onestà del medico e del chirurgo è la sua capacità di medico e di chirurgo, che non rovina e assassina la gente con la propria insipienza condita di buone intenzioni e di svariate e teoriche conoscenze.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "L'Unesco aveva della cultura un'idea semplicemente sbagliata perché sciolta dalla sua sorella di sangue e spirito, la libertà.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Un velo di mestizia par che avvolga la Bellezza, e non è velo, ma il volto stesso della Bellezza.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Vedo che l'esattezza dell'esposizione del Borsa e la giustezza dei suoi giudizi vengono riconosciute da uno dei più esperti critici teatrali inglesi, da William Archer (in un articolo della Tribune, del 3 novembre 1906). L'Archer rimprovera soltanto al Borsa la troppa severità della tesi generale, che un teatro inglese contemporaneo non esista: la quale tesi gli sembra contraddetta dalle analisi particolari che l'autore poi dà delle singole opere. E mi pare che l'Archer abbia ragione, e che un teatro in cui sono opere come quelle che Borsa fa conoscere ai lettori italiani, sia bene qualcosa di esistente; perché l'esistenza di un teatro non può significare chiaramente altro che l'esistenza di alcuni autori e di alcune opere, fornite di caratteri originali.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La fortuna dell'Orlando furioso si può comparare a quella di una donna leggiadra e sorridente, che tutti guardano con letizia, senza che l'ammirazione sia impacciata da alcuna perplessità d'intelletto, bastando, per ammirare, aver occhi e volgerli al grato oggetto. Limpidissimo com'è quel poema, nitidissimo in ogni particolare, facilmente apprendibile da chiunque possieda una generale cultura, non ha mai presentato seri ostacoli d'interpretazione, e perciò non ha avuto bisogno delle industrie dei commentatori e non è stato aduggiato dalle loro litiganti sottigliezze; né poi è andato soggetto, o assai lievemente, alle intermittenze che, per le varie disposizioni culturali dei vari tempi, hanno pur sofferto altre insigni opere di poesia. Grandi uomini e comuni lettori si sono trovati intorno ad esso in pieno accordo, come appunto intorno alla bellezza, poniamo di una signora Récamier; e nella folla di coloro che furono presi dal suo fascino, si notano un Machiavelli e un Galilei, un Voltaire e un Goethe.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Se l'Ariosto fosse stato un filosofo, o un poeta filosofo, avrebbe sciolto un inno all'Armonia, come non pochi se ne posseggono nella storia della letteratura, cantando quell'alta Idea che gli rendeva comprensibile la discorde concordia delle cose e, appagandogli l'intelletto, infondeva pace e gioia nell'animo.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Soverchia nel Furioso, la materia d'amore, perché soverchia nel cuore dell'Ariosto, nel quale essa agevolmente trapassava a sentimenti gentili, alla pietà che va oltre le tombe, alla rivendicazione dell'innocenza calunniata e della gratitudine brutalmente violata, al fervido culto pel santo nodo dell'amicizia.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Bontà e generosità erano anche la sostanza del suo sentimento politico, da onest'uomo di tutti i tempi, che piange sulle sventure della patria, aborre il dominio degli stranieri, giudica severamente le oppressioni dei signori, si scandalizza per la corruttela ed ipocrisia dei preti e Chiesa, lamenta che le armi unite di Europa non si volgono contro il Turco ossia contro il barbaro infesto.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "L'Ariosto era irriverente, o, ch'è lo stesso, indifferente, spirito altrettanto areligioso quanto afilosofico, non angosciato da dubbi, non pensoso del destino umano, non curioso del significato e valore di questo mondo che vedeva e toccava, e nel quale amava e dolorava; estraneo del tutto, come a ogni altra filosofia, a quella del Rinascimento, sia del Ficini sia del Pomponazzi.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Il bene o la virtù è, senza dubbio, nello Shakespeare, più forte del male e del vizio, ma non perché superi e risolva in sé l'altro termine, sibbene semplicemente è luce verso la tenebra, è bene, è virtù; insomma, in ragione della sua qualità stessa, che il poeta discerne e coglie nella purezza e verità originale, senza sofisticarla e infiacchirla.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "La quintessenza di tutte queste commede (al modo stesso che, rispetto alle grandi tragedie, si può in certo senso dire dell'Amleto'') è il \"Sogno di una notte di mezza estate\"; dove le rapide accensioni, le incostanze, i capricci, le illusioni e le delusioni, le follie d'ogni sorta dell'amore si danno un corpo e tessono un loro mondo così vivo e reale come quello degli uomini che quegli affetti visitano, estasiandoli e tormentandoli, innalzandoli e abbassandoli; sicché tutto vi è parimente reale e parimente fantastico, secondo meglio piaccia chiamarlo. Il senso del sogno, di un sogno-realtà, permane e impedisce ogni freddezza di allegoria e di apologo.", Author = "Benedetto Croce" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Benedetto_Croce", Text = "Quando dopo il \"Sogno\", si legge \"Romeo e Giulietta\", par di non essere usciti da quell'ambiente poetico, al quale espressamente ci richiamano Mercutio, col suo ricamo fantastico sulla Regina Mab, e, quel che è più, lo stile, le rime e la generale fisionomia della breve favola. Tutti, parlando di \"Romeo e Giulietta\", hanno provato il bisogno di ricorrere a parole e immagini soavi e gentili; e lo Schlegel vi ha sentito «i profumi della primavera, il canto dell'usignuolo, il delicato e fresco di una rosa mo' sbocciata», e lo Hegel ha pensato allo stesso fiore: alla", Author = "Benedetto Croce" },
        };
    }
}