using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class CarloEmilioGadda
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "È spiacevole dover parlare di avvenimenti spiacevoli: ma la chiarezza è la prima qualità di un racconto.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Gli italiani, generosissimi in tutto, non sono generosi quando si tratta di pensare.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Il dirmi che una scarica di mitra è realtà mi va bene, certo; ma io chiedo al romanzo che dietro questi due ettogrammi di piombo ci sia una tensione tragica, una consecuzione operante, un mistero, forse le ragioni o le irragioni del fatto.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "La mia biografia è ricchissima di deliziose pre-conferme alle «analisi» degli specializzati e alle loro complesse sistemazioni dottrinali.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "La sopportabilità massima del parlato-unito, in Italia, è di quindici minuti.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "La ''Conversazione in Sicilia'' di Vittorini esprime nei segni di poesia amore e pietà di questi suoi fratelli diseredati.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Noi viviamo di passato. Siamo degli stracchi rentiers che vivacchiano nell'accumulo lento del passato.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Una difficilissima elaborazione e costruzione morale fatta di incredibili sforzi e autoinibizioni individuali e puri e leganti entusiasmi, darà una più perfetta socialità di quella in che siamo oggi immersi.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Le parole non bastano e sdraiarsi nel comodo letto della vanità ciarliera è come farsi smidollare da una cupa e sonnolenta meretrice.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Ogni fatto o atto della vita e della coscienza è reato per chi fonda il suo imperio col proibire tutto a tutti, coltello alla cintola.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Il pontecorvo ha capellatura corvina: e naso matematico.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Le parole sacre, vedute le labbra dell'autore, ne rifuggono. Le cose sacre, veduto il cuore dell'autore, vi si fermano.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "L'italiani sono di simulato sospiro.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Morire per la patria è cosa dolce e onorevole: infatti alcuni sono morti per la patria immortale: ed altri, a guardarla dalle tignole, è bisognato vivessero. Questa favoletta ne dice: il morto giace, il vivo si dà pace.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Camminava tra i vivi. Andava i cammini degli uomini.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Era il male oscuro di cui le storie e le leggi e le universe discipline delle gran cattedre persistono a dover ignorare la causa, i modi: e lo si porta dentro di sé per tutto il fulgurato scoscendere d'una vita, più greve ogni giorno, immedicato.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "le moribonde parole dello Incas. Secondo cui la morte arriva per nulla, circonfusa di silenzio, come una tacita, ultima combinazione del pensiero.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "L'umanità Questo mare senza requie, fuori, sciabordava contro l'approdo di demenza, si abbatteva alle dementi riviere offrendo la sua perenne schiuma, ribevendosi la sua turpe risacca.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Se un'idea è più moderna di un'altra, è segno che non sono immortali né l'una né l'altra.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Un'infanzia tormentata e un'adolescenza anche più dolorosa.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "l'io, io!... il più lurido di tutti i pronomi!... I pronomi! Sono i pidocchi del pensiero.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Ma sognare è un fiume profondo, che precipita a una lontana sorgiva, ripùllula nel mattino di verità.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Che bravi! Le finestre han cornici barocche di pietra grigia, e fra la seconda e la terza del primo piano, sopra un bel balcone di ferro battuto, e panciuto, c'è dipinta una Madonna che appare benedicente a San Carlo Borromeo.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Certi imparaticci poi, recitati a gran voce dai concionanti droghieri, improvvisatisi economisti della nuova Europa, gli parevano indegni d'un venditore ambulante di fazzoletti.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Gentilissima Signora, al solito si è venuto accumulando in me, dopo le sue amichevoli, fraterne lettere, il nembo dei rimorsi, sospinto dalla bufera ciclonica della vergogna.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Subito preso dal lavoro della «puntata» per «Letteratura», passo giorni angosciosi. Ma risorgerò alla vita.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "La vitalità di questi mostriciattoli è una cosa incredibile. Verrebbe voglia di accarezzarli, poi di acciaccarli.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Là c'era il comando dell'Arma: là, là, da più lune, la sua pratica risognata attendeva, attendeva.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Don Ciccio moderò il galoppo della smania, tirò le redini allo scalpitare della rabbia.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "La volizione del volitivo giovane involveva già del suo velle la fuggitiva labilità degli eventi.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Come si capì dopo, il chiodo senatoriale era stato ribadito dalle martellate categorizzanti della signora Vigoni.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Senonché l'Adalgisa era di quelle meravigliose donne lombarde che estrinsecano la propria forma mentis nel postulare dovunque e davanti a chiunque la certezza della propria infallibilità.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "«Sei stupido!» «E tu sei scemo!» «Finitela!», si inviperì l'Adalgisa fuori di sé. «Finiscila Peppo o ti dò uno schiaffo!» E lo schiaffo arrivò difatti più rapido ancora dell'ipotesi, come il lampo in precedenza del tuono.–", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Il flusso continuo dei taxi, sul viale maggiore, pareva la vana furia degli uomini, che ad ogni costo volesse arrivare a una fine.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Insomma gli schidioni della cintura di castità erano ancora nel magazzino delle idee compossibili. O servivano ai rosticceri di via Larga, da infilarci dei polli.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Così la mia gente si fa ignara dell'inutile: dei segni che dici di bellezza non caverai càvolo per il bottaggio, di verità non caverai cotechino.", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Nei loro cuori è la fede: una certezza, una sicurezza salda: nessun lezzo di critica maldigesta contaminerà l'affermazione perenne: «Io sono il tuo Politecnico e tu non avrai altro Politecnico avanti di me».", Author = "Carlo Emilio Gadda" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Carlo_Emilio_Gadda", Text = "Un'idea, un'idea non sovviene, alla fatica de' cantieri, mentre i sibilanti congegni degli atti trasformano in cose le cose e il lavoro è pieno di sudore e di polvere.", Author = "Carlo Emilio Gadda" },
        };
    }
}