using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class DinoBuzzati
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Chi ha dato tanto alla montagna, chi per la montagna ha rischiato con tanto accanimento la vita, a questo amore resterà legato per sempre.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Ciascuno di noi forse porta scritta in una recondita particella del corpo, la propria finale condanna. Ma perché andare determinatamente a disseppellirla?", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "E se l'idea di poter prolungare l'esistenza al nostro cane ci seduce non è solo perché gli vogliamo bene, ma anche per amore di noi stessi.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Ho visto correre il tempo, ahimè, quanti anni e mesi e giorni, in mezzo a noi uomini, cambiandoci la faccia a poco a poco; e la sua velocità spaventosa, benché non cronometrata, presumo sia molto più alta di qualsiasi media totalizzata da qualsiasi corridore in bicicletta, in auto o in aeroplano-razzo da che mondo è mondo.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Il film ci rivela quanto abietto, crudele e stolto è l'uomo: è quindi una lezione di umiltà.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Io voglio ricordarmi di essere stato [...]. Divenire un'anima felice che ignora di essere stato Dino Buzzati, è una fregatura.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "L'opportunismo e l'arrivismo filo-marxista dei miei colleghi mi fa venire il vomito, e come primo impulso mi fa diventare assertore della monarchia assoluta.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La solitudine si accresce quante più persone conosciamo.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Una cretinèria bell'e buona.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Una specie di demonio si aggira dunque per la città, invisibile, e sta forse preparandosi a nuovo sangue.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La gente comincia ad avere paura. Non è più una faccenda altrui, buona per quattro chiacchiere fra comari, e dopo dieci minuti non ci si pensa più; nessuno può dirsene estraneo, l'ombra del male scivola intorno a ciascuno di noi e ci potrebbe toccare.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "E voi parlatene pure, se vi interessa tanto, leggete i resoconti, contemplate le fotografie, andate pure, se non potete farne a meno, alla Corte d'Assise, discutetene alla sera. Però vi resti fitto nel cuore il ricordo di quei tre bimbi selvaggiamente uccisi, di quei tre faccini rimasti là, immobili per sempre, con l'espressione stupefatta, di quel seggiolone da lattante da cui colò ilo tenero sangue. Le anime dei tre innocenti sovrastano, con pallida e dolorosa luce, la folla riunita al tribunale; e può darsi che vi guardino.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Può darsi che per colpa del mio dannato carattere, io muoia solo come un cane in fondo ad un vecchio e deserto corridoio. Eppure una persona quella sera inciamperà nella gobbetta cresciuta nel suo giardino e inciamperà anche la notte successiva e ogni volta penserà, perdonate la mia speranza, con un filo di rimpianto, penserà ad un certo tipo che si chiamava Dino Buzzati.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Cessati l'assalto al potere e la smania del predominio, si vide che dovunque si stabilivano automaticamente la giustizia e la pace.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "E di innumerevoli afflizioni è generoso il mondo, ma i morsi dell'invidia sono tra le ferite più sanguinose, profonde, difficili, da rimarginare e complessivamente degne di pietà.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Le storie che si scriveranno, i quadri che si dipingeranno, le musiche che si comporranno, le stolte pazze incomprensibili e inutili cose che tu dici, saranno pur sempre la punta massima dell'uomo, la sua autentica bandiera [...] quelle idiozie che tu dici saranno ancora la cosa che più ci distingue dalle bestie, non importa se supremamente inutili, forse anzi proprio per questo.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Perché le differenze continuano a esistere finché noi viviamo parliamo vestiamo, ciascuno recitando la sua bella commedia, poi basta: poi tutti uguali nell'identica positura della morte, così semplice, così confacente ai requisiti dell'eternità.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Che cosa sei Noretta col tuo palloncino attraversando il paese nel mattino della domenica? Sei la sposa raggiante che esce dalla chiesa, sei la regina in trionfo dopo la vittoria, sei la divina cantante sollevata a spalle dalla folla in delirio, sei la donna più ricca e bella del mondo, sei l'amore grande e fortunato, i fiori, la musica, la luna, le foreste e il sole, tutto questo in una sola volta sei perché un palloncino di guttaperca pneumatica ti ha resa felice.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Guardava dinnanzi a sé i parchi, i campi, i boschi, le montagne, le misteriose montagne. Vendetta, che inutile cosa.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Ogni vero dolore viene scritto su lastre di una sostanza misteriosa al paragone della quale il granito è burro. E non basta una eternità per cancellarlo.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Niente? Proprio niente rimane. Di mia mamma non esiste più nulla? Chissà. Di quando in quando, specialmente nel pomeriggio, se mi trovo solo, provo una sensazione strana.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Fino allora egli era avanzato per la spensierata età della prima giovinezza, una strada che da bambini sia infinita, dove gli anni scorrono lenti e con passo lieve, così che nessuno nota la loro partenza.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Ma a un certo punto, istintivamente, ci si volta indietro e si vede che un cancello è stato sprangato alle spalle nostre, chiudendo la via del ritorno. Allora si sente che qualche cosa è cambiato, il sole non sembra più immobile ma si sposta rapidamente, ahimè, non si fa tempo a fissarlo che già precipita verso il fiume dell'orizzonte, ci si accorge che le nubi non ristagnano più nei golfi azzurri del cielo ma fuggono accavallandosi l'una sull'altra, tanto è il loro affanno; si capisce che il tempo passa e che la strada un giorno dovrà pur finire.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Nel sogno c'è sempre qualcosa di assurdo e confuso, non ci si libera mai della vaga sensazione ch'è tutto falso, che un bel momento ci si dovrà svegliare.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Così una pagina lentamente si volta, si distende dalla parte opposta, aggiungendosi alle altre già finite, per ora è solamente uno strato sottile, quelle che rimangono da leggere sono in confronto un mucchio inesauribile.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Proprio in quel tempo Drogo si accorse come gli uomini, per quanto possano volersi bene, rimangono sempre lontani; che se uno soffre il dolore è completamente suo, nessun altro può prenderne su di sé una minima parte; che se uno soffre, gli altri per questo non sentono male, anche se l'amore è grande, e questo provoca la solitudine della vita.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Eppure il tempo soffiava; senza curarsi degli uomini passava su e giù per il mondo mortificando le cose belle; e nessuno riusciva a sfuggirgli, nemmeno i bambini appena nati, ancora sprovvisti di nome.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Gli parve che la fuga del tempo si fosse fermata, il mondo ristagnava in una orizzontale apatia e gli orologi correvano inutilmente. La strada di Drogo era finita; eccolo ora sulla solitaria riva di un mare grigio e uniforme.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Era stato l'uomo a cancellare quella residua macchia del mondo, l'uomo astuto e potente che dovunque stabilisce sapienti leggi per l'ordine, l'uomo incensurabile che si affatica per il progresso e non può ammettere in alcun modo la sopravvivenza dei draghi, sia pure nelle sperdute montagne.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "No, non è specialmente grande rispetto ad altri giovani compagni, ma in un certo senso è magnifico, lui che è una delle bestie più brutte del mondo.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Che peso, la presenza di Dio per chi non la desidera.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La luna [...] la placida abitatrice delle nostre notti, propizia agli incantesimi d'amore, discreta amica al cui lume favoloso le catapecchie diventavano castelli.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Le donne sono famose per costruir romanzi inverosimili.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "È la pace di colui che si sente in armonia con la massa che lo attornia. Oppure è l'inquietudine, il disagio, lo smarrimento di chi si allontana dalla norma.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Anche il più nobile sentimento si atrofizza e si dissolve a poco a poco, se nessuno intorno ne fa più caso. È triste dirlo, ma a desiderare il Paradiso non si può essere soli.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "E come nella vita l'attesa di un bene certo ci dà più gioia che il raggiungerlo (ed è saggio non approfittarne subito, ma conviene assaporare quella meravigliosa specie di desiderio che è il desiderio sicuro di essere appagato ma non ancora praticamente soddisfatto, l'attesa insomma che non ha più timori e dubbi e che rappresenta probabilmente l'unica forma di felicità concessa all'uomo), come la primavera, che è una promessa, rallegra gli uomini più dell'estate che ne è il compimento sospirato, così il pregustare con la fantasia lo splendore del poema ignoto, equivale, anzi supera il godimento artistico della diretta e profonda conoscenza.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La consolazione, la felicità era tale che il modo di raggiungerla non aveva più alcuna importanza.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La donna, forse a motivo dell'educazione familiare, gli era parsa sempre una creatura straniera, con una donna non era mai riuscito ad avere la confidenza che aveva con gli amici. La donna era sempre per lui la creatura di un altro mondo, vagamente superiore e indecifrabile.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Lui si ricordò di una Madonna di Antonello da Messina. Il taglio del volto e la bocca erano identici. La madonna aveva più dolcezza, certo. Ma lo stesso stampo netto e genuino.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "D'improvviso si rende conto di quello che forse sapeva già ma finora non ha mai voluto crederci. Come chi da tempo avverte i sintomi inconfondibili di un male orrendo ma ostinatamente riesce a interpretarli in modo da poter continuare la vita come prima ma viene il momento che, per la violenza del dolore, egli si arrende e la verità gli appare dinnanzi limpida e atroce e allora tutto della vita repentinamente cambia senso e le cose più care si allontanano diventando straniere, vacue e repulsive, e inutilmente l'uomo cerca intorno qualcosa a cui attaccarsi per sperare, egli è completamente disarmato e solo, nulla esiste oltre la malattia che lo divora, è qui se mai l'unico suo scampo, di riuscire a liberarsi, oppure di sopportarla almeno, di tenerla a bada, di resistere fino a che l'infezione col tempo esaurisca il suo furore.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "C'è, nel motivo popolaresco della musica, semplice come uno stecco eppure carico di secoli, qualcosa che precisamente diceva addio, con potenza d'amore per quello che fu e mai ritornerà e nello stesso tempo un confuso presentimento di cose che un giorno verranno, forse, perché la musica vera è tutta qui nel rimpianto del passato e nella speranza del domani, la quale è altrettanto dolorosa. Poi c'è la disperazione dell'oggi, fatta dell'uno e dell'altra. E fuori di qui altra poesia non esiste.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Eppure, in quella svergognata e puntigliosa ragazzina una bellezza risplendeva ch'egli non riusciva a definire per cui era diversa da tutte le altre ragazze come lei, pronte a rispondere al telefono. Le altre, al paragone, erano morte.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Guardò le dodici e venti. Laide non telefonerà più. Ma esiste la Laide? Esiste una ragazza con un nome così buffo? Non era mai esistita. E' esistita ma non esiste più. Esiste ma lontana lontanissima le dodici e ventuno l'orologio non ha fatto trac adesso finalmente anche lui ha sentito. Non la rivedrò mai più.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Come se qualcosa lo avesse toccato dentro. Come se quella ragazza fosse diversa dalle solite. Come se fra loro due dovessero succedere molte altre cose. Come se lui ne fosse uscito differente. Come se Laide incarnasse nel modo più perfetto e intenso il mondo avventuroso e proibito.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "La Laide era una delle tante. Graziosa, certo, genuina, fisicamente spiritosa. Ma vuota. Fra lui e lei non ci sarebbe stato mai niente. Del resto il giorno dopo partì con Soranza, il suo amico, per andare a sciare.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Ora si accorge che, per quanto egli cerchi di ribellarsi, il pensiero di lei lo perseguita in ogni istante millimetrico della giornata, ogni cosa persona situazione lettura ricordo lo riconduce fulmineamente a lei attraverso tortuosi e maligni riferimenti.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Eppure anche a cinquant'anni si può essere bambini, esattamente deboli smarriti e spaventati come il bambino che si è perso nel buio della selva. L'inquietudine, la sete, la paura, lo sbigottimento, la gelosia, l'impazienza, la disperazione. L'amore!", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "No. Lui la amava per se stessa, per quello che rappresentava di femmina, di capriccio, di giovinezza, di genuino popolana, di malizia, di inverecondia, di sfrontatezza, di libertà, di mistero.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Tante volte era rimasto in ammirazione dinanzi a un paesaggio, a un monumento, a una piazza, a uno scorcio di strada, a un giardino, a un interno di chiesa, a una rupe, a un viottolo, a un deserto. Solo adesso, finalmente, si rendeva conto del segreto. Un segreto molto semplice: l'amore.", Author = "Dino Buzzati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Dino_Buzzati", Text = "Era molto più delicato e tenero di quanto si credesse. Era fatto di quell'impalpabile sostanza che volgarmente si chiama favola o illusione: anche se vero.", Author = "Dino Buzzati" },
        };
    }
}