using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class FrancescoPetrarca
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "A che ti giova insegnare agli altri, se intanto tu per primo non ascolti te stesso?", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ho sempre avuto il massimo disprezzo per le ricchezze, non perché non mi piacessero, ma perché odiavo le fatiche e le preoccupazioni che ne derivano.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "I libri fecero diventare dotti alcuni, altri pazzi.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Il mondo, più che io lo giro, e meno mi piace.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Il saggio muta consiglio, ma lo stolto resta della sua opinione.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La fatica perseverante e la continua applicazione sono il cibo del mio spirito; quando comincerò a riposare e a rallentare il mio lavoro, allora cesserò anche di vivere.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Non so saziare la brama di aver libri, avvegnaché già molti, e forse più del bisogno io ne possegga.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ora questi, ora quelli io interrogo, ed essi mi rispondono, e per me cantano e parlano.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Quegli cui non è castigo sufficiente una moglie, è degno di averne parecchie.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Sento qualcosa di insoddisfatto nel mio cuore, sempre.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ventosa gloria è il cercar fama dalla splendidezza delle parole.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "L'antiquo valore Ne l'italici cor non è ancor morto.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Io parlo per ver dire Non per odio d'altrui né per disprezzo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "I' vo gridando: pace, pace, pace.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Non era l'andar suo cosa mortale, ma d'angelica forma; e le parole sonavan altro che, pur voce umana;", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Pace non trovo, et non ò da far guerra; e temo, et spero; et ardo, et son un ghiaccio; et volo sopra 'l cielo, et giaccio in terra; et nulla stringo, et tutto 'l mondo abbraccio.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Il bel paese ch'Appennin parte e 'l mar circonda e l'Alpe.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Chiare, fresche et dolci acque, ove le belle membra pose colei che sola a me par donna.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "O viva morte, o dilectoso male", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ché bel fin fa chi ben amando more.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Et veggio 'l meglio, et al peggior m'appiglio.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Cosa bella e mortal passa e non dura.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Chi pò dir com'egli arde d'amore, è 'n picciol foco.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Alma real, dignissima d'impero", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Cercato ò sempre solitaria vita per fuggir questi ingegni sordi et loschi, che la strada del cielo ànno smarrita.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Arbor victorïosa trumphale, honor d'imperadori et di poeti.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La vita fugge e non s'arresta un'ora.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Questo nostro caduco e fragil bene ch'è vento ed ombra ed à nome beltade.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Drez et rayson es qu'ieu ciant e 'm demori", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La vita el fin, e 'l dí loda la sera.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Povera et nuda vai philosophia.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Regnano i sensi, et la ragion è morta.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Sarò qual fui, vivrò com'io son visso.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Seguite i pochi, et non la volgar gente.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Un bel morir tutta la vita honora.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Vertú contra furore prenderà l'arme, et fia 'l combatter corto: ché l'antiquo valore ne gli italici cor' non è anchor morto.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Io credo che un animo nobile, eccetto che in Dio, dov'è il nostro fine estremo, eccetto che in sé stesso e nei suoi segreti pensieri o in qualche animo a lui congiunto da una grande affinità, non trovi pace in alcun luogo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "ogni persona indaffarata è infelice e lo è doppiamente se è alle dipendenze di un'altra persona, poiché ha la propria infelicità, ma non gode dei suoi frutti vantaggiosi.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "una verità universale, certo, non crolla per pochissime obiezioni.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ahimè, com'è forte in me il timore che tra coloro che pretendono d'essere considerati custodi delle pecore malate vi siano dei lupi che divorino quelle sane!", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ogniqualvolta decidiamo di intraprendere o di cambiare genere di vita, dobbiamo tenere innanzi agli occhi soprattutto questo: di non seguire la via che ci apparirà più splendida, ma quella che sarà più adatta a noi, confidando non su una vana passione, ma sulla guida della natura.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La solitudine è santa, semplice, incorrotta e davvero la più pura di tutte le cose umane.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "molti possono essere costretti ad affermare qualcosa, nessuno a crederlo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "la fine dell'infelicità è l'inizio della felicità, poiché la legge dei contrari esige che, dove questa termini, quella abbia principio.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ho provato gli stimoli che essa dà all'animo, le ali che fornisce all'ingegno, il tempo che accorda libero al lavoro: tutte cose che non saprei dove cercare al di fuori della solitudine.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "e in verità mai mi sembrerà che la presenza di un amico interrompa la solitudine, bensì che la adorni.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Come è grande dunque il piacere, come è grande la sicurezza data dalla solitudine che ha attraversato tutti i pericoli ed enumera, alle sue spalle, lontano, i propri mali!", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Benché infatti ogni natura abbia i propri difetti, tuttavia gran parte dei mali deriva da una sorta di emulazione e dalla smania di imitare.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Non cesserà mai di essere in ansia chi sarà sempre proteso verso il domani: nessun giorno infatti, eccetto l'ultimo, sarà privo di un domani e nessuno, eccetto il primo, non è stato il domani di qualche altro giorno.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "a poco a poco, in ogni luogo della terra, tutto decade: tutti i buoni costumi hanno breve durata, quelli cattivi invece sono eterni.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "fuggire le sciagure che non possiamo mettere in fuga.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ricerco inoltre libri di generi differenti che, per gli autori che li hanno scritti o per gli argomenti di cui trattano, siano nello stesso tempo compagni graditi e fedeli.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Solo al medico è conceduto dar morte agli uomini impunemente.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Non sono né vivo né sano, né morto né malato; allora soltanto comincerò a vivere e a star bene, quando troverò l'uscita di questo labirinto.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Povera e nuda vai, Filosofia.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Vergine chiara e stabile in eterno, Di questo tempestoso mare Stella, D'ogni fedel nocchier fidata guida, Pon mente in che terribile procella I mi ritrovo sol senza governo, Ed ho già da vicin l' ultime strida: Ma pur in te l'anima mia si fida.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Tennemi Amor anni ventuno ardendo Lieto nel foco, e nel duol pien di speme: Poiché Madonna e 'l mio cor seco insieme Saliro al ciel, dieci altri anni piangendo", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Tra lo stil de' moderni e 'l sermon prisco.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "I' da man manca, e' tenne il camin dritto: I' tratto a froza, ed e' d'Amore scorto: Egli in Jerusalem, ed io in Egitto.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ira è breve furor.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La vita el fin e 'l dì loda la sera.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Da me son fatti i miei pensier diversi.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Tempo non mi parea da far riparo Contr' a' colpi d'Amor.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La noia e 'l mal della passata via.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "El più bel fior ne colse.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Intendami chi po', ch'i' m'intend'io.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "E già di là dal rio passato è 'l merlo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "I' benedico il loco e 'l tempo e 'l ora.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Veggio 'l meglio ed al peggior m'appiglio.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Nel mondo Sua ventura ha ciascun dal dì che nasce.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Che 'nanzi al dì de l'ultima partita Uom beato chiamar non si convene.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Non era l'andar suo cosa mortale Ma d'angelica forma.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Poi che mia speme è lunga a venir troppo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Seguite i pochi, e non la volgar gente.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Né del vulgo mi cal né di fortuna.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Femina è cosa mobil per natura: ond'io so ben ch'un amoroso stato in cor di donna picciol tempo dura.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Lo spirito è pronto, ma la carne è stanca.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Morte fura prima i migliori, e lascia star i rei.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Così or quinci or quindi rimirando, Vidi in una fiorita e verde piaggia Gente che d'amor givan ragionando.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "I' che gioir di tal vista non soglio per lo secol noioso in ch'i' mi trovo, voto d'ogni valor, pien d'ogni orgoglio, l'abito in vista sì leggiadro e novo mirai, alzando gli occhi gravi e stanchi, ch'altro diletto che 'mparar non provo.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Tal biasma altrui che sè stesso condanna.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Stanco già di mirar, non sazio ancora.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ben è 'l viver mortal, che sì n'aggrada, Sogno d'infermi e fola di romanzi.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Tutti siam macchiati d'una pece.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "S'Affrica pianse, Italia non ne rise.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Ragion contra forza non ha loco.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Nel fuggir del sole La ruina del mondo manifesta.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Infinita è la schiera degli sciocchi.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Passan vostri triunfi e vostre pompe, Passan le signorie, passano i regni; Ogni cosa mortal Tempo interrompe.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Passa il penser sì come sole in vetro, anzi più assai, però che nulla il tene.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "degna di poema chiarissimo e d'istoria.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "O ciechi, il tanto affaticar che giova? Tutti torniamo a la grande madre antica, e il nome nostro a pena si ritrova.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "La morte è fin d'una pregione oscura a l'anime gentili; a l'altre è noia, ch'hanno posto nel fango ogni lor cura.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "che altro ch'un sospir breve è la morte?", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Pensier canuti in giovenil etate.", Author = "Francesco Petrarca" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Francesco_Petrarca", Text = "Passammo al tempio poi di Pudicizia, ch'accende in cor gentil oneste voglie, non di gente plebeia ma di patrizia.", Author = "Francesco Petrarca" },
        };
    }
}