using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class GiambattistaVico
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La provvidenza ordinò che nel censo vi fosse la regola degli onori; e così gli industriosi non gl'infingardi, i parchi non i prodighi, i prodighi non gli scioperati e in una parola i ricchi con qualche virtù, non i poveri con molti e sfacciati vizi, fossero estimati gli ottimi del Governo.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La filosofia, per giovar al gener umano, dee sollevar e reggere l'uomo caduto e debole, non convellergli la natura né abbandonarlo nella sua corrozione.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La filosofia considera l'uomo quale dev'essere, e sì non può fruttare ch'a pochissimi, che vogliono vivere nella repubblica di Platone, non rovesciarsi nella feccia di Romolo.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Le cose fuori del loro stato naturale né vi si adagiano né vi durano.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La filosofia contempla la ragione, onde viene la scienza del vero; la filologia osserva l'autorità dell'umano arbitrio, onde viene la coscienza del certo.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Il senso comune è un giudizio senz'alcuna riflessione, comunemente sentito da tutto un ordine, da tutto un popolo, da tutta una nazione, o da tutto il gener umano.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "È necessario che vi sia nella natura delle cose umane una lingua mentale comune a tutte le nazioni, la quale uniformemente intenda la sostanza delle cose agibili nell'umana vita socievole, e la spieghi con tante diverse modificazioni per quanti diversi aspetti possan aver esse cose; siccome lo sperimentiamo vero ne' proverbi, che sono massime di sapienza volgare, l'istesse in sostanza intese da tutte le nazioni antiche e moderne, quante elleno sono, per tanti diversi aspetti significate.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La maraviglia è figliuola dell'ignoranza; e quanto l'effetto ammirato è più grande, tanto più a proporzione cresce la maraviglia.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La fantasia tanto è più robusta quanto è più debole il raziocinio.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Il più sublime lavoro della poesia è alle cose insensate dare senso e passione, ed è proprietà de' fanciulli di prender cose inanimate tra mani e, trastullandosi, favellarvi come se fussero, quelle, persone vive. Questa degnità filologico-filosofica ne appruova che gli uomini del mondo fanciullo, per natura, furono sublimi poeti.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La curiosità, propietà connaturale dell'uomo, figliuola dell'ignoranza, che partorisce la scienza, all'aprire che fa della nostra mente la maraviglia, porta questo costume: ch'ove osserva straordinario effetto in natura, come cometa, parelio o stella di mezzodì, subito domanda che tal cosa voglia dire o significare.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Le streghe, nel tempo stesso che sono ricolme di spaventose superstizioni, sono sommamente fiere ed immani; talché, se bisogna per solennizzare le loro stregonerie, esse uccidono spietatamente e fanno in brani amabilissimi innocenti bambini.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La fantasia [...] altro non è, che memoria o dilatata, o composta.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Gli uomini sfogano le grandi passioni dando nel canto, come si sperimenta ne' sommamente addolorati e allegri.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La mente umana è inchinata naturalmente co' sensi a vedersi fuori nel corpo, e con molta difficultà per mezzo della riflessione ad intendere se medesima.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "L'ordine delle idee dee procedere secondo l'ordine delle cose.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Gli uomini prima sentono il necessario, dipoi badano all'utile, appresso avvertiscono il comodo, più innanzi si dilettano del piacere, quindi si dissolvono nel lusso, e finalmente impazzano in istrappazzar le sostanze.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La natura de' popoli prima è cruda; dipoi severa, quindi benigna, appresso dilicata, finalmente dissoluta.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "I governi debbon esser conformi alla natura degli uomini governati.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "L'onore è 'l più nobile stimolo del valor militare.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "I deboli vogliono le leggi; i potenti le ricusano; gli ambiziosi, per farsi séguito, le promuovono; i principi, per uguagliar i potenti co' deboli, le proteggono.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Osserviamo tutte le nazioni così barbare come umane, quantunque, per immensi spazi di luoghi e tempi tra loro lontane, divisamente fondate, custodire questi tre umani costumi: che tutte hanno qualche religione, tutte contraggono matrimoni solenni, tutte seppelliscono i loro morti.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "L'ironia certamente non poté cominciare che da' tempi della riflessione, perch'ella è formata dal falso in forza d'una riflessione che prende maschera di verità.", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "Il sillogismo [...] è un metodo che più tosto spiega gli universali ne' loro particolari che unisce particolari per raccogliere universali [...].", Author = "Giambattista Vico" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giambattista_Vico", Text = "La vera Unità, il vero Uno, l'Unico è sviluppo; sviluppo di se stesso: da se stesso, per se stesso, a se stesso: cioè veramente e totalmente Se stesso. Questo è il nuovo concetto, che, più o meno espressamente, consapevolmente e inconsapevolmente, è l'anima di tutta la Scienza nuova: è il gran valore di Vico.", Author = "Bertrando Spaventa" },
        };
    }
}