using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class GiordanoBruno
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Chi, perciò, consistendo nel luogo e nel tempo, libererà le ragioni delle idee dal luogo e dal tempo, si conformerà agli enti divini.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Colui che vede in se stesso tutte le cose è al tempo stesso tutte le cose.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "E noi, per quanto ci troviamo in situazioni inique [...] tuttavia serbiamo il nostro invincibile proposito [...] tanto da non temere la morte stessa.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ho lottato, è molto; ho creduto nella mia vittoria [...]. È già qualcosa essere arrivati fin qui [...]. Non aver temuto di morire, [...] aver preferito coraggiosa morte a vita imbelle.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "I filosofi sono in qualche modo pittori e poeti, i poeti sono pittori e filosofi, i pittori sono filosofi e poeti. Donde i veri poeti, i veri pittori e i veri filosofi si prediligono l'un con l'altro e si ammirano vicendevolmente.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "La sapienza ha dunque tre dimore: la prima inedificata, eterna, perché è essa stessa la sede dell'eternità; la seconda, sua primogenita, è questo mondo visibile; la terza, sua secondogenita, è l'anima dell'uomo.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Non è dunque filosofo se non chi immagina e riproduce.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ogni volta, infatti, che riteniamo che rimanga una qualche verità da conoscere, un qualche bene da raggiungere, noi sempre ricerchiamo un'altra verità ed aspiriamo ad un altro bene. Insomma l'indagine e la ricerca non si appagheranno nel conseguimento di una verità limitata e di un bene definito. [...] Nello stesso modo la materia particolare, sia essa corporea o incorporea, non assume mai una struttura definitiva, e non essendo paga delle forme particolari assunte in eterno, aspira nondimeno in eterno al conseguimento di nuove forme.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Venni, tra gli altri io, attratto dal desiderio di visitare la casa della sapienza, ardente di contemplare codesto Palladio, onde non mi vergogno d'aver sopportato la povertà, la malevolenza e l'odio dei miei, le esacrazioni, le ingratitudini di coloro ai quali volli giovare e giovai, gli effetti d'un'estrema barbarie e d'un'avarizia sordidissima; [...]. Per il che non mi duole d'esser incorso in fatiche, dolori, esilio: ché faticando profittai, soffrendo feci esperienza, vivendo esule imparai: ché trovai in breve fatica lunga quiete, in leggera sofferenza gaudio immenso, in un angusto esilio una patria grandissima.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Io dirò la verità, più volte m'è stato minacciato de farmi venire a questo Santo Offitio, et sempre l'ho tenuto per burla, perche io son pronto a dar conto di me.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Parlando cristianamente e secondo la teologia e che ogni fidel cristiano e catolico deve creder, ho in effetti dubitato circa il nome di persona del Figliuolo e del Spirito santo, non intendendo queste due persone distinte dal Padre se non nella maniera che ho detto de sopra, parlando filosoficamente.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Io credo che nelle mie opere si troveranno scritte molte cose, quali saranno contrarie alla fede catolica [...] ma però io non ho detto né scritto queste cose ex professo, né per impugnar direttamente la fede catolica, ma fondandomi solamente nelle raggioni filosofiche o recitando le opinion de eretici.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Quanto a questo io ne ho parlato qualche volta, dicendo che il peccato della carne, parlando in genere, era il minor peccato delli altri.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Questo non si troverà mai nelle mie parole, né meno nelle mie scritture, perché non ho mai detto né scritto che l'azioni del mondo si governano dal fato e non dalla providenzia divina; anzi ritrovarete nei miei libri che io pongo la providenzia ed il libero arbitrio, da che se comprende, come si dà il libero arbitrio, se oppugna il fato.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Io non tengo per nimico in queste parti alcun altro se non il S.r Gioanni Mocenigo ed altri suoi seguaci e servitori, dal quale sono stato più gravemente offeso che da omo vivente; perché lui me ha assassinato nella vita, nello onore e nelle robbe.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Bella Chiesa è questa governata da ignorantazzi et asini.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "La messa è una biastema e una mala cosa, perché in quella il pane non è transubstantiato ne la carne di Christo, come dite voi altri, e come ne la messa si alza su l'ostia, così tu sarai alzato su la forca.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Sino Christo ha peccato quando non volse fare la volontà del Padre.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Nella tristezza ilare, nell'ilarità triste.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ricordatevi, Signora, di quel che credo non bisogna insegnarvi: «Il tempo tutto toglie e tutto dà; ogni cosa si muta, nulla s'annichila; è un solo che non può mutarsi, un solo è eterno, e può perseverare eternamente uno, simile e medesmo».", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Con questa filosofia l'animo mi s'aggrandisse, e me si magnifica l'intelletto. Però, qualunque sii il punto di questa sera ch'aspetto, si la mutazione è vera, io che son ne la notte, aspetto il giorno, e quei che son nel giorno, aspettano la notte.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Son tre materie principali intessute insieme ne la presente comedia: l'amor di Bonifacio, l'alchimia di Bartolomeo e la pedanteria di Manfurio.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "L'autore, si voi lo conoscete, direste ch'ave una fisionomia smarrita: par che sii in contemplazione delle pene dell'inferno, par sii stato alla pressa come le barrette: un che ride sol per far come fan gli altri: per il più lo vedrete fastidito e bizzarro, non si contenta di nulla, ritroso come un vecchio d'ottant'anni, fantastico com'un cane ch'ha ricevute mille spellicciate, pasciuto di cipolla.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Questa è una specie di tela, ch'ha l'ordimento e tessitura insieme: chi la può capir, la capisca; chi la vuol intendere, l'intenda. Ma non lascierò per questo di avertirvi che dovete pensare di essere nella regalissima città di Napoli, vicino al seggio di Nilo. Questa casa che vedete qua formata, per questa notte servirà per certi barri, furbi e marioli, – guardatevi, pur voi, che non vi faccian vedovi di qualche cosa che portate adosso: – qua costoro stenderranno le sue rete, e zara a chi tocca.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Questo animale che chiamiamo Amore, per il più suole assalire colui ch'ha poco da pensare e manco da fare.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "È buon segno quando le cose vanno per la mente: guardati che la mente non vadi essa per le cose, perché potrebbe rimaner attaccata con qualch'una di quelle, ed il cervello, la sera, indarno l'aspetterebbe a cena.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "I savi vivono per i pazzi, ed i pazzi per i savii. Si tutti fussero signori, non sarebbono signori: cossì, se tutti saggi, non sarebbono saggi, e se tutti pazzi, non sarebbono pazzi. Il mondo sta bene come sta.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Erbe, parole e pietre son materia di virtù a presso certi filosofi matti ed insensati, li quali, odiati da Dio, dalla natura e dalla fortuna, si vedono morir di fame, lagnarsi senza un poverello quattrino in borsa; per temprar il tossico dell'invidia ch'hanno verso pecuniosi, biasmano l'oro, argento e possessori di quello. Poi quando mi accorgo, ecco che tutti questi vanno come cagnoli per le tavole de ricchi, veramente cani che non sanno con altro che col baiare acquistars' il pane.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Il danaio contiene tutte l'altre quattro: a chi manca il danaio, non solo mancano pietre, erbe e parole, ma l'aria, la terra, l'acqua, il fuoco e la vita istessa.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "L'uomo, senza l'argento ed oro, è come uccello senza piume, ché chi lo vuol prendere, sel prende, chi sel vuol mangiar, sel mangia.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Onore non è altro che una stima, una riputazione; però sta sempre intatto l'onore, quando la stima e riputazione persevera la medesima. Onore è la buona opinione che altri abbiano di noi: mentre persevera questa, persevera l'onore. E non è quel che noi siamo e quel [che] noi facciamo, che ne rendi onorati o disonorati, ma sì ben quel che altri stimano, e pensano di noi.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "È forza che gli doni e grazie sien divisi, a fin che l'uno abbi bisogno dell'altro, e, per conseguenza, l'uno ami l'altro. A chi è concesso il meritare, sii negato l'avere; a chi è concesso l'avere, sii negato il meritare.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "La poesia non nasce da le regole, se non per leggerissimo accidente; ma le regole derivano da le poesie: e però tanti son geni e specie di vere regole, quanti son geni e specie di veri poeti.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "L'amor fa dovenir li vecchi pazzi, e gli giovani savii.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "In viva morte morta vita vivo!", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "L'eroico ingegno si contenta più tosto di cascar o mancar degnamente e nell'alte imprese, dove mostre la dignità del suo ingegno, che riuscir a perfezione in cose men nobili e basse.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Certo che meglio è una degna ed eroica morte, che un indegno e vil trionfo.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "non è cosa naturale né conveniente che l'infinito sia compreso, né esso può donarsi finito: percioché non sarebbe infinito [...].", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ogni amore procede dal vedere: l'amore intelligibile dal vedere intelligibilmente; il sensibile dal vedere sensibilmente.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Non è armonia e concordia dove è unità, dove un essere vuol assorbir tutto l'essere; ma dove è ordine ed analogia di cose diverse; dove ogni cosa serva la sua natura.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Più facilmente determina e condanna chi manco considera.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Se non è vero, è molto ben trovato [...].", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Nessuna potenza et appulso naturale è senza gran raggione.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Accade in color che amano la verità e la bontà [...] s'adirano tanto contro quelli che la vogliono adulterare, guastare, corrompere [...], come son trovati di quelli che si son ridutti sino alla morte, alle pene ed essere ignominiosamente trattati da gli popoli ignoranti e sette volgari.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "A me non è mestieri trascorrere ai confini della terra: basta mi profondi nella mente; basta che sopra a tutto vivamente desideri, per se medesima, la luce divina, e col sommo del mio ingegno mi sforzi di pervenire al cospetto della maestà sua, bramando e sperando di potermi beare nel di lei volto. E, mirabile a dirsi quanto ella sia dappresso, mirabile come ben pronta s'appresenti.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Allora da Trismegisto sarà detto grande miracolo l'uomo che si muta in dio quasi fosse un dio egli stesso; che cerca di essere il tutto come dio è in tutto; che aspira all'oggetto illimitato (tuttavia dovunque da circoscrivere), come illimitato è dio, immenso, dovunque totalmente.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Allora io, rivoltomi da quella parte con i miei limpidi occhi, contemplando quella figura informe e percorrendo con lo sguardo il suo aspetto, nient'altro che un ammasso nerastro di terra, dissi: quello con il dorso prominente, quello con la schiena curva e dentellata, che raggiunge e fende il cielo? Tanto distante di qui, brutto, coperto di fumo, non produce alcun frutto, né pomi, né uva, né dolci fichi: è privo di alberi e di orti, oscuro, tetro, triste, truce, vile, avaro. Ma tu, sorridendo: eppure è mio fratello e mi ama, e vuole bene anche a te. Osservalo bene, dunque, e non disprezzare le sue blandizie. So che non farà niente che ti sia molesto, e se non vorrai rimanerci ritornerai.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Come è possibile che l'universo sia infinito?", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Come è possibile che l'universo sia finito?", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Che dilatazione è questa?", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Che margine è questa?", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Se io, illustrissimo Cavalliero, contrattasse l'aratro, pascesse un gregge, coltivasse un orto, rassettasse un vestimento, nessuno mi guardarebbe, pochi m'osservarebono, da rari sarei ripreso e facilmente potrei piacere a tutti. Ma per essere delineatore del campo de la natura, sollecito circa la pastura de l'alma, vago de la coltura de l'ingegno e dedalo circa gli abiti de l'intelletto, ecco che chi adocchiato me minaccia, chi osservato m'assale, chi giunto mi morde, chi compreso mi vora; non è uno, non son pochi, son molti, son quasi tutti.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ottavo, da quel che nessun senso nega l'infinito, atteso che non lo possiamo negare per questo, che non lo comprendiamo col senso; ma da quel, che il senso viene compreso da quello e la raggione viene a confirmarlo lo doviamo ponere.", Author = "Giordano Bruno" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giordano_Bruno", Text = "Ecco la raggion della mutazion vicissitudinale del tutto, per cui cosa non è di male da cui non s'esca, cosa non è di buono a cui non s'incorra, mentre per l'infinito campo, per la perpetua mutazione, tutta la sustanza persevera medesima ed una. [...] e verremo certamente piú grandi che que' dei che il cieco volgo adora, perché dovenerremo veri contemplatori dell'istoria de la natura, la quale è scritta in noi medesimi, e regolati executori delle divine leggi, che nel centro del nostro core son inscolpite.", Author = "Giordano Bruno" },
        };
    }
}