using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class GiovanniBoccaccio
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Giovine donna è mobile, e vogliosa | È negli amanti molti, e sua bellezza | Estima più ch'allo specchio, e pomposa | Ha vanagloria di sua giovinezza; | La qual quanto piacevole e vezzosa | È più, cotanto più seco l'apprezza: | Virtù non sente, né conoscimento, | Volubil sempre come foglia al vento.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Le ricchezze dipingono l'uomo, e con i loro colori cuoprono e nascondono non solamente i difetti del corpo, ma ancora quelli dell'anima.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Umana cosa è aver compassione agli afflitti; e come che a ciascuna persona stea bene, a coloro è massimamente richiesto li quali già hanno di conforto avuto mestiere, e hannol trovato in alcuni: fra' quali, se alcuno mai n'ebbe bisogno, o gli fu caro, o già ne ricevette piacere, io son uno di quegli.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "E essa che con otto uomini forse diecemilia volte giaciuta era, allato a lui si coricò per pulcella, e fecegliele credere che così fosse; e reina con lui lietamente poi più tempo visse.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "E perciò si disse: «Bocca basciata non perde ventura, anzi rinnuova, come fa la luna.»", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "E abbi questo per certo, che colei sola è casta, la quale o non fu mai da alcuno pregata, o se pregò, non fu esaudita.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "È [...] meglio fare e pentere, che starsi e pentersi.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Fate quello che noi diciamo e non quello che noi facciamo.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "sola la miseria è senza invidia nelle cose presenti.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Amor può troppo più che né voi né io possiamo.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Alcuni, al mio giudicio, valorose donne, sono li quali più che l'altre genti si credon sapere, e sanno meno: e per questo non solamente a' consigli degli uomini, ma ancora contra la natura delle cose presummono d'opporre il senno loro; della quale presunzione già grandissimi mali sono avvenuti ed alcun bene non se ne vide già mai.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "le leggi deono essere comuni e fatte con consentimento di coloro a cui toccano.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Meritamente una delle luci della fiorentina gloria dirsi puote.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Amor, s'i' posso uscir de' tuoi artigli, | appena creder posso | che alcun altro uncin più mai mi pigli.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "E così, a modo del villan matto, dopo danno fe' patto.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Gli ignoranti dall'esteriorità giudicano l'interiorità.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Suole a' miseri crescere di dolersi vaghezza, quando di sé discernono o sentono compassione in alcuno. Adunque, acciò che in me, volonterosa più che altra a dolermi, di ciò per lunga usanza non menomi la cagione, ma s'avanzi, mi piace, o nobili donne, ne' cuori delle quali amore più che nel mio forse felicemente dimora, narrando i casi miei, di farvi, s'io posso, pietose.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Né m'è cura perché il mio parlare agli uomini non pervenga, anzi, in quanto io possa, del tutto il niego loro, però che sì miseramente in me l'acerbità d'alcuno si discuopre, che gli altri simili imaginando, piuttosto schernevole riso che pietose lagrime ne vedrei.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Né credo che piú nobile o ricca cosa fosse a riguardare le nuore di Priamo con l'altre frigie donne, qualora piú ornate davanti al suocero loro a festeggiare s'adunavano, che sono in piú luoghi della nostra città le nostre cittadine a vedere; le quali poi che alli teatri in grandissima quantitá ragunate si veggono, ciascuna quanto il suo potere si stende dimostrandosi bella, non dubito che qualunque forestiere intendente sopravvenisse, considerate le contenenze altiere, li costumi notabili, gli ornamenti piuttosto reali che convenevoli ad altre donne, non giudicasse noi non donne moderne, ma di quelle antiche magnifiche essere al mondo tornate: quella per alterezza, dicendo, Semiramis somigliare; quell'altra, agli ornamenti guardando, Cleopatras si crederebbe; l'altra, considerata la sua vaghezza, sarebbe creduta Elena; e alcuna, gli atti suoi bene mirando, in niente si direbbe dissimigliare a Didone.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Perché andrò io somigliandole tutte? Ciascuna per se medesima pare una cosa piena di divina maestà, non che d'umana.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Mancate già tanto le forze del valoroso popolo anticamente disceso del troiano Enea, che quasi al niente venute erano per lo maraviglioso valore di Giunone, la quale la morte della pattovita Didone cartaginese non avea voluta inulta dimenticare e all'altre offese porre non debita dimenticanza, faccendo degli antichi peccati de' padri sostenere a' figliuoli aspra gravezza, possedendo la loro città, la cui virtù già l'universe nazioni si sottomise, sentì che quasi nelle streme parti dello ausonico corno ancora un picciolo ramo della ingrata progenie era rimaso, il quale s'ingegnava di rinverdire le già seccate radici del suo pedale.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Donna del cielo, e non m' avere a sdegno, | perch'io sia di peccati grave e brutto. | io spero in te, e 'n te sempre ho sperato: | prega per me, ed esser mi fa' degno | Di veder teco il tuo beato frutto.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Non spero mai di tal noia guarire, | si d' ogni parte circondato m' ave: | ben so però che Dio mi può aiutare'.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Poco senno ha chi crede la fortuna | o con preghi o con lacrime piegare, | e molto men chi crede lei fermare | con senno con ingegno o arte alcuna.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Solone, il cui petto uno umano tempio di divina sapienzia fu reputato, e le cui sacratissime leggi sono ancora alli presenti uomini chiara testimonianza dell'antica giustizia, era, secondo che dicono alcuni, spesse volte usato di dire ogni republica, sì come noi, andare e stare sopra due piedi; de' quali, con matura gravità, affermava essere il destro il non lasciare alcuno difetto commesso impunito, e il sinistro ogni ben fatto remunerare; aggiugnendo che, qualunque delle due cose già dette per vizio o per nigligenzia si sottraeva, o meno che bene si servava, senza niuno dubbio quella republica, che 'l faceva, convenire andare sciancata: e se per isciagura si peccasse in amendue, quasi certissimo avea, quella non potere stare in alcun modo.", Author = "Giovanni Boccaccio" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giovanni_Boccaccio", Text = "Qualunque persona, tacendo, i benefìci ricevuti nasconde senza aver di ciò cagione convenevole, secondo il mio giudicio assai manifestamente dimostra sé essere ingrato e mal conoscente di quelli. Oh cosa iniqua e a Dio dispiacevole e gravissima a' discreti uomini, il cui malvagio fuoco il fonte secca della pietà!", Author = "Giovanni Boccaccio" },
        };
    }
}