using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class GiuseppeTomasidiLampedusa
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Io sono una persona che sta molto sola; delle mie sedici ore di veglia quotidiane dieci almeno sono passate in solitudine.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Essa non scrisse che pochi versi, brevi liriche aspre, ferite, alla cui malia non si sfugge.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "E un romanzo. Wuthering Heights, un romanzo come non ne sono mai stati scritti prima, come non saranno mai più scritti dopo.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il romanzo romantico, se mi si consente il bisticcio, ha qui raggiunto il proprio zenith.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Raccontami della nostra isola; è una bella terra benché popolata da somari.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Parlammo dell'incanto di certe notti estive in vista del golfo di Castellammare, quando le stelle si specchiano nel mare che dorme e lo spirito di chi è coricato riverso tra i lentischi si perde nel vortice del cielo mentre il corpo, teso e all'erta, teme l'avvicinarsi dei demoni.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il suo volto triangolare assunse una inaspettata espressione virile.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Se vogliamo che tutto rimanga come è, bisogna che tutto cambi.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il paesaggio ostentava tutte le proprie bellezze.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Sotto il lievito del forte sole ogni cosa sembrava priva di peso.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Nella rada le navi straniere all'ancora, inviate in previsione di torbidi, non riuscivano ad immettere un senso di timore nella calma maestosa.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il sole violento e sfacciato, il sole narcotizzante anche, che annullava le volontà singole e manteneva ogni cosa in una immobilità servile, cullata in sogni violenti, in violenze che partecipavano all'arbitrarietà dei sogni.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Nelle persone del carattere e della classe di don Fabrizio la facoltà di essere divertiti costituisce i quattro quinti dell'affetto.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "L'amore. Certo, l'amore.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Finché c'è morte c'è speranza.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Nel termine \"campagna\" è implicito un senso di terra trasformata dal lavoro; la boscaglia invece, aggrappata alle pendici di un colle, si trovava nell'identico stato di intrico aromatico nel quale la avevano trovata Fenici, Dori e Ioni quando sbarcavano in Sicilia, quest'America dell'antichità.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "In Sicilia non importa far male o far bene: il peccato che noi siciliani non perdoniamo mai è semplicemente quello di 'fare'.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Siamo vecchi, Chevalley, vecchissimi.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Noi siamo dei bianchi quanto lo è lei Chevalley, e quanto la regina d'Inghilterra; eppure da duemilacinquecento anni siamo colonia.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il sonno, caro Chevalley, il sonno è ciò che i Siciliani vogliono, ed essi odieranno sempre chi li vorrà svegliare, sia pure per portar loro i piú bei regali.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Appartengo a una generazione disgraziata, a cavallo fra i vecchi tempi ed i nuovi, e che si trova a disagio in tutti e due.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Cosí rispondo anche a lei, caro Chevalley: i Siciliani non vorranno mai migliorare per la semplice ragione che credono di essere perfetti; la loro vanità è più forte della loro miseria.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Noi fummo i Gattopardi, i Leoni: chi ci sostituirà saranno gli sciacalletti, le iene; e tutti quanti, gattopardi, sciacalli e pecore, continueremo a crederci il sale della terra.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Essi offrivano lo spettacolo patetico più di ogni altro, quello di due giovanissimi innamorati che ballano insieme, ciechi ai difetti reciproci, sordi agli ammonimenti del destino, illusi che tutto il cammino della vita sarà liscio come il pavimento del salone.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Come era possibile infierire contro chi, se ne è sicuri, dovrà morire?", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Non era lecito odiare altro che l'eternità.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "E se in lui, vecchio, il fragore della vita in fuga era tanto potente, quale mai doveva essere stato il tumulto di quei serbatoi ancora colmi che si svuotavano in un attimo da quei poveri corpi giovani?", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Macinava \"Tu che a Dio spiegasti l'ale\".", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Quel che rimaneva di don Fabrizio pensò a quanto fiele venisse in quel momento mescolato a tante agonie, in Italia, da queste musiche meccaniche.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il mio sicilianissimo amor proprio era umiliato: ero stato fatto fesso; e decisi di abbandonare per qualche tempo il mondo e le sue pompe.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Se la Sicilia è ancora come ai tempi miei, immagino che non vi succede mai niente di buono, come da tremila anni.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Confessai che ero proprio un Corbèra di Salina, anzi il solo esemplare superstite di questa famiglia: tutti i fasti, tutti i peccati, tutti i canoni inesatti, tutti i pesi non pagati, tutte le Gattoparderie insomma erano concentrate in me solo.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Pensa a sposarti presto, Corbèra, dato che voialtri non avete trovato nulla di meglio, per sopravvivere, che il disperdere la vostra semente nei posti più strani.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Gli Dei vi hanno soggiornato, forse negli Agosti inesauribili vi soggiornano ancora.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Il mare: il mare di Sicilia è il più colorito, il più aromatico di quanti ne abbia visti; sarà la sola cosa che non riuscirete a guastare, fuori delle città, s'intende.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "I dolci, Corbèra, debbono essere dolci e basta.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Come Odisseo mi turerò le orecchie per non sentire le fandonie di quei minorati.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Sai, io, in fondo, ti voglio bene: la tua ingenuità mi commuove, le tue scoperte macchinazioni vitali mi divertono; e poi mi sembra di aver capito che tu, come capita ad alcuni siciliani della specie migliore, sei riuscito a compiere la sintesi di sensi e di ragione.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "La costa è selvaggia, è vero, senatore?", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "Completamente deserta, non si vede neppure una casa; il mare è del colore dei pavoni; e proprio di fronte, al di là di queste onde cangianti, sale l'Etna; da nessun altro posto è bello come da lì, calmo, possente, davvero divino.", Author = "Giuseppe Tomasi di Lampedusa" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Giuseppe_Tomasi_di_Lampedusa", Text = "È uno di quei luoghi nei quali si vede un aspetto eterno di quell'isola che tanto scioccamente ha volto le spalle alla sua vocazione che era quella di servir da pascolo per gli armenti del sole.", Author = "Giuseppe Tomasi di Lampedusa" },
        };
    }
}