using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class LeonardoSciascia
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "A pensarci bene, sono poi questi strumenti (l'ironia e il gusto) che impediscono lo scatto verso la grandezza. Un grande artista, un grande scrittore, non ha ironia e non ha gusto; e così anche i grandi momenti della letteratura, dell'arte, sono quelli che mancano di gusto e non sono governati dall'ironia.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Arrivandovi da Gela, da Caltanissetta, da Palermo, Vittoria è come un paese di frontiera: ne ha l'animazione, la mescolanza, l'ambiguità, la contraddizione. Era l'argine contro cui si spegnevano, non senza qualche impennata, le ondate mafiose.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Curiosamente, coi miei pensieri mi pare di stare a fare la punta a una matita: sempre più sottile, sempre più acuta, ma che non serve...", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Ci sono uomini che in determinate epoche arrivano alla perfezione, sciogliendosi dall'ambiente in cui vivono e dalle cose del loro tempo, assumendo coscienza della fine e salvandosene nel distacco, nella superiorità, nell'autosufficienza.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Continuo ad essere convinto che la Sicilia offre la rappresentazione di tanti problemi, di tante contraddizioni, non solo italiani ma anche europei, al punto da poter costituire la metafora del mondo odierno.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Cosa rispondere, se non che il siciliano è il prodotto della sua storia? È colpa sua se non ha mai davvero deciso da solo, se sono gli altri che hanno sempre agito per lui, in sua vece e luogo, romani, bizantini, piemontesi?", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Dopo I Promessi sposi, il più grande romanzo che conti la letteratura italiana.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "E dunque la parola \"astrologare\", \"strologare\", può avere il senso proprio di scrutare e studiare gli astri, di indovinarne le leggi e quello, più abusato e comune, di indovinare negli astri – come in un sogno immenso – il destino degli uomini.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "La difficoltà, per Guttuso, per noi, per ogni uomo che è nato in quest'isola, di vivere dopo aver fatto, dopo avere accumulato quadri o libri o denaro; la difficoltà a resistere, a non soccombere «sotto il gruzzolo» della ricchezza o della gloria o soltanto e semplicemente delle cose fatte, delle cose in cui abbiamo messo e mettiamo la nostra passione.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Ho detto, e ribadisco, dell'immediatezza con cui l'opera di Pirandello, per il luogo ed il tempo in cui mi sono trovato a nascere e a vivere, si dispiegò in tutta la sua verità e profondità e sofferenza.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Pirandello ha operato per me una specie di catalizzazione, di precipitazione: la realtà mi si è fatta più reale, la verità più vera.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "I siciliani [...] sono stati del tutto impermeabili alle dominazioni straniere, [...] un'autentica identità sicula è riuscita a conservarsi attraverso i secoli.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Il cinema si interessa della Sicilia perché la Sicilia è cinema.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Il cretino di sinistra ha una spiccata tendenza verso tutto ciò che è difficile. Crede che la difficoltà sia profondità.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Il più bell'esemplare di fascista in cui ci si possa oggi imbattere è quello del sedicente antifascista unicamente dedito a dare del fascista a chi fascista non è.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Il più grande difetto della società italiana è quello di essere senza memoria.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "L'aspetto peggiore della morte non è tanto il non esserci quanto il fatto che altri daranno una interpretazione delle tue parole e della tua opera.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "La contraddizione definisce Palermo. Pena antica e dolore nuovo, le pietre dei falansteri impastate di sangue ma anche di sudore onesto.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "La Mafia che distribuisce equamente lavoro e morte, soperchierìa e protezione.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "La poetica è per entrambi quella di «semplificare le umane passioni»; ma quella di Verga prende avvio da un ritorno, quella di Guttuso da una fuga. La differenza non è trascurabile.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "La sicurezza del potere si fonda sull'insicurezza dei cittadini.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Mi ripugna quando mi sento dire che sono un garantista. Io non sono un garantista: sono uno che crede nel diritto, che crede nella giustizia.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Nessuna crisi può segnare il punto del cedimento per un uomo, per un artista, il cui elemento di vita è appunto la crisi. Guttuso è sempre in crisi: sicché nessuna crisi può coglierlo con insidia o alla sprovvista.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Non c'è nulla di più falso che il proclama di Mussolini secondo cui la Sicilia era fascista fino al midollo.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Non di solo barocco è fatta Palermo. C'è anche una città modernista che tra la fine dell'Ottocento e l'inizio del Novecento scelse l'art-nouveau per realizzare i teatri, le ville e i palazzi di una borghesia che voleva sentirsi all'altezza della vecchia aristocrazia cittadina.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Per un artista vero – qual è per esempio Guttuso – il \"realismo socialista\" non esiste. Guttuso è un grande pittore più quando fa I tetti di Sicilia che quando dipinge i Funerali di Togliatti.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Poiché nulla di sé e del mondo sa la generalità degli uomini, se la letteratura non glielo apprende.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Dunque: al vescovo vanno a riferire che in un paese c'è un prete che non solo tiene una perpetua di età molto al di sotto, come dice Manzoni, della sinodale; ma che se la corica a lato, nello stesso letto.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Che un delitto si offra agli inquirenti come un quadro i cui elementi materiali e, per così dire, stilistici consentano, se sottilmente reperiti e analizzati, una sicura attribuzione, è corollario di tutti quei romanzi polizieschi cui buona parte dell'umanità si abbevera.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Nella realtà le cose stanno però diversamente: e i coefficienti dell'impunità e dell'errore sono alti non perché (o non soltanto, o non sempre) è basso l'intelletto degli inquirenti, ma perché gli elementi che un delitto offre sono di solito assolutamente insufficienti.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "E sa che penso? Che la Chiesa cattolica stia registrando oggi il suo più grande trionfo: l'uomo odia finalmente la donna.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "«Non esce mai di casa?». «Mai, da parecchi anni... Ad un certo punto della mia vita ho fatto dei calcoli precisi: che se io esco di casa per trovare la compagnia di una persona intelligente, di una persona onesta, mi trovo ad affrontare, in media, il rischio di incontrare dodici ladri e sette imbecilli che stanno lì, pronti a comunicarmi le loro opinioni sull'umanità, sul governo, sull'amministrazione municipale, su Moravia... Le pare che valga la pena?».", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "«Che popolo», pensò con un disprezzo venato di gelosia: e che in qualunque posto del mondo, là dove l'orlo di una gonna saliva di qualche centimetro sul ginocchio, nel raggio di trenta metri c'era sicuramente un siciliano, almeno uno, a spiare il fenomeno.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "«Sai come si dice? Tre c sono pericolose: cugini, cognati e compari. Le tresche più gravi si verificano quasi sempre nella parentela e nel comparatico».", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "''Il Globo'', 24 luglio 1982 [...] direi che il dato più probante e preoccupante della corruzione italiana non tanto risieda nel fatto che si rubi nella cosa pubblica e nella privata, quanto nel fatto che si rubi senza l'intelligenza del fare e che persone di assoluta mediocrità si trovino al vertice di pubbliche e private imprese.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "''L'espresso'', 20 febbraio 1983 [...] Non credendo, dunque, di far parte di una categoria, corporazione o sindacato, se qualcuno mi corre dietro chiamandomi \"intellettuale\" non mi volto nemmeno.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "''La Stampa'', 6 agosto 1988 [...] Voglio quel che non c'è mai stato e che evidentemente non c'è; e che continuando si fa meta sempre più lontana. Il che mi fa ancora e sempre apparire come un pessimista: e pare non sia permesso esserlo neppure di fronte al pessimo.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Una sola complicazione: e veniva da Candido. Entrambi, marito e moglie, si tenevano in obbligo, e così li teneva la società in cui vivevano i parenti, gli amici, i preti e gli avvocati, di una terribile finzione: dovevano fingere, l'uno contro l'altra, di volerlo e di non essere lei disposta a cederlo a lui e lui a lei.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "E proprio durante una di queste messe, a Candido avvenne di scoprire, un pensiero dietro l'altro, che la morte è terribile non per il non esserci più ma, al contrario, per l'esserci ancora e in balìa dei mutevoli ricordi, dei mutevoli sentimenti, dei mutevoli pensieri di coloro che restavano.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Essere comunista era insomma, per Candido, un fatto quasi di natura: il capitalismo portava l'uomo alla dissoluzione, alla fine; l'istinto della conservazione, la volontà di sopravvivere, ecco che avevano trovato forma nel comunismo.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Noi siamo quel che facciamo. Le intenzioni, specialmente se buone, e i rimorsi, specialmente se giusti, ognuno, dentro di sé, può giocarseli come vuole, fino alla disintegrazione, alla follia.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Poi, forse, il corpo di Paola aveva ceduto all'anima. All'anima immortale, all'anima sentimentale, all'anima bella: ed ecco che la gioiosa verità del corpo le si era appannata, le si era stravolta; era diventata un bene inferiore.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Tante cose si fanno per il bene degli altri che diventano il male degli altri e il proprio.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Ché a vederle, le cose si semplificano: e noi abbiamo invece bisogno di complicarle, di farne complicate analisi, di trovarne complicate cause, ragioni, giustificazioni.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Sai cos'è la nostra vita? La tua e la mia? Un sogno fatto in Sicilia. Forse stiamo ancora lì e stiamo sognando.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Antonello, dunque: e il suo essere siciliano, come personaggio e come artista; come uomo insomma la cui vita, la cui visione della vita, il cui modo di esprimere nell'arte la vita, sono irreversibilmente condizionati dai luoghi dagli ambienti dalle persone tra cui si trova a nascere e a passare l'infanzia, l'adolescenza.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "I ritratti di Antonello «somigliano»; sono l'idea stessa, l'archè, della somiglianza.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "E questa può essere la più ovvia conclusione su Antonello: che un uomo straordinariamente «oggettivo» si è trovato a vivere e ad esprimere compiutamente, impareggiabilmente, il momento più «oggettivo» che la storia della pittura abbia mai toccato.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Non c'è turista che viaggiando per la Sicilia – minimo che sia il suo interesse alle cose dell'arte – tra Palermo e Messina non si senta obbligato o desideroso di fermarsi a Cefalù: e dopo averne ammirato il Duomo e sostato nella piazza luminosa che lo inquadra, non imbocchi la stradetta di fronte a destra per visitare, fatti pochi passi, il Museo Mandralisca.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Dove sono tante cose – libri, conchiglie e quadri – legati, per testamento del barone Enrico Mandralisca di Pirajno, al Comune di Cefalù: ma soprattutto vi è splendidamente isolato, folgorante, quel ritratto virile che, tra quelli di Antonello da Messina che conosciamo, è forse il più vigoroso e certamente il più misterioso e inquietante.", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "che cosa è la fotografia se non verità momentanea, verità di un momento che contraddice altre verità di altri momenti?", Author = "Leonardo Sciascia" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Leonardo_Sciascia", Text = "Un libro, dunque, è come riscritto in ogni epoca in cui lo si legge e ogni volta che lo si legge. E sarebbe allora il rileggere un leggere: ma un leggere inconsapevolmente carico di tutto ciò che tra una lettura e l'altra è passato su quel libro e attraverso quel libro, nella storia umana e dentro di noi.", Author = "Leonardo Sciascia" },
        };
    }
}