using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class LudovicoAriosto
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "chi fa sua vendetta, oltra che offende | chi offeso l'ha, da molti si difende.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Piccola è questa casa, ma sufficiente per me, nessuno vi ha ragioni sopra, è pulita, infine è stata fatta con i miei denari.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Né che poco io vi dia da imputar sono, | che quanto io possa dar, tutto vi dono.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ecco il giudicio uman come spesso erra!", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Oh gran bontà de' cavalieri antiqui!", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Pel bosco Ferraú molto s'avvolse,| e ritrovossi al fine onde si tolse.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Né tempo avendo a pensar altra scusa, | e conoscendo ben che 'l ver gli disse, | restò senza risposta a bocca chiusa", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che chi ne l'acqua sta fin alla gola | ben è ostinato se mercé non grida.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Corro la fresca e matutina rosa | Che tardando stagion perder potria", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ingiustissimo amor, perché sì raro | corrispondenti fai nostri desiri? ... da chi disia il mio amor tu mi richiami, | e chi m'ha in odio vuoi ch'adori ed ami.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Questo disir, ch'a tutti sta nel core, | de' fatti altrui sempre cercar novella...", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ma ne li vizi abominandi e brutti | non pur gli altri adeguò, ma passò tutti.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Perché si de' punir donna o biasmare, | che con uno o più d'uno abbia commesso | quel che l'uom fa con quante n'ha appetito, | e lodato ne va, non che impunito?", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ben s'ode il ragionar, si vede il volto: | Ma dentro il petto mal giudicar puossi", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Oh Dio, che disse e fece, poi che sola | si ritrovò nel suo fidato letto! | percosse il seno, e si stracciò la stola, | e fece all'aureo crin danno e dispetto.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Come aviene a un disperato spesso, | che da lontan brama e disia la morte, | e l'odia poi che se la vede appresso, | tanto gli pare il passo acerbo e forte", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Pareami aver qui tutto il ben raccolto | che fra i mortali in piú parti si smembra, | a chi piú et a chi meno e a nessun molto", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Donna sì laida, che la terra tutta | né la più vecchia avea né la più brutta", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ho perduto l'onor, ch'è stato peggio; | che, se ben con effetto io non peccai, | io do però materia ch'ognun dica, | ch'essendo vagabonda, io sia impudica", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Non comincia Fortuna mai per poco, | quando un mortal si piglia a scherno e a gioco", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ben ch'esser donna sia in tutte le bande | danno e sciagura, quivi era pur grande", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Io credea e credo, e creder credo il vero", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "L'amante, per aver quel che desia, | senza guardar che Dio tutto ode e vede, | aviluppa promesse e giuramenti, | che tutti spargon poi per l'aria i venti", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Bene è felice quel, donne mie care, | ch'essere accorto all'altrui spese impare", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che fossi fatto in quarti, arso o impiccato, | brutto ladron, villan, superbo, ingrato", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Natura il fece, e poi ruppe la stampa", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che ben fu il più crudele e il più di quanti | mai furo al mondo ingegni empi e maligni, | ch'imaginò sì abominosi ordigni", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "E spenta ogni pietà, strage nefanda | di quel popul facean per tutti i liti: | fosse iustizia, o fosse crudeltade, | né sesso riguardavano né etade", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Dirò insomma, ch'in lei dal capo al piede, | quant'esser può beltà, tutta si vede", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "A tutti par che quella cosa sia, | che piú ciascun per sé brama e desia", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Fu il vincer sempre mai laudabil cosa | Vincasi o per fortuna o per ingegno", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "O d'ogni vizio fetida sentina, | dormi, Italia imbriaca, e non ti pesa | ch'ora di questa gente, ora di quella | che già serva ti fu, sei fatta ancella?", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che l'uomo il suo destin fugge di raro", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "non è il ribaldo questo, | che si fa laude con l'altrui buone opre? | e la virtú di chi non è ben desto, | con la sua infamia e col suo obbrobrio copre?", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che sarebbe pensier non troppo accorto | perder duo vivi per salvare un morto", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Se, come il viso, si mostrasse il core", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Le donne son venute in eccellenza | di ciascun'arte ove hanno posto cura", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che non è soma da portar sí grave, | come aver donna, quando a noia s'have", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Credo che t'abbia la Natura e Dio | produtto, o scelerato sesso, al mondo | per una soma, per un grave fio | de l'uom, che senza te saria giocondo", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "A donna non si fa maggior dispetto, | che quando o vecchia o brutta le vien detto", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Il consiglio del mal va raro invano", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Amor, con che miracolo lo fai, | che 'n fuoco li tenghi, e nol consumi mai?", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Senza il pane discerner da le giande, | dal digiuno e da l'impeto cacciato, | le mani e il dente lasciò andar di botto | in quel che trovò prima, o crudo o cotto", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "L'animo è pronto, ma il potere è zoppo", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Di più direi; ma di men dir bisogna", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Io sua non son, né d'altri son che mia: | dunque me tolga a me chi mi desia", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Gli è teco cortesia l'esser villano", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Non siate però tumide e fastose, | donne, per dir che l'uom sia vostro figlio; | che de le spine ancor nascon le rose, | e d'una fetida erba nasce il giglio", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Mettendolo Turpino, anch'io l'ho messo", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Se piú che crini avesse occhi il marito, | non potria far che non fosse tradito.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Non conosce la pace e non l'estima | chi provato non ha la guerra prima.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Vide gran copia di panie con visco, | ch'erano, o donne, le bellezze vostre", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "voglion tutti gli ordini e le leggi, | Che chi dà morte altrui, debb'esser morto.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Che s'abbia a ritrovar con numer pare | Di cavallieri armati in Lipadusa. | Una isoletta è questa, che dal mare | Medesmo che li cinge, è circonfusa.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Temerità per certo e pazzia vera | è la tua, e di qualunque che si pose | a consigliar mai cosa buona o ria, | ove chiamato a consigliar non sia", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "L'incarco de le corna, e lo più lieve | Ch'al mondo sia, se ben l'huom tanto inſama | Lo vede quasi tutta l'altra gente | E chi l'ha in capo mai non se lo sente", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ove femine son, son liti e risse", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Bestemmiando fuggì l'alma sdegnosa | Che fu sì altiera al mondo e sì orgogliosa", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "E levar questa donna anco ti voglio; ché sarebbe a lasciartela gran fallo.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "E quel che non si sa non si de' dire, | e tanto men, quando altri n'ha a patire", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Ma 'l popolo facea, come i più fanno, | ch'ubbidiscon più a quei che più in odio hanno.", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Natura il fece, e poi ruppe la stampa", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "O città bene avventurosa... | ...la gloria tua salirà tanto | ch'avrai di tutta Italia il pregio e 'l vanto", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Or che s'aspetta? Soccorrer qui, non lacrimare accade", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Pazzo chi al suo signor contradir vole, | se ben dicesse c'ha veduto il giorno | pieno di stelle e a mezzanotte il sole", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Più tosto che arricchir, voglio quïete", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "più tosto ch'esser servo | torrò la povertade in pazïenza", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Non si adatta una sella o un basto solo | ad ogni dosso; ad un non par che l'abbia, | all'altro stringe e preme e gli dà duolo", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Degli uomini son varii li appetiti: | a chi piace la chierca, a chi la spada, | a chi la patria, a chi li strani liti", Author = "Ludovico Ariosto" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Ludovico_Ariosto", Text = "Chi vuole andare a torno, a torno vada: | vegga Inghelterra, Ongheria, Francia e Spagna; | a me piace abitar la mia contrada", Author = "Ludovico Ariosto" },
        };
    }
}