using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class LuigiCapuana
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "È il cuore della città. La gente vi s'affolla da tutte le parti, continuamente, secondo le circostanze e le ore della giornata, e si riversa dai suoi quattro sbocchi, stavo per dire nell'aorta e nelle arterie del grande organismo tanto la sua rassomiglianza colle funzioni del cuore è evidente. Tutte le pulsazioni della vita cittadina si ripercuotono qui. Quando pare che anche qui ogni movimento sia cessato, dai grand'occhi di cristallo del pavimento può scorgersi che nei suoi sotterranei ferve sempre il lavoro, quasi che in questo centro vitale l'attività non possa mai addormentarsi e prosegua senza coscienza, proprio come nell'organismo vivente che abbandonasi al sonno. Gli ultimi urli degli scapati che tornano a casa con l'alba si confondono, sotto la grande vôlta di cristallo, col rumore dei passi dei primi operai che s'avviano al lavoro, o dei contadini che l'attraversano per andare al mercato coi nasi all'aria e colla bocca aperta, sbattendo sul pavimento di marmo le enormi bullette delle loro scarpe o i loro zoccoli poderosi.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Ebbi rimorsi di non essermi sentito Siciliano abbastanza; di avere esagerato anch'io i difetti del carattere isolano, e di avere apprezzato equamente pregi e particolari ogni volta che, interrogato, avevo dovuto ragionare; ebbi rimorso di non aver difeso clamorosamente, e senza sciocche gonfiezze di amor provinciale, la Sicilia, quando l'avevo sentita mal giudicata o calunniata... cosa non rara purtroppo!", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Era un meraviglioso giornalista. I suoi articoli non annoiavano mai, interessavano sempre.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "La signorina Deledda fa benissimo di non uscire dalla sua Sardegna e di continuare a lavorare in questa preziosa miniera, dove ha già trovato un forte elemento di originalità. I suoi personaggi non possono esser confusi con personaggi di altre regioni; i suoi paesaggi non sono vuote generalità decorative. Il lettore, chiuso il libro, conserva vivo il ricordo di quelle figure caratteristiche, di quei paesaggi grandiosi; e le impressioni sono cosi forti, che sembrano quasi immediate, e non di seconda mano, a traverso un'opera d'arte.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Quando l'artista riesce a darmi il personaggio vivente davvero, non so chiedergli altro e lo ringrazio. Mi pare ch'egli m'abbia dato tutto quello che dovea. Pel solo fatto di esser vivente, quel personaggio è bello, è morale; e, se opera bene e se predica meglio, non nuoce: torno a ringraziar l'artista del di più. E al pari del personaggio amo viva l'azione. L'azione allo stesso modo, pel solo fatto di esser vivente è bella, è morale; non bisogna pretendere l'assurdo. Sotto la veste dell'artista, convien rammentarselo, c'è sempre più o meno un pensatore. Se questi fa capolino un po' più dell'altro, tanto meglio; è quel che ci vuole a questi benedetti lumi di luna. Ma se si dovesse scegliere ad ogni patto, o l'uno o l'altro, io non esiterei, trattandosi di teatro, a sceglier l'artista.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Questa benedetta o maledetta riflessione moderna, questa smania di positivismo, di studi, di osservazioni, di collezioni di fatti, noi non possiamo cavarcela di dosso.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Quando il denaro non serve a far godere la vita, è cosa senza valore.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Il paradiso è quaggiù, mentre respiriamo e viviamo. Dopo, si diventa un pugno di cenere e tutto è finito", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "L'anima è il corpo che funziona; morto il corpo, morta l'anima.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "«Perché Dio ci ha creati?» «Non ci ha creati nessuno! La Natura ha prodotto un primo animale e da esso, per trasformazioni e perfezionamenti, siamo venuti fuori noi. Siamo figli di scimmia, animali come gli altri animali.»", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "«I preti cattolici hanno preso Dio agli ebrei e hanno inventato Gesù Cristo.»", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Quando un Roccaverdina prende un drizzone, è capace di tutto, nel bene e nel male! ... Anche a costo di far scorazzare il collo a chi non c'entra.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Il Michelet è uno dei pochi francesi che abbiano amato l'Italia con affetto profondo. Potremmo anzi dire che ci appartiene.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Il Michelet è di quegli scrittori estremamente simpatici, dei quali si parla e si sente parlar volentieri. Più che un pensatore è un uomo di cuore; più che uno storico uno scienziato, è un mistico, un poeta, un allucinato [...], ma anche un divinatore; uno di quegli uomini insomma che ritengono meno degli altri le caratteristiche più spiccate della propria razza e parlano un linguaggio che qualche volta può parere od essere strano, ma che è sentito da tutti, perfino quando non viene ben compreso da tutti.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Magro, debole, di piccola statura, con una testa sviluppatissima, dove contrastavano la bianchezza della sua precoce canizie e il vivo lampo degli occhi, il suo corpo pareva fatto a posta per lasciare allo spirito piena libertà d'azione. Infatti la sua vita fu tutta intera uno studio. Egli lavorava assiduamente dallo sei del mattino fino al mezzogiorno. Consacrava il dopopranzo a qualche passeggiata e alle relazioni amichevoli: andava a letta alle dieci. D'abitudini regolatissime, soffriva a veder mutati, anche soltanto di posto, gli oggetti che lo circondavano nella sua stanza da lavoro. Il panno del tavolino da scrivere, il portafogli di cartone non poterono venir rinnovati benché sudici e laceri.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Teofilo Gautier, pei francesi, è rimasto fino all'ultimo l'uomo ''dal gilè rosso'' del 25 febbraio 1830 (una data indimenticabile nella storia dell'arte). Non se ne sapeva dar pace. – L'indossai una sola volta e l'ho portato per tutta la vita – soleva dire con tristezza. Ormai il gilè rosso appartiene alla leggenda. Né vale il sapere che non era rosso, ma color di rosa; che non era un gilè, ma un ''pourpoint''. Il Gautier insisteva sul colore. Il rosso avrebbe avuto un significato repubblicano e fra i romantici di repubblicani ce n'era appena un solo, Pietro Borel. Il resto erano ''medioevisti'', del partito dei ''castelli merlati'', e nient'altro: ecco perché il ''pourpoint'' era color di rosa... Ma già è inutile: il Gautier del 1830 non sarà rappresentato altrimenti.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "il lavoro giornalistico l'oppresse fino all'estremo momento; lavoro duro, ingrato, perfettamente contrario al suo carattere d'artista pieno di capricci e di paradossi. Negli ultimi anni che il disgusto del suo mestiere veniva accresciuto da diverse circostanze, egli non desiderava altro che una piccola rendita fissa per andare a nascondersi in un paesetto di riviera, nel Mediterraneo, e lì ''estetizzare'' sulla riva coi piedi lambiti dall'onda marina, come Socrate e Platone. – Un muricciuolo per fumarvi la mia pipa al sole, diceva talvolta colla sua forma plastica, e la minestra due volte la settimana... ecco tutto quel che io desidero.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Il Fullone del popolo è un cavapietre, buontempone, arguto, malizioso, sarcastico, sguaiato, osceno, religioso, accattabrighe e, per giunta, ignorante. Vissuto da capo scarico, fa la fine d'un anacoreta. Il Fullone che appare dai numerosi volumi messi a stampa è un uomo evidentemente assai colto, intinto di scolastica e di teologia, amico di moltissimi dotti contemporanei, dai quali riceve distici latini, epigrammi, sonetti in lode dei suoi poemi; un uomo che sa a menadito la storia e la mitologia, che imita bene i classici, che maneggia con arditezza lo stile, ora tenendolo in un tono mediano tra lo artifizio e la naturalezza, ora abbandonandolo a tutte le capestrerie delle metafore, dei concettini, dello iperboli, come conveniva per meritarsi l'onore d'accademico Racceso.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Egli entrava nella sala dell'Accademia di belle arti per le sue lezioni di estetica con un'aria severa, quasi solenne, tenendo in mano il quaderno della lezione da leggere arrotolato e legato con un nastrino di seta a colore. La sua declamazione non era teatrale, ma faceva scorgere una grande preoccupazione dell'effetto, massime verso la fine. Il testo della lezione aveva anch'esso una ''stretta finale'' per strappare l'applauso. Insomma l'incesso, la declamazione, il contenuto dello scritto mostravano qualche cosa d'affettato, di ricercato, di lezioso che non lasciava nell'animo una buona impressione del suo carattere. Per molti che al pari di me lo conobbero soltanto di vista, l'Aleardi non fu altro che un superbioso: lo chiamavamo l'olimpico.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Per ingegno e per costume Ferdinando II delle Due Sicilie era il migliore tra i suoi fratelli. Eppure egli era ignorante, non leggeva mai libro, scriveva con molti errori di ortografia. Egli, come il padre e come l'avo, non credeva virtù in altri, ne beffava il sapere, rideva dell'ingegno, non pregiava che la furbizia; chiunque sapesse leggere e scrivere era suo nemico e lo chiamava ''pennaiuolo''; si circondò degli uomini più ignoranti e bestiali. Educato da bassi servitori di Corte, che i Borboni sogliono tenere come i fedeli amici e consiglieri, egli ne apprese due vizi propri del più feccioso popolazzo: la bugia e la beffa.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Gli opuscoli del Galateo posseggono anch'essi un valore storico, e non solamente allorché versano intorno a memorie storiche propriamente dette, ma più quando senza volerlo apprestano documenti del suo tempo che vincono in pregio cento storie messe insieme.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Il Galateo, fra gli errori d'ogni sorta che sconvolsero l'Italia dal 1450 al 1517, sembra l'espressione dell'ideale, verso cui gl'italiani d'allora dovevano sospirar coll'animo in segreto e in palese. E questo sospiro all'ideale non trasparisce unicamente dai suoi pensieri, ma pur dalla forma con cui li esprime. Aprendo il libro, istintivamente non vien fatto di buttar gli occhi sul testo latino, che giace a piè di pagina. Ma procedendo nella lettura, si subisce una dolce opera d'incanto, o si abbandona la traduzione per vedere le idee sotto l'antica lor veste. Già s'indovina subito che non si ha da fare con uno di quei pedanti latinisti, pazienti cucitori di frasi e di periodi ciceroniani, che inocularono il malanno dell'imitazione alla nostra vergine letteratura. Si comprende che le cose lette nella traduzione devono infondere allo stilo dell'autore quella certa fervida vita, che manca pel solito a coloro che scrivono in una lingua morta; e non ci s'inganna.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Egli non bada all'eleganza della frase o al giro del periodo in discapito delle idee; è purgato, è accurato; ma soprattutto, più che latino, vuol esser lui, il Galateo, un uomo del secolo XV, che pensa, che sente e che ragiona a suo modo, senza affettazione, senz'arte, o almeno colla sola di dir le cose alla buona. Ed è forse per conservar sempre questa sua diletta libertà di maniera, ch'egli si serve quasi costantemente pei suoi opuscoli della forma epistolare, trattino di storia, di morale, di filosofia, di fisica, di cosmografia o di medicina.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "—E la giustizia?—esclamò Lastrucci.—Quale?—replicò Morani.—Di quella del mondo di là, nessuno sa niente; la nostra, l'umana, è cosa talmente rozza, superficiale, barbarica, da non meritar punto di essere chiamata giustizia. Condanna o assolve alla cieca, per fatti esteriori, su testimonianze che affermano soltanto l'azione materiale, quel che meno importa in un delitto. Il vero delitto, lo spirituale, resultato del pensiero e della coscienza, le sfugge quasi sempre; e così essa spessissimo condanna quando dovrebbe assolvere e assolve, pur troppo! quando dovrebbe condannare.", Author = "Luigi Capuana" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Luigi_Capuana", Text = "Abbiamo tante e tante volte ragionato insieme di ''Spiritismo'', tu da credente, con molte riserbe e cautele, attirato più dal misticismo della dottrina spiritica che dal meraviglioso delle ''communicazioni'' o delle ''apparizioni'', io da curioso, da dilettante che ha tentato e provato e non ha perduto la voglia di ritentare e riprovare; ne abbiamo ragionato insieme tante volte, che ora ti dovrà parere naturalissimo il vederti indirizzata in pubblico una lettera colla quale si vuol sottoporre al giudizio delle persone competenti alcuni fatti e alcune ipotesi meritevoli, mi pare, di considerazione e spiegazione.", Author = "Luigi Capuana" },
        };
    }
}