using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class NataliaGinzburg
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Come può rimanere impunito un delitto contro la persona? Come può sottrarsi alle forze dell'ordine chi ha commesso uno stupro semplicemente perché la vittima ha deciso di non denunziarlo?", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Io non avrei potuto fare che un mestiere, un mestiere solo: il mestiere che ho scelto, e che faccio, quasi dall'infanzia.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "L'Italia è un paese pronto a piegarsi ai peggiori governi. È un paese dove tutto funziona male, come si sa. È un paese dove regna il disordine, il cinismo, l'incompetenza, la confusione. E tuttavia, per le strade, si sente circolare l'intelligenza, come un vivido sangue. È un'intelligenza che, evidentemente, non serve a nulla.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Se c'è Dio non importa pregarlo, è Dio e capisce da sé cosa bisogna fare.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Il crocifisso è il segno del dolore umano. La corona di spine, i chiodi, evocano le sue sofferenze. La croce, che pensiamo alta in cima al monte, è il segno della solitudine nella morte. Non conosco altri segni che diano con tanta forza il senso del nostro umano destino.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Cristo ha scacciato i mercanti dal Tempio. Se fosse qui oggi, non farebbe che scacciare mercanti.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Per quanto riguarda l'educazione dei figli, penso che si debbano insegnar loro non le piccole virtù, ma le grandi. Non il risparmio, ma la generosità e l'indifferenza al denaro; non la prudenza, ma il coraggio e lo sprezzo del pericolo; non l'astuzia, ma la schiettezza e l'amore alla verità; non la diplomazia, ma l'amore al prossimo e l'abnegazione; non il desiderio del successo, ma il desiderio di essere e di sapere.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "E ci sono poi tutte le cose che si fanno ''per non dover parlare'': alcuni passano le serate addormentati in una sala di proiezioni, con al fianco la donna alla quale, cosi, non sono tenuti a dover parlare; alcuni imparano a giocare a bridge; alcuni fanno l'amore, che si può fare anche senza parole.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Basta una parola, una frase: una di quelle frasi antiche, sentite e ripetute infinite volte nella nostra infanzia. Ci basta dire: \"Non siamo venuti a Bergamo per fare campagna\" o \"De cosa spussa l'acido solfidrico\", per ritrovare ad un tratto i nostri antichi rapporti, e la nostra infanzia e giovinezza, legata indissolubilmente a quelle frasi, a quelle parole.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Il suo parlare correva sul filo d'una ricerca disinteressata, pura e del tutto destituita di scopo. Ma usava far defluire alla casa editrice una parte di ciò che aveva appreso, come chi, cacando per pura necessità di cacare, è tuttavia consapevole di concimare un campo.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Romanzieri e poeti avevano, negli anni del fascismo, digiunato, non essendovi intorno molte parole che fosse consentito usare; e i pochi che ancora avevano usato parole le avevano scelte con ogni cura nel magro patrimonio di briciole che ancora restava.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Ma l'errore comune era sempre credere che tutto si potesse trasformare in poesia e parole. Ne conseguì un disgusto di poesia e parole, così forte che incluse anche la vera poesia e le vere parole, per cui alla fine ognuno tacque, impietrito di noia e di nausea.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Era, il dopoguerra, un tempo in cui tutti pensavano d'essere dei poeti, e tutti pensavano d'essere dei politici; tutti s'immaginavano che si potesse e si dovesse anzi far poesia di tutto, dopo tanti anni in cui era sembrato che il mondo fosse ammutolito e pietrificato e la realtà era stata guardata come di là da un vetro, in una vitrea, cristallina e muta immobilità.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Leone Ginzburg, la sua passione vera era la politica. Tuttavia aveva, oltre a questa vocazione essenziale, altre appassionate vocazioni, la poesia, la filologia e la storia.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "la vecchiaia, che è starsene ripiegati in disparte piangendo lo sfacelo del passato.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Pavese commetteva errori piú gravi dei nostri. Perché i nostri errori erano generati da impulso, imprudenza, stupidità e candore; e invece gli errori di Pavese nascevano dalla prudenza, dall'astuzia, dal calcolo e dall'intelligenza.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Nulla è pericoloso come questa sorta di errori. Possono essere, come lo furono per lui, mortali; perché dalle strade che si sbagliano per astuzia, è difficile ritornare.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "è estinta o si sta estinguendo la stirpe dei padri. Da tempo orfani, noi generiamo degli orfani, essendo stati incapaci di diventare noi stessi dei padri.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "il nostro malcostume ci porta a chiedere all'amicizia, o anche a un semplice sorriso di cortesia, non già il vero ma un nostro immediato vantaggio.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "ogni essere ha la fortuna che il suo spirito chiede.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Essere capiti vuol dire essere presi e accettati per quello che siamo.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "La vecchiaia vorrà dire in noi, essenzialmente, la fine dello stupore. Perderemo la facoltà sia di stupirci, sia di stupire gli altri. Noi non ci meraviglieremo più di niente, avendo passato la nostra vita a meravigliarci di tutto; e gli altri non si meraviglieranno di noi, sia perché ci hanno già visto fare e dire stranezze, sia perché non guarderanno più dalla nostra parte.", Author = "Natalia Ginzburg" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Natalia_Ginzburg", Text = "Ti auguro ogni bene possibile, e spero che tu sia felice, ammesso che la felicità esista. Io non credo che esista, ma gli altri lo credono, e non è detto che non abbiano ragione gli altri.", Author = "Natalia Ginzburg" },
        };
    }
}