using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class SalvatoreQuasimodo
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "La rassegnazione alla solitudine, opposta al dolore lucreziano, avvicina a noi Virgilio più degli altri poeti latini dell'antichità classica.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Avidamente allargo la mia mano: | dammi dolore cibo cotidiano.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Desiderio delle tue mani chiare | nella penombra della fiamma: | sapevano di rovere e di rose; | di morte. Antico inverno.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "E quel gettarmi alla terra, | quel gridare alto il nome del silenzio, | era dolcezza di sentirmi vivo.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Fatica d'amore, tristezza, | tu chiami una vita | che dentro, profonda, ha nomi | di cieli e giardini. | E fosse mia carne | che dono di male trasforma.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Mi trovi deserto, Signore, | nel tuo giorno, | serrato ad ogni luce. | Di te privo spauro, | perduta strada d'amore, | e non m'è grazia | nemmeno trepido cantarmi | che fa secche mie voglie.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Se mi desti t'ascolto, | e ogni pausa è cielo in cui mi perdo, | serenità d'alberi a chiaro della notte.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Si china il giorno | e colgo ombre dai cieli: | che tristezza il mio cuore | di carne!", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "S'udivano stagioni aeree passare, | nudità di mattini, | labili raggi urtarsi.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Tindari, mite ti so | fra larghi colli pensile sull'acque | dell'isole dolci del dio, | oggi m'assali | e ti chini in cuore.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ti rivedo. Parole | avevi chiuse e rapide, | che mettevano cuore | nel peso di una vita | che sapeva di circo.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Un po' di sole, una raggera d'angelo, | e poi la nebbia; e gli alberi, | e noi fatti d'aria al mattino.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ali oscillano in fioco cielo, | labili: il cuore trasmigra | ed io son gerbido, | e i giorni una maceria.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Autunno mansueto, io mi posseggo | e piego alle tue acque a bermi il cielo, | fuga soave d'alberi e d'abissi.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Avara pena, tarda il tuo dono | in questa mia ora | di sospirati abbandoni.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Città d'isola | sommersa nel mio cuore, | ecco discendo nell'antica luce | delle maree, presso sepolcri | in riva d'acque | che una letizia scioglie | d'alberi sognati.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ed è morte | uno spazio nel cuore.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Farsi amore un'altra morte sento | ignota a me, ma più di questa tarda, | che mi spinge sovente alle sue forme.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "In te mi getto: un fresco | di navate posa nel cuore; | passi nudi d'angeli | vi s'ascoltano, al buio.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Io tento una vita: | ognuno si scalza e vacilla | in ricerca.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Lievita la mia vita di caduto, | esilio morituro.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Non so odiarti: così lieve | il mio cuore d'uragano.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Non una dolcezza mi matura, | e fu di pena deriva | ad ogni giorno | il tempo che rinnova | a fiato d'aspre resine.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Odore buono del cielo | sull'erbe, | pioggia di prima sera.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Un sole rompe gonfio nel sonno | e urlano alberi; | avventurosa aurora | in cui disancorata navighi, | e le stagioni marine | dolci fermentano rive nasciture.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Seguiremo case silenziose, | dove morti stanno ad occhi aperti | e bambini già adulti | nel risata che li attrista, | e fronde battono a vetri taciti | a mezzo delle notti.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Dammi il mio giorno; | ch'io mi cerchi ancora | un volto d'anni sopito | che un cavo d'acque | riporti in trasparenza, | e ch'io pianga amore di me stesso.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ti cammino sul cuore, | ed è un trovarsi d'astri | in arcipelaghi insonni, | notte, fraterni a me | fossile emerso da uno stanco flutto;", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "A te piega il cuore in solitudine, | esilio d'oscuri sensi | in cui trasmuta ed ama | ciò che parve nostro ieri, | e ora è sepolto nella notte.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Alle sponde odo l'acqua colomba, | Ànapo mio, nella memoria geme | al suo cordoglio | uno stormire altissimo.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "I monti a cupo sonno | supini giacciono affranti.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Mansueti animali, | le pupille d'aria, | bevono in sogno.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Nella palude calda confitto al limo, | caro agli insetti, in me dolora | un airone morto.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Per averti ti perdo, | e non mi dolgo: sei bella ancora, | ferma in posa dolce di sonno: | serenità di morte estrema gioia.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Sillabe d'ombre e foglie, | sull'erbe abbandonati | si amano i morti.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Terrena notte, al tuo esiguo fuoco | mi piacqui talvolta, e scesi fra i mortali.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ancora un anno è bruciato, | senza un lamento, senza un grido | levato a vincere d'improvviso un giorno.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Illeso sparì da noi quel giorno | nell'acqua coi velieri capovolti.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Nello spazio dei colli, | tutto inverno, il silenzio | del lume dei velieri: | fredda immagine eterna | navigante! E qui risorge.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Isole che ho abitato | verdi su mari immobili | D'alghe arse, di fossili marini | e spiagge ove corrono in amore | cavalli di luna e di vulcani.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Ancora un verde fiume mi rapina | e concordia d'erbe e pioppi, | ove s'oblia lume di neve morta.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Scende la sera: ancora ci lasciate, | o immagini care della terra, alberi, | animali, povera gente chiusa | dentro i mantelli dei soldati, madri | dal ventre inaridito dalle lacrime.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Giorno dopo giorno: parole maledette e il sangue | e l'oro. Vi riconosco, miei simili, o mostri | della terra. Al vostro morso è caduta la pietà, | e la croce gentile ci ha lasciati.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Invano cerchi tra la polvere, | povera mano, la città è morta.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "La luna rossa, il vento, il tuo colore | di donna del Nord, la distesa di neve... | Il mio cuore è ormai su queste praterie, | in queste acque annuvolate dalle nebbie.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Dicevi: morte, silenzio, solitudine; | come amore, vita. Parole | delle nostre provvisorie immagini.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "L'uomo grida dovunque la sorte d'una patria.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "La mia terra è sui fiumi stretta al mare, | non altro luogo ha voce così lenta | dove i miei piedi vagano | tra giunchi pesanti di lumache.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Le spine dei fichidindia | sulla siepe, il tuo corpetto strappato | appena azzurro e nuovo, un dolore | al centro del cuore scavato, | forse a Lentini vicino la palude | di Iacopo notaio d'anguille | e d'amori.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Dalla natura deforme la foglia | simmetrica fugge, l'àncora più | non la tiene. Già inverno, non inverno, | fuma un falò presso il Naviglio.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Visibile, invisibile | il carettiere all'orizzonte | nelle braccia della strada chiama | risponde alla voce delle isole.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Dove sull'acque viola | era Messina, tra fili spezzati | e macerie tu vai lungo binari | e scambi col tuo berretto di gallo | isolano. Il terremoto ribolle | da due giorni, è dicembre d'uragani | e mare avvelenato.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Alle fronde dei salici, per voto, | anche le nostre cetre erano appese: | oscillavano lievi al triste vento.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "Mi richiama talvolta la tua voce, | e non so che cieli ed acque | mi si svegliano dentro: | una rete di sole che si smaglia | sui tuoi muri ch’erano a sera | un dondolio di lampade | dalle botteghe tarde | piene di vento e di tristezza.", Author = "Salvatore Quasimodo" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Salvatore_Quasimodo", Text = "La loro morte copre uno spazio immenso, | in esso uomini d'ogni terra | non dimenticano Marzabotto | il suo feroce evo | di barbarie contemporanea.", Author = "Salvatore Quasimodo" },
        };
    }
}