using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class TorquatoTasso
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "È la bellezza un raggio | di chiarissima luce | che non si può ridir quanto riluce | né pur quel ch'ella sia.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Era fermo Imeneo tra l'erto monte | e 'l mare, in cui sovente austro risuona, | la 've cinge e 'n corona Napoli bella l'onorata fronte.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Già discende Imeneo là dove alberga | la virtù col valore | e la gloria e l'onore, | e a gloriosi Eroi tesson corona.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "La materia nuda cade sotto la considerazion del poeta in quella guisa che 'l ferro o 'l legno vien sotto la considerazion del fabro.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "le scienze deono adoperarsi in grazia di se medesime, né altra grazia o altro giovamento o altro piacere o altra gloria è necessario che si ricerchi.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Non ci è chi meriti nome di creatore, che Dio e il poeta.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Penso e ripenso e nel pensar impazzo; levati di costì, testa di...", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Quella della musica è una delle tre vie per le quali l'anima ritorna al Cielo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Quivi Napoli bella i regi alberga, | città vittoriosa e trionfale: | veggio altri tempi ancor, e in altri monti | quel ch'ora innalza tre sublimi fronti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Solo gli schiavi delle galere si conoscono, tuttavia noi facciamo certamente finta di \"non conoscere\" gli altri perché essi siano a loro volta costretti a non conoscerci.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Chi crederia che sotto umane forme | e sotto queste pastorali spoglie | fosse nascosto un Dio?", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Forse, se tu gustassi anco una volta | la millesima parte de le gioie, | che gusta un cor amato riamando, | diresti, ripentita, sospirando: | perduto è tutto il tempo, | che in amar non si spende.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ma legge aurea, e felice, | che natura scolpì, S'ei piace, ei lice.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Amiam, ché non hà tregua | Con gli anni humana vita, e si dilegua: | Amiam, che ’l Sol si muore, e poi rinasce.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Veramente il secol d'oro è questo, | poiché sol vince l'oro e regna l'oro.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Femina, cosa mobil per natura.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "A poco a poco nacque ne 'l mio petto, | non so da qual radice, | com'erba suol che per se stessa germini, | un incognito affetto", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il ben passato e la presente noia!", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il mondo invecchia, | e invecchiando intristisce.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ma nulla fa chi troppe cose pensa.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il vero condito in molli versi | i più schivi allettando ha persuaso.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "A re malvagio, consiglier peggiore.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Già l'aura messaggera erasi desta | ad annunziar che se ne vien l'aurora: | ella intanto s'adorna, e l'aurea testa | di rose colte in paradiso infiora.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Purché 'l reo non si salvi, il giusto pera | e l'innocente.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Magnanima menzogna, or quand'è il vero | sì bello che si possa a te preporre?", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Un non so che d'inusitato e molle | par che nel duro petto al re trapasse; | ei presentillo e si sdegnò, né volle | piegarsi, e gli occhi torse, e si ritrasse.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Nulla a tanto intercessor si neghi.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Di sua bocca uscieno | più che mel dolci d'eloquenza i fiumi.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ben gioco è di fortuna audace e stolto | por contra il poco e incerto il certo e 'l molto.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ché fortuna qua già varia a vicenda | mandandoci venture or triste or buone, | ed a i voli troppo alti e repentini | sogliono i precipizi esser vicini.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Liberi sensi in libere parole.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Noi morirem, ma non morremo inulti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Chi la pace non vuol, la guerra s'abbia.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Io vêr Gerusalem, tu verso Egitto.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Sommessi accenti, e tacite parole, | Rotti singulti, e flebili sospiri.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Non lunge, quai veggiam fantasmi o larve, | Poi che nascoso è lo splendor diurno, | Tale un corrier ne l'ombre oscuro apparve | Per non diritte vie cheto e notturno.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il gran nemico dell'umane genti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Diversi aspetti in un confusi e misti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il rauco suon della tartarea tromba.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Pera il campo e ruini, e resti in tutto | Ogni vestigio suo con lui distrutto.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "(ahi, cieca umana mente, | come i giudizi tuoi son vani e torti!)", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Fa manto del vero alla menzogna.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Renditi vinto; e per tua gloria basti | Che dir potrai che contro me pugnasti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ahi crudo Amor, ch'ugualmente n'ancide | l'assenzio e 'l mèl che tu fra noi dispensi, | e d'ogni tempo egualmente mortali | vengon da te le medicine e i mali!", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ché nel mondo mutabile e leggiero | costanza è spesso il variar pensiero.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Così conclude, e con sì adorno inganno | cerca di ricoprir la mente accesa | sotto altro zelo; e gli altri anco d'onore | fingon desio quel ch'è desio d'amore.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Instinto è dell'umane menti | Che ciò che più si vieta, uom più desia.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Spesso avvien che ne' maggior perigli | Sono i più audaci gli ottimi consigli.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Mostra a dito ed onorata andresti | Fra le madri latine e fra le spose | Là nella bella Italia.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Era la notte, e 'l suo stellato velo | chiaro spiegava e senza nube alcuna; | e già spargea rai luminosi e gelo | di vive perle la sorgente luna.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "ombrose piante | D'antica selva.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Questa greggia e l'orticel dispensa | Cibi non compri alla mia parca mensa.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Difesa miglior, ch'usbergo e scudo, | È la santa innocenza al petto ignudo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Tosto s'opprime chi di sonno è carco, | ché dal sonno a la morte è un picciol varco.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Però che quello, o figli, è vile onore | cui non adorni alcun passato orrore.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Ma non perciò nel disdegnoso petto | d'Argante vien l'ardire o 'l furor manco.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Risorgerò nemico ognor più crudo, | Cenere anco sepolto e spirto ignudo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "A guisa di leon quando si posa.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "L'asta, ch'offesa or porta ed or vendetta, | per lo noto sentier vola e rivola.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Il bruno il bel non toglie.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Degne d'un chiaro sol, degne d'un pieno | teatro, opre sarian sì memorande.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Oh nostra folle | mente ch'ogn'aura di fortuna estolle!", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Segue egli la vittoria, e la trafitta | vergine minacciando incalza e preme.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Amico, hai vinto: io ti perdon...; perdona.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "La vide, e la conobbe; e restò senza | E voce e moto. Ahi vista! ahi conoscenza!", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "In questa forma | Passa la bella donna, e par che dorma.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Qual in membro gentil piaga mortale | tocca s'inaspra e in lei cresce il dolore, | tal da i dolci conforti in sì gran male | più inacerbisce medicato il core.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Oh vani giuramenti! ecco contrari | seguir tosto gli effetti a l'alta speme.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Non dee guerra co' morti aver chi vive.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Femmina è cosa garrula e fallace, | Vuole e disvuole: è folle uom che sen fida.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Muoiono le città, muoiono i regni, | copre i fasti e le pompe arena ed erba.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Di poema dignissima e d'istoria.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Quando mi gioverà narrare altrui | Le novità vedute e dire: Io fui!", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "E quel che 'l bello e 'l caro accresce a l'opre, | l'arte, che tutto fa, nulla si scopre.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Cogliam' la rosa in sul mattino adorno | Di questo dì che tosto il seren perde.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Teneri sdegni, e placide e tranquille | Repulse, e cari vezzi, e liete paci, | Sorrisi e parolette e dolci stille | Di pianto, e sospir tronchi, e molli baci.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "E mentre spunta l'un, l'altro matura.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Lo schermitor vinto è di schermo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Non scese, no, precipitò di sella.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Purché costei si salvi, il mondo pera.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Combatta qui chi di campar desia: | la via d'onor de la salute è via.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Conosco l'arti del fellone ignote, | ma ben può nulla chi morir non pote.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "– Ecco l'ancilla tua; d'essa a tuo senno | dispon, – gli disse – e le fia legge il cenno. –", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Difesa miglior ch'usbergo e scudo | è la santa innocenza al petto ignudo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "È 'l sonno, ozio de l'alme, oblio de' mali.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "La morte non è pena de i rei, ma fine de la pena.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "In questo sacro legno, ove la vita | Fu la sua prima foglia, e 'l frutto morte, | Estinta morte prende oggi la morte, | E più bella, che pria, torna la vita.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Qui gli Angeli innalzaro il santo albergo, | Che già Maria co ‘l santo figlio accolse.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Tu, Regina del ciel, ch' a noi ti mostri | umida i lumi e l'una e l'altra gota, | fa' di lagrime dono a gli occhi nostri.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Vecchio ed alato dio, nato col sole | ad un parto medesmo e con le stelle, | che distruggi le cose e rinnovelle.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Tu ne sterpa i pensieri e di giocondo | oblio spargi le piaghe, e tu disgombrala frode onde son pieni i regi chiostri.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Vergine bella, che dal Re del Cielo | Dell'alma i doni sì graditi avesti.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Che 'l gentil sangue, e i bei sembianti onesti | Sprezzasti, e ciò, ch'offende il caldo, e 'l gelo.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Pendon dopoi da le parti più belle | molte imagin ritratte in tutti i lati.", Author = "Torquato Tasso" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Torquato_Tasso", Text = "Di sesso e volto son diverse quelle, | e gli abiti tra loro han variati.", Author = "Torquato Tasso" },
        };
    }
}