using System;

namespace StdbModule;

public static partial class ItalianQuotes
{
    public static class VitalianoBrancati
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Che i conservatori siano conformisti, è cosa di tutti i tempi. Ma che siano conformisti, convenzionali, obbedienti i cosiddetti rivoluzionari, è cosa soltanto dei nostri tempi.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Dire che un delitto è opera di una società, il risultato matematico di taluni «fattori ambientali», è una di quelle offese che il nostro tempo rivolge continuamente alla libertà individuale e alla libertà in genere.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "È vero che ciascuna persona ha sotto il braccio il libro che si merita.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "I campi siciliani sono metropoli vegetali.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "No, non è vero che qui si parli molto. Anzi, è vero il contrario. In Sicilia, la vita intima fa a meno delle parole. Una madre e una figlia possono trascorrere un'intera giornata dietro il balcone, scambiandosi due o tre frasi.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Pago amarissimamente gli scherzi che mi sono permesso sui furiosi amori del Sud; del Sud a cui appartengo interamente e di cui sono, me ne accordo ora, il più pazzo ed avvelenato figliuolo.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Per essere siciliani bisogna essere diversi.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Siamo cinici nei riguardi di un credente fascista o di un credente comunista il quale, sotto le apparenze di fervore religioso, nasconde il più tetro dei cinismi.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "La ricchezza guasta l'intelligenza, come un pasto troppo forte vela di sonno anche l'occhio più vivace.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Se dunque la musica ha un maggior numero di amatori che non la poesia, o l'architettura, o la scultura, questo non si deve al fatto che essa è «più spirituale», come suol dirsi, bensì al fatto inverso: che è più sensuale.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Per il rispetto che il mio mestiere di cronista deve alla verità, dirò che questi scapoli siciliani erano piuttosto brutti, fuorché uno, Antonio Magnano, che era bellissimo. Con questo non voglio però affermare che i brutti riuscissero sgraditi alle donne: al contrario molti di essi, nonostante la bassa statura, e i nasi ebraici, e l'unghia del mignolo lasciata crescere per pulire l'interno dell'orecchio, parevano legati da una grave complicità a tutto il genere femminile; si sarebbe detto che fra loro e qualunque donna ci fosse una cattiva azione compiuta insieme chissà dove e quando: non v'era sconosciuta che, al primo vederli, non sembrasse riconoscerli impallidendo e rivelarsi subito legata a loro da vecchi e inconfessabili trascorsi. Per questo, i loro successi avevano sempre un'aria esosa di riscatto, sebbene, posso giurarlo, questi uomini di venticinque e trent'anni fossero di una cortesia e una tenerezza senza pari nei riguardi dell'altro sesso. Ma sulla terra piena di misteri, il viventi più misterioso è forse l'uomo brutto.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Un istantaneo vacillamento del passo la staccò dalla madre e la portò vicinissima al giovane che poté sentirne l'odore di velo, di pelle bruscamente riscaldata dal sangue, di forcine di tartaruga e d'indumenti conservati a lungo insieme a vecchi fiori, odore che nessuna donna di Roma aveva mai posseduto e che gli saettò dentro la carne come uno scotimento profondo. Egli rimase immobile, seguendo il corso di quella specie di serpe che gli era entrato nei nervi e li mordeva alla radice.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Gli uomini, per distrarsi dalla gelosia che gli riempiva la bocca di amaro ogni volta che guardavano le loro donne, rosse ed agitate come se tutte avessero sposato Antonio e s'inoltrassro con trepidazione in una giornata che conduceva alla sera e quindi ai misteri della notte, ragionavano fra di loro di politica, non senza aver dato una sbirciatina all'intorno per vedere se potessero parlare del capo del governo, non insolentendolo naturalmente, ma con rispetto moderato e senza le frasi di rito.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Il cielo sa quello che vuole, e quando un matrimonio non è scritto nel suo libro, abbiamo voglia, noi poveretti, di scrivere i nostri nomi l'uno accanto all'altro nel libro della parrocchia... il matrimonio rimane sulla carta!", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "«La contessa K» continuò «è stata la sola che ha dovuto sospettare la verità, perché una sera mi disse: \"Antonio, sia sincero, non sarebbe comodo poter possedere una donna con gli occhi?\" Non so se volesse alludere al fatto ch'io avevo lo sguardo di certi ingravidafinestroni siciliani dei quali aveva parlato la sera avanti...»", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Il rumore di quello scandalo fu avvertito da tutta Catania come un boato dell'Etna. Antonio Magnano, il figlio di Alfio, il nipote di Ermenegildo, il bellissimo giovane che faceva alzare lo sguardo dal messale alla più santa delle ragazze, Antonio dagli occhi sempre addormentati, e chi non lo conosceva? (levavano una mano al di sopra della testa per indicare ch'era alto o se la passavano dolcemente lungo le guance per dire che aveva un viso perfetto), Antonio, sí, proprio lui, quello, esattamente quello e non altri, ebbene Antonio con la moglie... niente! vi dico niente! assolutamente niente! Barbara Puglisi, dopo tre anni di matrimonio, non sa ancora cosa sia la grazia di Dio.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "« [...] Ognuno pensi a guardarsi la sua roba. Io come io, quando mi càpita una donna, non voglio sapere né di chi è figlia né di chi è moglie. È donna con la veste? e allora basta! Non voglio sapere altro!» «Ma cosí dove si va a finire?» «Una sotto e una sopra.» «E se lo facessero a te, che diresti?» «Io non sono sposato.» «Ma hai una madre, una sorella...» «Non mi parlare di mia madre e di mia sorella! Mia madre e mia sorella non c'entrano!» «Ma non sono donne anche loro?» «Sono donne, ma in questo discorso, ti ho detto, non c'entrano!»", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Le donne si comportavano con lui come gli uomini con le donne; tutte si ritenevano in diritto di scrivergli, di rivolgergli la parola, d'indorargli la pillola, di nascondergli la verità sotto abili eufemismi, di fare in modo da non spaventarlo, e infine di convincerlo a mettersi fiducioso nelle loro mani. Non erano questi i mezzi del più consumato dongiovannismo?", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "«Fra poco» diceva, «questi venti anni di tirannia, di rozzezza, di presunzione ci parrà di averli sognati in una notte di febbre. Conserveremo soltanto il tic di voltarci indietro prima di parlare a voce alta, e faremo ridere i nostri nipoti. \"Ma che ha il nonno\" domanderanno, \"che si guarda sempre alle spalle?\" E i nostri figli spiegheranno sorridendo che il povero nonno è vissuto in un'epoca nella quale ogni cittadino aveva il suo angelo custode dietro e andava in prigione solo per aver detto che il capo del governo era vecchio... Ma ci pensi, Antonio?»", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Io non sono vecchio! Non vogliono dir nulla settantaquattro anni! Cinquant'anni non sono nulla, non mi separano affatto dalla giovinezza. Se mi volto, dietro le mie spalle c'è la giovinezza chiara, nitida, e dietro c'è la fanciullezza, ancora più chiara e nitida di quando avevo vent'anni. I pensieri sono con me, li devo ancora sviluppare, e così i sentimenti, i desideri: li devo ancora appagare! Io non sono affatto sazio di vita, comincio appena ora ad assaporarla! Perché mi mettete addosso questi dolori artritici, queste rughe che mi fanno ghignare mentre non ghigno affatto, queste borse di pelle? Perché m'impastoiate come un mulo e mi accecate? Perché mi otturate le orecchie? E perché mi guardate con quegli occhi che trovano naturale che io muoia? C'è un errore, ve lo giuro! Arrivate alla mia età e ve ne accorgerete! Ma allora avrete anche voi un bel gridare, e quelli che avranno i venti, i trenta, i quaranta, i cinquanta, i sessanta, i settanta anni che adesso avete voi non vi crederanno, e vi conforteranno col tono bonario che si usa con i pazzi quando dicono d'essere sani!.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Ci sono sofferenze che scavano nella persona come i buchi di un flauto, e la voce dello spirito ne esce melodiosa.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "L'anima è eterna, e quello che non fa oggi, può farlo domani.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "L'avvenire non è un probabile dono del ciclo, ma è reale, legato al presente come una sbarra di ferro, immersa nel buio, alla sua punta illuminata.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "La felicità è la ragione.", Author = "Vitaliano Brancati" },
            new Quote { Id = "https://it.wikiquote.org/wiki/Vitaliano_Brancati", Text = "Un uomo può avere due volte vent'anni senz'averne quaranta.", Author = "Vitaliano Brancati" },
        };
    }
}