// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as GameModeVariants from './game_mode_variants'

// The tagged union or sum type for the algebraic type `GameMode`.
export type GameMode = GameModeVariants.English500 |
  GameModeVariants.Spanish500 |
  GameModeVariants.French500 |
  GameModeVariants.German500 |
  GameModeVariants.Italian500 |
  GameModeVariants.Portuguese500 |
  GameModeVariants.Japanese500 |
  GameModeVariants.Korean500 |
  GameModeVariants.Chinese500 |
  GameModeVariants.Ukrainian500 |
  GameModeVariants.Arabic500 |
  GameModeVariants.Hindi500 |
  GameModeVariants.Dutch500 |
  GameModeVariants.Swedish500 |
  GameModeVariants.Turkish500;

let _cached_GameMode_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const GameMode = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  English500: { tag: "English500" } as const,
  Spanish500: { tag: "Spanish500" } as const,
  French500: { tag: "French500" } as const,
  German500: { tag: "German500" } as const,
  Italian500: { tag: "Italian500" } as const,
  Portuguese500: { tag: "Portuguese500" } as const,
  Japanese500: { tag: "Japanese500" } as const,
  Korean500: { tag: "Korean500" } as const,
  Chinese500: { tag: "Chinese500" } as const,
  Ukrainian500: { tag: "Ukrainian500" } as const,
  Arabic500: { tag: "Arabic500" } as const,
  Hindi500: { tag: "Hindi500" } as const,
  Dutch500: { tag: "Dutch500" } as const,
  Swedish500: { tag: "Swedish500" } as const,
  Turkish500: { tag: "Turkish500" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GameMode_type_value) return _cached_GameMode_type_value;
    _cached_GameMode_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_GameMode_type_value.value.variants.push(
      { name: "English500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Spanish500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "French500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "German500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Italian500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Portuguese500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Japanese500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Korean500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Chinese500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Ukrainian500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Arabic500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Hindi500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Dutch500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Swedish500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Turkish500", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_GameMode_type_value;
  },

  serialize(writer: __BinaryWriter, value: GameMode): void {
      __AlgebraicTypeValue.serializeValue(writer, GameMode.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameMode {
      return __AlgebraicTypeValue.deserializeValue(reader, GameMode.getTypeScriptAlgebraicType());
  },

}

export default GameMode;


