// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as PlayerColorVariants from './player_color_variants'

// The tagged union or sum type for the algebraic type `PlayerColor`.
export type PlayerColor = PlayerColorVariants.Red |
  PlayerColorVariants.Orange |
  PlayerColorVariants.Amber |
  PlayerColorVariants.Yellow |
  PlayerColorVariants.Lime |
  PlayerColorVariants.Green |
  PlayerColorVariants.Emerald |
  PlayerColorVariants.Teal |
  PlayerColorVariants.Cyan |
  PlayerColorVariants.Sky |
  PlayerColorVariants.Blue |
  PlayerColorVariants.Indigo |
  PlayerColorVariants.Violet |
  PlayerColorVariants.Purple |
  PlayerColorVariants.Fuchsia |
  PlayerColorVariants.Pink |
  PlayerColorVariants.Rose;

let _cached_PlayerColor_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const PlayerColor = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Red: { tag: "Red" } as const,
  Orange: { tag: "Orange" } as const,
  Amber: { tag: "Amber" } as const,
  Yellow: { tag: "Yellow" } as const,
  Lime: { tag: "Lime" } as const,
  Green: { tag: "Green" } as const,
  Emerald: { tag: "Emerald" } as const,
  Teal: { tag: "Teal" } as const,
  Cyan: { tag: "Cyan" } as const,
  Sky: { tag: "Sky" } as const,
  Blue: { tag: "Blue" } as const,
  Indigo: { tag: "Indigo" } as const,
  Violet: { tag: "Violet" } as const,
  Purple: { tag: "Purple" } as const,
  Fuchsia: { tag: "Fuchsia" } as const,
  Pink: { tag: "Pink" } as const,
  Rose: { tag: "Rose" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_PlayerColor_type_value) return _cached_PlayerColor_type_value;
    _cached_PlayerColor_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_PlayerColor_type_value.value.variants.push(
      { name: "Red", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Orange", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Amber", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Yellow", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Lime", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Green", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Emerald", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Teal", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Cyan", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Sky", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Blue", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Indigo", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Violet", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Purple", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Fuchsia", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Pink", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Rose", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_PlayerColor_type_value;
  },

  serialize(writer: __BinaryWriter, value: PlayerColor): void {
      __AlgebraicTypeValue.serializeValue(writer, PlayerColor.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerColor {
      return __AlgebraicTypeValue.deserializeValue(reader, PlayerColor.getTypeScriptAlgebraicType());
  },

}

export default PlayerColor;


