// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

import { CountdownStart } from "./countdown_start_type";
// Mark import as potentially unused
declare type __keep_CountdownStart = CountdownStart;

export type StartCountdown = {
  args: CountdownStart,
};
let _cached_StartCountdown_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const StartCountdown = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_StartCountdown_type_value) return _cached_StartCountdown_type_value;
    _cached_StartCountdown_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_StartCountdown_type_value.value.elements.push(
      { name: "args", algebraicType: CountdownStart.getTypeScriptAlgebraicType() },
    );
    return _cached_StartCountdown_type_value;
  },

  serialize(writer: __BinaryWriter, value: StartCountdown): void {
    __AlgebraicTypeValue.serializeValue(writer, StartCountdown.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): StartCountdown {
    return __AlgebraicTypeValue.deserializeValue(reader, StartCountdown.getTypeScriptAlgebraicType());
  },

}

export default StartCountdown;

