// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

import { CharacterEventType } from "./character_event_type_type";
// Mark import as potentially unused
declare type __keep_CharacterEventType = CharacterEventType;

export type UpdateProgress = {
  gameId: string,
  newIndex: number,
  eventType: CharacterEventType,
};
let _cached_UpdateProgress_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const UpdateProgress = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_UpdateProgress_type_value) return _cached_UpdateProgress_type_value;
    _cached_UpdateProgress_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_UpdateProgress_type_value.value.elements.push(
      { name: "gameId", algebraicType: __AlgebraicTypeValue.String },
      { name: "newIndex", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "eventType", algebraicType: CharacterEventType.getTypeScriptAlgebraicType() },
    );
    return _cached_UpdateProgress_type_value;
  },

  serialize(writer: __BinaryWriter, value: UpdateProgress): void {
    __AlgebraicTypeValue.serializeValue(writer, UpdateProgress.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): UpdateProgress {
    return __AlgebraicTypeValue.deserializeValue(reader, UpdateProgress.getTypeScriptAlgebraicType());
  },

}

export default UpdateProgress;

