using System;

namespace StdbModule;

public static partial class PortugueseQuotes
{
    public static class EuclidesdaCunha
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O sertanejo é, antes de tudo, um forte.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Não é o bárbaro que nos ameaça, é a civilização que nos apavora.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Estamos condenados à civilização. Ou progredimos ou desaparecemos.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O bandeirante foi brutal, inexorável, mas lógico. Foi o super-homem do deserto.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Canudos tinha muito apropriadamente, em roda, uma cercadura de montanhas. Era um parêntesis; era um hiato. Era um vácuo. Não existia. Transposto aquele cordão de serras, ninguém mais pecava.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Somos o único caso histórico de uma nacionalidade feita por uma teoria política. Vimos, de um salto, da homogeineidade da colônia para o regímen constitucional: do alvará para as leis.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O evangelho fecha-se com a astronomia.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "A jurisdição do Uruguai sobre as águas platinas, nos limites normais do direito, imposta vigorosamente pelos antecedentes históricos e pelas próprias leis naturais, é dessas causas superiores, que para triunfar dispensam a fragilidade das espadas, amparando-se exclusivamente na fortaleza eterna e tranquila da justiça.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "A poeira dos arquivos de que muita gente fala sem nunca a ter visto ou sentido, surgindo tenuíssima de páginas que se esfarelam ainda quando delicadamente folheadas, esta poeira clássica — adjetivemos com firmeza — que cai sobre tenazes investigadores ao investirem contra as longas veredas do passado, levanto-a diariamente. E não tem sido improfícuo o esforço.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O verdadeiro Brasil nos aterra; trocamo-lo de bom grado pela civilização mirrada que nos acotovela na rua do Ouvidor...", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Sem este objetivo firme e permanente de conhecer o interior inóspito, a Amazônia, mais cedo ou mais tarde, se destacará do Brasil, naturalmente e irresistivelmente, como se despega um mundo de uma nebulosa — pela expansão centrífuga do seu próprio movimento.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "A República tirou-nos do remanso isolador do império para a perigosa solidariedade sul-americana: caímos dentro do campo da visão, nem sempre lúcida, do estrangeiro, insistentemente fixa sobre os povos, os governos e os 'governos' (ironicamente sublinhados ou farpeados de aspas) da América do Sul.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O lema da nossa bandeira é uma síntese admirável do que há de mais elevado em política.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "A nossa nacionalidade atravessa de há muito uma quadra em que o mais difícil problema consiste em harmonizar a vida ao dever.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Sem nos filiarmos a escolas filosóficas — o que é um verdadeiro absurdo na mocidade, na quadra exuberante em que, para a formação imprescindível da consciência, nos voltamos indistintamente para todas as ideias, abrindo com igual interesse e igual curiosidade todos os livros, ouvindo com igual respeito todas as crenças e tributando igual veneração a todos os sábios — vamos definir o nosso modo de pensar...", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "É necessário que tenhamos a postura corretíssima dos fortes! Não é invadindo prisões que se castigam criminosos. Nada mais falível e relativo do que esta justiça humana condecorada pela metafísica com o qualificativo de absoluta. Há nos sentimentos que ambos tributamos à República uma diferença enorme: s. ex. tem por ela um amor tempestuoso e cheio de delírios de amante, eu tenho por ela os cuidados e a afeição serena de um filho.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Então... eu não creio em Deus?! Quem te disse isto? Puseste-me na mesma roda dos singulares infelizes, que usam o ateísmo como usam de gravatas — por \"chic\", e para se darem ares de sábios... Não.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Num país em que toda a gente acomoda a sua vidinha num cantinho de secretaria, ou numa aposentadoria, eu estou, depois de haver trabalhado tanto, galhardamente, sem posição definida! Reivindico, assim, o belo título de último dos românticos, não já do Brasil apenas, mas do mundo todo, nestes tempos utilitários! Julgo, entretanto, que hei de arrepender-me muito, mais tarde, desta vaidade...", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Quem definirá um dia essa Maldade obscura e misteriosa das coisas, que inspirou aos gregos a concepção indecisa da Fatalidade?", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Nostalgia e revolta: tu não imaginas como andam propícios os tempos a todas as mediocridades. Estamos no período hilariante dos grandes homens-pulhas, dos Pachecos empavesados e dos Acácios triunfantes. Nunca se berrou tão convictamente tanta asneira sob o sol! [...] É asfixiante! A atmosfera moral é magnífica para batráquios. Mas apaga o homem. [...].", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "nada se perde abandonando uma estrela para abraçar um amigo.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "O nosso povo, meu caro Porchat, por abdicação completa de todas as energias, não tem forças para agitar-se além das arruaças desprezíveis.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "No meio de tudo isto [Revolta da Armada] eu tive felizmente bastante lucidez para descobrir a estrada do dever, e nela estou e nela prosseguirei.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "se as nações estrangeiras mandam cientistas ao Brasil, que absurdo haverá no encarregar-se de idêntico objetivo um brasileiro?", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "não desejo Europa, o 'boulevard', os brilhos de uma posição, desejo o sertão, a picada malgradada, e a vida afanosa e triste de pioneiro. Nestes tempos de fragilidade já não é pouco.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Há mais de um mês que me agito e trabalho — de graça — num país em que se inventam os empregos para a vadiagem remunerada.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "pareceu-me e parece-me que o mais tosco verso de um livre à memória de um herói [Tiradentes] esmaga o mais brilhante poema que se atira aos pés de um rei...", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "É, desgraçadamente, comum nesta terra vender-se a consciência; mas, eu terei asco de mim mesmo se um dia (estou plenamente seguro que nunca me achanará) calcar as mais sagradas ilusões de meu cérebro para satisfazer as exigências do estômago.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Os Farrapos — (...) Se um dia porém — puder arcar com tal assunto — hei de sacrificar-me inteiramente a esses revolucionários audazes e obscuros, a esses miseráveis sublimes que esqueceram a própria fome e arrojaram-se impávidos à goela famulenta do despotismo para que ele não lhes devorasse a pátria.", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "Eu tenho fanatismo tão insensato pela palavra, pela tribuna que, faça embora o que fizer de melhor para a sociedade, terei cumprido mal o meu destino se não tiver ocasião de, pelo menos uma vez, erguer a minha palavra sobre a fronte de qualquer infeliz, abandonado de todos; e aí impávido, altivo, audaz e insolente arriscar em prol de sua vida obscura todas as energias de meu cérebro, todos os meus ideais — a minha ilusão mais pura, o meu futuro e a vida minha!...", Author = "Euclides da Cunha" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Euclides_da_Cunha", Text = "É a realidade maior – vibrando numa emoção. Este chão que tumultua, e corre, e foge, e se crispa, e cai, e se alevanta, é o mesmo chão que o geólogo denomina \"solo perturbado\" e inspira à rasa, à modesta, à chaníssima topografia, a metáfora garbosa dos \"movimentos do terreno\".", Author = "Euclides da Cunha" },
        };
    }
}