using System;

namespace StdbModule;

public static partial class PortugueseQuotes
{
    public static class FernandoPessoa
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A felicidade está fora da felicidade.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Boa é a vida, mas melhor é o vinho.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A literatura, como toda a arte, é uma confissão de que a vida não basta.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Vão para o diabo sem mim, ou deixem-me ir sozinho para o diabo! Para que haveremos de ir juntos?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Descobri que a leitura é uma forma servil de sonhar. Se tenho de sonhar, porque não sonhar os meus próprios sonhos?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quero fugir ao mistério / Para onde fugirei? / Ele é a vida e a morte / Ó Dor, aonde me irei?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não me venham com conclusões! A única conclusão é morrer.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca ninguém se perdeu / Tudo é verdade e caminho.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sê plural como o universo!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tenho pensamentos que, se pudesse revelá-los e fazê-los viver, acrescentariam nova luminosidade às estrelas, nova beleza ao mundo e maior amor ao coração dos homens.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Pedi tão pouco à vida e mesmo esse pouco a vida me negou", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Com uma tal falta de gente coexistível, como há hoje, que pode um homem de sensibilidade fazer senão inventar os seus amigos, ou quando menos, os seus companheiros de espírito?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ai, que prazer / Não cumprir um dever.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O poeta é um fingidor. Finge tão completamente Que chega a fingir que é dor A dor que deveras sente.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não há normas. Todos os homens são excepção a uma regra que não existe", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O dinheiro compra um mausoléu, mas não um lugar no céu.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quando falo com sinceridade, não sei com que sinceridade falo. Sou variamente outro do que um eu que não sei se existe", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quem não vê bem uma palavra, não pode ver bem uma alma", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não haver deuses é um deus também", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tenho em cada canto de minha Alma, Um altar erguido a um Deus diferente", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tenho prazer em ser vencido quando quem me vence é a razão, seja quem for o seu procurador.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tudo que sou não é mais do que abismo Em que uma vaga luz Com que sei que sou eu, e nisto cismo, Obscura me conduz.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Um intervalo entre não-ser e ser Feito de eu ter lugar Como o pó, que se vê o vento erguer, Vive de ele o mostrar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tenho o dever de me fechar em casa no meu espírito e trabalhar quanto possa e em tudo quanto possa, para o progresso da civilização e o alargamento da consciência da humanidade", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Eu amo tudo o que foi. Tudo o que já não é. A dor que já não me dói. A antiga e errônea fé. O ontem que a dor deixou. O que deixou alegria. Só porque foi, e voou. E hoje é já outro dia.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A morte chega cedo, Pois breve é toda vida. O instante é o arremedo, De uma coisa perdida.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Minha pátria é a língua portuguesa.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Claro em pensar, e claro no sentir, / e claro no querer", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Cumpri contra o Destino o meu dever. / Inutilmente? Não, porque o cumpri.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Cumpriu-se o Mar, e o Império se desfez. / Senhor, falta cumprir-se Portugal!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Deus quer, o homem sonha, a obra nasce.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Deus ao mar o perigo e o abismo deu, / Mas nele é que espelhou o céu.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Fiel à palavra dada e à ideia tida. / Tudo o mais é com Deus!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "E o homem do leme disse, tremendo, / 'El-Rei D. João Segundo!'", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Jaz aqui, na pequena praia extrema, / o Capitão do Fim.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O mar com fim será grego ou romano: / O mar sem fim é português.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O mito é o nada que é tudo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ó mar salgado, quanto do teu sal / São lágrimas de Portugal", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ó Portugal, hoje és nevoeiro...", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Os Deuses vendem quando dão. / Compra-se a glória com desgraça. / Ai dos felizes, porque são / Só o que passa!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quem quer passar além do Bojador / Tem que passar além da dor.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "São ilhas afortunadas, / São terras sem ter lugar", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sem a loucura que é o homem / Mais que a besta sadia, / Cadáver adiado que procria?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Todo começo é involuntário.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tudo vale a pena / Se a alma não é pequena.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A arte consiste em fazer os outros sentir o que nós sentimos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A arte mente porque é social", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A beleza de um corpo nu só a sentem as raças vestidas.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A consciência da insonsciência da vida é o mais antigo imposto à inteligência.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A experiência directa é o subterfúgio, ou o esconderijo, daqueles que são desprovidos de imaginação.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A força sem a destreza é uma simples massa.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A fraternidade tem subtilezas.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A ironia é o primeiro indício de que a consciência se tornou consciente.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A ladeira leva ao moinho, mas o esforço não leva a nada.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A natureza é a diferença entre a alma e Deus.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A liberdade é a possibilidade do isolamento.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A minha alegria é tão dolorosa como a minha dor.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A minha curiosidade irmã das cotovias", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A minha vida é como se me batessem com ela.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A propriedade não é roubo: não é nada.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A solidão desola-me; a companhia oprime-me.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A sua cara lívida está de um verde falso e desnorteado. Noto-o, entre o ar difícil do peito, com a fraternidade de saber que também estarei assim.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "A vida é um novelo que alguém emaranhou.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ah, não há saudades mais dolorosas do que as das coisas que nunca foram!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Achego-me à minha secretária como a um baluarte contra a vida.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Adoramos a perfeição, porque não a podemos ter; repugná-la-íamos, se a tivéssemos. O perfeito é o desumano, porque o humano é imperfeito.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Agir é repousar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Aquilo que, creio, produz em mim o sentimento profundo, em que vivo, de inconguência com os outros, é que a maioria pensa com a sensibilidade, e eu sinto com o pensamento.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Assim como lavamos o corpo devíamos lavar o destino, mudar de vida como mudamos de roupa.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Benditos os que não confiam a vida a ninguém.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Busco-me e não me encontro. Pertenço a horas crisântemos, nítidas em alongamentos de jarros. Deus fez da minha alma uma coisa decorativa.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Cada um tem a sua vaidade, e a vaidade de cada um é o seu esquecimento de que há outros com alma igual.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Coisa arrojada a um canto, trapo caído na estrada, meu ser ignóbil ante a vida finge-se.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Como nunca podemos conhecer todos os elementos de uma questão, nunca a podemos resolver.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Considero a vida uma estalagem onde tenho que me demorar até que chegue a diligência do abismo. Não sei onde ela me levará, porque não sei nada.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Creio que dizer uma coisa é conservar-lhe a virtude e tirar-lhe o terror.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Dentro da capoeira de onde irá a matar, o galo canta hinos à liberdade porque lhe deram dois poleiros.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Digo-o porque não acredito.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Dispenso-a de comparecer na minha idéia de si.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Doem-me a cabeça e o universo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Dormia tudo como se o universo fosse um erro.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Duas coisas só me deu o Destino: uns livros de contabilidade e o dom de sonhar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Durmo e desdurmo. / Do outro lado de mim, lá para trás de onde jazo, o silêncio da casa toca no infinito. Oiço cair o tempo, gota a gota, e nenhuma gota que cai se ouve cair.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "E a suprema glória disto tudo, meu amor, é pensar que talvez isto não seja verdade, nem eu o creia verdadeiro. // E quando a mentira comece a dar-nos prazer, falemos a verdade para lhe mentirmos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "E assim como sonho, raciocino se quiser, porque isso é apenas uma outra espécie de sonho.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "É certo que, ao ouvir contar a qualquer destes indivíduos as suas maratonas sexuais, uma vaga suspeita nos invade, pela altura do sétimo desfloramento.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "E seja o nosso desprezo para os que trabalham e lutam e o nosso ódio para os que esperam e confiam.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "É nobre ser tímido, ilustre não saber agir, grande não ter jeito para viver.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Em qualquer espírito, que não seja disforme, existe a crença em Deus. Em qualquer espírito, que não seja disforme, não existe crença em um Deus definido.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Entre mim e a vida há um vidro ténue. por mais nitidamente que eu veja e compreenda a vida, eu não lhe posso tocar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Eram dois e belos e desejavam ser outra coisa; o amor tardava-lhes no tédio do futuro, e a saudade do que haveria de ser vinha já sendo filha do amor que não tinham tido.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Estagnar ao sol, douradamente, como um lago obscuro rodeado de flores.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Eu não escrevo em português. Escrevo eu mesmo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Eu, porém, não tenho nobreza estilística. Dói-me a cabeça porque me dói a cabeça. Dói-me o universo porque me dói a cabeça.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Foi num mar interior que o rio da minha vida findou.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Foi só um momento, e vi-me. Depois já não sei sequer dizer o que fui.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Gostava de estar no campo para poder gostar de estar na cidade.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Há os que Deus mesmo explora, e são profetas e santos na vacuidade do mundo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Há muito tempo que não sou eu.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Há sensações que são somos, que ocupam como uma névoa toda a extensão do espírito, que não deixam pensar, que não deixam agir, que não deixam claramente ser.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Hei-de por força dizer o que me parece, visto que sou eu.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Irrita-me a felicidade de todos estes homens que não sabem que são infelizes.[...] Por isto, contudo, amo-os a todos. Meus queridos vegetais!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Isso não é o meu amor; é apenas a sua vida.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Levo comigo a consciência da derrota como um pendão de vitória.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não o prazer, não a glória, não o poder: a liberdade, unicamente a liberdade.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O comboio abranda, é o Cais do Sodré. Cheguei a Lisboa, mas não a uma conclusão.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O coração, se pudesse pensar, pararia.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O olfacto é uma vista estranha. Evoca paisagens sentimentais por um desenhar súbito do subconsciente.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O relógio da casa, lugar certo lá ao fundo das coisas, soa a meia hora seca e nula. Tudo é tanto, tudo é tão fundo, tudo é tão negro e frio!", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O ter tocado os pés de Cristo não é desculpa para defeitos de pontuação.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Os meus sonhos são um refúgio estúpido, como um guarda-chuva contra um raio.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Para compreender, destruí-me.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Passar dos fantasmas da fé para os espectros da razão é somente ser mudado de cela.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Passo tempos, passo silêncios, mudos sem forma passam por mim.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Porque eu sou do tamanho do que vejo / e não do tamanho da minha altura.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Que seria do mundo se fôssemos humanos?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quem não vê bem uma palavra, não pode ver bem uma alma.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Manda quem não sente. Vence quem pensa só o que precisa para vencer.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Meu Deus, meu Deus, a quem assisto? Quantos sou? Quem é eu? O que é este intervalo que há entre mim e mim?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Minha Pátria é a língua portuguesa.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não acredito na paisagem.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Não há critério seguro para distinguir o homem dos animais.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Narrar é criar, pois viver é apenas ser vivido.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Navegar é preciso, viver não é preciso.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca amamos ninguém. Amamos, tão-somente, a ideia que fazemos de alguém. É a um conceito nosso -- em suma, é a nós mesmos -- que amamos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca fui mais que um boémio isolado, o que é um absurdo; ou um boémio místico, o que é uma coisa impossível.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca me pesou o que de trágico se passasse na China. É decoração longínqua, ainda que a sangue e peste.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca pretendi ser senão um sonhador.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Nunca vou para onde há risco. tenho medo a tédio dos perigos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O entusiasmo é uma grosseria.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O fim é baixo, comotodos os fins quantitativos, pessoais ou não, e é atingível e verificável.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O homem não deve poder ver a sua própria cara. Isso é o que há de mais terrível. A Natureza deu-lhe o dom de não a poder ver, assim como a de não poder fitar os seus próprios olhos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O homem perfeito do pagão era a perfeição do homem que há; o homem perfeito do cristão a perfeição do homem que não há; o homem perfeito do budista a perfeição de não haver homem.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O homem vulgar, por mais dura que lhe seja a vida, tem ao menos a felicidade de a não pensar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O que há de mais reles nos sonhos é que todos os têm.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O humanitarismo é uma grosseria.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O império supremo é o do Imperador que abdica de toda a vida normal, dos outros homens, em quem o cuidado da supremacia não pesa como um fardo de jóias.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O mundo é de quem não sente. A condição essencial para se ser um homem prático é a ausência de sensibilidade.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "O tédio é a falta de uma mitologia. A quem não tem crenças, até a dúvida é impossível, até o cepticismo não tem força para desconfiar.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Pensar é destruir. O próprio processo do pensamento o indica para o mesmo pensamento, porque pensar é decompor.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Perder tempo comporta uma estética", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Pertenço àquela espécie de homens que estão sempre na margem daquilo a que pertencem, nem vêem só a multidão de que são, senão também os grandes espaços que há ao lado.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Porque é bela a arte? Porque é inútil. Porque é feia a vida? Porque é toda fins e propósitos e intenções.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Porque dar valor ao próprio sofrimento põe-lhe o ouro de um sol do orgulho. Sofrer muito pode dar a ilusão de ser o Eleito da Dor.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quando escrevo, visito-me solenemente.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Que é a arte senão a negação da vida?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Quem sou eu para mim? Só uma sensação minha.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Releio? Menti! Não ouso reler. Não posso reler. De que me serve reler?", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Respira-se melhor quando se é rico.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sabemos bem que toda a obra tem que ser imperfeita, e que a menos segura das nossas contemplações estéticas será a daquilo que escrevemos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Saber iludir-se bem é a primeira qualidade do estadista.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Saber não ter ilusões é absolutamente necessário para se poder ter sonhos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Se conhecêssemos a verdade, vêr-la-íamos; tudo o mais é sistema e arrabaldes.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Se te é impossível viver só, nasceste escravo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sento-me à porta e embebo meus olhos e ouvidos nas cores e nos sons da paisagem, e canto lento, para mim só, vagos cantos que componho enquanto espero.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ser compreendido é prostituir-se.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ser major reformado parece-me uma coisa ideal. É pena não se poder ter sido eternamente apenas major reformado.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Serei o que quiser. Mas tenho que querer o que for. O êxito está em ter êxito, e não em ter condições de êxito.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sim, falar com gente dá-me vontade de dormir.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Só a esterilidade é nobre e digna. Só o matar o que nunca foi é alto e perverso e absurdo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Somos dois abismos -- um poço fitando o céu.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sou um homem para quem o mundo exterior é uma realidade interior.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Sou todas essa coisas, embora o não queira, no fundo confuso da minha sensibilidade fatal.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Ter opiniões definidas e certas, instintos, paixões e carácter fixo e conhecido -- tudo isto monta ao horror de tornar a nossa alma num facto, de a materializar e tornar exterior.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Todo o gesto é um acto revolucionário.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Todo o prazer é um vício, porque buscar o prazer é o que todos fazem na vida, e o único vício negro é fazer o que toda a gente faz.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Todos os problemas são insolúveis. A essência de haver um problema é não haver solução. Procurar um facto significa não haver um facto. Pensar é não saber existir.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tornamo-nos esfinges, ainda que falsas, até chegarmos ao ponto de não sabermos quem somos.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Trazem-me a fé como um embrulho fechado numa salva alheia. Querem que o aceite para que não o abra.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Tudo é absurdo.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Uma espécie de anteneurose do que serei quando já não for gela-me o corpo e alma. Uma como que lembrança da minha morte futura arrepia-me dentro.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Um tédio que inclui a antecipação só de mais tédio; a pena, já, de amanhã ter pena de ter tido pena hoje.", Author = "Fernando Pessoa" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Fernando_Pessoa", Text = "Vivo sempre no presente. O futuro, não o conheço. O passado, já o não tenho.", Author = "Fernando Pessoa" },
        };
    }
}