using System;

namespace StdbModule;

public static partial class PortugueseQuotes
{
    public static class PauloCoelho
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "É um sonho, e, como todo sonho, é um sonho.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O primeiro sintoma de que estamos matando nossos sonhos é a falta de tempo. As pessoas mais ocupadas têm tempo para tudo. As que nada fazem estão sempre cansadas.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A busca da felicidade é pessoal, e não um modelo que possamos dar para os outros.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A cada momento de nossa existência temos que escolher entre um caminho e o outro. Uma simples decisão pode afetar uma pessoa para resto da vida.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A linguagem de seu coração é que irá determinar a maneira correta de descobrir e manejar a sua espada.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "No Bom Combate, atacar ou fugir fazem parte da luta. O que não faz parte da luta é ficar paralisado de medo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O bom combate é aquele que é travado em nome de nossos sonhos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O homem é o único ser na natureza que tem consciência de que vai morrer. [...] Mesmo sabendo que seus dias estão contados e tudo irá se acabar quando menos espera, ele faz da vida uma luta digna de um ser eterno..", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O homem nunca pode parar de sonhar. O sonho é o alimento da alma, como a comida é o alimento do corpo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Antes da mão manejar a espada, ela deve localizar o Inimigo e saber como enfrentá-lo. A espada apenas dá o golpe. Mas a mão já está vitoriosa ou perdedora antes desse golpe.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "o maior pecado de todos: o Arrependimento.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Os homens que se julgam sábios são indecisos na hora de mandar e são rebeldes na hora de servir.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A única maneira de salvarmos nossos sonhos, é sendo generosos conosco mesmos", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Às vezes, a felicidade é uma bênção - mas geralmente é uma conquista.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O amor se descobre através da prática de amar e não das palavras.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Se admitirmos por nós mesmos que Deus nos criou para a felicidade, teremos que assumir que tudo aquilo que nos leva para a tristeza e para a derrota é nossa culpa.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Para você ter uma vida espiritual, não precisa entrar para um seminário, nem fazer jejum, abstinência e castidade.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "AI EU O ESPERO OU O ESQUEÇO. ESPERAR DÓI, ESQUECER DÓI, MAS NÃO SABER O QUE FAZER É A PIOR DOR", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A melhor maneira de servir a Deus é indo ao encontro de seus próprios sonhos. Só quem é feliz pode espalhar felicidade.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "No amor não existem regras.Não adianta tentar seguir manuais. O coração decide, e o que ele decidir é o que vale.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Todos os dias Deus nos dá um momento em que é possível mudar tudo que nos deixa infelizes. O instante mágico é o momento em que um \"sim* “ ou um \"não* “ pode mudar toda a nossa existência.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Uma coisa é você achar que está no caminho certo, outra é achar que o seu caminho é o único. Nunca podemos julgar a vida dos outros, porque cada um sabe da sua própria dor e renúncia.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Tudo o que é novo incomoda. A vida nos pega desprevenidos e nos obriga a caminhar para o desconhecido mesmo quando não queremos ou quando não precisamos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A vida nos pega desprevenidos e nos obriga a caminhar para o desconhecido mesmo quando não queremos, quando não precisamos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A palavra é um dos meios favoritos de Deus se manifestar. Deus se manifesta em tudo, mas a palavra é um dos seus meios favoritos de agir. Porque a palavra é o pensamento transformado em vibração; você está colocando no ar a sua volta aquilo que antes era apenas energia.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A prece, quando feita com as palavras da alma, é muito mais poderosa.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "É preciso correr riscos, seguir certos caminhos e abandonar outros. Nenhuma pessoa é capaz de escolher sem medo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Jamais deixe que as dúvidas paralisem suas ações. Tome sempre todas as decisões que precisar tomar, mesmo sem ter a segurança de estar decidindo corretamente.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Julgar-se pior que os outros é um dos mais violentos atos de orgulho - porque é usar a maneira mais destrutiva possível de ser diferente.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Não existe outra maneira de estar perto das pessoas sem ser uma delas.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O caminho da sabedoria é não ter medo de errar.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quando alguém encontra seu caminho, precisa ter coragem suficiente para dar passos errados. As decepções, as derrotas, o desânimo são ferramentas que Deus utiliza para mostrar a estrada.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quando as dúvidas param de existir, é porque você parou em sua caminhada.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quem tenta possuir uma flor verá a sua beleza murchando. Mas quem olhar uma flor no campo permanecerá para sempre com ela.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Sabedoria é conhecer e transformar.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Conhecimento sem transformação não é sabedoria.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Deus é a palavra. Cuidado com o que você fala em qualquer situação ou instante de sua vida.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Pelo brilho nos olhos, desde o começo dos tempos, as pessoas reconhecem seu verdadeiro Amor.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quanto mais você entender de si mesma, mais entenderá do mundo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Ser homem é ter dúvidas, e mesmo assim continuar o seu caminho.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "As coisas simples são as mais extraordinárias, e só os sábios conseguem vê-las.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Cada momento da busca é um momento de encontro com Deus e com a Eternidade.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "É justamente a possibilidade de realizar um sonho que torna a vida interessante.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Ninguém sente medo do desconhecido, porque qualquer pessoa é capaz de conquistar tudo que quer e necessita.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O medo de sofrer é pior do que o próprio sofrimento. E nenhum coração jamais sofreu quando foi em busca de seus sonhos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O seu coração está onde está o seu tesouro. E seu tesouro precisa ser encontrado para que tudo possa fazer sentido.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quando se ama é que se consegue ser qualquer coisa da criação. Quando se ama não temos necessidade nenhuma de entender o que acontece, porque tudo passa a acontecer dentro de nós, e os homens podem se transformar em vento. Desde que os ventos ajudem, é claro.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "E quando você quer alguma coisa, todo o Universo conspira para que você realize seu desejo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Só sentimos medo de perder aquilo que temos, sejam nossas vidas ou nossas plantações. Mas esse medo passa quando entendemos que nossa história e a história do mundo foram escritas pela mesma mão.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Só uma coisa torna um sonho impossível: o medo de fracassar.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A maior mentira do mundo: em determinado momento de nossa existência, perdemos o controle de nossas vidas, e ela passa a ser governada pelo destino.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "É preciso não relaxar nunca, mesmo tendo chegado tão longe.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Escute seu coração. Ele conhece todas as coisas, porque veio da Alma do Mundo e um dia retornará para ela.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Ninguém consegue fugir do seu coração. Por isso é melhor escutar o que ele fala. Para que jamais venha um golpe que você não espera.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Os olhos mostram a força da alma.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O mal não é o que entra na boca do homem. O mal é o que sai dela.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "quando uma coisa evolui, evolui também tudo que está a sua volta.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Somos responsáveis por tudo que acontece neste mundo. Somos os Guerreiros da Luz. Com a força do nosso amor, de nossa vontade, podemos mudar o nosso destino, e o destino de muita gente.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A fé é uma conquista difícil, que exige combates diários para ser mantida.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Com a força de nosso amor, da nossa vontade, podemos mudar o nosso destino, e o destino de muita gente.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "As tarefas diárias jamais impediram alguém de seguir seus sonhos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Às vezes um acontecimento sem importância é capaz de transformar toda a beleza em um momento de angústia. Insistimos em ver o cisco no olho, e esquecemos as montanhas, os campos e as oliveiras.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Existem momentos na vida em que a única alternativa possível é perder o controle.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Insistimos em ver o cisco no olho, e esquecemos as montanhas, os campos e as oliveiras.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Muitas pessoas se fascinam pelos detalhes e esquecem o que procuram.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Não ofereça a Deus apenas a dor de suas penitências, ofereça também suas alegrias.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Não precisamos saber nem 'como' nem 'onde', mas existe uma pergunta que devemos fazer sempre que começamos qualquer coisa. 'Para que tenho que fazer isto?", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Não queira ser bravo, quando basta ser inteligente.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O amor é arriscado, mas sempre foi assim. Há milhares de anos as pessoas se buscam e se encontram.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O esforço é saudável e indispensável, mas sem os resultados não significa nada.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O mundo está nas mãos daqueles que tem coragem de sonhar, e correr o risco de viver seus sonhos.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O mundo se transforma e nós somos parte desta transformação. Os anjos nos guiam e nos protegem.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Os anjos se fazem notar apenas para aqueles que acreditam na sua existência, embora sempre estejam presentes.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Poucos aceitam o fardo da própria vitória, a maioria desiste dos sonhos quando eles se tornam possíveis.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quantas coisas perdemos por medo de perder.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quem interfere no destino dos outros nunca descobrirá o seu.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Só entendemos a vida e o Universo quando não procuramos explicações. Aí tudo fica claro.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Só um homem que não tem vergonha de si, é capaz de manifestar a glória de Deus.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Toda a vida do homem sobre a face da terra se resume a buscar o amor. Não importa se ele finge correr atrás de sabedoria, de dinheiro ou de poder.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O amor só descansa quando morre. Um amor vivo é um amor em conflito.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Existem coisas na vida pelas quais vale à pena lutar até o fim.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "A única chance que uma tragédia nos dá: a de reconstruir nossa vida.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Assuma o seu caminho. Mesmo que precise dar passos incertos, mesmo que saiba que pode fazer melhor o que está fazendo.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Cuidado com a solidão. Ela vicia tanto quanto as drogas.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Todas as artes divinatórias foram feitas para aconselhar o homem, jamais para prever o futuro. São excelentes conselheiras e péssimas profetizas.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Um autor escrevera que o tempo não transforma o homem, a sabedoria não transforma o homem — a única coisa que pode fazer alguém mudar de idéia é o amor", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Quando adiamos a colheita os frutos apodrecem, mas quando adiamos os problemas, eles não param de crescer.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Todos nós nos preparamos para matar dragões e terminamos sendo devorados pelas formigas dos detalhes, às quais nunca prestamos atenção.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "O poder da vontade não transforma o homem. O tempo não transforma o homem. O amor transforma.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Deus está onde O deixam entrar.", Author = "Paulo Coelho" },
            new Quote { Id = "https://pt.wikiquote.org/wiki/Paulo_Coelho", Text = "Deus sempre dá uma segunda chance aos seus filhos", Author = "Paulo Coelho" },
        };
    }
}