using System;

namespace StdbModule;

public static partial class TurkishQuotes
{
    public static class NecipFazılKısakürek
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Dâvâ, gerçek ölümsüzlüğü bulmakta.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Viyana'da Kara Mustafa'nın yenilmesi ne askerîdir, ne iktisadîdir, ne şudur, ne budur; sadece ahlâkîdir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Her felsefe mektebi, öbür mektebinin yanlışını çıkarmak için faydalıdır; kendi hakikatiyle değil...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Büyük tefekkür plânında ve büyük içtimaî sistemde milletçe zayıf olduğumuzun bilincinde olmalıyız.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Komünizm sosyalizmin azmanıdır. Komünist olmaya razı olunmadan sosyalist olunmaz!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ne mutlu Müslüman'ım diyene!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ya olun, ya ölün!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ağlayalım ve dua edelim. Duanın icabını yapalım.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Doğrudan doğruya söylüyorum: Lâiklik bize göre samimi ve hakiki bir kelime değildir. Kutup ayısını, hurma ağacının ikliminde besleyemezsin!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tek yol dine dönmek: Tek din İslâm!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Çoğu, sigâya çekilecek olsalar, komünizmi de bilmeyen, komünist bile olmaktan âciz, lâfta ilerilik heveskârı küfür yobazlarıdır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tanzimattan beri devam eden sahte inkılaplar ve bu inkılapların türettiği sahte kahramanlar, dâvamızın, müşahhas plânda baş meselesidir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Her şey Doğu'dan geldi; her şey, her şey, yani ruhumuz.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Mesele, Batı'yı anlamak. Dâvanın en nazik istikâmeti, bütün mâzi ve tarih hükümlerinin özü ve halinde bugün Doğu'nun Batı'ya karşı nasıl bir anlayış tavrı takınacağında.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Düşünmediğimizi düşünmedikçe düşünebilmekten uzak yaşayacağız.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Yalnız İslâmiyete inanıyoruz!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "O küllî şeyin adı ki İslâm, her şey onda, o da her şeyde...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İnsan olduğu için İslâm oldu; ve İslâm olduğu için insan vardır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bir kişinin herkes, herkesin de bir kişi olduğu hakikati İslâmındır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Âlemde tek adalet kaynağı, İslâm...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İslâmiyet'in kılıcı bizzat merhamettir. Hıristiyanlıktaki sun'i merhamet edebiyatı değil...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Fakat İmparatorluk o kadar cüsselidir ki, can çekişirken bile dünyayı titretmektedir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tanzimatın, olmaması değil, aksine, İslâmlık emrinde ve çok daha geniş ve köklü bir hareket şeklinde olması lâzımdı.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Giden şey İslâm, gelen şeyse hiçti.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Kanunî devrinden beri gerçek inkılâbı bekliyoruz.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Gerçek Türk tarihi henüz yazılmamıştır. Yazılabilseydi zaten mesele yoktu.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Fakat sadece ruhlarda ve düşünce çevresinde bir inkılap...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bu inkılâbın âletleri, söz ve kalem...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Çölde, devesine, kölesiyle nöbetleşe binen Reisler Reisi'nin ahlâkı. Buna muhtacız...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İslâm ahlâkı, buna muhtacız.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Biz, gerçek milliyetçiliği, geriye doğru değil, ileriye doğru, menba istikâmetinde değil, mansap istikâmetinde, tohum üstünde değil ağaç üstünde karar kılıcı bir anlayış ve görüşe bağlıyoruz.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İnsan hür değildir; hür olan, eşek veya köpek...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Hürriyet bir gâye değil, vasıtadır ve gâye bir tarafa bırakılıp vasıta gâyeleştirilemez.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bir dilde uzun, dolgun ve çok heceli kelimeler, tefekkür ve medeniyet işaretidir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ruhumuzun ırzına geçtiği sanılar Arapçayı karşılık, ruh ismet ve iffetimiz gâvurcaya karşı takdim ve teslim edilmiştir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bir milletin diliyle oynamak, onun hayatıyla oynamaktır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Yine o, hep o, yalnız o, daima o...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Gerici... O da ne kelime? Gerilerinde damgamız mı var ki gerici oluyoruz?", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Gerici kelimesi, ancak gerilerini döndürmekten başk abir hüneri olmayanlara yakışır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Hasret, vuslatın yarısıdır. İste ki olsun!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Sen yalnız düşün!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Sen, düşünmeyi düşünmekten başlayarak düşün, yeter!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Abdülhamid'i anlamak her şeyi anlamak olacaktır.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Fars tesiri korkunçtur; İslâmda en büyük kafalarla at başı, en hain bozguncu kelleleri de İranlı.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bizde heykel yoktur.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İrtica, yatağımızın başucundaki bir bardak suya karıştırılan zehirdir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ağlayabilseydiniz, anlayabilirdiniz.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ne mutlu fikir vebalılarına; ve yazıklar olsun, eşek sıhhati içinde, günübirlik hayat çayırında otlayanlara!.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ben, emekliliği olmayan ve bir kenara çekilip pineklemeye izni bulunmayan bir dâva üzerindeyim.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Hayat dayanılmaz bir ıstıraptır ve insanın bu ıstıraptan kurtulması lâzımdır. Istırap, ihtirastan doğar, istekten, arzudan... Istıraptan kurtulmanın tek çaresi ihtirastan kurtulmaktır. İhtirastan kurtulan da erer...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Yenilik dâvasında, \"devrim\" isimli nice hareketler vardır ki, beş aylıkken düşürülmüş kavanoz çocukları gibi sadece ölünün yenisidirler.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tek yol dine dönmek.. Tek din İslâm!.. Mânasını yıktığımız ve yaktığımız cami.. Batı O'nun eşiğinde.. Ya biz neredeyiz?", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İnsan başıyla fare kafasını ayıran tek hassa, fikir öfkesidir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Allah, ızdırabını çektirmediği şeyin, nimetini vermez.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Arı bal yapar, fakat balı izah edemez. Ağaçtan düşen elma da arz cazibesi kanunundan habersizdir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Bir kız öğrenciyi, başını örttüğü için tahsil hakkından mahrum etmek, İstiklâl Savaşı başlarında ve Maraş'ta, düşmanlar tarafından başörtüsü çıkarılıp düşürüldüğü için başlayan millî şahlanışın ruhuna tükürmektir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Biz şiiri iman için bilmişiz; ve bu mihrak bilgiyi, her bilginin geçtiği binbir yol ağzı biliyoruz.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Çile kapısından erişilecek dünyayı bilseydin, yatağını yorganını satardın.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Devler gibi eserler bırakmak için, karıncalar gibi çalışmak lazım.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Demokrasi, kendini çölde hayal edenlerin serabıdır. Yaşanmaya değer hayatı bul ve ölümsüzlüğe geç!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Dinin olmadığı yerde hiçbir şey yoktur; yokluk bile yok... Şiir ve san'atsa hiç yok...", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Ey Türk ruhumun atomu. Çatla ve idealinin baş harflerini göklere yaz!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İdrâk, idrâksizliğin idrâkini idrâktır!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "İnsan başiyle fare kafasını birbirinden ayıran tek hassa, fikir öfkesidir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Kökünü beğenmeyen dal ve dalını beğenmeyen meyve olgunlaşmadan çürür.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Kendi kendimizin altında kalmamalıyız ki cemiyetin üstüne çıkalım.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Mâsum, küçücük bir taşın beresi üzerine flaster yapıştırmak ne demek? Haklı, koca bir güllenin yere sereceği leşinin üstünü örtecek kanlı kefenden ne haber?", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Şiirde gaye, kökte Allah ve mutlak hakikat olarak, dalda sırrilik ve remziliktir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Şiirde baş unsur, fikirle hissin ara çizgisi üzerinde, duygulaşmış düşüncelerdir.", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tereddüt edersen bacakların seni taşımaz. Yürüyeceğim de, bas ve yürü!", Author = "Necip Fazıl Kısakürek" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Necip_Fazıl_Kısakürek", Text = "Tomurcuk derdinde olmayan ağaç, odundur.", Author = "Necip Fazıl Kısakürek" },
        };
    }
}