using System;

namespace StdbModule;

public static partial class TurkishQuotes
{
    public static class OrhanPamuk
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bu çirkin ve iğrenç dünyada ancak aptallar mutlu olabilir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Tutkularım var benim. Başkalarına benzemiyorum. Cesaretim var!", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Ben zenginlerden hoşlanmıyor değilim! Ben zenginlerin kaba, kültürsüz, cahil olmalarına, memleketi, inkılapları, böyle şeyleri düşünmemelerine karşıyım!", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Ahlaksız bir insan olmaktan yalnızca kendi irademi ve aklımı kullanarak kurtulacağımı anladım.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Ama mutsuzluk gerçek bir intihar nedeni olsaydı Türkiye' deki kadınların yarısı intihar ederdi...", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "İnsan bir başkasının sesini ne kadar duyabilir içinde?", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Mutluluğun bu kadarı bana fazla geliyor ve mutlaka bir kötülük olacağını da seziyorum.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Dinle beni: Hayat ilkeler için değil, mutlu olmak için yaşanır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Ben ülkemin kalkınmasını, insanlarının özgürleşmesini, modernleşmesini bir çocuk gibi iyi niyetlerle istedim hep.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Sana kızmıyorum, çünkü, bütün iyi insanlar gibi, kötülüğünü farkında olmadan yapıyorsun…", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Aslında kimse, onu yaşarken hayatının en mutlu anını yaşadığını bilmez.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Mutluluk, insanın sevdiği kişiye yakın olmasıdır yalnızca. Ona hemen sahip olmamız gerekmez.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bana yalan söylemeni isterdim aslında... Çünkü insan ancak kaybetmekten çok korktuğu bir şey için yalan söyler.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Her akıllı insan hayatın güzel bir şey olduğunu, amacının da mutlu olmak olduğunu bilir,” dedi babam üç güzel kızı seyrederken. “Ama yalnızca aptallar mutlu olur. Nasıl izah edeceğiz bunu?”", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Yazar olmak, içe kapanmak demektir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bizi yazmaya iten şey, genellikle kendi içimizdeki eksikliktir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Kendimize özgü olanı bulmak için önce başkalarını okumalıyız.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bavul, yazarın zihnindeki yalnızlık ve merak dolu dünyayı taşır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bir insanın iç sesiyle konuşması, edebiyatın ta kendisidir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Yazmak, derinleşmeyi ve kendi kendimizle hesaplaşmayı gerektirir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Yazarken beni düşündüren ilk şey, kimse beni okumazsa ne olacak endişesidir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bir kitap yazmak, yavaşça kendini tanımaktır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Edebiyat, çocukluğumuza geri dönmenin en içten yollarından biridir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Bazen bir kelime, binlerce sayfadan daha fazla şey anlatır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Benim için yazar olmak demek, içimizde taşıdığımız, en fazla taşıdığımızı biraz bildiğimiz gizli yaralarımızın üzerinde durmak, onları sabırla keşfetmek, tanımak, iyice ortaya çıkarmak ve bu yaraları ve acıları yazımızın ve kimliğimizin bilinçle sahiplendiğimiz bir parçası haline getirmektir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Aslında en iyi aşk, değil tanımak, hiç görmediğin kişiye duyulan aşktır. Körler iyi âşık olurlar mesela.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Benim için yazarlığın sırrı, nereden geleceği hiç belli olmayan ilhamda değil, inat ve sabırdadır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Cebinizde, çantanızda bir kitap taşımak; özellikle mutsuzluk zamanlarınızca cebinizde, çantanızda sizi mutlu edecek bir öteki dünya taşımak demektir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "İçimden geldiği için yazıyorum! Başkaları gibi normal bir iş yapamadığım için yazıyorum. Benim yazdığım gibi kitaplar yazılsın da okuyayım diye yazıyorum. Hepinize, herkese çok çok kızdığım için yazıyorum. Bir odada bütün gün oturup yazmak çok hoşuma gittiği için yazıyorum. Ben, ötekiler, hepimiz, bizler İstanbul’da, Türkiye’de nasıl bir hayat yaşadık, yaşıyoruz, bütün dünya bilsin diye yazıyorum. Kâğıdın, kalemin, mürekkebin kokusunu sevdiğim için yazıyorum. Edebiyata, roman sanatına her şeyden çok inandığım için yazıyorum. Bir alışkanlık ve tutku olduğu için yazıyorum. Unutulmaktan korktuğum için yazıyorum. Getirdiği şöhret ve ilgiden hoşlandığım için yazıyorum. Yalnız kalmak için yazıyorum. Hepinize, herkese neden o kadar çok çok kızdığımı belki anlarım diye yazıyorum. Okunmaktan hoşlandığım için yazıyorum. Bir kere başladığım şu romanı, bu yazıyı, şu sayfayı artık bitireyim diye yazıyorum. Herkes benden bunu bekliyor diye yazıyorum. Kütüphanelerin ölümsüzlüğüne ve kitaplarımın raflarda duruşuna çocukça inandığım için yazıyorum. Hayat, dünya, her şey inanılmayacak kadar güzel ve şaşırtıcı olduğu için yazıyorum. Hayatın bütün bu güzelliğini ve zenginliğini kelimelere geçirmek zevkli olduğu için yazıyorum. Hikâye anlatmak için değil, hikâye kurmak için yazıyorum. Hep gidilecek bir yer varmış ve oraya tıpkı bir rüyadaki gibi bir türlü gidemiyormuşum duygusundan kurtulmak için yazıyorum. Bir türlü mutlu olamadığım için yazıyorum. Mutlu olmak için yazıyorum...", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Ödül alırken de söyledim; Ben boş sayfaya yavaş yavaş yeni kelimeler ekleyerek masamda oturdukça günler, aylar, yıllar geçtikçe, kendime yeni bir âlem kurduğumu, kendi içimdeki bir başka insanı, tıpkı bir köprüyü ya da bir kubbeyi taş taş kuran biri gibi ortaya çıkardığımı hissederdim. Biz yazarların taşları kelimelerdir. Onları elleyerek, birbirleriyle ilişkilerini hissederek, bazen uzaktan bakıp seyrederek, bazen parmaklarımızla ve kalemimizin ucuyla sanki onları okşayarak ve ağırlıklarını tartarak kelimeleri yerleştire yerleştire, yıllarca inatla, sabırla ve umutla yeni dünyalar kurarız. Türkçe'deki o güzel deyiş, iğneyle kuyu kazmak bana sanki yazarlar için söylenmiş gibi gelir.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Doğu'da olduğum belli değil mi… Dünyanın neresinde olursa olsun, ister Doğu'da ister Batı'da, cemaatlerinden kopup kendilerini kitaplarla bir odaya kapatan yazarlar geleneğinin bir parçası olarak görmek isterim kendimi. Benim için hakiki edebiyatın başladığı yer kitaplarla kendini bir odaya kapatan adamdır.", Author = "Orhan Pamuk" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Orhan_Pamuk", Text = "Anlamıyorsunuz! Bakıyorsunuz, ama görmüyorsunuz; düşünüyorsunuz, ama bilmiyorsunuz!", Author = "Orhan Pamuk" },
        };
    }
}