using System;

namespace StdbModule;

public static partial class TurkishQuotes
{
    public static class PeyamiSafa
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Tecrübe, yaşlanarak değil, yaşayarak kazanılır; ve zaman insanları değil, armutları olgunlaştırır.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Aşkın tam bir tarifi yapılamaz. Şiir de böyledir. Yapılmış ve yapılacak tariflerden her biri, denizden alınmış bir kova suya benzer. Hiç şüphesiz bu, deniz suyudur, fakat deniz değildir. Aşkı denize, tarifi de kovaya benzetirseniz elde edilen şey, aşkın bir halini izahtan ibaret kalır. Enginsiz, kıyısız, renksiz, dalgasız, derinliksiz bir izah.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Bekârları çoğalan cemiyet, gizli bir anarşi geçiriyordur. Ya büyük bir inkılâba, ya inhitata gidecektir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Batıda hükümet sansürü yerine seviye sansürü vardır. Bu seviyenin olmadığı memleketlerde kanun düşünceyi hudutlandırır. Düşünce hürriyeti isteyenler daha evvel düşünce seviyesinin yükselmesine hizmet etmelidirler.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Otobiyografik romanlar, yaratma hürriyetimizi kısıtlar. Orada biz sayısız imkân ve ihtimallerden bazılarını tercih hürriyetini kaybeder, bir tanesi üzerinde billurlaşmaya mecbur kalırız.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Ben iki yaşında babasız kaldım. Bütün çocukluğum ve gençliğim korkunç bir hastalığa ve fakirliğe karşı mücadele içinde geçti. Kimsesiz, sıhhatsiz, parasız ve talihsiz kaldım. Orta sekizden yukarı okul görmedim. Hastalık, cehalet ve sefalet ejderleriyle boğuştum.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Keriman Halis'in tüm dünyaya ispat ettiği şey, yalnız ferdi bir güzellikten ibaret değildir. O, düne kadar kafes arkasında yalnız 'insan yumurtlamaya' yarar, acayip bir kümes hayvanı zannedilen Türk kadını ile bugünün beynelmilel hareketlerine karışan, zeki ve cevval bakışlı Türk kızının farkını meydana çıkardı. Bu olay Türkiye'nin geçirdiği inkılap hakkında yazılmış ve yazılacak kitaplardan ziyade fikir vermek kudretini haizdir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Öğleye doğru muayene odasının önü doldu. Sıralarda oturacak yer kalmadığı için yeni gelenler ayakta durdular ve anneler, hasta çocuklarını dizlerine oturtabilmek için duvar diplerine çömeldiler.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Bizden uzaklaşmadıkça bize görünmeyen sıhhat, alışkanlığın verdiği hissizlikle, sağlamların şuurundan kaçıp nasıl ve nereye saklanıyor? Onu ben görüyorum, çünkü benden uzak.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Dünyanın hiçbir Nüzhet'i yalan söylememelidir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "...Ve bir yalan söylendiği zaman insanların değil, eşyanın bile buna nasıl tahammül ettiğine şaşırıyordum. Yalana her şey isyan etmelidir. Eşya bile: Damlardan kiremitler uçmalıdır, ağaçlar köklerinden sökülüp havada bir saniye içinde toz duman olmalıdır, camlar kırılmalıdır, hattâ yıldızlar düşüp gökyüzünde bin parçaya ayrılmalıdır.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "En basit içtimaî dâvaları anlamayacak kadar yabancı tesirler altında şahsiyetlerini kaybeden bu insanlarla münakaşaya mecbur olmanın küçüklüğünden muzdariptim.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Meçhul ümitlere inanmadığım an, beni kurtaracak şeyin ne olduğunu bilmek istiyorum. Ümit etmek bile az. Emin olmak ihtiyacı. Yalancı istikbalin şüpheli vaatlerine değil, teminatına ve senedine ihtiyacım var.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Felâketimizi başka biriyle taksim etmek saadettir fakat annelerle değil, annelerle değil. Annelere anlatılan kederler taksim değil zarbedilmiş (dövülmüş) olur.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Asır tereddüt ediyor.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Ben esrarlıyım, ben karanlığım diye bar bar bağıran şeyin esrarı kalır mı?", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Bu kaçan benliklerimizi birbirimizde aramak tecessüsü olmasaydı bir saniye bile konuşabilir miydik?", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Evlenmek insanı yalnızlıktan kurtarmaz, belki daha müthiş bir yalnızlığa atar.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Ben'in Allah'ta yok olmaya koşması azizleri, insanlıkta yok olmaya koşması dâhileri, millette yok olmaya koşması kahramanları yaratmıştır.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Delilik şüphesiz aptallıktan iyidir. Delilik var olmuş bir zekanın yok oluşudur; aptallık, var olmamış bir zekanın var olmamaya devam edişidir. Deliliğin hiç olmazsa mazisi şanlı. Aptallığın şerefli bir tarihi bile yok...", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Âşıklara haber vermek isterim: Kalbin tüm meseleleri yalnız kalpte halledilir, çünkü bir hissin hakkından ancak başka bir his gelir. Ümitsiz bir aşkın panzehiri ise nefrettir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Halk sevginin veya alâkanın objesini ortadan kaldırmakla meseleyi kestirme halledeceğini sanır ve sevdiğini öldürür. Biz meselenin dışarıda değil, içimizde halledilebileceğini daha çok anlarız. Çünkü dâva yalnız sevgili ile kendimiz arasında değil, hattâ senin meselende olduğu gibi hiç değil, asıl dâva kendimizle kendimiz arasındadır. Sevgiliyi dışarıda öldürmek neye yarar? İçimizde yaşadığı müddetçe, biz sadece bir şeklin katili olmakla kalırız. Onu içimizde öldürebilmeliyiz. Unutmak budur. Tereddüdün lüzumsuz. Rezil etmek veya öldürmek, yani mânen veya maddeten öldürmek, verdiği zafer gururu ne olursa olsun, meseleyi halletmez.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Her sıkıntı bir isyan hazırlığıdır. Ruhta başlayan bu hazırlık vücudun hastalanması şeklinde organik bir isyana çevrilir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Sevgi ile nefret arasında çok ince bir çizgi vardır. Birisinden nefret ediyorsanız ve bir gün onu yenemeyeceğinizi anladığınız zaman onu sevmeye başlarsınız. Ve yine birisini seviyorsanız ve bir gün onu yenebileceğinizi düşündüğünüz zaman ondan nefret etmeye başlarsınız.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "İnsanın kandırdığı en büyük budala kendisidir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "İki tarafta da arzuyu gurura hesap vermeye çağıran iç muhasebe anları olmasaydı, kendi kendini yiyen aşkın işkenceleri ne kadar azalırdı.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Kendi kendimden nefretimin çerçevelediği ve çirkinleştirdiği bir dünyada yalnızım", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Her hastalık önce ruhta başlayıp sonra vücuda sirayet etmiş bir isyandır. İnsanda hastalık kaderin aksiliklerine karşı bir intibaksızlıktır. Simeranya'da her türlü hastalığın âmilini evvela hastanın hayatında ve ruhunda ararlar.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Septisemi, verem, kanser hep boş lakırdı. İnsanı öldüren illet: SIKINTI. Öteki hastalıklar bunların görünüşleridir.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Ev kadınlığını hizmetçilik sandığı için kendisini Üniversiteye atan bir kızın kültüründen de, ahlakından da bu memlekete hiçbir hayır gelmez.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Gerçek aşk sevgilinin bütün kusurlarını görür ve sever... Aşk inanmanın şiiridir. Aşk şüphe etmez. Aşk kıskanmaz. Aşk iğrenmez. Aşk çirkin bulmaz. Aşk küçümsemez. Aşk bencilliğin, kendini sevgiliden daha üstün görmenin, buhranın ve kötümserliğin tam zıddıdır. Aşk istemez, yalnız verir. Aşk bir mücadele değil âhenktir... Aşk bunun için ilâhidir... Gerçek aşkın bir tek değişmez vasfı vardır: Tükenmezlik... Aşk engellere ve hücuma uğradıkça kuvvetlenen ihtirastır. Rakipsizdir, yenilmez... Aşk kendi saadetini bir başkasınınkine feda etmektir... Mârifet bize yâr olmayan sevgiliyi kalbimizin içinde öldürmek! İşte en haklı, en mâsum, en kudretli ve en muhteşem cinayet.", Author = "Peyami Safa" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Peyami_Safa", Text = "Kadın yüzünde bir neşter izi kadar çirkin duran çizgilerin ve buruşukların çoğu, erkek yüzünde, dışarıdan vurulan bir bıçağın değil, kafanın içinde kaynayan bir zekanın çalışma izleri olduğu için güzeldir.", Author = "Peyami Safa" },
        };
    }
}