using System;

namespace StdbModule;

public static partial class TurkishQuotes
{
    public static class SaitFaikAbasıyanık
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Eğer doğduğun zaman Havra kapısına bırakırlarsa Yahudi olursun, Cami kapısına bırakırlarsa Müslüman, Kilise kapısına bırakırlarsa Hristiyan olursun.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Seyahatler çekiyor içim.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Kuşları boğdular, çimenleri söktüler, yollar çamur içinde kaldı.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben bir acayip oldum. Gözüm kimseyi görmüyor, kimsenin kapımı çalmasını istemiyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben bayrakları değil insanları severim.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Yeniden doğulmaz. Doğsan bile ne olacak?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "İnsanı dolu günleri değil, boş günleri dolduruyor...", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben hiç gülmedim demem; güldüm. Güldüm ama şöyle içten, candan gülmedim.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ölüm var arkadaş, ölüm. Şu köşkün sahibi de ölecek, şu horoz da.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ölüm bildiğimiz kadar korkunç bir şey değildi. Yalnız biraz soğuktu o kadar..", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Eksikliğimi beni kaybettiğinde anlayacaksın.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Biz kuşları ve yeşillikleri çok gördük. Sizin için kötü olacak. Benden hikâyesi.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "İyi adam pişman olan adamdır.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Milyonluk şehirlerde de yaşasa, insanoğlunun içinde yalnızlık, kendi içine çekilme, sinme günleri doludur.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Kendi peşimi bile bıraktım.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben kendim, kaç defa, dakikalarca, yol soracak adam seçemediğimi hatırlıyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Doğru, yalnız hayalle geçiniyorum; ben yalnız hayal kuruyorum...", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "O güzel pişmanlık hissi çocuklukta kaldı. Şimdi nerede?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Dünyayı güzellik kurtaracak, bir insanı sevmekle başlayacak her şey.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Sevmiş sevilmemiştim.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Yalnızlık dünyayı doldurmuş. Sevmek bir insanı sevmekle başlar her şey. Burada her şey bir insanı sevmekle bitiyor.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Çünkü unutulmayacak yalnız o kaldı.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "İnsanoğlunu aldatmak bir zeka sayılmaz ki. Bence zeki adam çabuk kanan adamdır.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Şerefli bir milletin, demokrasi ayıbı olmaz.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Yazmasam deli olacaktım.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Okumuş yazmış adam öğüt vermez, adamı anlar.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Soğan ekmek yalnız şehirli midesine değil köylü midesine'de dokunabilir ve dokunmaktadır..", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ölümün karşısında, ne yapsak, muvaffak olmuş bir aktörden farkımız olmayacak!", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Bütün insanlar birbirine aşağı yukarı benzemez mi?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ama artık benim sana kadar yetiştirecek ne sesim, ne halim kalmıştı.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Sevmekten korkuyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Şehrin dışına çıkmak kendi kendinden kurtulmak gibi bir şey. Hatıralarımız, aşklarımız, dostluklarımız, hıyanetlerimiz hep şehrin içinde kaldı.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Bütün ümit yarın sabahta.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Karanlıktan, riyadan, zulümden, hürriyetsizlikten korkar gibi ürküyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Her insandan korkuyorum. Kimdir bu sokakları dolduran adamlar? Bu koca şehir, ne kadar birbirine yabancı insanlarla dolu.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Kitaplar, bir zamanlar bana, insanları sevmek lazım geldiğini, insanları sevince tabiatın, tabiatı sevince dünyanın sevileceğini, oradan yaşama sevinci duyulacağını öğretmişlerdi.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Hep kötüler mi var? Dört bir yanımız sefalet, hastalıkla mı çevrili? Her gördüğümüz zalim, katil, egoist, hasut, kindar, yarı deli, ahlaksız mı?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Bizim için değil ama, çocuklar, sizin için kötü olacak. Biz kuşları ve yeşilleri çok gördük. Sizin için kötü olacak.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Fakat toprağın üstünde koşan ,onun üstünde beş on para kazanmak kaygısıyla dönüp dolaşan insanlar ne tuhaf mahluklardı..", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Bu dünyadan hiçbir iş yapmadan göçüp gitmek de fena bir şey.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Kaç para eder! Gözümde, milyonu olsa da, kalp para ile metelik etmez.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Denize bir dakika durup bakmaya vakitleri olmadığını söyleyen bu insanlar ne zevksiz mahluklardı..", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben ne istediğini adamakıllı bilen birisi değilim. Yalnız bildiğim bir şey varsa o da, başkaları iyi şeyler yaparsa derhal anlıyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben görmeden severim bahçeleri, insanları, evleri.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ah bu insan yüzleri. Her şeyimizi bağladığımız, durmadan yanıldığımız.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "İçimde muhakkak bir yer paramparça olmuştu ki, ağlayamıyordum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Düşünmeye başlayalı beri bir gün sarhoş olmadan gülmedik ki.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ne kadar üstü başı düzgünler, suratı ciddiler, hali azametliler içinde kalmışım ki bir türlü hikayeme yanaşamıyorum.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Sonra oturup hüngür hüngür ağlasam. Boş geçirdiğim, bağırmadığım, sustuğum günlere.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Hepimiz, sırtımızda ve elbiselerimizin altında, gözlerimizin içinde müstakbel ölü gezdirmiyor muyduk?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Aklım ermiyor. Birbirini küçük görmeye, boğazlaşmaya, kandırmaya mı? Nasıl birbirinden bu kadar ayrı, birbirini bu kadar tanımayan insanlar bir şehirde yaşıyor?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ben hikayeciyim diye sizden ayrı şeyler düşünecek değilim. Sizin düşündüklerinizden başka bir şey de düşünemem. O halde bu adamın hikayesi ne olabilir? Sakın benden büyük vakalar beklemeyin, n'olur?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Şu karşıki sandalı görüyor musun? Bakın sahile yaklaşıyor. Onu yürüten şey nedir? Kürekleri değil mi? Ya şu uçan martılar! Kanatları yolunsa artık uçabilir mi? Düşünce de böyledir.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Dört duvar arasına kapatılmak istenirse kanatsız kuş, küreksiz sandal oluverir ve bütün manasını kaybeder.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Edebi eserler, insanı yeni ve mesut, başka iyi ve güzel bir dünyaya götürmeye yardım etmiyorlarsa neye yarar?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Ne kadar kaçmak ve uzaklaşmak arzusu ile dolu isem, o kadar da bağlanmak, kalmak, bağdaş kurup oturmak istiyorum. Sonra? Sonra?", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Her şeyin sonrasını düşünürsen en sonrası günün birinde son nefestir.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "[[Şiir]] olmayan yerde [[insan]] sevgisi de olmaz. İnsanı insana ancak şiir sevdirir. Şiir, insanı insana yaklaştıran şeydir.", Author = "Sait Faik Abasıyanık" },
            new Quote { Id = "https://tr.wikiquote.org/wiki/Sait_Faik_Abasıyanık", Text = "Kimseler âşık değil mi bu şehirde? Kimseler, bir meydanın kanepesinde kimseyi beklemeyecek mi, yüzünü bir dakika görmek için kimsenin?", Author = "Sait Faik Abasıyanık" },
        };
    }
}