using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class AAMilne
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Tell the innocent visitor from another world that two people were killed at Serajevo, and that the best that Europe could do about it was to kill eleven million more.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I wrote somewhere once that the third-rate mind was only happy when it was thinking with the majority, the second-rate mind was only happy when it was thinking with the minority, and the first-rate mind was only happy when it was thinking.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Here is Edward Bear, coming downstairs now, bump, bump, bump, on the back of his head, behind Christopher Robin. It is, as far as he knows, the only way of coming downstairs, but sometimes he feels that there really is another way, if only he could stop bumping for a moment and think about it.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "If there's a buzzing-noise, somebody's buzzing-noise, and the only reason for making a buzzing-noise that I know of is because you're a bee. And the only reason for being a bee that I know of is making honey. And the only reason for making honey is so I can eat it.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I have been Foolish and Deluded, and I am a Bear of No Brain at All.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "These notices had been written by Christopher Robin, who was the only one in the forest who could spell; for Owl, wise though he was in many ways, able to read and write and spell his own name WOL, yet somehow went all to pieces over delicate words like MEASLES and BUTTEREDTOAST.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "It is hard to be brave, said Piglet, sniffing slightly, when you're only a Very Small Animal.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "It's a little Anxious, he said to himself, to be a Very Small Animal Entirely Surrounded by Water.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "How sweet to be a cloud Floating in the blue.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Let's pretend it isn't, said Rabbit, and see what happens.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Isn't it funny How a bear likes honey? Buzz! Buzz! Buzz! I wonder why he does?", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "There are some people who begin the Zoo at the beginning, called WAYIN, and walk as quickly as they can past every cage until they get to the one called WAYOUT, but the nicest people go straight to the animal they love the most, and stay there.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "We can't all and some of us don't. That's all there is to it.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "You can't stay in your corner of the forest waiting for others to come to you. You have to go to them sometimes.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "When I was One, I had just begun. When I was Two, I was nearly new. When I was Three I was hardly me. When I was Four, I was not much more. When I was Five, I was just alive. But now I am Six, I'm as clever as clever, So I think I'll be six now for ever and ever.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "When we asked Pooh what the opposite of an Introduction was, he said \"The what of a what?\" which didn't help us as much as we had hoped, but luckily Owl kept his head and told us that the Opposite of an Introduction, my dear Pooh, was a Contradiction; and, as he is very good at long words, I am sure that that's what it is.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "The more he looked inside the more Piglet wasn't there.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Nearly eleven o'clock, said Pooh happily. You're just in time for a little smackerel of something.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Shall I look too? said Pooh, who was beginning to feel a little eleven o'clockish. And he found a small tin of condensed milk, and something seemed to tell him that Tiggers didn't like this, so he took it into a corner by itself, and went with it to see that nobody interrupted it.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Piglet looked up, and looked away again. And he felt so Foolish and Uncomfortable that he had almost decided to run away to Sea and be a Sailor, when suddenly he saw something.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "One day when Pooh was thinking, he thought he would go and see Eeyore, because he hadn't seen him since yesterday.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Yes, they're very good flyers, Tiggers are. Strornry good flyers.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Piglet took Pooh's arm, in case Pooh was frightened.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "And he respects Owl, because you can't help respecting anyone who can spell Tuesday, even if he doesn't spell it right; but spelling isn't everything. There are days when spelling Tuesday simply doesn't count.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "By the time it came to the edge of the Forest the stream had grown up, so that it was almost a river, and, being grown-up, it did not run and jump and sparkle along as it used to do when it was younger, but moved more slowly. For it knew now where it was going, and it said to itself, \"There is no hurry. We shall get there some day.\"", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I've got a sort of idea, said Pooh at last, but I don't suppose it's a very good one. I don't suppose it is either, said Eeyore.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "when you are a Bear of Very Little Brain, and you Think of Things, you find sometimes that a Thing which seemed very Thingish inside you is quite different when it gets out into the open and has other people looking at it.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Pooh looked at his two paws. He knew that one of them was the right, and he knew that when you had decided which one of them was the right, then the other one was the left, but he never could remember how to begin.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Lucky we know the forest so well, or we might get lost, said Rabbit half an hour later, and he gave the careless laugh which you give when you know the Forest so well that you can't get lost. Piglet sidled up to Pooh from behind. Pooh! he whispered. Yes, Piglet? Nothing, said Piglet, taking Pooh's paw. I just wanted to be sure of you.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I don't see much sense in that, said Rabbit. No, said Pooh humbly, there isn't. But there was going to be when I began it. It's just that something happened to it on the way.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "You only blinched inside, said Pooh, and that's the bravest way for a Very Small Animal not to blinch that there is.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Well, said Pooh, what I like best— and then he had to stop and think. Because although Eating Honey was a very good thing to do, there was a moment just before you began to eat it which was better than when you were, but he didn't know what it was called.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I'm not going to do just nothing anymore. You mean never again? Well, not so much. They don't let you.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "I shouldn't be surprised if it hailed a good deal tomorrow, Eeyore was saying. Blizzards and what-not. Being fine today doesn't mean anything. It has no sig - what's that word? Well, it has none of that. It's just a small piece of weather.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "If I plant a honeycomb outside my house, then it will grow up into a beehive.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "Then Christopher Robin and Winnie the Pooh walked hand in hand down the forest path and they said goodbye. So they went off together. But wherever they go, and whatever happens to them along the way, in that enchanted place on the top of the forest a little boy and his bear will always be playing.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "That's what Jagular's always do, said Pooh, much interested. They call 'Help! Help!' and then when you look up, they'll drop on you.", Author = "A. A. Milne" },
            new Quote { Id = "https://en.wikiquote.org/wiki/A._A._Milne", Text = "They wanted to come in after the pounds, explained Pooh, so I let them. It's the best way to write poetry, letting things come.", Author = "A. A. Milne" },
        };
    }
}