using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class AbrahamLincoln
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Those who deny freedom to others deserve it not for themselves.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "America will never be destroyed from the outside. If we falter and lose our freedoms, it will be because we destroyed ourselves.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Upon the subject of education, not presuming to dictate any plan or system respecting it, I can only say that I view it as the most important subject which we as a people can be engaged in.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Every man is said to have his peculiar ambition. Whether it be true or not, I can say, for one, that I have no other so great as that of being truly esteemed of my fellow-men, by rendering myself worthy of their esteem.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "These capitalists generally act harmoniously and in concert to fleece the people, and now that they have got into a quarrel with themselves, we are called upon to appropriate the people's money to settle the quarrel.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "I can never be satisfied with anyone who would be blockhead enough to have me.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The probability that we may fall in the struggle ought not to deter us from the support of a cause we believe to be just; it shall not deter me.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Let every American, every lover of liberty, every well-wisher to his posterity swear by the blood of the Revolution never to violate in the least particular the laws of the country, and never to tolerate their violation by others.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "When I so pressingly urge a strict observance of all the laws, let me not be understood as saying there are no bad laws, or that grievances may not arise for the redress of which no legal provisions have been made.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "There is no grievance that is a fit object of redress by mob law. In any case that arises, one of two positions is necessarily true; that is, the thing is right within itself, or it is wrong, and therefore proper to be prohibited by legal enactments.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "We hope all danger may be overcome; but to conclude that no danger may ever arise would itself be extremely dangerous.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "It is to deny, what the history of the world tells us is true, to suppose that men of ambition and talents will not continue to spring up amongst us.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Towering genius disdains a beaten path. It seeks regions hitherto unexplored.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Passion has helped us; but can do so no more. It will in future be our enemy. Reason, cold, calculating, unimpassioned reason, must furnish all the materials for our future support and defence.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "If what I feel were equally distributed to the whole human family, there would not be one cheerful face on the earth.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "It has long been recognized that the problems with alcohol relate not to the use of a bad thing, but to the abuse of a good thing.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The abandonment of the protective policy by the American Government, must result in the increase of both useless labour, and idleness; and so, in proportion, must produce want and ruin among our people.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "It has so happened in all ages of the world, that some have laboured, and others have, without labour, enjoyed a large proportion of the fruits. This is wrong, and should not continue.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "He who makes an assertion without knowing whether it is true or false, is guilty of falsehood; and the accidental truth of the assertion, does not justify or excuse him.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Any people anywhere being inclined and having the power have the right to rise up and shake off the existing government, and form a new one that suits them better.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Military glory, - that attractive rainbow that rises in showers of blood.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Allow the President to invade a neighboring nation, whenever he shall deem it necessary to repel an invasion, and you allow him to do so, whenever he may choose to say he deems it necessary for such purpose, and you allow him to make war at pleasure.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "In law it is a good policy never to plead what you need not, lest you oblige yourself to prove what you cannot.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The true rule, in determining to embrace, or reject any thing, is not whether it have any evil in it; but whether it have more of evil, than of good.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Determine that the thing can and shall be done, and then we shall find the way.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The way for a young man to rise, is to improve himself every way he can, never suspecting that any body wishes to hinder him.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The better part of one's life consists of his friendships.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "My childhood's home I see again, and sadden with the view; and still, as memory crowds my brain, there's pleasure in it too.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "As leaving some grand waterfall, we, lingering, list its roar - so memory will hallow all we've known, but know no more.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "I range the fields with pensive tread, and pace the hollow rooms; and feel (companion of the dead) I'm living in the tombs.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Leave nothing for to-morrow which can be done to-day. Never let your correspondence fall behind.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Discourage litigation. Persuade your neighbors to compromise whenever you can. Point out to them how the nominal winner is often a real loser - in fees, expenses, and waste of time.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Resolve to be honest at all events; and if in your own judgment you cannot be an honest lawyer, resolve to be honest without being a lawyer.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "You say A. is white, and B. is black. It is color, then; the lighter, having the right to enslave the darker? Take care.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The legitimate object of government, is to do for a community of people, whatever they need to have done, but can not do, at all, or can not, so well do, for themselves.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "The Autocrat of all the Russias will resign his crown, and proclaim his subjects free republicans sooner than will our American masters voluntarily give up their slaves.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Always bear in mind that your own resolution to succeed, is more important than any other one thing.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "We live in the midst of alarms; anxiety beclouds the future; we expect some new disaster with each newspaper we read.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Don't interfere with anything in the Constitution. That must be maintained, for it is the only safeguard of our liberties.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Our government rests in public opinion. Whoever can change public opinion, can change the government, practically just so much.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "As I would not be a slave, so I would not be a master. This expresses my idea of democracy.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Will springs from the two elements of moral sense and self-interest.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "In my poor, lean lank face nobody has ever seen that any cabbages were sprouting.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "All I ask for the negro is that if you not like him, let him alone. If God gave him but little let him enjoy.", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "What constitutes the bulwark of our own liberty and independence? It is not our frowning battlements, our bristling sea coasts, the guns of our war steamers, or the strength our gallant and disciplined army?", Author = "Abraham Lincoln" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Abraham_Lincoln", Text = "Our defense is in the preservation of the spirit which prizes liberty as the heritage of all men, in all lands, everywhere.", Author = "Abraham Lincoln" },
        };
    }
}