using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class AlbertCamus
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Do not wait for the Last Judgment. It takes place every day.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The realization that life is absurd cannot be an end, but only a beginning.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Man cannot do without beauty, and this is what our era pretends to want to disregard.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "In the depths of winter, I finally learned that within me there lay an invincible summer.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "A living man can be enslaved and reduced to the historic condition of an object. But if he dies in refusing to be enslaved, he reaffirms the existence of another kind of human nature which refuses to be classified as an object.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Knowing that certain nights whose sweetness lingers will keep returning to the earth and sea after we are gone, yes, this helps us to die.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "We always deceive ourselves twice about the people we love — first to their advantage, then to their disadvantage.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Without beauty, love, or danger it would be almost easy to live.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "We have exiled beauty; the Greeks took up arms for her.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "We turn our backs on nature; we are ashamed of beauty. Our wretched tragedies have a smell of the office clinging to them, and the blood that trickles from them is the color of printer's ink.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Mistaken ideas always end in bloodshed, but in every case it is someone else's blood. That is why some of our thinkers feel free to say just about anything.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The only great spirit of our time.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "One does not decide the truth of a thought according to whether it is right-wing or left-wing.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "With rebellion, awareness is born.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There is not love of life without despair about life.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Accepting the absurdity of everything around us is one step, a necessary experience: it should not become a dead end. It arouses a revolt that can become fruitful.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Autumn is a second Spring when every leaf is a flower.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "All I know most surely about morality and obligations, I owe to football.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "If there is a sin against life, it consists perhaps not so much in despairing of life as in hoping for another life and in eluding the implacable grandeur of this life.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The opposite of an idealist is too often a man without love.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Happiness, too, is a long patience.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Having money is a way of being free of money.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "It takes time to live. Like any work of art, life needs to be thought about.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The opposite of an idealist is too often a man without love.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Fate is not in man but around him.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Mother died today. Or maybe yesterday; I can't be sure.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I was assailed by memories of a life that wasn't mine anymore, but one in which I'd found the simplest and most lasting joys.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Since we're all going to die, it's obvious that when and how don't matter.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I may not have been sure about what really did interest me, but I was absolutely sure about what didn't.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I had only a little time left and I didn't want to waste it on God.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Everybody was privileged. There were only privileged people.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I, too, felt ready to start life all over again. It was as if that great rush of anger had washed me clean, emptied me of hope, and, gazing up at the dark sky spangled with its signs and stars, for the first time, the first, I laid my heart open to the benign indifference of the universe. To feel it so like myself, indeed, so brotherly, made me realize that I'd been happy, and that I was happy still.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Those who need myths are indeed poor. Here the gods serve as beds or resting places as the day races across the sky.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Nothing is harder to understand than a symbolic work. A symbol always transcends the one who makes use of it and makes him say in reality more than he is aware of expressing.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There is but one truly serious philosophical problem and that is suicide. Judging whether life is or is not worth living amounts to answering the fundamental question of philosophy.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Today people despair of true knowledge. If the only significant history of human thought were to be written, it would have to be history of its successive regrets and impotences.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "This divorce between man and his life, the actor and his setting, is properly the feeling of absurdity.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I do not want to found anything on the incomprehensible. I want to know whether I can live with what I know and with that alone.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "I don't know whether this world has a meaning that transcends it. But I know that I cannot know that meaning and that it is impossible for me just now to know it.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The absurd is the essential concept and the first truth.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "To two men living the same number of years, the world always provides the same sum of experiences. It is up to us to be conscious of them.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The preceding merely defines a way of thinking. But the point is to live.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "This heart within me I can feel, and I judge that it exists. This world I can touch, and I likewise judge that it exists. There ends all my knowledge, and the rest is construction.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "At any street corner the feeling of absurdity can strike any man in the face.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Great feelings take with them their own universe, splendid or abject. They light up with their passion an exclusive world in which they recognize their climate. There is a universe of jealousy, of ambition, of selfishness or generosity. A universe — in other words a metaphysic and an attitude of mind.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There can be no question of holding forth on ethics. I have seen people behave badly with great morality and I note every day that integrity has no need of rules.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "All systems of morality are based on the idea that an action has consequences that legitimize or cancel it. A mind imbued with the absurd merely judges that those consequences must be considered calmly.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The only truth that might seem instructive to him is not formal: it comes to life and unfolds in men. The absurd mind cannot so much expect ethical rules at the end of its reasoning as, rather, illustrations and the breath of human lives.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "A man's failures imply judgment, not of circumstances, but of himself.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "To become god is merely to be free on this earth, not to serve an immortal being.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There is no true creation without a secret.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "If the world were clear, art would not exist.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "One recognizes one's course by discovering the paths that stray from it.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Ironic philosophies produce passionate works.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "In that daily effort in which intelligence and passion mingle and delight each other, the absurd man discovers a discipline that will make up the greatest of his strengths.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Outside of that single fatality of death, everything, joy or happiness, is liberty.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "A fate is not a punishment.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "You have already grasped that Sisyphus is the absurd hero. He is, as much through his passions as through his torture.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Myths are made for the imagination to breathe life into them.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There is no fate that can not be surmounted by scorn.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Happiness and the absurd are two sons of the same earth. They are inseparable.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The struggle itself toward the heights is enough to fill a man's heart. One must imagine Sisyphus happy.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "So many men are deprived of grace. How can one live without grace? One has to try it and do what Christianity never did: be concerned with the damned.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There is always a philosophy for lack of courage.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The greatest saving one can make in the order of thought is to accept the unintelligibility of the world — and to pay attention to man.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Poor and free rather than rich and enslaved. Of course, men want to be both rich and free, and this is what leads them at times to be poor and enslaved.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Our technical civilization has just reached its greatest level of savagery. We will have to choose, in the more or less near future, between collective suicide and the intelligent use of our scientific conquests.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Even before the bomb, one did not breathe too easily in this tortured world. Now we are given a new source of anguish; it has all the promise of being our greatest anguish ever.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "Before the terrifying prospects now available to humanity, we see even more clearly that peace is the only goal worth struggling for. This is no longer a prayer but a demand to be made by all peoples to their governments — a demand to choose definitively between hell and reason.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "When a war breaks out, people say: \"It's too stupid; it can't last long.\" But though the war may well be \"too stupid,\" that doesn't prevent its lasting. Stupidity has a knack of getting its way; as we should see if we were not always so much wrapped up in ourselves.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The evil that is in the world always comes of ignorance, and good intentions may do as much harm as malevolence, if they lack understanding.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There can be no true goodness, nor true love, without the utmost clear-sightedness.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "There always comes a time in history when the person who dares to say that 2+2=4 is punished by death.", Author = "Albert Camus" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Albert_Camus", Text = "The issue is simply whether or not 2+2=4.", Author = "Albert Camus" },
        };
    }
}