using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class AnneFrank
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "It's a wonder I haven't abandoned all my ideals, they seem so absurd and impractical. Yet I cling to them because I still believe, in spite of everything, that people are truly good at heart.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "We're all alive, but we don't know why or what for; we're all searching for happiness; we're all leading lives that are different and yet the same.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I hear the approaching thunder that, one day, will destroy us too, I feel the suffering of millions. And yet, when I look up at the sky, I somehow feel that this cruelty too shall end, and that peace & tranquility will return once again.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Go outside, to the country, enjoy the sun and all nature has to offer. Go outside and try to recapture the happiness within yourself; think of all the beauty in yourself and in everything around you and be happy.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I've found that there is always some beauty left — in nature, sunshine, freedom, in yourself; these can all help you. Look at these things, then you find yourself again, and God, and then you regain your balance.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "A person who's happy will make others happy; a person who has courage and faith will never die in misery!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "For someone like me, it is a very strange habit to write in a diary. Not only that I have never written before, but it strikes me that later neither I, nor anyone else, will care for the musings of a thirteen-year-old schoolgirl.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I've learned one thing: you only really get to know a person after a fight. Only then can you judge their true character!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Fine specimens of humanity, those Germans, and to think that I am actually one of them!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "If I read a book that impresses me, I have to take myself firmly by the hand, before I mix with other people; otherwise they would think my mind rather queer.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "You can be lonely even when you're loved by many people, since you're still not anybody's 'one and only'.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I soothe my conscience now with the thought that it is better for hard words to be on paper than that Mummy should carry them in her heart.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Who would ever think that so much went on in the soul of a young girl?", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I trust to luck and do nothing but work, hoping that all will end well.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "The best remedy for those who are afraid, lonely or unhappy is to go outside, somewhere where they can be quiet, alone with the heavens, nature and God. Because only then does one feel that all is as it should be and that God wishes to see people happy, amidst the simple beauty of nature. As long as this exists, and it certainly always will, I know that then there will always be comfort for every sorrow, whatever the circumstances may be. And I firmly believe that nature brings solace in all troubles.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "People can tell you to keep your mouth shut, but it doesn't stop you having your own opinions. Even if people are still very young, they shouldn't be prevented from saying what they think.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "At such moments I don't think about all the misery, but about the beauty that still remains. This is where Mother and I differ greatly. Her advice in the face of melancholy is: 'Think about all the suffering in the world and be thankful you're not part of it.' My advice is: 'Go outside, to the country, enjoy the sun and all nature has to offer. Go outside and try to recapture the happiness within yourself; think of all the beauty in yourself and in everything around you and be happy.'", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "A 'food cycle' is a period in which we have only one particular dish or type of vegetable to eat. For a long time we ate nothing but endive. Endive with sand — , endive without sand, endive with mashed potatoes, endive-and-mashed potato casserole. Then it was spinach, followed by kohlrabi, salsify, cucumbers, tomatoes, sauerkraut, etc., etc.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I need to have something besides a husband and children to devote myself to! I don't want to have lived in vain like most people. I want to be useful or bring enjoyment to all people, even those I've never met.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I want to go on living even after my death! And that's why I'm so grateful to God for having given me this gift, which I can use to develop myself and to express all that's inside me!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Be brave! Let's remember our duty and perform it without complaint. There will be a way out. God has never deserted our people. Through the ages Jews have had to suffer, but through the ages they've gone on living, and the centuries of suffering have only made them stronger. The weak shall fall and the strong shall survive and not be defeated!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I don't believe that the big men, the politicians and the capitalists alone are guilty of the war. Oh, no, the little man is just as keen, otherwise the people of the world would have risen in revolt long ago! There is an urge and rage in people to destroy, to kill, to murder, and until all mankind, without exception, undergoes a great change, wars will be waged, everything that has been built up, cultivated and grown, will be destroyed and disfigured, after which mankind will have to begin all over again.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I have often been downcast, but never in despair; I regard our hiding as a dangerous adventure, romantic and interesting at the same time. In my diary I treat all the privations as amusing. I have made up my mind now to lead a different life from other girls and, later on, different from ordinary housewives. My start has been so very full of interest, and that is the sole reason why I have to laugh at the humorous side of the most dangerous moments.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Is discord going to show itself while we are still fighting, is the Jew once again worth less than another? Oh, it is sad, very sad, that once more, for the umpteenth time, the old truth is confirmed: 'What one Christian does is his own responsibility, what one Jew does is thrown back at all Jews.'", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "I believe that in the course of the next century the notion that it's a woman's duty to have children will change and make way for the respect and admiration of all women, who bear their burdens without complaint or a lot of pompous words!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Laziness may look inviting, but only work gives you true satisfaction.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "We're all alive, but we don't know why or what for; we're all searching for happiness; we're all leading lives that are different and yet the same.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "It's difficult in times like these: ideals, dreams and cherished hopes rise within us, only to be crushed by grim reality. It's a wonder I haven't abandoned all my ideals, they seem so absurd and impractical. Yet I cling to them because I still believe, in spite of everything, that people are truly good at heart. It's utterly impossible for me to build my life on a foundation of chaos, suffering and death. I see the world being slowly transformed into a wilderness, I hear the approaching thunder that, one day, will destroy us too, I feel the suffering of millions. And yet, when I look up at the sky, I somehow feel that everything will change for the better, that this cruelty too shall end, that peace and tranquility will return once more. In the meantime, I must hold on to my ideals. Perhaps the day will come when I'll be able to realize them!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Parents can only give good advice or put them on the right paths, but the final forming of a person's character lies in their own hands.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Forgive me, they don't call me a bundle of contradictions for nothing!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Where there's hope, there's life. It fills us with fresh courage and makes us strong again.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "All people are born equal, all people die in the end and keep nothing of their worldly status. All riches, all power and all greatness exist only for so few years, why then is that mortality clung to so strongly?", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "We all know that a good example is more effective than advice. So set a good example, and it won't take long for others to follow.", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "How wonderful it is that no one has to wait, but can start right now to gradually change the world! How wonderful it is that everyone, great and small, can immediately help bring about justice by giving of themselves! [...] You can always — always — give something, even if it's a simple act of kindness!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "No one has ever become poor by giving. If you act that way, then after a few generations people will no longer have to feel sorry for child beggars, because there will no longer be any! There is enough space, wealth, money and beauty in the world. God has created enough for everyone! So let us all begin to distribute it justly!", Author = "Anne Frank" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Anne_Frank", Text = "Who knows, perhaps one day people will listen more to “the little piece of God”, which we call a conscience, than to their own desires!.", Author = "Anne Frank" },
        };
    }
}