using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class AynRand
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "I am. I think. I will.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "I need no warrant for being, and no word of sanction upon my being. I am the warrant and the sanction.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "There is nothing to take a man's freedom away from him, save other men. To be free, a man must be free of his brothers.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "In the temple of his spirit, each man is alone.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "'Free competition enforced by law' is a grotesque contradiction in terms.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "My views on charity are very simple. I do not consider it a major virtue and, above all, I do not consider it a moral duty.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "I regard compassion as proper only toward those who are innocent victims, but not toward those who are morally guilty.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Not only the post office, but streets, roads, and above all, schools, should all be privately owned and privately run.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "I am an advocate of laissez-faire capitalism, of individual rights—there are no others—of individual freedom.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "When I came here from Soviet Russia, I was interested in politics for only one reason—to reach the day when I would not have to be interested in politics.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "And if you ask me, what is greatness? – I will answer, it is the capacity to live by the three fundamental values of John Galt: reason, purpose, self-esteem.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Is man worth it? What else is worth anything?", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Man is the only living species that has the power to act as his own destroyer—and that is the way he has acted through most of his history.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The men who attempt to survive, not by means of reason, but by means of force, are attempting to survive by the method of animals.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Poverty, ignorance, illness and other problems of that kind are not metaphysical emergencies.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "When you consider socialism, do not fool yourself about its nature. Remember that there is no such dichotomy as “human rights” versus “property rights.”", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Since only an individual man can possess rights, the expression “individual rights” is a redundancy.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Man's rights can be violated only by the use of physical force.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Any group or “collective,” large or small, is only a number of individuals. A group can have no rights other than the rights of its individual members.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Errors of knowledge are not breaches of morality; no proper moral code can demand infallibility or omniscience.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Racism is the lowest, most crudely primitive form of collectivism.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Racism is a doctrine of, by and for brutes.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "A genius is a genius, regardless of the number of morons who belong to the same race—and a moron is a moron, regardless of the number of geniuses who share his racial origin.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The skyline of New York is a monument of a splendor that no pyramids or palaces will ever equal or approach.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "All the reasons which made the initiation of physical force evil, make the retaliatory use of physical force a moral imperative.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Individual rights are the means of subordinating society to moral law.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The moral precept to adopt...is: Judge, and be prepared to be judged.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The moral cannibalism of all hedonist and altruist doctrines lies in the premise that the happiness of one man necessitates the injury of another.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Individual rights are not subject to a public vote; a majority has no right to vote away the rights of a minority.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The spread of evil is the symptom of a vacuum. Whenever evil wins, it is only by default: by the moral failure of those who evade the fact that there can be no compromise on basic principles.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "In a capitalist society, all human relationships are voluntary. Men are free to cooperate or not, to deal with one another or not, as their own individual judgments, convictions and interests dictate.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Statism is a system of institutionalized violence and perpetual civil war.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "A gun is not an argument.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "An attempt to achieve the good by force is like an attempt to provide a man with a picture gallery at the price of cutting out his eyes.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Businessmen are the one group that distinguishes capitalism and the American way of life from the totalitarian statism that is swallowing the rest of the world.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Every government interference in the economy consists of giving an unearned benefit, extorted by force, to some men at the expense of others.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "It is futile to fight against, if one does not know what one is fighting for.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Remember also that the smallest minority on earth is the individual. Those who deny individual rights, cannot claim to be defenders of minorities.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Capitalism has created the highest standard of living ever known on earth. The evidence is incontrovertible.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The most profound breach in this country is not between the rich and the poor, but between the people and the intellectuals.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Some day, the world will discover that, without thought, there can be no love.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "It is typical of today's culture that the proponents of seething, raging hostility are taken as advocates of love.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "There is a kind of malicious wink, a contemptuous sneer in the public voices claiming the hippies as heroes.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The hippies are the living demonstration of what it means to give up reason, and to rely on one's primeval instincts, urges, intuitions, and whims.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Is there any doubt that drug addiction is an escape from an unbearable inner state - from a reality that one cannot deal with - from an atrophying mind one can never fully destroy?", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "It is man's irrational emotions that bring him down to the mud. It is man's reason that lifts him to the stars.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Art is a selective re-creation of reality according to an artist's individual value-judgments.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Anyone who fights for the future, lives in it today.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "An artist reveals his naked soul in his work - and so, gentle reader, do you when you respond to it.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Pity for the guilty is treason to the innocent.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Definitions are the guardians of rationality, the first line of defense against the chaos of mental disintegration.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Even if smog were a risk to human life, we must remember that life in nature, without technology, is wholesale death.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Above all, do not join the wrong ideological groups or movements, in order to “do something.”", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "They didn't have any rights to the land, and there was no reason for anyone to grant them rights which they had not conceived and were not using.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The worst evil that you can do, psychologically, is to laugh at yourself. That means spitting in your own face.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The trouble with the world today is philosophical: only the right philosophy can save us.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "By the same principle, the government may not give special leniency to the perpetrator of a crime, on the grounds of the nature of his ideas.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "There is a level of cowardice lower than that of the conformist: the fashionable non-conformist.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Today, racism is regarded as a crime if practiced by a majority—but as an inalienable right if practiced by a minority.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Thanksgiving is a typically American holiday... The lavish meal is a symbol of the fact that abundant consumption is the result and reward of production.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Competition is a by-product of productive work, not its goal. A creative man is motivated by the desire to achieve, not by the desire to beat others.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Honor is self-esteem made visible in action.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "As far as the feminist movement is concerned, I am a male chauvinist.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "There are only two means by which men can deal with one another: guns or logic. Force or persuasion.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The conservatives see man as a body freely roaming the earth, building sand piles or factories—with an electronic computer inside his skull, controlled from Washington.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "A culture is made — or destroyed — by its articulate voices.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The purpose of my work: to introduce, or, rather, to re-introduce the original ways of human development.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Never demand of another that which would constitute his sacrifice to you. Never grant that which would constitute your sacrifice to him.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Never initiate the use of force against another man. Never let his use of force against you remain unanswered by force.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The actions of all group leaders throughout history have had one common element: altruism - common good of the collective.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The human race has only two unlimited capacities: one for suffering and one for lying.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "All progress is the work of individuals.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Selfishness does not mean only to do things for one's self. One may do things, affecting others, for his own pleasure and benefit. This is not immoral, but the highest of morality.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "The second handers offer substitutes for competence such as love, charm, kindness - easy substitutes - and there is no substitute for creation.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "On second handers: They are always concerned with people - not facts, ideas, work or production. What would happen to the world without those who think, work, and produce?", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "It took centuries of intellectual, philosophical development to achieve political freedom. It was a long struggle, stretching from Aristotle to John Locke to the Founding Fathers.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Let no man posture as an advocate of peace if he proposes or supports any social system that initiates the use of force against individual men, in any form.", Author = "Ayn Rand" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ayn_Rand", Text = "Man—every man—is an end in himself, not a means to the ends of others; he must live for his own sake, neither sacrificing himself to others nor sacrificing others to himself.", Author = "Ayn Rand" },
        };
    }
}