using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class BertrandRussell
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The fundamental cause of the trouble is that in the modern world the stupid are cocksure while the intelligent are full of doubt.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Most people would sooner die than think; in fact, they do so.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "My whole religion is this: do every duty, and expect no reward for it, either here or hereafter.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "I am looking forward very much to getting back to Cambridge, and being able to say what I think and not to mean what I say: two things which at home are impossible. Cambridge is one of the few places where one can talk unlimited nonsense and generalities without anyone pulling one up or confronting one with them when one says just the opposite the next day.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Pure mathematics consists entirely of assertions to the effect that, if such and such a proposition is true of anything, then such and such another proposition is true of that thing. It is essential not to discuss whether the first proposition is really true, and not to mention what the anything is, of which it is supposed to be true. Both these points would belong to applied mathematics. We start, in pure mathematics, from certain rules of inference, by which we can infer that if one proposition is true, then so is some other proposition. These rules of inference constitute the major part of the principles of formal logic. We then take any hypothesis that seems amusing, and deduce its consequences. If our hypothesis is about anything, and not about some one or more particular things, then our deductions constitute mathematics. Thus mathematics may be defined as the subject in which we never know what we are talking about, nor whether what we are saying is true. People who have been puzzled by the beginnings of mathematics will, I hope, find comfort in this definition, and will probably agree that it is accurate.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "It seems to me now that mathematics is capable of an artistic excellence as great as that of any music, perhaps greater; not because the pleasure it gives (although very pure) is comparable, either in intensity or in the number of people who feel it, to that of music, but because it gives in absolute perfection that combination, characteristic of great art, of godlike freedom, with the sense of inevitable destiny; because, in fact, it constructs an ideal world where everything is perfect and yet true.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "I hold all knowledge that is concerned with things that actually exist – all that is commonly called Science – to be of very slight value compared to the knowledge which, like philosophy and mathematics, is concerned with ideal and eternal objects, and is freed from this miserable world which God has made.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Only in thought is man a God; in action and desire we are the slaves of circumstance.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Philosophy seems to me on the whole a rather hopeless business.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The fact that all Mathematics is Symbolic Logic is one of the greatest discoveries of our age; and when this fact has been established, the remainder of the principles of mathematics consists in the analysis of Symbolic Logic itself.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "What does not exist must be something, or it would be meaningless to deny its existence; and hence we need the concept of being, as that which belongs even to the non-existent.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Arithmetic must be discovered in just the same sense in which Columbus discovered the West Indies, and we no more create numbers than he created the Indians.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Historical facts, many of them, have an intrinsic value, a profound interest on their own account, which makes them worthy of study, quite apart from any possibility of linking them together by means of causal laws.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The past alone is truly real: the present is but a painful, struggling birth into the immutable being of what is no longer. Only the dead exist fully. The lives of the living are fragmentary, doubtful, and subject to change; but the lives of the dead are complete, free from the sway of Time, the all but omnipotent lord of the world. Their failures and successes, their hopes and fears, their joys and pains, have become eternal—our efforts cannot now abate one jot of them. Sorrows long buried in the grave, tragedies of which only a fading memory remains, loves immortalized by Death's hallowing touch these have a power, a magic, an untroubled calm, to which no present can attain. ...On the banks of the river of Time, the sad procession of human generations is marching slowly to the grave; in the quiet country of the Past, the march is ended, the tired wanderers rest, and the weeping is hushed.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "A logical theory may be tested by its capacity for dealing with puzzles, and it is a wholesome plan, in thinking about logic, to stock the mind with as many puzzles as possible, since these serve much the same purpose as is served by experiments in physical science.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "All's well that ends well; which is the epitaph I should put on my tombstone if I were the last man left alive.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "We tend to believe the premises because we can see that their consequences are true, instead of believing the consequences because we know the premises to be true. But the inferring of premises from consequences is the essence of induction; thus the method in investigating the principles of mathematics is really an inductive method, and is substantially the same as the method of discovering general laws in any other science.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Ironclads and Maxim guns must be the ultimate arbiters of metaphysical truth.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "only on the firm foundation of unyielding despair, can the soul's habitation henceforth be safely built.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Indignation is a submission of our thoughts, but not of our desires.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Freedom comes only to those who no longer ask of life that it shall yield them any of those personal goods that are subject to the mutations of time.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Brief and powerless is Man's life; on him and all his race the slow, sure doom falls pitiless and dark.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Mathematics, rightly viewed, possesses not only truth, but supreme beauty – a beauty cold and austere, like that of sculpture, without appeal to any part of our weaker nature, without the gorgeous trappings of painting or music, yet sublimely pure, and capable of a stern perfection such as only the greatest art can show. The true spirit of delight, the exaltation, the sense of being more than Man, which is the touchstone of highest excellence, is to be found in mathematics as surely as in poetry. What is best in mathematics deserves not merely to be learnt as a task, but to be assimilated as a part of daily thought, and brought again and again before the mind with ever-renewed encouragement.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Real life is, to most men, a long second-best, a perpetual compromise between the ideal and the possible; but the world of pure reason knows no compromise, no practical limitations, no barrier to the creative activity embodying in splendid edifices the passionate aspiration after the perfect from which all great work springs. Remote from human passions, remote even from the pitiful facts of nature, the generations have gradually created an ordered cosmos, where pure thought can dwell as in its natural home, and where one, at least, of our nobler impulses can escape from the dreary exile of the actual world.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Mathematics takes us still further from what is human, into the region of absolute necessity, to which not only the world, but every possible world, must conform.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The above proposition is occasionally useful.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "When people begin to philosophize they seem to think it necessary to make themselves artificially stupid.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "A hallucination is a fact, not an error; what is erroneous is a judgment based upon it.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "No nation was ever so virtuous as each believes itself, and none was ever so wicked as each believes the other.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Righteousness cannot be born until self-righteousness is dead.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "I don't care for the applause one gets by saying what others are thinking; I want actually to change people's thoughts. Power over people's minds is the main personal desire of my life; and this sort of power is not acquired by saying popular things.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "How much good it would do if one could exterminate the human race.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The principal source of the harm done by the State is the fact that power is its chief end.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The best life is the one in which the creative impulses play the largest part and the possessive impulses the smallest.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Without effort and change, human life cannot remain good. It is not a finished Utopia that we ought to desire, but a world where imagination and hope are alive and active.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "My desire and wish is that the things I start with should be so obvious that you wonder why I spend my time stating them. This is what I aim at because the point of philosophy is to start with something so simple as not to seem worth stating, and to end with something so paradoxical that no one will believe it.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Reason is a harmonising, controlling force rather than a creative one.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Thus mathematics may be defined as the subject in which we never know what we are talking about, nor whether what we are saying is true.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Organic life, we are told, has developed gradually from the protozoon to the philosopher, and this development, we are assured, is indubitably an advance. Unfortunately it is the philosopher, not the protozoon, who gives us this assurance.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "Ethics is in origin the art of recommending to others the sacrifices required for co-operation with oneself.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "The law of causality, I believe, like much that passes muster among philosophers, is a relic of a bygone age, surviving, like the monarchy, only because it is erroneously supposed to do no harm.", Author = "Bertrand Russell" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bertrand_Russell", Text = "My own opinion—which I may as well indicate at the outset—is that pure Anarchism, though it should be the ultimate ideal, to which society should continually approximate, is for the present impossible, and would not survive more than a year or two at most if it were adopted.", Author = "Bertrand Russell" },
        };
    }
}