using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class BruceLee
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Under the sky, under the heavens, there is but one family. It just so happens that people are different.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "All types of knowledge, ultimately mean self knowledge.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Man, the living creature, the creating individual, is always more important than any established style or system.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Use only that which works, and take it from any place you can find it.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Don't get set into one form, adapt it and build your own, and let it grow, be like water.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "When I look around I always learn something, and that is to be yourself always, express yourself, and have faith in yourself.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "When you're talking about fighting, as it is, with no rules, well then, baby you'd better train every part of your body!", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Boards don't hit back.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "A good martial artist does not become tense, but ready.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Don't think, feel... it is like a finger pointing a way to the moon. Don't concentrate on the finger or you will miss all that heavenly glory!", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Forget about winning and losing; forget about pride and pain. Lay your life before him.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "There are no limits. There are plateaus, but you must not stay there, you must go beyond them.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Be water, my friend.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Jeet Kune Do favors formlessness so that it can assume all forms and since Jeet Kune Do has no style, it can fit in with all styles.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "When there is freedom from mechanical conditioning, there is simplicity.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Do not deny the classical approach, simply as a reaction, or you will have created another pattern and trapped yourself there.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Awareness has no frontier; it is giving of your whole being, without exclusion.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "To contemplate a thing implies maintaining oneself OUTSIDE it, resolved to keep a distance between it and ourselves.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Running water never grows stale. So you just have to 'keep on flowing.'", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "If one loves, one need not have an ideology of love.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The happiness that is derived from excitement is like a brilliant fire - soon it will go out.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "I think of myself as a human being.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "It flows through the slightest crack.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "All of his classical techniques and standard styles are minimized, if not wiped out, and nothingness prevails. He is no longer confined.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Using no way as way; Having no limitation as limitation.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "'Being' is more valued than \"doing\".", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "To grow, to discover, we need involvement, which is something I experience every day - sometimes good, sometimes frustrating. No matter what, you must let your inner light guide you out of the darkness.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "I believe in sleeping.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "There is no such thing as maturity. There is instead an ever-evolving process of maturing.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "I have changed from self-image actualization to self-actualization, from blindly following propaganda, organized truths, etc. to searching internally for the cause of my ignorance.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "With all the training thrown to nowhere, with a mind perfectly unaware of its own working, with the \"self\" vanishing nowhere, the art of JKD attains its perfection.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "You must have complete determination.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Walk on.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Jeet Kune Do rejects all restrictions imposed by form and formality and emphasizes the clever use of the mind and body to defend and attack.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "As an instructor, you must be able to distinguish between poor performance caused by lack of ability or aptitude on the part of the student and poor performance caused by lack of effort.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Even today, I dare not say that I have reached a state of achievement. I'm still learning, for learning is boundless.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The man who is really serious, with the urge to find out what truth is, has no style at all. He lives only in what is.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Faith will accomplish.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Faith makes it possible to achieve that which man's mind can conceive and believe.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Thoughts are things.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Make at least one definite move daily toward your goal.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The intangible represents the real power of the universe. It is the seed of the tangible.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Emptiness the starting point.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Life is wide, limitless. There is no border, no frontier.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The meaning of life is that it is to be lived, and it is not to be traded and conceptualized and squeezed into a pattern of systems.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The aphorism \"as a man thinketh in his heart so is he\" contains the secret of life.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Meaning is found in relationship.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Life is never stagnation.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Life itself is your teacher, and you are in a state of constant learning.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The primary reality is not what I think, but that I live, for those also live who do not think.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "To spend time is to pass it in a specified manner. To waste time is to expend it thoughtlessly or carelessly. We all have time to spend or waste, and it is our decision what to do with it. But once passed, it is gone forever.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "If you love life, don't waste time, for time is what life is made up of.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Be aware of doing your best to understand the ROOT in life, and realize the DIRECT and the INDIRECT are in fact a complementary WHOLE.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Concentration is the ROOT of all the higher abilities in man.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Seek to understand the root.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "What we are after is the ROOT and not the branches.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "If nothing within you stays rigid, outward things will disclose themselves. Moving, be like water. Still, be like a mirror. Respond like an echo.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "You cannot force the Now.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The Moment is freedom.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "The Now is indivisible.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "In Science we have finally come back to the pre-Socratic philosopher Heraclitus, who said everything is flow, flux, process. There are no \"things.\"", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "What IS is more important than WHAT SHOULD BE.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Conditioning obstructs our view of reality.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Reality is apparent when one ceases to compare.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Reality is being itself.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "A self-willed man obeys a different law, the one law I, too, hold absolutely sacred - the human law in himself, his own individual will.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "One should be in harmony with, not in opposition to, the strength and force of the opposition.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "I do not think unless I think of things - and there I find myself.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Taoist philosophy ... is essentially monistic. ... Matter and energy, Yang and Yin, heaven and earth, are conceived of as essentially one or as two coexistent poles of one indivisible whole.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Like everyone else you want to learn the way to win. But never to accept the way to lose. To accept defeat - to learn to die - is to be liberated from it.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "True thusness is the substance of thought, and thought is the function of true thusness. There is no thought except that of true thusness. Thusness does not move, but its motion and function are inexhaustible.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "When our mind is tranquil, there will be an occasional pause to its feverish activities, there will be a let-go, and it is only then in the interval between two thoughts that a flash of UNDERSTANDING - understanding, which is not thought - can take place.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Balance your thoughts with action.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Instead of dedicating your life to actualize a concept of what you should be like, ACTUALIZE YOURSELF.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Life is better lived than conceptualized.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Knowledge will give you power, but character respect.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "What you HABITUALLY THINK largely determines what you will ultimately become.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Choose the positive.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Cease negative mental chattering.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "A goal is not always meant to be reached, it often serves simply as something to aim at.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Don't fear failure. - Not failure, but low aim, is the crime. In great attempts it is glorious even to fail.", Author = "Bruce Lee" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Bruce_Lee", Text = "Research your own experience; absorb what is useful, reject what is useless and add what is essentially your own.", Author = "Bruce Lee" },
        };
    }
}