using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class CarlSagan
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "We make our world significant by the courage of our questions and by the depth of our answers.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The fact that some geniuses were laughed at does not imply that all who are laughed at are geniuses. They laughed at Columbus, they laughed at Fulton, they laughed at the Wright brothers. But they also laughed at Bozo the Clown.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "We live in a society absolutely dependent on science and technology and yet have cleverly arranged things so that almost no one understands science and technology. That's a clear prescription for disaster.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "We live in a society exquisitely dependent on science and technology, in which hardly anyone knows anything about science and technology.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Not explaining science seems to me perverse. When you're in love, you want to tell the world.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The truth may be puzzling. It may take some work to grapple with. It may be counterintuitive. It may contradict deeply held prejudices. It may not be consonant with what we desperately want to be true. But our preferences do not determine what's true.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Cleverly designed experiments are the key.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Every kid starts out as a natural-born scientist, and then we beat it out of them. A few trickle through the system with their wonder and enthusiasm for science intact.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "If you wish to make an apple pie from scratch, you must first invent the universe.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Who is more humble? The scientist who looks at the universe with an open mind and accepts whatever it has to teach us, or somebody who says everything in this book must be considered the literal truth and never mind the fallibility of all the human beings involved?", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Not all bits have equal value.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "I think people in power have a vested interest to oppose critical thinking.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "I do not consider myself a religious person in the usual sense, but there is a religious aspect to some highs. The heightened sensitivity in all areas gives me a feeling of communion with my surroundings, both animate and inanimate.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "A sense of what the world is really like can be maddening; cannabis has brought me some feelings for what it is like to be crazy, and how we use that word 'crazy' to avoid thinking about things that are too painful for us.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Many but not all my cannabis trips have somewhere in them a symbolism significant to me which I won't attempt to describe here, a kind of mandala embossed on the high. Free-associating to this mandala, both visually and as plays on words, has produced a very rich array of insights.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "I say 'Listen closely, you sonofabitch of the morning! This stuff is real!'", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "My high is always reflective, peaceable, intellectually exciting, and sociable, unlike most alcohol highs, and there is never a hangover.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "R is very large for LSD (which I've never taken) and reasonably short for cannabis. Small values of R should be one measure of the safety of psychedelic drugs.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The illegality of cannabis is outrageous, an impediment to full utilization of a drug which helps produce the serenity and insight, sensitivity and fellowship so desperately needed in this increasingly mad and dangerous world.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "I proffer the following ideas with a substantial degree of trepidation; I know very well that many of them are speculative and can be proved or disproved on the anvil of experiment.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Absence of evidence is not evidence of absence.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "It is important to distinguish between the amount of information and the quality of that information.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Note that in all this interaction between mutation and natural selection, no moth is making a conscious 'effort' to adapt to a changed environment. The process is random and statistical.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "There is a popular contention that half or more of the brain is unused. From an evolutionary point of view this would be quite extraordinary: why should it have evolved if it had no function? But actually the statement is made on very little evidence.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The price we pay for the anticipation of our future is anxiety about it. Foretelling disaster is probably not much fun; Pollyanna was much happier than Cassandra. But the Cassandric components of our nature are necessary for survival.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Evolution often uses this strategy. Indeed, the standard evolutionary practice of increasing the amount of genetic information as organisms increase in complexity is accomplished by doubling part of the genetic material and then allowing the slow specialization of function of the redundant set.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The search for patterns without critical analysis, and rigid skepticism without a search for patterns, are the antipodes of incomplete science. The effective pursuit of knowledge requires both functions.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Anatomy is not destiny, but it is not irrelevant either.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The integrity of the experimenters in the face of this unexpected finding is breathtaking. (It is difficult to imagine any experiment that would convince leading practitioners of many political or religious philosophies of the superiority of a competing doctrine.)", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "To me it is not in the least demeaning that consciousness and intelligence are the result of 'mere' matter sufficiently complexly arranged; on the contrary, it is an exalting tribute to the subtlety of matter and the laws of Nature.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The entire evolutionary record on our planet, particularly the record contained in fossil endocasts, illustrates a progressive tendency toward intelligence. There is nothing mysterious about this: smart organisms by and large survive better and leave more offspring than stupid ones.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Once intelligent beings achieve technology and the capacity for self-destruction of their species, the selective advantage of intelligence becomes more uncertain.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Both borderline science and many religions are motivated in part by a serious concern about the nature of the universe and our role in it, and for this reason merit our consideration and regard.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The well-meaning contention that all ideas have equal merit seems to me little different from the disastrous contention that no ideas have any merit.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Society corrupts the best of us. It is a little unfair, I think, to criticize a person for not sharing the enlightenment of a later epoch, but it is also profoundly saddening that such prejudices were so extremely pervasive.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Our perceptions may be distorted by training and prejudice or merely because of the limitations of our sense organs, which, of course, perceive directly but a small fraction of the phenomena of the world.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Whether in some sense the universe is ultimately knowable depends not only on how many natural laws there are that encompass widely divergent phenomena, but also on whether we have the openness and the intellectual capacity to understand such laws.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "For myself, I like a universe that includes much that is unknown and, at the same time, much that is knowable. A universe in which everything is known would be static and dull, as boring as the heaven of some weak-minded theologians.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "People are rarely grateful for a demonstration of their credulity.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "But our openness to the dazzling possibilities presented by modern science must be tempered by some hard-nosed skepticism. Many interesting possibilities simply turn out to be wrong. An openness to new possibilities and a willingness to ask hard questions are both required to advance our knowledge.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "I believe that the extraordinary should certainly be pursued. But extraordinary claims require extraordinary evidence.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Where skeptical observation and discussion are suppressed, the truth is hidden.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The best antidote for pseudoscience, I firmly believe, is science.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The idea of science as a method rather than as a body of knowledge is not widely appreciated outside of science, or indeed in some corridors inside of science.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Vigorous criticism is more constructive in science than in some other areas of human endeavor because in science there are adequate standards of validity that can be agreed upon by competent practitioners the world over.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "It is merely a coincidence. When enough fiction is written and enough scientific hypotheses are proposed, sooner or later there will be accidental concordances.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "In the face of all this, many of the standard ideas of science fiction seem to me to pale by comparison. I see the relative absence of these things and the distortions of scientific thinking often encountered in science fiction as terrible wasted opportunities.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Many scientists deeply involved in the exploration of the solar system (myself among them) were first turned in that direction by science fiction. And the fact that some of that science fiction was not of the highest quality is irrelevant.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Every new set of discoveries raises a host of questions which we were never before wise enough even to ask.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "Much of human history can, I think, be described as a gradual and sometimes painful liberation from provincialism, the emerging awareness that there is more to the world than was generally believed by our ancestors.", Author = "Carl Sagan" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Carl_Sagan", Text = "The search for extraterrestrial intelligence is the search for a generally acceptable cosmic context for the human species. In the deepest sense, the search for extraterrestrial intelligence is a search for ourselves.", Author = "Carl Sagan" },
        };
    }
}