using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class CharlesBukowski
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "No shortcuts, with me as with life.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I've never met another man I'd rather be.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I walk through rooms of the dead, streets of the dead, cities of the dead: men without eyes, men without voices; men with manufactured feelings and standard reactions; men with newspaper brains, television souls and high school ideals.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "If you want to know who your friends are, get yourself a jail sentence.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "An intellectual is a man who says a simple thing in a difficult way; an artist is a man who says a difficult thing in a simple way.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Show me a man who lives alone and has a perpetually clean kitchen, and eight times out of nine I'll show you a man with detestable spiritual qualities.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "The free soul is rare, but you know it when you see it - basically because you feel good, very good, when you are near or with them.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "It began as a mistake.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Any damn fool can beg up some kind of job; it takes a wise man to make it without working.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I wasn't much of a petty thief. I wanted the whole world or nothing.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Women were meant to suffer; no wonder they asked for constant declarations of love.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Maybe she hadn’t saved the world but she had made a major improvement. Ring one up for Fay.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I was a man who thrived on solitude; without it I was like another man without food or water. Each day without solitude weakened me. I took no pride in my solitude; but I was dependent on it.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Love is for real people.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I dislike real people.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "That was all a man needed: hope. It was a lack of hope that discouraged a man.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "When you drank the world was still out there, but for the moment it didn't have you by the throat.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Someday, when they demonstrate that the world has four dimensions instead of just three, a man will be able to go for a walk and just disappear. No burial, no tears, no illusions, no heaven or hell. People will be sitting around and they'll say, 'What happened to George?' And somebody will say, 'Well, I don't know. He said he was going out for a pack of cigarettes.'", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "My ambition is handicapped by my laziness.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "People don't need love. What they need is success in one form or another. It can be love but it needn't be.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "It was true that I didn't have much ambition, but there ought to be a place for people without ambition, I mean a better place than the one usually reserved. How in the hell could a man enjoy being awakened at 6:30 a.m. by an alarm clock, leap out of bed, dress, force-feed, shit, piss, brush teeth and hair, and fight traffic to get to a place where essentially you made lots of money for somebody else and were asked to be grateful for the opportunity to do so?", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "For each Joan of Arc there is a Hitler perched at the other end of the teeter-totter. The old story of good and evil.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Nothing is worse than to finish a good shit, then reach over and find the toilet paper container empty. Even the most horrible human being on earth deserves to wipe his ass.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Not everybody thought they could be a dentist or an automobile mechanic but everybody knew they could be a writer. But most men, fortunately, aren't writers, or even cab drivers, and some men - many men - unfortunately aren't anything.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Every man is a poet", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Human relationships didn't work anyhow. Only the first two weeks had any zing, then the participants lost their interest. Masks dropped away and real people began to appear: cranks, imbeciles, the demented, the vengeful, sadists, killers. Modern society had created its own kind and they feasted on each other. It was a duel to the death--in a cesspool.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "People with no morals often considered themselves more free, but mostly they lacked the ability to feel hate or love.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Morals were restrictive, but they were grounded on human experience.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Many a good man has been put under the bridge by a woman.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Once a woman turns against you, forget it. They can love you, then something turns in them. They can watch you dying in a gutter, run over by a car, and they'll spit on you.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Nothing was ever in tune. People just blindly grabbed at whatever there was: communism, health foods, zen, surfing, ballet, hypnotism, group encounters, orgies, biking, herbs, Catholicism, weight-lifting, travel, withdrawal, vegetarianism, India, painting, writing, sculpting, composing, conducting, backpacking, yoga, copulating, gambling, drinking, hanging around, frozen yogurt, Beethoven, Bach, Buddha, Christ, TM, H, carrot juice, suicide, handmade suits, jet travel, New York City, and then it all evaporated and fell apart. People had to find things to do while waiting to die. I guess it was nice to have a choice.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "All a guy needed was a chance. Somebody was always controlling who got a chance and who didn’t.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Drink was the only thing that kept a man from feeling forever stunned and useless. Everything else just kept picking and picking, hacking away. And nothing was interesting, nothing. The people were restrictive and careful, all alike. And I've got to live with these fuckers for the rest of my life, I thought. God, they all had assholes and sexual organs and their mouths and their armpits. They shit and they chattered and they were dull as horse dung. The girls looked good from a distance, the sun shining through their dresses, their hair. But get up close and listen to their minds running out of their mouths, you felt like digging in under a hill and hiding out with a tommy-gun. I would certainly never be able to be happy, to get married, I could never have children. Hell, I couldn't even get a job as a dishwasher.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "The problem was you had to keep choosing between one evil or another, and no matter what you chose, they sliced a little more off you, until there was nothing left. At the age of 25 most people were finished. A whole goddamned nation of assholes driving automobiles, eating, having babies, doing everything in the worst way possible, like voting for the presidential candidate who reminded them most of themselves. I had no interests. I had no interest in anything. I had no idea how I was going to escape. At least the others had some taste for life. They seemed to understand something that I didn't understand. Maybe I was lacking. It was possible. I often felt inferior. I just wanted to get away from them. But there was no place to go.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Money is like sex. It seems much more important when you don't have any...", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "the bluebird in my heart that wants to get out but I'm too tough for him, I say, stay in there, I'm not going to let anybody see you. ...I only let him out at night sometimes when everybody's asleep. ...he's singing a little in there, I haven't quite let him die ...and it's nice enough to make a man weep, but I don't weep,do you?", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "a woman can drop out of your life and forget you real fast. a woman can't go anywhere but UP after leaving you, honey.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "there were these people on the ground, they were reaching up their arms and trying to pull me down but they couldn't do it. I felt like pissing on them. they were so jealous. all they had to do was to work their way slowly up to it as I had done. such people think success grows on trees. you and I, we know better.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Hell was what you made it.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Sex was a trap, a snare. It was for animals.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "Something was always after a man. It never relented. No rest, ever.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I am waiting to live, waiting to die. I wish I could ring in some bravery. it's a lousy fix", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "There's nothing to mourn about death any more than there is to mourn about the growing of a flower. What is terrible is not death but the lives people live or don't live up until their death. They don't honor their own lives, they piss on their lives. They shit them away. Dumb fuckers. They concentrate too much on fucking, movies, money, family, fucking. Their minds are full of cotton. They swallow God without thinking, they swallow country without thinking. Soon they forget how to think, they let others think for them. Their brains are stuffed with cotton. They look ugly, they talk ugly, they walk ugly. Play them the great music of the centuries and they can't hear it. Most people's deaths are a sham. There's nothing left to die.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "We're all going to die, all of us, what a circus! That alone should make us love each other but it doesn't. We are terrorized and flattened by trivialities, we are eaten up by nothing.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I am building a machine gun in my closet now to take out as many of them as I can before they get me.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "The female is skilled at betrayal. and torture and damnation. Never envy a man his lady. Behind it all lays a living hell.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I grow tired of 18th century moralities in a 20th century space-atomic age. If I want to kill myself I feel that should be my business. If I go out and hold up gas stations at night to pay for my supply it is because the law inflates a very cheap thing into an escalated war against my nerves and my soul.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "If I'm an ass, I should say so. If I don't, somebody else will. If I say it first, that disarms them.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "We are here to unlearn the teachings of the church, state and our educational system. We are here to drink beer. We are here to kill war. We are here to laugh at the odds and live our lives so well that Death will tremble to take us.", Author = "Charles Bukowski" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Charles_Bukowski", Text = "I found out that Hollywood is more crooked, dumber, crueler, stupider than all the books I've read about it. They didn't go deeply enough into how it lacks art, and soul, and heart— how it's really a piece of crap. There are too many hands directing, there're too many fingers in the pot, and they're all kind of ignorant about what they're doing. They're greedy, and they're vicious. So you don't get much of a movie.", Author = "Charles Bukowski" },
        };
    }
}