using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class DHLawrence
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I hold that the parentheses are by far the most important parts of a non-business letter.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "My God, these folks don't know how to love — that's why they love so easily.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Tragedy ought really to be a great kick at misery.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "We have to hate our immediate predecessors to get free from their authority.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "It's the man who dares to take, who is independent, not he who gives.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Not I, not I, but the wind that blows through me!", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The nature of the infant is not just a new permutation-and-combination of elements contained in the natures of the parents. There is in the nature of the infant that which is utterly unknown in the natures of the parents.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The dead don't die. They look on and help.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "California is a queer place — in a way, it has turned its back on the world, and looks into the void Pacific. It is absolutely selfish, very empty, but not false, and at least, not full of false effort.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Never trust the artist. Trust the tale. The proper function of a critic is to save the tale from the artist who created it", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "It was in 1915 the old world ended.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Men! The only animal in the world to fear!", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The Rhine is still the Rhine, the great divider... Immediately you are over the Rhine, the spirit of place has changed... It is as if the life had retreated eastwards. As if the Germanic life were slowly ebbing away from contact with western Europe, ebbing to the deserts of the east.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Out of the very air comes a sense of danger, a queer, bristling feeling of uncanny danger. Something has happened. Something has happened which has not yet eventuated. The old spell of the old world has broken, and the old, bristling, savage spirit has set in... Back, back to the savage polarity of Tartary, and away from the polarity of civilised Christian Europe. This, it seems to me, has already happened. And it is a happening of far more profound import than any actual event. It is the father of the next phase of events. And the feeling never relaxes. As you travel up the Rhine valley, still the same latent sense of danger, of silence, of suspension. Not that the people are actually planning or plotting or preparing. I don't believe it for a minute. But something has happened to the human soul, beyond all help. The human soul recoiling now from unison, and making itself strong elsewhere. The ancient spirit of prehistoric Germany coming back, at the end of history.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Something about the Germanic races is unalterable. White-skinned, elemental, and dangerous. Our civilisation has come from the fusion of the dark-eyed with the blue. The meeting and mixing and mingling of the two races has been the joy of our ages. And the Celt has been there, alien, but necessary as some chemical re-agent to the fusion. So the civilisation of Europe rose up. So these cathedrals and these thoughts. But now the Celt is the disintegrating agent. And the Latin and southern races are falling out of association with the northern races, the northern Germanic impulse is recoiling towards Tartary, the destructive vortex of Tartary. It is a fate; nobody now can alter it. It is a fate. The very blood changes. Within the last three years, the very constituency of the blood has changed, in European veins. But particularly in Germanic veins. At the same time, we have brought it about ourselves—by a Ruhr occupation, by an English nullity, and by a German false will. We have done it ourselves. But apparently it was not to be helped. Quos vult perdere Deus, dementat prius.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I want to go south, where there is no autumn, where the cold doesn't crouch over one like a snow leopard waiting to pounce. The heart of the North is dead, and the fingers of cold are corpse fingers.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "For Society or Democracy or any political State or Community exists not for the sake of the individual nor should ever exist for the sake of the individual, but simply to establish the Average, in order to make living together possible: that is, to make proper facilities for every man's clothing, feeding, housing himself, working, sleeping, mating, playing, according to his necessity as a common unit, an average. Everything beyond that common necessity depends on himself alone.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The more scholastically educated a man is generally, the more he is an emotional boor.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Men fight for liberty, and win it with hard knocks. Their children, brought up easy, let it slip away again, poor fools. And their grandchildren are once more slaves.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Every man has a mob self and an individual self, in varying proportions.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Pornography is the attempt to insult sex, to do dirt on it.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I can't stand Willy wet-leg, can't stand him at any price. He's resigned, and when you hit him he lets you hit him twice.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Censors are dead men set up to judge between life and death. For no live, sunny man would be a censor, he'd just laugh.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I never saw a wild thing Sorry for itself. A small bird will drop frozen dead from a bough without ever having felt sorry for itself.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The tiny fish enjoy themselves in the sea. Quick little splinters of life, their little lives are fun to them in the sea.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "What man most passionately wants is his living wholeness and his living unison, not his own isolate salvation of his \"soul.\" Man wants his physical fulfillment first and foremost, since now, once and once only, he is in the flesh and potent. For man, the vast marvel is to be alive. For man, as for flower and beast and bird, the supreme triumph is to be most vividly, most perfectly alive. Whatever the unborn and the dead may know, they cannot know the beauty, the marvel of being alive in the flesh. The dead may look after the afterwards. But the magnificent here and now of life in the flesh is ours, and ours alone, and ours only for a time. We ought to dance with rapture that we should be alive and in the flesh, and part of the living, incarnate cosmos. I am part of the sun as my eye is part of me. That I am part of the earth my feet know perfectly, and my blood is part of the sea. My soul knows that I am part of the human race, my soul is an organic part of the great human soul, as my spirit is part of my nation. In my own very self, I am part of my family. There is nothing of me that is alone and absolute except my mind, and we shall find that the mind has no existence by itself, it is only the glitter of the sun on the surface of the waters.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "To the Puritan all things are impure, as somebody says.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "God is only a great imaginative experience.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Those that go searching for love only make manifest their own lovelessness, and the loveless never find love, only the loving find love, and they never have to seek for it.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I don't think I love you as a man ought to love his wife", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Humanity is a huge aggregate lie, and a huge lie is less than a small truth. Humanity is less, far less than the individual, because the individual may sometimes be capable of truth, and humanity is a tree of lies. And they say that love is the greatest thing; they persist in SAYING this, the foul liars, and just look at what they do! Look at all the millions of people who repeat every minute that love is the greatest, and charity is the greatest— and see what they are doing all the time. By their works ye shall know them, for dirty liars and cowards, who daren't stand by their own actions, much less by their own words.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "But better die than live mechanically a life that is a repetition of repetitions.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Mystic equality lies in abstraction, not in having or in doing, which are processes. In function and process, one man, one part, must of necessity be subordinate to another. It is a condition of being.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Ours is essentially a tragic age, so we refuse to take it tragically. The cataclysm has happened, we are among the ruins, we start to build up new little habitats, to have new little hopes. It is rather hard work: there is now no smooth road into the future: but we go round, or scramble over the obstacles. We’ve got to live, no matter how many skies have fallen.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The world is supposed to be full of possibilities, but they narrow down to pretty few in most personal experience. There's lots of good fish in the sea ... maybe ... but the vast masses seem to be mackerel or herring, and if you're not mackerel or herring yourself you are likely to find very few good fish in the sea.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Folks should do their own fuckin', then they wouldn't want to listen to a lot of clatfart about another man's.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I believe in being warm-hearted. I believe especially in being warm-hearted in love, in fucking with a warm heart. I believe if men could fuck with warm hearts, and the women take it warm-heartedly, everything would come all right. It's all the cold-hearted fucking that is death and idiocy.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The Italians are not passionate: passion has deep reserves. They are easily moved, and often affectionate, but they rarely have any abiding passion of any sort.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Money poisons you when you've got it, and starves you when you haven't.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "We are today, as human beings, evolved and cultured far beyond the taboos which are inherent in our culture. This is a very important fact to realise.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The great necessity is that we should act according to our thoughts, and think according to our acts. But while we are in thought we cannot really act, and while we are in action we cannot really think. The two conditions, of thought and action, are mutually exclusive. Yet they should be related in harmony.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Men and women aren't really dogs: they only look like it and behave like it. Somewhere inside there is a great chagrin and a gnawing discontent.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Of course Celia shits! Who doesn't? And how much worse if she didn't.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Augustine said that God created the universe new every day: and to the living, emotional soul, this is true. Every dawn dawns upon an entirely new universe, every Easter lights up an entirely new glory of a new world opening in utterly new flower. And the soul of man and the soul of woman is new in the same way, with the infinite delight of life and the ever-newness of life. So a man and a woman are new to one another throughout a life-time, in the rhythm of marriage that matches the rhythm of the year.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Sex is the balance of male and female in the universe, the attraction, the repulsion, the transit of neutrality, the new attraction, the new repulsion, always different, always new.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Oh, what a catastrophe for Humanity when he cut himself off from the rhythm of the year, from his unison with the sun and the earth. Oh, what a catastrophe, what a maiming of love when it was a personal, merely personal feeling, taken away from the rising and the setting of the sun, and cut off from the magic connection of the solstice and the equinox!", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "Marriage is the clue to human life, but there is no marriage apart from the wheeling sun and the nodding earth, from the straying of the planets and the magnificance of the fixed stars. Is not a man different, utterly different, at dawn from what he is at sunset? And a woman too? And does not the changing harmony and discord of their variation make the secret music of life?", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "When I read Shakespeare I am struck with wonder that such trivial people should muse and thunder in such lovely language.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I am not a mechanism, an assembly of various sections. And it is not because the mechanism is working wrongly, that I am ill. I am ill because of wounds to the soul, to the deep emotional self and the wounds to the soul take a long, long time, only time can help and patience, and a certain difficult repentance long, difficult repentance, realization of life’s mistake, and the freeing oneself from the endless repetition of the mistake which mankind at large has chosen to sanctify.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "The gods are nameless and imageless yet looking in a great full lime-tree of summer I suddenly saw deep into the eyes of gods: it is enough.", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I refuse to name the gods, because they have no name. I refuse to describe the gods, because they have no form nor shape nor substance. Ah, but the simple ask for images! Then for a time at least, they must do without. But all the time I see the gods: the man who is moving the tall white corn, suddenly, it curves, as it yields, the white wheat and sinks down with a swift rustle, and a strange, falling flatness, ah! the gods, the swaying body of god!", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "There are no gods, and you can please yourself have a game of tennis, go out in the car, do some shopping, sit and talk, talk, talk with a cigarette browning your fingers. There are no gods, and you can please yourself — go and please yourself — But leave me alone, leave me alone, to myself!", Author = "D. H. Lawrence" },
            new Quote { Id = "https://en.wikiquote.org/wiki/D._H._Lawrence", Text = "I fall asleep with the gods, the gods that are not, or that are like a pool into which we plunge, or do not plunge.", Author = "D. H. Lawrence" },
        };
    }
}