using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class DouglasAdams
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Let us think the unthinkable, let us do the undoable, let us prepare to grapple with the ineffable itself, and see if we may not eff it after all.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "It's nice to think that one could, even here and now, be whisked away just by hitchhiking.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The fact that we live at the bottom of a deep gravity well, on the surface of a gas covered planet going around a nuclear fireball 90 million miles away and think this to be normal is obviously some indication of how skewed our perspective tends to be.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "We don't have to save the world. The world is big enough to look after itself. What we have to be concerned about is whether or not the world we live in will be capable of sustaining us in it.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "A learning experience is one of those things that say, \"You know that thing you just did? Don't do that.\"", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "If you try and take a cat apart to see how it works, the first thing you have on your hands is a nonworking cat.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "You are disoriented. Blackness swims toward you like a school of eels who have just seen something that eels like a lot.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Driving a Porsche in London is like bringing a Ming vase to a football game.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "I think a nerd is a person who uses the telephone to talk to other people about telephones. And a computer nerd therefore is somebody who uses a computer in order to use a computer.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Imagine a puddle waking up one morning and thinking, \"This is an interesting world I find myself in — an interesting hole I find myself in — fits me rather neatly, doesn't it? In fact it fits me staggeringly well, may have been made to have me in it!\" This is such a powerful idea that as the sun rises in the sky and the air heats up and as, gradually, the puddle gets smaller and smaller, it's still frantically hanging on to the notion that everything's going to be alright, because this world was meant to have him in it, was built to have him in it; so the moment he disappears catches him rather by surprise. I think this may be something we need to be on the watch out for.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "There are some oddities in the perspective with which we see the world.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "If you try and take a cat apart to see how it works, the first thing you have on your hands is a nonworking cat. Life is a level of complexity that almost lies outside our vision; it is so far beyond anything we have any means of understanding that we just think of it as a different class of object, a different class of matter; 'life', something that had a mysterious essence about it, was God given, and that's the only explanation we had. The bombshell comes in 1859 when Darwin publishes 'On the Origin of Species'. It takes a long time before we really get to grips with this and begin to understand it, because not only does it seem incredible and thoroughly demeaning to us, but it's yet another shock to our system to discover that not only are we not the centre of the Universe and we're not made by anything, but we started out as some kind of slime and got to where we are via being a monkey. It just doesn't read well.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The world is a thing of utter inordinate complexity and richness and strangeness that is absolutely awesome.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "CLIXBY (adj.) Politely rude. Briskly vague. Firmly uninformative.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "SHOEBURYNESS (abs.n.) The vague uncomfortable feeling you get when sitting on a seat which is still warm from somebody else's bottom", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "WOKING (vb.) To enter the kitchen with the precise determination to perform something only to forget what it is just before you do it.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "If it looks like a duck, and quacks like a duck, we have at least to consider the possibility that we have a small aquatic bird of the family Anatidae on our hands.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The teacher usually learns more than the pupils. Isn't that true? \"It would be hard to learn much less than my pupils,\" came a low growl from somewhere on the table, \"without undergoing a pre-frontal lobotomy.\"", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The door was the way to... to... The Door was The Way. Good. Capital letters were always the best way of dealing with things you didn't have a good answer to.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "This was the evening of the last day of Gordon Way's life … The weather forecast hadn't mentioned that, of course, that wasn't the job of the weather forecast, but then his horoscope had been pretty misleading as well. It had mentioned an unusual amount of planetary activity in his sign and had urged him to differentiate between what he thought he wanted and what he actually needed, and suggested that he should tackle emotional or work problems with determination and complete honesty, but had inexplicably failed to mention that he would be dead before the day was out.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Sir Isaac Newton, renowned inventor of the milled-edge coin and the catflap! [...] Gravity, said Dirk with a slightly dismissive shrug, yes, there was that as well, I suppose. Though that, of course, was merely a discovery. It was there to be discovered. [...] They even keep it on at weekends. Someone was bound to notice sooner or later. But the catflap … ah, there is a very different matter. Invention, pure creative invention. It is a door within a door, you see.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "If the Universe came to an end every time there was some uncertainty about what had happened in it, it would never have got beyond the first picosecond. And many of course don’t. Paradoxes are just the scar tissue. Time and space heal themselves up around them and people simply remember a version of events which makes as much sense as they require it to make.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "It can hardly be a coincidence that no language on Earth has ever produced the expression \"As pretty as an airport.\"", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Always expecting this and expecting that. May I recommend serenity to you? A life that is burdened with expectations is a heavy life. Its fruit is sorrow and disappointment. Learn to be one with the joy of the moment.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The kid was deliberately and maliciously watching television at him.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Thor was the God of Thunder and, frankly, acted like it.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The impossible often has a kind of integrity to it which the merely improbable lacks.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Immortals are what you wanted, said Thor in a low, quiet voice. Immortals are what you got. It is a little hard on us. You wanted us to be for ever, so we are for ever. Then you forget about us. But we are still for ever. Now at last, many are dead, many are dying, he then added in a quiet voice, but it takes a special effort. [...] You can begin to understand, said Thor, angrily, which is why I have come to you. Do you know that most people hardly see me? Hardly notice me at all? It is not that we are hidden. We are here. We move among you. My people. Your gods. You gave birth to us. You made us what you would not dare to be yourselves. Yet you will not acknowledge us. If I walk along one of your streets in this... world you have made for yourselves without us, then barely an eye will once flicker in my direction. [...] Especially when I'm wearing the helmet!", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "they won't be rivers anymore, just currents in the ocean.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Radio did not kill books and television did not kill radio or movies — what television did kill was cinema newsreel. TV does it much better because it can deliver it instantly. Who wants last week's news?", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Generally, old media don't die. They just have to grow old gracefully.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "For us, there is no longer a fundamental mystery about Life. It is all the process of extraordinary eruptions of information, and it is information which gives us this fantastically rich, complex world in which we live; but at the same time that we've discovered that we are destroying it at a rate that has no precedent in history, unless you go back to the point when we are hit by an asteroid!", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "You will need to know the difference between Friday and a fried egg. It's quite a simple difference, but an important one. [...] It's all rather complicated, but it makes a kind of sense if you think about it for a while.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "All opinions are not equal. Some are a very great deal more robust, sophisticated and well supported in logic and argument than others.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Anything invented after you're thirty-five is against the natural order of things.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The future of computer power is pure simplicity.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "I am fascinated by religion. (That's a completely different thing from believing in it!)", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "I'd take the awe of understanding over the awe of ignorance any day.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "My 'absolute' favourite piece of information is the fact that young sloths are so inept that they frequently grab their own arms and legs instead of tree limbs, and fall out of trees.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "The hotel shop only had two decent books, and I'd written both of them.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "We are stuck with technology when what we really want is just stuff that works.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "I love deadlines. I love the whooshing noise they make as they go by.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "He was constantly reminded of how startlingly different a place the world was when viewed from a point only three feet to the left.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Solutions nearly always come from the direction you least expect, which means there's no point trying to look in that direction because it won't be coming from there.", Author = "Douglas Adams" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Douglas_Adams", Text = "Five years later, while he was struggling to think of a legitimate reason for an alien to visit Earth, the phrase returned to him. The rest is history…", Author = "Douglas Adams" },
        };
    }
}