using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class EdgarAllanPoe
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "O, human love! thou spirit given, On Earth, of all we hope in Heaven!", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Sound loves to revel in a summer night.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Years of love have been forgot In the hatred of a minute.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And the cloud that took the form (When the rest of Heaven was blue) Of a demon in my view.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Hast thou not torn the Naiad from her flood, The Elfin from the green grass, and from me The summer dream beneath the tamarind tree?", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "It is with literature as with law or empire — an established name is an estate in tenure, or a throne in possession.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Music, when combined with a pleasurable idea, is poetry; music without the idea is simply music; the idea without the music is prose from its very definitiveness.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Thy Naiad airs have brought me home To the glory that was Greece And the grandeur that was Rome.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Yes, Heaven is thine; but this Is a world of sweets and sours; Our flowers are merely—flowers.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "If I could dwell Where Israfel Hath dwelt, and he where I, He might not sing so wildly well A mortal melody, While a bolder note than this might swell From my lyre within the sky.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Come! let the burial rite be read — the funeral song be sung! — An anthem for the queenliest dead that ever died so young — A dirge for her the doubly dead in that she died so young.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Vastness! and Age! and Memories of Eld! Silence! and Desolation! and dim Night! I feel ye now — I feel ye in your strength.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Thou wast that all to me, love, For which my soul did pine — A green isle in the sea, love, A fountain and a shrine, All wreathed with fairy fruits and flowers, And all the flowers were mine.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And all my days are trances, And all my nightly dreams Are where thy grey eye glances, And where thy footstep gleams — In what ethereal dances, By what eternal streams.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Convinced myself, I seek not to convince.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "In the greenest of our valleys By good angels tenanted, Once a fair and stately palace — Radiant palace — reared its head.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "This—all this—was in the olden Time long ago.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "While, like a ghastly rapid river, Through the pale door A hideous throng rush out forever And laugh — but smile no more.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "A carpet is the soul of an apartment.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "They who dream by day are cognizant of many things which escape those who dream only by night.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Had the routine of our life at this place been known to the world, we should have been regarded as madmen —; although, perhaps, as madmen of a harmless nature.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "To observe attentively is to remember distinctly.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And Darkness and Decay and the Red Death held illimitable dominion over all.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "While the angels, all pallid and wan, Uprising, unveiling, affirm That the play is the tragedy, \"Man\", And its hero the Conqueror Worm.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Man is an animal that diddles, and there is no animal that diddles but man.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "The boundaries which divide Life from Death are at best shadowy and vague. Who shall say where the one ends, and where the other begins?", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "For the love of God Montresor!", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "I became insane, with long intervals of horrible sanity.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Can it be fancied that Deity ever vindictively Made in his image a mannikin merely to madden it?", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Depend upon it, after all, Thomas, Literature is the most noble of professions. In fact, it is about the only one fit for a man. For my own part, there is no seducing me from the path.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Gaily bedight, A gallant knight, In sunshine and in shadow, Had journeyed long, Singing a song, In search of Eldorado.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "\"Over the Mountains Of the Moon, Down the Valley of the Shadow, Ride, boldly ride,\" The shade replied, — \"If you seek for Eldorado!\"", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "O God! Can I not save ''One'' from the pitiless wave? ''Is ''all'' that we see or seem But a dream within a dream?'", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Thank Heaven! the crisis — The danger is past, And the lingering illness Is over at last — And the fever called \"Living\" Is conquered at last.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Keeping time, time, time, In a sort of Runic rhyme, To the tintinnabulation that so musically wells From the bells, bells, bells, bells, Bells, bells, bells.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Hear the mellow wedding bells Golden bells! What a world of happiness their harmony foretells Through the balmy air of night How they ring out their delight!", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Believe nothing you hear, and only one half that you see.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Lo! Death has reared himself a throne In a strange city lying alone Far down within the dim West, Where the good and the bad and the worst and the best Have gone to their eternal rest.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "So blend the turrets and shadows there That all seem pendulous in air, While from a proud tower in the town Death looks gigantically down.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Words have no power to impress the mind without the exquisite horror of their reality.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "\"Villains!\" I shrieked, \"dissemble no more! I admit the deed! — tear up the planks! — here, here! — it is the beating of his hideous heart!\"", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "I grew, day by day, more moody, more irritable, more regardless of the feelings of others. I suffered myself to use intemperate language to my wife. At length, I even offered her personal violence.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "If you wish to forget anything on the spot, make a note that this thing is to be remembered.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "How many good books suffer neglect through the inefficiency of their beginnings!", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "In reading some books we occupy ourselves chiefly with the thoughts of the author; in perusing others, exclusively with our own.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "I have great faith in fools — self-confidence my friends will call it.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "That man is not truly brave who is afraid either to seem or to be, when it suits him, a coward.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Ah, distinctly I remember it was in the bleak December; And each separate dying ember wrought its ghost upon the floor.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Sorrow for the lost Lenore — For the rare and radiant maiden whom the angels name Lenore — Nameless ''here'' for evermore.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And the silken sad uncertain rustling of each purple curtain Thrilled me — filled me with fantastic terrors never felt before.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Deep into that darkness peering, long I stood there, wondering, fearing, Doubting, dreaming dreams no mortal ever dared to dream before.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Perched upon a bust of Pallas, just above my chamber door,— Perched, and sat, and nothing more.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "\"Ghastly grim and ancient Raven wandering from the Nightly shore — Tell me what thy lordly name is on the Night's Plutonian shore!\" Quoth the Raven, \"Nevermore.\"", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "\"Doubtless,\" said I, \"what it utters is its only stock and store, Caught from some unhappy master whom unmerciful Disaster Followed fast and followed faster till his songs one burden bore.\"", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "\"Prophet!\" said I, \"thing of evil! — prophet still, if bird or devil!\"", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And the Raven, never flitting, still is sitting, ''still'' is sitting On the pallid bust of Pallas just above my chamber door.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And my soul from out that shadow that lies floating on the floor Shall be lifted — nevermore!", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Beauty is the sole legitimate province of the poem.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "The death then of a beautiful woman is unquestionably the most poetical topic in the world, and equally is it beyond doubt that the lips best suited for such topic are those of a bereaved lover.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "The skies they were ashen and sober; The leaves they were crisped and sere — The leaves they were withering and sere; It was night in the lonesome October Of my most immemorial year.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Here once, through an alley Titanic, Of cypress, I roamed with my Soul — Of cypress, with Psyche, my Soul.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "Thus I pacified Psyche and kissed her, And tempted her out of her gloom.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "And so, all the night-tide, I lie down by the side Of my darling — my darling — my life and my bride, In her sepulcher there by the sea — In her tomb by the sounding sea.", Author = "Edgar Allan Poe" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edgar_Allan_Poe", Text = "A poem deserves its title only inasmuch as it excites, by elevating the soul.", Author = "Edgar Allan Poe" },
        };
    }
}