using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class EdmundBurke
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Whenever a separation is made between liberty and justice, neither, in my opinion, is safe.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The people never give up their liberties but under some delusion.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Magnanimity in politics is not seldom the truest wisdom; and a great empire and little minds go ill together.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The writers against religion, whilst they oppose every system, are wisely careful never to set up any of their own.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Parties in religion and politics make sufficient discoveries concerning each other, to give a sober man a proper caution against them all.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "In vain you tell me that artificial government is good, but that I fall out only with the abuse. The thing! the thing itself is the abuse!", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Quis custodiet ipsos custodes?", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "These few have the passions of the one; and they unite to strengthen themselves, and to secure the gratification of their lawless passions at the expense of the general good.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The spirit which actuates all parties is the same; the spirit of ambition, of self-interest, of oppression, and treachery.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Evils we have had continually calling for reformation, and reformations more grievous than any evils.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "A good parson once said, that where mystery begins, religion ends. Cannot I say, as truly at least, of human laws, that where mystery begins, justice ends?", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The lawyers, as well as the theologians, have erected another reason besides natural reason; and the result has been, another justice besides natural justice.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Power gradually extirpates from the mind every humane and gentle virtue. Pity, benevolence, friendship, are things almost unknown in high stations.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The several species of government vie with each other in the absurdity of their constitutions, and the oppression which they make their subjects endure. Take them under what form you please, they are in effect but a despotism.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The nearer we approach to the goal of life, the better we begin to understand the true value of our existence, and the real weight of our opinions.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "A definition may be very exact, and yet go but a very little way towards informing us of the nature of the thing defined.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The first and the simplest emotion which we discover in the human mind is Curiosity.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "No passion so effectually robs the mind of all its powers of acting and reasoning as fear.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "When any work seems to have required immense force and labor to effect it, the idea is grand.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "A great profusion of things, which are splendid or valuable in themselves, is magnificent.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Custom reconciles us to every thing.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "There is a sort of enthusiasm in all projectors, absolutely necessary for their affairs, which makes them proof against the most fatiguing delays, the most mortifying disappointments, the most shocking insults.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "One may observe, that men of all persuasions confine the word persecution, and all the ill ideas of injustice and violence which belong to it, solely to those severities which are exercised upon themselves, or upon the party they are inclined to favour.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "In all persuasions the bigots are persecutors; the men of a cool and reasonable piety are favourers of toleration.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "When bad men combine, the good must associate; else they will fall one by one, an unpitied sacrifice in a contemptible struggle.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Laws, like houses, lean on one another.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "There is however a limit at which forbearance ceases to be a virtue.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "It is a general popular error to suppose the loudest complainers for the publick to be the most anxious for its welfare.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Toleration is good for all, or it is good for none.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "I take toleration to be a part of religion.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "But his unbiased opinion, his mature judgment, his enlightened conscience, he ought not to sacrifice to you, to any man, or to any set of men living.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Your representative owes you, not his industry only, but his judgment; and he betrays instead of serving you if he sacrifices it to your opinion.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Parliament is not a congress of ambassadors from different and hostile interests; but parliament is a deliberative assembly of one nation, with one interest, that of the whole.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "A conscientious man would be cautious how he dealt in blood.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "People crushed by law, have no hopes but from power. If laws are their enemies, they will be enemies to laws; and those who have much to hope and nothing to lose, will always be dangerous.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "It is an advantage to all narrow wisdom and narrow morals that their maxims have a plausible air; and, on a cursory view, appear equal to first principles.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Of this stamp is the cant of, Not men, but measures.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Public life is a situation of power and energy; he trespasses against his duty who sleeps upon his watch, as well as he that goes over to the enemy.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "To tax and to please, no more than to love and to be wise, is not given to men.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "It is the nature of all greatness not to be exact.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "I have in general no very exalted opinion of the virtue of paper government.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The concessions of the weak are the concessions of fear.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The use of force alone is but temporary. It may subdue for a moment; but it does not remove the necessity of subduing again: and a nation is not governed, which is perpetually to be conquered.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Abstract liberty, like other mere abstractions, is not to be found.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Religion, always a principle of energy, in this new people, is no way worn out or impaired; and their mode of professing it is also one main cause of this free spirit.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "It looks to me to be narrow and pedantic to apply the ordinary ideas of criminal justice to this great public contest. I do not know the method of drawing up an indictment against a whole people.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "It is not, what a lawyer tells me I may do; but what humanity, reason, and justice, tell me I ought to do.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "The march of the human mind is slow.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Freedom and not servitude is the cure of anarchy; as religion, and not atheism, is the true remedy for superstition.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "All government - indeed, every human benefit and enjoyment, every virtue and every prudent act - is founded on compromise and barter.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Slavery they can have anywhere. It is a weed that grows in every soil.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Deny them this participation of freedom, and you break that sole bond, which originally made, and must still preserve the unity of the empire.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Magnanimity in politics is not seldom the truest wisdom; and a great empire and little minds go ill together.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Strange incongruities must ever perplex those, who confound the unhappiness of civil dissensions with the crime of treason.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Liberty, if I understand it at all, is a general principle, and the clear right of all the subjects within the realm, or of none. Partial freedom seems to me a most invidious mode of slavery.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "But the true danger is, when liberty is nibbled away, for expedients, and by parts.", Author = "Edmund Burke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Edmund_Burke", Text = "Never expecting to find perfection in men, and not looking for divine attributes in created beings, in my commerce with my contemporaries, I have found much human virtue.", Author = "Edmund Burke" },
        };
    }
}
