using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class EleanorRoosevelt
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Do what you feel in your heart to be right — for you'll be criticized anyway. You'll be \"damned if you do, and damned if you don't.\"", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Understanding is a two-way street.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "It isn't enough to talk about peace. One must believe in it. And it isn't enough to believe in it. One must work at it.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Life was meant to be lived, and curiosity must be kept alive. One must never, for whatever reason, turn his back on life.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "I think, at a child's birth, if a mother could ask a fairy godmother to endow it with the most useful gift, that gift should be curiosity.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "When you cease to make a contribution, you begin to die.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Friendship with oneself is all-important, because without it one cannot be friends with anyone else in the world.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "When will our consciences grow so tender that we will act to prevent human misery rather than avenge it?", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "You get more joy out of the giving to others, and should put a good deal of thought into the happiness you are able to give.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "The most important thing in any relationship is not what you get but what you give.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "The purpose of life...is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "One's philosophy is not best expressed in words; it is expressed in the choices one makes. In stopping to think through the meaning of what I have learned, there is much that I believe intensely, much I am unsure of. In the long run, we shape our lives and we shape ourselves. The process never ends until we die. And, the choices we make are ultimately our own responsibility.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "One thing life has taught me: if you are interested, you never have to look for new interests. They come to you. … All you need to do is to be curious, receptive, eager for experience. And there's one strange thing: when you are genuinely interested in one thing, it will always lead to something else.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "You gain strength, courage, and confidence by every experience in which you really stop to look fear in the face. You are able to say to yourself, \"I have lived through this horror. I can take the next thing that comes along.\" … You must do the thing you think you cannot do.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "A mature person is one who does not think only in absolutes, who is able to be objective even when deeply stirred emotionally, who has learned that there is both good and bad in all people and all things, and who walks humbly and deals charitably with the circumstances of life, knowing that in this world no one is all-knowing and therefore all of us need both love and charity.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Happiness is not a goal, it is a by-product. Paradoxically, the one sure way not to be happy is deliberately to map out a way of life in which one would please oneself completely and exclusively.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "This freedom of which men speak, for which they fight, seems to some people a perilous thing. It has to be earned at a bitter cost and then — it has to be lived with. For freedom makes a huge requirement of every human being. With freedom comes responsibility.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "It takes courage to love, but pain through love is the purifying fire which those who love generously know.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "During prohibition I observed the law meticulously, but I came gradually to see that laws are only observed with the consent of the individuals concerned and a moral change still depends on the individual and not on the passage of any law.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Little by little it dawned upon me that this law was not making people drink any less, but it was making hypocrites and law breakers of a great number of people.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Will people ever be wise enough to refuse to follow bad leaders or to take away the freedom of other people?", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "No writing has any real value which is not the expression of genuine thought and feeling.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "When life is too easy for us, we must beware or we may not be ready to meet the blows which sooner or later come to everyone, rich or poor.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "I have a great belief in spiritual force, but I think we have to realize that spiritual force alone has to have material force with it so long as we live in a material world. The two together make a strong combination.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Sometimes I wonder if we shall ever grow up in our politics and say definite things which mean something, or whether we shall always go on using generalities to which everyone can subscribe, and which mean very little.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "One should always sleep in all of one's guest beds, to make sure that they are comfortable.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Long ago, I made up my mind that when things were said involving only me, I would pay no attention to them, except when valid criticism was carried by which I could profit.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "One of the blessings of age is to learn not to part on a note of sharpness, to treasure the moments spent with those we love, and to make them whenever possible good to remember, for time is short.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "At all times, day by day, we have to continue fighting for freedom of religion, freedom of speech, and freedom from want — for these are things that must be gained in peace as well as in war.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "One of the best ways of enslaving a people is to keep them from education... The second way of enslaving a people is to suppress the sources of information, not only by burning books but by controlling all the other ways in which ideas are transmitted.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Only a man's character is the real criterion of worth.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "I have never felt that anything really mattered but the satisfaction of knowing that you stood for the things in which you believed and had done the very best you could.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "I would not be very much surprised if some writers or actors or stagehands, or what not, were found to have Communist leanings, but I was surprised to find that, at the start of the inquiry, some of the big producers were so chicken-hearted about speaking up for the freedom of their industry. One thing is sure — none of the arts flourishes on censorship and repression. And by this time it should be evident that the American public is capable of doing its own censoring.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "The film industry is a great industry with infinite possibilities for good and bad. Its primary purpose is to entertain people. On the side, it can do many other things. It can popularize certain ideals, it can make education palatable. But in the long run, the judge who decides whether what it does is good or bad is the man or woman who attends the movies.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "What is going on in the Un-American Activities Committee worries me primarily because little people have become frightened and we find ourselves living in the atmosphere of a police state, where people close doors before they state what they think or look over their shoulders apprehensively before they express an opinion.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "In our country we must trust the people to hear and see both the good and the bad and to choose the good. The Un-American Activities Committee seems to me to be better for a police state than for the USA.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "The mobilization of world opinion and methods of negotiation should be developed and used by every nation in order to strengthen the United Nations.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "This is a time for action — not for war, but for mobilization of every bit of peace machinery. It is also a time for facing the fact that you cannot use a weapon, even though it is the weapon that gives you greater strength than other nations, if it is so destructive that it practically wipes out large areas of land and great numbers of innocent people.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "If the use of leisure time is confined to looking at TV for a few extra hours every day, we will deteriorate as a people.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "The arts in every field — music, drama, sculpture, painting — we can learn to appreciate and enjoy. We need not be artists, but we should be able to appreciate the work of artists.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "If man is to be liberated to enjoy more leisure, he must also be prepared to enjoy this leisure fully and creatively. For people to have more time to read, to take part in their civic obligations, to know more about how their government functions and who their officials are might mean in a democracy a great improvement in the democratic processes. Let's begin, then, to think how we can prepare old and young for these new opportunities. Let's not wait until they come upon us suddenly and we have a crisis that we will be ill prepared to meet.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "There is a widespread understanding among the people of this nation, and probably among the people of the world, that there is no safety except through the prevention of war.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "A consciousness of the fact that war means practically total destruction is the reason, I think, for the rising tide to prevent what seems such a senseless procedure.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "We should begin in our own environment and in our own community as far as possible to build a peace-loving attitude and learn to discipline ourselves to accept, in the small things of our lives, mediation and arbitration.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "As long as we are not actually destroyed, we can work to gain greater understanding of other peoples and to try to present to the peoples of the world the values of our own beliefs.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "We face the future fortified with the lessons we have learned from the past. It is today that we must create the world of the future.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Human resources are the most valuable assets the world has. They are all needed desperately.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "There never has been security. No man has ever known what he would meet around the next corner; if life were predictable it would cease to be life, and be without flavor.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "We must know what we think and speak out, even at the risk of unpopularity. In the final analysis, a democratic government represents the sum total of the courage and the integrity of its individuals. It cannot be better than they are.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "In the long run there is no more exhilarating experience than to determine one's position, state it bravely and then act boldly.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "What we must learn to do is to create unbreakable bonds between the sciences and the humanities. We cannot procrastinate. The world of the future is in our making. Tomorrow is now.", Author = "Eleanor Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Eleanor_Roosevelt", Text = "Example is the best lesson there is.", Author = "Eleanor Roosevelt" },
        };
    }
}