using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class EvelynWaugh
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The human mind is inspired enough when it comes to inventing horrors; it is when it tries to invent a Heaven that it shows itself cloddish.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "It is one of the facts of history that it is impossible for two peoples of widely different culture to live peaceably side by side. Sooner or later one must absorb the other. It is not necessarily the highest culture which survives. It is the more virile.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I believe it was a bad Government, rapidly deteriorating. If I were a Spaniard I should be fighting for General Franco.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "It is mischievous to suggest that such a choice is imminent.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "We prefer to harbour a grievance and vent our rage in moral lessons to our neighbours, eagerly accepting any extravagant report which will confirm our belief that foreigners as usual have behaved like cads.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I believe we are in danger of a...stultifying use of the word \"Fascist\".", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "My father taught me that it was flagitious to leave a letter of any kind unanswered.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "You can only leave God out by making your characters pure abstractions.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The failure of modern novelists since and including James Joyce is one of presumption and exorbitance.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "A novelist has no business with types; they are the property of economists and politicians and advertisers and the other professional bores of our period.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The artist is interested only in individuals.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The Common Man does not exist. He is an abstraction invented by bores for bores.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Don't give your opinions about Art and the Purpose of Life. They are of little interest and, anyway, you can't express them.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Don't analyze yourself. Give the relevant facts and let your readers make their own judgments.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Don't hold your parents up to contempt. After all, you are their son, and it is just possible that you may take after them.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Of children as of procreation- the pleasure momentary, the posture ridiculous, the expense damnable.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Manners are especially the need of the plain. The pretty can get away with anything.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "One can write, think and pray exclusively of others; dreams are all egocentric.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I think it great cheek of the Germans to try and teach the rest of the world anything about religion.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "They should be in perpetual sackcloth and ashes for all their enormities from Luther to Hitler.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "A typical triumph of modern science to find the only part of Randolph that was not malignant and remove it.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "When I first came into the Church I was drawn, not by splendid ceremonies but by the spectacle of the priest as a craftsman.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "He had an important job to do which none but he was qualified for.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "One participates in a work of art when one studies it with reverence and understanding.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I go to Rome for Easter (Grand Hotel) to avoid the horrors of the English liturgy.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "George Orwell wrote in 1942 at the height of his revulsion from what he regarded as the feeble hypocrisy of English socialist journalism.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I would ask him to consider that the function of the Church in every age has been conservative-to transmit undiminished and uncontaminated the creed inherited from its predecessors.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "It is natural to the Germans to make a row.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "We seek no \"Sieg Heils\". We pray in silence.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Participation\" means God hearing our voices.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Anyone who has taken part in a play knows that he can rant on the stage with his mind elsewhere.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "If the Germans want to be noisy, let them. But why should they disturb our devotions?", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Every attendance at Mass leaves me without comfort or edification.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I shall never, pray God, apostatise but church-going is now a bitter trial.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "They are destroying all that was superficially attractive about my Church.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "If you see Cardinal Bea spit in his eye.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I find the new liturgy a temptation against Faith, Hope and Charity but I shall never, pray God, apostatise.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "More than the aesthetic changes which rob the Church of poetry, mystery and dignity, there are suggested changes in Faith and morals which alarm me.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "A kind of anti-clericalism is abroad which seeks to reduce the priest's unique sacramental position.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The Mass is written of as a \"social meal\" in which the \"people of God\" perform the consecration.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I can only now go to church as an act of duty and obedience.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I have become very old in the last two years. Not diseased but enfeebled.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "The Vatican Council has knocked the guts out of me.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Easter used to mean so much to me.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Before Pope John and his Council - they destroyed the beauty of the liturgy.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I have not yet soaked myself in petrol and gone up in flames, but I now cling to the Faith doggedly without joy.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Church going is a pure duty parade.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I shall not live to see it restored.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I put the words down and push them a bit.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Aesthetic value is often the by-product of the artist striving to do something else.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Punctuality is the virtue of the bored.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "We cherish our friends not for their ability to amuse us, but for ours to amuse them -- a diminishing number in my case.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "There is a great deal to be said for the Arts. For one thing they offer the only career in which commercial failure is not necessarily discreditable.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Please bear in mind throughout that IT IS MEANT TO BE FUNNY.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I couldn't understand why God had made the world at all... I asked my bishop; he didn't know.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I'm one of the blind alleys off the main road of procreation.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I don't believe that people would ever fall in love or want to be married if they hadn't been told about it.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "There is a species of person called a 'Modern Churchman' who draws the full salary of a beneficed clergyman and need not commit himself to any religious belief", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "That's the public-school system all over. They may kick you out, but they never let you down.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Instead of this absurd division into sexes they ought to class people as static and dynamic.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I came to the conclusion many years ago that almost all crime is due to the repressed desire for aesthetic expression.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "I expect you'll be becoming a schoolmaster, sir. That's what most of the gentlemen does, sir, that gets sent down for indecent behaviour.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Anyone who has been to an English public school will always feel comparatively at home in prison.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "It is a curious thing... that every creed promises a paradise which will be absolutely uninhabitable for anyone of civilized taste.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "All this fuss about sleeping together. For physical pleasure I'd sooner go to my dentist any day.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "You never find an Englishman among the under-dogs-except in England, of course.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "In the dying world I come from, quotation is a national vice.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "It may happen in the next hundred years that the English novelists of the present day will come to be valued as we now value the artists and craftsmen of the late eighteenth century.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "He abhorred plastics, Picasso, sunbathing and jazz - everything in fact that had happened in his own lifetime.", Author = "Evelyn Waugh" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Evelyn_Waugh", Text = "Only when one has lost all curiosity about the future has one reached the age to write an autobiography.", Author = "Evelyn Waugh" },
        };
    }
}