using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class FriedrichNietzsche
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Here the ways of men part: if you wish to strive for peace of soul and pleasure, then believe; if you wish to be a devotee of truth, then inquire.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "it is precisely facts that do not exist, only interpretations.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "There are no facts, only interpretations.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Style ought to prove that one believes in an idea; not only that one thinks it but also feels it.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Mathematics would certainly have not come into existence if one had known from the beginning that there was in nature no exactly straight line, no actual circle, no absolute magnitude.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "He who fights with monsters should see to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Is not life a hundred times too short for us— to bore ourselves?", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "We imagine that hardness, violence, slavery, peril in the street and in the heart, concealment, Stoicism, temptation, and deviltry of every sort, everything evil, frightful, tyrannical, raptor- and snake-like in man, serves as well for the advancement of the species \"man\" as their opposite.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Although the most acute judges of the witches and even the witches themselves, were convinced of the guilt of witchery, the guilt nevertheless was non-existent. It is thus with all guilt.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Free will without fate is no more conceivable than spirit without matter, good without evil.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "As soon as it becomes possible, by dint of a strong will, to overthrow the entire past of the world, then, in a single moment, we will join the ranks of independent gods. World history for us will then be nothing but a dreamlike otherworldly being. The curtain falls, and man once more finds himself a child playing with whole worlds—a child, awoken by the first glow of morning, who laughingly wipes the frightful dreams from his brow.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "All truths are bloody truths to me—take a look at my previous writings.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "That which does not kill us makes us stronger.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "I imagine the sufferings of others as far greater than they really are. Ever since my childhood, the proposition ‘my greatest dangers lie in pity’ has been confirmed again and again.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Art is the supreme task and the truly metaphysical activity in this life...", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Thus the man who is responsive to artistic stimuli reacts to the reality of dreams as does the philosopher to the reality of existence; he observes closely, and he enjoys his observation: for it is out of these images that he interprets life, out of these processes that he trains himself for life. It is not only pleasant and agreeable images that he experiences with such universal understanding: the serious, the gloomy, the sad and the profound, the sudden restraints, the mockeries of chance, fearful expectations, in short the whole 'divine comedy' of life, the Inferno included, passes before him, not only as a shadow-play — for he too lives and suffers through these scenes — and yet also not without that fleeting sense of illusion; and perhaps many, like myself, can remember calling out to themselves in encouragement, amid the perils and terrors of the dream, and with success: 'It is a dream! I want to dream on!' Just as I have often been told of people who have been able to continue one and the same dream over three and more successive nights: facts which clearly show that our innermost being, our common foundation, experiences dreams with profound pleasure and joyful necessity.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Miserable, ephemeral race, children of hazard and hardship, why do you force me to say what it would be much more fruitful for you not to hear? The best of all things is something entirely outside your grasp: not to be born, not to be, to be nothing. But the second-best thing for you — is to die soon.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Underneath this reality in which we live and have our being, another and altogether different reality lies concealed...", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Greek tragedy met her death in a different way from all the older sister arts: she died tragically by her own hand, after irresolvable conflicts, while the others died happy and peaceful at an advanced age. If a painless death, leaving behind beautiful progeny, is the sign of a happy natural state, then the endings of the other arts show us the example of just such a happy natural state: they sink slowly, and with their dying eyes they behold their fairer offspring, who lift up their heads in bold impatience. The death of Greek tragedy, on the other hand, left a great void whose effects were felt profoundly, far and wide; as once Greek sailors in Tiberius' time heard the distressing cry 'the god Pan is dead' issuing from a lonely island, now, throughout the Hellenic world, this cry resounded like an agonized lament: 'Tragedy is dead! Poetry itself died with it! Away, away with you, puny, stunted imitators! Away with you to Hades, and eat your fill of the old masters' crumbs!'", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "...aesthetic Socratism, the chief law of which is, more or less: \"to be beautiful everything must first be intelligible\" — a parallel to the Socratic dictum: \"only the one who knows is virtuous.\"", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "But for Socrates, tragedy did not even seem to \"tell what's true\", quite apart from the fact that it addresses \"those without much wit\", not the philosopher: another reason for giving it a wide berth. Like Plato, he numbered it among the flattering arts which represent only the agreeable, not the useful, and therefore required that his disciples abstain most rigidly from such unphilosophical stimuli — with such success that the young tragedian, Plato, burnt his writings in order to become a pupil of Socrates.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Lessing, the most honest of theoretical men, dared to say that he took greater delight in the quest for truth than in the truth itself.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "We cannot help but see Socrates as the turning-point, the vortex of world history. For if we imagine that the whole incalculable store of energy used in that global tendency had been used not in the service of knowledge but in ways applied to the practical — selfish — goals of individuals and nations, universal wars of destruction and constant migrations of peoples would have enfeebled man's instinctive zest for life to the point where, suicide having become universal, the individual would perhaps feel a vestigial duty as a son to strangle his parents, or as a friend his friend, as the Fiji islanders do: a practical pessimism that could even produce a terrible ethic of genocide through pity, and which is, and always has been, present everywhere in the world where art has not in some form, particularly as religion and science, appeared as a remedy and means of prevention for this breath of pestilence.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "But what changes come upon the weary desert of our culture, so darkly described, when it is touched by the magic of Dionysus! A storm seizes everything decrepit, rotten, broken, stunted; shrouds it in a whirling red cloud of dust and carries it into the air like a vulture. In vain confusion we seek for all that has vanished; for what we see has risen as if from beneath he earth into the gold light, so full and green, so luxuriantly alive, immeasurable and filled with yearning. Tragedy sits in sublime rapture amidst this abundance of life, suffering and delight, listening to a far-off, melancholy song which tells of the Mothers of Being, whose names are Delusion, Will, Woe''. - Yes, my friends, join me in my faith in this Dionysiac life and the rebirth of tragedy. The age of Socratic man is past: crown yourselves with ivy, grasp the thyrsus and do not be amazed if tigers and panthers lie down fawning at your feet. Now dare to be tragic men, for you will be redeemed. You shall join the Dionysiac procession from India to Greece! Gird yourselves for a hard battle, but have faith in the miracles of your god!", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Philological considerations have slowly but surely taken the place of profound explorations of eternal problems. The question becomes: What did this or that philosopher think or not think? And is this or that text rightly ascribed to him or not? And even: Is this variant of a classical text preferable to that other? Students in university seminars today are encouraged to occupy themselves with such emasculated inquiries. As a result, of course, philosophy itself is banished from the university altogether.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "In some remote corner of the universe, poured out and glittering in innumerable solar systems, there once was a star on which clever animals invented knowledge. That was the highest and most mendacious minute of \"world history\" — yet only a minute. After nature had drawn a few breaths the star grew cold, and the clever animals had to die. One might invent such a fable and still not have illustrated sufficiently how wretched, how shadowy and flighty, how aimless and arbitrary, the human intellect appears in nature. There have been eternities when it did not exist; and when it is done for again, nothing will have happened.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "The pride connected with knowing and sensing lies like a blinding fog over the eyes and senses of men, thus deceiving them concerning the value of existence. For this pride contains within itself the most flattering estimation of the value of knowing. Deception is the most general effect of such pride, but even its most particular effects contain within themselves something of the same deceitful character.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "The liar is a person who uses the valid designations, the words, in order to make something which is unreal appear to be real. He says, for example, \"I am rich,\" when the proper designation for his condition would be \"poor.\" He misuses fixed conventions by means of arbitrary substitutions or even reversals of names. If he does this in a selfish and moreover harmful manner, society will cease to trust him and will thereby exclude him. What men avoid by excluding the liar is not so much being defrauded as it is being harmed by means of fraud. Thus, even at this stage, what they hate is basically not deception itself, but rather the unpleasant, hated consequences of certain sorts of deception. It is in a similarly restricted sense that man now wants nothing but truth: he desires the pleasant, life-preserving consequences of truth. He is indifferent toward pure knowledge which has no consequences; toward those truths which are possibly harmful and destructive he is even hostilely inclined.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Are designations congruent with things? Is language the adequate expression of all realities? It is only by means of forgetfulness that man can ever reach the point of fancying himself to possess a \"truth\" of the grade just indicated. If he will not be satisfied with truth in the form of tautology, that is to say, if he will not be content with empty husks, then he will always exchange truths for illusions.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "The various languages placed side by side show that with words it is never a question of truth, never a question of adequate expression; otherwise, there would not be so many languages. The \"thing in itself\" (which is precisely what the pure truth, apart from any of its consequences, would be) is likewise something quite incomprehensible to the creator of language and something not in the least worth striving for. This creator only designates the relations of things to men, and for expressing these relations he lays hold of the boldest metaphors. To begin with, a nerve stimulus is transferred into an image: first metaphor. The image, in turn, is imitated in a sound: second metaphor. And each time there is a complete overleaping of one sphere, right into the middle of an entirely new and different one.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "We believe that we know something about the things themselves when we speak of trees, colors, snow, and flowers; and yet we possess nothing but metaphors for things — metaphors which correspond in no way to the original entities.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Every word instantly becomes a concept precisely insofar as it is not supposed to serve as a reminder of the unique and entirely individual original experience to which it owes its origin; but rather, a word becomes a concept insofar as it simultaneously has to fit countless more or less similar cases — which means, purely and simply, cases which are never equal and thus altogether unequal. Every concept arises from the equation of unequal things. Just as it is certain that one leaf is never totally the same as another, so it is certain that the concept \"leaf\" is formed by arbitrarily discarding these individual differences and by forgetting the distinguishing aspects.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "We obtain the concept, as we do the form, by overlooking what is individual and actual; whereas nature is acquainted with no forms and no concepts, and likewise with no species, but only with an X which remains inaccessible and undefinable for us.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "What then is truth? A movable host of metaphors, metonymies, and anthropomorphisms: in short, a sum of human relations which have been poetically and rhetorically intensified, transferred, and embellished, and which, after long usage, seem to a people to be fixed, canonical, and binding. Truths are illusions which we have forgotten are illusions — they are metaphors that have become worn out and have been drained of sensuous force, coins which have lost their embossing and are now considered as metal and no longer as coins.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "As a \"rational\" being, he now places his behavior under the control of abstractions. He will no longer tolerate being carried away by sudden impressions, by intuitions.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Everything which distinguishes man from the animals depends upon this ability to volatilize perceptual metaphors in a schema, and thus to dissolve an image into a concept. For something is possible in the realm of these schemata which could never be achieved with the vivid first impressions: the construction of a pyramidal order according to castes and degrees, the creation of a new world of laws, privileges, subordinations, and clearly marked boundaries — a new world, one which now confronts that other vivid world of first impressions as more solid, more universal, better known, and more human than the immediately perceived world, and thus as the regulative and imperative world.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "One may certainly admire man as a mighty genius of construction, who succeeds in piling an infinitely complicated dome of concepts upon an unstable foundation, and, as it were, on running water. Of course, in order to be supported by such a foundation, his construction must be like one constructed of spiders' webs: delicate enough to be carried along by the waves, strong enough not to be blown apart by every wind.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "As a genius of construction man raises himself far above the bee in the following way: whereas the bee builds with wax that he gathers from nature, man builds with the far more delicate conceptual material which he first has to manufacture from himself.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "When someone hides something behind a bush and looks for it again in the same place and finds it there as well, there is not much to praise in such seeking and finding. Yet this is how matters stand regarding seeking and finding \"truth\" within the realm of reason. If I make up the definition of a mammal, and then, after inspecting a camel, declare \"look, a mammal\" I have indeed brought a truth to light in this way, but it is a truth of limited value. That is to say, it is a thoroughly anthropomorphic truth which contains not a single point which would be \"true in itself\" or really and universally valid apart from man. At bottom, what the investigator of such truths is seeking is only the metamorphosis of the world into man.", Author = "Friedrich Nietzsche" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Nietzsche", Text = "Only by forgetting this primitive world of metaphor can one live with any repose, security, and consistency: only by means of the petrification and coagulation of a mass of images which originally streamed from the primal faculty of human imagination like a fiery liquid, only in the invincible faith that this sun, this window, this table is a truth in itself, in short, only by forgetting that he himself is an artistically creating subject, does man live with any repose, security, and consistency. If but for an instant he could escape from the prison walls of this faith, his \"self consciousness\" would be immediately destroyed. It is even a difficult thing for him to admit to himself that the insect or the bird perc", Author = "Friedrich Nietzsche" },
        };
    }
}