using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class FriedrichEngels
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The history of all hitherto existing society is the history of class struggles.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Freedom does not consist in any dreamt-of independence from natural laws, but in the knowledge of these laws, and in the possibility this gives of systematically making them work towards definite ends.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Hegel was the first to state correctly the relation between freedom and necessity. To him, freedom is the insight into necessity.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "What each individual wills is obstructed by everyone else, and what emerges is something that no one willed.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Terror consists mostly of useless cruelties perpetrated by frightened people in order to reassure themselves.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Only sound common sense, respectable fellow that he is, in the homely realm of his own four walls, has very wonderful adventures directly he ventures out into the wide world of research.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The state is not \"abolished,\" it withers away.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The anarchists put the thing upside down. They declare that the proletarian revolution must begin by doing away with the political organisation of the state. But after its victory the sole organisation which the proletariat finds already in existence is precisely the state.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "It is no longer a question anywhere of inventing interconnections from out of our brains, but of discovering them in the facts.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "By bourgeoisie is meant the class of modern capitalists, owners of the means of social production and employers of wage labor. By proletariat, the class of modern wage laborers who, having no means of production of their own, are reduced to selling their labor power in order to live.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The first act by virtue of which the State really constitutes itself the representative of the whole of society - the taking possession of the means of production in the name of society - this is, at the same time, its last independent act as a State.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "History has proved us, and all who thought like us, wrong. It has made it clear that the state of economic development on the Continent at that time [1848] was not, by a long way, ripe for the removal of capitalist production.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The irony of world history turns everything upside down. We, the \"revolutionaries,\" the \"rebels\" - we are thriving far better on legal methods than on illegal methods and revolt.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Political economy came into being as a natural result of the expansion of trade, and with its appearance elementary, unscientific huckstering was replaced by a developed system of licensed fraud, an entire science of enrichment.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "This political economy or science of enrichment born of the merchants' mutual envy and greed, bears on its brow the mark of the most detestable selfishness.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The Mercantile System still had a certain artless Catholic candour and did not in the least conceal the immoral nature of trade. ... But when the economic Luther, Adam Smith, criticised past economics things had changed considerably. ... Protestant hypocrisy took the place of Catholic candour.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Naturally, it is in the interest of the trader to be on good terms with the one from whom he buys cheap as well as with the other to whom he sells dear. A nation therefore acts very imprudently if it fosters feelings of animosity in its suppliers and customers.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "You have destroyed the small monopolies so that the one great basic monopoly, property, may function the more freely and unrestrictedly. You have civilised the ends of the earth to win new terrain for the deployment of your vile avarice.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The economist's \"demand\" is not the real demand; his \"consumption\" is an artificial consumption. For the economist, only that person really demands, only that person is a real consumer, who has an equivalent to offer for what he receives.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The bourgeoisie has gained a monopoly of all means of existence in the broadest sense of the word. What the proletarian needs, he can obtain only from this bourgeoisie, which is protected in its monopoly by the power of the state.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "I have never seen a class so deeply demoralised, so incurably debased by selfishness, so corroded within, so incapable of progress, as the English bourgeoisie; and I mean by this, especially the bourgeoisie proper, particularly the Liberal, Corn Law repealing bourgeoisie.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The way in which the vast mass of the poor are treated by modern society is truly scandalous. They are herded into great cities where they breathe a fouler air than in the countryside which they have left.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "How is it possible that the poorer classes can remain healthy and have a reasonable expectation of life under such conditions? What can one expect but that they should suffer from continual outbreaks of epidemics and an excessively low expectation of life?", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The bourgeoisie is charitable out of self-interest; it gives nothing outright, but regards its gifts as a business matter, makes a bargain with the poor, saying: \"If I spend this much upon benevolent institutions, I thereby purchase the right not to be troubled any further.\"", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "True, the law is sacred to the bourgeois, for it is his own composition, enacted with his consent, and for his benefit and protection.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Communism is the doctrine of the conditions of the liberation of the proletariat.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "There have always been poor and working classes; and the working class have mostly been poor. But there have not always been workers and poor people living under conditions as they are today.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The capitalists soon had everything in their hands and nothing remained to the workers.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Labor is a commodity, like any other, and its price is therefore determined by exactly the same laws that apply to other commodities.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The slave is sold once and for all; the proletarian must sell himself daily and hourly.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The slave frees himself when, of all the relations of private property, he abolishes only the relation of slavery and thereby becomes a proletarian; the proletarian can free himself only by abolishing private property in general.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Big industry has brought all the people of the Earth into contact with each other, has merged all local markets into one world market, has spread civilization and progress everywhere and has thus ensured that whatever happens in civilized countries will have repercussions in all other countries.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Wherever big industries displaced manufacture, the bourgeoisie developed in wealth and power to the utmost and made itself the first class of the country.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "The introduction of free competition is thus public declaration that from now on the members of society are unequal only to the extent that their capitals are unequal, that capital is the decisive power, and that therefore the capitalists, the bourgeoisie, have become the first class in society.", Author = "Friedrich Engels" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Friedrich_Engels", Text = "Every change in the social order, every revolution in property relations, is the necessary consequence of the creation of new forces of production which no longer fit into the old property relations.", Author = "Friedrich Engels" },
        };
    }
}
