using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class FScottFitzgerald
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "The idea that to make a man work you've got to hold gold in front of his eyes is a growth, not an axiom. We’ve done that for so long that we've forgotten there’s any other way.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Let me tell you about the very rich. They are different from you and me.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "There are no second acts in American lives.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "People try so hard to believe in leaders now, pitifully hard. But we no sooner get a popular reformer or politician or soldier or writer or philosopher — a Roosevelt, a Tolstoy, a Wood, a Shaw, a Nietzsche, than the cross-currents of criticism wash him away. My Lord, no man can stand prominence these days. It's the surest path to obscurity.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Here was a new generation, shouting the old cries, learning the old creeds, through a revery of long days and nights; destined finally to go out into that dirty gray turmoil to follow love and pride; a new generation dedicated more than the last to the fear of poverty and the worship of success; grown up to find all Gods dead, all wars fought, all faiths in man shaken. . . .", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "The victor belongs to the spoils.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "All life was weather, a waiting through the hot where events had no significance for the cool that was soft and caressing like a woman's hand on a tired forehead.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "I have it upon the best authority that for a brief space Mr. In and Mr. Out lived, breathed, answered to their names and radiated vivid personalities of their own.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "You're a historian. Tell me if there are any bath-tubs in history. I think they've been frightfully neglected.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "My father has a diamond bigger than the Ritz-Carlton Hotel.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "It was an amazing predicament. He was, in one sense, the richest man that ever lived — and yet was he worth anything at all?", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "At any rate, let us love for a while, for a year or so, you and me. That's a form of divine drunkenness that we can all try. There are only diamonds in the whole world, diamonds and perhaps the shabby gift of disillusion.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "As this was an inane and unanswerable argument Benjamin made no reply, and from that time on a chasm began to widen between them.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "The years between thirty-five and sixty-five revolve before the passive mind as one unexplained, confusing merry-go-round.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "He knew now that he had always been a fool.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "But it was too late. He had angered Providence by resisting too many temptations. There was nothing left but heaven, where he would meet only those who, like him, had wasted earth.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "It was a marriage of love. He was sufficiently spoiled to be charming; she was ingenuous enough to be irresistible.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Summer was gone and now Indian summer. The grass was cold and there was no mist and no dew. After he left she would go in and light the gas and close the shatters, and he would go down the path and on to the village. To these two life had come quickly and gone, leaving not bitterness, but pity; not disillusion, but only pain.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "I care not who hoes the lettuce of my country if I can eat the salad!", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Family quarrels are bitter things. They don't go according to any rules. They are not like aches or wounds; they are more like splits in the skin that won't heal because there is not enough material.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Whenever you feel like criticizing any one... just remember that all the people in this world haven't had the advantages that you've had.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "So we beat on, boats against the current, borne back ceaselessly into the past.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "One writes of scars healed, a loose parallel to the pathology of the skin, but there is no such thing in the life of an individual.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Either you think — or else others have to think for you and take power from you, pervert and discipline your natural tastes, civilize and sterilize you.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "In a real dark night of the soul it is always three o'clock in the morning, day after day.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Before I go on with this short history, let me make a general observation – the test of a first-rate intelligence is the ability to hold two opposed ideas in the mind at the same time, and still retain the ability to function.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Genius goes around the world in its youth incessantly apologizing for having large feet. What wonder that later in life it should be inclined to raise those feet too swiftly to fools and bores.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "All life is just a progression toward, and then a recession from, one phrase— 'I love you.'", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "His was a great sin who first invented consciousness. Let us lose it for a few hours.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "It isn't given for us to know those rare moments when people are wide open and the lightest touch can wither or heal. A moment too late and we can never reach them any more in this world. They will not be cured by our most efficacious drugs or slain with our sharpest swords.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "All good writing is swimming under water and holding your breath.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "I fell in love with her courage, her sincerity and her flaming self-respect. And it's these things I’d believe in, even if the whole world indulged in wild suspicions that she wasn’t all she should be. But of course the real reason, Isabelle, is that I love her and that’s the beginning and end of everything. You’re still a Catholic, but Zelda’s the only God I have left now.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "It takes a genius to whine appealingly.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "I hate the place like poison with a sincere hatred.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "I have never been able to forgive the rich for being rich, and it has colored my entire life and works.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "My generation of radicals and breakers-down never found anything to take the place of the old virtues of work and courage and the old graces of courtesy and politeness.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Once one is caught up into the material world not one person in ten thousand finds the time to form literary taste, to examine the validity of philosophic concepts for himself, or to form what, for lack of a better phrase, I might call the wise and tragic sense of life.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Isn’t Hollywood a dump — in the human sense of the word. A hideous town, pointed up by the insulting gardens of its rich, full of the human spirit at a new low of debasement.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "How strange to have failed as a social creature — even criminals do not fail that way — they are the law's \"Loyal Opposition,\" so to speak. But the insane are always mere guests on earth, eternal strangers carrying around broken decalogues that they cannot read.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Great art is the contempt of a great man for small art.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "Show me a hero and I will write you a tragedy.", Author = "F. Scott Fitzgerald" },
            new Quote { Id = "https://en.wikiquote.org/wiki/F._Scott_Fitzgerald", Text = "It is in the thirties that we want friends. In the forties we know they won't save us any more than love did.", Author = "F. Scott Fitzgerald" },
        };
    }
}