using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class GalileoGalilei
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "I do not feel obliged to believe that the same God who has endowed us with senses, reason, and intellect has intended us to forgo their use and by some other means to give us knowledge which we can attain by them.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "You cannot teach a man anything, you can only help him to find it within himself.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Philosophy is written in that great book which ever lies before our eyes — I mean the universe — but we cannot understand it if we do not first learn the language and grasp the symbols, in which it is written.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "All truths are easy to understand once they are discovered; the point is to discover them.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "The increase of known truths stimulates the investigation, establishment, and growth of the arts; not their diminution or destruction.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Nature … is inexorable and immutable; she never transgresses the laws imposed upon her, or cares a whit whether her abstruse reasons and methods of operation are understandable to men.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "The intention of the Holy Ghost is to teach us how one goes to heaven, not how heaven goes.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Philosophy is written in this grand book — I mean the universe — which stands continually open to our gaze, but it cannot be understood unless one first learns to comprehend the language in which it is written.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "A bucketful of water raised on high and set free, returns to the sea; but who will say that the same water remains heavy in the sea, when being set free there, does not move?", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "It always seems to me extreme rashness on the part of some when they want to make human abilities the measure of what nature can do.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "This vain presumption of understanding everything can have no other basis than never understanding anything.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "To apply oneself to great inventions, starting from the smallest beginnings, is no task for ordinary minds; to divine that wonderful arts lie hid behind trivial and childish things is a conception for superhuman talents.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "I consider the earth very noble and admirable precisely because of the diverse alterations, changes, generations, etc. that occur in it incessantly.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "What greater stupidity can be imagined than that of calling jewels, silver, and gold \"precious,\" and earth and soil \"base\"?", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "If you could see the earth illuminated when you were in a place as dark as night, it would look to you more splendid than the moon.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Beside themselves with passion, some of them would not be backward even about scheming to suppress and silence their adversaries.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "The sun, with all those planets revolving around it and dependent on it, can still ripen a bunch of grapes as if it had nothing else in the universe to do.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "With regard to those few [propositions] which the human intellect does understand, I believe its knowledge equals the Divine in objective certainty, for here it succeeds in understanding necessity, beyond which there can be no greater sureness.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "I cannot find any bounds for my admiration, how that reason was able in Aristarchus and Copernicus, to commit such a rape on their senses, as in despite thereof to make herself mistress of their credulity.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Who knows but men will reduce me from the profession of a philosopher to that of historian of the Inquisition!", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "Let us see how it might be demonstrated that in a finite continuous extension it is not impossible for infinitely many voids to be found.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "If I were again beginning my studies, I should follow the advice of Plato and start with mathematics, a science which proceeds very cautiously and admits nothing as established until it has been rigidly demonstrated.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "There is, in nature, perhaps nothing older than motion, concerning which the books written by philosophers are neither few nor small; nevertheless I have discovered by experiment some properties of it which are worth knowing and which have not hitherto been either observed or demonstrated.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "No one has yet pointed out that this path [of projectiles] is a parabola.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "This experimentation is the custom—and properly so—in those sciences where mathematical demonstrations are applied to natural phenomena.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "See now the power of truth; the same experiment which at first glance seemed to show one thing, when more carefully examined, assures us of the contrary.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "I wonder not a little how such a question escaped the attention of Archimedes, Apollonius, Euclid and so many other mathematicians and illustrious philosophers, especially since so many ponderous tomes have been devoted to the subject of motion.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "This bounded terminal speed will be called the maximum that such a heavy body can naturally attain through the air...", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "I esteem myself happy to have as great an ally as you in my search for truth.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "In the sciences the authority of thousands of opinions is not worth the humble reasoning of a single individual.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "My dear Kepler, what would you say of the learned here, who, replete with the pertinacity of the asp, have steadfastly refused to cast a glance through the telescope?", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "What shall we make of this? Shall we laugh, or shall we cry?", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "In questions of science the authority of a thousand is not worth the humble reasoning of a single individual.", Author = "Galileo Galilei" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Galileo_Galilei", Text = "We seek not what God could have done but what He has done.", Author = "Galileo Galilei" },
        };
    }
}