using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class HenryDavidThoreau
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Let us not underrate the value of a fact; it will one day flower in a truth.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The life that I aspire to live No man proposeth me— No trade upon the street Wears its emblazonry.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "When will the world learn that a million men are of no importance compared with one man?", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The law will never make men free; it is men who have got to make the law free.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "It is not enough to be industrious; so are the ants. What are you industrious about?", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Not that the story need be long, but it will take a long while to make it short.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "If a man believes and expects great things of himself, it makes no odds where you put him, or what you show him ... he will be surrounded by grandeur.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "I am enjoying existence as much as ever, and regret nothing.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "A gun gives you the body, not the bird.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Truth, Goodness, Beauty — those celestial thrins, Continually are born'; e'en now the Universe, With thousand throats, and eke with greener smiles, Its joy confesses at their recent birth.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "That virtue we appreciate is as much ours as another's. We see so much only as we possess.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Aeschylus had a clear eye for the commonest things. His genius was only an enlarged common sense. [...] The multitude that thronged the theatre could no doubt go along with him to the end...", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "An early morning walk is a blessing for the whole day.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Who looks in the sun will see no light else; but also he will see no shadow. Our life revolves unceasingly, but the centre is ever the same, and the wise will regard only the seasons of the soul.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "We are as much as we see. Faith is sight and knowledge. The hands only serve the eyes.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "It is a great art to saunter.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "For many years I was self-appointed inspector of snowstorms and rainstorms, and did my duty faithfully, though I never received one cent for it.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Disobedience is the true foundation of liberty. The obedient must be slaves.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "How vain it is to sit down to write when you have not stood up to live.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Nothing is so much to be feared as fear. Atheism may comparatively be popular with God himself.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The bluebird carries the sky on his back.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The perception of beauty is a moral test.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Fire is the most tolerable third party.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Some circumstantial evidence is very strong, as when you find a trout in the milk.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Nature is full of genius, full of the divinity; so that not a snowflake escapes its fashioning hand.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "That man is the richest whose pleasures are the cheapest.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "It is in vain to dream of a wildness distant from ourselves.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The savage in man is never quite eradicated.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Any fool can make a rule And every fool will mind it.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Law never made men a whit more just; and, by means of their respect for it, even the well-disposed are daily made the agents of injustice.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Any man more right than his neighbors constitutes a majority of one.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Thus the state never intentionally confronts a man's sense, intellectual or moral, but only his body, his senses. It is not armed with superior wit or honesty, but with superior physical strength.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "When I meet a government which says to me, ‘Your money or your life,’ why should I be in haste to give it my money?", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "I am as desirous of being a good neighbor as I am of being a bad subject.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The progress from an absolute to a limited monarchy, from a limited monarchy to a democracy, is a progress toward a true respect for the individual.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The rich man... is always sold to the institution which makes him rich.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "if it is of such a nature that it requires you to be the agent of injustice to another, then I say, break the law. Let your life be a counter-friction to stop the machine.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "You can hardly convince a man of an error in a lifetime, but must content yourself with the reflection that the progress of science is slow. If he is not convinced, his grandchildren may be.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Men reverence one another, not yet God.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The wisest man preaches no doctrines; he has no scheme; he sees no rafter, not even a cobweb, against the heavens. It is clear sky.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Some old poet's grand imagination is imposed on us as adamantine everlasting truth, and God's own word!", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The mass of men lead lives of quiet desperation. What is called resignation is confirmed desperation.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Most of the luxuries, and many of the so-called comforts of life, are not only not indispensable, but positive hindrances to the elevation of mankind.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Men remain in their present low and primitive condition; but if they should feel the influence of the spring of springs arousing them, they would of necessity rise to a higher and more ethereal life.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Our inventions are wont to be pretty toys, which distract our attention from serious things. They are but improved means to an unimproved end, an end which it was already but too easy to arrive at.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "If I knew for a certainty that a man was coming to my house with the conscious design of doing me good, I should run for my life.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Simplify, simplify.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Money is not required to buy one necessity of the soul.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Only that day dawns to which we are awake. There is more day to dawn. The sun is but a morning star.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "It takes two to speak the truth, — one to speak, and another to hear.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "This world is but canvas to our imaginations.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Dreams are the touchstones of our characters.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Go where we will on the ''surface'' of things, men have been there before us.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "A true account of the actual is the rarest poetry, for common sense always takes a hasty and superficial view.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "Poetry is the mysticism of mankind.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "The unconsciousness of man is the consciousness of God.", Author = "Henry David Thoreau" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Henry_David_Thoreau", Text = "My life has been the poem I would have writ, But I could not both live and utter it.", Author = "Henry David Thoreau" },
        };
    }
}