using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class HLMencken
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "School teachers, taking them by and large, are probably the most ignorant and stupid class of men in the whole group of mental workers.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Explanations exist; they have existed for all time; there is always a well-known solution to every human problem - neat, plausible, and wrong.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The final test of truth is ridicule. Very few dogmas have ever faced it and survived.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "No healthy man, in his secret heart, is content with his destiny. He is tortured by dreams and images as a child is tortured by the thought of a state of existence in which it would live in a candy store and have two stomachs.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "An idealist is one who, on noticing that a rose smells better than a cabbage, concludes that it is also more nourishing.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The allurement that women hold out to men is precisely the allurement that Cape Hatteras holds out to sailors: they are enormously dangerous and hence enormously fascinating.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Democracy is the theory that the common people know what they want, and deserve to get it good and hard.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Of all escape mechanisms, death is the most efficient.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "It is a fact that no man improves much after the age of 60 and after 65, most suffer a really alarming decline. I could give some examples, but at the advice of my publisher will refrain from doing so.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Progress: The process whereby the human race has got rid of whiskers, the vermiform appendix and God.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Socialism is the theory that the desire of one man to get something he hasn't got is more pleasing to a just God than the desire of some other man to keep what he has got.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The objection to Puritans is not that they try to make us think as they do, but that they try to make us do as they think.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "At the bottom of Puritanism one finds envy of the fellow who is having a better time in the world, and hence hatred of him. At the bottom of democracy one finds the same thing. This is why all Puritans are democrats and all democrats are Puritans.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Truth would quickly cease to be stranger than fiction, once we got used to it.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Bachelors know more about women than married men. If they didn't, they'd be married, too.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The virulence of the national appetite for bogus revelation.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "To the man with an ear for verbal delicacies - the man who searches painfully for the perfect word, and puts the way of saying a thing above the thing said - there is in writing the constant joy of sudden discovery, of happy accident.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Poverty is a soft pedal upon the branches of human activity, not excepting the spiritual.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Time is the great legalizer, even in the field of morals.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "I was at the job of reading it for days and days, endlessly daunted and halted by its laborious dullness, its flatulent fatuity, its almost fabulous inconsequentiality.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Every normal man must be tempted, at times, to spit upon his hands, hoist the black flag, and begin slitting throats.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "All successful newspapers are ceaselessly querulous and bellicose. They never defend anyone or anything if they can help it; if the job is forced on them, they tackle it by denouncing someone or something else.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The great artists of the world are never Puritans, and seldom even ordinarily respectable.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "To be in love is merely to be in a state of perpetual anesthesia - to mistake an ordinary young man for a Greek god or an ordinary young woman for a goddess.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "To die for an idea; it is unquestionably noble. But how much nobler it would be if men died for ideas that were true!", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "A novelty loses nothing by the fact that it is a novelty; it rather gains something, and particularly if it meets the national fancy for the terse, the vivid, and, above all, the bold and imaginative.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Philadelphia is the most pecksniffian of American cities, and thus probably leads the world.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "It is the dull man who is always sure, and the sure man who is always dull.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The only good bureaucrat is one with a pistol at his head. Put it in his hand and it's good-bye to the Bill of Rights.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "To sum up: 1. The cosmos is a gigantic fly-wheel making 10,000 revolutions a minute. 2. Man is a sick fly taking a dizzy ride on it. 3. Religion is the theory that the wheel was designed and set spinning to give him the ride.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "If, after I depart this vale, you ever remember me and have thought to please my ghost, forgive some sinner and wink your eye at some homely girl.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The most dangerous man to any government is the man who is able to think things out for himself, without regard to the prevailing superstitions and taboos.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The men the American people admire most extravagantly are the most daring liars; the men they detest most violently are those who try to tell them the truth.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The difference between a moral man and a man of honor is that the latter regrets a discreditable act, even when it has worked and he has not been caught.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "For if experience teaches us anything at all it teaches us this: that a good politician, under democracy, is quite as unthinkable as an honest burglar.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Suppose two-thirds of the members of the national House of Representatives were dumped into the Washington garbage incinerator tomorrow, what would we lose to offset our gain of their salaries and the salaries of their parasites?", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The strange American ardor for passing laws, the insane belief in regulation and punishment, plays into the hands of the reformers, most of them quacks themselves. Their efforts, even when honest, seldom accomplish any appreciable good.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Oppressive laws do not destroy minorities; they simply make bootleggers.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "One of the main purposes of laws in a democratic society is to put burdens upon intelligence and reduce it to impotence. Ostensibly, their aim is to penalize anti-social acts; actually their aim is to penalize heretical opinions.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The liberty to have and hold property is not one they recognize. They believe only in the liberty to envy, hate and loot the man who has it.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Democrats are always happy. Democracy is a sort of laughing gas. It will not cure anything, perhaps, but it unquestionably stops the pain.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Bryan, at his best, was simply a magnificent job-seeker. The issues that he bawled about usually meant nothing to him.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Bryan was a vulgar and common man, a cad undiluted. He was ignorant, bigoted, self-seeking, blatant and dishonest.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The way to deal with superstition is not to be polite to it, but to tackle it with all arms, and so rout it, cripple it, and make it forever infamous and ridiculous.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Religion, after all, is nothing but an hypothesis framed to account for what is evidentially unaccounted for.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The truth, indeed, is something that mankind, for some mysterious reason, instinctively dislikes. Every man who tries to tell it is unpopular, and even when, by the sheer strength of his case, he prevails, he is put down as a scoundrel.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The basic fact about human existence is not that it is a tragedy, but that it is a bore. It is not so much a war as an endless standing in line. The objection to it is not that it is predominantly painful, but that it is lacking in sense.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Public opinion, in its raw state, gushes out in the immemorial form of the mob's fear. It is piped into central factories, and there it is flavoured and coloured and put into cans.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "Shave a gorilla and it would be almost impossible, at twenty paces, to distinguish him from a heavyweight champion of the world. Skin a chimpanzee, and it would take an autopsy to prove he was not a theologian.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "The most curious social convention of the great age in which we live is the one to the effect that religious opinions should be respected. Its evil effects must be plain enough to everyone.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "There is, in fact, nothing about religious opinions that entitles them to any more respect than other opinions get. On the contrary, they tend to be noticeably silly.", Author = "H. L. Mencken" },
            new Quote { Id = "https://en.wikiquote.org/wiki/H._L._Mencken", Text = "No theologian is honest.", Author = "H. L. Mencken" },
        };
    }
}
