using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class HunterSThompson
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Who is the happier man, he who has braved the storm of life and lived, or he who has stayed securely on shore and merely existed?", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "A man who has blown all his options can't afford the luxury of changing his ways. He has to capitalize on whatever he has left, and he can't afford to admit - no matter how often he's reminded of it - that every day of his life takes him farther and farther down a blind alley...", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Tiny hurts people. When he loses his temper he goes completely out of control and his huge body becomes a lethal weapon. It is difficult to see what role he might play in the Great Society.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Women are terrified of being raped, but somewhere in the back of the womb there is one rebellious nerve end that tingles with curiosity whenever the word is mentioned.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "My face looked like it had been jammed into the spokes of a speeding Harley, and the only thing keeping me awake was the spastic pain of a broken rib.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Let the young enjoy themselves while they can. Why not?", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "We disagree so violently on almost everything that it's a real pleasure to drink with him. If nothing else, he's absolutely honest in his lunacy...", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "In a world as weird and cruel as this one we have made for ourselves, I figure anybody who can find peace and personal happiness without ripping off somebody else deserves to be left alone.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "When the going gets weird, the weird turn pro.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Weird heroes and mould-breaking champions exist as living proof to those who need it that the tyranny of 'the rat race' is not yet final.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The only other important thing to be said about Fear and Loathing at this time is that it was fun to write, and that's rare - for me, at least, because I've always considered writing the most hateful kind of work.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "We were somewhere around Barstow on the edge of the desert when the drugs began to take hold.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "If the current polls are reliable... Nixon will be re-elected by a huge majority of Americans who feel he is not only more honest and more trustworthy than George McGovern, but also more likely to end the war in Vietnam.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "There was something... total... something very undermining about the McGovern defeat... There was a very unexplained kind of... ominous quality to it... weeping chaos.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The importance of Liking Yourself is a notion that fell heavily out of favour during the coptic, anti-ego frenzy of the acid era - but nobody guessed back then that the experiment might churn up this kind of hangover; a whole subculture of frightened illiterates with no faith in anything.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "So much for Objective Journalism. Don't bother to look for it here - not under any byline of mine; or anyone else I can think of.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The phrase itself is a pompous contradiction in terms.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "It's come to the point where you almost can't run unless you can cause people to salivate and whip each other with big sticks. You almost have to be a rock star to get the kind of fever you need to survive in American politics.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "They wanted Action, Color, Speed, Violence...", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "How many times had he stood calmly back there on the duckboards and listened to respectable-looking people talk about raping the hotel penguins?", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "I went to the Democratic Convention as a journalist, and returned a raving beast. For me, that week in Chicago was far worse than the worst bad acid trip I'd ever heard rumors about.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The TV business is uglier than most things. It is normally perceived as some kind of cruel and shallow money trench through the heart of the journalism industry, a long plastic hallway where thieves and pimps run free and good men die like dogs, for no good reason.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "There are times, however, and this is one of them, when even being right feels wrong. What do you say, for instance, about a generation that has been taught that rain is poison and sex is death?", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "It is all well and good for children and acid freaks to still believe in Santa Claus - but it is still a profoundly morbid day for us working professionals.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "In my case, using what politely might be called \"advocacy journalism,\" I've used reporting as a weapon to affect political situations that bear down on my environment.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Not everybody is comfortable with the idea that politics is a guilty addiction. But it is.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "No candidate will risk being linked with a \"suspected\" addict - but a registered, admitted addict is a whole different thing.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Nobody really cared about the countless criminal addictions that preyed on me day and night - just as long as I was not in denial.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "If you consider the great journalists in history, you don't see too many objective journalists on that list.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Mark Twain was not objective.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "I don't quite understand this worship of objectivity in journalism. Now, just flat-out lying is different from being subjective.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Objective journalism is one of the main reasons American politics has been allowed to be so corrupt for so long.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "You can't be objective about Nixon.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "These are harsh words for a man only recently canonized by President Clinton and my old friend George McGovern - but I have written worse things about Nixon, many times, and the record will show that I kicked him repeatedly long before he went down.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "He could shake your hand and stab you in the back at the same time.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Some people will say that words like scum and rotten are wrong for Objective Journalism - which is true, but they miss the point.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "It was the built-in blind spots of the Objective rules and dogma that allowed Nixon to slither into the White House in the first place.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Nixon will be remembered as a classic case of a smart man shitting in his own nest.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "By disgracing and degrading the Presidency of the United States, by fleeing the White House like a diseased cur, Richard Nixon broke the heart of the American Dream.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Hopes rise and dreams flicker and die. Love plans for tomorrow and loneliness thinks of yesterday. Life is beautiful and living is pain.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "I'll stop trying to convince myself that I can't fail; how dull the whole thing would be if that were true.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "We shall ride the bouncing ball and fight gamely to avoid being on the bottom when it bounces.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Events of the past two years have virtually decreed that I shall wrestle with the literary muse for the rest of my days.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Frankly, I have no taste for either poverty or honest labor, so writing is the only recourse left me.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "A man has to BE something; he has to matter.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "For words are merely tools and if you use the right ones you can actually put even your life in order, if you don't lie to yourself and use the wrong words.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Platitudes are safe, because they're easy to wink at, but truth is something else again.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Once I establish credit, I may be able to function. A man needs credit. Especially when he has no money.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "Something new is wanted.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The big ones are tough and it takes either a priest or a fool to use them with any confidence.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "It was the tension between these two poles - a restless idealism on one hand and a sense of impending doom on the other - that kept me going.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "The scene I had just witnessed brought back a lot of memories - not of things I have done but of things I have failed to do, wasted hours and frustrated moments and opportunities forever lost because time had eaten so much of my life and I would never get it back.", Author = "Hunter S. Thompson" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Hunter_S._Thompson", Text = "What passed for society was a loud, giddy whirl of thieves and pretentious hustlers, a dull sideshow full of quacks and clowns and philistines with gimp mentalities.", Author = "Hunter S. Thompson" },
        };
    }
}