using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JackKerouac
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Maybe that's what life is... a wink of the eye and winking stars.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "All of life is a foreign country.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I want to work in revelations, not just spin silly tales for money. I want to fish as deep down as possible into my own subconscious in the belief that once that far down, everyone will understand because they are the same that far down.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I hope it is true that a man can die and yet not only live in others but give them life, and not only life but that great consciousness of life.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Write in recollection and amazement for yourself", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Accept loss forever", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Believe in the holy contour of life", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Be in love with your life every detail of it", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Who knows, my God, but that the universe is not one vast sea of compassion actually, the veritable holy honey, beneath all this show of personality and cruelty?", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Listen to the silence inside the illusion of the world", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "All is well, practice kindness, heaven is nigh.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I'm a wretch. But I love, love.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "You can't fight City Hall. It keeps changing its name.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "All our best men are laughed at in this nightmare land.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "So long and take it easy, because if you start taking things seriously, it is the end of you.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "The fact that everybody in the world dreams every night ties all mankind together.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "They danced down the streets like dingledodies, and I shambled after as I've been doing all my life after people who interest me, because the only people for me are the mad ones, the ones who are mad to live, mad to talk, mad to be saved, desirous of everything at the same time, the ones who never yawn or say a commonplace thing, but burn, burn, burn like fabulous yellow roman candles exploding like spiders across the stars and in the middle you see the blue centerlight pop and everybody goes \"Awww!\"", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "So I rushed past the pretty girls, and the prettiest girls in the world live in Des Moines.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "The one thing that we yearn for in our living days, that makes us sigh and groan and undergo sweet nauseas of all kinds, is the remembrance of some lost bliss that was probably experienced in the womb and can only be reproduced (though we hate to admit it) in death.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I like too many things and get all confused and hung-up running from one falling star to another till I drop. This is the night, what it does to you. I had nothing to offer anybody except my own confusion.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "What is that feeling when you're driving away from people and they recede on the plain till you see their specks dispersing? — it's the too-huge world vaulting us, and it's good-bye. But we lean forward to the next crazy venture beneath the skies.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "It was sad to see his tall figure receding in the dark as we drove away, just like the other figures in New York and New Orleans: they stand uncertainly underneth inmense skies, and everything about them is drowned. Where go? what do? what for? — sleep.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "In 1942 I was the star in one of the filthiest dramas of all time. I was a seaman, and went to the Imperial Café on Scollay Square in Boston to drink; I drank sixty glasses of beer and retired to the toilet, where I wrapped myself around the toilet bowl and went to sleep. During the night at least a hundred seamen and assorted civilians came in and cast their sentient debouchements on me till I was unrecognizably caked. What difference does it make after all? — anonymity in the world of men is better than fame in heaven, for what's heaven? what's earth? All in the mind.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I felt like lying down by the side of the trail and remembering it all. The woods do that to you, they always look familiar, long lost, like the face of a long-dead relative, like an old dream, like a piece of forgotten song drifting across the water, most of all like golden eternities of past childhood or past manhood and all the living and the dying and the heartbreak that went on a million years ago and the clouds as they pass overhead seem to testify (by their own lonesome familiarity) to this feeling. Ecstacy, even, I felt, with flashes of sudden remembrance, and feeling sweaty and drowsy I felt like sleeping and dreaming in the grass.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I saw that my life was a vast glowing empty page and I could do anything I wanted.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "No man should go through life without once experiencing healthy, even bored solitude in the wilderness, finding himself depending solely on himself and thereby learning his true and hidden strength. Learning for instance, to eat when he's hungry and sleep when he's sleepy.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Thinking of the stars night after night I begin to realize \"The stars are words\" and all the innumerable worlds in the Milky Way are words, and so is this world too. And I realize that no matter where I am, whether in a little room full of thought, or in this endless universe of stars and mountains, it's all in my mind.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "The happiness consists in realizing that it is all a great strange dream.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Ah, life is a gate, a way, a path to Paradise anyway, why not live for fun and joy and love or some sort of girl by a fireside, why not go to your desire and LAUGH...", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "And I will die, and you will die, and we all will die, and even the stars will fade out one after another in time.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "It no longer makes me cry and die and tear myself to see her go because everything goes away from me like that now — girls, visions, anything, just in the same way and forever and I accept lostness forever.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "I'm writing this book because we're all going to die — In the loneliness of my life, my father dead, my brother dead, my mother far away, my sister and my wife far away, nothing here but my own tragic hands that once were guarded by a world, a sweet attention, that now are left to guide and disappear their own way into the common dark of all our death, sleeping in me raw bed, alone and stupid...", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "If only I had the magic self of babyhood when I remembered what it was like before I was born, I wouldn't worry about death now knowing both to be the same empty dream.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "A man who allows wild passion to arise within, himself burns his heart, then after burning adds the wind that thereto which ignites the fire again, or not, as the case may be.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "My witness is the empty sky.", Author = "Jack Kerouac" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jack_Kerouac", Text = "Soon I'll find the right words, they'll be very simple.", Author = "Jack Kerouac" },
        };
    }
}