using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JamesJoyce
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Art is the human disposition of sensible or intelligible matter for an aesthetic end.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "There is not past, no future; everything flows in an eternal present.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "I want to give a picture of Dublin so complete that if the city suddenly disappeared from the earth it could be reconstructed out of my book.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Does nobody understand?", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Love (understood as the desire of good for another) is in fact so unnatural a phenomenon that it can scarcely repeat itself, the soul being unable to become virgin again and not having energy enough to cast itself out again into the ocean of another's soul.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "The pity is the public will demand and find a moral in my book - or worse they may take it in some more serious way, and on the honor of a gentleman, there is not one single serious line in it.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "One great part of every human existence is passed in a state which cannot be rendered sensible by the use of wideawake language, cutanddry grammar and goahead plot.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Poetry, even when apparently most fantastic, is always a revolt against artifice, a revolt, in a sense, against actuality.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Every age must look for its sanction to its poetry and philosophy, for in these the human mind, as it looks backward or forward, attains to an eternal state.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Beauty, the splendour of truth, is a gracious presence when the imagination contemplates intensely the truth of its own being or the visible world, and the spirit which proceeds out of truth and beauty is the holy spirit of joy. These are realities and these alone give and sustain life.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "There is no heresy or no philosophy which is so abhorrent to the church as a human being.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "All things are inconstant except the faith in the soul, which changes all things and fills their inconstancy with light, but though I seem to be driven out of my country as a misbeliever I have found no man yet with a faith like mine.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "I confess that I do not see what good it does to fulminate against the English tyranny while the Roman tyranny occupies the palace of the soul.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Christopher Columbus, as everyone knows, is honoured by posterity because he was the last to discover America.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "You forget that the kingdom of heaven suffers violence: and the kingdom of heaven is like a woman.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Writing in English is the most ingenious torture ever devised for sins committed in previous lives. The English reading public explains the reason why.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "If I gave it all up immediately, I'd lose my immortality. I've put in so many enigmas and puzzles that it will keep the professors busy for centuries arguing over what I meant, and that's the only way of insuring one's immortality.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "The demand that I make of my reader is that he should devote his whole Life to reading my works.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "My words in her mind: cold polished stones sinking through a quagmire.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "I laugh at it today, now that I have had all the good of it. Let the bridge blow up, provided I have got my troops across... Nonetheless, that book was a terrible risk. A transparent leaf separates it from madness.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "For myself, I always write about Dublin, because if I can get to the heart of Dublin I can get to the heart of all the cities of the world. In the particular is contained the universal.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "I had never spoken to her, except for a few casual words, and yet her name was like a summons to all my foolish blood.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "But my body was like a harp and her words and gestures were like fingers running upon the wires.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Gazing up into the darkness I saw myself as a creature driven and derided by vanity; and my eyes burned with anguish and anger.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "She dealt with moral problems the way a cleaver deals with meat: and in this case she had made up her mind.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "He was not sure what idea he wished to express but the thought that a poetic moment had touched upon him took life within him like an infant hope.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "He tried to weigh his soul to see if it was a poet's soul. Melancholy was the dominant note of his temperament, he thought, but it was a melancholy tempered by recurrences of faith and resignation and simple joy. If he could give expression to it in a book of poems perhaps men would listen.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Everything in Paris is gay", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "But there was no harshness in the eyes which, looking at the world from under their tawny eyebrows, gave the impression of a man ever alert to greet a redeeming instinct in others but often disappointed. He lived at a little distance from his body, regarding his own acts with doubtful side-glances.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "One of his sentences, written two months after his last interview with Mrs. Sinico, read: Love between man and man is impossible because there must not be sexual intercourse and friendship between man and woman is impossible because there must be sexual intercourse.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "One by one they were all becoming shades. Better pass boldly into that other world, in the full glory of some passion, than fade and wither dismally with age.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "His soul swooned slowly as he heard the snow falling faintly through the universe and faintly falling, like the descent of their last end, upon all the living and the dead.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "The heaventree of stars hung with humid nightblue fruit.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "A man of genius makes no mistakes. His errors are volitional and are the portals of discovery", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Frail the white rose and frail are Her hands that gave ", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "How soft, how sad his voice is ever calling,Ever unanswered, and the dark rain falling,Then as now.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Seraphim, The lost hosts awaken", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Again!", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Phall if you but will, rise you must: and none so soon either shall the pharce for the nunce come to a setdown secular phoenish.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Humme the Cheapner, Esc, overseen as we thought him, yet worthy of the naym, came at this timecoloured place where we live in our paroqial fermament one tide on another", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "In the name of Annah the Allmaziful, the Everliving, the Bringer of Plurabilities, haloed be her eve, her singtime sung, her rill be run, unhemmed as it is uneven!", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Quoint a quincidence! O.K. Omnius Kollidimus. As Ollover Krumwall sayed when he slepped ueber his grannyamother. Kangaroose feathers. Who in the name of thunder'd ever belevin you were that bolt?", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Three quarks for Muster Mark!", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "A Place for Everything and Everything in its Place, Is the Pen Mightier than the Sword? A Successful Career in the Civil Service.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "In the name of the former and of the latter and of their holocaust. Allmen.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "Thaw! The last word in stolentelling!", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "I've lapped so long. As you said. It fair takes. If I lose my breath for a minute or two don't speak, remember! Once it happened, so it may again.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "He comes into the world God knows how, walks on the water, gets out of his grave and goes up off the Hill of Howth. What drivel is this?", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "This triviality made him think of collecting many such moments together in a book of epiphanies. By an epiphany he meant a sudden spiritual manifestation, whether in the vulgarity of speech or of gesture or in a memorable phase of the mind itself.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "The apprehensive faculty must be scrutinised in action.", Author = "James Joyce" },
            new Quote { Id = "https://en.wikiquote.org/wiki/James_Joyce", Text = "It has not epiphanised yet, he said.", Author = "James Joyce" },
        };
    }
}