using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JeanPaulSartre
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Imagination is not an empirical or superadded power of consciousness, it is the whole of consciousness as it realizes its freedom.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Fascism is not defined by the number of its victims, but by the way it kills them.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Our responsibility is much greater than we might have supposed, because it involves all mankind.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "A writer who takes political, social or literary positions must act only with the means that are his. These means are the written words.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "She believed in nothing; only her skepticism kept her from being an atheist.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I hate victims who respect their executioners.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I construct my memories with my present. I am lost, abandoned in the present. I try in vain to rejoin the past: I cannot escape.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "The real nature of the present revealed itself: it was what exists, all that was not present did not exist.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "The past is the luxury of proprietors.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "For an occurrence to become an adventure, it is necessary and sufficient for one to recount it.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I know I'll never jump again.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Every existing thing is born without reason, prolongs itself out of weakness and dies by chance.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Nothingness haunts being.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Existence precedes and rules essence.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I am condemned to be free.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Man is a useless passion.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "All human activities are equivalent ... and ... all are on principle doomed to failure.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Man is condemned to be free; because once thrown into the world, he is responsible for everything he does.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "It is certain that we cannot escape anguish, for we are anguish.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "The For-itself, in fact, is nothing but the pure nihilation of the In-itself; it is like a hole of being at the heart of Being.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Some men are born committed to action: they do not have a choice, they have been thrown on a path, at the end of that path, an act awaits them, their act.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "They are in bad faith — they are afraid — and fear, bad faith have an aroma that the gods find delicious. Yes, the gods like that, the pitiful souls.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Do not judge the gods, young man, they have painful secrets.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Yes, I am so free. And what a superb absence is my soul.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "A man who is free is like a mangy sheep in a herd. He will contaminate my entire kingdom and ruin my work.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "What do I care about Jupiter? Justice is a human issue, and I do not need a god to teach it to me.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "All-powerful god, who am I but the fear that I inspire in others?", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Blood doubly unites us, for we share the same blood and we have spilled blood.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Suppose that I wish to deserve the title of \"robber of remorse\" and that I place in myself all [the townspeople's] repentence?", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "He is dead, and my hatred has died with him.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I gave you the liberty to serve me. That is possible, but it has turned against you and there is nothing either one of us can do about it.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I am not your king, impudent larva? Who then has created you? You. But you should not have created me free.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I am a man, Jupiter, and each man must invent his own path.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "In a world, man must create his own essence: it is in throwing himself into the world, suffering there, struggling there, that he gradually defines himself.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "man first of all exists, encounters himself, surges up in the world – and defines himself afterwards.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Life has no meaning a priori … It is up to you to give it a meaning, and value is nothing but the meaning that you choose.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I respect orders but I respect myself too and I do not obey foolish rules made especially to humiliate me.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "It is the same thing: killing, dying, it is the same thing: one is just as alone in each. He is lucky, he will only die once. As for me, for ten days I have been killing him at every minute.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I say a murder is abstract. You pull the trigger and after that you do not understand anything that happens.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Politics is a science. You can demonstrate that you are right and that others are wrong.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Intellectuals cannot be good revolutionaries; they are just good enough to be assassins.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "As far as men go, it is not what they are that interests me, but what they can become.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "You take souls for vegetables.... The gardener can decide what will become of his carrots but no one can choose the good of others for them.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "The best work is not what is most difficult for you; it is what you do best.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "If you are not already dead, forgive. Rancor is heavy, it is worldly; leave it on earth: die light.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I know only one Church: it is the society of men.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "If a victory is told in detail, one can no longer distinguish it from a defeat.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "It is too early to love. We will buy the right to do so by shedding blood.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "When the rich make war, it's the poor that die.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Why commit Evil? Because Good has already been done. Who has done it? God the Father. I, on the other hand, am improvising.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I am not virtuous. Our sons will be if we shed enough blood to give them the right to be.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "There are two types of poor people, those who are poor together and those who are poor alone. The first are the true poor, the others are rich people out of luck.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I will not be modest. Humble, as much as you like, but not modest. Modesty is the virtue of the lukewarm.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "One cannot become a saint when one works sixteen hours a day.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "One always dies too soon — or too late. And yet, life is there, finished: the line is drawn, and it must all be added up. You are nothing other than your life.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I think of death only with tranquility, as an end. I refuse to let death hamper life. Death must enter life only to define it.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "A man is what he wills himself to be.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "If the Jew did not exist, the anti-Semite would invent him.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "And when we speak of \"abandonment\" - a favorite word of Heidegger - we only mean to say that God does not exist and that it is necessary to draw the consequences of his absence to the end.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "I am mean: that means that I need the suffering of others to exist. A flame. A flame in their hearts. When I am all alone, I am extinguished.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "You have stolen my face from me: you know it and I no longer do.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "Don't you feel the same way? When I cannot see myself, even though I touch myself, I wonder if I really exist.", Author = "Jean-Paul Sartre" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Jean-Paul_Sartre", Text = "If only you knew how little I care. Cowardly or not, as long as he is a good kisser.", Author = "Jean-Paul Sartre" },
        };
    }
}