using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JohnLocke
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "But there is only one thing which gathers people into seditious commotion, and that is oppression.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "To love truth for truth's sake is the principal part of human perfection in this world, and the seed-plot of all other virtues.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Reading furnishes the mind only with materials of knowledge; it is thinking that makes what we read ours.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Sophistry is only fit to make men more conceited in their ignorance.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "This life affords no solid satisfaction, but in the consciousness of having done well, and the hopes of another life.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "New opinions are always suspected, and usually opposed, without any other reason but because they are not already common.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "I have always thought the actions of men the best interpreters of their thoughts.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "There cannot any one moral Rule be propos'd, whereof a Man may not justly demand a Reason.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "No man's knowledge here can go beyond his experience.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Preference of vice to virtue, a manifest wrong judgment.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The boundaries of the species, whereby men sort them, are made by men.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "He that uses his words loosely and unsteadily will either not be minded or not understood.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "I doubt not, but from self-evident Propositions, by necessary Consequences, as incontestable as those in Mathematics, the measures of right and wrong might be made out.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "He that knows anything, knows this, in the first place, that he need not seek long for instances of his ignorance.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "False and doubtful positions, relied upon as unquestionable maxims, keep those who build on them in the dark from truth.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "It is one thing to show a man that he is in error, and another to put him in possession of the truth.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "He that would seriously set upon the search of truth, ought in the first place to prepare his mind with a love of it.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "There are very few lovers of truth, for truth's sake, even amongst those who persuade themselves that they are so.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "One unerring mark of the love of truth is not entertaining any proposition with greater assurance than the proofs it is built upon will warrant.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "All men are liable to error; and most men are, in many points, by passion or interest, under temptation to it.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Freedom of Nature is, to be under no other restraint but the Law of Nature.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Though the Earth, and all inferior Creatures be common to all Men, yet every Man has a Property in his own Person.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The end of law is not to abolish or restrain, but to preserve and enlarge freedom.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "This is to think that men are so foolish that they take care to avoid what mischiefs may be done them by polecats or foxes, but are content, nay, think it safety, to be devoured by lions.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Government has no other end than the preservation of property.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Men being, as has been said, by nature, all free, equal and independent, no one can be put out of this estate, and subjected to the political power of another, without his own consent.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "As usurpation is the exercise of power which another has a right to, so tyranny is the exercise of power beyond right, which nobody can have a right to.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Wherever Law ends, Tyranny begins.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "That force is to be opposed to nothing, but to unjust and unlawful force.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "A sound mind in a sound body, is a short but full description of a happy state in this world.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Good and evil, reward and punishment, are the only motives to a rational creature: these are the spur and reins whereby all mankind are set on work, and guided.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Take care of, not to endeavour to settle too many habits at once, lest by variety you confound them, and so perfect none.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Children (nay, and men too) do most by example.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "We are all a sort of camelions, that still take a tincture from things near us; nor is it to be wonder'd at in children, who better understand what they see than what they hear.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Virtue is harder to be got than knowledge of the world; and, if lost in a young man, is seldom recovered.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "He that will have his son have a respect for him and his orders, must himself have a great reverence for his son.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "You must do nothing before him, which you would not have him imitate.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "None of the things they learn, should ever be made a burthen to them, or impos's on them as a task.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Long discourses, and philosophical readings, at best, amaze and confound, but do not instruct children.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The scene should be gently open'd, and his entrance made step by step, and the dangers pointed out that attend him from several degrees, tempers, designs, and clubs of men.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The sooner you treat him as a man, the sooner he will begin to be one.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "You will insensibly raise his mind above the usual amusements of youth, and those trifling occupations which it is commonly wasted in.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The reservedness and distance that fathers keep, often deprive their sons of that refuge which would be of more advantage to them than an hundred rebukes or chidings.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "See what are his predominate passions and prevailing inclinations.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "These native propensities, these prevalencies of constitution, are not to be cur'd by rules, or a direct contest.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The bypass will always hang on that side that nature first plac'd it.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "They would have propriety and possession, pleasing themselves with the power which that seems to give, and the right that they thereby have, to dispose of them as they please.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Distinguish between the wants of fancy, and those of nature.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "The pains that come from the necessities of nature, are monitors to us to beware of greater mischiefs, which they are the forerunner of.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Curiosity should be as carefully cherish'd in children, as other appetites suppress'd.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "If the complaint be of something really worth your notice, and prevention another time, then reprove the offender by himself alone, out of sight of him who complain'd.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Teach them to part with what they have, easily and freely to their friends, and let them find by experience that the most liberal has always the most plenty, with esteem and commendation to boot.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Carefully keep children from frights of all kinds, when they are young.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "By gentle degrees accustom children to those things they are too much afraid of.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Since the great foundation of fear is pain, the way to harden and fortify children against fear and danger is to accustom them to suffer pain.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "They who have once brought themselves not to think bodily pain the greatest of evils, or that which they ought to stand most in fear of, have made no small advance toward virtue.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Inuring children gently to suffer some degrees of pain without shrinking, is a way to gain firmness to their minds, and lay a foundation for courage and resolution in the future part of their lives.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Children should not be suffer'd to lose the consideration of human nature in the shufflings of outward conditions.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "Knowledge is grateful to the understanding, as light to the eyes.", Author = "John Locke" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Locke", Text = "There cannot be a greater spur to the attaining what you would have the eldest learn, and know himself, than to set him upon teaching it his younger brothers and sisters.", Author = "John Locke" },
        };
    }
}