using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JohnKeats
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Sweet are the pleasures that to verse belong, and doubly sweet a brotherhood in song.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "My spirit is too weak - mortality weighs heavily on me like unwilling sleep, and each imagin'd pinnacle and steep of godlike hardship tells me I must die like a sick Eagle looking at the sky.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "It keeps eternal whisperings around desolate shores, and with its mighty swell gluts twice ten thousand Caverns, till the spell of Hecate leaves them their old shadowy sound.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Bright star! would I were stedfast as thou art - not in lone splendour hung aloft the night and watching with eternal lids apart, like nature's patient, sleepless Eremite, the moving waters at their priestlike task of pure ablution round earth's human shores.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The day is gone, and all its sweets are gone! Sweet voice, sweet lips, soft hand, and softer breast.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "To his sight the husk of natural objects opens quite to the core; and every secret essence there reveals the elements of good and fair; making him see, where Learning hath no light.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Here lies one whose name was writ in water.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "My chest of books divide amongst my friends.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The imagination may be compared to Adam's dream - he awoke and found it truth.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "O for a life of Sensations rather than of Thoughts!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The excellency of every art is its intensity, capable of making all disagreeables evaporate, from their being in close relationship with beauty and truth.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "They will explain themselves - as all poems should do without any comment.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Works of genius are the first things in this world.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Nothing is finer for the purposes of great productions than a very gradual ripening of the intellectual powers.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Poetry should be great and unobtrusive, a thing which enters into one's soul, and does not startle it or amaze it with itself, but with its subject.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Many have original minds who do not think it - they are led away by custom - Now it appears to me that almost any man may like the spider spin from his own inwards his own citadel.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Scenery is fine - but human nature is finer.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Every mental pursuit takes its reality and worth from the ardour of the pursuer.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Axioms in philosophy are not axioms until they are proved upon our pulses: we read fine things but never feel them to the full until we have gone the same steps as the author.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I compare human life to a large mansion of many apartments, two of which I can only describe, the doors of the rest being as yet shut upon me.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "There is an awful warmth about my heart like a load of immortality.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I begin to get a little acquainted with my own strength and weakness. Praise or blame has but a momentary effect on the man whose love of beauty in the abstract makes him a severe critic on his own works.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I think I shall be among the English Poets after my death.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "A poet is the most unpoetical of anything in existence; because he has no identity - he is continually informing - and filling some other body.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Nothing ever becomes real till it is experienced - Even a proverb is no proverb to you till your Life has illustrated it.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Call the world if you please \"The vale of soul-making.\"", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I have two luxuries to brood over in my walks, your loveliness and the hour of my death. O that I could have possession of them both in the same minute.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I have nothing to speak of but my self - and what can I say but what I feel?", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Some think I have lost that poetical ardour and fire 'tis said I once had- the fact is, perhaps I have; but, instead of that, I hope I shall substitute a more thoughtful and quiet power.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I have been astonished that Men could die Martyrs for religion - I have shudder'd at it - I shudder no more - I could be martyr'd for my Religion - Love is my religion - I could die for that - I could die for you. My Creed is Love and you are its only tenet.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "If I should die,\" said I to myself, \"I have left no immortal work behind me - nothing to make my friends proud of my memory - but I have loved the principle of beauty in all things, and if I had had time I would have made myself remembered.\"", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "You are always new. The last of your kisses was ever the sweetest; the last smile the brightest; the last movement the gracefullest.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "You might curb your magnanimity, and be more of an artist, and load every rift of your subject with ore.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "I can scarcely bid you good-bye, even in a letter. I always made an awkward bow. God bless you!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And then there crept A little noiseless noise among the leaves, Born of the very sigh that silence heaves.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Open afresh your round of starry folds, Ye ardent marigolds!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Nought but a lovely sighing of the wind Along the reedy stream; a half-heard strain, Full of sweet desolation-balmy pain.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Woman! when I behold thee flippant, vain, Inconstant, childish, proud, and full of fancies.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "To one who has been long in city pent, 'Tis very sweet to look into the fair And open face of heaven.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "E'en like the passage of an angel's tear That falls through the clear ether silently.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The poetry of earth is never dead.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Stop and consider! life is but a day; A fragile dew-drop on its perilous way From a tree's summit.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "O for ten years, that I may overwhelm Myself in poesy; so I may do the deed That my own soul has to itself decreed.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The sweet converse of an innocent mind.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "A thing of beauty is a joy forever: Its loveliness increases; it will never Pass into nothingness; but still will keep A bower quiet for us, and a sleep Full of sweet dreams, and health, and quiet breathing.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "In spite of all, Some shape of beauty moves away the pall From our dark spirits.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "O magic sleep! O comfortable bird, That broodest o'er the troubled sea of the mind Till it is hush'd and smooth!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Time, that aged nurse, Rocked me to patience.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "My restless spirit never could endure To brood so long upon one luxury, Unless it did, though fearfully, espy A hope beyond the shadow of a dream.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Pleasure is oft a visitant; but pain Clings cruelly to us.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "He ne'er is crown'd With immortality, who fears to follow Where airy voices lead.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "'Tis the pest Of love, that fairest joys give most unrest.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "So many, and so many, and such glee.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "That large utterance of the early gods!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The days of peace and slumberous calm are fled.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Knowledge enormous makes a God of me.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And for her eyes: what could such eyes do there But weep, and weep, that they were born so fair?", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Love in a hut, with water and a crust, Is - Love, forgive us! - cinders, ashes, dust.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "\"For cruel 'tis,\" said she, \"To steal my Basil-pot away from me.\"", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Ever let the Fancy roam, Pleasure never is at home.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Then in a wailful choir the small gnats mourn Among the river sallows, borne aloft Or sinking as the light wind lives or dies.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "No, no, go not to Lethe, neither twist Wolfs-bane, tight-rooted, for its poisonous wine; Nor suffer thy pale forehead to be kiss'd By nightshade.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Music's golden tongue Flatter'd to tears this aged man and poor.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The silver snarling trumpets 'gan to chide.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "The music, yearning like a God in pain.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "She sighed for Agnes' dreams, the sweetest of the year.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Asleep in lap of legends old.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Sudden a thought came like a full-blown rose, Flushing his brow, and in his pained heart Made purple riot.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "A poor, weak, palsy-stricken, churchyard thing.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "As though a tongueless nightingale should swell Her throat in vain, and die, heart-stifled, in her dell.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Unclasps her warmed jewels one by one; Loosens her fragrant bodice; by degrees Her rich attire creeps rustling to her knees.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "As though a rose should shut and be a bud again.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And still she slept an azure-lidded sleep, In blanched linen, smooth, and lavender'd.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And lucent syrops, tinct with cinnamon.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "He play'd an ancient ditty long since mute, In Provence call'd \"La belle dame sans mercy.\"", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And the long carpets rose along the gusty floor.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "And they are gone: ay, ages long ago These lovers fled away into the storm.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Already with thee! tender is the night.", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Forlorn! the very word is like a bell To toil me back from thee to my sole self!", Author = "John Keats" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Keats", Text = "Was it a vision, or a waking dream? Fled is that music: - Do I wake or sleep?", Author = "John Keats" },
        };
    }
}
