using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JohnStuartMill
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Whatever we may think or affect to think of the present age, we cannot get out of it; we must suffer with its sufferings, and enjoy with its enjoyments; we must share in its lot, and, to be either useful or at ease, we must even partake its character.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "All students of man and society who possess that first requisite for so difficult a study, a due sense of its difficulties, are aware that the besetting danger is not so much of embracing falsehood for true, as of mistaking part of the truth for the whole.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "It is not because men's desires are strong that they act ill; it is because their consciences are weak.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "War is an ugly thing, but not the ugliest of things: the decayed and degraded state of moral and patriotic feeling which thinks that nothing is worth a war, is much worse.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "A man who has nothing which he is willing to fight for, nothing which he cares more about than he does about his personal safety, is a miserable creature who has no chance of being free, unless made and kept so by the exertions of better men than himself.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "What is called the Law of Nations is not properly law, but a part of ethics: a set of moral rules, accepted as authoritative by civilized states.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Let not any one pacify his conscience by the delusion that he can do no harm if he takes no part, and forms no opinion. Bad men need nothing more to compass their ends, than that good men should look on and do nothing.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "How can great minds be produced in a country where the test of a great mind is agreeing in the opinions of small minds?", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "It might be plausibly maintained, that in almost every one of the leading controversies, past or present, in social philosophy, both sides were in the right in what they affirmed, though wrong in what they denied.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Aim at something great; aim at things which are difficult; and there is no great thing which is not difficult.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Whatever is known to us by consciousness, is known beyond possibility of question. What one sees or feels, whether bodily or mentally, one cannot but be sure that one sees or feels.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "I regard utility as the ultimate appeal on all ethical questions; but it must be utility in the largest sense, grounded on the permanent interests of man as a progressive being.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "The only purpose for which power can be rightfully exercised over any member of a civilized community, against his will, is to prevent harm to others. His own good, either physical or moral, is not a sufficient warrant.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "If all mankind minus one, were of one opinion, and only one person were of the contrary opinion, mankind would be no more justified in silencing that one person, than he, if he had the power, would be justified in silencing mankind.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Truth gains more even by the errors of one who, with due study and preparation, thinks for himself, than by the true opinions of those who only hold them because they do not suffer themselves to think.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "No one can be a great thinker who does not recognise, that as a thinker it is his first duty to follow his intellect to whatever conclusions it may lead...Not that it is solely, or chiefly, to form great thinkers, that freedom of thinking is required.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Human nature is not a machine to be built after a model, and set to do exactly the work prescribed for it, but a tree, which requires to grow and develop itself on all sides, according to the tendency of the inward forces which make it a living thing.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Whatever crushes individuality is despotism, by whatever name it may be called, and whether it professes to be enforcing the will of God or the injunctions of men.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Persons of genius, it is true, are, and are always likely to be, a small minority; but in order to have them, it is necessary to preserve the soil in which they grow. Genius can only breathe freely in an atmosphere of freedom.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "One person with a belief is a social power equal to ninety-nine who have only interests.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Whenever the general disposition of the people is such, that each individual regards those only of his interests which are selfish, and does not dwell on, or concern himself for, his share of the general interest, in such a state of things, good government is impossible.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "A bureaucracy always tends to become a pedantocracy.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Among a people without fellow-feeling, especially if they read and speak different languages, the united public opinion, necessary to the working of the representative government, cannot exist.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Whatever can be proved to be good, must be so by being shown to be a means to something admitted to be good without proof.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "The creed which accepts as the foundation of morals, Utility, or the Greatest Happiness Principle, holds that actions are right in proportion as they tend to promote happiness, wrong as they tend to produce the reverse of happiness.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "To do as one would be done by, and to love one's neighbour as oneself, constitute the ideal perfection of utilitarian morality.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "The utilitarian morality does recognise in human beings the power of sacrificing their own greatest good for the good of others. It only refuses to admit that the sacrifice is itself a good. A sacrifice which does not increase, or tend to increase, the sum total of happiness, it considers as wasted.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "It is not the fault of any creed, but of the complicated nature of human affairs, that rules of conduct cannot be so framed as to require no exceptions, and that hardly any kind of action can safely be laid down as either always obligatory or always condemnable.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied. And if the fool, or the pig, are of a different opinion, it is because they only know their own side of the question. The other party to the comparison knows both sides.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "The utilitarian doctrine is, that happiness is desirable, and the only thing desirable, as an end; all other things being only desirable as means to that end.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "So it has been with the distinctions of slaves and freemen, nobles and serfs, patricians and plebeians; and so it will be, and in part already is, with the aristocracies of colour, race, and sex.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Stupidity is much the same all the world over. A stupid person's notions and feelings may confidently be inferred from those which prevail in the circle by which the person is surrounded. Not so with those whose opinions and feelings are an emanation from their own nature and faculties.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "I deny that anyone knows, or can know, the nature of the two sexes, as long as they have only been seen in their present relation to one another.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "It appears... that a work similar in its object and general conception to that of Adam Smith, but adapted to the more extended knowledge and improved ideas of the present age, is the kind of contribution which Political Economy at present requires.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "To tax the larger incomes at a higher percentage than the smaller is to lay a tax on industry and economy; to impose a penalty on people for having worked harder and saved more than their neighbours.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "The reasons for legal intervention in favour of children, apply not less strongly to the case of those unfortunate slaves and victims of the most brutal part of mankind, the lower animals.", Author = "John Stuart Mill" },
            new Quote { Id = "https://en.wikiquote.org/wiki/John_Stuart_Mill", Text = "Since the state must necessarily provide subsistence for the criminal poor while undergoing punishment, not to do the same for the poor who have not offended is to give a premium on crime.", Author = "John Stuart Mill" },
        };
    }
}