using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class JosephConrad
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "It's only those who do nothing that make no mistakes, I suppose.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "All creative art is magic, is evocation of the unseen in forms persuasive, enlightening, familiar and surprising, for the edification of mankind, pinned down by the conditions of its existence to the earnest consideration of the most insignificant tides of reality.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The sea never changes and its works, for all the talk of men, are wrapped in mystery.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "When he stepped off the straight and narrow path of his peculiar honesty, it was with an inward assertion of unflinching resolve to fall back again into the monotonous but safe stride of virtue as soon as his little excursion into the wayside quagmires had produced the desired effect.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "What makes mankind tragic is not that they are the victims of nature, it is that they are conscious of it.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Egoism, which is the moving force of the world, and altruism, which is its morality, these two contradictory instincts, of which one is so plain and the other so mysterious, cannot serve us unless in the incomprehensible alliance of their irreconcilable antagonism.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "She strode like a grenadier, was strong and upright like an obelisk, had a beautiful face, a candid brow, pure eyes, and not a thought of her own in her head.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "One must have lived on such diet to discover what ghastly trouble the necessity of swallowing one's food become.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Running all over the sea trying to get behind the weather.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "It is to be remarked that a good many people are born curiously unfitted for the fate awaiting them on this earth.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "I can't tell if a straw ever saved a drowning man, but I know that a mere glance is enough to make despair pause. For in truth we who are creatures of impulse are not creatures of despair.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Being a woman is a terribly difficult trade since it consists principally of dealings with men.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The world of finance is a mysterious world in which, incredible as the fact may appear, evaporation precedes liquidation.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "It is not the clear-sighted who lead the world. Great achievements are accomplished in a blessed, warm mental fog.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Every age is fed on illusions, lest men should renounce life early and the human race come to an end.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The last thing a woman will consent to discover in a man whom she loves, or on whom she simply depends, is want of courage.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Reality, as usual, beats fiction out of sight.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "In plucking the fruit of memory one runs the risk of spoiling its bloom.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "A man is a worker. If he is not that he is nothing.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "For the great mass of mankind the only saving grace that is needed is steady fidelity to what is nearest to hand and heart in the short moment of each human effort.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "This could have occurred nowhere but in England, where men and sea interpenetrate, so to speak.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "\"God for men — religions for women,\" he muttered sometimes.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Action is consolatory. It is the enemy of thought and the friend of flattering illusions.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The air of the New World seems favorable to the art of declamation.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "A nickname may be the best record of a success. That's what I call putting the face of a joke upon the body of a truth.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "There is no credulity so eager and blind as the credulity of covetousness, which, in its universal extent, measures the moral misery and the intellectual destitution of mankind.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The truth was that he died from solitude, the enemy known but to few on this Earth, and whom only the simplest of us are fit to withstand. The brilliant Costaguanaro of the boulevards had died from solitude and want of faith in himself and others.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "There is no peace and no rest in the development of material interests. They have their law, and their justice. But it is founded on expediency, and is inhuman; it is without rectitude, without the continuity and the force that can be found only in a moral principal.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "History repeats itself, but the special call of an art which has passed away is never reproduced. It is as utterly gone out of the world as the song of a destroyed wild bird.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "An artist is a man of action, whether he creates a personality, invents an expedient, or finds the issue of a complicated situation.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The Westerly Wind asserting his sway from the south-west quarter is often like a monarch gone mad, driving forth with wild imprecations the most faithful of his courtiers to shipwreck, disaster, and death.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The East Wind, an interloper in the dominions of Westerly weather, is an impassive-faced tyrant with a sharp poniard held behind his back for a treacherous stab.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "For all that has been said of the love that certain natures (on shore) have professed to feel for it, for all the celebrations it had been the object of in prose and song, the sea has never been friendly to man. At most it has been the accomplice of human restlessness.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Coming in from the eastward, the bright colouring of the Nore lightship marking the part of the river committed to the charge of an Admiral (the Commander-in-Chief at the Nore) accentuates the dreariness and the great breadth of the Thames Estuary.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Then, on the slight turn of the Lower Hope Reach, clusters of factory chimneys come distinctly into view, tall and slender above the squat ranges of cement works in Grays and Greenhithe.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Between the crowded houses of Gravesend and the monstrous red-brick pile on the Essex shore the ship is surrendered fairly to the grasp of the river.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "This stretch of the Thames from London Bridge to the Albert Docks is to other watersides of river ports what a virgin forest would be to a garden.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Protection is the first necessity of opulence and luxury.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The imbecile bourgeoisie of this country make themselves the accomplices of the very people whose aim is to drive them out of their houses to starve in ditches.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "To the destruction of what is.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The cabman looked at the pieces of silver, which, appearing very minute in his big, grimy palm, symbolised the insignificant results which reward the ambitious courage and toil of a mankind whose day is short on this earth of evil.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "All passion is lost now. The world is mediocre, limp, without force.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Words, as is well known, are the great foes of reality.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "To a teacher of languages there comes a time when the world is but a place of many words and man appears a mere talking animal not much more wonderful than a parrot.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "I take it that what all men are really after is some form or perhaps only some formula of peace.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "A man's real life is that accorded to him in the thoughts of other men by reason of respect or natural love.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Nations it may be have fashioned their Governments, but the Governments have paid them back in the same coin.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "They talk of a man betraying his country, his friends, his sweetheart. There must be a moral bond first. All a man can betray is his conscience.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "A man's most open actions have a secret side to them.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Let a fool be made serviceable according to his folly.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "The belief in a supernatural source of evil is not necessary; men alone are quite capable of every wickedness.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "Perhaps life is just that... a dream and a fear.", Author = "Joseph Conrad" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Joseph_Conrad", Text = "He feared neither God, nor devil, nor man, nor wind, nor sea, nor his own conscience.", Author = "Joseph Conrad" },
        };
    }
}