using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class LewisCarroll
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "If you want to inspire confidence, give plenty of statistics - it does not matter that they should be accurate, or even intelligible, so long as there is enough of them.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "But surely you trust God! Do you think He would let you come to harm? To be afraid is to distrust.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "As you have invited me, I cannot come, for I have made a rule to decline all invitations; but I will come the next day.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "And as to being in a fright, allow me to remark that ghosts have just as good a right in every way, to fear the light, as men to fear the dark.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "My father was a Brownie, Sir; my mother was a Fairy. The notion had occurred to her, the children would be happier, if they were taught to vary.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "There are certain things - as, a spider, a ghost, the income-tax, gout, an umbrella for three - that I hate, but the thing that I hate the most is a thing they call the Sea.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "I NEVER loved a dear Gazelle - Nor anything that cost me much: High prices profit those who sell, but why should I be fond of such?", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Blow, blow your trumpets till they crack, Ye little men of little souls! And bid them huddle at your back - Gold-sucking leeches, shoals on shoals!", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "I do not know if 'Alice in Wonderland' was an original story - I was, at least, no conscious imitator in writing it - but I do know that, since it came out, something like a dozen story-books have appeared, on identically the same pattern.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "I suppose every child has a world of his own - and every man, too, for the matter of that. I wonder if that's the cause for all the misunderstanding there is in Life?", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Since I have possessed a \"Wonderland Stamp Case\", Life has been bright and peaceful, and I have used no other. I believe the Queen's laundress uses no other.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Here is a golden Rule to begin with. Write legibly. The average temper of the human race would be perceptibly sweetened, if everybody obeyed this Rule! A great deal of the bad writing in the world comes simply from writing too quickly.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "God has given to Man an absolute right to take the lives of other animals, for any reasonable cause, such as the supply of food; but He has not given to Man the right to inflict pain, unless where necessary.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Say, what is the spell, when her fledgelings are cheeping, that lures the bird home to her nest?", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Say, whence is the voice that, when anger is burning, bids the whirl of the tempest to cease?", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "'Tis a secret: none knows how it comes, how it goes: but the name of the secret is Love!", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "All in the waning light she stood, the star of perfect womanhood.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "The dying crimson of the West that faintly tinged his haggard cheek, fell on her as she stood, and shed a glory round the patient head.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Not as in rest she bowed, but large hot tears were coursing down her cheek. And her low-panted sobs broke awefully upon the sleeping echoes of the night.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "O bitter is it to abide in weariness alway: at dawn to sigh for eventide, at eventide for day.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "The light was faint, and soft the air that breathed around the place; and she was lithe, and tall, and fair, and with a wayward grace her queenly head she bare.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "True love gives true love of the best: then take,\" I cried, \"my heart to thee! The very heart from out my breast I plucked, I gave it willingly; Her very heart she gave to me - then died the glory from the west.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "An island-farm - broad seas of corn Stirred by the wandering breath of morn - The happy spot where I was born.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Last night we owned, with looks forlorn, \"Too well the scholar knows There is no rose without a thorn\" - But peace is made! We sing, this morn, \"No thorn without a rose!\"", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "All too soon will Childhood gay realise Life's sober sadness. Let's be merry while we may, innocent and happy Fay!", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "I got through it all with great success, till I came to read out the first verse of the hymn before the sermon, where the two words 'strife strengthened,' coming together, were too much for me, and I had to leave the verse unfinished.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "I mark this day with a white stone.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "The proper definition of a man is an animal that writes letters.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "One of the deep secrets of life is that all that is really worth the doing is what we do for others.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Those of us who knew him best remember him as the kind and loving friend, who contributed so much to the happiness of our lives, and whom we shall truly mourn as one of the best of men.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Never, surely, did any man make more friends among children than he did.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "It was impossible for Mr. Dodgson to pass by the smallest opportunity of speaking to a child, and his winning manner gained the hearts, and generally the tongues, of all whom he met.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "In his estimation, logic was a most important study for everyone. No pains were spared to make it clear and interesting to those who would but consent to learn of him.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "The arrangement of his papers, the classification of his photographs, the order of his books, the lists and registers that he kept about everything imaginable - all this betokened his well-ordered mind.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Everything that he did must be done in the most perfect manner possible; and the same care and attention would be given to other people's affairs, if in any way he could assist or give them pleasure.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Mr. Dodgson had a great horror of being \"lionised,\" and ingeniously silenced his tormentors by representing to them, indirectly, that \"Lewis Carroll,\" the author of \"Alice,\" and \"Mr. Dodgson\" were two separate persons.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Never was there a more delightful host for a \"dinner-party,\" or one who took such pains for your entertainment, fresh and interesting to the last.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "With all his humour he took a serious view of life, and had a very grave vein running through his mind. The simplicity of his faith, his deep reverence, and his child-like faith in the goodness of God were striking.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Mr. Dodgson did not often preach, yet, when he did, he had the power to impress and captivate his hearers. There was no need for him to write out a sermon. Full of earnestness in his subject, the words came without difficulty.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Charles Dodgson, born a romantic and a rationalist, would have fitted more easily into the world of Voltaire and Goethe than into the one that received him.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Charles Lutwidge Dodgson's life in space-time colored his liberated life of the imagination.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Charles, trapped in the cave of his period, was the laughing philosopher who could show others the way out. He spoke the language and played the role of Ariel - the mantle of Prospero ill became him, though he fancied it.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Cramped by his own charts, on a stream itself restricted, his genius directed him to the bottomless ocean of his books, and impelled him to dive under the graciously sparkling surface into the dark swirl of the icy depths.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Rich deposits of perversity crop up in his humor - and his sudden attacks of virtue or sentimentality midway through his own or other persons' jests hint that his imp has suggested to him something particularly unfunny and unpardonable.", Author = "Lewis Carroll" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Lewis_Carroll", Text = "Dodgson of course was a meticulous traveler. He packed each article separately, well wrapped in paper to twice its bulk.", Author = "Lewis Carroll" },
        };
    }
}
