using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class MahatmaGandhi
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "In reality there are as many religions as there are individuals. Religions are different roads converging to the same point. What does it matter that we take different roads, so long as we reach the same goal. Wherein is the cause for quarreling?", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "One of the objects of a newspaper is to understand popular feeling and to give expression to it; another is to arouse among the people certain desirable sentiments; and the third is fearlessly to expose popular defects.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "We who seek justice will have to do justice to others.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "The only real, dignified, human doctrine is the greatest good of all, and this can only be achieved by uttermost self-sacrifice.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "We but mirror the world. All the tendencies present in the outer world are to be found in the world of our body. If we could change ourselves, the tendencies in the world would also change.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Victory attained by violence is tantamount to a defeat, for it is momentary.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "It is not true that we shall necessarily progress if our political conditions undergo a change, irrespectively of the manner in which it is brought about. If the means employed are impure, the change will not be in the direction of progress but very likely in the opposite.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "In matters of conscience, the law of majority has no place.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "When there is only a choice between cowardice and violence, I would advise violence... I would rather have India resort to arms in order to defend her honour than to remain a helpless witness to her own dishonour.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Cowardice is impotence worse than violence. The coward desires revenge but being afraid to die, he looks to others... to do the work of defense for him.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Good government is no substitute for self-government.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Complete civil disobedience is a state of peaceful revolution, a refusal to obey every single state-made law.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I have learnt through bitter experience the one supreme lesson to conserve my anger, and as heat conserved is transmuted into energy, even so our anger controlled can be transmuted into a power which can move the world.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I came in contact with every known Indian anarchist in London. Their bravery impressed me, but I felt that their zeal was misguided. I felt that violence was no remedy for India's ills, and that her civilisation required the use of a different and higher weapon for self-protection.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Satyagraha is made of sterner stuff. There is nothing reserved and nothing secret in it.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "The pre-British period was not a period of slavery. We had some sort of swaraj under Mogul rule. In Akbar’s time the birth of a Pratap was possible, and in Aurangzeb’s time a Sivaji could flourish. Has 150 years of British rule produced any Pratap and Sivaji?", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "It has always been easier to destroy than to create.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I claim that in losing the spinning wheel we lost our left lung. We are, therefore, suffering from galloping consumption. The restoration of the wheel arrests the progress of the fell disease.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "There is no such thing as slow freedom. Freedom is like a birth. Till we are fully free we are slaves.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "There is a higher court than courts of justice and that is the court of conscience. It supersedes all other courts.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I hold the opinion firmly that Civil Disobedience is the purest type of constitutional agitation. Of course, it becomes degrading and despicable if its civil, i.e. non-violent character is a mere camouflage.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Disobedience without civility, discipline, discrimination, non-violence, is certain destruction. Disobedience combined with love is the living water of life. Civil disobedience is a beautiful variant to signify growth, it is not discordance which spells death.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "A man is but the product of his thoughts. What he thinks, he becomes.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Any action that is dictated by fear or by coercion of any kind ceases to be moral.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "No action which is not voluntary can be called moral.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Satan's successes are the greatest when he appears with the name of God on his lips.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "The only tyrant I accept in this world is the \"still small voice\" within me. And even though I have to face the prospect of being a minority of one, I humbly believe I have the courage to be in such a hopeless minority.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Under democracy individual liberty of opinion and action is jealously guarded.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "If one has no affection for a person or a system, one should feel free to give the fullest expression to his disaffection so long as he does not contemplate, promote, or incite violence.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Nonviolence is the first article of my faith. It is also the last article of my creed.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Non-cooperation with evil is as much a duty as is cooperation with good.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Always believe in your dreams, because if you don't, you'll still have hope.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Hinduism is a relentless pursuit after truth and if today it has become moribund, inactive, irresponsive to growth, it is because we are fatigued. As soon as the fatigue is over, Hinduism will burst forth upon the world with a brilliance perhaps never known before.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I do believe in the essential unity of man and for that matter of all that lives. Therefore I believe that if one man gains spiritually, the whole world gains with him and if one man falls, the whole world falls to that extent.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Real Swaraj will come, not by the acquisition of authority by a few, but by the acquisition of the capacity by all to resist authority when it is abused. In other words, Swaraj is to be attained by educating the masses to a sense of their capacity to regulate and control authority.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Man becomes great exactly in the degree in which he works for the welfare of his fellow-men. The best way to find yourself is to lose yourself in the service of others.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I object to violence because, when it appears to do good, the good is only temporary, the evil it does is permanent.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Self-government means continuous effort to be independent of government control, whether it is foreign government or whether it is national. Swaraj government will be a sorry affair if people look up for the regulation of every detail of life.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "What the divine author of the Mahabharata said of his great creation is equally true of Hinduism. Whatever of substance is contained in any other religion is always to be found in Hinduism, and what is not contained in it is insubstantial or unnecessary.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Seven social sins: politics without principles, wealth without work, pleasure without conscience, knowledge without character, commerce without morality, science without humanity, and worship without sacrifice.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Politics without principle, wealth without work, pleasure without conscience, knowledge without character, commerce without morality, science without humanity, and worship without sacrifice - are the seven social sins.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Disobedience is a right that belongs to every human being, and it becomes a sacred duty when it springs from civility.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Hinduism is like the Ganga, pure and unsullied at its source but taking in its course the impurities in the way. Even like the Ganga it is beneficent in its total effect. It takes a provincial form in every provinvce, but the inner substance is retained everywhere.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Our sages have taught us to learn one thing; `As in the Self, so in the Universe.' It is not possible to scan the universe as it is to scan the self. Know the self and you know the universe.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "Now when we talk of brotherhood of men, we stop there and feel that all other life is there for man to exploit for his own purposes. But Hinduism excludes all exploitation.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "I do regard Islam to be a religion of peace in the same sense as Christianity, Buddhism and Hinduism are.", Author = "Mahatma Gandhi" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Mahatma_Gandhi", Text = "An error does not become truth by reason of multiplied propagation, nor does truth become error because nobody sees it. Truth stands, even if there be no public support. It is self sustained.", Author = "Mahatma Gandhi" },
        };
    }
}