using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class MartinLutherKingJr
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We must discover the power of love, the redemptive power of love. And when we discover that we will be able to make of this old world a new world. We will be able to make men better. Love is the only way.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Injustice anywhere is a threat to justice everywhere. We are caught in an inescapable network of mutuality, tied in a single garment of destiny. Whatever affects one directly, affects all indirectly.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We are reaching out for the daybreak of freedom and justice and equality.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "True peace is not merely the absence of tension: it is the presence of justice.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Men often hate each other because they fear each other; they fear each other because they don't know each other; they don't know each other because they cannot communicate; they cannot communicate because they are separated.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Justice is love correcting that which revolts against love.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "It is no longer a choice between violence and nonviolence in this world; it's nonviolence or nonexistence.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The absence of freedom is the presence of death. Any nation or government that deprives an individual of freedom is in that moment committing an act of moral and spiritual murder. Any individual who is not concerned about his freedom commits an act of moral and spiritual suicide.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "True peace is not merely the absence of tension: it is the presence of justice.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Let no man pull you so low as to hate him.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The Christian Gospel is, at bottom, a two-way road. On the one hand, it seeks to change the souls of men, and thereby unite them with God; on the other hand, it seeks to change the environmental conditions of men so that the soul will have a chance after it is changed.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "If one is truly devoted to the religion of Jesus he will seek to rid the earth of social evils. The gospel is social as well as personal.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The decision which we must make now is whether we will give our allegiance to outmoded and unjust customs or whether we owe our ultimate allegiance to God and His will, rather than to man and his folkways.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The decision we must make now is whether we will give our allegiance to outmoded and unjust customs or to the ethical demands of the universe. As Christians we owe our allegiance to God and His will, rather than to man and his folkways.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "I feel that segregation is totally unchristian, and that it is against everything the Christian religion stands for.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "In the struggle for human rights and justice, Negroes will make a mistake if they become bitter and indulge in hate campaigns.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The non-violent Negro is seeking to create the beloved community. He directs his attack on the forces of evil rather than on individuals. The tensions are not between the races, but between the forces of justice and injustice; between the forces of light and darkness.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The absence of freedom is the presence of death. Any nation or government that deprives an individual of freedom is in that moment committing an act of moral and spiritual murder. Any individual who is not concerned about his freedom commits an act of moral and spiritual suicide.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The great problem facing modern man is that the means by which we live have outdistanced the spiritual ends for which we live.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The real problem is that through our scientific genius we've made of the world a neighborhood, but through our moral and spiritual genius we've failed to make of it a brotherhood.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We've got to rediscover these precious values that we've left behind.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Some things are right and some things are wrong. Eternally so, absolutely so.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The thing that we need in the world today is a group of men and women who will stand up for right and to be opposed to wrong, wherever it is.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "It's possible to affirm the existence of God with your lips and deny his existence with your life. The most dangerous type of atheism is not theoretical atheism, but practical atheism ... And the world, even the church, is filled up with people who pay lip service to God and not life service.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "There is something wrong with our world, something fundamentally and basically wrong.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The trouble isn't so much that our scientific genius lags behind, but our moral genius lags behind. The great problem facing modern man is that the means by which we live have outdistanced the spiritual ends for which we live.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Sometimes, you know, it's necessary to go backward in order to go forward. That's an analogy of life.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We've left a lot of precious values behind; we've lost a lot of precious values. And if we are to go forward, if we are to make this a better world in which to live, we've got to go back. We've got to rediscover these precious values that we've left behind.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The first principle of value that we need to rediscover is this: that all reality hinges on moral foundations. In other words, that this is a moral universe, and that there are moral laws of the universe just as abiding as the physical laws.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "And I think, my friends, that that is the thing that has happened in America. That we have unconsciously left God behind. Now, we haven't consciously done it; we have unconsciously done it.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "The materialism in America has been an unconscious thing. Since the rise of the Industrial Revolution in England, and then the invention of all of our gadgets and contrivances and all of the things and modern conveniences - we unconsciously left God behind. We didn't mean to do it.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We became so involved and fascinated by the intricacies of television that we found it a little more convenient to stay at home than to come to church. It was an unconscious thing - we didn't mean to do it.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Not in the little gods that can be with us in a few moments of prosperity, but in the God who walks with us through the valley of the shadow of death, and causes us to fear no evil. That's the God.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Not in the god that can give us a few Cadillac cars and Buick convertibles, as nice as they are, that are in style today and out of style three years from now, but the God who threw up the stars to bedeck the heavens like swinging lanterns of eternity.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "I'm not going to put my ultimate faith in the little gods that can be destroyed in an atomic age, but the God who has been our help in ages past, and our hope for years to come, and our shelter in the time of storm, and our eternal home. That's the God that I'm putting my ultimate faith in.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "If we are to go forward, we must go back and rediscover these precious values - that all reality hinges on moral foundations and that all reality has spiritual control.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "There is the danger that you will misuse your capitalism. I still contend that money can be the root of all evil. It can cause one to live a life of gross materialism.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Freedom only comes through persistent revolt, through persistent agitation, through persistently rising up against the system of evil.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "These men so often have a high blood pressure of words and an anemia of deeds.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "We must work passionately and unrelentingly for the goal of freedom, but we must be sure that our hands are clean in the struggle. We must never struggle with falsehood, hate, or malice. We must never become bitter.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "I'm talking about the love of God in the hearts of men. I'm talking about a type of love which will cause you to love the person who does the evil deed while hating the deed that the person does. We've got to love.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Keep moving. Let nothing slow you up. Move on with dignity and honor and respectability.", Author = "Martin Luther King Jr." },
            new Quote { Id = "https://en.wikiquote.org/wiki/Martin_Luther_King_Jr.", Text = "Life's most persistent and urgent question is: 'What are you doing for others?'", Author = "Martin Luther King Jr." },
        };
    }
}
