using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class NikolaTesla
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The scientific man does not aim at an immediate result. He does not expect that his advanced ideas will be readily taken up. His work is like that of the planter — for the future. His duty is to lay the foundation for those who are to come, and point the way. He lives and labors and hopes.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Ere many generations pass, our machinery will be driven by a power obtainable at any point of the universe. Throughout space there is energy. If kinetic — and this we know it is, for certain — then it is a mere question of time when men will succeed in attaching their machinery to the very wheelwork of nature.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Ere long intelligence—transmitted without wires—will throb through the earth like a pulse through a living organism. The wonder is that, with the present state of knowledge and the experiences gained, no attempt is being made to disturb the electrostatic or magnetic condition of the earth, and transmit, if nothing else, intelligence.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Nature may reach the same result in many ways. Like a wave in the physical world, in the infinite ocean of the medium which pervades all, so in the world of organisms, in life, an impulse started proceeds onward... In no way can we get such an overwhelming idea of the grandeur of Nature than when we consider, that in accordance with the law of the conservation of energy, throughout the Infinite, the forces are in a perfect balance, and hence the energy of a single thought may determine the motion of a universe.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Our virtues and our failings are inseparable, like force and matter. When they separate, man is no more.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "In a crystal we have the clear evidence of the existence of a formative life-principle, and though we cannot understand the life of a crystal, it is none the less a living being.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "When the great truth accidentally revealed and experimentally confirmed is fully recognized, that this planet, with all its appalling immensity, is to electric currents virtually no more than a small metal ball and that by this fact many possibilities, each baffling imagination and of incalculable consequence, are rendered absolutely sure of accomplishment; ... humanity will be like an ant heap stirred up with a stick: See the excitement coming!", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Of all the frictional resistances, the one that most retards human movement is ignorance, what Buddha called 'the greatest evil in the world.' The friction which results from ignorance ... can be reduced only by the spread of knowledge and the unification of the heterogeneous elements of humanity. No effort could be better spent.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "As soon as it is completed, it will be possible for a business man in New York to dictate instructions, and have them instantly appear in type at his office in London or elsewhere. He will be able to call up, from his desk, and talk to any telephone subscriber on the globe, without any change whatever in the existing equipment.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Money does not represent such a value as men have placed upon it. All my money has been invested into experiments with which I have made new discoveries enabling mankind to have a little easier life.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Let the future tell the truth and evaluate each one according to his work and accomplishments. The present is theirs; the future, for which I really worked, is mine.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The idea of atomic energy is illusionary but it has taken so powerful a hold on the minds, that although I have preached against it for twenty-five years, there are still some who believe it to be realizable.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "I have harnessed the cosmic rays and caused them to operate a motive device.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "If Edison had a needle to find in a haystack, he would proceed at once with the diligence of the bee to examine straw after straw until he found the object of his search. … I was a sorry witness of such doings, knowing that a little theory and calculation would have saved him ninety per cent of his labor.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Edison was by far the most successful and, probably, the last exponent of the purely empirical method of investigation. Everything he achieved was the result of persistent trials and experiments often performed at random but always attesting extraordinary vigor and resource.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "I hold that space cannot be curved, for the simple reason that it can have no properties. It might as well be said that God has properties. I, for one, refuse to subscribe to such a view.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The mind is sharper and keener in seclusion and uninterrupted solitude. No big laboratory is needed in which to think. Originality thrives in seclusion free of outside influences beating upon us to cripple the creative mind. Be alone, that is the secret of invention; be alone, that is when ideas are born.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Today's scientists have substituted mathematics for experiments, and they wander off through equation after equation, and eventually build a structure which has no relation to reality.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The scientists from Franklin to Morse were clear thinkers and did not produce erroneous theories. The scientists of today think deeply instead of clearly. One must be sane to think clearly, but one can think deeply and be quite insane.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Einstein's relativity work is a magnificent mathematical garb which fascinates, dazzles and makes people blind to the underlying errors. The theory is like a beggar clothed in purple whom ignorant people take for a king... its exponents are brilliant men but they are metaphysicists rather than scientists.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Guglielmo Marconi is a good fellow. Let him continue. He is using seventeen of my patents.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "I do not think there is any thrill that can go through the human heart like that felt by the inventor as he sees some creation of the brain unfolding to success … Such emotions make a man forget food, sleep, friends, love, everything.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "When we speak of man, we have a conception of humanity as a whole, and before applying scientific methods to the investigation of his movement we must accept this as a physical fact. But can anyone doubt to-day that all the millions of individuals and all the innumerable types and characters constitute an entity, a unit? Though free to think and act, we are held together, like the stars in the firmament, with ties inseparable. These ties cannot be seen, but we can feel them.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "For every person who perishes from the effects of a stimulant, at least a thousand die from the consequences of drinking impure water. This precious fluid, which daily infuses new life into us, is likewise the chief vehicle through which disease and death enter our bodies. The germs of destruction it conveys are enemies all the more terrible as they perform their fatal work unperceived.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The production of artificial food as a means for causing an increase of the human mass naturally suggests itself, but a direct attempt of this kind to provide nourishment does not appear to me rational, at least not for the present. Whether we could thrive on such food is very doubtful.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "There can be no doubt that, of all the frictional resistances, the one that most retards human movement is ignorance. Not without reason said that man of wisdom, Buddha: 'Ignorance is the greatest evil in the world.' The friction which results from ignorance, and which is greatly increased owing to the numerous languages and nationalities, can be reduced only by the spread of knowledge and the unification of the heterogeneous elements of humanity. No effort could be better spent.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "It has been argued that the perfection of guns of great destructive power will stop warfare. So I myself thought for a long time, but now I believe this to be a profound mistake. Such developments will greatly modify, but not arrest it.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "As regards the security of a country against foreign invasion, it is interesting to note that it depends only on the relative, and not the absolute, number of the individuals or magnitude of the forces, and that, if every country should reduce the war-force in the same ratio, the security would remain unaltered.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "So we find that the three possible solutions of the great problem of increasing human energy are answered by the three words: food, peace, work. Many a year I have thought and pondered, lost myself in speculations and theories, considering man as a mass moved by a force, viewing his inexplicable movement in the light of a mechanical one, and applying the simple principles of mechanics to the analysis of the same until I arrived at these solutions, only to realize that they were taught to me in my early childhood.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "The ultimate results of development in these three directions are: first, the burning of coal by a cold process in a battery; second, the efficient utilization of the energy of the ambient medium; and, third the transmission without wires of electrical energy to any distance.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Iron is by far the most important factor in modern progress. It contributes more than any other industrial product to the force accelerating human movement. So general is the use of this metal, and so intimately is it connected with all that concerns our life, that it has become as indispensable to us as the very air we breathe.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Aluminium, however, will not stop at downing copper. Before many years have passed it will be engaged in a fierce struggle with iron, and in the latter it will find an adversary not easy to conquer.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "A far better way, however, to obtain power would be to avail ourselves of the sun's rays, which beat the earth incessantly and supply energy at a maximum rate of over four million horsepower per square mile.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Another of these reasons was that I was led to recognize the transmission of electrical energy to any distance through the media as by far the best solution of the great problem of harnessing the sun's energy for the uses of man. For a long time I was convinced that such a transmission on an industrial scale, could never be realized, but a discovery which I made changed my view.", Author = "Nikola Tesla" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Nikola_Tesla", Text = "Electrical pressures of many millions of volts had to be produced and handled; generating apparatus of a novel kind, capable of withstanding the immense electrical stresses, had to be invented and perfected, and a complete safety against the dangers of the high-tension currents had to be attained in the system before its practical introduction could be even thought of.", Author = "Nikola Tesla" },
        };
    }
}