using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class OprahWinfrey
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I do not choose to be a common man. It is my right to be uncommon—if I can. I seek opportunity—not security.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I've been stopped cold from eating another burger!", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "My reaction is that free speech not only lives, it rocks!", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I will continue to use my voice. I believed from the beginning that the lawsuit was an attempt to muzzle my voice, and I come from a people who have struggled and died in order to have a voice in this country. And I refused to be muzzled.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I'm still off hamburgers.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I never think about what I want. It's about what you want to give to other people.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "It felt like a new day.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "What I learned at a very early age was that I was responsible for my life. And as I became more spiritually conscious, I learned that we all are responsible for ourselves, that you create your own reality by the way you think and therefore act. You cannot blame apartheid, your parents, your circumstances, because you are not your circumstances. You are your possibilities. If you know that, you can do anything.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "What other people label or might try to call failure, I have learned is just God's way of pointing you in a new direction.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I believe that every single event in life happens in an opportunity to choose love over fear.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "All the energy that you spend, trying to hurt somebody else, that energy will turn around and slap you in the face. The same thing is true, Love, what I know is that the energy that put out everyday with the best of intentions that it would reach you where you really live in heart of yourself has come back to me from all of you in full force. So that what we've learnt on this show; You are responsible for your life and when you get that, everything changes, my friends. So don't wait for somebody else to fix you, to save you or complete you...", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "People often ask me: \"What is the secret to the success of the show?\" \"How it lasted 25 years?\" I none jokingly say: \"My team and Jesus\", because nothing but the Hand of God has made this possible for me.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I won't say goodbye, I'll just say until we meet again. To God be the glory.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I feel like my soul is aching for the country. … There's not a day that goes by where I'm not putting on my shoes, or brushing my teeth, where I just think about the ordinariness of, people who just went to a concert, or the ordinariness of the day from people from 9/11, who were just doing an ordinary thing, and then you never get home. … So, I would say that these days of crisis and tragedy are to remind us all to be present in the ordinariness of our lives, that actually turns out to be extraordinary, when the person you love doesn't come home at night.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "it's an opportunity to show the best of ourselves, when the worst shows up.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I would say, we can't allow ourselves to be frightened into not living our lives, and I think that we have to keep going and we have to keep going with the faith that thing will get better … And things will get better when we make them better.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I know where my lane is, and I know how to stay in my lane. My lane is evolving the consciousness of people.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "The thing that I do best is \"Be Here. Be Now\".", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Turn your wounds into wisdom.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Trust your heart, and success will come to you.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Surround yourself with people only who are going to take you higher", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Your life is not static. Every decision, setback, or triumph is an opportunity to identify the seeds of truth that make you the wondrous human being that you are. I'm not talking just about what you do for a living. When you pay attention to what feeds your energy, you move in the direction of the life for which you were intended. Trust that the Universe has a bigger, wider, deeper dream for you than you could ever imagine for yourself.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "As you begin to identify the seeds of knowing along your own path, the first question to ask yourself is, 'What do I believe?' Do you believe that you are worthy of happiness, success, abundance, fulfillment, peace, joy, and love? What I know for sure is you become what you believe.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Nourish what makes you feel confident, connected, contented. Opportunity will rise to meet you.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "We allow life to get so complicated- when it's really so very simple. From that day forward I resolved to continually ask myself, 'How am I making things more difficult than they need to be?' Your answer to that same question is the next step in your path. It's that simple. Imagine what lies just around the bend. Can you see it? I can. Love, Oprah.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Small steps lead to big accomplishments.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "everything is always working out for you.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Failure is what’s going to humble you.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Be yourself–but be all of you.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "This election isn’t about \"us and them\". It’s about you and me and what we want our futures to look like.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "When we stand together, it is impossible to conquer us.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "America is an ongoing project. It requires commitment, it requires being open to the hard work and the heart work of democracy. And every now and then, it requires standing up to life’s bullies.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "But more often than not, what I’ve witnessed and experienced are human beings, both conservative and liberal, who may not agree with each other, but who would still help you in a heartbeat if you were in trouble. These are the people who make me proud to say that I am an American. They are the best of America.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "And despite what some would have you think, we are not so different from our neighbors. When a house is on fire, we don’t ask about the homeowner’s race or religion. We don’t wonder who their partner is or how they voted. No, we just try to do the best we can to save them.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "These are complicated times, people, and they require adult conversation. And I welcome those conversations because civilized debate is vital to democracy, and it is the best of America.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Voting is the best of America. And I have always, since I was eligible to vote, I’ve always voted my values. And that is what is needed in this election, now more than ever.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "And just plain common sense.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Let us choose loyalty to the Constitution over loyalty to any individual, because that’s the best of America. And let us choose optimism over cynicism, because that’s the best of America. And let us choose inclusion over retribution. Let us choose common sense over nonsense, because that’s the best of America.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "And let us choose the sweet promise of tomorrow over the bitter return to yesterday. We won’t go back. We won’t be sent back, pushed back, bullied back, kicked back. We’re not going back.", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "And let us choose truth, let us choose honor, and let us choose joy! Because that’s the best of America. But more than anything else, let us choose freedom. Why? Because that’s the best of America. We’re all Americans, and together, let’s all choose Kamala Harris!", Author = "Oprah Winfrey" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "She actually is somebody who has the ability to move mountains and change minds.", Author = "Dana Bash" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "Oprah is different. Oprah has an army out there that really listens. She's one of the great marketing machines in history.", Author = "Howard Davidowitz" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "So far, I don't see anything negative on this woman. I think she's a real icon. She's much more complex and complicated than just a talk show host. Maya Angelou has said she sees her as a true missionary. Everybody has a different take on Oprah.", Author = "Kitty Kelly" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "She's — her great strength, if anybody watches the show — and I think everybody does in Iowa; it's the number one show in Iowa — she's instructive. She's empowering. Every time you watch an Oprah broadcast, at the end of it, you know more than you started and you feel stronger. That's her strength.", Author = "Chris Matthews" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "You have to admire Oprah Winfrey. She is the most powerful woman in the country and comes from a very humble background. The woman has succeeded on talent and energy.", Author = "Bill O'Reilly" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Oprah_Winfrey", Text = "I am grateful for the contribution Oprah Winfrey has made to our country in regard to reading.", Author = "Donald John Trump" },
        };
    }
}