using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class RichardFeynman
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The first principle is that you must not fool yourself – and you are the easiest person to fool.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "All mass is interaction.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "In this age of specialization men who thoroughly know one field are often incompetent to discuss another. The great problems of the relations between one and another aspect of human activity have for this reason been discussed less and less in public.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The old problems, such as the relation of science and religion, are still with us, and I believe present as difficult dilemmas as ever, but they are not often publicly discussed because of the limitations of specialization.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The other great heritage is Christian ethics — the basis of action on love, the brotherhood of all men, the value of the individual — the humility of the spirit.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "How can we draw inspiration to support these two pillars of western civilization so that they may stand together in full vigor, mutually unafraid?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Is this not the central problem of our time?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The stage is too big for the drama.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The real problem in speech is not precise language. The problem is clear language.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The desire is to have the idea clearly communicated to the other person.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "It is really quite impossible to say anything with absolute precision, unless that thing is so abstracted from the real world as to not represent any real thing.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "even though we may consistently consider ourselves to be the outside observer when we look at the rest of the world, the rest of the world is at the same time observing us, and that often we agree on what we see in each other.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Do you seriously entertain the idea that without the observer there is no reality?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We have a habit in writing articles published in scientific journals to make the work as finished as possible, to cover all the tracks, to not worry about the blind alleys or to describe how you had the wrong idea first, and so on.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "A very great deal more truth can become known than can be proven.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The chance is high that the truth lies in the fashionable direction. But, on the off-chance that it is in another direction — a direction obvious from an unfashionable view of field theory — who will find it?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Science is the belief in the ignorance of experts.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The female mind is capable of understanding analytic geometry.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Energy is a very subtle concept. It is very, very difficult to get right.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Science alone of all the subjects contains within itself the lesson of the danger of belief in the infallibility of the greatest teachers of the preceding generation.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Details that could throw doubt on your interpretation must be given, if you know them. You must do the best you can — if you know anything at all wrong, or possibly wrong — to explain it.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We've learned from experience that the truth will out.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Other experimenters will repeat your experiment and find out whether you were wrong or right. Nature's phenomena will agree or they'll disagree with your theory.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "And it's this type of integrity, this kind of care not to fool yourself, that is missing to a large extent in much of the research in cargo cult science.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "And that is the experiment that tells exactly what conditions you have to use in order to be careful and control everything in an experiment with rat-running.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "But not paying attention to experiments like that is a characteristic of cargo cult science.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "you'll have to accept it, because it's the way nature works. If you want to know the way nature works... We looked at it, carefully... That's the way it looks!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Go somewhere else... to another universe where the rules are simpler, philosophically more pleasing, more psychologically easy.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We are not to tell Nature what she's gotta be!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "She's clever. She's always got better imagination than we have, and she finds a cleverer way to do it than we have thought of.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Light works by probability.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The question of whether or not, when you see something, you see only the light or you see the thing you're looking at, is one of those dopey philosophical things that an ordinary person has no difficulty with.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Tell your son to stop trying to fill your head with science — for to fill your heart with love is enough!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "I cannot define the real problem, therefore I suspect there's no real problem, but I'm not sure there's no real problem.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Nature isn't classical, dammit, and if you want to make a simulation of nature, you'd better make it quantum mechanical, and by golly it's a wonderful problem, because it doesn't look so easy.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "One of the miseries of life is that everybody names things a little bit wrong, and so it makes a little bit harder to understand things than it would have been if they had been named differently.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "I do feel strongly that this is nonsense! ... I think all this superstring stuff is crazy and is in the wrong direction.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "I don't like it that they're not calculating anything.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "God was always invented to explain mystery. God is always invented to explain those things that you do not understand.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "What I cannot create, I do not understand.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Einstein was a giant. His head was in the clouds, but his feet were on the ground. But those of us who are not that tall have to choose!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Physics is to mathematics what sex is to masturbation.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Scientific knowledge is an enabling power to do either good or bad — but it does not carry instructions on how to use it.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The imagination of nature is far, far greater than the imagination of man.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "This is not yet a scientific age.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Our freedom to doubt was born out of a struggle against authority in the early days of science.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Permit us to question — to doubt, that's all — not to be sure.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We must frankly admit that we do not know.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The idea that no one really knew how to run a government led to the idea that we should arrange a system by which new ideas could be developed, tried out, and tossed out if necessary, with more new ideas brought in — a trial and error system.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "If we want to solve a problem that we have never solved before, we must leave the door to the unknown ajar.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We are at the very beginning of time for the human race.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Our responsibility is to do what we can, learn what we can, improve the solutions, and pass them on.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "If we suppress all discussion, all criticism, proclaiming \"This is the answer, my friends; man is saved!\" we will doom humanity for a long time to the chains of authority, confined to the limits of our present imagination.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Each piece, or part, of the whole of nature is always merely an approximation to the complete truth, or the complete truth so far as we know it.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The test of all knowledge is experiment. Experiment is the sole judge of scientific “truth”.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "All things are made of atoms — little particles that move around in perpetual motion, attracting each other when they are a little distance apart, but repelling upon being squeezed into one another.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The rules of the game are what we mean by fundamental physics.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "I too can see the stars on a desert night, and feel them. But do I see less or more?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "What is the pattern, or the meaning, or the why?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "It does not do harm to the mystery to know a little about it.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "For far more marvelous is the truth than any artists of the past imagined!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Why do the poets of the present not speak of it?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "What men are poets who can speak of Jupiter if he were a man, but if he is an immense spinning sphere of methane and ammonia must be silent?", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "Psychoanalysis has not been checked carefully by experiment.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "If our small minds, for some convenience, divide this glass of wine, this universe, into parts — physics, biology, geology, astronomy, psychology, and so on — remember that nature does not know it!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "So let us put it all back together, not forgetting ultimately what it is for.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "It is important to realize that in physics today, we have no knowledge what energy is.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "We cannot define anything precisely.", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "The answer is simple: because we can solve them!", Author = "Richard Feynman" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Richard_Feynman", Text = "because if we understand linear equations, we are ready, in principle, to understand a lot of things.", Author = "Richard Feynman" },
        };
    }
}