using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class RobertBrowning
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Kiss me as if you made believe You were not sure, this eve, How my face, your flower, had pursed It's petals up.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Over my head his arm he flung Against the world.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "There's a woman like a dewdrop, she's so purer than the purest.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Sing, riding's a joy! For me I ride.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Fail I alone, in words and deeds? Why, all men strive and who succeeds?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Who hears music feels his solitude Peopled at once.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Womanliness means only motherhood; All love begins and ends there.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "My sun sets to rise again.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "I find earth not gray but rosy; Heaven not grim but fair of hue.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Never the time and the place And the loved one all together!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What Youth deemed crystal, Age finds out was dew.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "A minute's success pays the failure of years.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "One who never turned his back but marched breast forward, Never doubted clouds would break, Never dreamed, though right were worsted, wrong would triumph, Held we fall to rise, are baffled to fight better, Sleep to wake.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Strive and thrive!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Autumn wins you best by this its mute Appeal to sympathy for its decay.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "That we devote ourselves to God, is seen In living just as though no God there were.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Be sure that God Ne'er dooms to waste the strength he deigns impart.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Truth is within ourselves.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "God is the perfect poet, Who in his person acts his own creations.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Strange secrets are let out by Death Who blabs so oft the follies of this world.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Error has no end.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The sad rhyme of the men who proudly clung To their first fault, and withered in their pride.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Every joy is gain And gain is gain, however small.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Jove strikes the Titans down Not when they set about their mountain-piling But when another rock would crown the work.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The peerless cup afloat Of the lake-lily is an urn some nymph Swims bearing high above her head.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "I give the fight up: let there be an end, A privacy, an obscure nook for me. I want to be forgotten even by God.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Progress is The law of life: man is not Man as yet.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Fear had long since taken root In every breast, and now these crushed its fruit, The ripe hate, like a wine", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "So men believe And worship what they know not, nor receive Delight from.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Deeds let escape are never to be done.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Each a God's germ, but doomed remain a germ In unexpanded infancy", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Any nose May ravage with impunity a rose.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Say not \"a small event!\" Why \"small\"? Costs it more pain that this ye call A \"great event\" should come to pass From that? Untwine me from the mass Of deeds which make up life, one deed Power shall fall short in or exceed!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "In the morning of the world, When earth was nigher heaven than now.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "When is man strong until he feels alone?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The heavens and earth stay as they were; my heart Beats as it beat: the truth remains the truth.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "He gathers earth's whole good into his arms; Standing, as man now, stately, strong and wise, Marching to fortune, not surprised by her.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What's a man's age? He must hurry more, that's all; Cram in a day, what his youth took a year to hold:", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Oh, to be in England Now that April's there,", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "That's the wise thrush; he sings each song twice over, Lest you should think he never could recapture The first fine careless rapture!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "God made all the creatures, and gave them our love and our fear, To give sign we and they are his children, one family here.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "How good is man's life, the mere living! How fit to employ All the heart and the soul and the senses Forever in joy!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "'Tis not what man Does which exalts him, but what man Would do!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Ah, but a man's reach should exceed his grasp, Or what's a heaven for?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Take away love, and our earth is a tomb!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "If you get simple beauty and naught else, You get about the best thing God invents.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "You should not take a fellow eight years old And make him swear to never kiss the girls.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "I count life just a stuff To try the soul's strength on.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What of soul was left, I wonder, when the kissing had to stop?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Progress, man's distinctive mark alone, Not God's, and not the beasts': God is, they are, Man partly is and wholly hopes to be.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Italy, my Italy! Queen Mary's saying serves for me (When fortune's malice Lost her Calais): \"Open my heart, and you will see Graved inside of it ‘Italy.'\"", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Our interest's on the dangerous edge of things. The honest thief, the tender murderer, The superstitious atheist.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "When the fight begins within himself, A man's worth something.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "He said true things, but called them by the wrong names.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "That low man seeks a little thing to do, Sees it and does it. This high man, with a great thing to pursue, Dies ere he knows it.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Lofty designs must close in like effects.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Rafael made a century of sonnets.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Other heights in other lives, God willing.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Stung by the splendour of a sudden thought.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What? Was man made a wheel-work to wind up, And be discharged, and straight wound up anew? No! grown, his growth lasts; taught, he ne'er forgets: May learn a thousand things, not twice the same.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Progress, man's distinctive mark alone, Not God's, and not the beasts': God is, they are; Man partly is, and wholly hopes to be.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The ultimate, angels' law, Indulging every instinct of the soul There where law, life, joy, impulse are one thing!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Grow old along with me! The best is yet to be, The last of life, for which the first was made: Our times are in his hand Who saith, \"A whole I planned, Youth shows but half; trust God: see all, nor be afraid!\"", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Mine be some figured flame which blends, transcends them all! Not for such hopes and fears Annulling youth's brief years, Do I remonstrate: folly wide the mark! Rather I prize the doubt Low kinds exist without, Finished and finite clods, untroubled by a spark.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Let us cry, \"All good things Are ours, nor soul helps flesh more, now, than flesh helps soul!\"", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Be there, for once and all, Severed great minds from small, Announced to each his station in the Past! Was I, the world arraigned, Were they, my soul disdained, Right? Let age speak the truth and give us peace at last!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Fool! All that is, at all, Lasts ever, past recall; Earth changes, but thy soul and God stand sure: What entered into thee, That was, is, and shall be: Time's wheel runs back or stops: Potter and clay endure.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Look not thou down but up! To uses of a cup.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "So, take, and use thy work: Amend what flaws may lurk, What strain o' the stuff, what warpings past the aim! My times be in thy hand! Perfect the cup as planned! Let age approve of youth, and death complete the same!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "A book in shape but, really, pure crude fact Secreted from man's life when hearts beat hard, And brains, high-blooded, ticked two centuries since. Give it me back! The thing's restorative I'the touch and sight.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "A ring without a posy, and that ring mine?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Go practise if you please With men and women: leave a child alone For Christ's particular love's sake!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "In the great right of an excessive wrong.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Was never evening yet But seemed far beautifuller than its day.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "On our Pompilia, faultless to a fault, Law bends a brow maternally severe, Implies the worth of perfect chastity, By fancying the flaw she cannot find.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Oh child that didst despise thy life so much When it seemed only thine to keep or lose, How the fine ear felt fall the first low word \"Value life, and preserve life for My sake!\"", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The curious crime, the fine Felicity and flower of wickedness.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Why comes temptation, but for man to meet And master and make crouch beneath his foot, And so be pedestaled in triumph?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "White shall not neutralize the black, nor good Compensate bad in man, absolve him so: Life's business being just the terrible choice.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Inscribe all human effort with one word, Artistry's haunting curse, the Incomplete!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Thy rare gold ring of verse (the poet praised) Linking our England to his Italy.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "The sprinkled isles, Lily on lily, that o'erlace the sea.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "And I have written three books on the soul, Proving absurd all written hitherto, And putting us to ignorance again.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Just my vengeance complete, The man sprang to his feet, Stood erect, caught at God's skirts, and prayed! So, I was afraid!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Oh never star Was lost here but it rose afar.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "When the liquor's out, why clink the cannikin?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Lost, lost! one moment knelled the woe of years.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Just for a handful of silver he left us, Just for a riband to stick in his coat.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What's come to perfection perishes. Things learned on earth we shall practise in heaven; Works done least rapidly Art most cherishes.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "O woman-country! wooed not wed, Loved all the more by earth's male-lands, Laid to their hearts instead.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "That great brow And the spirit-small hand propping it.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "If two lives join, there is oft a scar. They are one and one, with a shadowy third; One near one is too far.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Only I discern Infinite passion, and the pain Of finite hearts that yearn.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Round and round, like a dance of snow In a dazzling drift, as its guardians, go Floating the women faded for ages, Sculptured in stone on the poet's pages.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "How he lies in his rights of a man! Death has done all death can. And absorbed in the new life he leads, He recks not, he heeds Nor his wrong nor my vengeance; both strike On his senses alike, And are lost in the solemn and strange Surprise of the change.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Ah, did you once see Shelley plain, And did he stop and speak to you, And did you speak to him again? How strange it seems, and new!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "He who did well in war just earns the right To begin doing well in peace.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "A people is but the attempt of many To rise to the completer life of one; And those who live as models for the mass Are singly of more value than they all.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "I count life just a stuff To try the soul's strength on.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Was there nought better than to enjoy? No feat which, done, would make time break, And let us pent-up creatures through Into eternity, our due? No forcing earth teach heaven's employ?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "There shall never be one lost good! What was, shall live as before; The evil is null, is nought, is silence implying sound; What was good shall be good, with for evil so much good more; On the earth the broken arcs; in the heaven, a perfect round.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Then welcome each rebuff That turns earth's smoothness rough, Each sting that bids nor sit nor stand, but go! Be our joys three-parts pain! Strive, and hold cheap the strain; Learn, nor account the pang; dare, never grudge the throe!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "What I aspired to be, And was not, comforts me.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "How sad and bad and mad it was! But then, how it was sweet!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "So may a glory from defect arise.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "But how carve way i' the life that lies before, If bent on groaning ever for the past?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "With this same key Shakespeare unlocked his heart\" once more! Did Shakespeare? If so, the less Shakespeare he!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "God's justice, tardy though it prove perchance, Rests never on the track until it reach Delinquency.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Good, to forgive; Best, to forget! Living, we fret; Dying, we live.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "Can we love but on condition that the thing we love must die?", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "As if true pride Were not also humble!", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "But little do or can the best of us: That little is achieved through Liberty.", Author = "Robert Browning" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Robert_Browning", Text = "There is no truer truth obtainable By Man than comes of music.", Author = "Robert Browning" },
        };
    }
}