using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class RudyardKipling
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Words are, of course, the most powerful drug used by mankind.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "There is no middle way in this war. We do not doubt our ultimate victory any more than we doubt the justice of our cause. It is not conceivable that we should fail, for if we fail the lights of freedom go out over the whole world.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "The individual has always had to struggle to keep from being overwhelmed by the tribe. To be your own man is a hard business. If you try it, you'll be lonely often, and sometimes frightened. But no price is too high to pay for the privilege of owning yourself.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "The toad beneath the harrow knows Exactly where each tooth point goes; The butterfly upon the road Preaches contentment to that toad.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "And a woman is only a woman, but a good cigar is a smoke.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "It takes a great deal of Christianity to wipe out uncivilized Eastern instincts, such as falling in love at first sight.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "The silliest woman can manage a clever man; but it needs a very clever woman to manage a fool!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Never praise a sister to a sister, in the hope of your compliments reaching the proper ears, and so preparing the way for you later on. Sisters are women first, and sisters afterwards; and you will find that you do yourself harm.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Everyone is more or less mad on one point.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "East of Suez, some hold, the direct control of Providence ceases; Man being there handed over to the power of the Gods and Devils of Asia, and the Church of England Providence only exercising an occasional and modified supervision in the case of Englishmen.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "I've taken my fun where I've found it; I've rogued an' I've ranged in my time.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For the colonel's lady an' Judy O'Grady, Are sisters under their skins.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For it's Tommy this, an' Tommy that, an' \"Chuck him out, the brute!\" But it's \"Saviour of 'is country\" when the guns begin to shoot.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "'E's all 'ot sand an' ginger when alive An' 'e's generally shammin' when 'e's dead.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Oh the road to Mandalay Where the flyin'-fishes play An' the dawn comes up like thunder outer China 'crost the Bay!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Ship me somewheres east of Suez, where the best is like the worst, Where there aren't no Ten Commandments, an' a man can raise a thirst.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "There is none like to me!' says the Cub in the pride of his earliest kill; But the jungle is large and the Cub he is small. Let him think and be still.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "We be of one blood, ye and I.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Brother, thy tail hangs down behind! This is the way of the Monkey-kind!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Now this is the Law of the Jungle-as old and as true as the sky; And the Wolf that shall keep it may prosper, but the Wolf that shall break it must die.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For the strength of the Pack is the Wolf, and the strength of the Wolf is the Pack.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "When Pack meets with Pack in the Jungle, and neither will go from the trail, Lie down till the leaders have spoken-it may be fair words shall prevail.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Now these are the Laws of the jungle, and many and mighty are they; But the head and the hoof of the Law and the haunch and the hump is-Obey!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "If you can force your heart and nerve and sinew To serve your turn long after they are gone, And so hold on when there is nothing in you Except the will which says to them: \"Hold on!\"", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "We have fed our sea for a thousand years And she calls us, still unfed, Though there's never a wave of all her waves But marks our English dead.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "They change their skies above them, But not their hearts that roam!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "There are nine and sixty ways of constructing tribal lays, And every single one of them is right!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For 'im that doth not work must surely die; But that's no reason man should labour all 'Is life on one same shift-life's none so long.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "'E's a sort of a bloomin' cosmopolouse-soldier an' sailor too.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "I keep six honest serving-men: (They taught me all I knew) Their names are What and Where and When And How and Why and Who.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Take of English earth as much As either hand may rightly clutch. In the taking of it breathe Prayer for all who lie beneath.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "If any question why we died, Tell them, because our fathers lied.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "I could not dig: I dared not rob: Therefore I lied to please the mob. Now all my lies are proved untrue And I must face the men I slew. What tale shall serve me here among Mine angry and defrauded young?", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "But that's another story.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Being kissed by a man who didn't wax his moustache was like eating an egg without salt.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Men and women may sometimes, after great effort, achieve a creditable lie; but the house, which is their temple, cannot say anything save the truth of those who have lived in it.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Enough work to do, and strength enough to do the work.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Brothers and Sisters, I bid you beware Of giving your heart to a dog to tear.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For the female of the species is more deadly than the male.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "No easy hope or lies Shall bring us to our goal, But iron sacrifice Of body, will, and soul.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "There is but one task for all- One life for each to give. What stands if Freedom fall? Who dies if England live?", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "As I pass through my incarnations in every age and race, I make my proper prostrations to the Gods of the Market-Place. Peering through reverent fingers I watch them flourish and fall, And the Gods of the Copybook Headings, I notice, outlast them all.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Never again will I spend another winter in this accursed bucket shop of a refrigerator called England.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "A people always ends by resembling its shadow.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "When your Daemon is in charge, do not try to think consciously. Drift, wait, and obey.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Four things greater than all things are,- Women and Horses and Power and War.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Two things greater than all things are, The first is Love, and the second War.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Down to Gehenna or up to the Throne, He travels the fastest who travels alone.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "More men are killed by overwork than the importance of the world justifies.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "For all we take we must pay, but the price is cruel high.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "We know that the tail must wag the dog, for the horse is drawn by the cart; But the Devil whoops, as he whooped of old: \"It's clever, but is it Art?\"", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Bite on the bullet, old man, and don't let them think you're afraid.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "San Francisco is a mad city-inhabited for the most part by perfectly insane people, whose women are of a remarkable beauty.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Asia is not going to be civilised after the methods of the West. There is too much Asia and she is too old.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Winds of the World, give answer! They are whimpering to and fro- And what should they know of England who only England know?", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Take up the White Man's burden- Send forth the best ye breed- Go bind your sons to exile To serve your captives' need.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Let us admit it fairly, as a business people should, We have had no end of a lesson: it will do us no end of good.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "It was our fault, and our very great fault-and now we must turn it to use. We have forty million reasons for failure, but not a single excuse.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Who hath desired the Sea?-the sight of salt water unbounded- The heave and the halt and the hurl and the crash of the comber wind-hounded?", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Something hidden. Go and find it. Go and look behind the Ranges- Something lost behind the Ranges. Lost and waiting for you. Go!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Boots-boots-boots-boots-movin' up and down again! There's no discharge in the war!", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "That's the secret. 'Tisn't beauty, so to speak, nor good talk necessarily. It's just It. Some women'll stay in a man's memory if they once walk down a street.", Author = "Rudyard Kipling" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Rudyard_Kipling", Text = "Fiction is Truth's elder sister. Obviously. No one in the world knew what truth was till some one had told a story.", Author = "Rudyard Kipling" },
        };
    }
}
