using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class SamuelBeckett
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Spend the years of learning squandering Courage for the years of wandering Through a world politely turning From the loutishness of learning.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "The only sin is the sin of being born.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "If by Godot I had meant God I would have said God, and not Godot.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "It means what it says.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I grow gnomic. It is the last phase.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "The confusion is not my invention. We cannot listen to a conversation for five minutes without being acutely aware of the confusion. It is all around us and our only chance now is to let it in.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "The sun shone, having no alternative, on the nothing new.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "God is a witness that cannot be sworn.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Personally of course I regret everything.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "But he had turned, little by little, a disturbance into words, he had made a pillow of old words, for his head.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Bid us sigh on from day to day, And wish and wish the soul away, Till youth and genial years are flown, And all the life of life is gone.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Memories are killing. So you must not think of certain things, of those that are dear to you, or rather you must think of them, for if you don't there is the danger of finding them, in your mind, little by little.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "They were most correct, according to their god.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I have always been amazed at my contemporaries' lack of finesse, I whose soul writhed from morning to night, in the mere quest of itself.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Poor juvenile solutions, explaining nothing. No need then for caution, we may reason on to our heart's content, the fog won't lift.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Does one ever know oneself why one laughs?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Living souls, you will see how alike they are.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "They never lynch children, babies, no matter what they do they are whitewashed in advance.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "All I say cancels out, I'll have said nothing.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "To think that in a moment all will be said, all to do again.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "They didn't say in so many words that I was as well as I would ever be, but that was the implication.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "My appearance still made people laugh, with that hearty jovial laugh so good for the health.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Strictly speaking I wasn't there. Strictly speaking I believe I've never been anywhere.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I knew it would soon be the end, so I played the part, you know, the part of - how shall I say, I don't know.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "The expression that there is nothing to express, nothing with which to express, nothing from which to express, no power to express, no desire to express, together with the obligation to express.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Don't wait to be hunted to hide, that's always been my motto.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "To restore silence is the role of objects.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "To him who has nothing it is forbidden not to relish filth.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Saying is inventing. Wrong, very rightly wrong.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Watch wound and buried by the watchmaker, before he died, whose ruined works will one day speak of God, to the worms.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Can it be we are not free? It might be worth looking into.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "For had I been able to conceive something worse than what I had I would have known no peace until I got it, if I know anything about myself.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "In me there have always been two fools, among others, one asking nothing better than to stay where he is and the other imagining that life might be slightly less horrible a little further on.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Yes, there were times when I forgot not only who I was, but that I was, forgot to be.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What do you expect, one is what one is, partly at least.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "At least I did not go in a circle, and that was something.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What I assert, deny, question, in the present, I still can. But mostly I shall use the various tenses of the past. For mostly I do not know, it is perhaps no longer so, it is too soon to know, I simply do not know, perhaps shall never know.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Unfathomable mind, now beacon, now sea.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I was not made for the great light that devours, a dim lamp was all I had been given, and patience without end, to shine it on the empty shadows.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "To decompose is to live too, I know, I know, don't torment me, but one sometimes forgets.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Let me cry out then, it's said to be good for you. Yes let me cry out, this time, then another time perhaps, then perhaps a last time.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "There is a little of everything, apparently, in nature, and freaks are common.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Tears and laughter, they are so much Gaelic to me.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Nothing is more real than nothing.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Nothing to be done.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Isn't that obvious?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I find this really most extraordinarily interesting.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Let's hang ourselves immediately!", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "The tears of the world are a constant quantity. For each one who begins to weep, somewhere else another stops. The same is true of the laugh.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Let us not then speak ill of our generation, it is not any unhappier than its predecessors.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "It would have passed in any case.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Mr Godot told me to tell you he won't come this evening but surely tomorrow.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "We are all born mad. Some remain so.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "They give birth astride of a grave, the light gleams an instant, then it's night once more.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What have I said?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "We are not saints, but we have kept our appointment. How many people can boast as much?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What makes me weep so? From time to time. There is nothing saddening here.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I only see what appears close beside me, what I best see I see ill.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Some of this rubbish has come in handy on occasions, I don't deny it, on occasions which would never have arisen if they had left me in peace.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "I, of whom I know nothing, I know my eyes are open, because of the tears that pour from them unceasingly.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Dear incomprehension, it's thanks to you I'll be myself, in the end.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "At no moment do I know what I'm talking about, nor of whom, nor of where, nor how, nor why, but I could employ fifty wretches for this sinister operation and still be short of the fifty-first, to close the circuit, that I know, without knowing what it means.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What a joy to know where one is, and where one will stay, without being there.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What can it matter to me, that I succeed or fail? The undertaking is none of mine, if they want me to succeed I'll fail, and vice versa, so as not to be rid of my tormentors.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Yes, in my life, since we must call it so, there were three things, the inability to speak, the inability to be silent, and solitude, that's what I've had to make the best of.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "My keepers, why keepers, I'm in no danger of stirring an inch, ah I see, it's to make me think I'm a prisoner, frantic with corporeality, rearing to get out and away.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "No need of a story, a story is not compulsory, just a life, that's the mistake I made, one of the mistakes, to have wanted a story for myself, whereas life alone is enough.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Hamm: Can there be misery loftier than mine?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Hamm: Ah, the old questions, the old answers, there's nothing like them!", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Hamm: There's something dripping in my head. A heart, a heart in my head.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Clov: When I fall I'll weep for happiness.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "We still find it funny, but we don't laugh any more.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "What in God's name could there be on the horizon?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Hamm: Gray! Did I hear you say gray?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Hamm: We're not beginning ... to ... to ... mean something?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Perhaps my best years are gone. When there was a chance of happiness. But I wouldn't want them back. Not with the fire in me now.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Ah finish your booze now and get to your bed. Go on with this drivel in the morning. Or leave it at that.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "No way in, go in, measure.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Nohow less. Nohow worse. Nohow naught. Nohow on.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Birth was the death of him.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Why can't you write the way people want?", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "Its author has achieved a theoretical impossibility - a play in which nothing happens, that yet keeps audiences glued to their seats.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "He has written a play in which nothing happens, twice.", Author = "Samuel Beckett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Beckett", Text = "He was a taciturn man.", Author = "Samuel Beckett" },
        };
    }
}
