using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class SamuelTaylorColeridge
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Blest hour! it was a luxury - to be!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "O! I do love thee, meek Simplicity!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "And this reft house is that the which he built, Lamented Jack!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "So for the mother's sake the child was dear, And dearer was the mother for the child.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "In nature there is nothing melancholy.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "With what deep worship I have still adored The spirit of divinest Liberty.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "O Liberty! my spirit felt thee there.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The frost performs its secret ministry, Unhelped by any wind.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Only that film, which fluttered on the grate, Still flutters there, the sole unquiet thing.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Or if the secret ministry of frost Shall hang them up in silent icicles, Quietly shining to the quiet moon.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Alas! said she, we ne'er can be Made happy by compulsion.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "And the Devil did grin, for his darling sin Is pride that apes humility.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Strongly it bears us along in swelling and limitless billows, Nothing before and nothing behind but the sky and the ocean.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "In the hexameter rises the fountain's silvery column; In the pentameter aye falling in melody back.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Joy rises in me, like a summer's morn.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Well, they are gone, and here must I remain, This lime-tree bower my prison!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Tranquillity! thou better name Than all the family of Fame!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Aloof with hermit-eye I scan The present works of present man - A wild and dreamlike trade of blood and guile, Too foolish for a tear, too wicked for a smile!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "What is an Epigram? a dwarfish whole, Its body brevity, and wit its soul.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Trochee trips from long to short; From long to long in solemn sort Slow Spondee stalks.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Iambics march from short to long;- With a leap and a bound the swift Anapaests throng.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "And looking to the Heaven, that bends above you, How oft! I bless the Lot, that made me love you.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "His soul is with the saints, I trust.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "To know, to esteem, to love-and then to part, Makes up life's tale to many a feeling heart!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The Eighth Commandment was not made for bards.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Nought cared this Body for wind or weather When Youth and I lived in't together.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "In many ways doth the full heart reveal The presence of the love it would conceal.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "My eyes make pictures, when they are shut.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "I counted two and seventy stenches, All well defined, and several stinks!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "If a man could pass through Paradise in a dream, and have a flower presented to him as a pledge that his soul had really been there, and if he found that flower in his hand when he awake - Aye! and what then?", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "In Xanadu did Kubla Khan A stately pleasure-dome decree: Where Alph, the sacred river, ran Through caverns measureless to man Down to a sunless sea.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The shadow of the dome of pleasure Floated midway on the waves; Where was heard the mingled measure From the fountain and the caves.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "It was a miracle of rare device, A sunny pleasure-dome with caves of ice!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "A sight to dream of, not to tell!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Saints will aid if men will call: For the blue sky bends over all!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "They stood aloof, the scars remaining,- Like cliffs which had been rent asunder: A dreary sea now flows between.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "I see, not feel, how beautiful they are!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "I may not hope from outward forms to win The passion and the life, whose fountains are within.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "O lady! we receive but what we give And in our life alone does Nature live.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "A light, a glory, a fair luminous cloud Enveloping the earth.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "I've lived and loved.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The doing evil to avoid an evil Cannot be good.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Clothing the palpable and the familiar With golden exhalations of the dawn.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Often do the spirits Of great events stride on before the events, And in to-day already walks to-morrow.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "O struggling with the darkness all the night, And visited all night by troops of stars.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Motionless torrents! silent cataracts!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "A mother is a mother still; The holiest thing alive.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "An instinctive taste teaches men to build their churches in flat countries, with spire-steeples, which, as they cannot be referred to any other object, point as with silent finger to the sky and star.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The Dwarf sees farther than the Giant, when he has the Giant's shoulders to mount on.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Reviewers are usually people who would have been poets, historians, biographers, etc., if they could; they have tried their talents at one or the other, and have failed; therefore they turn critics.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The poet is not only the man made to solve the riddle of the universe, but he is also the man who feels where it is not solved.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The proper and immediate object of science is the acquirement, or communication, of truth; the proper and immediate object of poetry is the communication of immediate pleasure.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Iago's soliloquy-the motive-hunting of a motiveless malignity-how awful it is!", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Taste is the intermediate faculty which connects the active with the passive powers of our nature, the intellect with the senses; and its appointed function is to elevate the images of the latter, while it realizes the ideas of the former.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The Beautiful arises from the perceived harmony of an object, whether sight or sound, with the inborn and constitutive rules of the judgment and imagination: and it is always intuitive.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "The artist must imitate that which is within the thing, that which is active through form and figure, and discourses to us by symbols.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "In philosophy equally as in poetry it is the highest and most useful prerogative of genius to produce the strongest impressions of novelty, while it rescues admitted truths from the neglect caused by the very circumstance of their universal admission.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "He, who begins by loving Christianity better than Truth, will proceed by loving his own Sect or Church better than Christianity, and end in loving himself better than all.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Your Sensibilities are tempestuous - you feel Indignation at Weakness - Now Indignation is the handsome Brother of Anger and Hatred - His looks are \"lovely in terror\" - yet still remember, 'who' are his 'Relations.'", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "He has no native Passion, because he is not a Thinker - and has probably weakened his Intellect by the haunting Fear of becoming extravagant.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Moral obligation is to me so very strong a Stimulant, that in 9 cases out of ten it acts as a Narcotic. The Blow that should rouse, stuns me.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "Humour is consistent with pathos, whilst wit is not.", Author = "Samuel Taylor Coleridge" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Samuel_Taylor_Coleridge", Text = "It is a flat'ning Thought, that the more we have seen, the less we have to say.", Author = "Samuel Taylor Coleridge" },
        };
    }
}
