using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class Socrates
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It would be better for me... that multitudes of men should disagree with me rather than that I, being one, should be out of harmony with myself.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "One should never do wrong in return, nor mistreat any man, no matter how one has been mistreated by him.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Wonder is the feeling of a philosopher, and philosophy begins in wonder.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "I myself know nothing, except just a little, enough to extract an argument from another man who is wise and to receive it fairly.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Each of these private teachers who work for pay ... inculcates nothing else than these opinions of the multitude which they opine when they are assembled and calls this knowledge wisdom.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Anyone who holds a true opinion without understanding is like a blind man on the right road.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "How singular is the thing called pleasure, and how curiously related to pain, which might be thought to be the opposite of it; for they never come to a man together, and yet he who pursues either of them is generally compelled to take the other.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The true disciple of philosophy is likely to be misunderstood by other men; they do not perceive that he is ever pursuing death and dying; and if this is true, why, having had the desire of death all his life long, should he repine at that which he has always been pursuing and desiring?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Whence come wars, and fighting, and factions? whence but from the body and the lusts of the body?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Either knowledge is not to be attained at all, or if at all, after death. For then, and not til then, the soul will be in herself alone and without the body.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "In this present life, I reckon that we make the nearest approach to knowledge when we have the least possible concern or interest in the body, and are not saturated with the bodily nature, but remain pure until the hour when God himself is pleased to release us.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "And will he who is a true lover of wisdom, and is persuaded in like manner that only in the world below can he worthily enjoy her, still repine at death? Will he not depart with joy?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "There is a virtue, Simmias, which is named courage. Is not that a special attribute of the philosopher?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The exchange of one fear or pleasure or pain for another fear or pleasure or pain, which are measured like coins, the greater with the less, is not the exchange of virtue.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If the knowledge which we acquired before birth was lost to us at birth, and afterwords by the use of the senses we recovered that which we previously knew, will not that which we call learning be a process of recovering our knowledge, and may not this be rightly termed recollection by us?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Now the compound or composite may be supposed to be naturally capable of being dissolved in like manner as being compounded; but that which is uncompounded, and that only, must be, if anything is, indissoluble.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The soul is in the very likeness of the divine, and immortal, and intelligible, and uniform, and indissoluble, and unchangeable; and the body is in the very likeness of the human, and mortal, and unintelligible, and multiform, and dissoluble, and changeable.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He who is a philosopher or lover of learning, and is entirely pure at departing, is alone permitted to reach the gods.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "As there are misanthropists, or haters of men, there are also misologists or haters of ideas, and both spring from the same cause, which is ignorance of the world.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It may be said, indeed, that without bones and muscles and the other parts of the body I cannot execute my purposes. But to say that I do as I do because of them, and that this is the way in which the mind acts, and not from the choice of the best, is a very careless and idle mode of speaking.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "And thus one man makes a vortex all round and steadies the earth by the heaven; another gives the air as support for the earth, which is sort of a broad trough.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If there is anything beautiful other than absolute beauty, that can only be beautiful as far as it partakes of absolute beauty—and this I should say of everything.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Not that this confusion signifies to them who never care to think about the matter at all, for they have the wit to be well pleased with themselves, however great the turmoil of their ideas.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "What is that the inherence of which, will render the body alive?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If the immortal is also imperishable, the soul when attacked by death cannot perish; for the preceding argument shows that the soul will not admit of death, or even be dead, any more than three or the odd number will admit of the even.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "For after death, as they say, the genius of each individual, to whom he belonged in life, leads him to a certain place in which the dead are gathered together for judgment, whence they go into the world below, following the guide who is appointed to conduct them from this world to the other.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "False words are not only evil in themselves, but they infect the soul with evil.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He who has lived as a true philosopher has reason to be of good cheer when he is about to die, and that after death he may hope to receive the greatest good in the other world.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The being of all virtues, and chiefly of temperance, depends on the practice of them.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "You will know that the divine is so great and of such a nature that it sees and hears everything at once, is present everywhere, and is concerned with everything.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Order and discipline are the most important things in an army, and without them it is impossible to have any other service of the troops than of a confused heap of stones, bricks, timber, and tiles.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It is a disgrace to grow old through sheer carelessness before seeing what manner of man you may become by developing your bodily strength and beauty to their highest limit.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It is the example of the rider who wishes to become an expert horseman: \"None of your soft-mouthed, docile animals for me,\" he says; \"the horse for me to own must show some spirit.\"", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Bad men live that they may eat and drink, whereas good men eat and drink that they may live.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He knew nothing except just the fact of his ignorance.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "How many things I have no need of!", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The man who eats with the greatest appetite has the least need of delicacies.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Those who want fewest things are nearest to the Gods.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "There is only one good, knowledge, and one evil, ignorance.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Contentment is natural wealth; luxury, artificial poverty.", Author = "Socrates" },
        };
    }
}