using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class Socrates
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It would be better for me... that multitudes of men should disagree with me rather than that I, being one, should be out of harmony with myself.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "One should never do wrong in return, nor mistreat any man, no matter how one has been mistreated by him.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Wonder is the feeling of a philosopher, and philosophy begins in wonder.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "I myself know nothing, except just a little, enough to extract an argument from another man who is wise and to receive it fairly.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Each of these private teachers who work for pay ... inculcates nothing else than these opinions of the multitude which they opine when they are assembled and calls this knowledge wisdom.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Anyone who holds a true opinion without understanding is like a blind man on the right road.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "How singular is the thing called pleasure, and how curiously related to pain, which might be thought to be the opposite of it; for they never come to a man together, and yet he who pursues either of them is generally compelled to take the other.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The true disciple of philosophy is likely to be misunderstood by other men; they do not perceive that he is ever pursuing death and dying; and if this is true, why, having had the desire of death all his life long, should he repine at that which he has always been pursuing and desiring?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The body is a source of endless trouble to us by reason of the mere requirement of food; and is also liable to diseases which overtake and impede us in the search after truth: and by filling us so full of loves, and lusts, and fears, and fancies, and idols, and every sort of folly, prevents our ever having, as people say, so much as a thought.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Whence come wars, and fighting, and factions? whence but from the body and the lusts of the body?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Either knowledge is not to be attained at all, or if at all, after death. For then, and not til then, the soul will be in herself alone and without the body.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "In this present life, I reckon that we make the nearest approach to knowledge when we have the least possible concern or interest in the body, and are not saturated with the bodily nature, but remain pure until the hour when God himself is pleased to release us.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "And will he who is a true lover of wisdom, and is persuaded in like manner that only in the world below can he worthily enjoy her, still repine at death? Will he not depart with joy?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "There is a virtue, Simmias, which is named courage. Is not that a special attribute of the philosopher?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The exchange of one fear or pleasure or pain for another fear or pleasure or pain, which are measured like coins, the greater with the less, is not the exchange of virtue.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "I conceive that the founders of the mysteries had a real meaning and were not mere triflers when they intimated in a figure long ago that he who passes unsanctified and uninitiated into the world below will live in a slough, but that he who arrives there after initiation and purification will dwell with the gods.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "I am confident in the belief that there truly is such a thing as living again, and that the living spring from the dead, and that the souls of the dead are in existence, and that the good souls have a better portion than the evil.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If the knowledge which we acquired before birth was lost to us at birth, and afterwords by the use of the senses we recovered that which we previously knew, will not that which we call learning be a process of recovering our knowledge, and may not this be rightly termed recollection by us?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Now the compound or composite may be supposed to be naturally capable of being dissolved in like manner as being compounded; but that which is uncompounded, and that only, must be, if anything is, indissoluble.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The soul is in the very likeness of the divine, and immortal, and intelligible, and uniform, and indissoluble, and unchangeable; and the body is in the very likeness of the human, and mortal, and unintelligible, and multiform, and dissoluble, and changeable.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He who is a philosopher or lover of learning, and is entirely pure at departing, is alone permitted to reach the gods.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "They who have a care of their souls, and do not merely live in the fashions of the body, say farewell to all this; they will not walk in the ways of the blind: and when philosophy offers them purification and release from evil, they feel that they ought not resist her influence, and to her they incline, and whither she leads they follow her.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "As there are misanthropists, or haters of men, there are also misologists or haters of ideas, and both spring from the same cause, which is ignorance of the world.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Nothing is more uncommon than a very large or a very small man; and this applies generally to all extremes, whether of great and small, or swift and slow, or fair and foul, or black and white; and whether the instances you select be man or dogs or anything else, few are the extremes,but many are in the mean between them.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Let us... be careful of admitting into our souls the notion that there is no truth or health or soundness in any arguments at all; but let us rather say that there is as yet no health in us, and that we must quit ourselves like men and do our best to gain health—you and all other men with a view to the whole of your future life, and I myself with a view to death.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It may be said, indeed, that without bones and muscles and the other parts of the body I cannot execute my purposes. But to say that I do as I do because of them, and that this is the way in which the mind acts, and not from the choice of the best, is a very careless and idle mode of speaking.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "And thus one man makes a vortex all round and steadies the earth by the heaven; another gives the air as support for the earth, which is sort of a broad trough.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "I thought that as I had failed in the contemplation of true existence, I ought to be careful that I did not lose the eye of my soul; as people may injure their bodily eye by observing and gazing on the sun during an eclipse, unless they take the precaution of looking at the image reflected in the water, or in some similar medium.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If there is anything beautiful other than absolute beauty, that can only be beautiful as far as it partakes of absolute beauty—and this I should say of everything.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Not that this confusion signifies to them who never care to think about the matter at all, for they have the wit to be well pleased with themselves, however great the turmoil of their ideas.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Absolute greatness will never be great and also small, but that greatness in us or in the concrete will never admit the small or admit of even being exceeded; instead of this, one of two things will happen—either the greater will fly and retire before the opposite, which is the less, or the advance of the less will cease to exist.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "What is that the inherence of which, will render the body alive?", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If the immortal is also imperishable, the soul when attacked by death cannot perish; for the preceding argument shows that the soul will not admit of death, or even be dead, any more than three or the odd number will admit of the even.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "For after death, as they say, the genius of each individual, to whom he belonged in life, leads him to a certain place in which the dead are gathered together for judgment, whence they go into the world below, following the guide who is appointed to conduct them from this world to the other.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The wise and orderly soul is conscious of her situation, and follows in the path; but the soul which desires the body, and which... has long been fluttering about the lifeless frame and the world of sight, is after many struggles and many sufferings hardly and with violence carried away by her attendant genius.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "If any man could arrive at the exterior limit, or take the wings of a bird and fly upward, like a fish who puts his head out and sees the world, he would see a world beyond; and, if the nature of man could sustain this sight, he would acknowledge that this was the place of the true heaven and the true light and the true stars.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Those also who are remarkable for having led holy lives are released from this earthly prison, and go to their pure home which is above, and dwell in the purer earth; and those who have duly purified themselves with philosophy live henceforth altogether without the body, in mansions fairer far than these.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Let a man be of good cheer about his soul, who has cast away the pleasures and ornaments of the body as alien to him, and rather hurtful in their effects, and has followed after the pleasures of knowledge in this life; who has adorned the soul in her own proper jewels, which are temperance, and justice, and courage, and nobility, and truth.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "False words are not only evil in themselves, but they infect the soul with evil.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He who has lived as a true philosopher has reason to be of good cheer when he is about to die, and that after death he may hope to receive the greatest good in the other world.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The being of all virtues, and chiefly of temperance, depends on the practice of them.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "You will know that the divine is so great and of such a nature that it sees and hears everything at once, is present everywhere, and is concerned with everything.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Order and discipline are the most important things in an army, and without them it is impossible to have any other service of the troops than of a confused heap of stones, bricks, timber, and tiles.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It is a disgrace to grow old through sheer carelessness before seeing what manner of man you may become by developing your bodily strength and beauty to their highest limit.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Really, Ischomachus, I am disposed to ask: \"Does teaching consist in putting questions?\"", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "It is the example of the rider who wishes to become an expert horseman: \"None of your soft-mouthed, docile animals for me,\" he says; \"the horse for me to own must show some spirit.\"", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Bad men live that they may eat and drink, whereas good men eat and drink that they may live.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "He knew nothing except just the fact of his ignorance.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "How many things I have no need of!", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "The man who eats with the greatest appetite has the least need of delicacies.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Those who want fewest things are nearest to the Gods.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "There is only one good, knowledge, and one evil, ignorance.", Author = "Socrates" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Socrates", Text = "Contentment is natural wealth; luxury, artificial poverty.", Author = "Socrates" },
        };
    }
}