using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class TheodoreRoosevelt
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Speak softly and carry a big stick; you will go far.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Hit the line hard; don't foul and don't shirk, but hit the line hard!", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "The light has gone out of my life.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "No candid observer will deny that whatever of good there may be in our American civilization is the product of Christianity.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "We cannot afford merely to sit down and deplore the evils of city life as inevitable, when cities are constantly growing, both absolutely and relatively. We must set ourselves vigorously about the task of improving them; and this task is now well begun.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "There is much talk about \"jingoism\". If by \"jingoism\" they mean a policy in pursuance of which Americans will with resolution and common sense insist upon our rights being respected by foreign powers, then we are \"jingoes\".", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "The worst lesson that can be taught a man is to rely upon others and to whine over his sufferings.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "It is both foolish and wicked to teach the average man who is not well off that some wrong or injustice has been done him, and that he should hope for redress elsewhere than in his own industry, honesty and intelligence.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "To sit home, read one's favorite paper, and scoff at the misdeeds of the men who do things is easy, but it is markedly ineffective. It is what evil men count upon the good men's doing.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "To borrow a simile from the football field, we believe that men must play fair, but that there must be no shirking, and that the success can only come to the player who hits the line hard.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "If we lose the virile, manly qualities, and sink into a nation of mere hucksters, putting gain over national honor, and subordinating everything to mere ease of life, then we shall indeed reach a condition worse than that of the ancient civilizations in the years of their decay.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Don't let anyone impose on you. Don't be quarrelsome, but stand up for your rights. If you've got to fight, fight hard and well. To my mind, a coward is the only thing meaner than a liar.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "The government is us; we are the government, you and I.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Death is always and under all circumstances a tragedy, for if it is not, then it means that life itself has become one.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "It is a dreadful thing to come into the Presidency in this way; but it would be far worse to be morbid about it. Here is the task, and I have got to do it to the best of my ability.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "I can be President of the United States, or I can control Alice. I cannot possibly do both.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "I don't pity any man who does hard work worth doing. I admire him. I pity the creature who does not work, at whichever end of the social scale he may regard himself as being.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Let us speak courteously, deal fairly, and keep ourselves armed and ready.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "A man who is good enough to shed his blood for his country is good enough to be given a square deal afterwards. More than that no man is entitled to, and less than that no man shall have.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "It is no use to preach to [children] if you do not act decently yourself.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "There are good men and bad men of all nationalities, creeds and colors; and if this world of ours is ever to become what we hope some day it may become, it must be by the general recognition that the man's heart and soul, the man's worth and actions, determine his standing.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "No man is above the law and no man is below it; nor do we ask any man's permission when we require him to obey it. Obedience to the law is demanded as a right; not asked as a favor.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "The only man who makes no mistakes is the man who never does anything.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "We face the future with our past and our present as guarantors of our promises; and we are content to stand or to fall by the record which we have made and are making.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "This country has nothing to fear from the crooked man who fails. We put him in jail. It is the crooked man who succeeds who is a threat to this country.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Men with the muckrake are often indispensable to the well-being of society, but only if they know when to stop raking the muck, and to look upward to the celestial crown above them. ... If they gradually grow to feel that the whole world is nothing but muck their power of usefulness is gone.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Malefactors of great wealth.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "To waste, to destroy, our natural resources, to skin and exhaust the land instead of using it so as to increase its usefulness, will result in undermining in the days of our children the very prosperity which we ought by right to hand down to them amplified and developed.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Anybody who says saccharin is injurious to health is an idiot.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Far better it is to dare mighty things, to win glorious triumphs, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much, because they live in that grey twilight that knows neither victory nor defeat.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "We cannot avoid meeting great issues. All that we can determine for ourselves is whether we shall meet them well or ill.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "We have a given problem to solve. If we undertake the solution, there is, of course, always danger that we may not solve it aright; but to refuse to undertake the solution simply renders it certain that we cannot possibly solve it aright.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "Throughout our history the success of the homemaker has been but another name for the up-building of the nation.", Author = "Theodore Roosevelt" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Theodore_Roosevelt", Text = "You, the sons of the pioneers, if you are true to your ancestry, must make your lives as worthy as they made theirs. They sought for true success, and therefore they did not seek ease. They knew that success comes only to those who lead the life of endeavor.", Author = "Theodore Roosevelt" },
        };
    }
}