using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class ThomasPaine
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Eloquence may strike the ear, but the language of poverty strikes the heart; the first may charm like music, but the second alarms like a knell.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "When men yield up the privilege of thinking, the last shadow of liberty quits the horizon.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "He who dares not offend cannot be honest.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Silence becomes a kind of crime when it operates as a cover or an encouragement to the guilty.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Where knowledge is a duty, ignorance is a crime.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "War involves in its progress such a train of unforeseen and unsupposed circumstances ... that no human wisdom can calculate the end.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is from the Bible that man has learned cruelty, rapine, and murder; for the belief of a cruel God makes a cruel man.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "We live to improve, or we live in vain", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "If every individual is to indulge his private malignancy or his private ambition, to denounce at random and without any kind of proof, all confidence will be undermined and all authority be destroyed.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "One good schoolmaster is of more use than a hundred priests.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is a want of feeling to talk of priests and bells while so many infants are perishing in the hospitals, and aged and infirm poor in the streets, from the want of necessaries.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Accustom a people to believe that priests or any other class of men can forgive sins, and you will have sins in abundance.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "And the final event to himself has been, that, as he rose like a rocket, he fell like the stick.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Moderation in temper, is always a virtue; but moderation in principle, is a species of vice.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is error only, and not truth, that shrinks from inquiry.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The right of voting for representatives is the primary right by which other rights are protected. To take away this right is to reduce a man to slavery, for slavery consists in being subject to the will of another, and he that has not a vote in the election of representatives is in this case.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is never to be expected in a revolution that every man is to change his opinion at the same moment. There never yet was any truth or any principle so irresistibly obvious that all men believed it at once.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The moral principle of revolutions is to instruct, not to destroy.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is the nature and intention of a constitution to prevent governing by party, by establishing a common principle that shall limit and control the power and impulse of party, and that says to all parties, thus far shalt thou go and no further. But in the absence of a constitution, men look entirely to party; and instead of principle governing party, party governs principle.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "An avidity to punish is always dangerous to liberty. It leads men to stretch, to misinterpret, and to misapply even the best of laws. He that would make his own liberty secure must guard even his enemy from oppression; for if he violates this duty he establishes a precedent that will reach to himself.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Men did not make the earth... It is the value of the improvements only, and not the earth itself, that is individual property... Every proprietor owes to the community a ground rent for the land which he holds.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "I care not how affluent some may be, provided that none be miserable in consequence of it. But it is impossible to enjoy affluence with the felicity it is capable of being enjoyed, while so much misery is mingled in the scene.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "An army of principles will penetrate where an army of soldiers cannot; it will succeed where diplomatic management would fall: it is neither the Rhine, the Channel, nor the ocean that can arrest its progress: it will march on the horizon of the world, and it will conquer.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The Theophilanthropists do not call themselves the disciples of such or such a man. They avail themselves of the wise precepts that have been transmitted by writers of all countries and in all ages.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Religion has two principal enemies, fanaticism and infidelity, or that which is called atheism. The first requires to be combated by reason and morality, the other by natural philosophy.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The universe is the bible of a true Theophilanthropist. It is there that he reads of God.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It must be in something that man could not make, that we must seek evidence for our belief, and that something is the universe; the true bible; the inimitable word, of God.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Search not written or printed books, but the Scripture called the Creation.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The universe is composed of matter, and, as a system, is sustained by motion.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "All the principles of science are of divine origin. Man cannot make, or invent, or contrive principles; he can only discover them, and he ought to look through the discovery to the Author.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Instead of looking through the works of creation to the Creator Himself, they stop short and employ the knowledge they acquire to create doubts of His existence. They labor with studied ingenuity to ascribe everything they behold to innate properties of matter and jump over all the rest by saying that matter is eternal.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "When we speak of looking through nature up to nature's God, we speak philosophically the same rational language as when we speak of looking through human laws up to the power that ordained them. God is the power of first cause, nature is the law, and matter is the subject acted upon.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "In things of this kind it sees something which it calls a natural cause, but none of the causes it sees is the cause of that motion which preserves the solar system.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The atheist who affects to reason, and the fanatic who rejects reason, plunge themselves alike into inextricable difficulties.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The one is a half-rational of whom there is some hope, the other a visionary to whom we must be charitable.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is a Being, whose power is equal to his will.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "We profess, and we proclaim in peace, the pure, unmixed, comfortable, and rational belief of a God, as manifested to us in the universe.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "To God, and not to man, are all men to account for their belief.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "If a man makes the press utter atrocious things he becomes as answerable for them as if he had uttered them by word of mouth.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "I have lived an honest and useful life to mankind; my time has been spend in doing good and I die in perfect composure and resignation to the will of my Creator, God.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "It is the duty of every man, so far as his ability extends, to detect and expose delusion and error.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "That some desperate wretches should be willing to steal and enslave men by violence and murder for gain, is rather lamentable than strange. But that many civilized, nay, christianized people should approve, and be concerned in the savage practice, is surprising.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "So much innocent blood have the Managers and Supporters of this inhuman Trade to answer for to the common Lord of all!", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "None can lawfully buy without evidence that they are not concurring with Men-Stealers; and as the true owner has a right to reclaim his goods that were stolen, and sold; so the slave, who is proper owner of his freedom, has a right to reclaim it, however often sold.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "All distinctions of nations, and privileges of one above others, are ceased; Christians are taught to account all men their neighbours; and love their neighbours as themselves; and do to all men as they would be done by; to do good to all men; and Man-stealing is ranked with enormous crimes.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "Is the barbarous enslaving our inoffensive neighbours, and treating them like wild beasts subdued by force, reconcilable with all these Divine precepts?", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "To go to nations with whom there is no war, who have no way provoked, without farther design of conquest, purely to catch inoffensive people, like wild beasts, for slaves, is an hight of outrage against Humanity and Justice, that seems left by Heathen nations to be practised by pretended Christians.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "As these people are not convicted of forfeiting freedom, they have still a natural, perfect right to it; and the Governments whenever they come should, in justice set them free, and punish those who hold them in slavery.", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "If the slavery of the parents be unjust, much more is their children's; if the parents were justly slaves, yet the children are born free; this is the natural, perfect right of all mankind; they are nothing but a just recompense to those who bring them up:", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "With what consistency, or decency they complain so loudly of attempts to enslave them, while they hold so many hundred thousands in slavery; and annually enslave many thousands more, without any pretence of authority, or claim upon them?", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "The past treatment of Africans must naturally fill them with abhorrence of Christians; lead them to think our religion would make them more inhuman savages, if they embraced it; thus the gain of that trade has been pursued in opposition to the Redeemer's cause, and the happiness of men: Are we not, therefore, bound in duty to him and to them to repair these injuries, as far as possible, by taking some proper measures to instruct, not only the slaves here, but the Africans in their own countries?", Author = "Thomas Paine" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Thomas_Paine", Text = "If we take a survey of ages and of countries, we shall find the women, almost - without exception - at all times and in all places, adored and oppressed. Man, who has never neglected an opportunity of exerting his power, in paying homage to their beauty, has always availed himself of their weakness He has been at once their tyrant and their slave.", Author = "Thomas Paine" },
        };
    }
}