using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class UrsulaKLeGuin
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "We read books to find out who we are.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "If you deny any affinity with another person or kind of person, if you declare it to be wholly different from yourself—as men have done to women, and class has done to class, and nation has done to nation—you may hate it, or deify it, but in either case you have denied its spiritual equality, and its human reality. You have made it into a thing, to which the only possible relationship is a power relationship. And thus you have fatally impoverished your own reality.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The artist deals in what cannot be said in words. The artist whose medium is fiction does this in words.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Distrust everything I say. I am telling the truth.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Great artists make the roads; good teachers and good companions can point them out. But there ain't no free rides, baby.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "We don’t live in order to die, we live in order to live.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "All of us have to learn how to invent our lives, make them up, imagine them. We need to be taught these skills; we need guides to show us how. If we don't, our lives get made up for us by other people.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "To think that realistic fiction is by definition superior to imaginative fiction is to think imitation is superior to invention.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "To leave the reader free to decide what your work means, that’s the real art; it makes the work inexhaustible.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "A writer is a person who cares what words mean, what they say, how they say it. Writers know words are their way towards truth and freedom, and so they use them with care, with thought, with fear, with delight. By using words well they strengthen their souls. Story-tellers and poets spend their lives learning that skill and art of using words well. And their words make the souls of their readers stronger, brighter, deeper.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "the realists of a larger reality.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "We live in capitalism. Its power seems inescapable; so did the divine right of kings.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The name of our beautiful reward is not profit. Its name is freedom.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "it is our pleasant duty ... to encourage that faculty of imagination in our children, to encourage it to grow freely, to flourish like the green bay tree, by giving it the best, absolutely the best and purest, nourishment that it can absorb. And never under any circumstances, to squelch it, or sneer at it, or imply that it is childish, or unmanly, or untrue.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Morning comes whether you set the alarm or not.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "No granite is so hard as hatred and no clay so cold as cruelty.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The trouble is that we have a bad habit, encouraged by pedants and sophisticates, of considering happiness as something rather stupid. Only pain is intellectual, only evil interesting. This is the treason of the artist: a refusal to admit the banality of evil and the terrible boredom of pain.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "As we did without clergy, let us do without soldiers. The joy built upon successful slaughter is not the right kind of joy; it will not do; it is fearful and it is trivial. A boundless and generous contentment, a magnanimous triumph felt not against some outer enemy but in communion with the finest and fairest in the souls of all men everywhere and the splendor of the world’s summer: this is what swells the hearts of the people of Omelas, and the victory they celebrate is that of life.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "What was the good working for freedom all your life and ending up without any freedom at all?", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "One voice, speaking truth is a greater force than fleets and armies, given time; plenty of time.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "When action grows unprofitable, gather information; when information grows unprofitable, sleep.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "We in the Handdara don’t want answers. It’s hard to avoid them, but we try to. To exhibit the perfect uselessness of knowing the answer to the wrong question.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The only thing that makes life possible is permanent, intolerable uncertainty: not knowing what comes next.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "A man wants his virility regarded, a woman wants her femininity appreciated, however indirect and subtle the indications of regard and appreciation. On Winter they will not exist. One is respected and judged only as a human being. It is an appalling experience.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "If civilization has an opposite, it is war.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Elegance is a small price to pay for enlightenment, and I was glad to pay it.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "To oppose something is to maintain it. You must go somewhere else; you must have another goal; then you walk a different road.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "To learn which questions are unanswerable, and not to answer them: this skill is most needful in times of stress and darkness.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "It is not human to be without shame and without desire.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "A man who doesn’t detest a bad government is a fool. And if there were such a thing as a good government on earth, it would be a great joy to serve it.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "What is more arrogant than honesty?", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "It is good to have an end to journey towards; but it is the journey that matters, in the end.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Light is the left hand of darkness and darkness the right hand of light. Two are one, life and death, lying together like lovers in kemmer, like hands joined together, like the end and the way.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "A profound love between two people involves, after all, the power and chance of doing profound hurt.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Wrongs done could not be righted, but at least they were not still being done.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "What are they doing? abruptly becomes, What are we doing? and then, What must I do?", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "What is, is. There is no use pretending, now, that we do not know how to kill one another.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Suffering is dysfunctional, except as a bodily warning against danger. Psychologically and socially it’s merely destructive.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "It is of the nature of idea to be communicated: written, spoken, done. The idea is like grass. It craves light, likes crowds, thrives on crossbreeding, grows better for being stepped on.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "To make a thief, make an owner; to create crime, create laws.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Coercion is the least efficient means of obtaining order.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "People like to do things. They like to do them well. People take the dangerous, hard jobs because they take pride in doing them, they can—egoize, we call it—show off?—to the weaker ones. Hey, look, little boys, see how strong I am! You know? A person likes to do what he is good at doing.... But really, it is the question of ends and means. After all, work is done for the work’s sake. It is the lasting pleasure of life. The private conscience knows that. And also the social conscience, the opinion of one’s neighbors. There is no other reward, on Anarres, no other law. One’s own pleasure, and the respect of one’s fellows. That is all. When that is so, then you see the opinion of the neighbors becomes a very mighty force.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "You can’t crush ideas by suppressing them. You can only crush them by ignoring them. By refusing to think, refusing to change. And that’s precisely what our society is doing!", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "If you can see a thing whole, it's always beautiful. Planets, lives.... But close up, a world’s all dirt and rocks. And day to day, life’s a hard job, you get tired, you lose the pattern. You need distance, interval. The way to see how beautiful the earth is, is to see it as the moon. The way to see how beautiful life is, is from the vantage point of death.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The politician and the physicist both deal with things as they are, with real forces, the basic laws of the world.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The law of evolution is that the strongest survives. Yes, and the strongest, in the existence of any social species, are those who are most social. In human terms, most ethical.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Our model of the cosmos must be as inexhaustible as the cosmos. A complexity that includes not only duration but creation, not only being but becoming, not only geometry but ethics. It is not the answer we are after, but only how to ask the question.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Anarres is all dusty and dry hills. All meager, all dry. And the people aren’t beautiful. They have big hands and feet, like me and the waiter there. But not big bellies. They get very dirty, and take baths together, nobody here does that. The towns are very small and dull, they are dreary. No palaces. Life is dull, and hard work. You can’t always have what you want, or even what you need, because there isn’t enough. You Urrasti have enough. Enough air, enough rain, grass, oceans, food, music, buildings, factories, machines, books, clothes, history. You are rich, you own. We are poor, we lack. You have, we do not have. Everything is beautiful here. Only not the faces. On Anarres nothing is beautiful, nothing but the faces. The other faces, the men and women. We have nothing but that, nothing but each other. Here you see the jewels, there you see the eyes. And in the eyes you see the splendor, the splendor of the human spirit. Because our men and women are free—possessing nothing, they are free. And you the possessors are possessed. You are all in jail. Each alone, solitary, with a heap of what he owns. You live in prison, die in prison. It is all I can see in your eyes—the wall, the wall!", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "A child free from the guilt of ownership and the burden of economic competition will grow up with the will to do what needs doing and the capacity for joy in doing it. It is useless work that darkens the heart. The delight of the nursing mother, of the scholar, of the successful hunter, of the good cook, of the skillful maker, of anyone doing needed work and doing it well—this durable joy is perhaps the deepest source of human affection, and of sociality as a whole.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "There’s a point, around age twenty, when you have to choose whether to be like everybody else the rest of your life, or to make a virtue of your peculiarities.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "It was easy to share when there was enough, even barely enough, to go round. But when there was not enough? Then force entered in; might making right; power, and its tool, violence, and its most devoted ally, the averted eye.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "Existence is its own justification, need is right.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "The individual cannot bargain with the State. The State recognizes no coinage but power: and it issues the coins itself.", Author = "Ursula K. Le Guin" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Ursula_K._Le_Guin", Text = "It is our suffering that brings us together. It is not love. Love does not obey the mind, it turns to hate when forced. The bond that binds us is beyond choice. We are brothers. We are brothers in what we share. In pain, which each of us must suffer alone, in hunger, in poverty, in hope, we know our brotherhood. We know it, because we have been forced to learn it. We know that there is no help for us but from one another, that no hand will save us if we do not reach out our hand. And the hand that you reach out is empty, as mine is. You have nothing. You possess nothing. You own nothing. You are free. All you have is what you are, and what you give.", Author = "Ursula K. Le Guin" },
        };
    }
}