using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class VirginiaWoolf
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "The beauty of the world which is so soon to perish, has two edges, one of laughter, one of anguish, cutting the heart asunder.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Once you begin to take yourself seriously as a leader or as a follower, as a modern or as a conservative, then you become a self-conscious, biting, and scratching little animal whose work is not of the slightest value or importance to anybody.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "It is so difficult to describe any human being. So they say: 'This is what happened'; but they do not say what the person was like to whom it happened.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "An illiterate, underbred book it seems to me; the book of a self-taught working man, and we all know how distressing they are, how egotistic, insistent, raw, striking, and ultimately nauseating. When one can have the cooked flesh, why have the raw?", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "The Reverend C. L. Dodgson had no life. He passed through the world so lightly that he left no print. He melted so passively into Oxford that he is invisible.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "For some reason, we know not what, his childhood was sharply severed. It lodged in him whole and entire. He could not disperse it.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "One cannot grow fine flowers in a thin soil.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Life is a luminous halo, a semi-transparent envelope surrounding us from the beginning of consciousness to the end.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "We are not pleading merely for courage and sincerity; we are suggesting that the proper stuff of fiction is a little other than custom would have us believe it.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Let us record the atoms as they fall upon the mind in the order in which they fall, let us trace the pattern, however disconnected and incoherent in appearance, which each sight or incident scores upon the consciousness.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Theirs, too, is the word-coining genius, as if thought plunged into a sea of words and came up dripping.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "We may enjoy our room in the tower, with the painted walls and the commodious bookcases, but down in the garden there is a man digging who buried his father this morning, and it is he and his like who live the real life and speak the real language.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Humour is the first of the gifts to perish in a foreign tongue.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "A whole lifetime was too short to bring out, the full flavour; to extract every ounce of pleasure, every shade of meaning.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "It was enemies one wanted, not friends.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Rigid, the skeleton of habit alone upholds the human frame.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "The merest schoolgirl when she falls in love, has Shakespeare or Keats to speak her mind for her; but let a sufferer describe a pain in his head to a doctor and language at once runs dry.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "A light here required a shadow there.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "There were the eternal problems: suffering; death; the poor. There was always a woman dying of cancer even here. And yet she had said to all these children, You shall go through with it.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "She had done the usual trick - been nice. She would never know him. He would never know her. Human relations were all like that, she thought, and the worst were between men and women. Inevitably these were extremely insincere.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "For our penitence deserves a glimpse only; our toil respite only.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Mrs Ramsay sat silent. She was glad, Lily thought, to rest in silence, uncommunicative; to rest in the extreme obscurity of human relationships. Who knows what we are, what we feel? Who knows even at the moment of intimacy, This is knowledge?", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "She alone spoke the truth; to her alone could he speak it. That was the source of her everlasting attraction for him, perhaps; she was a person to whom one could say what came into one's head.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "A woman must have money and a room of her own if she is to write fiction.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "No need to hurry. No need to sparkle. No need to be anybody but oneself.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "If truth is not to be found on the shelves of the British Museum, where, I asked myself, picking up a notebook and a pencil, is truth?", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Have you any notion how many books are written about women in the course of one year? Have you any notion how many are written by men? Are you aware that you are, perhaps, the most discussed animal in the universe?", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Women have served all these centuries as looking-glasses possessing the magic and delicious power of reflecting the figure of man at twice its natural size.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "I would venture to guess that Anon, who wrote so many poems without signing them, was often a woman.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Literature is strewn with the wreckage of men who have minded beyond reason the opinions of others.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "The history of men's opposition to women's emancipation is more interesting perhaps than the story of that emancipation itself.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "It is the nature of the artist to mind excessively what is said about him. Literature is strewn with the wreckage of men who have minded beyond reason the opinions of others.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Over the obscure man is poured the merciful suffusion of darkness. None knows where he goes or comes. He may seek the truth and speak it; he alone is free; he alone is truthful, he alone is at peace.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "His form combined in one the strength of a man and a woman's grace.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Some slight haziness there may have been, as if a few dark drops had fallen into the clear pool of memory; certain things had become a little dimmed; but that was all.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "One can only believe entirely, perhaps, in what one cannot see.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Old Madame du Deffand and her friends talked for fifty years without stopping. And of it all, what remains? Perhaps three witty sayings.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Thus, there is much to support the view that it is clothes that wear us and not we them; we may make them take the mould of arm or breast, but they mould our hearts, our brains, our tongues to their liking.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "As long as she thinks of a man, nobody objects to a woman thinking.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "The reign of chaos is over. He has imposed order. Knives cut again.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "We have dined well. The fish, the veal cutlets, the wine have blunted the sharp tooth of egotism. Anxiety is at rest.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Though we see the same world, we see it through different eyes. Any help we can give you must be different from that you can give yourselves, and perhaps the value of that help may lie in the fact of that difference.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Books are the mirrors of the soul.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Once you begin to take yourself seriously as a leader or as a follower, as a modern or as a conservative, then you become a self-conscious, biting, and scratching little animal whose work is not of the slightest value or importance to anybody.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "Lines slip easily down the accustomed grooves. The old designs are copied so glibly that we are half inclined to think them original, save for that very glibness.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "If you do not tell the truth about yourself you cannot tell it about other people.", Author = "Virginia Woolf" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Virginia_Woolf", Text = "That great Cathedral space which was childhood.", Author = "Virginia Woolf" },
        };
    }
}
