using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class Voltaire
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Love truth, but pardon error.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "There are truths which are not for all men, nor for all times.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Opinions have caused more ills than the plague or earthquakes on this little globe of ours.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "If God did not exist, it would be necessary to invent him.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Virtue is debased by self-justification.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "We should be considerate to the living; to the dead we owe only the truth.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "God gave us the gift of life; it is up to us to give ourselves the gift of living well.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Man is free at the instant he wants to be.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "All mortals are equal; it is not their birth, But virtue itself that makes the difference.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Don't think money does everything or you are going to end up doing everything for money.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "One always speaks badly when one has nothing to say.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The ancient Romans built their greatest masterpieces of architecture for wild beasts to fight in.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "If there were only one religion in England there would be danger of despotism, if there were two they would cut each other's throats, but there are thirty, and they live in peace and happiness.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Thus, almost everything is imitation. The most original minds borrowed from one another.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Where there is friendship, there is our natural soil.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "All styles are good except the boring kind.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The superfluous, a very necessary thing.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Every sensible man, every honorable man, must hold the Christian sect in horror.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is the privilege of true genius, and certainly of the genius that opens a new road, to make without punishment great mistakes.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Use, do not abuse; as the wise man commands. I flee Epictetus and Petronius alike. Neither abstinence nor excess ever renders man happy.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The secret of being a bore is to tell everything.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "A single part of physics occupies the lives of many men, and often leaves them dying in uncertainty.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The first who was king was a fortunate soldier: Who serves his country well has no need of ancestors.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Clever tyrants are never punished.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is better to risk sparing a guilty person than to condemn an innocent one.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "To hold a pen is to be at war.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is one of the superstitions of the human mind to have imagined that virginity could be a virtue.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "To pray to God is to flatter oneself that with words one can alter nature.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "We all look for happiness, but without knowing where to find it: like drunkards who look for their house, knowing dimly that they have one.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "If God has made us in his image, we have returned him the favor.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is dangerous to be right in matters where established men are wrong.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "A minister of state is excusable for the harm he does when the helm of government has forced his hand in a storm; but in the calm he is guilty of all the good he does not do.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "A people that sells its own children is more condemnable than the buyer; this commerce demonstrates our superiority; he who gives himself a master was born to have one.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "This body which called itself and which still calls itself the Holy Roman Empire was in no way holy, nor Roman, nor an empire.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "While loving glory so much how can you persist in a plan which will cause you to lose it?", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The husband who decides to surprise his wife is often very much surprised himself.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "When we hear news, we should always wait for the sacrament of confirmation.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "When it is a question of money, everybody is of the same religion.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "There are truths which are not for all men, nor for all times.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Men will always be mad, and those who think they can cure them are the maddest of all.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Whatever you do, crush the infamous thing, and love those who love you.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Superstition is to religion what astrology is to astronomy, the mad daughter of a wise mother. These daughters have too long dominated the earth.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Certainly, whoever is able to make you believe absurdities has the power to make you commit injustices.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Men use thought only to justify their wrongdoings, and speech only to conceal their thoughts.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Doubt is not a pleasant condition, but certainty is an absurd one.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is very strange that men should deny a creator and yet attribute to themselves the power of creating eels.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Where is the prince sufficiently educated to know that for seventeen hundred years the Christian sect has done nothing but harm?", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Religion may be purified. This great work was begun two hundred years ago: but men can only bear light to come in upon them by degrees.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "I always made one prayer to God, a very short one. Here it is: \"O Lord, make our enemies quite ridiculous!\" God granted it.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Indeed, history is nothing more than a tableau of crimes and misfortunes.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "A witty saying proves nothing.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is difficult to free fools from the chains they revere.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Life is bristling with thorns, and I know no other remedy than to cultivate one's garden.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "It is said that God is always on the side of the big battalions.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Thought depends largely on the stomach. In spite of this, those with the best stomachs are not always the best thinkers.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "If God did not exist, it would be necessary to invent him.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "\"If God did not exist, he would have to be invented.\" But all nature cries aloud that he does exist: that there is a supreme intelligence, an immense power, an admirable order, and everything teaches us our own dependence on it.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "All of the other people have committed crimes, the Jews are the only ones who have boasted about committing them.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The best is the enemy of the good.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "I die adoring God, loving my friends, not hating my enemies, and detesting superstition.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Let the punishments of criminals be useful. A hanged man is good for nothing; a man condemned to public works still serves the country, and is a living lesson.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "All philosophical sects have run aground on the reef of moral and physical ill. It only remains for us to confess that God, having acted for the best, had not been able to do better.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Man ought to be content, it is said; but with what?", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Superstition sets the whole world in flames; philosophy quenches them.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "The public is a ferocious beast: one must chain it up or flee from it.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Ancient histories, as one of our wits has said, are but fables that have been agreed upon.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Love is of all the passions the strongest, for it attacks simultaneously the head, the heart, and the body.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "If this is the best of possible worlds, what then are the others?", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Even in those cities which seem to enjoy the blessings of peace, and where the arts flourish, the inhabitants are devoured by envy, cares and anxieties, which are greater plagues than any experienced in a town when it is under siege.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "In every province, the chief occupations, in order of importance, are lovemaking, malicious gossip, and talking nonsense.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Fools have a habit of believing that everything written by a famous author is admirable. For my part I read only to please myself and like only what suits my taste.", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Optimism, What is that? Alas! It is the obstinacy of maintaining that everything is best when it is worst!", Author = "Voltaire" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Voltaire", Text = "Let us cultivate our garden.", Author = "Voltaire" },
        };
    }
}
