using System;

namespace StdbModule;

public static partial class EnglishQuotes
{
    public static class WarrenBuffett
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The stock market is a no-called-strike game. You don't have to swing at everything - you can wait for your pitch.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Love is the greatest advantage a parent can give.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We don't get paid for activity, just for being right. As to how long we'll wait, we'll wait indefinitely.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "There's class warfare, all right, but it's my class, the rich class, that's making war, and we're winning.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I happen to have a talent for allocating capital. But my ability to use that talent is completely dependent on the society I was born into.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I was lucky enough to be born in a time and place where society values my talent, and gave me a good education to develop that talent.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "People will always try to stop you doing the right thing if it is unconventional.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You do whatever the probabilities indicated based on the knowledge that you have at that time, but you are always willing to modify your behaviour or your approach as you get new information.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The asset I most value, aside from health, is interesting, diverse, and long-standing friends.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "All day you wait for the pitch you like; then when the fielders are asleep, you step up and hit it.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You're dealing with a lot of silly people in the marketplace; it's like a great big casino and everyone else is boozing.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Buy into a company because you want to own it, not because you want the stock to go up.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Someone's sitting in the shade today because someone planted a tree a long time ago.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Never count on making a good sale. Have the purchase price be so attractive that even a mediocre sale gives good results.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I like thinking big. I always have. To me it's very simple: if you're going to be thinking anyway, you might as well think big.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You're doing calculations all the time.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Wall Street is the only place that people ride to work in a Rolls Royce to get advice from those who take the subway.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Investors making purchases in an overheated market need to recognize that it may often take an extended period for the value of even an outstanding company to catch up with the price they paid.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We're more comfortable in that kind of business. It means we miss a lot of very big winners.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I wouldn't mind going to jail if I had three cellmates who played bridge.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "In the stock market you do not base your decisions on what the market is doing, but on what you think is rational.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "It's class warfare. My class is winning, but they shouldn't be.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "It takes 20 years to build a reputation and five minutes to ruin it.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You couldn't advance in a finance department in this country unless you taught that the world was flat.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "It's like choosing the 2020 Olympic team by picking the children of all the winners at the 2000 Games.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The least I can do is help pay for all that.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The 400 of us pay a lower part of our income in taxes than our receptionists do, or our cleaning ladies, for that matter.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "If you're in the luckiest 1 percent of humanity, you owe it to the rest of humanity to think about the other 99 percent.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You have to discard improper theories about what the hand had as more evidence comes in sometimes.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You have to be open to a possible change of course if you get new information.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You want to be greedy when others are fearful. You want to be fearful when others are greedy.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "More than 99% of my wealth will go to philanthropy during my lifetime or at death.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Too often, a vast collection of possessions ends up possessing its owner.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The reaction of my family and me to our extraordinary good fortune is not guilt, but rather gratitude.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Keep all we can conceivably need and distribute the rest to society, for its needs.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I could end the deficit in five minutes. You just pass a law that says that any time there's a deficit of more than 3% of GDP, all sitting members of Congress are ineligible for re-election.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The approach and strategies are very similar in that you gather all the information you can and then keep adding to that base of information as things develop.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Anyone who has become rich twice is dumb. Why would you risk what you need and have for what you don't need?", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Criticize by category - praise by name.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The independent directors, in many cases, are the least independent.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Can you really explain to a fish what it's like to walk on land?", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I make no attempt to forecast the general market - my efforts are devoted to finding undervalued securities.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "An irresistible footnote: in 1971, pension fund managers invested a record 122% of net funds available in equities.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The primary test of managerial economic performance is the achievement of a high earnings rate on equity capital employed.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We have tried occasionally to buy toads at bargain prices with results that have been chronicled in past reports.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Managers and investors alike must understand that accounting numbers are the beginning, not the end, of business valuation.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "When returns on capital are ordinary, an earn-more-by-putting-up-more record is no great managerial achievement.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Over the years, Charlie and I have observed many accounting-based frauds of staggering size.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "When we own portions of outstanding businesses with outstanding managements, our favorite holding period is forever.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "After 25 years of buying and supervising a great variety of businesses, Charlie and I have not learned how to solve difficult business problems. What we have learned is to avoid them.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The most common cause of low prices is pessimism - sometimes pervasive, sometimes specific to a company or industry.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Our stay-put behavior reflects our view that the stock market serves as a relocation center at which money is moved from the active to the patient.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We've long felt that the only value of stock forecasters is to make fortune tellers look good.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The strategy we've adopted precludes our following standard diversification dogma.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Just because Charlie and I can clearly see dramatic growth ahead for an industry does not mean we can judge what its profit margins and returns on capital will be.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The sad fact is that most major acquisitions display an egregious imbalance.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Leadership alone provides no certainties: Witness the shocks some years back at General Motors, IBM and Sears.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "In a bull market, one must avoid the error of the preening duck that quacks boastfully after a torrential rainstorm.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Only those who will be sellers of equities in the near future should be happy at seeing stocks rise.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Berkshire's capital base is now simply too large to allow us to earn truly outsized returns.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Intrinsic value can be defined simply: It is the discounted value of the cash that can be taken out of a business during its remaining life.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We will reject interesting opportunities rather than over-leverage our balance sheet.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The line separating investment and speculation, which is never bright and clear, becomes blurred still further when most market participants have recently enjoyed triumphs.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "But a pin lies in wait for every bubble. And when the two eventually meet, a new wave of investors learns some very old lessons.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Speculation is most dangerous when it looks easiest.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "After all, you only find out who is swimming naked when the tide goes out.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Investors should remember that excitement and expenses are their enemies.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Sir Isaac Newton gave us three laws of motion, which were the work of genius. But Sir Isaac's talents didn't extend to investing.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "For investors as a whole, returns decrease as motion increases.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Size seems to make many organizations slow-thinking, resistant to change and smug.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The worst sort of business is one that grows rapidly, requires significant capital to engender the growth, and then earns little or no money.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Price is what you pay; value is what you get.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Keeping them in their homes should be the ambition.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We never want to count on the kindness of strangers in order to meet tomorrow's obligations.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The common intellectual theme of the investors from Graham-Doddsville is this: they search for discrepancies between the value of a business and the price of small pieces of that business in the market.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The investors simply focus on two variables: price and value.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "He knows how to identify securities that sell at considerably less than their value to a private owner. And that's all he does.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "If a business is worth a dollar and I can buy it for 40 cents, something good may happen to me.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The idea of buying dollar bills for 40 cents takes immediately with people or it doesn't take at all.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Very, very few pension funds are managed from a value standpoint.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "These investors are, mentally, always buying the business, not buying the stock.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "All exploit the difference between the market price of a business and its intrinsic value.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I'm convinced that there is much inefficiency in the market.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "When the price of a stock can be influenced by a \"herd\" on Wall Street with prices set at the margin by the most emotional person, or the greediest person, or the most depressed person, it is hard to argue that the market always prices rationally.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "The greater the potential for reward in the value portfolio, the less risk there is.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "This is truly Alice in Wonderland.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I have never been able to figure out why it's riskier to buy $400 million worth of properties for $40 million than for $80 million.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "There seems to be some perverse human characteristic that likes to make easy things difficult.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "There will continue to be wide discrepancies between price and value in the marketplace, and those who read their Graham and Dodd will continue to prosper.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Risk comes from not knowing what you're doing.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "We're going to move a lot of crude (oil) in this country, and we have to learn how to do it very safely.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "You can't make a good deal with a bad person.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "What counts for most people in investing is not how much they know, but rather how realistically they define what they don't know.", Author = "Warren Buffett" },
            new Quote { Id = "https://en.wikiquote.org/wiki/Warren_Buffett", Text = "I insist on a lot of time being spent, almost every day, to just sit and think.", Author = "Warren Buffett" },
        };
    }
}
