using System;
using System.Linq;


namespace StdbModule;
public static partial class GermanQuotes
{
    public static readonly Quote[] Quotes = 
        JohannWolfgangvonGoethe.Quotes
        .Concat(FriedrichSchiller.Quotes)
        .Concat(FriedrichNietzsche.Quotes)
        .Concat(HermannHesse.Quotes)
        .Concat(FranzKafka.Quotes)
        .Concat(ThomasMann.Quotes)
        .Concat(BertoltBrecht.Quotes)
        .Concat(RainerMariaRilke.Quotes)
        .Concat(ArthurSchopenhauer.Quotes)
        .Concat(ImmanuelKant.Quotes)
        .Concat(HeinrichHeine.Quotes)
        .Concat(StefanZweig.Quotes)
        .Concat(HeinrichBöll.Quotes)
        .Concat(GünterGrass.Quotes)
        .Concat(GeorgWilhelmFriedrichHegel.Quotes)
        .Concat(KarlMarx.Quotes)
        .Concat(FriedrichEngels.Quotes)
        .Concat(MartinHeidegger.Quotes)
        .Concat(EdmundHusserl.Quotes)
        .Concat(GottfriedWilhelmLeibniz.Quotes)
        .Concat(GottholdEphraimLessing.Quotes)
        .Concat(TheodorFontane.Quotes)
        .Concat(WilhelmBusch.Quotes)
        .Concat(JosephvonEichendorff.Quotes)
        .Concat(Novalis.Quotes)
        .Concat(ETAHoffmann.Quotes)
        .Concat(GeorgBüchner.Quotes)
        .Concat(HeinrichvonKleist.Quotes)
        .Concat(ClemensBrentano.Quotes)
        .Concat(AnnettevonDrosteHülshoff.Quotes)
        .Concat(EduardMörike.Quotes)
        .Concat(FriedrichRückert.Quotes)
        .Concat(LudwigUhland.Quotes)
        .Concat(FriedrichHölderlin.Quotes)
        .Concat(JeanPaul.Quotes)
        .Concat(MatthiasClaudius.Quotes)
        .Concat(ChristianMorgenstern.Quotes)
        .Concat(HugovonHofmannsthal.Quotes)
        .Concat(StefanGeorge.Quotes)
        .Concat(ElseLaskerSchüler.Quotes)
        .Concat(GeorgTrakl.Quotes)
        .Concat(GottfriedBenn.Quotes)
        .Concat(PaulCelan.Quotes)
        .Concat(NellySachs.Quotes)
        .Concat(IngeborgBachmann.Quotes)
        .Concat(MaxFrisch.Quotes)
        .Concat(FriedrichDürrenmatt.Quotes)
        .Concat(RobertMusil.Quotes)
        .Concat(AlfredDöblin.Quotes)
        .Concat(LionFeuchtwanger.Quotes)
        .Concat(ErichMariaRemarque.Quotes)
        .Concat(ChristaWolf.Quotes)
        .Concat(HeinerMüller.Quotes)
        .Concat(PeterHandke.Quotes)
        .Concat(PatrickSüskind.Quotes)
        .Concat(BernhardSchlink.Quotes)
        .Concat(DanielKehlmann.Quotes)
        .Concat(ArthurSchnitzler.Quotes)
        .Concat(KarlKraus.Quotes)
        .Concat(EliasCanetti.Quotes)
        .Concat(JosephRoth.Quotes)
        .Concat(FranzWerfel.Quotes)
        .Concat(MartinBuber.Quotes)
        .Concat(WalterBenjamin.Quotes)
        .Concat(MaxHorkheimer.Quotes)
        .Concat(HerbertMarcuse.Quotes)
        .Concat(JürgenHabermas.Quotes)
        .Concat(HannahArendt.Quotes)
        .ToArray();
}