using System;
using System.Linq;


namespace StdbModule;
public static partial class ItalianQuotes
{
    public static readonly Quote[] Quotes = 
        DanteAlighieri.Quotes
        .Concat(ItaloCalvino.Quotes)
        .Concat(UmbertoEco.Quotes)
        .Concat(LeonardodaVinci.Quotes)
        .Concat(GiuseppeVerdi.Quotes)
        .Concat(AlessandroManzoni.Quotes)
        .Concat(GiacomoLeopardi.Quotes)
        .Concat(LuigiPirandello.Quotes)
        .Concat(PrimoLevi.Quotes)
        .Concat(GiovanniBoccaccio.Quotes)
        .Concat(FrancescoPetrarca.Quotes)
        .Concat(EugenioMontale.Quotes)
        .Concat(GiuseppeUngaretti.Quotes)
        .Concat(LudovicoAriosto.Quotes)
        .Concat(TorquatoTasso.Quotes)
        .Concat(CarloGoldoni.Quotes)
        .Concat(VittorioAlfieri.Quotes)
        .Concat(UgoFoscolo.Quotes)
        .Concat(GiosuèCarducci.Quotes)
        .Concat(GiovanniPascoli.Quotes)
        .Concat(GabrieleDAnnunzio.Quotes)
        .Concat(SalvatoreQuasimodo.Quotes)
        .Concat(CesarePavese.Quotes)
        .Concat(ElsaMorante.Quotes)
        .Concat(AlbertoMoravia.Quotes)
        .Concat(DinoBuzzati.Quotes)
        .Concat(CarloEmilioGadda.Quotes)
        .Concat(LeonardoSciascia.Quotes)
        .Concat(NataliaGinzburg.Quotes)
        .Concat(IgnazioSilone.Quotes)
        .Concat(VitalianoBrancati.Quotes)
        .Concat(GiuseppeTomasidiLampedusa.Quotes)
        .Concat(GiorgioBassani.Quotes)
        .Concat(AntonioTabucchi.Quotes)
        .Concat(PierPaoloPasolini.Quotes)
        .Concat(ItaloSvevo.Quotes)
        .Concat(GraziaDeledda.Quotes)
        .Concat(LuigiCapuana.Quotes)
        .Concat(GiovanniVerga.Quotes)
        .Concat(EdmondoDeAmicis.Quotes)
        .Concat(CarloCollodi.Quotes)
        .Concat(GianniRodari.Quotes)
        .Concat(GiuseppeMazzini.Quotes)
        .Concat(CamilloBensodiCavour.Quotes)
        .Concat(GiuseppeGaribaldi.Quotes)
        .Concat(BenedettoCroce.Quotes)
        .Concat(AntonioGramsci.Quotes)
        .Concat(GiordanoBruno.Quotes)
        .Concat(TommasoCampanella.Quotes)
        .Concat(GiambattistaVico.Quotes)
        .ToArray();
}