using System;

public struct Quote
{
    public string Id;
    public string Text;
    public string Author;
}

public static class PortugueseQuotes
{
    public static readonly Quote[] Quotes = new Quote[]
    {
        new Quote { Id = "https://pt.wikiquote.org/wiki/Nadine_Gordimer", Text = "A poesia é ao mesmo tempo um esconderijo e um altofalante.", Author = "Nadine Gordimer" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Thomas_P._Gore", Text = "Ele tem todas as características do cão - menos a lealdade.", Author = "Thomas P. Gore" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Dan%C3%A7a", Text = "A poesia é um eco convidando uma sombra para dançar.", Author = "Dança" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Serafim_de_Sarov", Text = "Adquira um espírito de paz, e milhares à sua volta serão salvos.", Author = "Serafim de Sarov" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Matthieu_Roug%C3%A9", Text = "Trinta pessoas é muito pouco numa grande catedral e é gente demais numa pequena capela.", Author = "Matthieu Rougé" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Carlo_Bini", Text = "A política é o governo da opinião", Author = "Carlo Bini" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/William_Slim%2C_1.%C2%BA_Visconde_Slim", Text = "Não há maus regimentos, há apenas maus oficiais.", Author = "William Slim, 1.º Visconde Slim" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Irving_Chernev", Text = "Cada mestre de xadrez, já foi um novato.", Author = "Irving Chernev" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Kazimierz_%C5%9Awi%C4%85tek", Text = "Felizmente, sou um lutador, porque para a reconstrução da Igreja será preciso sê-lo.", Author = "Kazimierz Świątek" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Lin_Yutang", Text = "A vida social só pode existir na base de uma certa dose de mentiras refinadas e de que ninguém diga exatamente o que pensa.", Author = "Lin Yutang" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Bob_Saget", Text = "Inteligência afiada, esperta, gentil, hilária, sincera e tão cheia de amor.", Author = "Bob Saget" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Jes%C3%BAs_Murgui_Soriano", Text = "Quando os pobres e os mais fracos estejam no centro de nosso pensamento se gerará uma mudança na sociedade.", Author = "Jesús Murgui Soriano" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Gabriel_Narciso_Escobar_Ayala", Text = "Uma característica do povo paraguaio é resistir e sofrer, mas não se pode mais tolerar esta situação, as pessoas desta parte do país merecem uma vida melhor.", Author = "Gabriel Narciso Escobar Ayala" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/C%C3%A9lestin_Freinet", Text = "A democracia de amanhã se prepara na democracia da escola.", Author = "Célestin Freinet" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Efraim_Sneh", Text = "Ficaremos por cima porque somos mais fortes.", Author = "Efraim Sneh" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Cl%C3%A1udia_Alencar", Text = "De que adianta a minha fama se eu não puder deixar alguma coisa para a eternidade?", Author = "Cláudia Alencar" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Romain_Rolland", Text = "Quando a ordem é injusta, a desordem é já um princípio de justiça.", Author = "Romain Rolland" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Semana", Text = "Em todo casamento que durou mais de uma semana existem motivos para o divórcio. A chave consiste em encontrar sempre motivos para o casamento.", Author = "Semana" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Julio_Mar%C3%ADa_Sanguinetti", Text = "Todo político em busca da reeleição é um animal perigoso.", Author = "Julio María Sanguinetti" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Alexandre_Pushkin", Text = "Genialidade e maldade não combinam.", Author = "Alexandre Pushkin" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Conforto", Text = "Quase sempre preferimos o conforto da opinião sem o desconforto da reflexão.", Author = "Conforto" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/John_Churton_Collins", Text = "Na prosperidade, nossos amigos nos conhecem; na adversidade, nós conhecemos nossos amigos.", Author = "John Churton Collins" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Clarice_Lispector", Text = "Suponho que me entender não é uma questão de inteligência e sim de sentir, de entrar em contato. Ou toca, ou não toca!", Author = "Clarice Lispector" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Reinhard_Marx", Text = "O mundo perfeito não chegará nunca. Isso um bispo sabe muito bem.", Author = "Reinhard Marx" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Fran%C3%A7oise_Giroud", Text = "Creio que a felicidade existe. A prova está em que, de repente, ela não existe mais.", Author = "Françoise Giroud" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Intelig%C3%AAncia", Text = "É belo modelar uma estátua e dar-lhe vida, mas é sublime modelar uma inteligência e dar-lhe liberdade.", Author = "Inteligência" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/%C3%89douard_Rod", Text = "No fundo de cada alma há tesouros escondidos que somente o amor permite descobrir.", Author = "Édouard Rod" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Peter_Loy_Chong", Text = "Não queremos uma teocracia, jamais dissemos que gostaríamos de um Estado cristão. Todavia, estamos preocupados se um Estado laico reduzir a fé a um fato puramente individual.", Author = "Peter Loy Chong" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ettore_Balestrero", Text = "A paz é um desafio e uma necessidade para todos, principalmente nas regiões aonde se sofre mais.", Author = "Ettore Balestrero" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Tomie_Ohtake", Text = "Não gosto de coisas pequenas, nem de pintar com a ponta dos dedos. Uso o corpo todo", Author = "Tomie Ohtake" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ada_Rogato", Text = "Eu não viajo por Turismo. O Brasil é muito grande. E um país muito especial. Eu quero divulgar esse país para o mundo todo!", Author = "Ada Rogato" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Lily_Safra", Text = "Um dia depois de chorar de tristeza pela Notre-Dame, choramos de inveja dos franceses.", Author = "Lily Safra" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Tugdual_Derville", Text = "O feminismo benéfico não se trata de obscurecer os marcadores corporais que distinguem homens de mulheres, mas de garantir que essas diferenças não sejam uma fonte de discriminação injusta.", Author = "Tugdual Derville" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Henry_John_Kaiser", Text = "Os problemas são apenas oportunidades com roupas de trabalho.", Author = "Henry John Kaiser" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/M._R._James", Text = "Eu ouvi um grito durante a noite e ouvi um riso depois. Se eu não puder esquecer isso, não poderei dormir novamente.", Author = "M. R. James" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Massimo_d%27Azeglio", Text = "A vaidade quer aplauso.", Author = "Massimo d'Azeglio" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Alejandro_Gonz%C3%A1lez_I%C3%B1%C3%A1rritu", Text = "Os governos não fazem mais parte da corrupção. O Estado é a corrupção.", Author = "Alejandro González Iñárritu" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Claudia_Leitte", Text = "Ostentação não tem nada a ver comigo. É até burrice num país com tanta gente pobre.", Author = "Claudia Leitte" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Gabriel_Bernardo_Barba", Text = "Como Igreja, continuemos em comunhão, rezando pela paz e construindo-a.", Author = "Gabriel Bernardo Barba" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Maria_Casadevall", Text = "Eu sempre tive um mundo subjetivo, uma imaginação muito presente. Meu mundo interior sempre foi muito fértil, muito criativo. A primeira forma que eu encontrei de transcrever a minha subjetividade foi através da escrita.", Author = "Maria Casadevall" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Giovanni_Angelo_Becciu", Text = "Não precisa confundir a fidelidade à doutrina com ideologia de quem não quer mudar nunca. Não somos fechados em um sistema de verdades cristalizadas, mas somos, ao invés disto, um organismo vivo.", Author = "Giovanni Angelo Becciu" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Thomas_Dabre", Text = "As diferenças podem levar a experiências belíssimas. Todavia, mesmo se celebramos a diversidade, devemos guardar-nos de quem diz que o relativismo é, por sua vez, ecletismo e sincretismo. Pelo contrário, devemos reconhecer as nossas diferenças e aprender a conviver com elas.", Author = "Thomas Dabre" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Nilton_Santos", Text = "Nilton exercia, com perfeição, todas as artes do jogo. Driblava bem, passava melhor ainda. Jamais foi traído pelo ‘quique’ de uma bola", Author = "Nilton Santos" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Borboleta", Text = "É preciso que eu suporte duas ou três larvas se quiser conhecer as borboletas.", Author = "Borboleta" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Hes%C3%ADodo", Text = "Qualquer um que prejudica os outros, faz mal a si", Author = "Hesíodo" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Frank_Rudolph_Wolf", Text = "Inúmeras vezes estes problemas são postos de lado, em prejuízo dos amantes da liberdade de todo o mundo.", Author = "Frank Rudolph Wolf" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/William_Cowper", Text = "Ter uma vida tranqüila é um objetivo díficil.", Author = "William Cowper" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Caio_Blat", Text = "Acham que é caridade, mas nós é que recebemos uma doação de carinho", Author = "Caio Blat" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Lygia_Clark", Text = "O erótico vivido como profano e a arte vivida como sagrada se fundem numa experiência única. Trata-se de misturar arte com vida.", Author = "Lygia Clark" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Marqu%C3%AAs_de_Vauvenargues", Text = "O ódio dos fracos não é tão perigoso quanto a sua amizade.", Author = "Marquês de Vauvenargues" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Charles_Beard", Text = "Quando está escuro o suficiente, você pode ver as estrelas.", Author = "Charles Beard" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/James_Mackintosh", Text = "Difunda conhecimento para imortalizar-se", Author = "James Mackintosh" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Emmanuel_%28Chico_Xavier%29", Text = "A felicidade não entra em portas trancadas.", Author = "Emmanuel (Chico Xavier)" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Luigi_Amaducci", Text = "Vossa Excelência guia com zelo e sabedoria.", Author = "Luigi Amaducci" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Frank_Burgess", Text = "Para apreciar o 'nonsense' é necessário interesse sério pela vida.", Author = "Frank Burgess" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Marcelo_D2", Text = "Se maconha já me causou perda de memória? Não que eu me lembre...", Author = "Marcelo D2" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Luciana_Mello", Text = "Já me chamaram pra ser modelo, mas esse negócio de ficar comendo alface não é comigo.", Author = "Luciana Mello" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Dina_Esther_Rezinovsky", Text = "Essas práticas nos levam a tempos sombrios de nossa história que não devemos permitir que se repitam.", Author = "Dina Esther Rezinovsky" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Katharine_Whitehorn", Text = "Do ponto de vista comercial, se o Natal não existisse seria preciso inventá-lo.", Author = "Katharine Whitehorn" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/N%C3%ADvea_Stelmann", Text = "Dinheiro nenhum paga essa vulgaridade.", Author = "Nívea Stelmann" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Filinto_M%C3%BCller", Text = "Fico com a responsabilidade. Não a atiro nem para cima nem para baixo.", Author = "Filinto Müller" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/John_Archibald_Wheeler", Text = "Algumas pessoas pensam que Wheeler ficou louco em seus últimos anos, mas ele sempre foi louco.", Author = "John Archibald Wheeler" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Edmundo_Ponziano_Valenzuela_Mellid", Text = "A violência gera mais violência, não leva a nada além disto. Rechaçamos categoricamente tudo o que ocorreu. O país se constrói com a misericórdia, com o amor, o trabalho, o diálogo. A violência não levantará o país, mas o afundará.", Author = "Edmundo Ponziano Valenzuela Mellid" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Franklin_D._Roosevelt", Text = "A felicidade não está em possuir mais dinheiro, mas na alegria de conseguir o almejado, na excitação do esforço criativo.", Author = "Franklin D. Roosevelt" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Horace_Walpole", Text = "O mundo é uma comédia para os que pensam e uma tragédia para os que sentem.", Author = "Horace Walpole" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Sexto_Prop%C3%A9rcio", Text = "Evita desprezar meus cantos com orgulho: / O Amor tardio cobra imensos juros.", Author = "Sexto Propércio" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Isaac_Rosenberg", Text = "Eu nunca entrei para o exército por razões patrióticas.", Author = "Isaac Rosenberg" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Aung_San_Suu_Kyi", Text = "A única prisão real é o medo e a única liberdade real é a liberdade de não ter medo.", Author = "Aung San Suu Kyi" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/James_Connolly", Text = "O Governo britânico não tem qualquer direito na Irlanda, nunca teve qualquer direito na Irlanda e nunca pode ter qualquer direito na Irlanda.", Author = "James Connolly" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Alain-Fournier", Text = "A aproximação é sempre mais bela que a chegada, o desejo que a posse.", Author = "Alain-Fournier" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Dhiloraj_Ranjit_Canagasabey", Text = "A liberdade de pensamento, consciência, religião e associação deveria ser uma prerrogativa de todas as comunidades religiosas. Esperamos a proteção do Estado de Direito.", Author = "Dhiloraj Ranjit Canagasabey" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Gritos_de_torcidas", Text = "Sou brasileiro, com muito orgulho, com muito amor. ~ Torcida brasileira", Author = "Gritos de torcidas" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Sombra", Text = "Muita luz é como muita sombra: não deixa ver.", Author = "Sombra" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ulysses_S._Grant", Text = "Apesar de um soldado por profissão, nunca senti qualquer tipo de gosto para a guerra, e eu nunca a defendi, exceto como meio de paz.", Author = "Ulysses S. Grant" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Tom%C3%A1s_de_Kempis", Text = "Quem não evita as pequenas faltas, pouco a pouco cai nas grandes.", Author = "Tomás de Kempis" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Gustavo_Noboa", Text = "Eu sou como os alcoólicos anônimos: vivo um dia de cada vez.", Author = "Gustavo Noboa" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/F%C3%A9lix_Lope_de_Vega", Text = "A harmonia é puro amor, pois amor é total concordância.", Author = "Félix Lope de Vega" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Betty_Faria", Text = "Assumir a idade é um compromisso com mulheres da minha geração.", Author = "Betty Faria" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ruben_Rosa", Text = "Não é o Tribunal, é a lei.", Author = "Ruben Rosa" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Brewster_Kahle", Text = "Precisamos de pôr o que temos de melhor ao alcance das nossas crianças. Se não o fizermos, a próxima geração será aquela que merecemos Vão aprender com aquilo que tiverem à sua volta.", Author = "Brewster Kahle" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Joseph_Fort_Newton", Text = "Crença é uma verdade aceita por sua mente. Fé é o fogo mantido em seu coração.", Author = "Joseph Fort Newton" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Cec%C3%ADlia_Meireles", Text = "Meus companheiros amados, não vos espero nem chamo: porque vou para outros lados", Author = "Cecília Meireles" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Emo%C3%A7%C3%A3o", Text = "O rosto é o palco onde vivem as emoções humanas.", Author = "Emoção" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Henri_Wallon_%28psic%C3%B3logo%29", Text = "Reprovar é sinônimo de expulsar, negar, excluir. É a própria negação do ensino", Author = "Henri Wallon (psicólogo)" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Gerard_Paul_Bergie", Text = "O tabernáculo pode ser substituído. É o conteúdo o que é tão precioso para nós. Isso é insubstituível.", Author = "Gerard Paul Bergie" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Rollo_May", Text = "Sem coragem o nosso amor empalidece em mera dependência.", Author = "Rollo May" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/C%C3%A9sar_Guerra-Peixe", Text = "Não imponho aos meus alunos nenhuma orientação. Discuto a parte da composição, mas a parte filosófica deixo com eles.", Author = "César Guerra-Peixe" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Henry_Brooks_Adams", Text = "Amizades nascem, não são feitas.", Author = "Henry Brooks Adams" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Jean-Pierre_Delville", Text = "Deus preenche as lacunas do nosso amor e nos impele mais longe do que pensamos que somos capazes.", Author = "Jean-Pierre Delville" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ang%C3%A9lique_Namaika", Text = "Se eu conseguir ajudar apenas uma mulher, já será um sucesso. Peço a Deus que me mantenha uma pessoa simples e que possa continuar ajudando essas mulheres.", Author = "Angélique Namaika" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/S%C3%A9rgio_Mamberti", Text = "São filhos com açúcar.", Author = "Sérgio Mamberti" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Francisco_Lima_Soares", Text = "Mais tarde, poderá ser tarde demais.", Author = "Francisco Lima Soares" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/John_McCrae", Text = "Nos campos de Flandres sopram as papoilas.", Author = "John McCrae" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Henry_James_Byron", Text = "A vida é curta demais para o xadrez.", Author = "Henry James Byron" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Luis_Pascual_Dri", Text = "A primeira coisa é reconhecer que sou tão pecador quanto aquele que se aproxima de mim.", Author = "Luis Pascual Dri" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Daphne_du_Maurier", Text = "A felicidade não é uma posse a ser valorizada, é uma qualidade de pensamento, um estado de espírito.", Author = "Daphne du Maurier" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Geraldo_Majella_Agnelo", Text = "Falar sobre os jovens é fácil. Difícil é deixar que eles falem. Se eles tivessem mais compreensão por parte dos adultos, com certeza a humanidade seria mais feliz .", Author = "Geraldo Majella Agnelo" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Ion_Mihai_Pacepa", Text = "Da intuição aos fatos, entretanto, há um longo caminho.", Author = "Ion Mihai Pacepa" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Marcel_Jouhandeau", Text = "É-se sempre mais religioso do que aquilo que se pensa.", Author = "Marcel Jouhandeau" },
        new Quote { Id = "https://pt.wikiquote.org/wiki/Miguel_%C3%81ngel_Ayuso_Guixot", Text = "Na realidade, o diálogo é uma necessidade, não uma opção.", Author = "Miguel Ángel Ayuso Guixot" }
    };
}