using System;
using System.Linq;


namespace StdbModule;
public static partial class SpanishQuotes
{
    public static readonly Quote[] Quotes = 
        GabrielGarcíaMárquez.Quotes
        .Concat(PabloNeruda.Quotes)
        .Concat(JorgeLuisBorges.Quotes)
        .Concat(MigueldeCervantes.Quotes)
        .Concat(FedericoGarcíaLorca.Quotes)
        .Concat(OctavioPaz.Quotes)
        .Concat(IsabelAllende.Quotes)
        .Concat(MarioVargasLlosa.Quotes)
        .Concat(AntonioMachado.Quotes)
        .Concat(MigueldeUnamuno.Quotes)
        .Concat(RubénDarío.Quotes)
        .Concat(GabrielaMistral.Quotes)
        .Concat(CésarVallejo.Quotes)
        .Concat(JuanRamónJiménez.Quotes)
        .Concat(RafaelAlberti.Quotes)
        .Concat(VicenteAleixandre.Quotes)
        .Concat(CamiloJoséCela.Quotes)
        .Concat(BenitoPérezGaldós.Quotes)
        .Concat(RosalíadeCastro.Quotes)
        .Concat(GustavoAdolfoBécquer.Quotes)
        .Concat(LopedeVega.Quotes)
        .Concat(FranciscodeQuevedo.Quotes)
        .Concat(LuisdeGóngora.Quotes)
        .Concat(TirsodeMolina.Quotes)
        .Concat(JorgeManrique.Quotes)
        .Concat(GarcilasodelaVega.Quotes)
        .Concat(VicenteBlascoIbáñez.Quotes)
        .Concat(PíoBaroja.Quotes)
        .Concat(Azorín.Quotes)
        .Concat(RamónMaríadelValleInclán.Quotes)
        .Concat(JacintoBenavente.Quotes)
        .Concat(MarianoJosédeLarra.Quotes)
        .Concat(EmiliaPardoBazán.Quotes)
        .Concat(JuanValera.Quotes)
        .Concat(JoséMartí.Quotes)
        .Concat(SimónBolívar.Quotes)
        .Concat(JosédeSanMartín.Quotes)
        .Concat(AndrésBello.Quotes)
        .Concat(DomingoFaustinoSarmiento.Quotes)
        .Concat(JoséHernández.Quotes)
        .Concat(HoracioQuiroga.Quotes)
        .Concat(JulioCortázar.Quotes)
        .Concat(AdolfoBioyCasares.Quotes)
        .Concat(SilvinaOcampo.Quotes)
        .Concat(ErnestoSabato.Quotes)
        .Concat(RobertoArlt.Quotes)
        .Concat(JuanCarlosOnetti.Quotes)
        .Concat(AlejoCarpentier.Quotes)
        .Concat(JoséLezamaLima.Quotes)
        .Concat(GuillermoCabreraInfante.Quotes)
        .Concat(MiguelÁngelAsturias.Quotes)
        .Concat(AugustoRoaBastos.Quotes)
        .Concat(JuanRulfo.Quotes)
        .Concat(CarlosFuentes.Quotes)
        .Concat(ElenaPoniatowska.Quotes)
        .Concat(RosarioCastellanos.Quotes)
        .Concat(AlfonsoReyes.Quotes)
        .Concat(JoséEmilioPacheco.Quotes)
        .Concat(ErnestoCardenal.Quotes)
        .Concat(ClaribelAlegría.Quotes)
        .ToArray();
}