using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class CzesławMiłosz
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Aż wszystko będzie legendą I wtedy po wielu latach Na nowym Campo di Fiori Bunt wznieci słowo poety.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Bo nadmiar światła umniejsza istnienie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "O tym, kto kim jest, nie decyduje pieniądz.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Żadnej miłości nie trzeba przeciągać poza jej kres.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Który skrzywdziłeś człowieka prostego Śmiechem nad krzywdą jego wybuchając, Gromadę błaznów koło siebie mając Na pomieszanie dobrego i złego.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Lepszy dla ciebie byłby świt zimowy I sznur i gałąź pod ciężarem zgięta.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Nie bądź bezpieczny – poeta pamięta Możesz go zabić – narodzi się nowy Spisane będą czyny i rozmowy…", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Wierzę, że Matka Boska ukazała się w Lourdes i Fatima. Ale o wiele trudniej jest wierzyć w rządy Pana Boga nad światem.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Zawsze mamy nadzieję, że jakoś to się ułoży, bo inni są lepsi od nas.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Dwa ocalone wyrazy: Prawda i sprawiedliwość.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Szaleństwo tak żyć bez uśmiechu I dwa powtarzać wyrazy Zwrócone do was, umarli, Do was, których udziałem Miało być wesele", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Definicje wolności są różne. Jedna z nich głosi, że wolność jest to możliwość picia nieograniczonej ilości wódki.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Łączność z siłami, które są, choć nie da się ich nazwać, wymaga gestów symbolicznych.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Pamiętnik: ta część naszego życia, którą możemy opowiedzieć nie rumieniąc się.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Czym jest poezja, która nie ocala Narodów ani ludzi? Wspólnictwem urzędowych kłamstw, Piosenką pijaków, którym za chwilę ktoś poderżnie gardła, Czytanką z panieńskiego pokoju.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Ty, którego nie mogłem ocalić, Wysłuchaj mnie. Zrozum tę mowę prostą, bo wstydzę się innej. Przysięgam, nie ma we mnie czarodziejstwa słów. Mówię do ciebie milcząc, jak obłok czy drzewo.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Nie jesteś jednak tak bezwolny, A choćbyś był jak kamień polny, Lawina bieg od tego zmienia, Po jakich toczy się kamieniach.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Pośród żarcików, anegdotek, Szlachecki wspominając miodek, Chyli się Polska w trudne czasy Przed bóstwem wódki i kiełbasy.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Żywot grabarza jest wesoły. Grzebie systemy, wiary, szkoły.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Donosicielstwo było i jest znane w różnych cywilizacjach. Na ogół jednak nie było nigdy podnoszone do godności cnoty. W cywilizacji Nowej wiary jest zalecane jako cnota podstawowa dobrego obywatela.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "A więc pamiętaj – w trudną porę marzeń masz być ambasadorem.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Bić, bo Żyd. Chwalić, bo Wyspiański. Zrozumieć prawdę współczesności i przestraszyć się – to już za trudny kunszt.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Bo więcej waży jedna dobra strofa, niż Ciężar wielu pracowitych stronic", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Być może nową erę ludzkości otwierają nie bronie atomowe i podróże międzyplanetarne, ale ''psychedelic drugs'' jako zapowiedź masowych, demokratycznych środków przeciwko nudzie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Cudowność. Być człowiekiem i żyć wśród ludzi to przecież cudowne, nawet jeżeli znamy podłości i zbrodnie, do jakich są zdolni.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Czemuż więc zapytujesz mnie o wiersze dawne I o minionych dziewczyn cudaczne imiona? Niech wiersze moje drogą jaką kto chce chodzą, Niechaj moje dziewczyny innym dzieci rodzą.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Człowiek rodzi się, nosi krótkie majtki, czyta o Indianach, później o odległych epokach trucizny, miecza, przetargów i intryg, nie wiedząc, jakie gorycze gotuje mu jego stulecie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Dużo śpię i czytam Tomasza z Akwinu Albo „Śmierć Boga” (takie protestanckie dzieło).", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Dziecko, które w nas mieszka, ufa, że istnieją gdzieś mędrcy znający prawdę.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Dzień taki szczęśliwy, Mgła opadła wcześnie, pracowałem w ogrodzie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Epika. Przebici włócznią, kiedy kucali za własną potrzebą.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Gdybym nie ufał słowu Boga mego Za cóż ufają ludzie słowom ludzi? Może nie świętych, ale nikczemnego Swoją miłością do chwały przebudzi I proch połączy niepojęta siłą Aby co skryte wyjawione było.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Głupcy są zdania, że kiedy poświęcą Pamięć przeszłości, będą żyć szczęśliwi.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Gwiazdo, chroń nas – od szczęścia i spokoju.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jak mogłem robić takie rzeczy żyjąc w tym strasznym świecie podlegając jego prawom igrając z jego prawami. Potrzebuję Boga, żeby mi przebaczył potrzebuję Boga miłosiernego.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jakakolwiek jest boleść, będzie więcej boleści. Noc jest czarna, ale bedzie czarniejsza. Dobrze takim co żyli ale w porę odeszli. Ty więc nie bierz spraw ludzkich do serca.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jest taka cierpienia granica, za którą się uśmiech pogodny zaczyna, i mija tak człowiek, i już zapomina, o co miał walczyć i po co.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jestem przeciw!", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jeżeli Boga nie ma, To nie wszystko człowiekowi wolno. Jest stróżem brata swego i nie wolno mu brata swego zasmucać, opowiadając, że Boga nie ma.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jeżeli jestem żołnierzem, ty jesteś skrzydłem na hełmie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Jeżeli nie rozerwiesz swoich pęt za życia, jaka nadzieja wyzwolenia w śmierci?", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Kiedy księżyc i spacerują kobiety w kwiaciastych sukniach Zdumiewają mnie ich oczy, rzęsy i całe urządzenie świata.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Kiedy nie mogłem bez alkoholu, jechałem na alkoholu. Kiedy nie mogłem bez papierosów i kawy, jechałem na papierosach i kawie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Kochałem ją, nie wiedząc kim była naprawdę. Zadawałem jej ból, goniąc za moją ułudą. Zdradzałem ją z kobietami, jej jednej wierny.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Masowa zagłada nie dosięga naszej wyobraźni, jest to po prostu za dużo.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Mieli rację katarzy: unikać grzechu poczęcia (Bo albo zabijesz płód i dręczyć będzie sumienie, Albo za żywot cierpień będziesz odpowiedzialny).", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Miłość to znaczy popatrzeć na siebie, Tak jak się patrzy na obce nam rzeczy, Bo jesteś tylko jedną z rzeczy wielu.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Moja radość Na myśl, że liście będą, kiedy mnie nie będzie. Próbuję zrozumieć, co ta radość znaczy.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Moja wierna mowo, służyłem tobie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Na dnie swojej nędzy Polska dostała króla, i to takiego, o jakim śniła, z piastowskiego szczepu, sędziego pod jabłoniami, nieuwikłanego w skrzeczącą rzeczywistość polityki.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Nadziei każdy musi szukać sam dla siebie. Nie ma żadnej powszechnej recepty.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Panie Boże, lubiłem dżem truskawkowy I ciemną słodycz kobiecego ciała (…)<br />Jakiż więc ze mnie prorok?", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Patrzcie, jak drzewo rzuca długie cienie, I nasz, i kwiatów cień pada na ziemię: Co nie ma cienia, istnieć nie ma siły.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Przystojniej byłoby nie żyć. A żyć nie jest przystojnie, Powiada ten, kto wrócił po bardzo wielu latach Do miasta swojej młodości.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Rzeczpospolita XVIII wieku była już rosyjskim protektoratem i rozbiory oznaczały raczej błąd rosyjskiej polityki, skoro carat musiał podzielić się z innymi monarchiami tym, co już miał.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Skąd bierze się moja pokora? A stąd, że zasiadam do stawiania znaczków na papierze w nadziei, że coś wyrażę, umiem na tym spędzać całe dnie, ale kiedy postawię kropkę, widzę, że nie wyraziłem nic.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Słowo jedno jedyne i jedno znaczące, które rozlegając się od niebios do piekieł przywróci ład utracony, słowo którego nie ma i ten szum jak lasu czy morza to tylko bełkot i płacz.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Tak mało powiedziałem. Krótkie dni. Krótkie dni, Krótkie noce, Krótkie lata. Tak mało powiedziałem, Nie zdążyłem.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "To, czego nie przeżyłeś, nie jest prawdziwe.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "To, że w buddyzmie nie istnieje pojęcie Boga osobowego, wydaje mi się najbardziej atrakcyjne. To znaczy, można wyznawać światopogląd naukowy i jednocześnie być buddystą.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Tylko siwy staruszek, który byłby prorokiem, Ale nie jest prorokiem, bo ma inne zajęcie, Powiada przewiązując pomidory: Innego końca świata nie będzie, Innego końca świata nie będzie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Tylko w Szetejniach, w wieku ośmiu lat. Potem nastąpiło wygnanie z raju.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Uszka i denka i dzbany. Niczego mi proszę pana Tak nie żal jak porcelany.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Wiedzieć i nie mówić: tak się zapomina. Co jest wymówione, wzmacnia się. Co nie jest wymówione, zmierza do nieistnienia.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Widzowie mogą robić sobie obraz mnie, jako takiego dostojnego starca, mędrca. No ale ja jestem małym chłopczykiem, który raptem osiwiał.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Więc sławę nam znaczono stworzyć – bezimienną, jak okrzyk pożegnalny odchodzących – w ciemność.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "W chwili dziejowej, gdy nic nie zależy od człowieka, wszystko zależy od człowieka.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Zadaję sobie pytanie, co najlepszego mogę dać studentom, co leży w zakresie moich możliwości.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Zaiste wariat na swobodzie największą klęską jest w przyrodzie.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Zając przebiegł nagle tuż przed nami, A jeden z nas pokazał go ręką. To było dawno. Dzisiaj już nie żyją Ni zając, ani ten co go wskazywał.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Związali drutem człowiekowi ręce I wyśmianego kładli w płytkie groby, Żeby nie wzywał prawdy w testamencie I już na zawsze był anonimowy.", Author = "Czesław Miłosz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Czesław_Miłosz", Text = "Zaglądali do kufrów, zaglądali do waliz, nie zajrzeli do dupy – tam miałem socjalizm.", Author = "Czesław Miłosz" },
        };
    }
}