using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class ElizaOrzeszkowa
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Nad wysoką, ciężką poręczą ławy oskarżonych podniosła się szczupła, jasnowłosa, czarno ubrana dziewczyna. Powieki miała spuszczone, postawę spokojną i głos trochę drżący. Uczyłam dzieci, myślałam, że czynię dobrze… I teraz myślę, że dobrze czyniłam.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Dusza ludzka, tak jak kula ziemska, posiada litosferę, na sposoby rozmaite wyrzeźbianą przez przygodne wiatry i wody, a pod tą zwierzchnią skorupą, jądro z naturą niezbadaną, i to skryte jądro właśnie, nie zaś rzeźba powierzchni, stanowi o wartości ludzi i o wzajemnych pomiędzy nimi podobieństwach.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Dusza ludzka zna dwa tylko stany: jest polem walki lub pobojowiskiem.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Są dusze tak stworzone, że czują spójnię, wiążącą je z wysokościami, bez granic wyższemi nad wysokości ziemskie.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Bożeż mój, Boże! toż bogactw wszelakich na świecie, jak tego śmiecia w izbie, kiedy przez cały tydzień jej nie zamieść. Toż tam ludzie dokazują, weselą się i grzeszą! Chyba oni nigdy nic nie robią, że im to wszystko do głowy przychodzi. Chyba oni Pana Boga nie lękają się i wstydu w oczach nie mają, kiedy takie rzeczy robić mogą. Człowiek i sto lat przeżyć mógłby, a w pracy i biedzie do głowy by mu nie przyszło, że są na świecie takie bogactwa, piękności, dziwy i grzechy! Oj, grzechy! Te szczególniej ludzi tych w oczy kłuły i w głowach im zamęt sprawiały. Nie dlatego, aby człowiek sam nigdy już Pana Boga nie obrażał i, szczególniej upiwszy się, siakim takim grzechem duszy nie obarczył. Ale zawszeż takie marnowanie darów boskich, rozpusty, kłótnie, zabijanie siebie i innych, to już piekło, czyste piekło!", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Co tam o śmierci myśleć, kiedy i żyć czasem dobrze... nie zawsze, ale czasem... dobrze!", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Człowiek a robak — mała różnica! robaka ryba je, a człowieka ziemia. Czy pan, czy chłop, czy król, czy parobek, każdego ziemia zjeść musi, jak ryba robaka. Ot, co!", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Czyny ludzkie, żeby mogły podobać się Bogu, muszą być nietylko dobremi, lecz nadto jeszcze nadprzyrodzonemi, czyli pochodzić z nadprzyrodzonej łaski Bożej...", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Grzechu lękaj się, nie cmentarza. Żywych lękaj się, nie umarłych...", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "I na tym świecie dobra żadnego nie zaznasz i duszę zgubisz. Czemu poczciwą nie być? poczciwym być dobrze. Kiedy człowiek żadnego grzechu na duszy nie czuje, to taki robi się lekki, jak ten ptak, co pod same niebo lata. I śmierci wtedy niestraszno. Choćby i dziś umrzeć, wszystko jedno, kiedy dusza czysta...", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Nieprawdą jest, że ludzie zdrowi, silni, z natury nie ułomni, umierają z cierpień moralnych.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Pan Bóg każdemu człowiekowi na świecie pracować przykazał... Święta modlitwa czortu do ciebie przystępu nie da, a przy robocie różne paskudztwa do głowy tobie przychodzić nie będą.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Są na świecie natury ludzkie, od wszelkiej studni głębsze, w które, gdy raz kwiat ukochania wpadnie, już go żadne fale precz nie wyrzucą, i żadne żale głośno wymówioną skargą nie splamią. Serce nóż zatopiony w sobie czuć może, ale usta nie otworzą się dla wydania słowa oskarżenia, bo nad wszystkie bóle większy żal zdejmuje nad tym, na kogo paść ma to słowo. Choćby im od tego oskarżenia włos nie spadł z głowy, oni go nie wymówią; choćby im ono wysunęło z tego serca połowę tego noża, który w niem zatopiony, oni go nie wymówią i jeszcze wszelkiemi sposoby, choćby kłamstwem, z ust innych wyjmować je będą. Jakto! tę pierś oskarżać, u której głowa nasza prześniła swój złoty sen życia? Tej duszy złorzeczyć, dla której z ognia, z wody, przez drogi kamieniste, przez czyściec gorejący pragnęlibyśmy dostać i przynieść wszystkie błogosławieństwa! Na te dni i godziny wyrzekać, w których nam drzewa śpiewały, ptaki gadały, ze wszystkich zdrojów życia wody słodkie i gorące biły! Wszystko to mogło być snem, złudzeniem, marą rozwiewną, lotną błyskawicą, po której same ciemności zostały, ale winy w tem niczyjej niema, a jeśli jest czyja, to nasza raczej, stokroć raczej nasza, lecz nie tej istoty, której oskarżyć za żadną cenę przed nikim w świecie usta nasze nie chcą i nie mogą.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Takie uczucia, nierozbierane, nienazywane, okrywają rozległe niziny ludzkości, lecz dlatego, że kwitną nisko i są bezimienne, mieszkańcy gór mniemają, że ich wcale nie ma.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Ty wielkim krzyżem przeżegnaj się, na tę szelmę pluń i po dawnemu sobie cicheńko, spokojnieńko żyć zaczynaj. Czego tobie braknie? Chatę swoją masz, rzemiosło, i dobre, w ręku masz, grosz siaki taki, i przyjaźń ludzką, i łaskę a miłosierdzie Pana Boga wszechmogącego nad sobą masz... Czego tobie smucić się i w zgryzocie żyć? Oj, oj! żeby tak wszystkim dobrym ludziom na świecie było, jak tobie dobrze być może, jeśli głupim nie będziesz. Pana Boga słuchaj, z dobrymi ludźmi żyj, jedz, pij i na tę biedę, co cię spotkała, pluj! Żaden człowiek bez biedy na świecie nie przeżyje, ale bywają daleko od tej gorsze...", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Wszelkie stworzenie swój żal i swoją biedę ma. Czemu to tak? Chto jego znaje?", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Przeznaczenie stoi za ludźmi, welonem tajemnicy zasłonięte, i w dłoni trzyma kołczan z tysiącem zdarzeń.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Z nadzieją czy przeciw nadziei!", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Co, kto miłuje, to i we śnie czuje.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Noc po dniu następuje, a dzień po nocy. Śmiech od płaczu smaczniejszy.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Zawsze jest pora i widzieć i mówić prawdę.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "O, nigdzie i nigdy nie znikająca pycho ludzi, głupia pycho robaków!", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Wierzę, iż miłość mężczyzny dla kobiety nie powinna być alfą i omegą ludzkiego istnienia, że ugiąć się, złamać się pod nią może tylko człowiek słaby, albo taki, któremu ona zastąpić musiała wszystko: czyn, ideę, sławę. W klatce niéma wyboru pożywienia; zgłodniały bierze taki pokarm, jaki znajduje, a jeśli pokarm ten jest trucizną, żyje nią czas jakiś, a potém… umiera, i tém się kończy jedna z tragi-komedyi ludzkiego istnienia na świecie.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Żeś nigdy nie kochał, a wybuch materyi palnych, im dłużéj wstrzymywany, tém silniejszy.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Bardzo trudno albo i niepodobna pomalować wstęgę życia kolorem różowym na zawsze.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Bywa z ludźmi, którzy widnokrąg swój biorą za koniec świata, nie pojmują, nie mają dość mocy serca i umysłu, aby pojąć, że osobiste bóle i szczęście to wyjątkowe, przelotne chwile w życiu człowieka, a całe życie jest nieprzerwanym ciągiem prac i powinności, którego ani radości, ani cierpienia przerywać nie powinny.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Dusze, tak samo jak ciała, bywają chore od urodzenia, albo od różnych przypadków życia. Utrzymywanie w zdrowiu dusz ludzkich i ich leczenie jest zadaniem trudniejszem niż czynienie tego względem ciał.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Im więcej naród jest oświecony, tym wyżej ceni tych, którzy mu światło przynoszą.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Kobieta z gatunku tych, którym ojcowie nasi dali miano herod-baba. Ruchliwa, krzykliwa, nieustraszona, gotowa zawsze do celów swych ludzi za gardła brać albo im oczy wydzierać. W biały dzień i na ulicy wyłajać bliźniego może ona tak dobrze, jak przełknąć ostrygę.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Ku celom pożądanym wiodą drogi trudne.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Los pożycza, nie daje.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Miłość jak odrę każdy człowiek, choćby raz, przebyć musi.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Nie idzie już tu nawet o serca, bo te, tak pod jedwabnymi, jak pod wełnianymi i perkalowymi stanikami, są u tak zwanej płci pięknej drażliwym i zarazem bezbronnym miejscem; byle co zranić je może, byle co zawojować.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Nie każdy może kochać, kto chce kochać.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Nikt nie zrozumie kobiety… ona sama siebie też nie.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Trzeba być podobnym, aby się zrozumieć i innym, aby się pokochać. Trzeba być silnym, aby wybaczyć.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Wspominać to łowić wiatr, co umknął w pole niepowrotności.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Zbyteczna pokora tak samo pozbawia sił, jak zarozumiałość.", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Złość jest chorobą duszy…", Author = "Eliza Orzeszkowa" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Eliza_Orzeszkowa", Text = "Żeby umieć kochać, trzeba umieć myśleć.", Author = "Eliza Orzeszkowa" },
        };
    }
}