using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class HenrykSienkiewicz
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Częstokroć mąż i żona przystają do siebie, jak dwie spaczone deski, a jednak jakoś to idzie…", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gdy na zamężną kobietę pada podejrzenie, że należy do kogo innego, cały świat urządza na nią jedną wielką obławę, często pełną bezmyślnego okrucieństwa.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Nie może być nic bardziej gnębiącego dla człowieka, który prawdziwie kocha, jak to poczucie, że przynosi zło i szkodzi istocie kochanej.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Wola ludzka kończy się tam – gdzie zaczyna się miłość (…).", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Lecz był to człowiek mający nie tylko ciało, lecz i duszę z żelaza. Umiał łamać innych, umiał i siebie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Mieczów ci u nas dostatek, ale i te przyjmuję jako wróżbę zwycięstwa, którą mi sam Bóg przez wasze ręce zsyła.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Historii Stanów Zjednoczonych szukaj w Waszyngtonie; w Nowym Jorku masz tylko kupców. Handel, handel i handel, ''business'' i ''business'', oto, co widzisz od rana do wieczora, o czym ustawicznie słyszysz i czytasz.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Nie blednieje, nie zgrzyta zębami, nie gryzie pięści z bólu i nie szarpie sobie duszy ten, kto wcale nie kocha…", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Boże, Ty to widzisz i nie grzmisz?", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Dziwne materii pomieszanie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Ale jak sobie co baby wbiją w głowę, obcęgami nie wyciągniesz.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Cóż bowiem są smutki, jeśli nie myszy, które gryzą ziarna wesołości złożone w naszych sercach?", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kochanie jak i śmierć nikogo nie minie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Jak nie ma ginąć ta Rzeczpospolita, skoro w niej białogłowy rządzą?", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Ale gdy pożyjesz dłużej, poznasz, że gdy ktoś chce czegoś na świecie dokazać, temu nie wolno ni własnej, ni cudzej słabości folgować, nie wolno większych spraw dla mniejszych poświęcać.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Głupich nigdzie na świcie nie brak, a szczególnie w tym kraju!", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Bogowie i ludzie szukają miłości.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Głupota (…) w niczym nie jest gorsza od mądrości i w niczym się od niej nie różni.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "O śmierci nie warto myśleć, bo ona bez naszej pomocy o nas myśli.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Świat stoi na oszustwie, a życie jest złudzeniem.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Często nawet inne małżeństwa są gorsze, bo gdy na przykład kobieta woli latać, a mężczyzna pełzać lub odwrotnie – to nie ma widoków na porozumienie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "miłość nie jest całkowicie ślepą, ale cierpi na daltonizm.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "można kobietę kochać nie taką jaka jest, ale taką jak by być mogła.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Najenergiczniejszy człowiek potrzebuje, by go ktoś kochał. Inaczej czuje w sobie śmierć i jego energia zwraca się przeciw życiu.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Zmarli opuszczają nas, ale i my ich opuszczamy.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Jeśli ktoś Kalemu zabrać krowy (…) to jest zły uczynek (…). Dobry, to jak Kali zabrać komu krowy.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Biada narodom, które kochają więcej wolność niż ojczyznę!", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Boć przecież, zaiste, pisma nie na to istnieją, byśmy ich szpaltami łatali nasze miłości własne.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Dla pokrzepienia serc.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Dobroć serca jest tym, czym ciepło słońca: ona daje życie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "gdy się czasem Polka Panu Bogu uda, to już, mówiąc po prostu, klękajcie narody!", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gdy się ktoś zaczyta, zawsze albo się czegoś nauczy, albo zapomni o tym, co mu dolega, albo zaśnie – w każdym razie wygra.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gdyby cnota opalała płeć jak słońce, kobiety zasłaniałyby się i od cnoty parasolkami.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gdybym miał określić, czym miłość być powinna, gdybym od niej czegoś chciał, to bym chciał… żeby się składała w równej części: z żądzy i z czci!", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gdzie indziej szewc zazdrości szewcowi, a malarz malarzowi. U nas szewc zazdrości malarzowi.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Głoszono Polskę umarłą, a oto jeden z dowodów, że ona żyje. Głoszono ją podbitą, a oto nowy dowód, że umie zwyciężać!", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Głowa mędrca, śpiąca na piersiach kobiety, to największy tryumf miłości.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Gwiazdka nadziei niknie ostatnia.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Hej, łzy się kręcą…", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Herod to był wielki król.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Higiena i miłość nigdy nie będą w zgodzie, albowiem pierwsza poleca owoce dojrzałe, a druga ich nie znosi.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Idea Ojczyzny powinna zawsze zajmować pierwsze miejsce w życiu każdego Polaka.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Jakie społeczeństwo, taka literatura.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Jesteśmy narodem zdemoralizowanym do gruntu i upadłym. Cudzoziemcowi, który by tak twierdził, wybiłbym zęby, ale między nami mówiąc: tak jest (…)", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kłamstwo jest chyba bardziej nagie niż prawda, albowiem stale od niej szat pożycza.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kobieta w bieliźnie to pornografia. Naga kobieta to piękno.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kochać a kochać to różnica.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kościół jest stróżem przeszłości, piastunem teraźniejszości i siewcą przyszłości.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kto kocha – ten wierzy.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Kto się kocha, temu się zwykle zdaje, że każdy sięga po przedmiot jego miłości.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Mężczyzna nie znosi u innych przede wszystkim wad własnych.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Miłość jest mgłą, która wytwarza się w głowie. Jeśli owa mgła opada na dół – na serce – następuje pogoda życia; jeśli pozostaje w głowie – pada deszcz łez.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Miłość potrzebuje gniazda jak ptak.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "miłość uszlachetnia wprawdzie wszystko, ale tylko wówczas, gdy jest wielką, gdy jest jedna na całe życie.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Można kochać a nie lubić…; w takim właśnie razie miłość gorzknieje do tego stopnia, że może stać się wiekuistym nieszczęściem.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Mój Boże, nie doczekam wolnej Polski.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Muzyka balowa sprawia, że matki słyszą gorzej niż zwykle, a córki lepiej.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Nagość artystyczna jest plamą barwną, nagość pornograficzna jest plamą etyczną.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Nie rzeczywistość sama, ale serce, z jakiem ku niej przystępujemy, daje rzeczom kształty i kolory.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "nieszczęście ma to do siebie, iż stoi, a człowiek, czy chce, czy nie chce, musi iść w przyszłość, więc odchodzi od niego coraz dalej.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Nieznajomość historii u Francuzów równa się w wielu razach osławionej nieznajomości geografii.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Otóż człowieka, który by tak kochał ludzi, jak Chałubiński, nie spotkałem.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Polak – sierota świata.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Prawdziwy mędrzec zawsze jest ze swego losu zadowolony.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Przyjaźń jest jak nieśmiertelnik: to blady kwiatek, ale niewiędnący nigdy.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Przyjaźń z kobietą zawsze kończy się miłością.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Ruja i porubstwo.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Tylko bardzo małe świeczki gasną od westchnień.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "W wielkim i szczerym kochaniu powinna się mieścić także przyjaźń.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "walory pokonanego wroga powiększają rozmiary własnego sukcesu.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Wolność jest to prawo do robienia tego, co się chce i przeszkadzania innym w robieniu tego, czego chcą.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Wyrachowanie na tym polega, aby nie żałować wydatku na to, co warte wydatku.", Author = "Henryk Sienkiewicz" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Henryk_Sienkiewicz", Text = "Zaszczytniej jest dla kobiety mieć u swych stóp lwa niż mopsa.", Author = "Henryk Sienkiewicz" },
        };
    }
}