using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class JulianTuwim
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Dzieci bzdurzą i – że tak powiem – chcą być bzdurzone. Potem im to przechodzi. Któremu nie przejdzie – zostaje poetą.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zakopane i cel wieczoru urocze i w lecie na pokaz.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "My country is my home. Ojczyzna Jest moim domem. Mnie w udziele Dom polski przypadł. To – ojczyzna A inne kraje są hotele.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Niech prawo zawsze prawo znaczy, A sprawiedliwość – sprawiedliwość.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Gdy wyjdzie biskup, pastor, rabin Pobłogosławić twój karabin, Bo mu sam Pan Bóg szepnął z nieba, Że za ojczyznę – bić się trzeba;", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Rżnij karabinem w bruk ulicy! Twoja jest krew, a ich jest nafta!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "A zresztą… małoż to bywa Na świecie różnych wypadków? Może się jednak zmienimy?", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Aby się poznać z najdalszą rodziną, wystarczy się wzbogacić…", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "A dziś o byle pindę, ździęrę Zaraz się gwałt i proces zacznie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "A ja, by się nie dać ogłupić, Także poszedłem się upić.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Bez mistycznego pomostu, Który prowadzi po prostu Do pani (pardon!) pośladków; Gdybym opuścić mógł z tonu I nie zaznając katuszy Dupie nie wmawiałbym duszy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Błogosławiony ten, co nie mając nic do powiedzenia, nie obleka tego faktu w słowa.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Bogactwo: oszczędności wielu w rękach jednego.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Ci, którzy przemawiają w imieniu Boga, powinni pokazać listy uwierzytelniające.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Cierpliwość – rozpacz pod maską cnoty.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Cnotliwa dziewczyna nigdy nie lata za chłopcem. Czy kto widział, żeby pułapka goniła mysz?", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Corpus delicti – rozkoszne ciało.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Czy żona męża stanu jest mężową stanu czy żoną stanu? I czy to zależy od stanu męża?", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Czysta wyborowa źle wpływa na czystość wyborów.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Do innej kobiety: „Jaka szkoda, że nie poznałem pani dwadzieścia kilo temu”.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Duchowny: człowiek, który dba o nasze życie poza grobem i w ten sposób zarabia na własne życie doczesne.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Dwa kieliszki wystarczą. Najpierw jeden, potem kilkanaście drugich.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Dziecko: przewód pokarmowy z hałasem z jednego końca i brakiem odpowiedzialności z drugiego.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Egoista: ten, który więcej dba o siebie niż o mnie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Ewangelia: księga do której zasad bliźni nasz powinien się stosować.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Filantrop jest to człowiek, który publicznie zwraca bliźniemu drobną cząstkę tego, co mu ukradł prywatnie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Gdy ci coś wpada do oka, pamiętaj, że to odrobina kosmosu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Głupstwa można mówić. Byle nie uroczystym tonem.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Gratulacje: najuprzejmiejsza forma zawiści.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kiedy przeskoczysz, to i wtedy nie mów hop. Zobacz najpierw w co wskoczyłeś.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Knajpa: miejsce, dokąd się co wieczór chodzi po raz ostatni w życiu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kobieta jest jak róża; na to ma kolce, by je owijać płatkami.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kobieta powinna być interesująca tylko erotycznie, ściślej: seksualnie. Inne jej zalety mężczyzna sam już sobie dorobi.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Konserwatysta: człowiek, któremu się zdaje, że nic nigdy nie zostało zrobione po raz pierwszy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Marzenie kobiety: mieć stopę wąziutką, a żyć na szeroką.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Mężczyzna pozostaje zazwyczaj bardzo długo pod wrażeniem, jakie zrobił na kobiecie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Miłość: jedyna funkcja fizjologiczna, która zrobiła karierę.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Mówią, że ostrożność jest matką powodzenia. To nieprawda, bo gdyby była ostrożnością, nie zostałaby matką.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Murzyni mówią, że na początku świata wszyscy ludzie byli jednego koloru. I nastał dzień, kiedy Bóg rzekł do Kaina: „Co zrobiłeś z twoim bratem Ablem?” Wtedy Kain zbladł ze strachu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Najpierw zaszło słońce, potem zaszedł fakt, a w rezultacie i ona.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nawet najpiękniejsze nogi gdzieś się kończą.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nie odkładaj nigdy do jutra tego, co możesz wypić dzisiaj.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nie pożądaj żony bliźniego swego nadaremno.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nie wiem, co się na świecie zrobiło! Zaczynają teraz umierać tacy ludzie, którzy dawniej nigdy nie umierali.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Odwaga: podejść do boksera i zwymyślać go od ostatnich. Ostrożność: powiedzieć mu to samo przez telefon.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Owocu zakazanego nie gryź wstawionymi zębami.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pamiętaj o ubogich – mawiał pewien łódzki fabrykant – to nic nie kosztuje.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Para: woda w natchnieniu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pchła: owad, co zszedł na psy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pesymista: optymista z praktyką życiową.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pesymista to człowiek, który sądzi, że wszyscy są tacy sami dranie jak on. Dlatego nienawidzi bliźnich.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pesymista twierdzi, że wszystkie kobiety to nierządnice. Optymista nie jest tego zdania, ale ma nadzieję.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pięść: ręka w gniewie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Powiedz człowiekowi, że na niebie jest gwiazd 978301246569987 a uwierzy. Ale napisz kartkę „Świeżo malowane”, a sprawdzi palcem i powala się.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Powiedzieć komuś: idiota! – to nie obelga, lecz diagnoza.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Przypuszczam, że w starożytnym Rzymie mówiono „żydochrystianizm” w tym samym sensie, jak u nas mówią o „żydokomunie”.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Radio – to cudowny wynalazek! Jeden ruch ręki – i nic nie słychać.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Rodzynka – stroskane winogrono.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Romans – to marzenie człowieka samotnego, a samotność – marzenie człowieka, który ma romans.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Różnica między wielbłądem a człowiekiem: wielbłąd może pracować nie pijąc przez cały tydzień; człowiek może przez tydzień pić nie pracując.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Sukces: coś, czego przyjaciele nigdy ci nie wybaczą.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Święty: martwy grzesznik, odpowiednio zredagowany i wydany.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Takt: nie wypowiedziana część naszych myśli.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Tragedia: zakochać się w twarzy, a ożenić z całą dziewczyną.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Twarz: to, co wyrosło dokoła nosa.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Uprzejmość – najwytworniejsza forma fałszu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "W twarz dadzą sobie napluć za tyle a tyle Obetrą gębę ręką, a sumę przeliczą!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Wierność: silne swędzenie z zakazem podrapania się.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Wolnoć Tomku w swoim podświadomku.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Wszystko w polowaniu jest urocze i nęcące. Z wyjątkiem zabijania zwierząt.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Znałem kobietę z takim zezem, że jak płakała, to łzy ściekały jej zza uszu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Znam 94-letniego starca, który całe życie pił, dziś jeszcze pije i jest zdrów jak ryba. Brat jego natomiast nie brał nigdy kropli do ust i umarł, mając dwa lata.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Z tego morał się wywodzi dla wielu, nie protestuj, gdy sam smrodzisz, śmierdzielu.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Życie – dożywotnia kara śmierci.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Życie to męka. Najlepiej się wcale nie urodzić. Ale to szczęście ma jeden na tysiąc.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Bezprzyczynny mój dzień, Bezsensowny mój wiek I te ślady bezładnych moich kroków po ziemi (….).", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Jak ciasto biorą gazety w palce I żują, żują na papkę pulchną, Aż, papierowym wzdęte zakalcem, Wypchane głowy grubo im puchną.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nie kwiatami, lecz zbożem zasiewajmy groby Ojców swych. Gdy ich ziemia przemiele w swych żarnach, Wzniosą się, martwi, w kłosy, zjędrnieją nam w ziarna I dopomną się szumem o żniwo żałoby.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nie natchnij mnie hymnami, bo nie hymnów trzeba Tym, którzy w zżartej piersi pod brudną koszulą Czcze serca noszą.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Od rana bełkot. Bełkocą, bredzą, Że deszcz, że drogo, że to, że tamto, Trochę pochodzą, trochę posiedzą, I wszystko widmo, i wszystko fantom.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Straszne mieszkania. W strasznych mieszkaniach Strasznie mieszkają straszni mieszczanie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Chwilna, zwiewna przelotność", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Jeden wiatr – w polu wiał, Drugi wiatr – w sadzie grał: Cichuteńko, leciuteńko, Liście pieścił i szeleścił, Mdlał…", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "On – najmędrszy, on – wybraniec, Gałgan z brzydką mordą psa, Poznał taniec, poznał taniec, Hopsa, hopsa, hopsa-sa!!!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Skonała radość – rozpacz skona…", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Palą się w moim wzroku Miliardy waszych dolarów, Popiół sypie się szary Z pychy głupich sztandarów.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Umrę ci kiedyś Oczy mi zamkniesz i wtedy swoje smutne, zdziwione – bardzo otworzysz…", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Aby ci, w których palnę, prosto w łeb dostali Kulą z sześciostrzałowej, błyszczącej piosenki!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Aforyzmu o książce nie potrafię niestety wymyślić. Książki kupuję, zbieram, czytam, nawet je piszę – i zanadto kocham, aby zbywać je aforyzmami.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Anielcia miała matkę bardzo małomówną, Więc gdy kiedyś spytała z minką zatroskaną: „Powiedz, droga mamusiu, co to jest guano?” Mama odrzekła: „G... o”.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "A teraz usnę – z uśmiechem szczęścia na zmęczonych wargach... szepcących słodkie Twoje imię. Dobranoc!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Bezstronny jak katalog.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Bo ja sama wszystko wiem I śniadanie sama zjem, I samochód sama zrobię, I z wszystkim poradzę sobie!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Całowałem usta Twoje, całowałem je w ciemności, w czarnym aksamicie miłosnej nocy... Całowałem usta Twoje i wyczuwałem wargami czerwień ich...", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Chodź, Młoda do Młodego: Ojcostwa mi się zachciało!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Co mi się pan tak przygląda? Jeśli dziwi pana, że mam taką dużą myszkę na twarzy, to mogę pana zapewnić, że gdybym się bez niej urodził, odebrałbym sobie życie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Co nam zostało z tych lat Miłości pierwszej? Zeschnięte liście i kwiat W tomiku wierszy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Czas życia krótki, kropnijmy wódki.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Dla oszczędności zagaście światło wiekuiste, gdyby miało mi kiedyś zaświecić.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Drogie dzieci! W tym liściku O jedno was proszę: Żebyście się co dzień myły, Bo brudnych nie znoszę.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Item ów belfer szkoły żeńskiej, Co dużo chciałby, a nie może, Item profesor Cy... wileński (Pan wie już za co, profesorze!)", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "I ty, księżuniu, co kutasa Zawiązanego masz na supeł, Żeby ci czasem nie pohasał, Całujcie mnie wszyscy w dupę.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Jeszcze się kiedyś rozsmucę, Jeszcze do Ciebie powrócę, Chrystusie...", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kiedy pytasz dorożkarza: „Wolny?” i otrzymasz odpowiedź twierdzącą – rzeknij: „To się ożeń”. Wychodząc z restauracji, należy odbierać w garderobie palto, pytając: „Gdzie mnie pan powiesił?”", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "„Kocham kobietę”. Znaczy to, że ta właśnie kobieta najbardziej mi tu na ziemi przypomina KOBIETĘ, którą rzeczywiście kocham.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Krwi słucham Twego serca, Bijącej w białej piersi I trwam miłością błędną W tym życiu, pełnym śmierci.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kto ja jestem? Kamień nagrobny Z wyrytym Twoim imieniem.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Kto z zielników, ziółek i przyziółków ZIELA zerwie w podsłownym zaułku i w zieliszczu, w szumnej zielbie świata, Antenata znajdzie, Zielonata.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Lipiec jest miesiącem, kiedy w tramwaju nie można otworzyć okna, którego w grudniu nie można zamknąć.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Miauczy kotek: miau! – Coś ty kotku miał?", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Miłość ci wszystko wybaczy, Smutek zamieni ci w śmiech. Miłość tak pięknie tłumaczy Zdradę i kłamstwo i grzech.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Milczenie to tekst, który niezwykle łatwo jest błędnie zinterpretować.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Milionerzy umierają wszyscy, a z chorych na tyfus tylko 65%.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Mój piesek Dżońcio – oto go macie – To mój największy w świecie przyjaciel. Codziennie w kącie kanapy siadam I z moim Dżońciem gadam i gadam.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Murzynek Bambo w Afryce mieszka, czarną ma skórę ten nasz koleżka.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Na pierwszy znak, gdy serce drgnie, ledwo drgnie, a już się wie, że to właśnie ten, tylko ten.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Na to wróbel zaterlikał: „(…) Ćwir ćwir świrk! Świr świr ćwirk! Tu nie teatr Ani cyrk!”", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nagrobek, który postawił żonie swej pewien wdowiec niepocieszony: „Łzy moje nie wskrzeszą cię. Dlatego płaczę”.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Najukochańsza moja! byle być przy tobie, Bez twej miłości nawet, ale z tobą być!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Nasza jest noc i oprócz niej nie mamy nic.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Ojczyzną moją jest Bóg, Duch, Syn i Ojciec wszechświata. Na każdej z moich dróg Ku Niemu dusza ulata.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "O, staroświecka młoda pani z Krakowa! Strzeż się! Biskup pieni się i krzyczy: horrendum!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pamiętaj: kiedy znów zdziczeję, Odrzyj mnie z wichrów i ugłaskaj!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pani pachnie jak tuberozy. To nastraja i to podnieca A ja lubię tuman narkozy, A najbardziej – gdy jest kobieca", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Pojęcia takie jak: wieczność, bezgraniczność zaczynam rozumieć dopiero wtedy, gdy załatwiam jakąś sprawę w urzędzie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Polak – bo moja nienawiść dla faszystów polskich jest większa niż faszystów innych narodowości. I uważam to za bardzo poważną cechę mojej polskości.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Po wypiciu jednej wódki wypij zaraz drugą, żeby tej pierwszej nie było w żołądku smutno.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Płacze pani Słowikowa w gniazdku na akacji, Bo pan Słowik przed dziewiątą miał być na kolacji.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Proszę! Zostaw mnie na drugie życie, Jak na drugi rok w tej samej klasie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Próżnoś repliki się spodziewał Nie dam ci prztyczka ani klapsa. Nie powiem nawet pies cię jebał, bo to mezalians byłby dla psa.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Puszczała się dziewczyna, puszczała z miłości, Puszczała dla pieniędzy, puszczała z litości, Aż taką masę razy upadła moralnie, Ze całkiem się skurwiła – i wpadła fatalnie,", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Różo, różo, formalistko! Różo, różo, bój się Boga!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Słowem... nie wiem, jak to wyrazić... Kocham ciebie nieomal okropnie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Spotkali się w święto o piątej przed kinem Miejscowa idiotka z tutejszym kretynem.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Sterczy w ścianie taki pstryczek, Mały pstryczek-elektryczek, Jak tym pstryczkiem zrobić pstryk, To się widno robi w mig.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Stoi na stacji lokomotywa, Ciężka, ogromna i pot z niej spływa – Tłusta oliwa.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Sumienie to jest ten cichy głosik, który szepce, że ktoś patrzy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Szkoda papieru i atramentu Szkoda peiperu i putramentu Szkoda Przybosia, szkoda Miłosza Wszystko to pójdzie razem do kosza.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Szkoda, że całe niebo Nie jest z tortu czekoladowego… Jaki piękny byłby wtedy świat!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Szkoło! Szkoło! Gdy cię wspominam, Tęsknota w serce się wgryza. Oczy mam pełne łez!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Szukałem tego w Paryżu, szukałem w Berlinie i Rzymie, A to za oknem było i miało polskie imię.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Szur, szur, szur, gwar, gwar, gwar, Suną tysiące rozwydrzonych par, – A dalej! A dalej! A dalej! W ciemne zieleńce, do alej,", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Tańcowały dwa Michały, Jeden duży, drugi mały.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Tu leży wieszcz, Przechodniu, nie szcz.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Ty trzymasz mnie na ziemi, Ty wznosisz mnie do nieba, Tyś jest mi tutaj wszystkim, Po co aż tam iść trzeba.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Tylko niemowlęta piją wódkę z zagrychą.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Używaj aforyzmów: „Nie to ładne co ładne, ale co się komu podoba” oraz „Są gusta i guściki” (Uwaga! Mów: „Biusta i biuściki” – a będzie jeszcze śmieszniej).", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "W brzoskwinię ciepłą, dłońmi moimi utuloną, tak miękką już, że sok lada chwila puści, wpijam się tym wszystkim, czym są usta...", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "W naturze nie ma linii prostej, Ludzki to wymysł sztuczny. Patrząc w skłębione żyworosty, Chaosu, chaosu się uczmy.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Warto, warto żyć. Mgławo jest za oknami, Zaraz listonosz zadzwoni, Ustami przypadam do dłoni,", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Wasze słowa są, jak salonowe pieski, A moje – jak wściekłe psy!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Wiem, że zawsze trafię, którą pójdę drogą, Bo wszystkie moje drogi prowadzą do Ciebie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Włóczęga: człowiek, który nazywałby się turystą, gdyby miał pieniądze.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Za zdrowie Kaczkosi, co Żydom wodę nosi!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zakochałem się w tobie, pani, w pewnej mierze, rzekłbym, niebywale.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zamiast pić – odkładaj do PKO. Gdy się zbierze większa sumka – przepij.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zasadził dziadek rzepkę w ogrodzie, Chodził tę rzepkę oglądać co dzień. Wyrosła rzepka jędrna i krzepka,", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zbiry, katy, wyrzutki, Wisielce, prostytutki, Syfilitycy, nożownicy, Łotry, złodzieje, chlacze wódki.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zdrowie twoje w gębę moję!", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Znałem człowieka, który umarł pionowo: powiesili go.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Zmęczony burz szaleństwem, jak statek pijany, Już niczego nie pragnę, jeno wielkiej ciszy I kogoś, kto zrozumie mój żal nienazwany,", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Z miłością wpadłem już nie raz, Bo mam demokratyczne serce, I tak się stało, proszę was, Że zakochałem się w kelnerce.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "„Żeby kózka nie skakała, Toby nóżki nie złamała” Prawda, Ale gdyby nie skakała, Toby smutne życie miała.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Żeby móc „zacisnąć pasa”, trzeba najpierw mieć spodnie.", Author = "Julian Tuwim" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Julian_Tuwim", Text = "Żyj tak, aby znajomym zrobiło się nudno, gdy umrzesz.", Author = "Julian Tuwim" },
        };
    }
}