using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class LeopoldTyrmand
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Dobroć wymaga reklamy, tak samo jak zbrodnia, aczkolwiek tę ostatnią reklamować jest łatwiej.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Jeśli w kapitalizmie bezrobocie jest nieszczęściem, w komunizmie jest przestępstwem.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Kiedy kobiety nie umieją odmawiać (…), upada kultura i więdną sztuki piękne. Kiedy kobieta potrafi powstrzymać rękę, ściągającą jej majtki, ręka pisze Cierpienia młodego Wertera, układa elegie, tworzy piękno i sięga po pojedynkowy pistolet, którego strzał otwiera oceany uczuć subtelnych i tkliwych.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Książki powinny same mówić o sobie i za siebie.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Mężczyzna, mówiąc „kocham”, myśli: „będę cię kochał jutro, pragnę, aby jutro wyglądało tak, jak dziś…” Kobieta, mówiąc „kocham”, myśli „kocham cię dziś i nie chcę myśleć o jutrze…”", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Nadzieja nadaje się do szyderczych przysłów.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Szczęście jest zawsze gdzie indziej.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Wędrowcy są zawsze wędrowcami wbrew własnej woli, inaczej zaliczają się do kategorii turystów lub wycieczkowiczów.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Właśnie drobne defekty budzą tkliwość. Nie kocha się doskonałości, lecz proporcje i to czasem bardzo niedoskonałe. Czasem fakt, że czyjeś brwi są zbyt blade, a usta za szerokie, jest przyczyną fali czułości.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Wraca się jedynie do tych, których się kocha. Nie wraca się tam, gdzie jest się tylko kochanym. Wraca się wyłącznie do tych, których się kocha. Albo nie wraca się nigdzie i do nikogo. Po prostu jedzie się dalej.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Syneczku (…) po to, aby pisać, trzeba przede wszystkim wiedzieć, o czym się pisze. Wiedzieć, rozumiesz, zasada numer jeden. Inaczej zaczyna się pisać o wężach morskich.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Ciekawe – pomyślał – że wielka mistyfikacja literatury kryminalnej polega na braku luk w potoku wypadków. W powieściach tych dzieje się zawsze coś, co wypływa z żelazną logiką ze strumieniem zdarzeń. Tymczasem prawdziwe życie pełne jest luk, w których się nic nie dzieje. Coś dzieje się, potem przestaje się dziać i następuje luka.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Nie urodził się jeszcze na tym świecie architekt czy dekorator, który – budując kawiarnię – mógłby powiedzieć z góry: „W tym lokalu będzie taka a taka publiczność i taki a taki nastrój. Tak sobie to pomyśleliśmy i tak musi być…” – Kawiarnia zostaje urządzona, umeblowana, wchodzą do niej pierwsi goście, a po jakimś czasie okazuje się, że atmosfera jej nie ma nic wspólnego z tym, co zamierzyli jej twórcy: oddana do publicznego użytku rozpoczyna żywot własny i nieprzewidziany; jej losy nie dają się z góry wyznaczyć.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Warszawski kurz i pył lat odbudowy… Jeden z filozofów obliczył, że warszawiacy wdychali wtedy cztery cegły rocznie. Warszawiacy oddychali budową – nie była to metafora, lecz ciężka, zakurzona, ceglana i pylasta prawda. Trzeba zaś bardzo kochać swe miasto, by odbudowywać je za cenę własnego oddechu. I może dlatego Warszawa z pobojowiska gruzów i ruin stała się znów dawną Warszawą, wieczną Warszawą, tą samą Warszawą – mimo nowych kształtów ulic i konturów domów – że warszawiacy powołali ją do życia, tchnąwszy w jej ceglane ciało swój własny, gorący oddech.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "W zorganizowanym społeczeństwie jest tylko jedno prawo i tylko ono obowiązuje. Im ściślej organizujemy społeczeństwo dla skutecznej walki o rozwój, o coraz to lepsze życie, tym bardziej stanowczo przestrzegać musimy jedności i wyłączności prawa, obowiązującego nas wszystkich. I na tym polega praworządność.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "W żadnym z miast na świecie śnieg nie ma tak krańcowych humorów jak w Warszawie; nigdzie nie potrafi tak szybko i tak beznadziejnie zmienić się w brudne, dręczące błoto, ale też nigdzie nie pada z takim wdziękiem jak w tym mieście. Pada wtedy miękko i cicho, pokrywa świat cały puszystą bielą, mieniącą się w nocy granatowymi refleksami na dachach i skwerach, budzi tęsknoty za minionym dzieciństwem.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Wypili trzy ćwiartki wódki, po czym długo siedzieli milcząc, zaś w milczeniu tym było mnóstwo wzajemnych uczuć i kupa zadowolenia. Pierwszy raz pili razem alkohol. Ta chwila wymagała bowiem wielkiej dojrzałości i głębokiego, obopólnego zrozumienia.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Jak wiesz, życie jest gówno na kole – raz jest w górze, raz jest w dole – i to jest właśnie ze mną.", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Nie dlatego nie pływasz na kajaku, bo jesteś stary, lecz dlatego jesteś stary, bo nie pływasz na kajaku…", Author = "Leopold Tyrmand" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Leopold_Tyrmand", Text = "Z dziewczynami to jak z chodzeniem po bagnie. Skaczesz z kępy na kępę i próbujesz, jak daleko jeszcze możesz dojść. Jak dostaniesz w mordę, to wiesz, że trzeba się cofnąć. I idziesz do następnej.", Author = "Leopold Tyrmand" },
        };
    }
}