using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class MarekHłasko
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Cholera mi do tego co śmieszne, a co nie. Ja wolę zginąć na swój sposób, niż żyć i cieszyć się na wasz.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "I dlatego pewnie wymyślili małżeństwo i przysięgę wierności, iż wiedzieli, że nic na świecie nie pasuje tak źle do siebie jak mężczyzna i kobieta.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Kobieta, która nie daje snu mężczyźnie niewiele jest warta.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Pogodzenie się ze światem jest równie małoznaczne jak i bunt i wściekłość przeciw niemu.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Dziękuję Bogu że jestem tylko pijakiem. To jedyne, co daje jaką taką gwarancję; jeśli ktoś o mnie coś pomyśli, to tylko to jedno.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Świat to gromada zwierząt wałęsających się po gównie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Ludzie, którzy myślą, że z czasem dopiero staną się sobie potrzebni, powinni odejść od siebie i zapomnieć kroków, które ich wiodły ku sobie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Marzenie pozostanie czyste nawet wtedy, kiedy inni wdepczą ci je w błoto…", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Przez długie miesiące nie opuszczała mnie myśl, że właściwie nie jestem nikomu potrzebny. Zdawało mi się, że ludzie tacy jak ja – nie powinni żyć.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "W życiu warto mimo wszystko od czasu do czasu pomyśleć o sobie: to nie takie głupie, jakby się zdawało.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Cały świat to taki zasrany, wielki bluff, jaki wczoraj wyszedł temu bubkowi. Te góry to też lipa wymyślona przez jakichś podłych idiotów.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Człowieka gubi słabość.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Jeśli co po mnie zostanie, to tylko długi w knajpach. Mężczyzna tak powinien umierać.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Każda kobieta jest jak Bóg, dlatego tak mnie odpycha od religii.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Ludzie mijają się ze swoim prawdziwym ocaleniem i to jest najsmutniejsze.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie chcę iść do ziemi ze spermą w mózgu; potem kwiatki na grobie więdną.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie wiem, co można zrobić przez szesnaście godzin – rzekł. – Można się najeść, zakochać, zabić… Ale przekonać człowieka? To się czasem nie udaje przez całe życie…", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Raz w życiu pomyliły mi się kroki i od tego czasu chodzę krzywo.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Tak jest, że jeśli w piekle znajdzie się kobieta, to wychodzi z tego jeszcze gorsze piekło.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Trzeba być samemu, zawsze samemu, aż stąd do wieczności… Tylko wtedy jest siła, i pragnienie, i nie ma ni cierpień, ani strachu, ani złych snów po drodze…", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "W mieście wszyscy zdychają codziennie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Wielkie, silne zwierzęta umierają w samotności i milczeniu. Odchodzą w pustkę i nie skarżą się nikomu. Tylko człowiek szczeka wspomnieniami.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Zamieniliście [komuniści] Polskę w tak wielki obóz koncentracyjny, że nie potrzeba nawet drutów kolczastych i psów, gdyż i tak nie ma gdzie uciec.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Łatwiej oczyścić się z wielkich omyłek niż z drobnych świństw.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Słabością każdej mądrej idei jest to, że starają się realizować ją głupcy.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie myśl o tym, że wszystko się kończy. Myśl, że wszystko się dopiero zaczyna. To, co powinno być życiem: spokój, wolność i cisza.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Wszystko, co czyni człowiek, czyni z tęsknoty za lepszym życiem. Albo z protestu moralnego.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Chcę żyć tak, jak nie żył nikt. Nie chcę, żeby mnie pamiętali inni ludzie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Człowiek czasem myśli, że jest śmieszny, jak upierdoli drugiego.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Gdyby chciał pan rzucić w każdą kurwę kamieniem, musiałby pan rozebrać mury tego miasta.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Ja nie ufam niczemu, co ma pizdę i zna wartość pieniądza.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Ja przecież nawet seks muszę kupować ― powiedział Girl’s First Love. ― Tak jak inni kupują kartofle czy hamburgery. Jestem wstrętny i nikt mnie nie chce.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Kobiety nie mylą się nigdy (...) Tylko że nie mówią nigdy prawdy.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Moja żona jest w ciąży. ― Gratuluję ― powiedział mężczyzna. ― Wie pan przynajmniej z kim?", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie odejdę od ciebie, a nawet gdybym musiał odejść, to wezmę cię ze sobą. Nie umiałbym żyć bez ciebie, Helen. Wiesz, kiedy patrzę na ciebie, to myślę, że Bóg jednak istnieje.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Jeśli pani powie „osiem” – rzekł Kuba – to dziś odbiorę sobie życie. Uśmiechnęła się figlarnie i rzekła: – Osiem.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Kto pije – powiedział Władek i uśmiechnął się z mściwą satysfakcją – będzie pił. To zabawa bez mety.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie wiem, po co żyję, jeśli nie kocham nikogo…", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Przejdzie. Wszystko przechodzi. Nie ma gorszego snu jak życie. I też przechodzi.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Tylko młodzi ludzie są ciekawi. Człowiek naprawdę poznaje świat do któregoś tam wczesnego roku. Dalsza zabawa to powtarzanie cudzych doświadczeń.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Leżeli zmęczeni miłością i upałem, byli młodzi i ładni oboje.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Ja sam kochałem się w życiu tylko jeden raz; było to jedenaście lat temu i potem nie kochałem nikogo ani przez minutę, mimo iż bezustannie starałem się stworzyć sobie złudzenia.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Kiedy umiera człowiek wolny, kończy się życie pełne niebezpieczeństw, pełne walki, pełne radości. Ale kiedy umiera nędzarz, kończy się tylko wstyd. Mamy łzy w oczach.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Książki warto pisać tylko wtedy, jeśli przekroczy się ostatnią granicę wstydu; pisanie jest rzeczą bardziej intymną od łóżka; przynajmniej dla mnie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Świat dzieli się na dwie połowy, z tym jednak, że w jednej z nich jest nie do życia, w drugiej nie do wytrzymania.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Życie, które mi dano, jest tylko opowieścią; ale jak ja ją opowiem, to już moja sprawa.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Najbardziej kochamy tych ludzi, te sprawy i te rzeczy, od których bieg życia każe nam odchodzić – nieraz na zawsze.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Dano ci życie, które jest tylko opowieścią. Ale to już twoja sprawa, jak ty ją opowiesz i czy umrzesz pełen dni.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Każdy umie zabić, ale tylko prawdziwi ludzie umieją darować życie.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Pamięć jest głupstwem jak każda idea. Człowieka można tylko pamiętać poprzez innych ludzi.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "(…) po co człowiek w ogóle żyje, jeśli nie ma żadnych pragnień? (…) Nie warto żyć bez dobrych marzeń…", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Niech nie ośmielą się wydawać sądów o wódce ci, którym nie jest ona potrzebna. Jeśli ludzkość osiągnęła dotychczas cokolwiek trwałego w sensie ducha, to właśnie alkohol.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Miałem (...) fotografię takiej jednej kurwy, którą przechowywałem tylko dlatego, że była trochę podobna do innej kurwy, w której się kiedyś podkochiwałem.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Mnie tam nigdy nie żal kurew, bo kurwą nie można zostać, trzeba się nią urodzić i umrzeć, a reszta na ten temat to kiepska literatura.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Tak płakaliby chyba tylko umarli, którym przyszłoby zmartwychwstać i żyć po raz drugi.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Miłość nie jest prostą rzeczą, ale bez niej nie można żyć. Prawie wszystko na świecie da się wytłumaczyć miłością. To największy pomysł wszystkich czasów.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "(…) nie jestem przecież własnym patentem. Nie wymyśliłem samego siebie. To nie tylko inni muszą mnie znosić. Ja sam muszę także siebie samego znosić i nie idzie mi to wcale łatwo.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Nie ma kobiet dobrych i złych. Są tylko mężczyźni, którzy nie potrafią traktować ich tak, jak je traktować trzeba.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "(…) z każdej żony można zrobić kurwę. Nawet nie trzeba tego robić, one to już robią same. Kiedy z ich mężami zaczyna dziać się źle.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Zbyt wielu ludzi cierpi przez dobre uczynki i pomysły kobiet.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Dziś nie ma takiej zbrodni, której nie mógłby popełnić człowiek w imię wielkiego strachu.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Kiedy ma się dwadzieścia lat, to klęska jest jeszcze przygodą. Ale w dziesięć lat później wygląda ona jak stara prostytutka i jest tak samo nie do zniesienia, jak jej zapach i jej obecność.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Łatwiej chyba zbudować sobie nieśmiertelność niż porozumieć się z drugim człowiekiem.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Lecz aby płynąć, musieliśmy wiosłować we dwójkę.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Mam 11 lat, chciałbym być lotnikiem i chodzić do szkoły.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Można mieć syfilis, wyleczyć się z niego i nie mieć wstydu. Ale ze wstydu, że się miało pieniądze, żyło się z biednych ludzi – wyleczyć się nie można.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Największym nieszczęściem totalitaryzmu jest to, że zabija wyobraźnię.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "(…) nie osiągnął w życiu niczego, gdyż brakło mu i talentu, i wytrwałości. Jak każdy tego rodzaju człowiek uważał się jednak za skrzywdzonego i niezrozumianego.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Niektórzy mówią, że odwaga siedzi na krześle, którym jest strach.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Pijak znajduje w wódce szczęście upokorzenia siebie samego.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Przyjdzie czas, kiedy wrócę do Ciebie i będę już na zawsze Twoim alfonsem i omegą.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "To właśnie silni idą do diabła przez małych i głupich.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Wielka miłość zdarza się w życiu tylko raz, wszystko, co następuje potem, jest tylko szukaniem tej utraconej miłości.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Z każdej z nich można zrobić kurwę; ale to tylko dlatego, że nie umiemy z nich zrobić świętych.", Author = "Marek Hłasko" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Marek_Hłasko", Text = "Żył krótko, a wszyscy byli odwróceni.", Author = "Marek Hłasko" },
        };
    }
}