using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class OlgaTokarczuk
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Mówić do kogoś, kto nie rozumie, to próbować otworzyć zamek źdźbłem trawy, to kroić chleb gałązką bazylii, wkręcać żarówkę w ptasie gniazdo, wkładać dyskietkę między dwa kamienie. Daremnie.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Wszystko zdarza się tylko raz i my sami jesteśmy jednorazowi. Nie było nas, zanim się urodziliśmy, i nie będzie nas, gdy umrzemy. Raj to cyfrowy sen. Nikt nas nie wybawi, nie naprawi, nie zadośćuczyni.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Celem mojej pielgrzymki jest zawsze inny pielgrzym.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Gdyby można było spojrzeć na świat bez żadnej ochrony, uczciwie i odważnie – pękłyby nam serca.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Och, ludzie ciągle potrzebują rzeczy niezwykłych, cudów, szaleństw. I po co? Żeby z jeszcze większą gorliwością akceptować swoje zwyczajne życie.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Skoro jest prawo i porządek, musi być także coś, co to prawo dopełnia i ogranicza zarazem – chaos i nieistnienie. Nieistnienie i chaos.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Tu i teraz jesteśmy ślepi i nigdy nie wiemy, co jest naprawdę ważne.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Rewolucje nie lubią wariatów, bo same są śmiertelnie poważne.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Wszystko jest zawsze prostsze, niż się na początku wydaje.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Zdaje się, że nic nie budzi wśród mężczyzn takiego współczucia jak samotna kobieta.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Gdy przepisujemy i cytujemy, budujemy gmach wiedzy i rozmnażamy ją jak moje warzywa czy jabłonki. Przepisywanie jest jak szczepienie drzewa; cytowanie – jak wysiewanie nasion.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Skoro można pomyśleć, że może być lepiej, to znaczy, że już jest lepiej.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Wierzę, że uznawanie czegoś za oczywiste wcale nie wiąże się z kwestią faktów, lecz raczej umowy społecznej i przyzwyczajeń naszego umysłu, tym samym należy bardziej do dziedziny psychologii niż fizyki.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Jakikolwiek pomysł na przewidywanie przyszłości budzi w ludziach fascynację i jednocześnie wielki irracjonalny opór. Powoduje też klaustrofobiczny lęk przed fatum, z którym ludzkość zmaga się od czasów Edypa. W gruncie rzeczy ludzie nie chcą znać przyszłości.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Emocje zawsze są prawdziwe; nieprawdziwa może być ich przyczyna. Emocje wzbudzane przez fałszywe przyczyny są równie silne jak te powodowane przez prawdziwe, dlatego często wyprowadzają człowieka w pole. Trzeba je po prostu przeżyć.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Bóg jest w każdym procesie. Bóg pulsuje w przemianach. Raz jest, raz jest go mniej, ale czasem nie ma go wcale. Bóg bowiem przejawia się nawet w tym, że go nie ma.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Człowiek jest istotą głupią, która musi się uczyć. Dokleja więc do siebie wiedzę, zbiera ją jak pszczoła i ma jej coraz więcej, użytkuje ją i przetwarza. Ale to w środku, co jest „głupie” i potrzebuje nauki, nie zmienia się.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Kto raz widział granice świata, ten najboleśniej doświadczać będzie swego uwięzienia.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Ludzie – którzy sami są przecież procesem – boją się tego, co niestałe i zawsze zmienne, dlatego wymyślili coś, co nie istnieje – niezmienność, i uznali, że to, co wieczne i niezmienne, jest doskonałe.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Ludzie myślą, że żyją bardziej intensywnie niż zwierzęta, niż rośliny, a tym bardziej – niż rzeczy. Rośliny śnią, że żyją bardziej intensywnie niż rzeczy. A rzeczy trwają, i to trwanie jest bardziej życiem niż cokolwiek innego.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Młodość w swoim natężeniu, w swojej mocy, męczy się sobą. Którejś nocy czy któregoś poranka człowiek przechodzi granice, osiąga swój szczyt i robi pierwszy krok w dół ku śmierci.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Największym oszustwem młodości jest wszelki optymizm, uporczywa wiara w to, że we wszystkim jest postęp.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Nie ma nikogo takiego, o kim można by powiedzieć, że wymyślił młynek, tworzenie jest bowiem tylko przypominaniem sobie tego co istnieje poza czasem, czyli od zawsze. Człowiek nie potrafi stwarzać z niczego, to boska umiejętność.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "W niewiedzy, że się istnieje, jest wyzwolenie od czasu i śmierci.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Czasami, gdy Człowiek doświadcza Gniewu, wszystko wydaje się oczywiste i proste. Gniew zaprowadza porządek, pokazuje świat w oczywistym skrócie, w Gniewie powraca też dar Jasności Widzenia, o który trudno w innych stanach.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Historie życia nie są tematem do dyskusji. Powinno się ich wysłuchać i zrewanżować się tym samym.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Najlepiej rozmawia się samemu ze sobą. Przynajmniej nie dochodzi do nieporozumień.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Ranki zimowe zrobione są ze stali, mają metaliczny smak i ostre krawędzie. W środę o siódmej rano, w styczniu, widać, że świat nie został stworzony dla Człowieka, a na pewno nie ku jego wygodzie i przyjemności.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Smutek jest ważnym słowem w definicji świata. Leży u podstaw wszystkiego, jest piątym żywiołem, kwintesencją.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Więzienie nie tkwi na zewnątrz, ale jest w środku każdego z nas. Może jest tak, że nie umiemy bez niego żyć.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Wszystko przeminie. Mądry człowiek wie o tym od samego początku i niczego nie żałuje.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Z punktu widzenia natury nie ma istot pożytecznych i niepożytecznych. To tylko niemądre rozróżnienie stosowane przez ludzi.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Zdrowie jest stanem niepewnym i nie wróży nic dobrego. Lepiej jest być sobie spokojnie chorym, wtedy przynajmniej wiemy, na co umrzemy.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Parafraza Szekspirowskiego cytatu jak nigdy pasuje dzisiaj do tej kakofonicznej rzeczywistości: internet to coraz częściej opowieść idioty pełna wściekłości i wrzasku.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Czułam się tak, jakby jakieś niezależne siły zgłaszały swój akces do opisywanej przeze mnie historii, jakby sprzęgły się jakieś moce i niosły pomoc. Jakby światu zależało na napisaniu tej książki.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Katolicyzm nie sprzyja odwadze myślenia, eksperymentowaniu z ideami, jest zachowawczy i ostrożny. Zmiany w jego obrębie następują powoli i w sytuacji, kiedy już nie można dalej obstawać przy swoim. Taki klimat sprzyja dwóm filarom polskiej kultury religijnej – konformizmowi i hipokryzji.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "My, ludzie Zachodu, mamy wdrukowany leciutki odcień pogardy dla politeizmu jako czegoś bardziej prymitywnego, lecz można spojrzeć na to i tak, że w tej oszałamiającej różnorodności kultów wyraża się niepojęta dla człowieka natura sacrum.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Obraz naszej historii, który mamy w głowie, jest jak zamek z papieru. Wygląda imponująco, ale palcem można wywiercić w nim dziurę. Potrzeba nam więc historycznej herezji.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Praca jest najuczciwszym stosunkiem do rzeczywistości.", Author = "Olga Tokarczuk" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Olga_Tokarczuk", Text = "Zakazałabym używania pięknego słowa „solidarność” społeczeństwu, które odmówiło pomocy uchodźcom.", Author = "Olga Tokarczuk" },
        };
    }
}
