using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class StanisławJerzyLec
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "A może dopiero w świecie, który nie zna grawitacji, będzie opadanie na dno godne pogardy?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Bezmyślność zabija. Innych.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "I garderoba duszy ma swoje żurnale.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Cała rozpiętość natury! Od Kreatora do kreatury.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Gdyby jeszcze kozła ofiarnego można było doić!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wszystko zostało już napisane, na szczęście nie wszystko jeszcze pomyślane.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "A co by było, gdyby Bóg z żebra Adama zrobił drugiego Adama?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "A jakie było pytanie?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "A może szczęście ukrywa się pod jakimś pseudonimem.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ach, gdyby tak od razu, każdy zrozumieć mógł, że lepsza droga bez drogowskazów, niż drogowskazy bez dróg.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ale ta mała urosła! Kiedyś miałem ją blisko serca, teraz mam ją powyżej uszu!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Animowane trupy.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Antropomorfizacja bajek? Przy tym zezwierzęceniu człowieka?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Aureola oświetla wszystkie skazy urody.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Autor może popełnić samobójstwo celując w gust publiczności.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Bolesny jest poród człowieka, zwłaszcza gdy rodzi siebie sam w wieku dorosłym.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ból własnego nieistnienia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Byle smród co walczy z wentylatorem uważa się za Don Kichota.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ci, którym świat ucieka w przeciwnym kierunku, myślą, że wciąż idą naprzód.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ciosu się unika – nie przeciwnika!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Co nas trzyma na tym globie prócz siły ciążenia?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Co zostało z ekstaz i miłości – suche cyfry przyrostu ludności.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czasami ciemno od skrzydeł anielich.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czasem noce są zbyt ciemne, by je ujrzeć.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czasem odkrywamy pełni dumy jakiś dziewiczy ląd myśli. Ale w końcu widzimy gdzieś w lesie opakowanie środka antykoncepcyjnego.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czasem taki jest mecenat, że z pupila wkrótce denat.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Często trzeba powiedzieć nie, żeby siebie potwierdzić.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Człowiek się rodzi, choć mu to szkodzi.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy dusza po kretynie jest kierowana w ciało idioty jedynie?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy istniała kiedy kasta, która sobie rzekła: „Basta”?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy istnieje pojęcie większej połowy? Tak! To ta połowa, której tak półgłówkowi brak!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy jestem ateistą? Bóg jeden raczy wiedzieć.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy przyłączasz się do negatywnego środowiska?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Czy warto mijać się z prawdą? Tak, jeśli się ją wyprzedza.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Diabeł nie śpi z byle kim.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Dmijmy sami w nasze żagle.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Don Kichoci, nie walczcie z wiatrakami!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Do celu tam się wysiada.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Drakońskie pieszczoty.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Dwóch świadków trzeba dostać, aby móc bez świadków zostać.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Fakty wyobraźni.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Gdy nadchodzi świt, trudno walczyć przeciw nocy, która przyjdzie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Gdyby śmierć można było odespać na raty.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Geniusz nie chroni od nieszczęścia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Hipokrysus ducha.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Homo-szympans.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "I antysemitę można poznać po nosie. Węszącym.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "I ordery o siebie rozmaicie dzwonią.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ileż toastów spełnia się pełnym kielichem goryczy.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Im mniej ludzie mają zębów, tym są bardziej zgryźliwi.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Jestem w opozycji, dałem odpowiedź negatywną.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Już dawno eks, a wciąż ten seks…", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Jesteśmy coraz bliżej odkrycia Boga przez naukę. Drżę wtedy o Jego los.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Kat występuje zazwyczaj w masce – sprawiedliwości.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Kiedy znalazłem się na dnie, usłyszałem pukanie od spodu.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Klucz sytuacji często tkwi w zamku sąsiada.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Kobieta to tylko żebro Adama.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Liczby bezwzględne.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Lizusi są wierni. Gotowi twoją krew zlizywać z łap twego oprawcy.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ludzie mylą ustawodawstwa z prawodawstwem.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ludzie są sobie bliżsi, świat się przeludnia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Łamany kołem szczęścia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Łatwiej jest mieć kilka własnych książek niż jedno własne zdanie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Mądrości powinno być pod dostatkiem, któż z niej bowiem korzysta.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Mezalianse myśli.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Mężczyźni wolą kobiety ładne niż mądre, ponieważ łatwiej im przychodzi patrzenie niż myślenie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Mierz wysoko – wpajali mu wzniośli nauczyciele. Strzelił im w łeb.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Można być wirtuozem fałszywej gry.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Można się znaleźć na dnie nie osiągnąwszy głębi.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Mówi takimi banałami, że tylko podłożyć muzykę – a będzie przebój.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Największe poczucie humoru posiadają zmarli. Dla nich wszystko jest śmieszne!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nic nie mija bez echa, nawet cisza.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nie każdy, kto miewa sny, ma je gdzie śnić.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nie obiecujcie sobie zbyt wiele po końcu świata.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nie oddawaj czci tym, którzy ci ją zabrali.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nie opowiadajcie snów – a może przyjdą do władzy freudyści?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nie otwieraj drzwi takim, którzy je otwierają i bez twego pozwolenia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Niech sobie ten przypis przeczyta elita, że każda śmietanka na deser jest bita.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Niedobrze wierzyć w człowieka, lepiej być go pewnym.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Niejednego meteora czas upomnieć: „Przeszła pora!”", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Niektóre kalumnie brzmią dumnie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nigdy nie dyskutuj z głupcem – ludzie mogą nie zauważyć różnicy!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Nikt nie spojrzał prawdzie w oczy, bo ona ma tylko oczodoły.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "O losie człowieka decyduje człowiek.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "O pisowni. Nie masz morale bez ale.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "On nadaje się do tłuczenia kamieni filozoficznych.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Opinia publiczna powinna być zaalarmowana swoim nieistnieniem.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Otyli żyją krócej. Ale jedzą dłużej.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Paw ma dumę w ogonie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Pisarz X? Bóg mu nie dał talentu. On twierdzi, że nie przyjął, bo jest ateistą.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Płyń za rekinem – trafisz do ludzi.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Pod prąd własnej krwi płynąć najtrudniej.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Pomyśl, zanim pomyślisz.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Powiedz mi, z kim przestajesz, powiem ci, z kim zaczniesz.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Późno już. Świta.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Przekłady z wewnętrznego ja.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Przetrwać, przetrwać życie, potem damy już sobie radę!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Przez życie trzeba przejść z godnym przymrużeniem oka, dając tym samym świadectwo nieznanemu stwórcy, że poznaliśmy się na kapitalnym żarcie, jaki uczynił, powołując nas na ten świat.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Przywarli do siebie tak blisko, że nie było już miejsca na żadne uczucia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Racjonalizacja: żyjemy coraz dłużej i coraz mniej.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Rany się zabliźniają, ale blizny rosną wraz z nami.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Rasowy aktor, który pożegna scenę, do końca życia gra już tylko człowieka.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Remont wspomnienia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Rozpętał kalamburzę.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Salto morale jest bardziej niebezpieczne niż salto mortale.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Samozatrucie sobą.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Satyra zabija, nie obraża.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Serce mu uderzyło do głowy.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Sezamie otwórz się – ja chcę wyjść!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Sięgnąłem dna i usłyszałem pukanie od dołu.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Skarlałe zasady – zasadzki.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Słodkie życie słono kosztuje.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Szczęśliwi godzin nie liczą.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Tabliczka rozmnażania się.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Tam, gdzie uciska but, bez niego chodzi lud.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Tempo! Tempo! Można przejść życie w jednym dniu. Ale co zrobić z pozostałym czasem?", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ten, kto skacze z radości, powinien uważać, by grunt nie usunął mu się spod nóg.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ten, kto trzymał się kurczowo życia, może zginąć wraz z nim.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Tradycja – dziedziczne szlachectwo plagiatu.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Trzeba by stu oczu, by móc je na wszystko przymykać.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Trzeba wielu lat, by znaleźć przyjaciela, wystarczy chwila by go stracić.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Tyrani wiążą człowieka i w jego własnym sercu.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "W eufurii.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wchodź w siebie bez pukania.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wiele rzeczy, które nie mogą przejść przez gardło, ma się na końcu języka.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wiele rzeczy nie powstało z powodu niemożności ich nazwania.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wszyscy bogowie byli nieśmiertelni!", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wszystko mija, nawet najdłuższa żmija.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wyprowadził własne ślady w pole.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Wyrzutnie sumienia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Z cennika. Wtedy słowo w cenie, gdy płatne milczenie.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Z czego powstałeś zależy od genetyki, w co się obrócisz, od polityki.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Z doświadczenia ornitologów. Żeby pisarze mogli rozwinąć skrzydła, muszą mieć swobodę korzystania z piór.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Z opozycji można się wylizać.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Z żaru powstaje popiół lub dzieło.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Za dużo orłów, za mało drobiu.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Zaciekli krwią.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Zakochani z rozumu obrani.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Zanotował swą pustkę na tysiącu stron.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Zdanie to największa forma literacka.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Zero do zera i będzie kariera.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Ziemia to kropka pod znakiem zapytania.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Złamał sobie życie! I ma teraz dwa oddzielne, bardzo przyjemne życia.", Author = "Stanisław Jerzy Lec" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Jerzy_Lec", Text = "Żeby mieć tylu słuchaczy, co podsłuchujących.", Author = "Stanisław Jerzy Lec" },
        };
    }
}