using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class StanisławLem
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Nauka nie zajmuje się takimi własnościami bytu, do których należy śmieszność. Nauka objaśnia świat, ale pogodzić z nim może jedynie sztuka.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Pragniesz żyć, to jest posiadać przyszłość, która staje się teraźniejszością, do tego bowiem sprowadza się przecież życie.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wszystko, cokolwiek istnieje, bywa przedmiotem drwin. Nie ostoi się wobec nich żadna godność, wiadomo bowiem, że ten i ów śmie podrwiwać nawet z królewskiego majestatu.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Ignorancja nasza (ludzka) jest oceanem ogólnoświatowym, zaś wiedza pewna – pojedynczymi wysepkami na tym oceanie.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Internet nadal „nic nie rozumie”, żadnego odkrycia, choćby od niego zależał los świata, ale nadanego w egzotycznym języku, nie odróżni od nieco mniej ważnej wieści, że u ciotki w placku z jabłkami zrobił się w piekarniku zakalec.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Każda bez wyjątku nowa technologia ma awers korzyści i zarazem rewers nowych, nieznanych dotychczas bied.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Świadomość jest jak wiatr, o którym można powiedzieć, iż wieje, ale nie ma sensu pytać, gdzie jest wiatr, kiedy nie wieje.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Na szczyt można wejść, ale wszystkie drogi ze szczytu prowadzą w dół!", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Ludzie zbudują, mimo wszystkie zawody, klęski i tragiczne omyłki, lepszy świat. Gdybyśmy nie mieli działać z tą myślą, utracilibyśmy wiarę w człowieka i jego możliwości, a wtedy lepiej byłoby nie żyć, przyjacielu.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Mój przyjacielu, czyżbyś poczuł się dotknięty w swej ludzkiej godności? Dlaczego nie dotyka cię widok dźwigu 10 000 razy silniejszego od ciebie, a obraża cię obraz machiny 1000 razy od ciebie rozumniejszej?", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Duizm głosi, że każde życie zna dwie śmierci, przednią i tylną, to jest tę sprzed narodzin i tę po agonii.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Jak można się nie przekształcać, jeżeli można się przekształcać?", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Kiedy można być każdym i żywić dowolne przekonania, nie jest się już nikim i nie ma się żadnych przekonań.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Nie ma sprawiedliwości tam, gdzie jest prawo głoszące wolność najwyższą.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Przyroda postąpiła z nami jak łotr. Im kto bardziej w życiu zmądrzeje, tym bliżej do jamy.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Śruba, przykręcona we śnie, nie zmieni sytuacji, jaka panuje na jawie.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wiedza unicestwia stopniowo dyrektywy, zwane przykazaniami objawionymi. Pozwala ona zabijać, nie zabijając, niszczyć, lecz tak, że to niszczenie stwarza.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Zauważ, proszę, że świat zniewolony do samego dobra jest takim samym przybytkiem niewoli jak świat zniewolony do samego zła.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Astronautyka to czysty niepokalany płód ludzkiej ciekawości.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Na wszystko, co się zdarzy, masz gotowy, przywieziony z Ziemi schemat. Jeżeli jakiś szczegół nie pasuje, to go po prostu odrzucasz.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "W dziedzinie tej, jak w każdej w ogóle domenie poznania, ważne jest rozpoznanie tego, co stanowi już zdobytą wiedzę o badanym; lecz jeszcze ważniejsze bywa rozpoznanie tego, co stanowi odniesioną do badanego niewiedzę.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Gdyby ludzie od jaskiniowej epoki robili tylko to, co wyglądało na możliwe, do dzisiaj siedzieliby w jaskiniach.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wysoka technologia nie wyklucza wierzeń religijnego typu.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Poznanie jest zdobyciem pewności w jakiejkolwiek kwestii; otóż nie ma żadnego sposobu, który by mógł głód pewności zaspokoić, jeśli jest on tylko odpowiednio nieposkromiony.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Jednakowoż wiemy teraz na pewno, że gdy po planetach będą się przechadzali pierwsi wysłannicy Ziemi, inni jej synowie nie o wyprawach takich będą marzyć, lecz o kawałku chleba.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Ludzkość tak się rozmnożyła i zgęściła, że zaczynają nią rządzić prawa atomowe.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Jeżeli nie można odmienić prawdy, trzeba ją zasłonić. To ostatni jeszcze humanitarny, jeszcze ludzki obowiązek.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Odwrotna proporcjonalność liczby żyjących do wagi i godności indywidualnej egzystencji jest faktem.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Technocywilizacyjna działalność człowieka coraz silniej, a nawet coraz groźniej wpływa na klimat planety.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Większość fikcji beletrystycznych napisała mi się w tym rozumieniu sama, że pisałem, nie znając z góry ani fabularnego schematu, ani przebiegu akcji, ani jej miejsc węzłowych, ani wreszcie finału.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wolność nie oznacza wykorzystywanej szansy zaspokajania sprawiedliwie wyczuwanych potrzeb, ponieważ potrzeby są nam wmawiane i wciskane przez często anonimowe grupy wielkich inwestorów światowego kapitału.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wszystko jest znacznie bardziej skomplikowane, aniżeli zdolny byłby pojąć umysł człowieka, który stroniąc od eksperymentalnej nauki, pragnie się schronić w królestwie filozoficznego myślenia.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Do zagłady nie jest wcale potrzebna wojna, atomowa albo i nieatomowa, skoro doprowadzą do niej eskalacyjne koszty dalszych zbrojeń.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Kiedy stawka jest dostatecznie wysoka, prawo przestaje się liczyć.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Kiedy technicy nie wiedzą, co się dzieje, bogactwem słownictwa dorównują lekarzom przy konsylium nad beznadziejnym przypadkiem.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Kto sieje ewolucję, ten zbiera rozum. A rozum nie chce nikomu służyć.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Nie ma dobrej odpowiedzi na źle postawione pytanie.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Normalny człowiek jest istotą wysoce nielogiczną i w tym jego człowieczeństwo.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Postęp nigdy nie przychodzi za darmo.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Fantomatyka zdaje się stanowić swoisty szczyt, ku któremu zmierzają liczne techniki rozrywkowe współczesności.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Porównaliśmy cywilizację ekspansywną do gwiazdy supernowej. Jak gwiazda w eksplozji spala swoje zasoby materialne, tak cywilizacja zużywa rezerwy ludzkie w „łańcuchowej reakcji” lawinowego wzrostu nauki.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Przy całej bowiem nierozstrzygalności empirycznej istnienia desygnatów wiary, jej wartość przystosowawcza, jako źródła informacji uniwersalnej, nie ulega wątpliwości.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Systemy metafizyczne, czy to po wschodniemu mgliste i aforystycznie wieloznaczne, czy operujące po europejsku wykształconą logiką, zawsze są proste w zestawieniu z rzeczywistą złożonością świata.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Świat jest w pewnym sensie jak człowiek chory, który sądzi, że albo wnet wyzdrowieje, albo niebawem umrze, i nawet do głowy mu nie przychodzi, że może, kwękając, z okresowymi pogorszeniami i poprawami dożyć późnej starości.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Tak więc mózg fizjologicznie normalny może osiągać wyżyny doznań, zwanych mistycznymi, dopiero po przebyciu żmudnej drogi przepisanych określonym rytuałem zabiegów, albo też, wyjątkowo i rzadko, we śnie.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Tylko w powieści przed słowem „koniec” losy bohaterów nieruchomieją w figurze napawającej autora estetycznym zadowoleniem.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Żadna religia nie może nic uczynić dla ludzkości, ponieważ nie jest wiedzą empiryczną. Zmniejsza ona, owszem, „ból istnienia” jednostek, mimochodem zaś powiększa sumę nieszczęść trapiących ogół, właśnie przez swoją bezradność i bezczynność w obliczu problemów zbiorowości.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Perfekcja, pełnia, doskonałość – to rzadki wyjątek, zdarzający się tylko dlatego, że wszystkiego jest tak niesłychanie, niewyobrażalnie wiele!", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Religia, filozofia są klejem, wciąż składamy i zbieramy rozpełzające się w statystykę ochłapy, żeby je złożyć w sens, jak w dzwon naszej chwały, żeby odezwały się jednym, jedynym głosem!", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Jakże nie nadaje się ciało ludzkie do nieskończoności, jakie bezradne się w niej staje, każdym poruszeniem swoim objawia swój bezsens, pozbawione zbawczych ograniczeń i usprawiedliwiającego oporu ziemi, ścian, stropów.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Utyskuje się dziś na powszechne obniżenie lotu sztuki, tkniętej trądem bezideowości, skazanej niewiadomymi wyrokami na miałkość przemijających eksperymentów i jednodniowej mody.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Jak wiadomo, wydawcy nie boją się niczego tak jak wydawania książek, gdyż w pełni już działa tak zwane prawo Lema: „Nikt nie czyta; jeśli czyta, nic nie rozumie; jeśli rozumie, natychmiast zapomina”.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Kiedy wszyscy są wariatami, nikt nie jest wariatem.", Author = "Stanisław Lem" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stanisław_Lem", Text = "Wydelikaciła nas cywilizacja jak jagódki cieplarniane: pulchniśmy, rumiani, niezahartowani dostatecznie, nieuwędzeni w dymie diabelskim!", Author = "Stanisław Lem" },
        };
    }
}
