using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class StefanŻeromski
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Chłopy polskie – to tchórze nad tchórzami.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Człowiek mądry nie uważa śmierci za rzeczywistość godną myślenia. Przedmiotem myślenia filozoficznego może być tylko życie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Jak kwiat człowiek powstaje i skruszon bywa…", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Kiedy mogę przyczynić się, żeby w człowieku dobro się objawiło, no to przyczyniam się. Mam chyba, do diaska, po temu prawo! Nie sprzeciwiam się dobru. Dobru – słyszysz? Bo to nieprawda, żebyśmy absolutnie nie wiedzieli, co jest dobro. My wiemy, że jest dobro. Wiemy, że stoi ono wyżej niż piękno.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Przyszła jej do głowy dziwna myśl, po co też taki „gad” żyje na świecie? (…) Gdyby mu powiedzieć: – Jaśniachu, Jaśniachu, kocham cię! – zastanowiłby się z pewnością, przede wszystkim, czy on ma prawo kochać się, a następnie, czy już wszyscy ludzie także kochają, a dopiero na końcu, czy mu to nie zaszkodzi na kaszel i system nerwowy.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Ani chwili tracić darmo nie wolno!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Czyż to nie wielkość ducha, aby nie cofnąć ręki przed tym, od czego ludzie uciekają z całej siły?", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Dziś coraz bardziej rozwijająca się myśl usuwa po trochu wszystkie niedorzeczne fantazje, a na ich miejsce wprowadza kwestie rzeczywiście filozoficznej wartości i każe wróżyć wiele o myślicielu już w osiemnastym roku.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Ekscytacje rodzą ekscytacje i padam w „delirium tremens” – marzenia.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Kobieta pozwoli ze sobą zrobić, co zechcesz, bylebyś jej o tym nie mówił.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Kochając, marzy się o przyszłości – ja wspominam przeszłość.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Ludzkość musi przejrzeć – musi! Głupota średniowieczna wiecznie trwać nie może – to nie podobna!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Marzenia moje przyjdą więc może do skutku: choć okruszyną uznania wypłacą mu się może przecie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Myśl wielka, a mianowicie stosująca się do posłuszeństwa względem starszych i rodziców, ukryta jest w formie bajki; całe życie człowieka lekkomyślnego przeprowadzone jest pod obrazem nieposłusznego radom ojca młodzieńca.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Najmniej znacząca dla innego okoliczność mnie o sercowe łzy przyprawia.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Obejdę świat dookoła, a może zabiję bijące mnie serce – kalejdoskoskie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Poeta pisze dla siebie, bo jeżeli pisze dla ludzi, poetą nie jest; jest nim wówczas, gdy jest i filozofem zarazem, gdy twory jego są potrzebą ludzkości, a jeżeli tworzy tak sobie – to jest samolubem, niczym więcej, gdy ze smutków tylko chwali się przed światem!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Po mowie jest na świecie potęgą największą – milczenie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Przyjaźń wygląda przy uczuciu do kobiety jak świeca łojowa przy świetle elektrycznym.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Są chwile, że wszystko na mnie uderza, wszystko się łamie w rękach, wszystko zawodzi. Skądś niespodzianie zjawiają się bóle i targają serce.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Szczęście moje mieści się w wyrazie: wolność. Gdybym teraz odebrał sobie życie – nikt nie uroniłby po mnie łzy żalu.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Walka z miłością to walka niemal z życiem, bo miłość jest życia rdzeniem.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "My, lekarze! My, sól ziemi, my, rozum, my ręka kojąca wszelką boleść...", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Kto zmaga się ze światem, zginąć musi w czasie, by żyć w wieczności.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Bo czyliż najnędzniejszy ze wszystkich, najlichszy kwiatuszek może się rozwinąć w lodowni?", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Tęsknota, tęsknota… Uczucie najbardziej niewypowiedziane, stan próżny wszelakiej ulgi, ucisk serca ciągły i jednostajny.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Złe niewątpliwie jest tylko jedno: krzywda bliźniego. Człowiek – jest to rzecz święta, której krzywdzić nikomu nie wolno.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Polska nie dlatego powstała, żeby w niej stara nędza, jak za czasu najeźdźców, nadaremnie krwawe łzy lała. Polska nie dlatego powstała, żeby dygnitarz cywilny lub wojskowy, pędząc w automobilu, obryzgiwał dziadów i żebraków, wtulonych w każde załamanie muru stolicy państwa. Polska nie dlatego powstała, żeby w jej granicach miała swe rozpostarcie burżuazyjna fabryka paskarstw, szwindlów i oszustw. Polska odrodziła się z krwi i pracy męczenników po to, żeby na miejscu, gdzie stała ciemnica niewoli, rozpostarło się najjaśniejsze pracowisko postępu.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Pragnąc odnaleźć idealnie polską, to znaczy możliwie najbardziej wolną od wpływów zewnętrznych gwarę – macierz, należałoby szukać jej nie na pograniczu, lecz właśnie w głębi, niejako w łonie macierzystego kraju. Należałoby wynaleźć w Polsce krainę, położoną z dala od wszystkich granic, a więc od wpływu niemieckiego, czeskiego i ruskiego, iście słowiańską od samego początku, wreszcie nie obfitującą w miasta i mało uprzemysłowioną. Takim krajem, według mojego rozumienia, będzie obręb terytorium, na którego jednym krańcu leży miasto Opatów, na drugim miasteczko Przedbórz, – na północy Iłża, na południu Stopnica. Jest to mniej więcej obszar gór i lasów świętokrzyskich. Okolica ta ma – w przeciwieństwie do Tatr – wszystkie stopnie rozwoju: pasterski (jaki mają Tatry), leśny w okolicy samych Łysogór, rolniczy, ogrodnictwo, wysoko postawione na południowem zboczu gór świętokrzyskich (w Bielinach, Słupi, Porąbkach, Krajnie), kopalnictwo rud żelaza, miedzi, marmurów w Miedzianej Górze, Karczówce, Chęcinach, Suchedniowie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Prawdę swą należy mówić głośno, nie schlebiając ani – żal się Boże! – gwelfom i gibelinom polskim, ani rzeczom, ani wypadkom, ani stosunkom, ani ideom.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Gdybyś kiedy we śnie poczuła, że oczy moje już nie patrzą na ciebie z miłością, wiedz, żem żyć przestał.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Nauka jest jak niezmierne morze… Im więcej jej pijesz, tym bardziej jesteś spragniony. Kiedyś poznasz, jaka to jest rozkosz… Ucz się, co tylko jest sił w tobie, żeby jej zakosztować!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Trza było skazać na śmierć tę miłość, od której serce pęka, jakby zbielałem w ogniu żelazem wypalić wszystko aż do ostatniego wspomnienia.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Była w tej pani jakaś cecha otwartości, która nakłania do uczuć przyjaznych.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Cezary jeszcze się w nikim nie kochał, ale wiedział, że taka pozycja istnieje i jest w modzie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Gdzież są twoje szklane domy?", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Każdy ma swoje miejsce ulubione w dzieciństwie. To jest ojczyzna duszy.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Każdy z nich miał gdzieś jakąś „mamę” albo jakiegoś „tatę”. Byli tacy, co mieli nawet babcie, a prawie każdy na postoju w chwili, kiedy sądził, że go nikt nie widzi, ośliniał sekretnie jakąś fotografię — ach! — jej, Kazi albo Zosi. Cezary nie miał ani jednej Zosi.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Nie będzie już przenigdy Prusak niemczył Kaszuby!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Polecił tłumaczowi, żeby powiedział Kaszubie, iż podoba się panu jego opowieść.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Mówiąc i pisząc jedynie we własnym języku, nie zwracamy żadnej uwagi na nazwę przedmiotów, na historię rzeczowników, która niejednokrotnie sięga zamierzchłych czasów, na dostojność i, niejako, moc tajemniczą wyrazów. Są one dla nas powszednie i zdeptane, jak bruk i piasek drogi. Skoro zaś zajdzie potrzeba myślenia w jednej, a pisania w innej mowie, wyrazy dźwigają się ze swego poniżenia, mienią się, wiążą i, niejako, przechwalają, pokazując swą dostojność. Stąd wypływa konieczność szukania synonimów, dobierania nazw i strojenia inaczej wyrazów. Język zabarwia się i lśni niepowszednio, niezwykle, zgoła inaczej.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Nadszedł już piękny miesiąc maj… Wiosenna zieloność okryła rany poszarpanej ziemi. Pióra, liście, szypułki, pokrętne badyle i wielorakie odmiany barw osłoniły rany ziemi i zalecały się oczom ludzkim. Podobnie jak wsysały w siebie wilgoć i zgniliznę, tak sami barwami, kształtem i nieskończoną potęgą swego rozrostu chciały wessać w siebie cierpienie dusz, zniszczyć pamięć o tym, co już padło i umarło. Na dobro nowego życia rosło i bujało wszystko – na stratę śmierci. Słowik śpiewał nocami nad wodą, w sąsiedztwie wzgórka, pod którym Hubert Obromski znalazł schronienie.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Szczęście nie znosi za sobą pościgu. Napastowane – odwraca się i zaczyna prześladować napastnika.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Trzeba rozrywać rany polskie, żeby się nie zabliźniły błoną podłości.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Im kultura niższa, tym naśladownictwo bardziej rozwinięte.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Jestem inny, inny, inny. Trochę mi nawet żal dawnego łotra, który jeszcze dwa lata temu jednego wieczora szedł na schadzkę z panią Anielą, drugiego z panią Natalią, a w południe całował w lesie pannę Stasię. Dziś by mi się już tego wszystkiego nie chciało – daję na to znowu słowo honoru.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Łańcuch niewolniczy pokochasz po roku, spokojny kąt i dobrych ludzi po miesiącu.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Na pięść, jako argument, bywa też pięść argumentem.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Naród żyje, tworzy, pracuje, sięga tam, „gdzie wzrok nie sięga” – wtedy jedynie, gdy w nim kipi żądza swobody, gdy go nurtuje od piwnic do poddaszy lawa miłości rodzinnej ziemi. W jarzmie się tylko zdycha. Przyprawcie pracy organicznej skrzydła, którymi niech leci do niepodległości – wtedy wam uwierzę. Bez nadziei niepodległości jesteśmy żołnierzami, co nie myślą być generałami.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Piękno życia jest tylko w pracy.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Przydałoby się mniej ''Te Deum'', a więcej oleum.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Teatr Narodowy winien mieć na oku te szerokie masy inteligencji spracowanej wielkiego miasta, która wszystkiego pożąda umysłem zgłodniałym i sercem spragnionym, a która „nigdzie nie jeżdżając, tu się pasie na dziedzinie, jako w lesie zając”. Nie znaczy to wcale, że ma on być teatrem popularnym. Teatr Narodowy winien dawać dzieła wielkiego natchnienia, swoje przede wszystkim, a jeśli swoich nie stanie, obce dzieła geniuszów. Dzieł dramatycznych polskich nie bardzo starczy – dzieł dramatycznych polskich, które by nowoczesnego człowieka do teatru siłą niewoliły, a odwracały od obcej rewolucyjnej trucizny…", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Oświadczam krótko, iż nigdy nie byłem zwolennikiem rewolucyi, czyli mordowania ludzi przez ludzi z racyi rzeczy, dóbr i pieniędzy – we wszystkich swych pismach, a w ''Przedwiośniu'' najdobitniej, potępiałem rzezie i kaźnie bolszewickie. Nikogo nie wzywałem na drogę komunizmu, lecz zapomocą tego utworu literackiego usiłowałem, o ile to jest możliwe, zabiec drogę komunizmowi, ostrzec, przerazić, odstraszyć.", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Żałuję dziś bardzo, że nie umiem matematyki. Jest to nauka piękna – ja nie umiem uchwycić przewodniej myśli, jaka się śród formuł przewija. […] Umiem tylko i lubię arytmetykę. Do reszty – mam łeb tępy jak karp!", Author = "Stefan Żeromski" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Stefan_Żeromski", Text = "Życie jest trudną lekcją, której nie można się nauczyć. Trzeba ją przeżyć.", Author = "Stefan Żeromski" },
        };
    }
}