using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class SławomirMrożek
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ateista jest bezbronny wobec wierzącego, natomiast wierzący nie jest bezbronny wobec ateisty. Ateista musi udowadniać, co jest zajęciem samo w sobie trudnym, ulegającym niepewności, natomiast wierzący ma tylko piękne, czyste, swoje: ja wierzę, i nic do dodania.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Dlatego kobiety są „bezmyślne”. Nie muszą bowiem myśleć, bo one same są wnioskami z myślenia, przyzwoleniem.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ja smukle prosty. Moja sytuacja to jakieś pół drogi do uświadomienia sobie, że człowiek jest przeraźliwie sam wobec wszystkiego, z czego może wyniknąć albo wielki strach, albo wielka siła i niejaka swoboda.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nikt nie może ścierpieć podejrzenia, że o nic nie chodzi i, że nic nie wyniknie. Czy można szukać sensu nie wierząc w jego istnienie?", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Świat przeszkadza mi w życiu.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Tłumaczyć podwójność czy potrójność, po prostu wielorakość postaci względnością półsnu, zrozumiałą o piątej nad ranem…", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Właściwie nie wiadomo, co to znaczy dzień stracony czy nie stracony. Wszystkie są chyba tak samo nie stracone jak i stracone.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "„Wszystko jest coraz bardziej za późno”. Chociaż to zdanie jest może błędne nie tylko logicznie, językowo, ale naprawdę za późno może być tylko raz, w ciągu jednej sekundy, a potem już zawsze.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ale czy znajdziesz drugie takie miejsce, gdzie sąsiad byłby dokładnie w tej samej sytuacji co ty? Gdzie panuje podobna równość? Nigdzie. Nic nie szkodzi, że jest to równość w upodleniu, najważniejsze, że jest autentyczna, wyraźna, a nawet przejaskrawiona, karykaturalnie ekspresjonistyczna.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Będziesz miał piękne życie, pełne nadziei, tęsknoty i złudzeń. Nie każdemu jest to dane.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ci, którzy nie powinni mówić, mówią. A ci, którzy mogliby nie powiedzieć, nie mają nic do powiedzenia.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Do zwyczajnej nieuczciwości dodałeś nadzwyczajną bezczelność.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Istna kwadratura koła. Żeby wykorzystać moją jedyną szansę – utraciłem ją. Uciekłszy, przestałem być niewolnikiem. Rozrzedziłem się, rozpłynąłem w wolności.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Praca da chleb, a prawo wolność, bo wolność będzie prawem, a prawo wolnością.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Przesada jest w złym guście, przesada jest cechą ludzi z awansu.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ty możesz tylko na kanapie leżeć i mówić kazanie z kanapy. Apostoł kanapowy. Święty Szymon kanapnik.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = " (…) artysta nic nie ma i nic mieć nie może ze swojej sztuki. Nic w kategoriach uciech i światowych satysfakcji jako głównej rekompensaty. Nawet jeżeli jego sztuka przynosi mu sławę i pieniądze… Ma się, ale jak by się nie miało. Zazdrośnicy mogą spać spokojnie.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Czas jest zawsze aktualny.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Dlaczego wymieniliśmy słowa bogate na ubogie? Jeszcze mówimy radość, ale już powinniśmy mówić: euforia… Smutek i radość są stanami duszy… Teraz z duszą kiepsko. Pozostała nam tylko fizjologia, więc mamy już tylko depresję.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Gdyby nie odrobina hipokryzji i odrobina ślepoty, nikt by nie mógł funkcjonować i nikt by nie przeżył nikogo.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Humor czarny, zielony czy w kropki, podobnie jak literatura, grafika, teatr, film czy cokolwiek innego w tym rodzaju – nic mnie nie obchodzi. Obchodzi mnie wyłącznie świat i życie, ponieważ ja sam jestem światem i życiem.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ilość i pośpiech nie są przyjaciółmi artysty.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Im jestem starszy, tym bardziej chce mi się śmiać i tym mniej się śmieję. Zaś dowcipów nie opowiadam prawie nigdy.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Kiedy wiesz, że musisz napisać arcydzieło, wtedy prawie na pewno go nie napiszesz.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nawet lew wiedział, co robi, kiedy pokochał świętego Hieronima za to, że święty Hieronim wyjął mu z łapy cierń.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nic lepszego człowiek nie może zrobić człowiekowi, niż uwolnić go od bólu, i nic gorszego, niż mu ból zadać.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nie można dostrzegać nie widząc, ale można nie dostrzegać widząc. To jest codzienne doświadczenie naszego wzroku i percepcji.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nie wiem, czy był szczęśliwy, i sądzę, że również nie rozumiałby takiego pytania, gdyby mu je zadano. Ale wiem z całą pewnością, że jako dziecko bardzo lubiłem z nim przebywać. Gdyby był nieszczęśliwy, nie miałby takiego, ale stałego światełka, które sprawiało, że dobrze było, kiedy on był.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Tłumy jednostek szukają proroka, ale najczęściej znajdują Führera.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Wola sama w sobie nie ma kierunku, to intencja nadaje woli kierunek.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ze wszystkich fizjologicznych substancji nieprawdziwa w teatrze jest tylko krew.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Krokodyle są lepiej wychowane od ludzi. One tylko patrzą, nie zadają pytań.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nie można dojść do czegoś, od czego się nie zaczyna, ani w jedną, ani w drugą stronę. Zawsze na początku jest coś z tego, co i na końcu, obojętne, od której strony się zaczyna i w której się kończy.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Wie pan, dlaczego zginie Rosja? Bo nawet dekadenci chcą żyć.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Siekierkę – zamienię natychmiast na kijek. Zgłoszenie pod: Stryjek.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Czyściutkie ubranko z kołnierzykiem, haftowany kaftanik bezpieczeństwa.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Kruche jesteście, więc dotknę was siekierą. Pięknie śpiewacie, więc wam poderżnę gardło. Drogocenne jesteście, więc was zniszczę.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Lekarze nie dają mi więcej życia, niż dopóki nie umrę.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Bunt to postęp w fazie potencjalnej.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Jestem człowiekiem myślącym głębiej. Człowiek nie może żyć bezmyślnie, na zasadzie mechanicznych odruchów.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nam już nie formy trzeba, ale żywej idei.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Bo dlaczego właściwie człowiek ma tylko odczuwać, a nie myśleć, lub odwrotnie, dlaczego zdolność odczuwania ma oznaczać zanik zdolności rozumowania i odwrotnie, dlaczego człowiek ma być albo wzruszonym debilem, albo kalkulującą kłodą? Dlaczego ma, kiedy – po pierwsze – nie może?", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Jeżeli wojna zdarzyła się tylko po to, żeby zatrząść moim dziecinnym światopoglądem, to dziękuję, gruba przesada. Coś mniejszego by wystarczyło w zupełności.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Zrozumiałem, że gdy się raz odejdzie, nie ma już prawdziwego powrotu. To dotyczy wszystkich sytuacji tego typu.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Chłopiec jeszcze nie wie, że pojedynek jest z góry przegrany. Fala ma do dyspozycji to, co się nazywa wiecznością, kiedy czas Chłopca jest ograniczony.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Dzięki ci Boże. Nawet jeśli zesłałeś mi złudzenie, jestem Ci za nie wdzięczny. Ale nie, złudzenie jest grzechem, a Ty nie wodzisz na pokuszenie sługi Twego. Oddaję się Twojej opiece.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "I pamiętaj, żebyś już nie robił głupstw. Śmierć to nie jest zabawa dla chłopców w twoim wieku.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Człowiek myśli sobie to i owo, ale jednak najczęściej to.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Człowiek wytworny nie mówi „chamstwo”. Mówi „kontr-kultura”.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Denerwuje mnie to, że nie mogę przestać być patriotą.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Gdy dokucza mi nuda, wspominam czasy, gdy byłem rewolucjonistą.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Głupota jest zawsze wystarczająca, mądrość nigdy.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Jestem zdania, że za długo żyję. Powoli, ale coraz prędzej zamieniam się w coś nieokreślonego.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Jeśli prawdą jest, że wieczność zamyka się w jednej nieskończenie krótkiej chwili – a nie ma dowodów, że tak właśnie nie jest – to aktor na scenie jest bliżej nieskończoności niż budowniczy piramid.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Jutro to dziś – tyle że jutro.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Kiedy człowiek jest młody, próbuje wyprzedzić świat. Potem zaledwie dotrzymuje mu kroku, aż wreszcie zaczyna być przez świat wyprzedzany.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Ludzie dobrze wychowani unikają mówienia oczywistości.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Mądry, kto błędy swoje dostrzega.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nawet sprzeciwiać się życiu, dyskutować z nim, udowadniać życiu jego bezsens – nie można inaczej, tylko żyjąc.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nie ma takiego głupstwa i nikczemności, które, byle stale powtarzane, nie zostały wreszcie przyjęte i przestały razić jako głupstwo i nikczemność.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Nie płacz nad czymś, co nie płacze nad tobą.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "„No to co?” jest pytaniem kretyna, na które nawet mędrzec nie zna odpowiedzi.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "„Poznaj samego siebie”. A co potem?", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Polacy to też murzyni, tylko biali.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Profesjonalista.", Author = "Sławomir Mrożek" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Sławomir_Mrożek", Text = "Uprzejmie donoszę, że mój sąsiad nie donosi. Sławomir Donosek.", Author = "Sławomir Mrożek" },
        };
    }
}