using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class TadeuszKonwicki
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Gdzieś tam na trzęsawiskach, na rozstajach małej jak atom ziemi, umierają ludzie i konają przedwcześnie nieszczęśliwe narody… Serce kosmosu bije na alarm.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Moje życie, albo cudze. Najpewniej jakieś wymyślone. Ulepione z lektur, niespełnień, starych filmów, niedokończonych wojen, zasłyszanych legend, niewyśnionych snów. Moje życie. Kotlet z białka i kosmicznego pyłu.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Ziemia, totalny rozpad. Nieustanna wieczna agonia. Rozwlekła śmierć. Planeta śmierci.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Polak, jak ponarzeka, zaraz zdrowszy.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Polak, jak widzi balkon, to chce skakać.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Dzisiaj sukces łatwo przychodzi i jeszcze łatwiej odchodzi.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Inteligencja jest matką humoru.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Przyjaźń to strach przed samotnością, a miłość to jeszcze większy strach przed osamotnieniem.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Całe życie żyliśmy jakby na walizkach. Tysiące przejść, niepewności, załamań. Ciągła prowizorka, tymczasowość, byle do jutra. A kiedyś zacznie się prawdziwe życie. No i masz. Przychodzi starość i gdzie to prawdziwe życie?", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Przeznaczeniem inteligentnego człowieka jest samotność.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Właściwie to nawet trochę żałuję, że udałem się jakoś taki, że dużo wiem, i prawie wszystko przemyślałem. Co z tego mam? Nic. Tylko zniechęcenie.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "piszę przede wszystkim dla czytelnika, z zamiarem zrobienia mu przyjemności, zabawienia go, złomotania lub zniszczenia. Aby pisać, muszę mieć drugiego człowieka.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Praca w filmie jest wyczerpująca psychicznie. To jest sprawa nieustającego napięcia. Dotyczy to i reżysera, który pracuje w stanie histerii, i wózkarza, który wozi kamerę. To się bierze stąd, że trzeba zarejestrować geniusz chwili, moment, kiedy praca 50 ludzi osiągnie moment szczytowy.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "skrót jest w nas. Ten nieprawdopodobny niesamowity skrót.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "takie było stare polskie przysłowie: krowa, która głośno ryczy, mało mleka daje. Przecież ja, widząc te histerie, euforie patriotyczne, wiem, jak to w momencie tragicznym się kończy. I życzę tym, którzy tę nic niekosztującą histerię pobudzają, żeby ich los nie wypróbował.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Ja w ogóle nigdy nie czytałem po wydaniu swojej książki i nigdy nie widziałem na ekranie kinowym swojego filmu. Ktoś może na to powiedzieć: „No dobrze, ale ja pana widziałem na jakiejś premierze”. Tak, przychodziłem na premiery, grzecznie się kłaniałem i jak tylko gasło światło, uciekałem. To wynika z pewnych moich cech charakteru, z wychowania wileńskiego, w którym asceza, powściągliwość i rodzaj honoru były obowiązujące. Toteż za bardzo nie wiem, czy tom z okładką zapowiadającą moją książkę to naprawdę moja książka.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Piszę książki i realizuję filmy o sobie. Innymi słowy opisuję siebie w trybie warunkowym, czasie zaprzeszłym niedokonanym albo przyszłym. Stwarzam sytuacje, w których tak lub inaczej się zachowałem, mógłbym się zachować, a także wyrażam żal, że się nie zachowałem.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "ten wybuch totalnej demokracji, to szaleństwo uwięzione w dodatku poprawnością polityczną, która wszystko dopuszcza, na wszystko zezwala, jest jakimś rodzajem odruchu histerycznego, reakcji na to, co przeżyliśmy podczas II wojny światowej, na ten szok, jaki ludzkość przeżyła, ludzkość moich pokoleń, szok zawalenia się wszystkich wartości, zawalenia się całej tej gigantycznej budowli humanistycznej wznoszonej przez wieki. Coś wstrząsającego: nagle nastąpił Holokaust i wszystko się zawaliło, wszystkie wartości poszły w błoto. Dziedziczy się w genach, nawet poza czystą chemią, pewne klimaty moralne, myślowe, duchowe.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "W 68 roku elita nasza była gotowa oddać życie za każde przedstawienie ''Dziadów'', a w dwadzieścia dwa lata później już na ''Lawę'' mało kto przyszedł.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Bo jesteśmy wolni. Nie czuję się odpowiedzialny. (…) ja w jakiś sposób dręczyłem się odpowiedzialnością za PRL, w który się włączyłem. I być może to mną kierowało. Teraz jesteście wolni. Możecie wszystko robić i wszystko robicie, co chcecie.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Często nie wiadomo jak się nazywa, nie wiadomo gdzie pracuje, nie wiadomo czy jest żonaty, czy ma dzieci, czy żona choruje, czy ma kłopoty w pracy. Czy ma pieniądze czy nie ma pieniędzy. W naszym życiu nieważne było co się zje i gdzie się tam 5 zł zarobi. Byliśmy przymuszani do wyborów, nawet bym powiedział (…) do trudnych wyborów. Trzeba było znaleźć się w świecie, którego ja nie stworzyłem.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Ja tak spontanicznie rzucałem się na ten swój tapczan i po nocach pisałem. Pisałem z jakiejś potrzeby. Czułem, że powinienem ślad swojej egzystencji, swojego pobytu tutaj zostawić. Nie wiem dla kogo. Może dla nikogo.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Kabotynizm u nas jest najdroższą wartością. Polityk-kabotyn, który tęgo narozrabia, za karę zostaje świętym. Artysta-kabotyn zyskuje miano natury nieprzeniknionej i wzniosłej. Z rąk kabotyna nawet socjalizm zostałby u nas przyjęty entuzjastycznie.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Można mnie zapytać: słuchaj czy ty żałujesz tego okresu, zaangażowania? Nie wiem czy ja żałuję. Dlatego, że patrząc na życie, na naszą egzystencję… Błędy są czasem korzystne. Błędy człowieka wysubtelniają. Czynią go bardziej uważnego na otoczenie, na świat. Nie popada człowiek w demagogię, zadowolenie z tego, co sobie wymyślił (…). Błędy uczą nieufności do siebie i do świata.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Można się obawiać, że taki literat cały czas kreuje siebie, nie jest szczery. Dopiero na podsłuchach jest szczery. Otóż moim zdaniem każdy piszący, chce czy nie chce, całą prawdę o sobie powie.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Teoria najbujniej pleni się na ugorach.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "W życiu zdarzają się niesłychane przypadki i sam pamiętam, jak mi opowiadano, że pewien rolnik, rzucając grabiami w nisko lecący samolot niemiecki, zestrzelił sztukasa dlatego, że po prostu ugodził grabiami w oko lotnika i samolot spadł. To się może wydać czymś nieprawdopodobnym, ale taka historia mogła się zdarzyć właśnie tylko w Polsce. W czasie wojny działy się rzeczy najbardziej dziwne, a my – jako Polacy – jesteśmy najbardziej upoważnieni do tego, ażeby o tym temacie najwięcej powiedzieć.", Author = "Tadeusz Konwicki" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Konwicki", Text = "Z jakiś moich kompleksów z dzieciństwa, z młodości, dość uważnie słuchałem jak mnie pouczono. Wszyscy mnie chcieli wychowywać. W '56 roku byłem wstrząśnięty jak ci, którzy mnie szturchali, wymyślali mnie od zgniłych inteligentów, od nierozumiejących historii, od przygłupów, nagle powiedzieli: a tyś w to wierzył wszystko? Nagle zrozumiałem jedną rzecz – muszę sobie ufać. Patrzeć właśnie z przekorą, sceptycznie na to, co mi z wybałuszonymi oczami przejęci wmawiają, zmuszają do czegoś.", Author = "Tadeusz Konwicki" },
        };
    }
}