using System;

namespace StdbModule;

public static partial class PolishQuotes
{
    public static class TadeuszBoyŻeleński
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Gdziekolwiek wyłoni się paląca kwestia, w której ludzie głowią się i radzą, co czynić, aby na świecie było trochę lżej i trochę jaśniej, natychmiast wysuwa się złowroga czarna ręka i rozlega się grzmiący głos: „Nie pozwalamy! Nie wolno wam nic zmienić, nic poprawić. Wszystko musi zostać po dawnemu; niczego tknąć nie pozwolimy z gmachu ciemnoty i ucisku. Ktokolwiek chciałby ulżyć doli człowieka na ziemi, sprzeciwia się prawu Boga, sprzeciwia się woli bożej”. (…) Nie mogę uwierzyć, aby wola boża miała być zawsze i wszędzie układna wobec bogaczy, a bezlitosna dla biedaków; aby osłaniała swym płaszczem kłamstwo, okrucieństwo i chciwość.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Jeżeli Sienkiewicz w Potopie porównał Rzeczpospolitą do postawu czerwonego sukna, które sobie wydzierają królewięta, to dziś można by powiedzieć, że wszystkie bez wyjątku partie wydzierają sobie czarną połę sutanny.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Każdy rząd w Polsce, chce czy nie chce, będzie się uginał pod naciskiem kleru, dopóki ciemnota lub bierność ogółu będzie czyniła ten kler realną czy fikcyjną potęgą. Dopóki w Polsce będzie można wykrzykiwać wzniośle „Bóg i religia”, tam gdzie w gruncie chodzi o władzę i pieniądze – dopóty kasta wyodrębnionych z życia dzikusów będzie regulatorem najdonioślejszych spraw społeczeństwa, a jego największą szkodą.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Trzeba się dziwić bierności, z jaką społeczeństwo oczekuje, co – bez jego udziału – zdecyduje ktoś o jego losie i w czym potem bezradnie tkwić będą całe pokolenia.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Mówili o niej bógwico, Że jest tylko półdziewicą.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Ojciec najgorsze wyrazy Powtarzał po kilka razy.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Oto jak nas, biednych ludzi, Rzeczywistość ze snu budzi.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Pamiętajcie, drogie dziatki, Nie żartować z ojca, matki, Bo paraliż postępowy Najzacniejsze trafia głowy.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Pełna wrzasku ziemia polska Od Czikago do Tobolska.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Takie ma kobieta szanse, Gdy się z wieszczem wda w romanse. A niech która się odważy Zerwać nici tych szantaży, Śluza przekleństwa się otwiera: „Puchu marny” et cetera!", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Więc choć świat biada: «lepiej wcale nie żyć» I pesymizmu słychać zewsząd jęk, Najmilsi bracia, zechciejcie mi wierzyć, Życie jest piękne, życie ma swój wdzięk.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Z kobietami trzeba twardo, A nie cackać się z pulardą.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Z tym największy jest ambaras, Żeby dwoje chciało naraz", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Życie ludzkie na pozór to zwykły kawał, lecz on nie jest tak prosty, jak by się zdawał.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "A to czysta wariacja ta demokracja.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Arcydzieła minionych epok mają to do siebie, że trzeba się nauczyć je czytać.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Dawniej ludzie mniej mieli kultury, lecz byli szczersi.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Doprawdy, kiedy poeci bujają w obłokach, to jest w porządku, ale kiedy belfry przypną sobie skrzydła i zaczynają fruwać, to bywa straszne!", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Ilekroć chodzi o usprawiedliwienie kleru, zawsze wysuwa się straszaka Bolszewii, od której kler ma być obroną. Ale ten przykład ma dwa oblicza. Przecież właśnie w Rosji było morze ciemnoty i nad nim – tryumfujący pop. To powinno dać do myślenia.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Każdy człowiek staje się pajacem, byle go pociągnąć za odpowiednią nitkę.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Kler, który, uporawszy się z 'heretykami' położył w dawnej Polsce rękę na wszystkim, przyczynił się do pogrążenia narodu w owej straszliwej ciemnocie, w jakiej tkwiliśmy przez cały wiek siedemnasty i trzy czwarte ośmnastego, wówczas gdy inne narody spełniały największą pracę myśli.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Nic się tak nie powtarza jak ekscentryczność i oryginalność.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Nie jestem ani satyrykiem, ani humorystą, te etykietki są mi bardzo niemiłe, jestem czystej krwi błaznem i nie widzę innego odcienia na wyrażenie swego temperamentu literackiego.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Niewątpliwie, biorąc zewnętrznie, Polska jest klerykalna. Kina ani dansingu nie otworzy nikt bez święconej wody.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Pełna gracyi, zacna, słodka, Żyła sobie stara ciotka. Bez zbytków, lecz i bez braku, Miała swój domek na Szlaku.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Piękna nasza ziemia polska – od Chicago do Tobolska.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Pisarz francuski to dla wielu blagier, dla którego nie ma nic świętego, który ze wszystkiego się śmieje i mówi sprośności. (…) Skoro przeznaczeniem naszym jest poznawać Francję z owej śmiejącej strony, nauczmyż się bodaj rozumieć ten francuski uśmiech. Wieki nieprzerwanej pracy i kultury są poza tym uśmiechem. Trzeba było zdeptać we wszystkich kierunkach wszystkie ścieżki, wszystkie dziedziny ducha, aby w świecie myśli stworzyć sobie ogródek intelektualnej zabawy, aby skrót mądrości pokoleń umieć podawać w żartobliwej formie.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Pomyliliśmy się wszyscy. Oszukali nas. (…) Prawdą jest tylko, że w tym systemie nie może żyć człowiek, który by chciał choćby w najniklejszym stopniu wyrazić jakiś pogląd krytyczny. To najstraszniejsza niewola myśli, jaką znają dzieje.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Przykre w miłości jest to, że jest to zabawa, w której nie można obejść się bez wspólnika.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Skoro wychodzi na plac słowo „masoni”, można być pewnym, że bezmyślność i głupota są za węgłem.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Smutno byłoby, gdyby nikt się nie mylił i wszyscy robili dobrze.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Uczynić biedną dziewczynę matką, pozbawić ją pracy dlatego, bo spodziewa się macierzyństwa, kopnąć ją z pogardą, zrzucić na nią cały ciężar błędu i jego skutków, zagrozić jej latami więzienia, jeżeli oszalała rozpaczą chce się od tego zbyt ciężkiego na jej siły brzemienia uwolnić, oto filozofia praw, które – aż nadto znać – były przez mężczyzn pisane.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "W tym jedynym w swoim rodzaju mieście szaleństwem byłoby tracić czas na opukiwanie płuc i macanie wątrób absolutnie takich samych, jak te w kraju.", Author = "Tadeusz Boy-Żeleński" },
            new Quote { Id = "https://pl.wikiquote.org/wiki/Tadeusz_Boy-Żeleński", Text = "Może dupa nareszcie Oczyści atmosferę.", Author = "Tadeusz Boy-Żeleński" },
        };
    }
}