// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as CharacterEventTypeVariants from './character_event_type_variants'

// The tagged union or sum type for the algebraic type `CharacterEventType`.
export type CharacterEventType = CharacterEventTypeVariants.Correct |
  CharacterEventTypeVariants.Incorrect |
  CharacterEventTypeVariants.Backspace;

let _cached_CharacterEventType_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const CharacterEventType = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Correct: { tag: "Correct" } as const,
  Incorrect: { tag: "Incorrect" } as const,
  Backspace: { tag: "Backspace" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_CharacterEventType_type_value) return _cached_CharacterEventType_type_value;
    _cached_CharacterEventType_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_CharacterEventType_type_value.value.variants.push(
      { name: "Correct", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Incorrect", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Backspace", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_CharacterEventType_type_value;
  },

  serialize(writer: __BinaryWriter, value: CharacterEventType): void {
      __AlgebraicTypeValue.serializeValue(writer, CharacterEventType.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): CharacterEventType {
      return __AlgebraicTypeValue.deserializeValue(reader, CharacterEventType.getTypeScriptAlgebraicType());
  },

}

export default CharacterEventType;


