// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { XpMultiplier } from "./xp_multiplier_type";
// Mark import as potentially unused
declare type __keep_XpMultiplier = XpMultiplier;


export type XpGain = {
  id: string,
  playerId: __Identity,
  gameId: string,
  timestamp: bigint,
  baseXp: number,
  multipliers: XpMultiplier[],
  totalXp: number,
};
let _cached_XpGain_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const XpGain = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_XpGain_type_value) return _cached_XpGain_type_value;
    _cached_XpGain_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_XpGain_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "gameId", algebraicType: __AlgebraicTypeValue.String },
      { name: "timestamp", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "baseXp", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "multipliers", algebraicType: __AlgebraicTypeValue.Array(XpMultiplier.getTypeScriptAlgebraicType()) },
      { name: "totalXp", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_XpGain_type_value;
  },

  serialize(writer: __BinaryWriter, value: XpGain): void {
    __AlgebraicTypeValue.serializeValue(writer, XpGain.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): XpGain {
    return __AlgebraicTypeValue.deserializeValue(reader, XpGain.getTypeScriptAlgebraicType());
  },

}

export default XpGain;


