using System;

public static class Dutch500Words
{
    public static readonly string[] Words = new string[]
    {
        "ik", "je", "het", "de", "dat", "is", "een", "niet", "en", "van",
        "wat", "we", "in", "ze", "hij", "te", "zijn", "op", "maar", "er",
        "met", "voor", "die", "heb", "me", "als", "was", "ben", "om", "dit",
        "mijn", "aan", "dan", "naar", "weet", "hier", "zo", "jij", "kan", "geen",
        "nog", "ja", "hem", "heeft", "wel", "moet", "wil", "hebben", "goed", "haar",
        "nee", "hoe", "nu", "waar", "over", "ook", "doen", "uit", "zou", "ga",
        "of", "gaan", "bent", "mij", "bij", "al", "ons", "had", "iets", "daar",
        "jullie", "gaat", "zal", "hebt", "kom", "waarom", "meer", "deze", "moeten", "laat",
        "kunnen", "dus", "jou", "denk", "wie", "alles", "echt", "doe", "door", "alleen",
        "toch", "zien", "weg", "eens", "man", "misschien", "laten", "nooit", "nou", "zei",
        "terug", "mee", "niets", "iemand", "komt", "toen", "veel", "even", "onze", "gewoon",
        "weten", "komen", "nodig", "mensen", "tot", "worden", "zeggen", "tijd", "weer", "leven",
        "twee", "net", "tegen", "maken", "uw", "zeg", "omdat", "zit", "wordt", "hou",
        "kijk", "heel", "wij", "altijd", "mag", "gedaan", "dood", "zeker", "af", "jaar",
        "hun", "wilde", "dag", "allemaal", "jouw", "huis", "dacht", "doet", "vader", "kunt",
        "wacht", "zie", "vrouw", "keer", "andere", "zoals", "zij", "dank", "anders", "geef",
        "waren", "willen", "zich", "bedankt", "erg", "wilt", "praten", "spijt", "geld", "kon",
        "werk", "iedereen", "beter", "werd", "moeder", "niemand", "vinden", "staat", "gezien", "niks",
        "binnen", "zitten", "zullen", "na", "helpen", "wist", "vind", "genoeg", "vast", "elkaar",
        "ging", "uur", "klaar", "hele", "neem", "leuk", "natuurlijk", "alle", "god", "maak",
        "lang", "kwam", "graag", "toe", "drie", "zegt", "bedoel", "deed", "dingen", "maakt",
        "alsjeblieft", "eerste", "krijgen", "zonder", "steeds", "hallo", "houden", "vertellen", "ziet", "idee",
        "geven", "achter", "geweest", "blijven", "helemaal", "mooi", "onder", "kijken", "zag", "goede",
        "naam", "moest", "blijf", "kun", "auto", "luister", "grote", "lijkt", "snel", "ooit",
        "vragen", "paar", "wanneer", "want", "meneer", "nieuwe", "gebeurd", "zorgen", "vriend", "beetje",
        "kinderen", "gek", "hand", "vraag", "laatste", "geweldig", "hadden", "zelfs", "enige", "bang",
        "nemen", "samen", "eten", "zelf", "hoor", "geleden", "staan", "gevonden", "jongen", "denken",
        "vandaag", "denkt", "beste", "gezegd", "thuis", "wereld", "jongens", "heen", "ken", "hen",
        "eerst", "eigen", "zoon", "gelijk", "buiten", "vertel", "morgen", "meisje", "probleem", "alsof",
        "geloof", "halen", "familie", "elke", "zouden", "hoop", "politie", "mannen", "bijna", "vermoord",
        "eigenlijk", "werken", "verdomme", "horen", "manier", "zat", "vrienden", "precies", "kind", "kleine",
        "begrijp", "wou", "geeft", "orde", "houdt", "verder", "vroeg", "stop", "wachten", "rustig",
        "hoofd", "krijg", "daarom", "gebeurt", "soms", "volgens", "dagen", "vond", "krijgt", "gemaakt",
        "kant", "werkt", "open", "gehad", "voel", "zaak", "blij", "volgende", "zoek", "kans",
        "vanavond", "bel", "probeer", "zoeken", "oude", "ding", "moment", "best", "tussen", "plaats",
        "pas", "gehoord", "vijf", "verteld", "zet", "prima", "hulp", "stad", "vindt", "brengen",
        "pijn", "slecht", "geloven", "eruit", "minuten", "school", "plan", "broer", "pak", "jezelf",
        "hoeveel", "kamer", "betekent", "spreken", "juist", "heet", "soort", "haal", "ergens", "vier",
        "gebruiken", "ligt", "blijft", "welke", "proberen", "dokter", "agent", "help", "later", "voordat",
        "ogen", "vrij", "klopt", "gaf", "foto", "word", "zodat", "dochter", "problemen", "plek",
        "water", "kent", "week", "beginnen", "praat", "eerder", "mis", "handen", "deur", "bellen",
        "boven", "groot", "echte", "hoeft", "doden", "stoppen", "moeilijk", "sinds", "land", "spelen",
        "zoveel", "hetzelfde", "mevrouw", "snap", "breng", "pakken", "druk", "verhaal", "lekker", "vrouwen",
        "schat", "vergeten", "gebeuren", "ervan", "kreeg", "waarschijnlijk", "hoi", "mogelijk", "mooie", "bloed",
        "wees", "nacht", "nieuws", "bed", "liet", "lopen", "gelukkig", "waarheid", "reden", "papa",
        "hoorde", "klinkt", "maanden", "vermoorden", "zorg", "bezig", "voorbij", "terwijl", "sta", "zaken",
        "avond", "tien", "schuld", "veilig", "redden", "hart", "zult", "duidelijk", "stel", "schiet",
        "eraan", "zes", "begin", "gekomen", "vol", "vriendin", "rond", "voelt", "baas", "moord",
        "ander", "klein", "fijn", "jaren", "mam", "lichaam", "eerlijk", "gezicht", "ver", "wakker",
        "ouders", "zoiets", "leren", "telefoon", "los", "per", "mama", "nummer", "fout", "mogen"
    };
}
