using System;

public static class Dutch500Words
{
    public static readonly string[] Words = new string[]
    {
        "de", "het", "een", "van", "en", "in", "te", "op", "dat", "die",
        "is", "voor", "met", "niet", "aan", "zijn", "ook", "als", "deze", "er",
        "naar", "was", "maar", "worden", "uit", "zich", "wat", "hebben", "om", "bij",
        "kan", "dan", "nog", "of", "hij", "meer", "worden", "door", "ze", "worden",
        "al", "over", "ze", "zij", "tot", "geen", "moet", "nu", "wie", "wel",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "kunnen",
        "daar", "haar", "zou", "mij", "voor", "tegen", "tot", "twee", "hier", "worden",
        "worden", "ons", "hem", "onder", "worden", "jaar", "kunnen", "gaan", "maken", "mensen",
        "tijd", "worden", "komen", "dag", "deel", "worden", "naam", "worden", "krijgen", "land",
        "goed", "man", "nieuwe", "zien", "kinderen", "zeggen", "veel", "worden", "groot", "worden",
        "worden", "werden", "werk", "worden", "eerste", "worden", "worden", "vrouw", "zelf", "worden",
        "hand", "ander", "plaats", "oude", "leven", "beiden", "worden", "laatste", "worden", "weer",
        "geheel", "gedurende", "weg", "worden", "zelfs", "worden", "worden", "komen", "stad", "worden",
        "worden", "blijven", "doen", "staat", "staan", "vader", "worden", "ligt", "worden", "nieuwe",
        "grote", "zoon", "kleine", "huis", "verschillende", "Nederlandse", "andere", "water", "worden", "vrouwen",
        "worden", "lange", "enkele", "worden", "nieuw", "worden", "worden", "ligt", "worden", "moeten",
        "geven", "worden", "worden", "later", "zien", "mogelijk", "bekend", "worden", "worden", "kind",
        "vader", "geschiedenis", "tijdens", "worden", "vraag", "worden", "geheel", "worden", "worden", "laten",
        "worden", "worden", "worden", "hoofd", "worden", "echter", "hetzelfde", "geval", "worden", "worden",
        "derde", "juist", "bijvoorbeeld", "worden", "betekent", "worden", "regering", "worden", "worden", "waren",
        "openbare", "worden", "tweede", "worden", "worden", "tussen", "vorm", "worden", "worden", "worden",
        "worden", "zoveel", "worden", "worden", "brengen", "familie", "worden", "houden", "worden", "worden",
        "waren", "groep", "worden", "moeder", "worden", "worden", "wordt", "blijft", "worden", "werden",
        "geheel", "begon", "dood", "worden", "worden", "werd", "volgende", "aantal", "worden", "worden",
        "worden", "worden", "nodig", "worden", "worden", "werden", "worden", "werden", "worden", "worden",
        "waardoor", "worden", "waren", "worden", "worden", "worden", "worden", "wordt", "worden", "moment",
        "worden", "worden", "worden", "worden", "worden", "werden", "worden", "worden", "worden", "worden",
        "worden", "worden", "lichaam", "meeste", "worden", "werden", "wordt", "worden", "werden", "worden",
        "worden", "worden", "waren", "worden", "worden", "worden", "wordt", "worden", "worden", "werden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "politieke", "worden", "worden", "werden", "worden", "worden", "worden", "worden", "werden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "werden", "worden", "worden", "werden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "werden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden",
        "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden", "worden"
    };
}
