using System;

public static class English500Words
{
    public static readonly string[] Words = new string[]
    {
        "you", "the", "to", "it", "and", "that", "of", "is", "in", "what",
        "we", "me", "this", "he", "for", "my", "on", "have", "your", "do",
        "was", "no", "not", "be", "are", "know", "can", "with", "but", "all",
        "so", "just", "there", "here", "they", "like", "get", "she", "go", "if",
        "right", "out", "about", "up", "at", "him", "now", "one", "come", "well",
        "her", "how", "will", "got", "want", "think", "as", "see", "did", "good",
        "who", "why", "from", "let", "his", "yes", "when", "going", "time", "an",
        "back", "look", "us", "would", "them", "where", "were", "take", "then", "had",
        "or", "been", "our", "tell", "really", "man", "some", "say", "could", "by",
        "need", "something", "has", "too", "more", "way", "down", "make", "very", "never",
        "only", "people", "over", "because", "little", "please", "love", "should", "mean", "said",
        "sorry", "give", "off", "am", "thank", "any", "two", "even", "much", "doing",
        "sure", "thing", "these", "help", "first", "into", "anything", "still", "find", "life",
        "nothing", "sir", "day", "god", "work", "their", "again", "maybe", "must", "before",
        "other", "wait", "stop", "call", "after", "talk", "away", "than", "thought", "home",
        "night", "put", "great", "those", "last", "better", "everything", "told", "new", "things",
        "always", "keep", "long", "years", "leave", "does", "money", "around", "name", "place",
        "ever", "feel", "guys", "father", "guy", "made", "old", "which", "big", "lot",
        "done", "hello", "nice", "believe", "girl", "someone", "fine", "thanks", "wanted", "kind",
        "coming", "house", "every", "through", "being", "course", "stay", "left", "dad", "enough",
        "happened", "came", "may", "mother", "wrong", "world", "bad", "might", "three", "today",
        "listen", "another", "understand", "hear", "remember", "ask", "own", "same", "show", "else",
        "kill", "talking", "found", "next", "getting", "care", "car", "looking", "son", "try",
        "woman", "went", "dead", "many", "mind", "friend", "best", "mom", "morning", "trying",
        "boy", "together", "yourself", "job", "saw", "family", "real", "without", "baby", "room",
        "already", "move", "most", "seen", "live", "miss", "actually", "both", "heard", "once",
        "ready", "head", "called", "used", "idea", "knew", "hold", "happy", "door", "such",
        "brother", "also", "pretty", "bit", "took", "yet", "men", "whole", "start", "use",
        "while", "since", "wife", "days", "guess", "tomorrow", "matter", "meet", "bring", "tonight",
        "everyone", "run", "hard", "alone", "myself", "school", "gone", "end", "saying", "phone",
        "play", "looks", "problem", "few", "friends", "ago", "open", "anyone", "killed", "hope",
        "face", "until", "lost", "police", "excuse", "turn", "business", "case", "wants", "says",
        "true", "die", "heart", "soon", "each", "worry", "later", "year", "watch", "music",
        "hand", "having", "probably", "beautiful", "doctor", "sit", "eat", "thinking", "young", "second",
        "working", "water", "person", "part", "kids", "late", "stuff", "exactly", "under", "death",
        "minute", "pay", "crazy", "forget", "everybody", "kid", "change", "gave", "happen", "five",
        "drink", "far", "knows", "its", "whatever", "eyes", "shut", "hit", "taking", "easy",
        "times", "check", "hands", "minutes", "deal", "different", "means", "point", "inside", "makes",
        "asked", "somebody", "mine", "making", "body", "afraid", "sleep", "chance", "dear", "quite",
        "four", "anyway", "close", "party", "fun", "against", "word", "comes", "important", "set",
        "shall", "story", "number", "daughter", "least", "waiting", "hurt", "wish", "moment", "fight",
        "week", "husband", "girls", "rest", "married", "fire", "game", "nobody", "children", "side",
        "stand", "read", "though", "cut", "started", "sister", "supposed", "between", "child", "goes",
        "hours", "speak", "women", "behind", "almost", "truth", "blood", "able", "lady", "anymore",
        "playing", "gets", "shot", "reason", "trouble", "break", "war", "city", "walk", "town",
        "trust", "met", "office", "question", "brought", "yours", "welcome", "high", "couple", "half",
        "died", "cool", "free", "either", "seems", "power", "bye", "buy", "telling", "honey",
        "tried", "front", "team", "answer", "gun", "boys", "line", "send", "news", "stupid",
        "bed", "hurry", "full", "months", "save", "sometimes", "become", "along", "hate", "food",
        "outside", "light", "needs", "dog", "country", "clear", "order", "em", "fact", "lord"
    };
}
