using System;

public static class English500Words
{
    public static readonly string[] Words = new string[]
    {
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
        "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
        "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
        "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
        "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
        "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
        "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
        "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
        "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
        "is", "was", "are", "been", "has", "had", "were", "said", "did", "having",
        "may", "should", "being", "does", "doing", "man", "woman", "child", "person", "place",
        "thing", "life", "world", "school", "state", "family", "student", "group", "country", "problem",
        "hand", "part", "case", "week", "company", "system", "program", "question", "government", "number",
        "night", "point", "home", "water", "room", "mother", "area", "money", "story", "fact",
        "month", "lot", "right", "study", "book", "eye", "job", "word", "business", "issue",
        "side", "kind", "head", "house", "service", "friend", "father", "power", "hour", "game",
        "line", "end", "member", "law", "car", "city", "community", "name", "president", "team",
        "minute", "idea", "kid", "body", "information", "parent", "face", "others", "level", "office",
        "door", "health", "art", "war", "history", "party", "result", "change", "morning", "reason",
        "research", "girl", "guy", "moment", "air", "teacher", "force", "education", "foot", "boy",
        "age", "policy", "process", "music", "market", "die", "sense", "build", "college", "blood",
        "term", "test", "movie", "certain", "north", "love", "picture", "rate", "local", "those",
        "report", "nature", "player", "economy", "medical", "hospital", "church", "close", "thousand", "risk",
        "current", "fire", "future", "wrong", "involve", "defense", "anyone", "increase", "security", "bank",
        "myself", "certainly", "west", "sport", "board", "seek", "per", "subject", "officer", "private",
        "rest", "behavior", "deal", "performance", "fight", "throw", "top", "quickly", "past", "goal",
        "bed", "order", "author", "fill", "represent", "focus", "foreign", "drop", "plan", "upon",
        "agency", "push", "color", "recently", "store", "reduce", "sound", "note", "fine", "before",
        "near", "movement", "page", "enter", "share", "common", "poor", "natural", "race", "concern",
        "series", "significant", "similar", "hot", "language", "each", "usually", "response", "dead", "rise",
        "animal", "factor", "decade", "article", "shoot", "east", "save", "seven", "artist", "away",
        "scene", "stock", "career", "despite", "central", "eight", "thus", "treatment", "beyond", "happy",
        "exactly", "protect", "approach", "lie", "size", "dog", "fund", "serious", "occur", "media",
        "ready", "sign", "thought", "list", "individual", "simple", "quality", "pressure", "accept", "answer",
        "hard", "resource", "identify", "left", "meeting", "determine", "prepare", "disease", "whatever", "success",
        "argue", "cup", "particularly", "amount", "ability", "staff", "recognize", "indicate", "character", "growth",
        "loss", "degree", "wonder", "attack", "herself", "region", "television", "box", "training", "pretty",
        "trade", "election", "everybody", "physical", "lay", "general", "feeling", "standard", "bill", "message",
        "fail", "outside", "arrive", "analysis", "benefit", "sex", "forward", "lawyer", "present", "section",
        "environmental", "glass", "skill", "sister", "professor", "operation", "financial", "crime", "stage", "compare",
        "authority", "miss", "design", "sort", "act", "ten", "knowledge", "gun", "station", "blue",
        "strategy", "little", "clearly", "discuss", "indeed", "truth", "song", "example", "democratic", "check",
        "environment", "leg", "dark", "public", "various", "rather", "laugh", "guess", "executive", "set",
        "prove", "hang", "entire", "rock", "enough", "forget", "since", "claim", "remove", "manager",
        "help", "enjoy", "network", "legal", "religious", "cold", "form", "final", "main", "science",
        "green", "memory", "card", "above", "seat", "cell", "establish", "nice", "trial", "expert",
        "spring", "firm", "democrat", "radio", "visit", "management", "care", "avoid", "imagine", "tonight",
        "huge", "ball", "finish", "yourself", "talk", "theory", "impact", "respond", "statement", "maintain",
        "charge", "popular", "traditional", "onto", "reveal", "direction", "weapon", "employee", "cultural", "contain"
    };
}