using System;

public static class French500Words
{
    public static readonly string[] Words = new string[]
    {
        "le", "de", "un", "être", "et", "à", "il", "avoir", "ne", "je",
        "son", "que", "se", "qui", "ce", "dans", "en", "du", "elle", "au",
        "pour", "pas", "que", "vous", "par", "sur", "faire", "plus", "dire", "me",
        "on", "mon", "lui", "nous", "comme", "mais", "pouvoir", "avec", "tout", "y",
        "aller", "voir", "en", "bien", "où", "sans", "tu", "ou", "leur", "homme",
        "si", "deux", "moi", "autre", "dans", "très", "tant", "vouloir", "dont", "chose",
        "elle", "tout", "lui", "temps", "très", "quand", "peu", "falloir", "celle", "entre",
        "moi", "tenir", "même", "monde", "encore", "trop", "grand", "mon", "pourquoi", "femme",
        "demander", "donc", "notre", "tout", "rendre", "jour", "leur", "prendre", "venir", "main",
        "trouver", "donner", "parler", "aimer", "chaque", "faut", "ces", "fois", "aussi", "bien",
        "alors", "nouveau", "seul", "quelque", "depuis", "autre", "mettre", "vie", "savoir", "croire",
        "devant", "sous", "avant", "contre", "vers", "jamais", "après", "toujours", "heure", "ans",
        "maintenant", "peut", "même", "enfant", "quelque", "comment", "petit", "raison", "année", "là",
        "encore", "cette", "rester", "votre", "moins", "vraiment", "dire", "porte", "français", "partir",
        "jour", "chez", "cela", "tel", "passer", "arriver", "laisser", "ainsi", "entrer", "beaucoup",
        "commencer", "place", "suivre", "penser", "regarder", "travailler", "pied", "servir", "vivre", "point",
        "soir", "tête", "sentir", "coeur", "oeil", "loin", "beau", "pendant", "autant", "bas",
        "besoin", "sembler", "seulement", "matin", "devenir", "guerre", "garder", "genre", "poser", "nom",
        "corps", "endroit", "pays", "écrire", "revenir", "attendre", "dernier", "certain", "père", "parce",
        "asseoir", "politique", "entendre", "question", "eau", "ensuite", "histoire", "côté", "rue", "sortir",
        "agir", "important", "amour", "jeune", "personne", "cas", "connaître", "ville", "présent", "moment",
        "français", "situation", "doute", "état", "parti", "national", "public", "long", "forme", "rôle",
        "chef", "action", "différent", "face", "blanc", "nord", "ami", "ordre", "seul", "premier",
        "bureau", "ministre", "livre", "compter", "million", "permettre", "reprendre", "ministre", "part", "mesure",
        "groupe", "montrer", "voix", "vue", "social", "force", "train", "classe", "position", "idée",
        "système", "voiture", "répondre", "intérêt", "français", "projet", "simple", "sud", "problème", "service",
        "père", "étude", "jouer", "recherche", "continuer", "façon", "constituer", "besoin", "dernier", "étranger",
        "société", "cause", "fond", "figure", "regard", "nature", "compte", "mère", "route", "école",
        "fois", "port", "terre", "chambre", "mer", "image", "ligne", "gros", "franc", "langue",
        "frère", "lumière", "coup", "famille", "union", "table", "plan", "main", "note", "fils",
        "ville", "justice", "groupe", "général", "siècle", "milieu", "terrain", "perte", "droit", "plein",
        "souvenir", "sujet", "marcher", "salle", "jeu", "bois", "courir", "rouge", "reste", "dieu",
        "type", "obtenir", "rapport", "officiel", "mort", "gagner", "parole", "but", "prince", "esprit",
        "maître", "condition", "loi", "vue", "court", "lever", "quartier", "soleil", "représenter", "rester",
        "mari", "armée", "enfin", "population", "attention", "résultat", "art", "manquer", "toucher", "chef",
        "proposer", "lieu", "réaliser", "preuve", "suite", "haut", "lettre", "entreprise", "changer", "centre",
        "air", "appeler", "fille", "conduire", "communauté", "mouvement", "époque", "fond", "écrire", "maison",
        "couleur", "revue", "mur", "offrir", "caractère", "réunion", "effet", "effort", "tirer", "espèce",
        "compagnie", "mois", "courant", "signe", "lire", "fort", "marché", "perdre", "tuer", "soutenir",
        "auteur", "nuit", "programme", "plupart", "douleur", "ton", "exemple", "produire", "principe", "direction",
        "propos", "personnel", "parler", "moyen", "vieux", "joli", "anglais", "présenter", "page", "ordre",
        "sentir", "rapporter", "vrai", "noir", "passage", "monsieur", "remettre", "ressource", "bras", "tenter",
        "semaine", "succès", "technique", "ouvrir", "établir", "âge", "origine", "théorie", "somme", "ouvrage",
        "défense", "ajouter", "assurer", "composer", "défendre", "établissement", "dame", "expression", "province", "rang",
        "réel", "demeurer", "appel", "tendre", "mariage", "maintenir", "affirmer", "poursuivre", "prévoir", "double",
        "vérité", "qualité", "décision", "manière", "intérieur", "souffrir", "valeur", "conclure", "près", "commerce"
    };
}
