using System;

public static class French500Words
{
    public static readonly string[] Words = new string[]
    {
        "de", "je", "est", "pas", "le", "que", "la", "vous", "tu", "un",
        "et", "il", "ne", "les", "en", "on", "ça", "une", "ce", "pour",
        "ai", "des", "qui", "mais", "dans", "nous", "elle", "me", "bien", "si",
        "du", "suis", "non", "avec", "tout", "plus", "mon", "te", "au", "fait",
        "moi", "oui", "va", "était", "as", "faire", "ils", "sur", "quoi", "se",
        "comme", "sais", "être", "veux", "ici", "ma", "toi", "dit", "lui", "votre",
        "es", "pourquoi", "où", "là", "rien", "cette", "sont", "quand", "peux", "dire",
        "son", "avez", "vais", "alors", "ton", "comment", "par", "ou", "chose", "bon",
        "ont", "merci", "juste", "très", "jamais", "été", "aussi", "avoir", "vraiment", "voir",
        "même", "sa", "oh", "maintenant", "tous", "peut", "deux", "ces", "êtes", "allez",
        "ta", "autre", "peu", "temps", "quelque", "fais", "toujours", "encore", "notre", "mes",
        "besoin", "avait", "accord", "faut", "dois", "vie", "aller", "fois", "vu", "donc",
        "sans", "monde", "étais", "parce", "avant", "sûr", "trop", "parler", "personne", "avais",
        "père", "crois", "après", "aux", "dieu", "ouais", "ses", "pense", "eu", "aime",
        "leur", "homme", "viens", "vrai", "femme", "ok", "doit", "veut", "ans", "mal",
        "chez", "déjà", "depuis", "beaucoup", "vos", "bonne", "mort", "mieux", "vas", "mère",
        "sera", "dis", "fille", "tes", "gens", "quel", "vois", "désolé", "ca", "voilà",
        "avons", "petit", "maison", "soit", "cela", "autres", "toute", "soir", "passé", "prendre",
        "jour", "monsieur", "nos", "savoir", "choses", "salut", "cet", "nom", "argent", "bonjour",
        "nuit", "raison", "moins", "arrive", "maman", "reste", "moment", "voulais", "seul", "aider",
        "air", "entre", "papa", "passe", "aurais", "problème", "ah", "peur", "regarde", "voulez",
        "gars", "trouvé", "fils", "attends", "savez", "trouver", "trois", "assez", "famille", "dû",
        "eh", "toutes", "plaît", "pourrait", "travail", "pris", "pu", "tête", "quelle", "sait",
        "sommes", "appelle", "quelques", "faites", "partir", "vite", "arrête", "seule", "serait", "voiture",
        "enfants", "tuer", "hé", "pendant", "idée", "chance", "parle", "aurait", "part", "elles",
        "jours", "grand", "venir", "ami", "demain", "hein", "tard", "puis", "truc", "passer",
        "petite", "tant", "connais", "combien", "mec", "sens", "pouvez", "porte", "sortir", "super",
        "heure", "contre", "coup", "comprends", "entendu", "vient", "allons", "ensemble", "nouveau", "amour",
        "importe", "sang", "désolée", "cas", "sous", "rester", "amis", "prends", "fini", "hommes",
        "tué", "question", "partie", "histoire", "devrais", "aide", "dernière", "demande", "chercher", "pensais",
        "genre", "seulement", "police", "car", "mois", "frère", "laisser", "aucun", "mettre", "eux",
        "laisse", "chaque", "ville", "arrivé", "devrait", "parlé", "vont", "longtemps", "aucune", "heures",
        "bébé", "place", "revoir", "compris", "ni", "savais", "leurs", "étaient", "attention", "donner",
        "affaire", "endroit", "pourrais", "corps", "façon", "donné", "voici", "train", "dont", "écoute",
        "yeux", "trouve", "pouvoir", "type", "perdu", "premier", "première", "côté", "point", "tellement",
        "main", "tiens", "sois", "enfant", "vieux", "matin", "venu", "pardon", "suite", "vers",
        "minutes", "demandé", "venez", "devant", "dr", "enfin", "arrêter", "cause", "nouvelle", "attendez",
        "chambre", "droit", "parti", "mis", "eau", "compte", "dirait", "terre", "belle", "espère",
        "aimerais", "loin", "mari", "donne", "fin", "croire", "mme", "aura", "gros", "boulot",
        "plutôt", "chérie", "prêt", "filles", "bureau", "mourir", "hier", "possible", "jouer", "demander",
        "celui", "voulait", "beau", "jeune", "euh", "dehors", "docteur", "confiance", "appeler", "années",
        "vérité", "école", "chef", "femmes", "propos", "semaine", "vivre", "regardez", "feu", "journée",
        "madame", "hey", "téléphone", "près", "affaires", "meilleur", "devez", "dessus", "mains", "penses",
        "prie", "équipe", "grande", "manger", "arriver", "dur", "guerre", "ait", "appelé", "marche",
        "sécurité", "garçon", "essaie", "important", "dites", "exactement", "font", "fort", "presque", "plein",
        "derrière", "ben", "mariage", "parents", "capitaine", "dernier", "fou", "ceux", "tomber", "attendre",
        "vue", "pensé", "souviens", "envie", "fête", "jeu", "génial", "pays", "garde", "cours",
        "bientôt", "ii", "numéro", "personnes", "cinq", "parfait", "laissé", "ainsi", "retour", "semble",
        "autant", "peine", "minute", "essayé", "plan", "instant", "serai", "prison", "penser", "essayer",
        "prend", "arme", "mauvais", "mot", "travailler", "quatre", "rentrer", "regarder", "choix", "parfois"
    };
}
