using System;

public static class German500Words
{
    public static readonly string[] Words = new string[]
    {
        "ich", "sie", "das", "ist", "du", "nicht", "die", "es", "und", "der",
        "wir", "was", "zu", "er", "ein", "in", "ja", "mir", "mit", "wie",
        "den", "mich", "auf", "dass", "aber", "eine", "so", "hat", "hier", "haben",
        "für", "sind", "war", "von", "wenn", "dich", "ihr", "nein", "habe", "an",
        "bin", "noch", "nur", "da", "dir", "sich", "einen", "uns", "hast", "dem",
        "kann", "gut", "auch", "schon", "als", "sein", "mal", "jetzt", "ihn", "dann",
        "aus", "meine", "um", "im", "wird", "mein", "bist", "doch", "alles", "weiß",
        "keine", "oder", "nach", "nichts", "man", "muss", "werden", "will", "ihnen", "geht",
        "wo", "etwas", "oh", "mehr", "bei", "also", "bitte", "immer", "hab", "warum",
        "vor", "los", "können", "wieder", "sagen", "machen", "danke", "sehr", "alle", "denn",
        "mann", "tun", "ihm", "zum", "gehen", "sehen", "vielleicht", "einem", "wer", "ihre",
        "diese", "euch", "einer", "komm", "über", "gibt", "okay", "wissen", "deine", "müssen",
        "soll", "werde", "nie", "wirklich", "hey", "kein", "viel", "weg", "würde", "tut",
        "am", "des", "einfach", "leben", "hatte", "zeit", "weil", "willst", "kommen", "dein",
        "heute", "kommt", "wollen", "damit", "ganz", "wäre", "wollte", "weißt", "ok", "sicher",
        "gesagt", "frau", "nun", "bis", "wurde", "leid", "na", "kannst", "macht", "dieser",
        "zurück", "lassen", "hallo", "meinen", "gott", "seine", "hätte", "zwei", "könnte", "genau",
        "waren", "zur", "lass", "klar", "morgen", "leute", "vater", "schön", "glaube", "ab",
        "gerade", "tag", "gesehen", "reden", "wohl", "liebe", "sollte", "sagte", "unsere", "jemand",
        "geld", "durch", "ob", "keinen", "mutter", "raus", "gemacht", "paar", "mach", "passiert",
        "dachte", "besser", "musst", "wieso", "sir", "dieses", "selbst", "gehört", "möchte", "ohne",
        "hör", "her", "sag", "meiner", "anderen", "helfen", "nacht", "finden", "diesen", "gute",
        "wirst", "lange", "natürlich", "ach", "meinem", "gar", "ins", "sei", "dort", "weiter",
        "geben", "seit", "gleich", "sagt", "recht", "ihren", "richtig", "ordnung", "vom", "hören",
        "sieht", "davon", "dafür", "geh", "diesem", "wegen", "hause", "sollten", "mädchen", "hin",
        "sollen", "abend", "haus", "denke", "viele", "drei", "deinen", "freund", "guten", "unser",
        "warte", "machst", "menschen", "essen", "angst", "bleiben", "zusammen", "welt", "unter", "habt",
        "schnell", "andere", "tot", "getan", "darf", "erst", "rein", "stimmt", "nehmen", "kinder",
        "eines", "glauben", "bringen", "ganze", "genug", "brauchen", "gegen", "moment", "junge", "steht",
        "sonst", "musik", "arbeit", "seid", "ihrer", "fragen", "herr", "dabei", "heißt", "familie",
        "warten", "niemand", "sofort", "bevor", "jahre", "einmal", "problem", "sohn", "wann", "brauche",
        "fertig", "halt", "allein", "beim", "sprechen", "beide", "gefunden", "hatten", "sache", "hilfe",
        "ne", "jeder", "warst", "gern", "konnte", "darüber", "halten", "siehst", "verstehe", "jahren",
        "kam", "kind", "wusste", "wahr", "seinen", "dazu", "bruder", "daran", "ihrem", "denken",
        "könnten", "dank", "würden", "lieber", "fall", "deiner", "sehe", "egal", "kennen", "deinem",
        "vergessen", "frage", "mache", "komme", "sage", "mag", "sieh", "echt", "gib", "eigentlich",
        "jeden", "dad", "gab", "uhr", "stadt", "männer", "baby", "fahren", "namen", "bekommen",
        "kopf", "hi", "gehe", "kleine", "später", "glück", "letzte", "freunde", "all", "darauf",
        "ende", "bald", "töten", "dinge", "meinst", "toll", "eins", "minuten", "vielen", "bereit",
        "weit", "ahnung", "seiner", "bisschen", "tür", "auto", "jungs", "eure", "augen", "polizei",
        "stehen", "sterben", "hätten", "draußen", "kenne", "fast", "runter", "vorbei", "treffen", "gerne",
        "dran", "wurden", "arbeiten", "mom", "verrückt", "neue", "ging", "hinter", "sorgen", "einzige",
        "jemanden", "darum", "tochter", "braucht", "idee", "schwester", "drin", "ruhig", "sah", "ganzen",
        "spät", "ziemlich", "solltest", "name", "sogar", "kurz", "kerl", "frauen", "liegt", "suchen",
        "finde", "je", "woher", "lang", "job", "keiner", "seinem", "hört", "verstehen", "spielen",
        "überhaupt", "teufel", "verstanden", "verloren", "große", "hand", "grund", "jahr", "kommst", "mama",
        "ruhe", "gewesen", "tod", "stunden", "hoffe", "denkst", "oben", "gestern", "versuchen", "art",
        "letzten", "schatz", "endlich", "he", "nimm", "etwa", "erzählt", "läuft", "schwer", "anders",
        "miss", "musste", "fünf", "wasser", "lässt", "erste", "versucht", "gekommen", "geschichte", "wenig",
        "holen", "bedeutet", "nett", "wahrheit", "woche", "bringt", "deshalb", "welche", "bestimmt", "hoch"
    };
}
