public static class Indonesian500Words
{
    // Frequency-ranked Indonesian, normalized to Unicode NFC.
    // Source: https://github.com/hermitdave/FrequencyWords/blob/master/content/2016/id/id_50k.txt
    public static readonly string[] Words = new string[]
    {
        "aku", "kau", "yang", "tidak", "ini", "itu", "dan", "di", "dia", "akan",
        "apa", "kita", "untuk", "anda", "bisa", "tak", "ada", "mereka", "saya", "tahu",
        "dengan", "dari", "ya", "kami", "tapi", "ke", "harus", "sudah", "kamu", "adalah",
        "orang", "saja", "ingin", "seperti", "pergi", "jika", "hanya", "sini", "sekarang", "semua",
        "dalam", "jadi", "baik", "bukan", "jangan", "bagaimana", "punya", "lagi", "lebih", "pada",
        "mungkin", "lakukan", "kalian", "sangat", "karena", "apakah", "satu", "pernah", "mau", "telah",
        "ayo", "siapa", "juga", "hal", "kembali", "datang", "atau", "hari", "sesuatu", "kasih",
        "melihat", "banyak", "saat", "benar", "terima", "lihat", "begitu", "tentang", "terjadi", "bahwa",
        "menjadi", "kenapa", "seorang", "bagus", "melakukan", "hei", "bilang", "masih", "oke", "sana",
        "kalau", "keluar", "baiklah", "mana", "lain", "waktu", "malam", "tempat", "mati", "lalu",
        "maaf", "dapat", "membuat", "memiliki", "anak", "tahun", "sedang", "sampai", "mengapa", "beberapa",
        "sekali", "baru", "katakan", "ia", "sendiri", "sebuah", "ayah", "tunggu", "hidup", "perlu",
        "ketika", "salah", "cepat", "sama", "mengatakan", "kan", "besar", "masuk", "semuanya", "dengar",
        "rumah", "pikir", "padaku", "dua", "tuhan", "masalah", "selamat", "tentu", "pasti", "belum",
        "pak", "bicara", "suka", "cukup", "selalu", "pria", "seseorang", "melakukannya", "mendapatkan", "mengerti",
        "sedikit", "ibu", "berada", "atas", "setelah", "tolong", "tinggal", "sayang", "menemukan", "bahkan",
        "percaya", "jalan", "bertemu", "bekerja", "lama", "terlalu", "makan", "wanita", "mari", "kecil",
        "kali", "tetap", "setiap", "padamu", "sebagai", "oleh", "berpikir", "berhenti", "yakin", "membunuh",
        "luar", "mengambil", "cara", "dunia", "mulai", "pertama", "diri", "selama", "sebelum", "ayolah",
        "uang", "bersama", "teman", "boleh", "senang", "merasa", "mencari", "yah", "kurasa", "gadis",
        "butuh", "jam", "mencoba", "tanpa", "dulu", "polisi", "buruk", "sebenarnya", "para", "berapa",
        "membawa", "kemudian", "siap", "ingat", "sial", "denganmu", "biarkan", "mobil", "takkan", "tuan",
        "tidur", "itulah", "gila", "maksudku", "kepada", "berbicara", "terus", "pulang", "segera", "kota",
        "sakit", "nama", "halo", "takut", "pun", "seharusnya", "memang", "terakhir", "biasa", "tiga",
        "membantu", "terlihat", "depan", "dirimu", "cinta", "sebentar", "minta", "bodoh", "bagian", "manusia",
        "ambil", "bawah", "berhasil", "tepat", "padanya", "mendengar", "berikan", "bawa", "rasa", "air",
        "sepertinya", "pagi", "sungguh", "maafkan", "hebat", "bagi", "tangan", "hai", "pekerjaan", "menunggu",
        "kehilangan", "melihatnya", "ikut", "keluarga", "cuma", "nanti", "suatu", "tua", "bergerak", "paling",
        "tenang", "jauh", "masa", "untukmu", "menit", "meninggalkan", "terbaik", "peduli", "penting", "aneh",
        "seluruh", "hentikan", "selesai", "tadi", "ah", "si", "duduk", "coba", "memberikan", "berdua",
        "bisakah", "bulan", "senjata", "besok", "khawatir", "kepala", "minum", "tetapi", "berarti", "secara",
        "pintu", "hampir", "sekolah", "berjalan", "diam", "sebelumnya", "nak", "aman", "sekitar", "buat",
        "maksudmu", "kemari", "sejak", "nah", "maka", "bermain", "menggunakan", "astaga", "cari", "inginkan",
        "sulit", "dekat", "jatuh", "ayahku", "mendapat", "memberi", "kapan", "memberitahu", "kumohon", "kesempatan",
        "cantik", "benarkah", "mudah", "kawan", "dapatkan", "menarik", "soal", "mata", "berakhir", "hati",
        "jelas", "ayahmu", "bukankah", "akhirnya", "minggu", "dengannya", "tim", "lainnya", "indah", "bunuh",
        "alasan", "denganku", "bangun", "keras", "eh", "serius", "berubah", "kupikir", "berkata", "menyenangkan",
        "kosong", "pergilah", "kerja", "belakang", "dokter", "beri", "agar", "beritahu", "kuat", "lari",
        "dengarkan", "kamar", "kata", "berharap", "bertanya", "meminta", "kulakukan", "dilakukan", "berbeda", "iya",
        "tau", "hilang", "biar", "darah", "makanan", "menurutmu", "perang", "bantuan", "kedua", "raja",
        "demi", "kabar", "telepon", "kehidupan", "buku", "meninggal", "ruang", "membuatku", "daripada", "turun",
        "lima", "kaki", "menyelamatkan", "lepaskan", "menuju", "kapal", "pertanyaan", "suara", "membiarkan", "anjing",
        "naik", "dasar", "muda", "permisi", "perjalanan", "kasus", "pikirkan", "tinggi", "lupa", "marah",
        "lihatlah", "agen", "menikah", "lewat", "ide", "rencana", "kapten", "belajar", "silakan", "penuh",
        "lucu", "membutuhkan", "diriku", "negara", "berusaha", "berdiri", "cerita", "kecuali", "tanah", "namanya",
        "kekuatan", "buka", "langsung", "menang", "antara", "bicarakan", "menunjukkan", "bila", "kematian", "pesawat",
        "ibumu", "nona", "melalui", "sendirian", "melawan", "akhir", "menerima", "rahasia", "nomor", "awak",
        "sepanjang", "terlambat", "api", "pesta", "temukan", "paham", "artinya", "dirinya", "empat", "ibuku",
        "kira", "pilihan", "rasanya", "sementara", "bu", "membuatnya", "panas", "memilih", "mencintaimu", "semakin",
        "untukku", "mulia", "l", "omong", "film", "waktunya", "tiba", "bantu", "tinggalkan", "menembak",
    };
}
