using System;

public static class Italian500Words
{
    public static readonly string[] Words = new string[]
    {
        "non", "che", "di", "la", "il", "un", "per", "in", "una", "mi",
        "sono", "ho", "si", "ha", "ma", "lo", "cosa", "con", "no", "le",
        "ti", "se", "da", "come", "io", "ci", "hai", "questo", "bene", "qui",
        "sei", "del", "tu", "solo", "mio", "al", "me", "tutto", "te", "era",
        "della", "mia", "fatto", "fare", "essere", "so", "quando", "sì", "ora", "lei",
        "gli", "ne", "oh", "questa", "detto", "ok", "va", "perche", "quello", "mai",
        "alla", "anche", "stato", "abbiamo", "tutti", "dei", "grazie", "chi", "sta", "molto",
        "più", "voglio", "perché", "tuo", "beh", "sia", "nel", "lui", "allora", "posso",
        "piu", "ehi", "prima", "tua", "suo", "niente", "qualcosa", "sai", "siamo", "cosi",
        "davvero", "ancora", "hanno", "stai", "fa", "sua", "così", "casa", "uno", "dove",
        "su", "vero", "vuoi", "noi", "due", "quindi", "dire", "delle", "quella", "sempre",
        "altro", "sto", "andare", "ad", "po", "loro", "devo", "quel", "forse", "li",
        "proprio", "certo", "tempo", "nella", "poi", "vi", "credo", "vita", "cose", "sul",
        "quanto", "puoi", "fuori", "anni", "cui", "andiamo", "parte", "visto", "qualcuno", "lavoro",
        "voi", "ciao", "dio", "volta", "dopo", "adesso", "stata", "uomo", "padre", "devi",
        "bisogno", "gia", "amico", "ed", "posto", "nessuno", "via", "fai", "signore", "meglio",
        "dai", "dal", "vuole", "sembra", "giorno", "ogni", "modo", "senza", "vedere", "dobbiamo",
        "signor", "qualche", "dispiace", "penso", "ecco", "parlare", "tra", "mamma", "già", "sarebbe",
        "dalla", "troppo", "fosse", "possiamo", "ce", "nuovo", "male", "madre", "avete", "tanto",
        "favore", "successo", "vai", "sulla", "giusto", "sa", "miei", "aspetta", "avere", "altra",
        "farlo", "alle", "facendo", "abbia", "momento", "ero", "aveva", "ragazzi", "deve", "persone",
        "nostro", "tipo", "prego", "grande", "può", "senti", "appena", "potrebbe", "soldi", "dice",
        "sapere", "tre", "oggi", "questi", "piace", "idea", "siete", "ai", "avevo", "figlio",
        "accordo", "gente", "sicuro", "vieni", "degli", "guarda", "dentro", "trovato", "queste", "caso",
        "forza", "tutte", "pensi", "signora", "faccio", "nome", "avuto", "problema", "altri", "puo",
        "aver", "mondo", "tutta", "preso", "nulla", "nostra", "donna", "stare", "basta", "insieme",
        "faccia", "ragazza", "subito", "famiglia", "ragazzo", "volevo", "okay", "sentito", "ah", "stesso",
        "ragione", "sarà", "tuoi", "capito", "notte", "volte", "testa", "serve", "tesoro", "sotto",
        "eh", "suoi", "vado", "sara", "dato", "stiamo", "bella", "scusa", "erano", "pensavo",
        "avrei", "prendere", "buona", "porta", "bello", "moglie", "vorrei", "storia", "succede", "morto",
        "cercando", "dici", "persona", "pronto", "meno", "dovuto", "avanti", "capisco", "secondo", "venire",
        "polizia", "lì", "avrebbe", "stanno", "mentre", "letto", "fino", "dico", "amici", "fine",
        "aiuto", "paura", "fratello", "stavo", "uomini", "domani", "facciamo", "abbastanza", "capo", "amore",
        "nei", "ucciso", "state", "piano", "macchina", "trovare", "comunque", "vediamo", "giorni", "nemmeno",
        "mano", "presto", "stati", "far", "bambino", "andato", "vedo", "tornare", "quelle", "cio",
        "primo", "vostro", "neanche", "sera", "giro", "morte", "qua", "pensato", "buon", "anno",
        "mie", "diavolo", "quasi", "piacere", "bel", "dovrei", "nessun", "contro", "stessa", "felice",
        "colpa", "punto", "andata", "dovrebbe", "vedi", "quale", "chiesto", "invece", "perchè", "migliore",
        "nostri", "finito", "figlia", "dovresti", "papa", "almeno", "sento", "quei", "col", "ore",
        "passato", "magari", "minuti", "terra", "vostra", "strada", "sola", "credi", "importante", "sue",
        "salve", "settimana", "perso", "uscire", "parlato", "papà", "stasera", "scusi", "dollari", "occhi",
        "mani", "ultima", "possibile", "scuola", "significa", "sapevo", "nelle", "potrei", "stava", "bambini",
        "eri", "importa", "indietro", "riesco", "sangue", "chiama", "messo", "piccolo", "traduzione", "tardi",
        "cuore", "marito", "viene", "venuto", "ieri", "spero", "ricordi", "quelli", "dovremmo", "lasciato",
        "ascolta", "difficile", "auto", "chiamato", "ciò", "altre", "parlando", "pensare", "fantastico", "fatta",
        "numero", "veramente", "fanno", "serio", "possa", "fossi", "entrare", "qualsiasi", "pensa", "dicendo",
        "acqua", "portato", "stanza", "problemi", "forte", "nessuna", "lascia", "amo", "roba", "agente",
        "dietro", "corpo", "pare", "sentire", "foto", "telefono", "voleva", "poco", "prendi", "piccola",
        "vicino", "sacco", "stia", "capire", "potuto", "cinque", "strano", "tue", "andando", "donne",
        "sappiamo", "bravo", "ragazze", "festa", "senso", "genere", "quattro", "dare", "attimo", "sorella"
    };
}
