public static class Polish500Words
{
    // Frequency-ranked Polish, normalized to Unicode NFC.
    // Source: https://github.com/hermitdave/FrequencyWords/blob/master/content/2016/pl/pl_50k.txt
    public static readonly string[] Words = new string[]
    {
        "nie", "to", "się", "w", "na", "i", "że", "z", "co", "jest",
        "do", "tak", "o", "jak", "a", "ale", "mnie", "mi", "za", "ja",
        "tym", "tego", "ci", "czy", "go", "tylko", "tu", "po", "może", "jestem",
        "ty", "ma", "cię", "mam", "jesteś", "już", "dla", "jeśli", "wiem", "coś",
        "więc", "dobrze", "teraz", "od", "pan", "wszystko", "być", "masz", "nic", "tam",
        "będzie", "proszę", "mogę", "są", "jej", "on", "ten", "gdzie", "kiedy", "ze",
        "ciebie", "wiesz", "sobie", "był", "bardzo", "by", "było", "przez", "jego", "dlaczego",
        "chcę", "jeszcze", "mój", "ją", "pani", "nas", "no", "żeby", "chcesz", "ich",
        "tutaj", "bo", "też", "nigdy", "naprawdę", "mamy", "kto", "możesz", "przepraszam", "dobra",
        "mu", "porządku", "muszę", "ona", "nawet", "chyba", "dziękuję", "gdy", "domu", "zrobić",
        "prawda", "właśnie", "hej", "była", "będę", "te", "zawsze", "nam", "moja", "nim",
        "musisz", "je", "trochę", "tej", "dzięki", "bez", "ktoś", "panie", "jesteśmy", "moje",
        "powiedzieć", "który", "twój", "czas", "więcej", "lat", "prostu", "chce", "ta", "musimy",
        "wszyscy", "tobą", "możemy", "albo", "chodzi", "cześć", "razem", "stało", "czego", "mną",
        "sam", "myślę", "boże", "pana", "dalej", "raz", "przed", "będziesz", "ludzie", "czym",
        "niż", "czemu", "was", "dobry", "ludzi", "życie", "lepiej", "przy", "rzeczy", "dzień",
        "twoja", "miał", "robisz", "czasu", "niech", "myślisz", "kim", "daj", "temu", "chodź",
        "my", "cóż", "które", "powiedział", "moim", "tych", "siebie", "niego", "twoje", "oczywiście",
        "u", "nikt", "musi", "aby", "powiedz", "pod", "dlatego", "wtedy", "jeden", "wygląda",
        "pewnie", "mojego", "mówi", "im", "taki", "oni", "znaczy", "wszystkie", "mieć", "takie",
        "dziś", "dwa", "jako", "stąd", "wie", "potem", "dzieje", "moją", "będziemy", "nią",
        "mojej", "dużo", "wiele", "rozumiem", "iść", "miejsce", "kilka", "pomóc", "myśli", "byłem",
        "ile", "swoje", "jasne", "cały", "skąd", "dzieci", "nich", "wiedzieć", "można", "jakieś",
        "przykro", "jakiś", "wam", "sposób", "wszystkich", "nad", "która", "mają", "trzeba", "mówisz",
        "zanim", "robić", "tę", "zbyt", "niej", "kogoś", "bardziej", "szybko", "dzisiaj", "pracy",
        "tyle", "tobie", "zaraz", "kocham", "takiego", "kochanie", "miałem", "zobaczyć", "świetnie", "jaki",
        "mówię", "tą", "ponieważ", "ojciec", "myślałem", "pewno", "cholera", "rację", "robi", "ani",
        "stary", "trzy", "później", "idź", "życia", "stanie", "nadal", "twoim", "przestań", "mamo",
        "kiedyś", "swoją", "jutro", "długo", "nadzieję", "chciałem", "widzisz", "będą", "widzę", "aż",
        "tato", "problem", "żebyś", "każdy", "mógł", "dni", "wciąż", "taka", "nocy", "znowu",
        "twojej", "potrzebuję", "dziecko", "dnia", "słuchaj", "znaleźć", "pierwszy", "pieniądze", "powiem", "dokładnie",
        "nami", "sama", "czuję", "zrobił", "nasz", "nasze", "twoją", "widziałem", "razie", "gdyby",
        "jakie", "spokój", "dobre", "wy", "samo", "miała", "koniec", "były", "znam", "chciał",
        "wszystkim", "został", "chciałbym", "och", "mama", "spójrz", "wcześniej", "zostać", "żyje", "czegoś",
        "sobą", "zabić", "którzy", "mówić", "bym", "imię", "chwilę", "roku", "porozmawiać", "lub",
        "we", "poza", "mogą", "dom", "minut", "twojego", "drzwi", "powiedziałem", "miło", "posłuchaj",
        "prawie", "kogo", "jakby", "jeżeli", "jesteście", "którą", "wydaje", "czekaj", "człowiek", "powodu",
        "powinniśmy", "lubię", "gdzieś", "przecież", "sprawy", "mów", "końcu", "moich", "byłam", "byłeś",
        "pomysł", "żadnych", "broń", "panu", "razy", "innego", "zrobię", "pomocy", "ciągle", "facet",
        "wiemy", "jednak", "noc", "żebym", "podoba", "macie", "mówiłem", "którego", "dość", "miejscu",
        "źle", "powinieneś", "właściwie", "powiedziała", "ojca", "lata", "idziemy", "pamiętasz", "pokoju", "pewien",
        "niczego", "takim", "sprawa", "ego", "jedno", "znasz", "bądź", "dwie", "skoro", "którym",
        "sądzę", "swój", "swojego", "chodźmy", "zamknij", "byś", "rozumiesz", "samochód", "jedną", "idę",
        "myślałam", "spokojnie", "musiał", "oczy", "mały", "nowy", "również", "rzecz", "swoim", "których",
        "życiu", "podczas", "wystarczy", "której", "matka", "wczoraj", "rano", "świat", "całą", "byli",
        "pozwól", "chciałam", "weź", "sprawę", "nimi", "powinienem", "dwóch", "miałam", "jedna", "oto",
        "poważnie", "dać", "telefon", "numer", "całe", "wiedziałem", "dziewczyna", "pracę", "czujesz", "idzie",
        "da", "chcą", "cokolwiek", "wina", "dopóki", "powiedziałeś", "trzymaj", "śmierci", "nikogo", "prawdę",
        "wrócić", "miejsca", "mówił", "świecie", "swojej", "powiesz", "zrobiłem", "pamiętam", "halo", "swoich",
        "śmierć", "przynajmniej", "najpierw", "pytanie", "wyglądasz", "między", "widzieć", "jednego", "dam", "znów",
    };
}
