using System;

public static class Portuguese500Words
{
    public static readonly string[] Words = new string[]
    {
        "que", "não", "de", "um", "para", "eu", "uma", "está", "com", "se",
        "do", "por", "os", "ele", "mas", "em", "bem", "isso", "da", "como",
        "sim", "as", "no", "mais", "na", "meu", "aqui", "me", "muito", "foi",
        "ela", "isto", "estou", "fazer", "vamos", "já", "ser", "vai", "minha", "só",
        "ao", "tem", "tudo", "te", "porque", "há", "tenho", "vou", "tu", "sei",
        "quando", "agora", "estás", "você", "lá", "então", "ter", "era", "quem", "onde",
        "nada", "ou", "coisa", "dizer", "são", "quero", "estava", "sou", "seu", "pode",
        "mesmo", "esta", "eles", "nós", "sua", "dos", "todos", "nos", "mim", "posso",
        "bom", "ver", "este", "casa", "temos", "tens", "tua", "nunca", "estão", "até",
        "assim", "teu", "acho", "falar", "disse", "ainda", "tempo", "também", "ir", "pai",
        "sobre", "vez", "quê", "quer", "és", "favor", "depois", "tão", "melhor", "mãe",
        "talvez", "olá", "obrigado", "noite", "ti", "sabes", "sempre", "deus", "estamos", "alguém",
        "dia", "certo", "nem", "alguma", "vida", "anos", "dele", "sem", "vais", "das",
        "tinha", "estar", "queres", "coisas", "homem", "pessoas", "algo", "pelo", "ficar", "boa",
        "sabe", "parece", "claro", "dois", "verdade", "tipo", "preciso", "antes", "senhor", "lhe",
        "podes", "apenas", "faz", "vocês", "ninguém", "trabalho", "outra", "espera", "saber", "comigo",
        "vão", "dinheiro", "aí", "podemos", "pouco", "essa", "esse", "grande", "pois", "pela",
        "qualquer", "disso", "num", "qual", "desculpa", "dela", "hoje", "toda", "deve", "mulher",
        "queria", "fora", "filho", "cá", "seja", "meus", "nosso", "olha", "vá", "daqui",
        "sério", "oh", "nossa", "certeza", "diz", "nome", "às", "outro", "todo", "dar",
        "tentar", "sair", "têm", "quanto", "pensar", "mal", "volta", "aconteceu", "consigo", "três",
        "mundo", "menos", "amigo", "contigo", "embora", "numa", "passa", "porquê", "problema", "carro",
        "lado", "vezes", "nas", "fez", "seus", "novo", "parte", "todas", "aos", "obrigada",
        "primeiro", "será", "lugar", "voltar", "pensei", "algum", "achas", "vem", "dentro", "família",
        "ali", "razão", "aquele", "dias", "fui", "anda", "querida", "sabia", "duas", "ideia",
        "hora", "si", "polícia", "podem", "forma", "entre", "caso", "gosto", "atrás", "homens",
        "devia", "aquilo", "amor", "pessoa", "ok", "podia", "uns", "desde", "somos", "cabeça",
        "horas", "deles", "fica", "ajudar", "tarde", "momento", "tal", "tenha", "pronto", "fiz",
        "foram", "ia", "cidade", "amigos", "encontrar", "frente", "sido", "passar", "deixar", "vi",
        "nenhum", "gente", "durante", "seria", "outros", "entrar", "chegar", "nova", "trabalhar", "quase",
        "desculpe", "amanhã", "tanto", "fosse", "história", "irmão", "cima", "contra", "morrer", "maneira",
        "suas", "enquanto", "alguns", "ajuda", "precisa", "morto", "primeira", "porta", "minhas", "medo",
        "morte", "aquela", "óptimo", "caminho", "vir", "feliz", "sinto", "minutos", "ouvir", "desta",
        "tive", "neste", "matar", "cada", "estes", "acontecer", "espero", "ano", "rapaz", "precisamos",
        "for", "causa", "feito", "sorte", "lamento", "filha", "acha", "teus", "levar", "conta",
        "estas", "arma", "pessoal", "quarto", "olhos", "senhora", "adeus", "cara", "disto", "algumas",
        "juntos", "difícil", "última", "única", "manhã", "importante", "poder", "mãos", "ei", "água",
        "começar", "faço", "perto", "cuidado", "sangue", "nossos", "semana", "mesma", "usar", "significa",
        "acredito", "querem", "cinco", "acabou", "problemas", "corpo", "altura", "disseste", "nisso", "chefe",
        "jogo", "guerra", "fala", "procura", "sabemos", "fizeste", "ouve", "realmente", "terra", "havia",
        "ontem", "umas", "dólares", "comer", "dormir", "dá", "escola", "logo", "querido", "sabem",
        "fim", "deste", "eram", "pára", "agente", "equipa", "rapariga", "marido", "calma", "coração",
        "segurança", "viver", "estado", "parar", "teve", "segundo", "muitas", "quatro", "mão", "baixo",
        "maior", "meio", "meses", "mau", "vê", "ouvi", "andar", "rápido", "número", "vejo",
        "mulheres", "morreu", "nenhuma", "acordo", "festa", "fazes", "capitão", "raio", "pais", "suficiente",
        "poderia", "crianças", "estavam", "força", "muitos", "nesta", "presidente", "buscar", "filhos", "perder",
        "esperar", "viu", "irmã", "chega", "possível", "devias", "sai", "acabar", "rapazes", "precisas",
        "elas", "contar", "idiota", "olhar", "vossa", "teria", "foste", "estavas", "pena", "mil",
        "longe", "faça", "penso", "tivesse", "tuas", "pedir", "estranho", "importa", "fácil", "muita",
        "veio", "brincar", "bebé", "plano", "devo", "prazer", "velho", "conseguir", "passado", "tomar"
    };
}
