public static class Romanian500Words
{
    // Frequency-ranked spoken Romanian, normalized to modern Romanian diacritics.
    // Source: https://github.com/hermitdave/FrequencyWords/blob/master/content/2016/ro/ro_50k.txt
    public static readonly string[] Words = new string[]
    {
        "de", "nu", "să", "o", "e", "în", "ce", "și", "că", "la",
        "a", "cu", "pe", "am", "un", "mai", "asta", "pentru", "sunt", "ai",
        "este", "te", "ca", "da", "bine", "dar", "se", "din", "care", "fost",
        "fi", "mă", "sa", "eu", "aici", "dacă", "trebuie", "va", "cum", "tu",
        "acum", "așa", "ceva", "ar", "lui", "el", "ești", "când", "doar", "ne",
        "ei", "mine", "tine", "poate", "pot", "cred", "voi", "face", "îmi", "au",
        "mea", "știu", "spus", "unde", "meu", "vă", "vreau", "mult", "ea", "vrei",
        "despre", "tot", "foarte", "sau", "pare", "acolo", "chiar", "bună", "noi", "era",
        "ta", "nimic", "faci", "are", "făcut", "cine", "nici", "știi", "putea", "fac",
        "fie", "trebui", "nevoie", "rău", "atunci", "îți", "timp", "tău", "rog", "spun",
        "poți", "avem", "spune", "îl", "al", "le", "prea", "după", "mulțumesc", "deci",
        "cineva", "vom", "acest", "toate", "ani", "cel", "suntem", "vei", "sigur", "bun",
        "vrea", "vor", "îi", "haide", "iar", "mare", "până", "cât", "crezi", "stai",
        "încă", "ăsta", "avea", "totul", "spui", "venit", "atât", "avut", "hei", "văzut",
        "fel", "putem", "lucru", "ceea", "aș", "place", "fără", "mama", "domnule", "decât",
        "regulă", "niciodată", "prin", "puțin", "mergem", "înainte", "văd", "uite", "unul", "nimeni",
        "loc", "hai", "vezi", "fii", "dat", "toată", "apoi", "întâmplat", "oameni", "facem",
        "nou", "ia", "multe", "zi", "acasă", "toți", "două", "lumea", "jos", "timpul",
        "doi", "orice", "auzit", "oamenii", "astea", "aia", "fiecare", "luat", "peste", "niște",
        "ați", "fiu", "vrut", "trei", "înapoi", "această", "lor", "numele", "cea", "dintre",
        "merge", "om", "doamne", "găsit", "cei", "mele", "viața", "duc", "ziua", "serios",
        "aceasta", "deja", "parte", "gata", "dată", "câteva", "vino", "vedem", "destul", "bani",
        "vorbesc", "numai", "aproape", "dau", "una", "zis", "tatăl", "înseamnă", "eram", "vin",
        "afară", "nostru", "există", "întâmplă", "scuze", "cam", "locul", "adevărat", "noastră", "vine",
        "ori", "repede", "fapt", "grijă", "acesta", "probabil", "prima", "tale", "putut", "știe",
        "exact", "ajuns", "casa", "singur", "lucruri", "sunteți", "simt", "dreptate", "noapte", "trecut",
        "tocmai", "târziu", "iau", "partea", "zile", "adică", "cele", "seara", "mereu", "lucrurile",
        "facă", "unui", "imediat", "azi", "omule", "spre", "împreună", "plecat", "trebuia", "terminat",
        "crezut", "iubesc", "început", "copii", "departe", "măcar", "pierdut", "mi", "banii", "treaba",
        "tata", "sub", "frumos", "aceste", "vorba", "mâine", "plec", "mamă", "tată", "mei",
        "ăla", "viață", "tipul", "păi", "greu", "minute", "dai", "sus", "drumul", "dumnezeu",
        "vedea", "mie", "înțeleg", "desigur", "murit", "aveți", "ajuta", "trebuit", "idee", "data",
        "aceea", "ale", "tip", "ultima", "femeie", "sper", "primul", "gândit", "așteaptă", "vreo",
        "copil", "erau", "seama", "tare", "pus", "bune", "problema", "merg", "moment", "dus",
        "noastre", "înțeles", "camera", "griji", "între", "minunat", "își", "lua", "cauza", "pic",
        "poftim", "duci", "ajunge", "mort", "ba", "ajutor", "urmă", "vorbim", "ore", "noaptea",
        "vorbești", "corect", "ciudat", "ele", "unei", "simți", "problemă", "probleme", "încercat", "pune",
        "întotdeauna", "ucis", "credeam", "cazul", "vorbit", "adus", "fiul", "față", "vreodată", "cap",
        "luni", "vii", "crede", "familia", "cer", "ales", "duce", "cale", "altă", "bucur",
        "nicio", "uitat", "cunosc", "ascultă", "casă", "fața", "joc", "oricum", "iei", "caz",
        "ochii", "altceva", "lume", "băieți", "singură", "mergi", "patru", "cinci", "mulți", "încredere",
        "veni", "siguranță", "salut", "prins", "mașina", "acord", "primit", "fată", "telefon", "grozav",
        "lăsat", "ușor", "acel", "dolari", "fratele", "lângă", "puteți", "prieten", "important", "câte",
        "zici", "asemenea", "mașină", "vina", "omul", "dragă", "pun", "faceți", "știm", "găsi",
        "vorbi", "simplu", "sunat", "odată", "doamnă", "mâna", "pasă", "pleci", "ora", "stau",
        "prieteni", "alte", "arată", "pleacă", "drum", "mod", "întors", "mic", "acea", "alo",
        "singura", "legătură", "treabă", "aveam", "nouă", "alt", "curând", "chestia", "capul", "gând",
        "soția", "începe", "spate", "astfel", "noroc", "trimis", "posibil", "către", "singurul", "veți",
        "mersi", "apă", "oraș", "inima", "încearcă", "copilul", "las", "frumoasă", "știți", "bărbat",
        "nume", "taci", "adevărul", "prietenul", "știam", "auzi", "domnul", "niciun", "tăi", "rămâne"
    };
}
