using System;

public static class Spanish500Words
{
    public static readonly string[] Words = new string[]
    {
        "el", "la", "de", "que", "y", "a", "en", "un", "ser", "se",
        "no", "haber", "por", "con", "su", "para", "como", "estar", "tener", "le",
        "lo", "todo", "pero", "más", "hacer", "o", "poder", "decir", "este", "ir",
        "otro", "ese", "la", "si", "me", "ya", "ver", "porque", "dar", "cuando",
        "él", "muy", "sin", "vez", "mucho", "saber", "qué", "sobre", "mi", "alguno",
        "mismo", "yo", "también", "hasta", "año", "dos", "querer", "entre", "así", "primero",
        "desde", "grande", "eso", "ni", "nos", "llegar", "pasar", "tiempo", "ella", "sí",
        "día", "uno", "bien", "poco", "deber", "entonces", "poner", "cosa", "tanto", "hombre",
        "parecer", "nuestro", "tan", "donde", "ahora", "parte", "después", "vida", "quedar", "siempre",
        "creer", "hablar", "llevar", "dejar", "nada", "cada", "seguir", "menos", "nuevo", "encontrar",
        "algo", "solo", "decir", "salir", "venir", "pensar", "tomar", "nadie", "mano", "parecer",
        "trabajo", "llamar", "volver", "sacar", "conocer", "mientras", "último", "pueblo", "empezar", "cual",
        "aunque", "sentir", "necesitar", "mismo", "tanto", "cual", "medio", "vez", "pedir", "partir",
        "contra", "casa", "momento", "hijo", "además", "aunque", "nunca", "manera", "problema", "punto",
        "estar", "mayor", "menos", "durante", "ninguno", "ciudad", "dar", "cuenta", "caso", "importar",
        "entrar", "grande", "cerca", "tiempo", "día", "año", "llevar", "país", "dejar", "dentro",
        "medio", "igual", "volver", "conocer", "llegar", "hablar", "creer", "encontrar", "seguir", "menos",
        "ninguno", "comprar", "salir", "venir", "pensar", "tomar", "nadie", "mientras", "aunque", "sentir",
        "nuevo", "mundo", "estado", "vida", "hacer", "cuenta", "historia", "ser", "estar", "haber",
        "tener", "poder", "decir", "ver", "dar", "saber", "querer", "llegar", "pasar", "deber",
        "poner", "parecer", "quedar", "creer", "hablar", "llevar", "dejar", "seguir", "encontrar", "llamar",
        "venir", "pensar", "salir", "volver", "tomar", "conocer", "vivir", "sentir", "tratar", "mirar",
        "contar", "empezar", "esperar", "buscar", "existir", "entrar", "trabajar", "escribir", "perder", "producir",
        "ocurrir", "entender", "pedir", "recibir", "recordar", "terminar", "permitir", "aparecer", "conseguir", "comenzar",
        "servir", "sacar", "necesitar", "mantener", "resultar", "leer", "caer", "cambiar", "presentar", "crear",
        "abrir", "considerar", "oír", "acabar", "mil", "contra", "sin", "caso", "nivel", "obra",
        "fin", "verdad", "cuerpo", "libro", "forma", "cara", "grupo", "mesa", "lugar", "campo",
        "fuerza", "amor", "objeto", "realidad", "razón", "mujer", "vista", "precio", "muerte", "acción",
        "cabeza", "pie", "nombre", "número", "palabra", "hermano", "edad", "tierra", "lado", "centro",
        "rey", "padre", "madre", "luz", "guerra", "señor", "ley", "puerta", "orden", "tarde",
        "agua", "fuego", "gente", "calle", "voz", "arte", "papel", "color", "negro", "blanco",
        "rojo", "verde", "azul", "amarillo", "viejo", "joven", "largo", "corto", "alto", "bajo",
        "fuerte", "débil", "rico", "pobre", "bueno", "malo", "mejor", "peor", "primero", "último",
        "solo", "único", "propio", "otro", "mismo", "tanto", "poco", "mucho", "todo", "varios",
        "cierto", "verdadero", "falso", "posible", "imposible", "fácil", "difícil", "simple", "complejo", "claro",
        "oscuro", "público", "privado", "general", "especial", "común", "raro", "normal", "extraño", "natural",
        "artificial", "libre", "igual", "diferente", "similar", "contrario", "anterior", "posterior", "interior", "exterior",
        "superior", "inferior", "central", "lateral", "total", "parcial", "completo", "incompleto", "lleno", "vacío",
        "limpio", "sucio", "sano", "enfermo", "vivo", "muerto", "abierto", "cerrado", "derecho", "izquierdo",
        "arriba", "abajo", "delante", "detrás", "dentro", "fuera", "cerca", "lejos", "aquí", "allí",
        "siempre", "nunca", "también", "tampoco", "sí", "no", "tal", "cual", "quien", "donde",
        "cuando", "como", "porque", "para", "por", "con", "sin", "sobre", "bajo", "ante",
        "tras", "entre", "durante", "mediante", "según", "hasta", "desde", "hacia", "contra", "excepto",
        "salvo", "menos", "incluso", "además", "pero", "sino", "aunque", "pues", "luego", "así",
        "entonces", "todavía", "aún", "apenas", "pronto", "tarde", "temprano", "ahora", "hoy", "ayer",
        "mañana", "antes", "después", "luego", "siempre", "nunca", "jamás", "acaso", "quizá", "tal",
        "otro", "más", "bien", "solo", "vez", "año", "día", "mes", "hora", "minuto",
        "segundo", "siglo", "semana", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo",
        "enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre",
        "noviembre", "diciembre", "primavera", "verano", "otoño", "invierno", "clima", "tiempo", "sol", "luna"
    };
}