using System;

public static class Spanish500Words
{
    public static readonly string[] Words = new string[]
    {
        "de", "que", "no", "la", "el", "es", "en", "lo", "un", "por",
        "qué", "me", "una", "los", "se", "te", "con", "para", "está", "mi",
        "pero", "sí", "si", "bien", "eso", "su", "las", "yo", "del", "como",
        "aquí", "tu", "al", "más", "le", "esto", "todo", "ya", "estoy", "ahora",
        "muy", "ha", "esta", "así", "vamos", "algo", "hay", "bueno", "tengo", "él",
        "cuando", "estás", "sé", "tú", "nos", "nada", "cómo", "este", "he", "ser",
        "tiene", "puedo", "ella", "quiero", "hacer", "fue", "gracias", "vez", "era", "soy",
        "sólo", "todos", "porque", "son", "tienes", "creo", "voy", "sabes", "estaba", "puede",
        "eres", "ese", "usted", "entonces", "hola", "solo", "verdad", "casa", "tan", "quién",
        "sus", "tiempo", "dos", "esa", "nunca", "dónde", "va", "oh", "favor", "mucho",
        "mí", "quieres", "siento", "señor", "mejor", "hace", "has", "decir", "también", "sobre",
        "dios", "sin", "tenemos", "están", "ti", "puedes", "ver", "hombre", "vida", "alguien",
        "cosas", "siempre", "hasta", "ahí", "ir", "años", "antes", "estar", "ni", "poco",
        "día", "uno", "noche", "hecho", "mis", "estamos", "otra", "acuerdo", "trabajo", "nosotros",
        "parece", "gente", "sea", "padre", "mira", "mismo", "dijo", "nadie", "quiere", "podría",
        "hablar", "vas", "ellos", "tal", "pasa", "fuera", "después", "han", "desde", "dinero",
        "mundo", "claro", "momento", "les", "tener", "estado", "otro", "había", "mañana", "tenía",
        "madre", "vale", "lugar", "haciendo", "donde", "seguro", "sabe", "podemos", "tus", "espera",
        "nuevo", "sido", "cosa", "hijo", "allí", "menos", "tipo", "amigo", "gran", "nuestro",
        "mujer", "mamá", "luego", "papá", "días", "dice", "hoy", "tres", "buena", "necesito",
        "dije", "oye", "gusta", "quería", "será", "haber", "parte", "todas", "crees", "buen",
        "conmigo", "nombre", "nuestra", "mal", "debe", "realmente", "estas", "aún", "mío", "toda",
        "hacerlo", "cada", "visto", "importa", "contigo", "tienen", "hemos", "razón", "alguna", "tanto",
        "saber", "hizo", "veces", "serio", "ven", "idea", "eh", "tarde", "problema", "hora",
        "cierto", "dicho", "quien", "demasiado", "amor", "entre", "ve", "pasado", "familia", "estos",
        "policía", "debería", "ustedes", "chica", "esos", "chicos", "cuenta", "haces", "todavía", "salir",
        "algún", "vaya", "unos", "veo", "amigos", "hermano", "pensé", "sabía", "cabeza", "ah",
        "cariño", "digo", "van", "hombres", "buenas", "somos", "cualquier", "forma", "mientras", "lado",
        "debo", "sería", "caso", "pueden", "pasó", "primera", "genial", "chico", "supuesto", "hice",
        "pues", "adiós", "muchas", "personas", "señora", "volver", "esas", "quizá", "contra", "camino",
        "durante", "hablando", "manera", "muerto", "persona", "rápido", "cuál", "ayuda", "historia", "iba",
        "supongo", "nueva", "entiendo", "dentro", "casi", "puerta", "ves", "pasar", "primero", "significa",
        "semana", "hacia", "quizás", "espero", "juntos", "año", "niños", "pronto", "tío", "suerte",
        "ciudad", "siquiera", "feliz", "venir", "hija", "gustaría", "minutos", "cuánto", "os", "hey",
        "muerte", "dejar", "realidad", "deja", "problemas", "vi", "da", "importante", "dijiste", "corazón",
        "miedo", "jefe", "agua", "haré", "justo", "horas", "poder", "buenos", "esposa", "manos",
        "debes", "viene", "venga", "nuestros", "ojos", "adelante", "encontrar", "mano", "cinco", "niño",
        "ninguna", "otros", "cara", "cuidado", "bajo", "cerca", "viejo", "déjame", "noches", "bastante",
        "fin", "tomar", "único", "misma", "escucha", "ningún", "suficiente", "punto", "cuándo", "sigue",
        "haya", "equipo", "grande", "necesita", "llegar", "incluso", "algunos", "doctor", "difícil", "aunque",
        "hubiera", "primer", "coche", "hago", "clase", "cuatro", "mas", "dices", "pequeño", "llama",
        "toma", "hiciste", "allá", "última", "arriba", "tierra", "guerra", "pensar", "pueda", "igual",
        "loco", "sangre", "mujeres", "vuelta", "fui", "trabajar", "tenido", "juego", "deberías", "cuerpo",
        "algunas", "entrar", "cree", "podía", "debemos", "oportunidad", "teléfono", "necesitamos", "final", "listo",
        "fiesta", "muchos", "estabas", "quieren", "vete", "auto", "dar", "vivir", "posible", "ok",
        "hermana", "número", "meses", "exactamente", "culpa", "abajo", "escuela", "ido", "fuerte", "diciendo",
        "habla", "esté", "ello", "pregunta", "chicas", "eran", "unas", "pasando", "atrás", "malo",
        "capitán", "bebé", "segundo", "sabemos", "mayor", "comida", "morir", "conozco", "dame", "fácil",
        "comer", "vino", "lista", "haga", "necesitas", "hijos", "probablemente", "padres", "habitación", "creer",
        "pensando", "fueron", "dime", "trata", "buscando", "tuve", "tampoco", "amo", "joven", "podrías"
    };
}
