using System;

public static class Swedish500Words
{
    public static readonly string[] Words = new string[]
    {
        "jag", "det", "är", "du", "att", "inte", "en", "och", "har", "vi",
        "på", "för", "han", "med", "som", "om", "var", "vad", "mig", "här",
        "dig", "så", "den", "kan", "till", "de", "men", "ett", "ska", "ni",
        "av", "hon", "vill", "ja", "vet", "nu", "nej", "bara", "hur", "min",
        "kommer", "där", "måste", "honom", "gör", "din", "skulle", "när", "då", "kom",
        "ha", "bra", "får", "man", "vara", "oss", "ut", "ta", "er", "göra",
        "okej", "eller", "hade", "från", "varför", "dem", "alla", "tror", "sig", "allt",
        "henne", "upp", "sa", "ingen", "tack", "gå", "in", "igen", "få", "nåt",
        "se", "går", "mycket", "hej", "vem", "kanske", "lite", "behöver", "ser", "mitt",
        "aldrig", "finns", "än", "inget", "efter", "blir", "ju", "hans", "sen", "bli",
        "gjorde", "två", "nån", "tillbaka", "tar", "mer", "något", "över", "säger", "fick",
        "ditt", "ge", "väl", "också", "mina", "åt", "nog", "fan", "kunde", "år",
        "säga", "någon", "mamma", "varit", "ner", "ville", "vänta", "mot", "pappa", "andra",
        "borde", "känner", "rätt", "vid", "några", "hela", "såg", "hit", "prata", "komma",
        "låt", "detta", "gjort", "blev", "själv", "tog", "alltid", "vår", "utan", "fel",
        "hem", "mr", "dag", "dina", "liv", "menar", "verkligen", "visst", "va", "förstår",
        "sin", "tid", "trodde", "gick", "älskar", "sätt", "berätta", "tänker", "döda", "veta",
        "tre", "många", "folk", "sluta", "precis", "inga", "hennes", "titta", "innan", "visste",
        "gillar", "barn", "bättre", "hjälpa", "under", "förlåt", "gång", "bort", "hjälp", "händer",
        "just", "helt", "säg", "tycker", "första", "död", "håll", "länge", "hör", "sett",
        "ledsen", "snälla", "saker", "hitta", "fortfarande", "står", "pengar", "god", "samma", "sir",
        "ens", "ursäkta", "heter", "håller", "vilken", "enda", "gud", "våra", "hand", "borta",
        "mår", "hallå", "hände", "ur", "problem", "vän", "ger", "stanna", "sak", "dom",
        "försöker", "låter", "far", "kvar", "väg", "annan", "redan", "längre", "jävla", "helvete",
        "pratar", "väldigt", "åh", "herregud", "vart", "dit", "kväll", "morgon", "fått", "snart",
        "ute", "fråga", "sitt", "tiden", "kör", "deras", "tänkte", "namn", "verkar", "tro",
        "jo", "varje", "fram", "bästa", "fru", "först", "träffa", "säkert", "slut", "sedan",
        "hos", "ingenting", "därför", "åka", "visa", "säker", "lämna", "börjar", "vägen", "genom",
        "gav", "härifrån", "jobb", "hålla", "son", "stor", "vänner", "hittade", "annat", "hoppas",
        "sina", "hörde", "vilket", "kolla", "minns", "ihop", "rädd", "sista", "även", "era",
        "sex", "vårt", "kunna", "ses", "del", "nästa", "fem", "livet", "nya", "människor",
        "bilen", "dö", "riktigt", "klarar", "höra", "tills", "liten", "betyder", "tänk", "tag",
        "lyssna", "polisen", "ändå", "sagt", "hemma", "sant", "världen", "fast", "faktiskt", "ligger",
        "skit", "idag", "minuter", "familj", "runt", "blivit", "klart", "fall", "väntar", "dog",
        "fyra", "dra", "dollar", "åker", "kul", "tala", "illa", "män", "försökte", "dödade",
        "helst", "annars", "haft", "sånt", "nästan", "ensam", "inne", "lika", "lägg", "hittar",
        "redo", "hämta", "jobbar", "dr", "gången", "båda", "ny", "denna", "stora", "plats",
        "tur", "börja", "svårt", "lugnt", "långt", "spelar", "kvinna", "känns", "älskling", "hänt",
        "bil", "emot", "låta", "tillsammans", "öppna", "släpp", "hört", "huset", "senare", "bror",
        "ringer", "lilla", "be", "rör", "ibland", "rädda", "heller", "fort", "glad", "gått",
        "mellan", "nära", "ifrån", "hus", "vore", "igenom", "fler", "kände", "vilka", "dotter",
        "bryr", "dagar", "kille", "tänka", "bor", "fattar", "gärna", "fanns", "ber", "började",
        "killen", "sitter", "slå", "ännu", "tio", "trevligt", "vilja", "gott", "spela", "bäst",
        "chans", "gånger", "varandra", "timmar", "lever", "pengarna", "äta", "handlar", "natt", "rum",
        "klara", "mor", "gamla", "ord", "ihåg", "reda", "ringa", "mannen", "ert", "dags",
        "bakom", "eftersom", "gammal", "jobbet", "dörren", "fara", "känna", "dessa", "all", "dör",
        "sån", "par", "bad", "hjälper", "alls", "tyst", "egen", "kommit", "ringde", "dagen",
        "klar", "galen", "stan", "leva", "syster", "oroa", "mat", "vapen", "john", "ring",
        "skull", "stället", "antar", "tagit", "vadå", "sätta", "stå", "mrs", "jaså", "berättade",
        "ganska", "följer", "klockan", "tidigare", "hittat", "följa", "räcker", "fint", "lätt", "försöka"
    };
}
