using System;

public static class Turkish500Words
{
    public static readonly string[] Words = new string[]
    {
        "bir", "bu", "ne", "ve", "için", "mi", "de", "ben", "çok", "ama",
        "evet", "var", "da", "mı", "değil", "şey", "hayır", "daha", "sen", "kadar",
        "bana", "gibi", "yok", "bunu", "onu", "iyi", "tamam", "beni", "seni", "her",
        "benim", "sana", "ki", "ya", "neden", "zaman", "sadece", "senin", "burada", "olduğunu",
        "nasıl", "hiç", "sonra", "şimdi", "en", "öyle", "mu", "şu", "misin", "önce",
        "biraz", "hadi", "güzel", "musun", "oldu", "yani", "böyle", "ona", "iyi", "lütfen",
        "onun", "bile", "bak", "çünkü", "peki", "eğer", "artık", "gerçekten", "geri", "biliyorum",
        "istiyorum", "kim", "olarak", "başka", "belki", "tek", "doğru", "büyük", "olan", "biri",
        "olur", "buraya", "bay", "in", "olacak", "adam", "ile", "hiçbir", "biz", "yardım",
        "demek", "hey", "sanırım", "ın", "bilmiyorum", "bunun", "tüm", "teşekkürler", "fazla", "yeni",
        "gün", "ederim", "nerede", "tanrım", "şeyi", "merhaba", "efendim", "orada", "son", "kötü",
        "şeyler", "gece", "biliyor", "sorun", "iki", "harika", "gerek", "et", "tam", "işte",
        "bütün", "diye", "hemen", "siz", "üzgünüm", "ol", "olabilir", "olsun", "küçük", "size",
        "yüzden", "bayan", "aynı", "teşekkür", "hakkında", "tabii", "gel", "onları", "kendi", "kız",
        "nin", "devam", "bize", "oluyor", "ver", "izin", "iş", "bizi", "buna", "anne",
        "selam", "vardı", "geldi", "bizim", "sizi", "dur", "kimse", "göre", "asla", "özür",
        "seninle", "baba", "değilim", "aslında", "önemli", "tekrar", "git", "nın", "yoksa", "hala",
        "işte", "oh", "benimle", "içinde", "mısın", "yine", "mü", "bence", "şekilde", "olmak",
        "bugün", "söyle", "birlikte", "olmaz", "pekala", "uzun", "lazım", "biliyorsun", "zaten", "para",
        "ilk", "geliyor", "onunla", "gerçek", "dostum", "al", "bakalım", "onlar", "haydi", "birkaç",
        "emin", "üç", "herkes", "dakika", "söyledi", "istiyorsun", "pek", "ister", "saat", "yapıyorsun",
        "eve", "yıl", "miyim", "çocuk", "yer", "hep", "şunu", "neler", "dilerim", "bekle",
        "sizin", "bırak", "olduğu", "ilgili", "gidelim", "yere", "etmek", "an", "dan", "nedir",
        "un", "nereye", "hepsi", "istemiyorum", "olmalı", "buradan", "lanet", "karşı", "kaç", "az",
        "burası", "hazır", "fakat", "eski", "çocuklar", "kendini", "ediyorum", "gerekiyor", "benden", "yapmak",
        "kadın", "söz", "kesinlikle", "zor", "işe", "anda", "tane", "diğer", "dinle", "bunlar",
        "işi", "kişi", "görmek", "kabul", "niye", "istiyor", "seviyorum", "aman", "sağ", "zorunda",
        "misiniz", "tanrı", "yarın", "kez", "bundan", "iki", "elbette", "falan", "gidip", "hem",
        "yanlış", "onlara", "senden", "hoş", "doktor", "tatlım", "yapma", "özel", "yemek", "hafta",
        "kontrol", "ediyor", "gereken", "yerde", "oraya", "geç", "dedim", "mutlu", "ye", "bazı",
        "birini", "ayrıca", "ondan", "eminim", "nereden", "etti", "dışarı", "beri", "gitti", "yalan",
        "edin", "bakın", "yalnız", "insan", "gördüm", "değildi", "merak", "insanlar", "polis", "ihtiyacım",
        "erkek", "görüşürüz", "dün", "ah", "haber", "la", "musunuz", "babam", "gidiyor", "yi",
        "olmuş", "akşam", "den", "geçen", "sakin", "ha", "sanki", "beş", "karar", "nefret",
        "sabah", "yaptım", "veya", "dikkat", "umarım", "yerine", "çabuk", "etme", "olması", "farklı",
        "değilsin", "ay", "sonunda", "gördün", "ettim", "sence", "fark", "üzerinde", "aptal", "kendimi",
        "tamamen", "oldukça", "su", "boyunca", "kendine", "tarafından", "yeter", "dünya", "yı", "olduğumu",
        "bunları", "vardır", "öldü", "olursa", "açık", "neyse", "annem", "kes", "ilk", "istediğim",
        "adı", "yaptın", "yap", "hangi", "olamaz", "ancak", "söyledim", "görünüyor", "dört", "yüzünden",
        "aldım", "olsa", "birşey", "birisi", "be", "yoktu", "kolay", "dolar", "dedi", "sahip",
        "ise", "olmadığını", "yanında", "gelecek", "adamı", "bende", "buldum", "yol", "geldim", "bazen",
        "konuşmak", "başına", "gitmek", "anlıyorum", "beraber", "henüz", "yapıyor", "yolu", "bitti", "onların",
        "cevap", "evde", "yardımcı", "zamanı", "almak", "konusunda", "genç", "oldum", "nun", "takip",
        "kal", "öyleyse", "kahretsin", "durum", "tabi", "günü", "ateş", "adamın", "muhtemelen", "adım",
        "istedim", "söylemek", "azından", "düşündüm", "le", "yaptı", "neredeyse", "eder", "olun", "yeniden",
        "düşünüyorsun", "ciddi", "vay", "herhangi", "ev", "hızlı", "sanmıyorum", "süre", "içeri", "altında",
        "mükemmel", "göz", "kan", "düşünüyorum", "ara", "boş", "miyiz", "konuda", "halde", "duydum",
        "oğlum", "şeyin", "uzak", "gelen", "aç", "işin", "hayatta", "çıktı", "sakın", "saniye",
        "yakın", "anladım", "garip", "john", "olduğuna", "on", "arada", "hayal", "gidiyorum", "araba",
        "çeviri", "çalışıyorum", "jack", "söylüyor", "sürü", "hepimiz", "kaldı", "galiba", "canım", "hayatım"
    };
}
