using System;

namespace StdbModule;

public static partial class ArabicQuotes
{
    public static class إيلياأبوماضي
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قال السماء كئيبة ! وتجهما قلت: ابتسم يكفي التجهم في السما !", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قال: الصبا ولى! فقلت له: ابتــسم لن يرجع الأسف الصبا المتصرما !!", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلـــت: ابتسم واطرب فلو قارنتها لقضيت عــــمرك كــله متألما", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلت: ابتسم ما أنت جالب دائها وشفائها, فإذا ابتسمت فربما", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلت: ابتسم, لم يطلبوك بذمهم لو لم تكن منهم أجل وأعظما !", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلت: ابتسم, يكفيك أنك لم تز ل حيا, ولست من الأحبة معدما!", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلت: ابتسم ولئن جرعت العلقما فلعل غيرك إن رآك مرنما طرح الكآبة جانبا وترنما", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أتُراك تغنم بالتبرم درهما أم أنت تخسر بالبشاشة مغنما ؟", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "يا صاح, لا خطر على شفتيك أن تتثلما, والوجه أن يتحطما", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فاضحك فإن الشهب تضحك والدجى متلاطم, ولذا نحب الأنجما !", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلت ابتسم مادام بينك والردى شبر, فإنك بعد لن تتبسما", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أيّها الشاكي الليالي إنَّما الغبطةُ فِكْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تلمسُ الغصنَ المُعَرَّى فإذا في الغصنِ نُضْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وإذا رفَّتْ على القَفْرِ استوى ماءً وخُضْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وإذا مَسَّتْ حصاةً صَقَلَتْها فهيَ دُرَّهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لَكَ ، ما دامتْ لكَ ، الأرضُ وما فوق المَجَرَّهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فإذا ضَيَّعْتَها فالكونُ لا يَعْدِلُ ذَرَّهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أيُّها الباكي رويداً لا يسدُّ الدمعُ ثغرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أيّها العابسُ لن تُعطَى على التقطيبِ أُجْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا تكنْ مُرَّاً ، ولا تجعَلْ حياةَ الغيرِ مُرَّهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "إِنَّ من يبكي لهُ حَوْلٌ على الضحكِ وقُدْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فتَهَلَّلْ وتَرَنَّمْ ، فالفتى العابسُ صَخْرَهْ", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كيف تغدو إذا غدوت عليلا؟", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "انّ شرّ الجناة في الأرض نفس تتوقّى قبل الرّحيل ، الرّحيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وترى الشّوك في الورود ، وتعمى أن ترى فوقها النّدى إكليلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "هو عبء على الحياة ثقيل من يظنّ الحياة عبئا ثقيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "والذي نفسه بغير جمال لا يرى في الوجود شيئا جميلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ليس أشقى مّمن يرى العيش مرا ويظنّ اللّذات فيه فضولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أحكم النّاس في الحياة أناس عللّوها فأحسنوا التّعليلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فتمتّع بالصّبح ما دمت فيه لا تخف أن يزول حتى يزولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وإذا ما أظلّ رأسك همّ قصّر البحث فيه كيلا يطولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أدركت كنهها طيور الرّوابي فمن العار أن تظل جهولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ما تراها_ والحقل ملك سواها تخذت فيه مسرحا ومقيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تتغنّى، والصّقر قد ملك الجوّ عليها ، والصائدون السّبيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تتغنّى، وقد رأت بعضها يؤخذ حيّا والبعض يقضي قتيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تتغنّى ، وعمرها بعض عام أفتبكي وقد تعيش طويلا؟", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فهي فوق الغصون في الفجر تتلو سور الوجد والهوى ترتيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وهي طورا على الثرى واقعات تلقط الحبّ أو تجرّ الذيولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كلّما أمسك الغصون سكون صفّقت الغصون حتى تميلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فاذا ذهّب الأصيل الرّوابي وقفت فوقها تناجي الأصيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فأطلب اللّهو مثلما تطلب الأطيار عند الهجير ظلاّ ظليلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وتعلّم حبّ الطلّيعة منها واترك القال للورى والقيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فالذي يتّقي العواذل يلقى كلّ حين في كلّ شخص عذولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أنت للأرض أولا وأخيرا كنت ملكا أو كنت عبدا ذليلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا خلود تحت السّماء لحيّ فلماذا تراود المستحيلا ؟..", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كلّ نجم إلى الأقوال ولكنّ آفة النّجم أن يخاف الأقولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "غاية الورد في الرّياض ذبول كن حكيما واسبق إليه الذبولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وإذا ما وجدت في الأرض ظلاّ فتفيّأ به إلى أن يحولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وتوقّع ، إذا السّماء اكفهرّت مطرا يحيي السهولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قل لقوم يستنزفون المآقي هل شفيتم مع البكاء غليلا؟", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ما أتينا إلى الحياة لنشقى فأريحوا ، أهل العقول، العقولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كلّ من يجمع الهموم عليه أخذته الهموم أخذا وبيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كن هزارا في عشّه يتغنّى ومع الكبل لا يبالي الكبولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا غرابا يطارد الدّود في الأرض ويوما في اللّيل يبكي الطّلولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كن غديرا يسير في الأرض رقراقا فيسقي من جانبيه الحقولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تستحم النّجوم فيه ويلقى كلّ شخص وكلّ شيء مثيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا وعاء يقيّد الماء حتى تستحل المياه فيه وحولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كن مع الفجر نسمة توسع الأزهار شمّا وتارة تقبيلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا سموما من السّوافي اللّواتي تملأ الأرض في الظّلام عويلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ومع اللّيل كوكبا يؤنس الغابات والنّهر والرّبى والسّهولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا دجى يكره العوالم والنّاس فيلقي على الجميع سدولا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أيّهذا الشّاكي وما بك داء كن جميلا تر الوجود جميلا", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تلك السنون الغاربات ورائي سفر كتبت حروفه بدمائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ما عشتها لأعدّها بل عشتها لتبين في سيمائها سيمائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "سيّان لو أني قنعت بعدّها عمري وعمر الصخرة الصماء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا حت لي العلياء في آفاقها فأردتها دربا ألى العلياء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ومحبة للخير تسري في دمي ورعاية للضعف والضعفاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وعبادة للحق أين وجدته والحسن في الأحياء والأشياء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لتدور بعدي قصة عن شاعر رقصت به الدنيا جناح ضياء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "نشر الطيوب على دروب حياته وسرى هوى في الطيب والأنداء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وأطلّ في قلب البخيل سماحة وشجاعة في السلم والهيجاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ومشى إلى المظلوم بارق رحمة وهوى على الظلام سوط بلاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فتعز دنيا قد طوت آبائي وتهش دنيا أطلعت أبنائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تلك السنون ببؤسها ونعيمها مالت بعودي وانطوت بروائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "أين الشباب ألفّ أحلامي به ليس الشباب الآن لي برداء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "نفسي تحس كأنما أثقالها قد خيرت فتخيرت أعضائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "كم من رؤى طلعت على جنباتها ركبا من الأضواء والأشذاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "قلبت فيها بعد لأي ناظري فتعثرت عيناي بالأشلاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "يا للضحايا لا يرفّ لموتها جفن ولا تحصى مع الشهداء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ودعت لذات الخيال وعفتها ورضيت أن أشقى مع الحكماء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فعرفت مثلهم بأني موحد بؤسي،وأني خالق نعمائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "إني أراني بعد ما كابدته كالفلك خارجة من لأنواء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وكسائح بلغ المدينة بعدما ضلّ الطريق وتاه في البيداء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "شكرا لأصحابي فلولا حبهم لم أقترب من عالم اللألاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "بهم اقتحمت العاصفات بمركبي وبهم عقدت على النجوم لوائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "شكرا لأعدائي فلولا عيثهم لم أدر أنهمو من الغوغاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "نهش الأسى لما ضحكت قلوبه م'عرس المحبة مأتم البغضاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ذني إلى الحسّاد أني فتّهم وتركهم يتعثرون ورائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وخطيئتي الكبرى إليهم أنهم قعدوا ولم أقعد على الغبراء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "عفو المروءة والرجولة أنني أخطأت حين حسبتهم نظرائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "شكرا لكلّ فتى مزجت بروحه روحي فطاب ولاؤه وولائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "من كان يحلم بالسماء فإني في قلب إنسان وجدت سمائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ليس الجمال هو الجمال بذاته الحسن يوجد حين يوجد رآء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ما الكون؟ ما في الكون لولا آدم إلا هباء عالقاً بهباء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وأبو البرية ما أبان وجوده وأتم غايته سوى حواء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "إني سكبت الخمر حين سكبتها للناس ، لا للأنجم الزهراء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "لا تشرب الخمر النجوم وإن تكن معصورة من أنفس الشعراء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "تلك السنون ، عقيمها كولودها حلو لديّ، كذا يشاء وفائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ف الليلة العسراء من عمري وعمر الدهر مثل الليلة السمحاء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "يا من يقول (ظلمت نفسك فاتئد) دعني ، فلست بحامل أعبائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "إنّ الحياة الروح بعض عطائها وأنا ثمار الروح كلّ عطائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "ما العمر؟ إان هو كالإناء وإنني بالطيّب الغالي ملأت إنائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "فإذا بقيت ، فللجمال بقائي وإذا فنيت ، ففي الجمال فنائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "للّه ما أحلى وأسنى ليلتي هي في كتاب العمر كالطغراء", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "يا صحب لن أنسى جميل صنيعكم حتى تفارق هيكلي حوبائي", Author = "إيليا أبو ماضي" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/إيليا_أبو_ماضي", Text = "وتقول عيني \"قد فقدت ضيائي\" ويقول قلبي\"قد فقدت رجائي\"", Author = "إيليا أبو ماضي" },
        };
    }
}