using System;

namespace StdbModule;

public static partial class ArabicQuotes
{
    public static class بهاءطاهر
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الحب الحقيقي التقاء روحين والأرواح لا تتنافس في الجمال ولا في الذكاء لأن كل الأرواح جميلة وذكية.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الحقيقة أن هذه الحياة فخ .. فخ نتخبط فيه منذ أن نولد والغلطة أننا نحاول الخروج من هذا الفخ.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الندم باب الحياء والحياء باب التوبة.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا تحسب يا توفيق أن عملك أو عملي هو المنجي وانما هي رحمة الله..", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا ييأس من الوقت إلا من يجهل أن الرحمة تسبق الوقت ولا يسبقها الوقت.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أن اخطات فكن شجاعا على الإنسان أن يحاول على الأقل أن يتصرف على أنه مخطي لا أن يواصل الخداع.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا تسعى لخداع رجل مسن يعلم أن الموت لا يمكن أن يكون بعيدًا.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "آلاف من الناس يصفعون كل يوم ولكن قليل منهم من يشعر بالإهانة او الغضب قليل منهم يا سيد من يصيبهم ذلك المرض الذي أصاب أباك والذى يصيبك أنت الآن.. مرض العدل", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أحتاج الوحدة والسكون لكى أفكر. أفكر في أي شئ بالضبط؟ أدمنت التفكير في نفسي وكلما فتحت صفحة وجدتها أسوأ من التي تسبقها", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الحقيقة بسيطة لا تحتاج إلى زخرفة الكلام..", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أن الهزيمة لا تنزع البطولة من الثوار", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "انتبه منذ مدة طويلة إلى أنه كلما كانت العادات غريبة وغير مفهومة، استحال التخلص منها", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أبشع شئ يا حشمت ليس الحزن ولكن اختفاء الحزن", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أخــاف الغربة في المـوت أكثر مما أخــافها وأنا على ظهـر الدنيا", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أخذت كل الأشياء تتداخل ، لا تفسر شيئا ولا تضيء شيئا ، ولكنها تتقاطع وتتكاثف وتنتهي إلى طرق مسدودة", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أخشى ونحن قطرة واحدة في الموج أن ننفصل.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أدمنت التفكير في نفسي ، وكلما فتحت صفحة وجدتها أسوأ من التي سبقتها.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إذا كنت لا أفهم نفسي فكيف أفهم القدر؟ فليكن ما يكون!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أرجوك لا تسألني اليوم عن الحزن، سيأتي في موعده، فدعنا علي الأقل ننساه في هذه اللحظة.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أصبح هو وقلبه صديقين حميمين لا يسع أحدهما أن يخون الآخر", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "اعرف أن الشقاء ندبة في الروح، أن بدأت في الطفولة فهي تستمر العمر كله", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أعرف اني يمكن أن أساعدالآن بالصمت أكثر مما اساعد بالثرثرة", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أفكر في هذا الطفل الذي يطاردنا حتى آخر العمر ، ألا توجد طريقة للتخلص منه ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الأرواح وحدها هي التي تتلوث ..", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "آلاف من الناس يُصفعون كل يوم ولكن قليلاً منهم من يشعر بالإهانة أو الغضب", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "التفاؤل في هذه الظروف يكاد يكون وقاحة!!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الدنيا التي احلم بها نغم لا عراك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الدوله تتظاهر بانها تريد وهي لا تريد، والشعب يتظاهر بانه يريد وهو لا يريد", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الطموح؟ لا افهم حتى لماذا يطمح الناس ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "العاقل من يمر على الأوقات لا الذي تمر به الأوقات، من يحكمها لا من تحكمه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "العامة لا تعيش بالتقوى، العامة تحتاج إلى الخوف لكي تعرف التقوى", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الكفر هو الظلم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "المتظاهرون يا أستاذ معهم حناجرهم وهو معه المال ومعه القانون ، فما يمكن أن تفعله مظاهرة ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "المسألة اني اريد أن اتكلم .. هذا المساء اريد أن اتكلم .. الا تستبد بك احيانا هذه الرغبة ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "المصيبه تحل ...ومعها خبرها ...الفرح وحده يحتاج الي سؤال وجواب", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "المهم ألا تيأس من الاستقامة إن وقع منك ذنب .. فقد يكون هو آخر ذنب كتب عليك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الناس الآن أعقل . العواطف الآن أهدأ . الدموع الآن لا تنزل إلا من إدمان النظر للتلفزيون ..", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "النور نور لأن ضوءه يبدد ظلمة النفس ويجلو البصيرة", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "الوصول الحق هو أن ترى النور في قلب الظلمة وقد يكون أقرب إليك مما تظن، لكنك لن تراه قبل أن ترى نفسك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أن أحدآ لا يدخل مملكة الأسرار القدسية ، إلا في غمار نشوة تهتك المألوف ، لتلج إلى المجهول", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أن الإنسان ينضج ويصنع نفسه بالصراع ضد ماضيه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن المخــبــرين في المحــروســة ...أكــثــر مــن سكــانهــا....!!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن حلَّت بك نعمة فصُنها. لا تبددها على من لا يستحق", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن خطانا تقودنا أحيانا دون أن ندري إلى عكس الطريقوإن السعيد من تهتدي خطاه؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن صح أن الشعراء هم ضمير الأمة ، فما مصير الأمة التي تنسى شعراءها ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن قل ما تفــرح بــه ...قــل ما تحــزن عليــه!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن كنت أجهل نفسي فكيف أحكم على الناس؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أن كنت لا تستطيع أن تساعد غريقا فلماذا تتظاهر بانك تمد اليه يدك ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن لم تهزمهم فاتبعهم !", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إن نزعتم من قلوبكم الغل صبح كل يوم من حياتكم عيدًا .", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أنا أعرف يا حاتم أن طلب العدل مرض .. ولكنه المرض الوحيد الذي لا يصيب الحيوانات", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "انا لا افعل شيئا ابدا. امشى في الشوارع حين اجد الوقت. وحدي.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أنــا ولــدت بالخــوف!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "انتهى كل شىء ولم يعد بيدك انت مايمكن أن تفعله لم يبطىء كثيرا ذلك اليوم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "إنه ساعدني على طريقته فدمر حياتي", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "أين السلام ياصديقى ؟ فقلت دون وعى ....ان ننام ....ان نحلم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "تشَبَث بيقينك لكى لا ينتهى عالمك .", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "تعطيه يدك ...فيريد أن يأخذ ذراعك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "تعلم يا ولدي ألا تطلب من الوقت الا ما يأذن به ربك ورب الوقت", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "تغالب الاعتراف بإنها تسعى وراء حلم غالب", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "تولد الفكرة في السوق بغيّاً. ثمّ تقضي العمر في لفق البكارة", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ثم أي زجاج هذا الذي يسقط على الأرض ، ومن أين أتى هذا الرنين ، من الذي يصرخ ومن الذي يسقط", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "جمــيــل وبعــيــد وصعــب!!!!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "حتى هذا كذب لا أحد يحمي أحد من خوفه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "حكمت الرعية بالخوف فأفرخ الخوف الخوف الطاعة كما أردت لكنه أفرخ معها الخيانة.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "خشيت نهايته فجاءت أسرع مما توقعت", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "دون أن نصنع النهاية فانها تأتى خفنا منها أو لم نخف فإنها تأتى وينتهى معها كل شئ", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "رب عمر اتسعت اماده وقلت إمداده", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ربما بعد الغياب الطويل في الغربة لا يعود للإنسان في الحقيقة أي بلد", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ربما تاتي العلامات ولكننا نتجاهلها ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ربما يبعث الضياع صورة الجمال القديم الذي كانت العين غافلة عنه والأصل قائم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "سئمت الهروب وهم في كل مكان", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "سأنتظر ألا أشتهي الدنيا لأتوجه بعدها نقيًا طاهرًا. ولكن كيف توقعت أن يأتي هذا النقاء؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "سنرجع إلى الوقت الذي يقتل الوقت ...ويميتني معه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "سنرحل إلى الصحراء معاً، سنولد هناك أيضاً من جديد معاً ، وفي هذا البعث لن افرّط فيك ، ستكون لي .", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "سيمر الزمن وسيأتى بعدنا من يعرف لم تعذبنا سينسون وجوهنا واصوتنا ولكنهم لن ينسوا لم تعذبنا", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "شعوب كالبشائر تنبت الأزهار من قلب المجازر.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ضع في الظلمة خطوطا وحلولا فسيبددها النهار.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "طبيبك أنت ... ولكن لا تقاوم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "طفلنــا لــم يكــن ثالثنــا فــي البيــت..... بــل كنــا كلانــا فيــه معـــاً", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "طيفاً يظهر أحيانا علي حافة القبر", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ظـلـلـت عمـــري كــله ....أغمــز بعــين للدنيــا وبعيــن للآخــرة.... دون أن أستقــر علــي حــال!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "على الأقل هي لم تفعل شيئا تعتقد في قرارة عقلها إنه خطأ", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "عن نفسى إذا كان ثمن المساعدة هو حريتى فلا أريد أن يساعدنى أحدلا أريد وصاية من أحد", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "عندما تقرر الانتحار تكون وقتها قد مت بالفعل .. ما ينقذونه بعد ذلك لا يكون هو أنت ولكن جثتك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "في النهار ظلمة اشد من حلكة الليل", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "قال أتعرف ما هو أكثر شيء محزن في هذه الأمور؟ أبشع ما فيها أنك تألفها.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "قبل أن تشجع على البدايات كان يجب أن تفهم أنك لا تستطيع أن ترسم النهايات", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "قد لا ينقذ من يطلب العدل العالم ولكنه ينقذ نفسه.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "قد يفتح للمرء باب الطاعة دون أن يفتح عليه بالقبول وربما يقضى عليه بالذنب فيكون سبب الوصول", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كان عيدا وانتهى. كان كابوساً وانتهى. كان ما كان .... وانتهى", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كذب ! لا أحد يحمي أحد من خوفه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كل الاسر السعيدة تتشابه ولكن كل اسرة شقية فريدة في شقائها", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كل الأفكار العاهرة الآن تسمى نفسها مبادىء وتزنى بالحقيقة !", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كــل الحكمــة لا تفيــد فــي أن تهـــدي الراحــة إلى القلب!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كل إنسان يصنع نفسه ..وفي الغالب يصنع نفسه ضد ماضيه", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كل شيء يمكن غفرانه إلا أن تكذب على نفسك .. وتكذب على الناس عن عمد", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كيف وهو ممتلئ بالدنيا إلى هذا الحد، سيصل إلى العزلة والخلوة اللتين تقول الكتب ألا وصول بدونهما؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "كيف يمكن لإنسان أن يتكلم دون اوكسجين ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا أحد يتكلم باسم الله هو وحده الذي يقدر ويحكم", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا أريد أن أفرط في يوم يمكن أن أعيشه لن أفرط في هذه الهدية باختيارى", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا تتعجل نهاية الفرح ! .. فلا تتعجل النهاية . لا تفكر حتى في أن نهاية ستأتي", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا تطلب من الوقت إلا ما يأذن به ربك ورب الوقت", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا يضيع الدنيا الذين مع أو الذين ضد .. لكن يضيعها المتفرجون", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا يعرف الإنسان الحقيقة إلا متأخرا", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا يهم ما حدث ولا ما سيحدث . نحن لا نملك غير لحظتنا ، هنا والآن", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لا يوجد غير شيء واحد يمكن أن يجعل الحلم مستحيلاهو خوف الفشل", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لأن الاهانه ترفض أن تزول ولأنني لاأعرف طريقه أرد بها هذه الاهانة", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "التفاؤل في هذه الظروف يكاد يكون وقاحة!!!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لماذا تبكين ؟ هل قلت شيئا ؟ لاأنت لم تقل شيئاتمنيت أن تقول", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لو أن الزمن لا يكون.. لو اني فقط اتلاشى !", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "لو يأتي النوم هكذا لو يأتي نوم طويل ونسيان", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ما أسهل أن تموت من اجل الحقيقة. و لكن هل تعرف كيف تضحى من اجلها؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ما الذي يجعل خطانا تقودنا إلى عكس الطريق ...ونحن نعرف أنه عكس الطريق ؟؟؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ما هي تلك المصادفات التي تتحكم فينا وتصنعنا ؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ماذا تمنيت ؟ لا شيء وكل شيء", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "من أنا لأقول ذلك ؟! ...إن كنت أجهل نفسى فكيف أحكم على الناس ؟!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "من تكون لتتزوجنى ؟ من أنت ؟ أنت حتى لا تعرف أسماء الزهور !!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "من لا يخاف علي حياته لا تهمه حياة غيره.", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "من يتعذب يتعذب وحده ومن يموت يموت وحده", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "نعم في داخلى اشياء ولكنى لا استطيع أن اسميها", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "نقتل شعراءنا بالصمت......ونقتلهم بالنسيان", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ها قد جاءت آخر الأيام وأصبح كل إنسان يهذي بما يعرف وبما لا يعرف", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "هــذه كتب تتحدث عــن النــور ...لا شــأن لهــا بظلمــة النــفــس!!", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "هل مَـوات الأرواح يُـعدي؟", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "هناك زهور لكل وقت وليس الربيع فقط", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "هـــي ....وحيــدة فــي الليـــل وهـــو....يــعيــــش بــداخلــهـــا", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ولما وجدت كل فرحة تلد نهايتها، وجدت في فرحتك أنت المنتهى..", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "وماذا كانت ستفعل بنفسها في ليالي الوحدة و[[الخوف]] لو لم تكن الكتب هناك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "وراح هو يتحسس يدها برفق وكأن أنامله تقبل تلك اليد", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "وظل طول عمره يخاف ويمنعه الخوف من الكلام", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ولكن دائما يأتي من ينقذك. لا يتركونك في حالك ابدا", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ولكن كل الأوقات مناسبة لتقول المرأة للرجل أنه جميل !", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "ولكن متي ؟؟ سيأتي الوقت ولكن تعلم ياولدي ألا تطلب من الوقت إلا ما يؤذن به ربك ورب الوقت .", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "وماذا كانت ستفعل في ليالي الخوف والوحده .... أن لم تكن الكتب هناك", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "يتغير الإنسان في السجن... العواطف المشبوبه في داخله تنطفئ داخل أسواره", Author = "بهاء طاهر" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/بهاء_طاهر", Text = "يجب أن ننتهي من كل قصص الأجداد ليفيق الأحفاد من أوهام العظمة والعزاء الكاذب.", Author = "بهاء طاهر" },
        };
    }
}