using System;

namespace StdbModule;

public static partial class ArabicQuotes
{
    public static class ميخائيلنعيمة
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لكلّ كلمة أذن. ولعلّ أذنك ليست لكلماتي. فلا تتهمني بالغموض.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّما بريتُ قلمي براني.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "رُبّ صلاةٍ أفسدت صلوات.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "من قال إنّه يعطي ولا يأخذ فقد أخذ فوق ما يستحق.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "سألت ربّي مرة: أين أنت؟ فأجابني: بل أين أنت؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "من أطاع عصاك فقد عصاك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف يخاف شيئًا مَن حرّاسه كلّ شيء؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قوّيْتَ نظرك بالمجهر والمرقب. فهل قوّيت فهمك لما أنت ناظر؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "دار الفناء ودار البقاء - ألا مَن يدلّني عليهما في خريطة المسكونة؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "يا للعجيبة! أزرع قلبي على الورق فينبت في قلوب النّاس.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما من نقد متداول في سوق المعرفة إلّا الألم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما أحبّك من أبغض جارك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "من مشى وظهره إلى الشمس مشى مقودًا بظلّه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كم صوتٍ مرّ في أُذني وما سمعته. وكم صوت سمعته وما مرّ في أذني قطّ.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تقول لي يا سيّدي وأقول لك يا سيّدي. فأيّنا العبد يا ترى؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "للأب قلبٌ وللأمّ قلبان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "من استهان بالغير هان للغير.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "بعضهم يشتري الشهرة. وبعضهم تشتريه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ربّ شهرة جاءت عروسًا في المساء فوضعت في الصباح فضيحة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا تستعجل الشهرة إليك لئلا تستعجلها عنك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "صروف الزمان يصرفها الزمان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما دام الكلب ينبح قدام بيته فالثعلب في أمان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لماذا أكتب؟ لتراك فيّ وأراني فيك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ كاتب مولّدٌ حتى الذين فكرهم أعقم من بغلة وخيالهم أضيق من شقّ قصبتهم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ليس من العدل في شيء ألّا ترضوا من الكتّاب بأقلّ من الآيات البيّنات، وأن ترضوا من الوالدين ببنين وبنات أقل جمالًا من أدونيس وعشتروت.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما غصصتُ بلقمة قطّ إلّا لأن غيري كان أحق بها مني.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف تسألني مَن أنا وانت تجهل من أنت؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "جمرة في القلب ولا دمعة في العين.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "مهود الملحدين لحود. ولحود المؤمنين مهود.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أكثر الناس لا يفصلهم عن السماء غير السقف البيت.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عجبت لمن يغسل وجهه مرّات في النهار ولا يغسل قلبه ولو مرّة في السنة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "رغيفك رغيفان: رغيف تأكله، ورغيف يأكلك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "سكوت صاحب الحقّ عن حقّه شجاعة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ ما يعطيه الناس يستردّه النّاس. كلّ ما تعطيه الأرض تستردّه الأرض. فتّشوا عن عطايا لا تُستردّ لأنها مقدمّة منكم إليكم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الكبرياء والذلّ توأمان متلاصقان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "رويدك، فالزّمان كلّه لك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "زّوجوا الهرّ من الفأرة إن أردتم سِلمًا دائمًا.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا تغرب الشمس إلا عن الذين يغربون عنها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ قتيل قتيلان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عجبًا تحسّ وخز خرطوم الذبابة في جلدك ولا تحسّ وخز خرطومك في جلود النّاس.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عابد بطنه جزاؤه السرجين الكثير.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تقاتل نسران على جيفة فكانت من نصيب الثعلب.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما أفقر مَن حدود ملكه حدوده وإن ملك الأرض.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما عرفت أسخف من الذين يحفرون أسماءهم في الصخور ليخلدوا.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف يعبد الله من ليس يعبد نفسه؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "صلاة القويّ في قلبه. وصلاة الضعيف في فم الكاهن.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما آمن من طمع في الجنّة وخاف النّار.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما فات ما مات. وما مات ما فات.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أكذب الكذبة مِرآتي، وأغفل المغفّلين عيني.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "العزلة للملآن أنس، وللفارغ وحشة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تاهَ من لا دليل له من نفسه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أثقل غطاء للرأس التاج.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّنا في الطاحون بلابل.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "اقبلِ العذرَ وإن كاذبًا.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الكذب أحبولة لا تصطاد إلّا الكذوب.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قلب الساذج في عينيه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "يقرأ القارىء من الكتاب على قدر ما يقرأ الكتاب منه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "دقيقة الألم ساعة. وساعة اللذة دقيقة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ملوك العبيد ملوكٌ عبيد.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "للأسد هيبة في موته ليست للكلب في حياته.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تعدّ عمرك بالسنين فيقصر. إلا عددته بالثواني فيطول؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "بعض الإنصاف إجحاف. وبعض الإجحاف إنصاف.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا بركة في أرض تبرها أغلى من ترابها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "نصف النهار عندك نصف الليل عند غيرك. فلا تسوقنّ الزمان بعقرب ساعتك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أما تسمع الأرض تقول لك كلّما مشيت عليها: أهلًا وسهلًا؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما أكثر المتكلّمين وأقلّ السامعين.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا تخدعنّك أفعى إذا هي قالت لك: خذ سمّي واعطني سمّك. فصفقتها تكون الرابحة من غير شك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ لاعن ملعون بلعنته.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كم مرة لعنتَني فتباركتُ وكنتَ ملعونًا؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا تخَف يا أخي حُمَةَ نحلةٍ تحمل لك الشهد في فمها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "بين البداية والنهاية لمحة تدعى اللانهاية.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "جهلتُ فتمرّدت فاسنحقت.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قطع الضبّ خيط العنكبوت فأخذت بثأرها من الذبابة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "يتذوّق اللسان الطعام. فما باله لا يتذوّق الكلام؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لي بين حاجبيَّ عين ثالثة. ولولاها لكنتُ أعمى.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الخطيب المصقع مَن سمع سامعيه قبل أن يسمعوه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لكلّ كتاب قارىء، ولو كاتبه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أجهَلُ ما فيك عقلُك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أصحيح أنّ آدم مات؟ إذًا من أنت، ومن أنا؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "من كان لا يبصر غير محاسنه ومساوىء الغير فالضرير خير منه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "للحسود ألف عين. ولكن في كلّ عين ألف جمرة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قُصْرُ البصر ولا طول اللسان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عند تصفية الحساب ستجد أن للناس عليك مقدار ما لك عليهم لا أكثر ولا أقلّ.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عندما تتنازل إلى من تحسبه دونك مرتبةٌ تمشي إليه على رأسك ويمشي إليك على قدميه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لماذا تلعن فرعون وتبارك موسى؟ أما رَبيَ موسى في قصر فرعون؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "بدأت أتعلّم يوم نسيت كلّ ما تعلّمت.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما علّم من لا يتعلّم، ولا تعلّم من لا يُعلَّم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عناصر الكون أربعة: م. ح. ب. ة، يجمعها العنصر الفرد \"أنا\".", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما من سياج للمحبّة مثل المغفرة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف ينام الذي في رأسه شوك وفي قلبه دمامل؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تدور الأرض من غير أن تدفعها أرجل الماشين عليها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "للفضاء آذان وعيون وألسنة بغير عدّ.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "يا ويل من كثرت صناديقه ومفاتيحه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما كلّ زهرة تثمر. ولا كلّ ثمرة تنضج.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أعلى الفرس أسفلُ الفارس.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ساعة بعد ساعة، عامًا بعد عام، وجيلًا بعد جيل تنزع الإنسانية ورقة فورقة من المآرز التي خاطتها لها منذ أيّام عدن فاحتجبت بها عن الله.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أقرب ما تكون مني أبعد ما تكون عن نفسك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لنمشِ في الظلام آمنين. فلِلّيلِ دليل أصدق من دليل النهار.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أبواب المعرفة لا تحصى. أمّا المفتاح فواحد.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "جذور اللّذة في الألم. وجذور الألم في اللذّة. أمّا السعادة فلا جذور لها البتّة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما نفعك من الحياة ما دمت تجهل نفع الموت؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "متى أصبح صديقك منك بمنزلة نفسك فقل قد عرفت الصداقة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "جارُك من جاورتَ قلبه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "بين الصاعقة والمصعوق جواذب يجهلها المصعوق والصاعقة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا تنزل الصاعقة بالمصعوق إلا بدعوة منه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما تفهمه من كلامي هو لك. وما لا تفهمه فهو لغيرك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "حضرتُ السوق فما بعتُ ولا اشتريت.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أحلامك في الليل يقظة ما نام منك في النهار.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "إنّ دارًا لا تعرف الضيف لمقبرة لساكنيها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "يوم الحساب يوم جمع وضرب، لا يوم طرح وقسمة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "شِعر الأرض أشجارها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تَعَب الأبرار راحة. وراحة الأشرار تعب.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "دفع الأذى بالأذى انتحار.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ تائب نادم وما كلّ نادم بتائب.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "خذ من غذك رادًا ليومك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تأتي المشاكل ومفاتيحها فيها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كثير التشكّي عدوّ نفسه، وعدوّ الناس، وعدوّ الله.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّما قلّت الرحمة زادت أجور الأطباء والمستشفيات.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "حتى الجنون أصبح ذا ثمن محترم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف تعرف عيبًا ليس فيك؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كيف تقول لي \"وداعًا\"؟ ألعلّك ذاهب أبعَدَ من الله؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الإنسان مجموعة عجائب، وأعجبها النفس.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ أمسٍ غذٌ لكلّ غد. كلّ غدٍ أمسٌ لكلّ أمس. تلك هي روزنامة الزمان.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لا ينبذ الناس خرافة إلا ليعتنقوا أكبر منها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ترى من يحفر قبر حفّار القبور؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لو كنت حفّار قبور لأقمت دعوى على كلّ جيش محارب بالعطل والضرر الناتجين عن المضاربة غير المشروعة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما أضيق فكري ما دام لا يتّسع لكّل فكر.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "عجبتُ لمن يؤمن بالله ويكفر بصورته ومثاله.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما عرفت كالصابونة نكرانًا للذات. فهي تذيب نفسها لتذيب أوساخ الغير.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ابتعدتُ عن الناس لأقرّبهم مني.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "لقد اكتشفت جحيمًا جديدةٌ لا نار فيها ولا دود. هي جحيم الذين أدركوا الجنّة فوجدوا فيها كلّ من كانوا على يقين من ذهابهم إلى النار. وهكذا لبثوا لا يعرفون أفي الجنّة هم أم في جهنّم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "تعالوا أدلّكم على جنّة جديدة: قلب فهيم، وخيال سليم، وإرادة لا ترضى من الكلّ بالجزء، ولا تريد لغيرها ما تريده لذاتها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "إن لم تكن بئرًا فكن دلوًا، أو لم تكن دلوًا فكن حبلًا، أو لم تكن حبلًا فكن بكرة على الأقل. ولا تكن حجرًا يطرحه العابثون في البئر ليسمعوا ضجّة الماء فيها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أنت مجهول وأنا مهجول، فتعال نتعارف.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كم من معبد معبودٌ أكثر من الذي شُيِّد لأجل عبادته.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كلّ ثورة فورة. ثمّ تخمد النار فإذا الذي كان في القدر ما يزال فيها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "مثلما تهرب الفراشة من النار إلى النار فتحترق فيها. هكذا يهرب الإنسان من الله إلى الله ليفنى فيه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "أقَلّ النّاس انتفاعًا بنور المنارة حارسها.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما هي بالفضيلة أن تحبّ قريبك كنفسك. ولكنّها الفضيلة أن تجهل قريبك يجبّك كنفسه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قولهم إن الحبّ أعمى مبالغة. والحقيقة هي أن الحبّ بعين واحدة.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "إذا ما بكيت فابكِ الأحياء لا الأموات، لأن الأموات يهزأون بدموعك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "إنّما الأموات تربة الأحياء.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "مالِكٌ نفسه مَلِكٌ مطاع. تاجه الحريّة. والطمأنينة صولجانه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "ما دام بيتك يضيق بك دام عالَمُك سجنًا أضيق من بيتك.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الأرض بوابة السماء.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "كم من كتاب أفصح ما فيه بياضه.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "الطفولة زاد الصبا. والصبا زاد الشباب. والشباب زاد الكهولة. والكهولة زاد الشيوخة. فماذا عسى الشيوخة أن تكون إن لم تكن زادًا لطفولة جديدة؟", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "القداسة جبّة يتهرّب من لبسها الأبرار ويتسابق إلى التدثّر بها الأشرار.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "قبل أن تفكرّوا في التخلّص من حاكم مستبدّ فكّروا في العادات والتقاليد والشهوات السود التي تستبدّ عليكم.", Author = "ميخائيل نعيمة" },
            new Quote { Id = "https://ar.wikiquote.org/wiki/ميخائيل_نعيمة", Text = "سقيتُ زهرة في حديقتي كان قد برّح بها العطش. فلم تقلي \"شكرًا\". ولكنّها انتعشَتْ فانتَعَشْتُ.", Author = "ميخائيل نعيمة" },
        };
    }
}