// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity().name("player_id"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  rating: __t.i32(),
});
