// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";
import GameType from "./game_type_type";
import GameState from "./game_state_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  phrase: __t.string().name("Phrase"),
  createdAt: __t.i64().name("CreatedAt"),
  racingStartedAt: __t.i64().name("RacingStartedAt"),
  countdownDurationMs: __t.i64().name("CountdownDurationMs"),
  get state() {
    return GameState.name("State");
  },
  get gameMode() {
    return GameMode.name("GameMode");
  },
  get gameType() {
    return GameType.name("GameType");
  },
  placements: __t.array(__t.identity()).name("Placements"),
  owner: __t.option(__t.identity()).name("Owner"),
  attribution: __t.option(__t.string()).name("Attribution"),
});
