// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  GameType,
  GameState,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  phrase: __t.string(),
  createdAt: __t.i64().name("created_at"),
  racingStartedAt: __t.i64().name("racing_started_at"),
  countdownDurationMs: __t.i64().name("countdown_duration_ms"),
  get state() {
    return GameState;
  },
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get gameType() {
    return GameType.name("game_type");
  },
  placements: __t.array(__t.identity()),
  owner: __t.option(__t.identity()),
  attribution: __t.option(__t.string()),
});
