// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { GameMode } from "./game_mode_type";
// Mark import as potentially unused
declare type __keep_GameMode = GameMode;
import { GameType } from "./game_type_type";
// Mark import as potentially unused
declare type __keep_GameType = GameType;


export type GameRecord = {
  id: string,
  playerId: __Identity,
  gameId: string,
  gameMode: GameMode,
  gameType: GameType,
  year: number,
  month: number,
  day: string,
  date: bigint,
  timeMs: bigint,
  placement: number,
  wpm: number,
  xpGained: number,
  eloChange: number,
};
let _cached_GameRecord_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const GameRecord = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GameRecord_type_value) return _cached_GameRecord_type_value;
    _cached_GameRecord_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_GameRecord_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "gameId", algebraicType: __AlgebraicTypeValue.String },
      { name: "gameMode", algebraicType: GameMode.getTypeScriptAlgebraicType() },
      { name: "gameType", algebraicType: GameType.getTypeScriptAlgebraicType() },
      { name: "year", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "month", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "day", algebraicType: __AlgebraicTypeValue.String },
      { name: "date", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "timeMs", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "placement", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "wpm", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "xpGained", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "eloChange", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_GameRecord_type_value;
  },

  serialize(writer: __BinaryWriter, value: GameRecord): void {
    __AlgebraicTypeValue.serializeValue(writer, GameRecord.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameRecord {
    return __AlgebraicTypeValue.deserializeValue(reader, GameRecord.getTypeScriptAlgebraicType());
  },

}

export default GameRecord;


