// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";
import GameType from "./game_type_type";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  gameId: __t.string().name("GameId"),
  get gameMode() {
    return GameMode.name("GameMode");
  },
  get gameType() {
    return GameType.name("GameType");
  },
  year: __t.i32().name("Year"),
  month: __t.i32().name("Month"),
  date: __t.i64().name("Date"),
  timeMs: __t.i64().name("TimeMs"),
  placement: __t.i32().name("Placement"),
  wpm: __t.f64().name("Wpm"),
  xpGained: __t.i32().name("XpGained"),
  eloChange: __t.i32().name("EloChange"),
  day: __t.string().name("Day"),
});
