// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";
import GameType from "./game_type_type";


export default __t.object("GameModeCount", {
  get gameType() {
    return GameType;
  },
  get gameMode() {
    return GameMode;
  },
  finishedGames: __t.i32(),
  nonLonelyGames: __t.i32(),
  startedGames: __t.i32(),
  totalWpm: __t.f64(),
  minWpm: __t.f64(),
  maxWpm: __t.f64(),
  gameCount: __t.i32(),
});


