// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("GameScore", {
  id: __t.string(),
  gameId: __t.string(),
  language: __t.string(),
  playerId: __t.identity(),
  value: __t.i32(),
  timestamp: __t.i64(),
  timeMs: __t.i64(),
  day: __t.string(),
});


