// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type English500 = { tag: "English500" };
export type Spanish500 = { tag: "Spanish500" };
export type French500 = { tag: "French500" };
export type German500 = { tag: "German500" };
export type Italian500 = { tag: "Italian500" };
export type Portuguese500 = { tag: "Portuguese500" };
export type Japanese500 = { tag: "Japanese500" };
export type Korean500 = { tag: "Korean500" };
export type Chinese500 = { tag: "Chinese500" };
export type Ukrainian500 = { tag: "Ukrainian500" };
export type Arabic500 = { tag: "Arabic500" };
export type Hindi500 = { tag: "Hindi500" };
export type Dutch500 = { tag: "Dutch500" };
export type Swedish500 = { tag: "Swedish500" };
export type Turkish500 = { tag: "Turkish500" };
export type EnglishQuotes = { tag: "EnglishQuotes" };
export type SpanishQuotes = { tag: "SpanishQuotes" };
export type FrenchQuotes = { tag: "FrenchQuotes" };
export type GermanQuotes = { tag: "GermanQuotes" };
export type ItalianQuotes = { tag: "ItalianQuotes" };
export type PortugueseQuotes = { tag: "PortugueseQuotes" };
export type JapaneseQuotes = { tag: "JapaneseQuotes" };
export type KoreanQuotes = { tag: "KoreanQuotes" };
export type ChineseQuotes = { tag: "ChineseQuotes" };
export type UkrainianQuotes = { tag: "UkrainianQuotes" };
export type ArabicQuotes = { tag: "ArabicQuotes" };
export type HindiQuotes = { tag: "HindiQuotes" };
export type DutchQuotes = { tag: "DutchQuotes" };
export type SwedishQuotes = { tag: "SwedishQuotes" };
export type TurkishQuotes = { tag: "TurkishQuotes" };

