// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { GameMode } from "./game_mode_type";
// Mark import as potentially unused
declare type __keep_GameMode = GameMode;
import { GameType } from "./game_type_type";
// Mark import as potentially unused
declare type __keep_GameType = GameType;


export type GameModeCount = {
  gameType: GameType,
  gameMode: GameMode,
  finishedGames: number,
  nonLonelyGames: number,
  startedGames: number,
  totalWpm: number,
  minWpm: number,
  maxWpm: number,
  gameCount: number,
};
let _cached_GameModeCount_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const GameModeCount = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GameModeCount_type_value) return _cached_GameModeCount_type_value;
    _cached_GameModeCount_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_GameModeCount_type_value.value.elements.push(
      { name: "gameType", algebraicType: GameType.getTypeScriptAlgebraicType() },
      { name: "gameMode", algebraicType: GameMode.getTypeScriptAlgebraicType() },
      { name: "finishedGames", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "nonLonelyGames", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "startedGames", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "totalWpm", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "minWpm", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "maxWpm", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "gameCount", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_GameModeCount_type_value;
  },

  serialize(writer: __BinaryWriter, value: GameModeCount): void {
    __AlgebraicTypeValue.serializeValue(writer, GameModeCount.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameModeCount {
    return __AlgebraicTypeValue.deserializeValue(reader, GameModeCount.getTypeScriptAlgebraicType());
  },

}

export default GameModeCount;


