// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import * as GameStateVariants from './game_state_variants'

// The tagged union or sum type for the algebraic type `GameState`.
export type GameState = GameStateVariants.Lobby |
  GameStateVariants.Countdown |
  GameStateVariants.Racing |
  GameStateVariants.Archived;

let _cached_GameState_type_value: __AlgebraicTypeType | null = null;

// A value with helper functions to construct the type.
export const GameState = {
  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  Lobby: { tag: "Lobby" } as const,
  Countdown: { tag: "Countdown" } as const,
  Racing: { tag: "Racing" } as const,
  Archived: { tag: "Archived" } as const,

  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GameState_type_value) return _cached_GameState_type_value;
    _cached_GameState_type_value = __AlgebraicTypeValue.Sum({ variants: [] });
    _cached_GameState_type_value.value.variants.push(
      { name: "Lobby", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Countdown", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Racing", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
      { name: "Archived", algebraicType: __AlgebraicTypeValue.Product({ elements: [] }) },
    );
    return _cached_GameState_type_value;
  },

  serialize(writer: __BinaryWriter, value: GameState): void {
      __AlgebraicTypeValue.serializeValue(writer, GameState.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GameState {
      return __AlgebraicTypeValue.deserializeValue(reader, GameState.getTypeScriptAlgebraicType());
  },

}

export default GameState;


