// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  gameId: __t.string().name("GameId"),
  language: __t.string().name("Language"),
  playerId: __t.identity().name("PlayerId"),
  value: __t.i32().name("Value"),
  timestamp: __t.i64().name("Timestamp"),
  timeMs: __t.i64().name("TimeMs"),
  day: __t.string().name("Day"),
});
