// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";
import GameType from "./game_type_type";
import GameState from "./game_state_type";


export default __t.object("Game", {
  id: __t.string(),
  phrase: __t.string(),
  createdAt: __t.i64(),
  racingStartedAt: __t.i64(),
  countdownDurationMs: __t.i64(),
  get state() {
    return GameState;
  },
  get gameMode() {
    return GameMode;
  },
  get gameType() {
    return GameType;
  },
  placements: __t.array(__t.identity()),
  owner: __t.option(__t.identity()),
  attribution: __t.option(__t.string()),
});


