// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
  GameType,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity().name("player_id"),
  gameId: __t.string().name("game_id"),
  get gameMode() {
    return GameMode.name("game_mode");
  },
  get gameType() {
    return GameType.name("game_type");
  },
  year: __t.i32(),
  month: __t.i32(),
  date: __t.i64(),
  timeMs: __t.i64().name("time_ms"),
  placement: __t.i32(),
  wpm: __t.f64(),
  xpGained: __t.i32().name("xp_gained"),
  eloChange: __t.i32().name("elo_change"),
  day: __t.string(),
});
