// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { GameModeCount } from "./game_mode_count_type";
// Mark import as potentially unused
declare type __keep_GameModeCount = GameModeCount;


export type GlobalStats = {
  date: string,
  stats: GameModeCount[],
  total: GameModeCount,
  dailyActivePlayers: number,
};
let _cached_GlobalStats_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const GlobalStats = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_GlobalStats_type_value) return _cached_GlobalStats_type_value;
    _cached_GlobalStats_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_GlobalStats_type_value.value.elements.push(
      { name: "date", algebraicType: __AlgebraicTypeValue.String },
      { name: "stats", algebraicType: __AlgebraicTypeValue.Array(GameModeCount.getTypeScriptAlgebraicType()) },
      { name: "total", algebraicType: GameModeCount.getTypeScriptAlgebraicType() },
      { name: "dailyActivePlayers", algebraicType: __AlgebraicTypeValue.I32 },
    );
    return _cached_GlobalStats_type_value;
  },

  serialize(writer: __BinaryWriter, value: GlobalStats): void {
    __AlgebraicTypeValue.serializeValue(writer, GlobalStats.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): GlobalStats {
    return __AlgebraicTypeValue.deserializeValue(reader, GlobalStats.getTypeScriptAlgebraicType());
  },

}

export default GlobalStats;


