// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameModeCount from "./game_mode_count_type";


export default __t.row({
  date: __t.string().primaryKey().name("Date"),
  get stats() {
    return __t.array(GameModeCount);
  },
  get total() {
    return GameModeCount.name("Total");
  },
  dailyActivePlayers: __t.i32().name("DailyActivePlayers"),
});
