// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.12.0 (commit 4fdb8d923f39ed592931ad4c7e6391ed99b9fe3a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import ArchiveOldGamesReducer from "./archive_old_games_reducer";
export { ArchiveOldGamesReducer };
import CleanupOldScoresReducer from "./cleanup_old_scores_reducer";
export { CleanupOldScoresReducer };
import CleanupOldXpGainsReducer from "./cleanup_old_xp_gains_reducer";
export { CleanupOldXpGainsReducer };
import ClientConnectedReducer from "./client_connected_reducer";
export { ClientConnectedReducer };
import ClientDisconnectedReducer from "./client_disconnected_reducer";
export { ClientDisconnectedReducer };
import FillGameWithBotsReducer from "./fill_game_with_bots_reducer";
export { FillGameWithBotsReducer };
import JoinGameReducer from "./join_game_reducer";
export { JoinGameReducer };
import JoinPrivateGameReducer from "./join_private_game_reducer";
export { JoinPrivateGameReducer };
import KickPlayerReducer from "./kick_player_reducer";
export { KickPlayerReducer };
import PublishScoreReducer from "./publish_score_reducer";
export { PublishScoreReducer };
import RematchReducer from "./rematch_reducer";
export { RematchReducer };
import SetPlayerNameReducer from "./set_player_name_reducer";
export { SetPlayerNameReducer };
import StartCountdownReducer from "./start_countdown_reducer";
export { StartCountdownReducer };
import StartGameReducer from "./start_game_reducer";
export { StartGameReducer };
import StartPrivateGameReducer from "./start_private_game_reducer";
export { StartPrivateGameReducer };
import SyncAnonymousStatusReducer from "./sync_anonymous_status_reducer";
export { SyncAnonymousStatusReducer };
import UpdateBotProgressReducer from "./update_bot_progress_reducer";
export { UpdateBotProgressReducer };
import UpdateProgressReducer from "./update_progress_reducer";
export { UpdateProgressReducer };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import BotFillTriggerRow from "./bot_fill_trigger_table";
export { BotFillTriggerRow };
import BotProgressUpdateRow from "./bot_progress_update_table";
export { BotProgressUpdateRow };
import CountdownStartRow from "./countdown_start_table";
export { CountdownStartRow };
import GameArchiverRow from "./game_archiver_table";
export { GameArchiverRow };
import GameStartRow from "./game_start_table";
export { GameStartRow };
import ScoreCleanerRow from "./score_cleaner_table";
export { ScoreCleanerRow };
import XpGainCleanerRow from "./xp_gain_cleaner_table";
export { XpGainCleanerRow };
import EloRow from "./elo_table";
export { EloRow };
import GameRow from "./game_table";
export { GameRow };
import GameHighscoreRow from "./game_highscore_table";
export { GameHighscoreRow };
import GameScoreRow from "./game_score_table";
export { GameScoreRow };
import GamerecordRow from "./gamerecord_table";
export { GamerecordRow };
import GlobalstatsRow from "./globalstats_table";
export { GlobalstatsRow };
import PersonalrecordRow from "./personalrecord_table";
export { PersonalrecordRow };
import PlayerRow from "./player_table";
export { PlayerRow };
import PlayerprogressRow from "./playerprogress_table";
export { PlayerprogressRow };
import XpgainRow from "./xpgain_table";
export { XpgainRow };

// Import and reexport all types
import BotConfig from "./bot_config_type";
export { BotConfig };
import BotFillTrigger from "./bot_fill_trigger_type";
export { BotFillTrigger };
import BotProgressUpdate from "./bot_progress_update_type";
export { BotProgressUpdate };
import CharacterEventType from "./character_event_type_type";
export { CharacterEventType };
import CountdownStart from "./countdown_start_type";
export { CountdownStart };
import Elo from "./elo_type";
export { Elo };
import Game from "./game_type";
export { Game };
import GameArchiver from "./game_archiver_type";
export { GameArchiver };
import GameHighScore from "./game_high_score_type";
export { GameHighScore };
import GameMode from "./game_mode_type";
export { GameMode };
import GameModeCount from "./game_mode_count_type";
export { GameModeCount };
import GameRecord from "./game_record_type";
export { GameRecord };
import GameScore from "./game_score_type";
export { GameScore };
import GameStart from "./game_start_type";
export { GameStart };
import GameState from "./game_state_type";
export { GameState };
import GameType from "./game_type_type";
export { GameType };
import GlobalStats from "./global_stats_type";
export { GlobalStats };
import PersonalRecord from "./personal_record_type";
export { PersonalRecord };
import Player from "./player_type";
export { Player };
import PlayerColor from "./player_color_type";
export { PlayerColor };
import PlayerProgress from "./player_progress_type";
export { PlayerProgress };
import ScoreCleaner from "./score_cleaner_type";
export { ScoreCleaner };
import XpGain from "./xp_gain_type";
export { XpGain };
import XpGainCleaner from "./xp_gain_cleaner_type";
export { XpGainCleaner };
import XpMultiplier from "./xp_multiplier_type";
export { XpMultiplier };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'BotFillTrigger',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'BotFillTrigger_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BotFillTriggerRow),
  __table({
    name: 'BotProgressUpdate',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'BotProgressUpdate_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BotProgressUpdateRow),
  __table({
    name: 'CountdownStart',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'CountdownStart_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, CountdownStartRow),
  __table({
    name: 'GameArchiver',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'GameArchiver_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, GameArchiverRow),
  __table({
    name: 'GameStart',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'GameStart_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, GameStartRow),
  __table({
    name: 'ScoreCleaner',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'ScoreCleaner_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ScoreCleanerRow),
  __table({
    name: 'XpGainCleaner',
    indexes: [
      { name: 'ScheduledId', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'XpGainCleaner_ScheduledId_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, XpGainCleanerRow),
  __table({
    name: 'elo',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId_GameMode', algorithm: 'btree', columns: [
        'playerId',
        'gameMode',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'elo_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EloRow),
  __table({
    name: 'game',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'GameType', algorithm: 'btree', columns: [
        'gameType',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'State_GameType', algorithm: 'btree', columns: [
        'state',
        'gameType',
      ] },
      { name: 'State', algorithm: 'btree', columns: [
        'state',
      ] },
    ],
    constraints: [
      { name: 'game_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRow),
  __table({
    name: 'game_highscore',
    indexes: [
      { name: 'GameId_Language', algorithm: 'btree', columns: [
        'gameId',
        'language',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_highscore_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameHighscoreRow),
  __table({
    name: 'game_score',
    indexes: [
      { name: 'GameId_Language', algorithm: 'btree', columns: [
        'gameId',
        'language',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Timestamp', algorithm: 'btree', columns: [
        'timestamp',
      ] },
    ],
    constraints: [
      { name: 'game_score_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameScoreRow),
  __table({
    name: 'gamerecord',
    indexes: [
      { name: 'Day', algorithm: 'btree', columns: [
        'day',
      ] },
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'GameType', algorithm: 'btree', columns: [
        'gameType',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Month', algorithm: 'btree', columns: [
        'month',
      ] },
      { name: 'PlayerId_Day', algorithm: 'btree', columns: [
        'playerId',
        'day',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'Year', algorithm: 'btree', columns: [
        'year',
      ] },
    ],
    constraints: [
      { name: 'gamerecord_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GamerecordRow),
  __table({
    name: 'globalstats',
    indexes: [
      { name: 'Date', algorithm: 'btree', columns: [
        'date',
      ] },
    ],
    constraints: [
      { name: 'globalstats_Date_key', constraint: 'unique', columns: ['date'] },
    ],
  }, GlobalstatsRow),
  __table({
    name: 'personalrecord',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId_GameMode', algorithm: 'btree', columns: [
        'playerId',
        'gameMode',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'personalrecord_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PersonalrecordRow),
  __table({
    name: 'player',
    indexes: [
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'IsBot', algorithm: 'btree', columns: [
        'isBot',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  __table({
    name: 'playerprogress',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'playerprogress_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerprogressRow),
  __table({
    name: 'xpgain',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'Timestamp', algorithm: 'btree', columns: [
        'timestamp',
      ] },
    ],
    constraints: [
      { name: 'xpgain_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, XpgainRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("ArchiveOldGames", ArchiveOldGamesReducer),
  __reducerSchema("CleanupOldScores", CleanupOldScoresReducer),
  __reducerSchema("CleanupOldXpGains", CleanupOldXpGainsReducer),
  __reducerSchema("FillGameWithBots", FillGameWithBotsReducer),
  __reducerSchema("joinGame", JoinGameReducer),
  __reducerSchema("joinPrivateGame", JoinPrivateGameReducer),
  __reducerSchema("kickPlayer", KickPlayerReducer),
  __reducerSchema("publishScore", PublishScoreReducer),
  __reducerSchema("rematch", RematchReducer),
  __reducerSchema("setPlayerName", SetPlayerNameReducer),
  __reducerSchema("StartCountdown", StartCountdownReducer),
  __reducerSchema("StartGame", StartGameReducer),
  __reducerSchema("startPrivateGame", StartPrivateGameReducer),
  __reducerSchema("syncAnonymousStatus", SyncAnonymousStatusReducer),
  __reducerSchema("UpdateBotProgress", UpdateBotProgressReducer),
  __reducerSchema("updateProgress", UpdateProgressReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.12.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** A typed query builder for this remote SpacetimeDB module. */
export const query: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

