// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import JoinGameReducer from "./join_game_reducer";
import JoinPrivateGameReducer from "./join_private_game_reducer";
import RematchReducer from "./rematch_reducer";
import SetPlayerColorReducer from "./set_player_color_reducer";
import SetPlayerNameReducer from "./set_player_name_reducer";
import StartPrivateGameReducer from "./start_private_game_reducer";
import SyncAnonymousStatusReducer from "./sync_anonymous_status_reducer";
import UpdateProgressReducer from "./update_progress_reducer";
import MigrateToV2Reducer from "./migrate_to_v2_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import EloRow from "./elo_table";
import GameRow from "./game_table";
import GamerecordRow from "./gamerecord_table";
import GlobalstatsRow from "./globalstats_table";
import PersonalrecordRow from "./personalrecord_table";
import PlayerRow from "./player_table";
import PlayerprogressRow from "./playerprogress_table";
import XpgainRow from "./xpgain_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  elo: __table({
    name: 'elo_v2',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId_GameMode', algorithm: 'btree', columns: [
        'playerId',
        'gameMode',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'elo_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EloRow),
  game: __table({
    name: 'game_v2',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'GameType', algorithm: 'btree', columns: [
        'gameType',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'State_GameType', algorithm: 'btree', columns: [
        'state',
        'gameType',
      ] },
      { name: 'State', algorithm: 'btree', columns: [
        'state',
      ] },
    ],
    constraints: [
      { name: 'game_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameRow),
  gameRecord: __table({
    name: 'game_record_v2',
    indexes: [
      { name: 'Day', algorithm: 'btree', columns: [
        'day',
      ] },
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'GameType', algorithm: 'btree', columns: [
        'gameType',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'Month', algorithm: 'btree', columns: [
        'month',
      ] },
      { name: 'PlayerId_Day', algorithm: 'btree', columns: [
        'playerId',
        'day',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'Year', algorithm: 'btree', columns: [
        'year',
      ] },
    ],
    constraints: [
      { name: 'game_record_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GamerecordRow),
  globalStats: __table({
    name: 'global_stats_v2',
    indexes: [
      { name: 'Date', algorithm: 'btree', columns: [
        'date',
      ] },
    ],
    constraints: [
      { name: 'global_stats_v2_Date_key', constraint: 'unique', columns: ['date'] },
    ],
  }, GlobalstatsRow),
  personalRecord: __table({
    name: 'personal_record_v2',
    indexes: [
      { name: 'GameMode', algorithm: 'btree', columns: [
        'gameMode',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId_GameMode', algorithm: 'btree', columns: [
        'playerId',
        'gameMode',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'personal_record_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PersonalrecordRow),
  player: __table({
    name: 'player_v2',
    indexes: [
      { name: 'Identity', algorithm: 'btree', columns: [
        'identity',
      ] },
      { name: 'IsBot', algorithm: 'btree', columns: [
        'isBot',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_v2_Identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerRow),
  playerProgress: __table({
    name: 'player_progress_v2',
    indexes: [
      { name: 'GameId', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
    ],
    constraints: [
      { name: 'player_progress_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PlayerprogressRow),
  xpGain: __table({
    name: 'xp_gain_v2',
    indexes: [
      { name: 'Id', algorithm: 'btree', columns: [
        'id',
      ] },
      { name: 'PlayerId', algorithm: 'btree', columns: [
        'playerId',
      ] },
      { name: 'Timestamp', algorithm: 'btree', columns: [
        'timestamp',
      ] },
    ],
    constraints: [
      { name: 'xp_gain_v2_Id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, XpgainRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("JoinGame", JoinGameReducer),
  __reducerSchema("JoinPrivateGame", JoinPrivateGameReducer),
  __reducerSchema("Rematch", RematchReducer),
  __reducerSchema("SetPlayerColor", SetPlayerColorReducer),
  __reducerSchema("SetPlayerName", SetPlayerNameReducer),
  __reducerSchema("StartPrivateGame", StartPrivateGameReducer),
  __reducerSchema("SyncAnonymousStatus", SyncAnonymousStatusReducer),
  __reducerSchema("UpdateProgress", UpdateProgressReducer),
  __reducerSchema("MigrateToV2", MigrateToV2Reducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

