// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity(),
  get gameMode() {
    return GameMode;
  },
  gameRecordId: __t.string(),
  wpm: __t.f64(),
  phraseLength: __t.option(__t.i32()),
});
