// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  GameMode,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  get gameMode() {
    return GameMode.name("GameMode");
  },
  gameRecordId: __t.string().name("GameRecordId"),
  wpm: __t.f64().name("Wpm"),
});
