// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  owner: __t.identity().primaryKey().name("Owner"),
  backgroundColor: __t.string().name("BackgroundColor"),
  textColor: __t.string().name("TextColor"),
  borderColor: __t.string().name("BorderColor"),
  borderWidth: __t.i32().name("BorderWidth"),
  borderRadius: __t.f32().name("BorderRadius"),
  accentColor: __t.string().name("AccentColor"),
  font: __t.string().name("Font"),
  fontWeight: __t.i32().name("FontWeight"),
});
