// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { PlayerColor } from "./player_color_type";
// Mark import as potentially unused
declare type __keep_PlayerColor = PlayerColor;
import { BotConfig } from "./bot_config_type";
// Mark import as potentially unused
declare type __keep_BotConfig = BotConfig;


export type Player = {
  identity: __Identity,
  playerId: string,
  name: string,
  totalGames: number,
  wins: number,
  level: number,
  xp: number,
  xpRequiredForNextLevel: number,
  totalWordsTyped: number,
  totalTimeSpentMs: bigint,
  isBot: boolean,
  botConfig: BotConfig | undefined,
  color: PlayerColor,
  isAnonymous: boolean,
  lastGameDate: bigint,
};
let _cached_Player_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Player = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Player_type_value) return _cached_Player_type_value;
    _cached_Player_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Player_type_value.value.elements.push(
      { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.String },
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "totalGames", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "wins", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "level", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "xp", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "xpRequiredForNextLevel", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "totalWordsTyped", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "totalTimeSpentMs", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "isBot", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "botConfig", algebraicType: __AlgebraicTypeValue.createOptionType(BotConfig.getTypeScriptAlgebraicType()) },
      { name: "color", algebraicType: PlayerColor.getTypeScriptAlgebraicType() },
      { name: "isAnonymous", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "lastGameDate", algebraicType: __AlgebraicTypeValue.I64 },
    );
    return _cached_Player_type_value;
  },

  serialize(writer: __BinaryWriter, value: Player): void {
    __AlgebraicTypeValue.serializeValue(writer, Player.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Player {
    return __AlgebraicTypeValue.deserializeValue(reader, Player.getTypeScriptAlgebraicType());
  },

}

export default Player;


