// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `PlayerColor`.
const PlayerColor = __t.enum("PlayerColor", {Coral: __t.unit(),
  Red: __t.unit(),
  Orange: __t.unit(),
  Rose: __t.unit(),
  Teal: __t.unit(),
  Cyan: __t.unit(),
  Purple: __t.unit(),
  Violet: __t.unit(),
  Indigo: __t.unit(),
  Fuchsia: __t.unit(),
  Pink: __t.unit(),
  Green: __t.unit(),
  Lime: __t.unit(),
  Emerald: __t.unit(),
  Gold: __t.unit(),
  Amber: __t.unit(),
  Yellow: __t.unit(),
  Blue: __t.unit(),
  Sky: __t.unit(),
});

export default PlayerColor;


