// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerColor,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity().name("player_id"),
  playerPublicId: __t.string().name("player_public_id"),
  gameId: __t.string().name("game_id"),
  playerName: __t.string().name("player_name"),
  playerLevel: __t.i32().name("player_level"),
  progressIndex: __t.i32().name("progress_index"),
  isBot: __t.bool().name("is_bot"),
  isAnonymous: __t.bool().name("is_anonymous"),
  createdAt: __t.i64().name("created_at"),
  characterHistory: __t.byteArray().name("character_history"),
  time: __t.i64(),
  placement: __t.i32(),
  joinCode: __t.string().name("join_code"),
  wpm: __t.f64(),
  get playerColor() {
    return PlayerColor.name("player_color");
  },
  highestProgress: __t.i32().name("highest_progress"),
});
