// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerColor,
  BotConfig,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  playerId: __t.string().name("player_id"),
  name: __t.string(),
  totalGames: __t.i32().name("total_games"),
  wins: __t.i32(),
  level: __t.i32(),
  xp: __t.i32(),
  xpRequiredForNextLevel: __t.i32().name("xp_required_for_next_level"),
  totalWordsTyped: __t.i32().name("total_words_typed"),
  totalTimeSpentMs: __t.i64().name("total_time_spent_ms"),
  isBot: __t.bool().name("is_bot"),
  get botConfig() {
    return __t.option(BotConfig).name("bot_config");
  },
  get color() {
    return PlayerColor;
  },
  isAnonymous: __t.bool().name("is_anonymous"),
  lastGameDate: __t.i64().name("last_game_date"),
});
