// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PlayerColor from "./player_color_type";
import BotConfig from "./bot_config_type";


export default __t.row({
  identity: __t.identity().primaryKey().name("Identity"),
  playerId: __t.string().name("PlayerId"),
  name: __t.string().name("Name"),
  totalGames: __t.i32().name("TotalGames"),
  wins: __t.i32().name("Wins"),
  level: __t.i32().name("Level"),
  xp: __t.i32().name("Xp"),
  xpRequiredForNextLevel: __t.i32().name("XpRequiredForNextLevel"),
  totalWordsTyped: __t.i32().name("TotalWordsTyped"),
  totalTimeSpentMs: __t.i64().name("TotalTimeSpentMs"),
  isBot: __t.bool().name("IsBot"),
  get botConfig() {
    return __t.option(BotConfig).name("BotConfig");
  },
  get color() {
    return PlayerColor.name("Color");
  },
  isAnonymous: __t.bool().name("IsAnonymous"),
  lastGameDate: __t.i64().name("LastGameDate"),
});
