// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import PlayerColor from "./player_color_type";


export default __t.object("PlayerProgress", {
  id: __t.string(),
  playerId: __t.identity(),
  playerPublicId: __t.string(),
  gameId: __t.string(),
  playerName: __t.string(),
  playerLevel: __t.i32(),
  progressIndex: __t.i32(),
  isBot: __t.bool(),
  isAnonymous: __t.bool(),
  playerPhotoUrl: __t.option(__t.string()),
  createdAt: __t.i64(),
  characterHistory: __t.byteArray(),
  time: __t.i64(),
  placement: __t.i32(),
  joinCode: __t.string(),
  wpm: __t.f64(),
  get playerColor() {
    return PlayerColor;
  },
  highestProgress: __t.i32(),
});


