// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  PlayerColor,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  playerPublicId: __t.string().name("PlayerPublicId"),
  gameId: __t.string().name("GameId"),
  playerName: __t.string().name("PlayerName"),
  playerLevel: __t.i32().name("PlayerLevel"),
  progressIndex: __t.i32().name("ProgressIndex"),
  isBot: __t.bool().name("IsBot"),
  isAnonymous: __t.bool().name("IsAnonymous"),
  createdAt: __t.i64().name("CreatedAt"),
  characterHistory: __t.byteArray().name("CharacterHistory"),
  time: __t.i64().name("Time"),
  placement: __t.i32().name("Placement"),
  joinCode: __t.string().name("JoinCode"),
  wpm: __t.f64().name("Wpm"),
  get playerColor() {
    return PlayerColor.name("PlayerColor");
  },
  highestProgress: __t.i32().name("HighestProgress"),
});
