// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { PlayerColor } from "./player_color_type";
// Mark import as potentially unused
declare type __keep_PlayerColor = PlayerColor;


export type PlayerProgress = {
  id: string,
  playerId: __Identity,
  playerPublicId: string,
  gameId: string,
  playerName: string,
  playerLevel: number,
  progressIndex: number,
  isBot: boolean,
  isAnonymous: boolean,
  createdAt: bigint,
  characterHistory: Uint8Array,
  time: bigint,
  placement: number,
  joinCode: string,
  wpm: number,
  playerColor: PlayerColor,
};
let _cached_PlayerProgress_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const PlayerProgress = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_PlayerProgress_type_value) return _cached_PlayerProgress_type_value;
    _cached_PlayerProgress_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_PlayerProgress_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerId", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "playerPublicId", algebraicType: __AlgebraicTypeValue.String },
      { name: "gameId", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerName", algebraicType: __AlgebraicTypeValue.String },
      { name: "playerLevel", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "progressIndex", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "isBot", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "isAnonymous", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "createdAt", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "characterHistory", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8) },
      { name: "time", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "placement", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "joinCode", algebraicType: __AlgebraicTypeValue.String },
      { name: "wpm", algebraicType: __AlgebraicTypeValue.F64 },
      { name: "playerColor", algebraicType: PlayerColor.getTypeScriptAlgebraicType() },
    );
    return _cached_PlayerProgress_type_value;
  },

  serialize(writer: __BinaryWriter, value: PlayerProgress): void {
    __AlgebraicTypeValue.serializeValue(writer, PlayerProgress.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): PlayerProgress {
    return __AlgebraicTypeValue.deserializeValue(reader, PlayerProgress.getTypeScriptAlgebraicType());
  },

}

export default PlayerProgress;


