// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import BotConfig from "./bot_config_type";
import PlayerColor from "./player_color_type";


export default __t.row({
  identity: __t.identity().primaryKey(),
  playerId: __t.string(),
  name: __t.string(),
  totalGames: __t.i32(),
  wins: __t.i32(),
  level: __t.i32(),
  xp: __t.i32(),
  xpRequiredForNextLevel: __t.i32(),
  totalWordsTyped: __t.i32(),
  totalTimeSpentMs: __t.i64(),
  isBot: __t.bool(),
  get botConfig() {
    return __t.option(BotConfig);
  },
  get color() {
    return PlayerColor;
  },
  isAnonymous: __t.bool(),
  lastGameDate: __t.i64(),
});
