// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  backgroundColor: __t.string(),
  textColor: __t.string(),
  borderColor: __t.string(),
  borderWidth: __t.i32(),
  borderRadius: __t.f32(),
  accentColor: __t.string(),
  font: __t.string(),
  fontWeight: __t.i32(),
};
