// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BotConfig = __t.object("BotConfig", {
  typingRate: __t.f64().name("TypingRate"),
  errorRate: __t.f64().name("ErrorRate"),
});
export type BotConfig = __Infer<typeof BotConfig>;

export const BotFillTrigger = __t.object("BotFillTrigger", {
  scheduledId: __t.u64().name("ScheduledId"),
  gameId: __t.string().name("GameId"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type BotFillTrigger = __Infer<typeof BotFillTrigger>;

export const BotProgressUpdate = __t.object("BotProgressUpdate", {
  scheduledId: __t.u64().name("ScheduledId"),
  playerProgressId: __t.string().name("PlayerProgressId"),
  phraseLength: __t.i32().name("PhraseLength"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type BotProgressUpdate = __Infer<typeof BotProgressUpdate>;

// The tagged union or sum type for the algebraic type `CharacterEventType`.
export const CharacterEventType = __t.enum("CharacterEventType", {
  Correct: __t.unit(),
  Incorrect: __t.unit(),
  Backspace: __t.unit(),
});
export type CharacterEventType = __Infer<typeof CharacterEventType>;

export const CountdownStart = __t.object("CountdownStart", {
  scheduledId: __t.u64().name("ScheduledId"),
  gameId: __t.string().name("GameId"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type CountdownStart = __Infer<typeof CountdownStart>;

export const Elo = __t.object("Elo", {
  id: __t.string().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  get gameMode() {
    return GameMode.name("GameMode");
  },
  rating: __t.i32().name("Rating"),
});
export type Elo = __Infer<typeof Elo>;

export const Game = __t.object("Game", {
  id: __t.string().name("Id"),
  phrase: __t.string().name("Phrase"),
  createdAt: __t.i64().name("CreatedAt"),
  racingStartedAt: __t.i64().name("RacingStartedAt"),
  countdownDurationMs: __t.i64().name("CountdownDurationMs"),
  get state() {
    return GameState.name("State");
  },
  get gameMode() {
    return GameMode.name("GameMode");
  },
  get gameType() {
    return GameType.name("GameType");
  },
  placements: __t.array(__t.identity()).name("Placements"),
  owner: __t.option(__t.identity()).name("Owner"),
  attribution: __t.option(__t.string()).name("Attribution"),
});
export type Game = __Infer<typeof Game>;

export const GameArchiver = __t.object("GameArchiver", {
  scheduledId: __t.u64().name("ScheduledId"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type GameArchiver = __Infer<typeof GameArchiver>;

// The tagged union or sum type for the algebraic type `GameMode`.
export const GameMode = __t.enum("GameMode", {
  English500: __t.unit(),
  Spanish500: __t.unit(),
  French500: __t.unit(),
  German500: __t.unit(),
  Italian500: __t.unit(),
  Portuguese500: __t.unit(),
  Japanese500: __t.unit(),
  Korean500: __t.unit(),
  Chinese500: __t.unit(),
  Ukrainian500: __t.unit(),
  Arabic500: __t.unit(),
  Hindi500: __t.unit(),
  Dutch500: __t.unit(),
  Swedish500: __t.unit(),
  Turkish500: __t.unit(),
  EnglishQuotes: __t.unit(),
  SpanishQuotes: __t.unit(),
  FrenchQuotes: __t.unit(),
  GermanQuotes: __t.unit(),
  ItalianQuotes: __t.unit(),
  PortugueseQuotes: __t.unit(),
  JapaneseQuotes: __t.unit(),
  KoreanQuotes: __t.unit(),
  ChineseQuotes: __t.unit(),
  UkrainianQuotes: __t.unit(),
  ArabicQuotes: __t.unit(),
  HindiQuotes: __t.unit(),
  DutchQuotes: __t.unit(),
  SwedishQuotes: __t.unit(),
  TurkishQuotes: __t.unit(),
});
export type GameMode = __Infer<typeof GameMode>;

export const GameModeCount = __t.object("GameModeCount", {
  get gameType() {
    return GameType.name("GameType");
  },
  get gameMode() {
    return GameMode.name("GameMode");
  },
  finishedGames: __t.i32().name("FinishedGames"),
  nonLonelyGames: __t.i32().name("NonLonelyGames"),
  startedGames: __t.i32().name("StartedGames"),
  totalWpm: __t.f64().name("TotalWpm"),
  minWpm: __t.f64().name("MinWpm"),
  maxWpm: __t.f64().name("MaxWpm"),
  gameCount: __t.i32().name("GameCount"),
});
export type GameModeCount = __Infer<typeof GameModeCount>;

export const GameRecord = __t.object("GameRecord", {
  id: __t.string().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  gameId: __t.string().name("GameId"),
  get gameMode() {
    return GameMode.name("GameMode");
  },
  get gameType() {
    return GameType.name("GameType");
  },
  year: __t.i32().name("Year"),
  month: __t.i32().name("Month"),
  date: __t.i64().name("Date"),
  timeMs: __t.i64().name("TimeMs"),
  placement: __t.i32().name("Placement"),
  wpm: __t.f64().name("Wpm"),
  xpGained: __t.i32().name("XpGained"),
  eloChange: __t.i32().name("EloChange"),
  day: __t.string().name("Day"),
});
export type GameRecord = __Infer<typeof GameRecord>;

export const GameStart = __t.object("GameStart", {
  scheduledId: __t.u64().name("ScheduledId"),
  gameId: __t.string().name("GameId"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type GameStart = __Infer<typeof GameStart>;

// The tagged union or sum type for the algebraic type `GameState`.
export const GameState = __t.enum("GameState", {
  Lobby: __t.unit(),
  Countdown: __t.unit(),
  Racing: __t.unit(),
  Archived: __t.unit(),
});
export type GameState = __Infer<typeof GameState>;

// The tagged union or sum type for the algebraic type `GameType`.
export const GameType = __t.enum("GameType", {
  Public: __t.unit(),
  Private: __t.unit(),
  Practice: __t.unit(),
});
export type GameType = __Infer<typeof GameType>;

export const GlobalStats = __t.object("GlobalStats", {
  date: __t.string().name("Date"),
  get stats() {
    return __t.array(GameModeCount).name("Stats");
  },
  get total() {
    return GameModeCount.name("Total");
  },
  dailyActivePlayers: __t.i32().name("DailyActivePlayers"),
});
export type GlobalStats = __Infer<typeof GlobalStats>;

export const PersonalRecord = __t.object("PersonalRecord", {
  id: __t.string().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  get gameMode() {
    return GameMode.name("GameMode");
  },
  gameRecordId: __t.string().name("GameRecordId"),
  wpm: __t.f64().name("Wpm"),
});
export type PersonalRecord = __Infer<typeof PersonalRecord>;

export const Player = __t.object("Player", {
  identity: __t.identity().name("Identity"),
  playerId: __t.string().name("PlayerId"),
  name: __t.string().name("Name"),
  totalGames: __t.i32().name("TotalGames"),
  wins: __t.i32().name("Wins"),
  level: __t.i32().name("Level"),
  xp: __t.i32().name("Xp"),
  xpRequiredForNextLevel: __t.i32().name("XpRequiredForNextLevel"),
  totalWordsTyped: __t.i32().name("TotalWordsTyped"),
  totalTimeSpentMs: __t.i64().name("TotalTimeSpentMs"),
  isBot: __t.bool().name("IsBot"),
  get botConfig() {
    return __t.option(BotConfig).name("BotConfig");
  },
  get color() {
    return PlayerColor.name("Color");
  },
  isAnonymous: __t.bool().name("IsAnonymous"),
  lastGameDate: __t.i64().name("LastGameDate"),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `PlayerColor`.
export const PlayerColor = __t.enum("PlayerColor", {
  Red: __t.unit(),
  Orange: __t.unit(),
  Amber: __t.unit(),
  Yellow: __t.unit(),
  Lime: __t.unit(),
  Green: __t.unit(),
  Emerald: __t.unit(),
  Teal: __t.unit(),
  Cyan: __t.unit(),
  Sky: __t.unit(),
  Blue: __t.unit(),
  Indigo: __t.unit(),
  Violet: __t.unit(),
  Purple: __t.unit(),
  Fuchsia: __t.unit(),
  Pink: __t.unit(),
  Rose: __t.unit(),
});
export type PlayerColor = __Infer<typeof PlayerColor>;

export const PlayerProgress = __t.object("PlayerProgress", {
  id: __t.string().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  playerPublicId: __t.string().name("PlayerPublicId"),
  gameId: __t.string().name("GameId"),
  playerName: __t.string().name("PlayerName"),
  playerLevel: __t.i32().name("PlayerLevel"),
  progressIndex: __t.i32().name("ProgressIndex"),
  isBot: __t.bool().name("IsBot"),
  isAnonymous: __t.bool().name("IsAnonymous"),
  createdAt: __t.i64().name("CreatedAt"),
  characterHistory: __t.byteArray().name("CharacterHistory"),
  time: __t.i64().name("Time"),
  placement: __t.i32().name("Placement"),
  joinCode: __t.string().name("JoinCode"),
  wpm: __t.f64().name("Wpm"),
  get playerColor() {
    return PlayerColor.name("PlayerColor");
  },
  highestProgress: __t.i32().name("HighestProgress"),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const XpGain = __t.object("XpGain", {
  id: __t.string().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  gameId: __t.string().name("GameId"),
  timestamp: __t.i64().name("Timestamp"),
  baseXp: __t.i32().name("BaseXp"),
  get multipliers() {
    return __t.array(XpMultiplier).name("Multipliers");
  },
  totalXp: __t.i32().name("TotalXp"),
});
export type XpGain = __Infer<typeof XpGain>;

export const XpGainCleaner = __t.object("XpGainCleaner", {
  scheduledId: __t.u64().name("ScheduledId"),
  scheduledAt: __t.scheduleAt().name("ScheduledAt"),
});
export type XpGainCleaner = __Infer<typeof XpGainCleaner>;

export const XpMultiplier = __t.object("XpMultiplier", {
  label: __t.string().name("Label"),
  value: __t.string().name("Value"),
  type: __t.string().name("Type"),
});
export type XpMultiplier = __Infer<typeof XpMultiplier>;

