// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BotConfig = __t.object("BotConfig", {
  typingRate: __t.f64(),
  errorRate: __t.f64(),
});
export type BotConfig = __Infer<typeof BotConfig>;

export const BotFillTrigger = __t.object("BotFillTrigger", {
  scheduledId: __t.u64(),
  gameId: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type BotFillTrigger = __Infer<typeof BotFillTrigger>;

export const BotProgressUpdate = __t.object("BotProgressUpdate", {
  scheduledId: __t.u64(),
  playerProgressId: __t.string(),
  phraseLength: __t.i32(),
  scheduledAt: __t.scheduleAt(),
});
export type BotProgressUpdate = __Infer<typeof BotProgressUpdate>;

// The tagged union or sum type for the algebraic type `CharacterEventType`.
export const CharacterEventType = __t.enum("CharacterEventType", {
  Correct: __t.unit(),
  Incorrect: __t.unit(),
  Backspace: __t.unit(),
});
export type CharacterEventType = __Infer<typeof CharacterEventType>;

export const CountdownStart = __t.object("CountdownStart", {
  scheduledId: __t.u64(),
  gameId: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type CountdownStart = __Infer<typeof CountdownStart>;

export const Elo = __t.object("Elo", {
  id: __t.string(),
  playerId: __t.identity(),
  get gameMode() {
    return GameMode;
  },
  rating: __t.i32(),
});
export type Elo = __Infer<typeof Elo>;

export const Game = __t.object("Game", {
  id: __t.string(),
  phrase: __t.string(),
  createdAt: __t.i64(),
  racingStartedAt: __t.i64(),
  countdownDurationMs: __t.i64(),
  get state() {
    return GameState;
  },
  get gameMode() {
    return GameMode;
  },
  get gameType() {
    return GameType;
  },
  placements: __t.array(__t.identity()),
  owner: __t.option(__t.identity()),
  attribution: __t.option(__t.string()),
});
export type Game = __Infer<typeof Game>;

export const GameArchiver = __t.object("GameArchiver", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameArchiver = __Infer<typeof GameArchiver>;

// The tagged union or sum type for the algebraic type `GameMode`.
export const GameMode = __t.enum("GameMode", {
  English500: __t.unit(),
  Spanish500: __t.unit(),
  French500: __t.unit(),
  German500: __t.unit(),
  Italian500: __t.unit(),
  Portuguese500: __t.unit(),
  Japanese500: __t.unit(),
  Korean500: __t.unit(),
  Chinese500: __t.unit(),
  Ukrainian500: __t.unit(),
  Arabic500: __t.unit(),
  Hindi500: __t.unit(),
  Dutch500: __t.unit(),
  Swedish500: __t.unit(),
  Turkish500: __t.unit(),
  EnglishQuotes: __t.unit(),
  SpanishQuotes: __t.unit(),
  FrenchQuotes: __t.unit(),
  GermanQuotes: __t.unit(),
  ItalianQuotes: __t.unit(),
  PortugueseQuotes: __t.unit(),
  JapaneseQuotes: __t.unit(),
  KoreanQuotes: __t.unit(),
  ChineseQuotes: __t.unit(),
  UkrainianQuotes: __t.unit(),
  ArabicQuotes: __t.unit(),
  HindiQuotes: __t.unit(),
  DutchQuotes: __t.unit(),
  SwedishQuotes: __t.unit(),
  TurkishQuotes: __t.unit(),
});
export type GameMode = __Infer<typeof GameMode>;

export const GameModeCount = __t.object("GameModeCount", {
  get gameType() {
    return GameType;
  },
  get gameMode() {
    return GameMode;
  },
  finishedGames: __t.i32(),
  nonLonelyGames: __t.i32(),
  startedGames: __t.i32(),
  totalWpm: __t.f64(),
  minWpm: __t.f64(),
  maxWpm: __t.f64(),
  gameCount: __t.i32(),
});
export type GameModeCount = __Infer<typeof GameModeCount>;

export const GameRecord = __t.object("GameRecord", {
  id: __t.string(),
  playerId: __t.identity(),
  gameId: __t.string(),
  get gameMode() {
    return GameMode;
  },
  get gameType() {
    return GameType;
  },
  year: __t.i32(),
  month: __t.i32(),
  date: __t.i64(),
  timeMs: __t.i64(),
  placement: __t.i32(),
  wpm: __t.f64(),
  xpGained: __t.i32(),
  eloChange: __t.i32(),
  day: __t.string(),
});
export type GameRecord = __Infer<typeof GameRecord>;

export const GameStart = __t.object("GameStart", {
  scheduledId: __t.u64(),
  gameId: __t.string(),
  scheduledAt: __t.scheduleAt(),
});
export type GameStart = __Infer<typeof GameStart>;

// The tagged union or sum type for the algebraic type `GameState`.
export const GameState = __t.enum("GameState", {
  Lobby: __t.unit(),
  Countdown: __t.unit(),
  Racing: __t.unit(),
  Archived: __t.unit(),
});
export type GameState = __Infer<typeof GameState>;

// The tagged union or sum type for the algebraic type `GameType`.
export const GameType = __t.enum("GameType", {
  Public: __t.unit(),
  Private: __t.unit(),
  Practice: __t.unit(),
});
export type GameType = __Infer<typeof GameType>;

export const GlobalStats = __t.object("GlobalStats", {
  date: __t.string(),
  get stats() {
    return __t.array(GameModeCount);
  },
  get total() {
    return GameModeCount;
  },
  dailyActivePlayers: __t.i32(),
});
export type GlobalStats = __Infer<typeof GlobalStats>;

export const PersonalRecord = __t.object("PersonalRecord", {
  id: __t.string(),
  playerId: __t.identity(),
  get gameMode() {
    return GameMode;
  },
  gameRecordId: __t.string(),
  wpm: __t.f64(),
});
export type PersonalRecord = __Infer<typeof PersonalRecord>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  playerId: __t.string(),
  name: __t.string(),
  totalGames: __t.i32(),
  wins: __t.i32(),
  level: __t.i32(),
  xp: __t.i32(),
  xpRequiredForNextLevel: __t.i32(),
  totalWordsTyped: __t.i32(),
  totalTimeSpentMs: __t.i64(),
  isBot: __t.bool(),
  get botConfig() {
    return __t.option(BotConfig);
  },
  get color() {
    return PlayerColor;
  },
  isAnonymous: __t.bool(),
  lastGameDate: __t.i64(),
});
export type Player = __Infer<typeof Player>;

// The tagged union or sum type for the algebraic type `PlayerColor`.
export const PlayerColor = __t.enum("PlayerColor", {
  Red: __t.unit(),
  Orange: __t.unit(),
  Amber: __t.unit(),
  Yellow: __t.unit(),
  Lime: __t.unit(),
  Green: __t.unit(),
  Emerald: __t.unit(),
  Teal: __t.unit(),
  Cyan: __t.unit(),
  Sky: __t.unit(),
  Blue: __t.unit(),
  Indigo: __t.unit(),
  Violet: __t.unit(),
  Purple: __t.unit(),
  Fuchsia: __t.unit(),
  Pink: __t.unit(),
  Rose: __t.unit(),
});
export type PlayerColor = __Infer<typeof PlayerColor>;

export const PlayerProgress = __t.object("PlayerProgress", {
  id: __t.string(),
  playerId: __t.identity(),
  playerPublicId: __t.string(),
  gameId: __t.string(),
  playerName: __t.string(),
  playerLevel: __t.i32(),
  progressIndex: __t.i32(),
  isBot: __t.bool(),
  isAnonymous: __t.bool(),
  createdAt: __t.i64(),
  characterHistory: __t.byteArray(),
  time: __t.i64(),
  placement: __t.i32(),
  joinCode: __t.string(),
  wpm: __t.f64(),
  get playerColor() {
    return PlayerColor;
  },
  highestProgress: __t.i32(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const XpGain = __t.object("XpGain", {
  id: __t.string(),
  playerId: __t.identity(),
  gameId: __t.string(),
  timestamp: __t.i64(),
  baseXp: __t.i32(),
  get multipliers() {
    return __t.array(XpMultiplier);
  },
  totalXp: __t.i32(),
});
export type XpGain = __Infer<typeof XpGain>;

export const XpGainCleaner = __t.object("XpGainCleaner", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type XpGainCleaner = __Infer<typeof XpGainCleaner>;

export const XpMultiplier = __t.object("XpMultiplier", {
  label: __t.string(),
  value: __t.string(),
  type: __t.string(),
});
export type XpMultiplier = __Infer<typeof XpMultiplier>;

