// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  XpMultiplier,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey().name("Id"),
  playerId: __t.identity().name("PlayerId"),
  gameId: __t.string().name("GameId"),
  timestamp: __t.i64().name("Timestamp"),
  baseXp: __t.i32().name("BaseXp"),
  get multipliers() {
    return __t.array(XpMultiplier).name("Multipliers");
  },
  totalXp: __t.i32().name("TotalXp"),
});
