// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  XpMultiplier,
} from "./types";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity().name("player_id"),
  gameId: __t.string().name("game_id"),
  timestamp: __t.i64(),
  baseXp: __t.i32().name("base_xp"),
  get multipliers() {
    return __t.array(XpMultiplier);
  },
  totalXp: __t.i32().name("total_xp"),
});
