// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import GameMode from "./game_mode_type";


export default __t.row({
  gameId: __t.string().primaryKey(),
  get gameMode() {
    return GameMode;
  },
  createdAt: __t.i64(),
  archivedAt: __t.i64(),
  placementCount: __t.i32(),
});
