// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

// The tagged union or sum type for the algebraic type `GameMode`.
const GameMode = __t.enum("GameMode", {English500: __t.unit(),
  Spanish500: __t.unit(),
  French500: __t.unit(),
  German500: __t.unit(),
  Italian500: __t.unit(),
  Portuguese500: __t.unit(),
  Japanese500: __t.unit(),
  Korean500: __t.unit(),
  Chinese500: __t.unit(),
  Ukrainian500: __t.unit(),
  Arabic500: __t.unit(),
  Hindi500: __t.unit(),
  Dutch500: __t.unit(),
  Swedish500: __t.unit(),
  Turkish500: __t.unit(),
  EnglishQuotes: __t.unit(),
  SpanishQuotes: __t.unit(),
  FrenchQuotes: __t.unit(),
  GermanQuotes: __t.unit(),
  ItalianQuotes: __t.unit(),
  PortugueseQuotes: __t.unit(),
  JapaneseQuotes: __t.unit(),
  KoreanQuotes: __t.unit(),
  ChineseQuotes: __t.unit(),
  UkrainianQuotes: __t.unit(),
  ArabicQuotes: __t.unit(),
  HindiQuotes: __t.unit(),
  DutchQuotes: __t.unit(),
  SwedishQuotes: __t.unit(),
  TurkishQuotes: __t.unit(),
  Russian500: __t.unit(),
  RussianQuotes: __t.unit(),
});

export default GameMode;


