// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Red = { tag: "Red" };
export type Orange = { tag: "Orange" };
export type Amber = { tag: "Amber" };
export type Yellow = { tag: "Yellow" };
export type Lime = { tag: "Lime" };
export type Green = { tag: "Green" };
export type Emerald = { tag: "Emerald" };
export type Teal = { tag: "Teal" };
export type Cyan = { tag: "Cyan" };
export type Sky = { tag: "Sky" };
export type Blue = { tag: "Blue" };
export type Indigo = { tag: "Indigo" };
export type Violet = { tag: "Violet" };
export type Purple = { tag: "Purple" };
export type Fuchsia = { tag: "Fuchsia" };
export type Pink = { tag: "Pink" };
export type Rose = { tag: "Rose" };

