// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import XpEffect from "./xp_effect_type";


export default __t.row({
  id: __t.string().primaryKey(),
  playerId: __t.identity(),
  gameId: __t.string(),
  timestamp: __t.i64(),
  get effects() {
    return __t.array(XpEffect);
  },
  totalXp: __t.i32(),
});
