using System;

namespace StdbModule;

public static partial class ChineseQuotes
{
    public static class 杜甫
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "讀書破萬卷，下筆如有神。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "白鷗沒浩蕩，萬里誰能馴。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "卻看妻子愁何在，漫卷詩書喜欲狂。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "白日放歌須縱酒，青春作伴好還鄉。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "欲覺聞晨鐘，令人發深省。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "會當凌絕頂，-覽眾山小。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "翻手作雲覆手雨，紛紛輕薄何須數。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "人生不相見，動如參與商。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "炙手可熱勢絕倫，慎莫近前丞相嗔。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "此身飲罷無歸處，獨立蒼茫自詠詩。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "窮年憂黎元，嘆息腸內熱。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "朱門酒肉臭，路有凍死骨。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "明眸皓齒今何在，血污游魂歸不得。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "安得壯士輓天河，凈洗甲兵長不用。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "眼枯即見骨，天地終無情。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "吏呼-何怒，婦啼-何苦。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "積屍草木腥，流血川原丹。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "棄絕蓬室居，塌然摧肺肝。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "存者無消息，死者為塵泥。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "人生無家別，何以為烝黎。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "絕代有佳人，幽居在空谷。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "但見新人笑，那聞舊人哭。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "摘花不插髮，採柏動盈掬。天寒翠袖薄，日暮倚修竹。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "冠蓋滿京華，斯人獨憔悴。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "千秋萬歲名，寂寞身後事。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "輓弓當輓強，用箭當用長。射人先射馬，擒賊先擒王。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "落日照大旗，馬鳴風蕭蕭。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "嗚呼-歌兮歌已哀，悲風為我從天來。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "君不見朝來割素鬐，咫尺波濤永相失。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "但看古來盛名下，終日坎壈纏其身。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "憶昔開元全盛日，小邑猶藏萬家室。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "狐狸何足道，豺虎正縱橫。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "泥融飛燕子，沙暖睡鴛鴦。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "今春看又過，何日是歸年。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "新松恨不高千尺，惡竹應須斬萬竿。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "三年奔走空皮骨，信有人間行路難。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "花近高樓傷客心，萬方多難此登臨。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "錦江春色來天地，玉壘浮雲變古今。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "北極朝廷終不散，西山寇盜莫相侵。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "可憐後主還祠廟，日暮聊為梁甫吟。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "兩個黃鸝鳴翠柳，-行白鷺上青天。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "窗含西嶺千秋雪，門泊東吳萬里船。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "文章千古事，得失寸心知。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "江間波浪兼天涌，塞上風雲接地陰。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "同學少年多不賤，五陵衣馬自輕肥。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "香稻啄餘鸚鵡粒，碧梧棲老鳳凰枝。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "聞道長安似奕棋，百年世事不勝悲，王侯第宅皆新主，文武衣冠異昔時。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "庾信平生最萧瑟，暮年诗赋动江关。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "悵望千秋-灑淚，蕭條異代不同時。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "最是楚宮俱泯滅，舟人指點到今疑。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "畫圖省識春風面，環佩空歸月夜魂。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "伯仲之間見伊呂，指揮若定失蕭曹。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "-飯未曾留俗客，數篇今見古人詩。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "好雨知时节，当春乃发生。隨風潛入夜，潤物細無聲。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "人生七十古來稀。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "細推物理須行樂，何用浮名絆此身？", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "國破山河在 城春草木深", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "感時花濺淚 恨別鳥驚心", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "烽火連三月 家書抵萬金", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "出師未捷身先死，長使英雄淚滿襟。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "星垂平野闊，月湧大江流", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "飄飄何所似，天地-沙鷗", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "安得廣廈千萬間，大庇天下寒士俱歡顏，風雨⒈動安如山。", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "哭聲直上干雲霄", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "語不驚人死不休", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "功蓋三分國，名成八陣圖", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "无边落木萧萧下，不尽长江滚滚来", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "露从今夜白，月是故乡明", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "正是江南好風景，落花時節又逢君", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "花徑不曾緣客掃，蓬門今始為君開", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "爾曹身與名俱滅，不廢江河萬古流", Author = "杜甫" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/杜甫", Text = "暖汤濯我足，剪纸招我魂", Author = "杜甫" },
        };
    }
}