using System;

namespace StdbModule;

public static partial class ChineseQuotes
{
    public static class 鲁迅
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我想：希望本是无所谓有，无所谓无的。这正如地上的路；其实地上本没有路，走的人多了，也便成了路。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "当我沉默著的時候，我覺得充實；我將开口，同時感到空虚。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "万家墨面没蒿莱，敢有歌吟动地哀。心事浩茫连广宇，于无声处听惊雷。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "石在，火种是不會絕的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "辱骂与恐吓不是战斗。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "豈有豪情似舊時，花開花落兩由之。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "在我的後園，可以看見墻外有兩株樹，一株是棗樹，還有一株也是棗樹。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "人必生活着，爱才有所附丽。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "横眉冷对千夫指，俯首甘为孺子牛。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "世上如果還有真要活下去的人們，就先該敢說，敢笑，敢哭，敢怒，敢罵，敢打，在這可詛咒的地方擊退了可詛咒的時代！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "不满是向上的车轮，能够载不自满的人类，向人道前进。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "曾经阔气的要复古，正在阔气的要保持现状，未曾阔气的要革新。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "悲剧将人生的有价值的东西毁灭给人看，喜剧将那无价值的撕破给人看。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "节省时间，也就是使一个人的有限的生命更加有效，而也即等于延长了人的生命。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "巨大的建筑，总是由一木一石叠起来的，我们何妨做做这一木一石呢？我时常做些零碎事，就是为此。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "怀疑并不是缺点。总是疑，而并不下断语，这才是缺点。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "孩子是要别人教的，毛病是要别人医的，即使自己是教员或医生。但做人处事的法子，却恐怕要自己斟酌，许多人开来的良方，往往不过是废纸。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "寄意寒星荃不察，我以我血荐轩辕。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "心事浩茫连广宇，于无声处听惊雷。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "血沃中原肥劲草，寒凝大地发春华。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我們中國最偉大最永久，而且最普遍的藝術也就是男人扮女人。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "忍看朋辈成新鬼，怒向刀丛觅小诗。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "无情未必真豪杰，怜子如何不丈夫。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "度尽劫波兄弟在，相逢一笑泯恩仇。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "史家之绝唱，无韵之离骚。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "凡事总需研究，才会明白。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "救救孩子", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "墨写的谎言掩盖不了血写的事实。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "凡是愚弱的国民，即使体格如何健全，如何茁壮，也只能做毫無意義的示眾的材料和看客，病死多少是不必以為不幸的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "革命是要人生，不是要人死！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "所謂中國的文明者，其實不過是安排給闊人享用的人肉的筵宴；所謂中國者，其實不過是安排這人肉的筵宴的廚房。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中医不过是一种有意的或无意的骗子。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "时间就是性命，无端地空耗别人的时间，其实是无异于谋财害命的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "时间，就像海绵里的话，只要愿挤，总是还是有的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "人被杀于万众聚观之中，比被杀在“人不知鬼不觉”的地方快活，因为他可以妄想，博得观众中的或人的眼泪。但是，无泪的人无论被杀在什麽所在，於他并无不同。杀了无泪的人，一定连血也不见。爱人不觉他被杀之惨，仇人也終於得不到杀他之樂：這是他的報恩和復仇。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "仰慕往古的，回往古去罷！想出世的，快出世罷！想上天的，快上天罷！靈魂要離開肉體的，趕快離開罷！現在的地上，應該是執著現在，執著地上的人們居住的。但厭惡現世的人們還住著。這都是現世的仇仇，他們一日存在，現世即一日不能得救。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "勇者憤怒，抽刃向更強者；怯者憤怒，卻抽刃向更弱者。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "不可救藥的民族中，一定有許多英雄，專向孩子們瞪眼。這些孱頭們！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "古训所教的就是這樣的生活法，教人不要動。不動，失錯當然就較少了，但不活的巖石泥沙，失錯不是更少麽？我以為人類為向上，即發展起見，應該活動，活動而有若幹失錯，也不要緊。惟獨半死半生的茍活，是全盤失錯的。因為他掛了生活的招牌，其實卻引人到死路上去！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "但倘若一定要問我青年應當向怎樣的目標，那麽，我只可以說出我為別人設計的話，就是：一要生存，二要溫飽，三要發展。有敢來阻礙這三事者，無論是誰，我們都反抗他，撲滅他", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我們的古人又造出了一種難到可怕的一塊一塊的文字；但我還並不十分怨恨，因為我覺得他們倒並不是故意的。然而，許多人卻不能借此說話了，加以古訓所築成的高墻，更使他們連想也不敢想。現在我們所能聽到的不過是幾個聖人之徒的意見和道理，為了他們自己；至於百姓，卻就默默的生長，萎黃，枯死了，像壓在大石底下的草一樣，已經有四千年！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "意圖生存，而太卑怯，結果就得死亡。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "唯獨半死半生的苟活，是全盤失措的。因為他掛了生活的招牌，其實卻引人死路上去！", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "楼下一个男人病得要死，那间隔壁的一家唱着留声机，对面是弄孩子。楼上有两人狂笑；还有打牌声。河中的船上有女人哭着她死去的母亲。人类的悲欢并不相通，我只觉得他们吵闹。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "惟沉默是最高的轻蔑。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國人的性情是總喜歡調和折中的，譬如你說，這屋子太暗，須在這裏開一個窗，大家一定不允許的。但如果你主張拆掉屋頂他們就來調和，願意開窗了。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我們此後實在只有兩條路：一是抱著古文而死掉，一是捨掉古文而生存。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "窮人的孩子，蓬頭垢面在街上轉，闊人的孩子，妖形妖勢，嬌聲嬌氣的在家裏轉，長大了，都昏天黑地的在社會轉，同他們的父親一樣，或者還不如。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國大約太老了，社會上事無大小，都惡劣不堪，像一只黑色的染缸，無論加進甚麽新東西去，都變成漆黑。可是除了再想法子來改革之外，也再沒有別的路。我看一切理想家，不是懷念『過去』，就『是希望將來』，而對於『現在』這一個題目，都繳了白卷，因為誰也開不出藥方。所有最好的藥方即所謂『希望將來』的就是。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我先前總以為人是有罪，所以鎗斃或坐監的。現在才知道其中的許多，是先因為被人認為『可惡』，這才終於犯了罪。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "無論從那裏來的，只要是食物，壯健者大抵就無需思索，承認是吃的東西。惟有衰病的，卻總常想到害胃，傷身，特有許多禁例，許多避忌；還有一大套比較利害而終於不得要領的理由，例如吃固無妨，而不吃尤穩，食之或當有益，然究以不吃為宜雲雲之類。但這一類人物總要日見其衰弱的，自己先已失了活氣了。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國人的不敢正視各方面，用瞞和騙，造出奇妙的逃路來，而自以為正路。在這路上，就證明著國民性的怯弱，懶惰而又巧滑。一天一天的滿足著，即一天一天的墮落著，但卻又覺得日見其光榮。在事實上，亡國一次，即添加幾個殉難的忠臣，後來每不想光復舊物，而只去贊美那幾個忠臣；遭劫一次，即造成一群不辱的烈女，事過之後，也每每不思懲兇，自衛，卻只顧歌詠那一群烈女。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國人的雖然想了各種茍活的理想鄉，可惜終於沒有實現。但我卻替他們發現了，你們大概知道的罷，就是北京的第一監獄。這監獄在宣武門外的空地裏，不怕鄰家的火災；每日兩餐，不慮凍餒；起居有定，不會傷生；構造堅固，不會倒塌；禁卒管著，不會再犯；強盜是決不會來搶的。住在裏面，何等安全，真是『千金之子坐不垂堂』了。但缺少的就有一件事：自由。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國各處是壁，然而無形，像『鬼打墻』一般，使你隨時能『碰』，能打這墻的，能碰而不感到痛苦的，是勝利者。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國中流的家庭，教孩子大抵只有兩種法。其一是任其跋扈，一點也不管，罵人固可，打人亦無不可，在門內或門前是暴主，是霸王，但到外面便如失了網的蜘蛛一般，立刻毫無能力。其二，是終日給以冷遇或呵斥，甚於打撲，使他畏葸退縮，仿佛一個奴才，一個傀儡，然而父母卻美其名曰『聽話』，自以為是教育的成功，待到他們外面來，則如暫出樊籠的小禽，他決不會飛鳴，也不會跳躍。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "戰士死了的時候，蒼蠅所首先發見的是他的缺點和傷痕，嘬著，營營地叫著，以為得意，以為比死了的戰士更英雄。但是戰士已經死了，不再來揮去牠們。於是乎蒼蠅們即更其營營地叫，自以為倒是不朽的聲音，因為牠們的完全，遠在戰士之上。的確的，誰也沒有發見過蒼蠅們的缺點和創傷。然而，有缺點的戰士終竟是戰士，完美的蒼蠅也終竟不過是蒼蠅。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我獨不解中國人何以於舊狀況那麽心平氣和，於較新的機運就這麽疾首蹙額；於已成之局那麽委曲求全；於初興之事就這麽求全責備？", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國人不疑自己的多疑。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "群眾，尤其是中國的──永遠是戲劇的看客。犧牲上場，如果顯得慷慨，他們就看了悲壯劇；如果顯得觳觫（即恐懼顫抖），他們就看了滑稽劇。北京的羊肉鋪常有幾個人張嘴看剝羊，仿佛頗為愉快，人的犧牲能給他們的益處，也不過如此。而況事後走不幾步，他們並這一點也就忘了。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我先前的攻擊社會，其實也是無聊的。社會沒有知道我在攻擊，倘一知道，我早已死無葬身之所了……我之得以偷生者，因為他們大多數不識字，不知道，並且我的話也無效力，如一箭之入大海。否則，幾條雜感，就可以送命的。民眾的懲罰之心，並不下於學者和軍閥。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我總覺得洋鬼子比中國人文明，貨只管排，而那品性卻很有可學的地方，這種敢於指摘自己國度的錯誤的，中國人就很少。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "在中國，尤其是在都市裏，倘使路上有暴病倒地，或翻車捽摔傷的人，路人圍觀或甚至高興的人盡有，有肯伸手來扶助一下的人卻是極少的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "中國人自己誠然不善於戰爭，卻並沒有詛咒戰爭；自己誠然不願出戰，卻並未同情於不願出戰的他人；雖然想到自己，卻沒有想到他人的自己。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "在要求天才的產生之前，應該先要求可以使天才生長的民眾。──譬如想有喬木，想看好花，一定要有好土；沒有土，便沒有花木了；所以土實在較花木還重要。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "即使艱難，也還要做；愈艱難，就愈要做。改革，是向來沒有一帆風順的，冷笑家的贊成，是在見了成功之後……", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "「可惜中國人但對於羊顯兇獸相，而對於兇獸則顯羊相，所以即使顯兇獸相，也還是卑怯的國民。這樣下去，一定要完結的。」「我想，要中國得救，也不必添甚麽東西進去，只要青年們將這兩種性質的古傳用法，反過來一用就夠了；對手如兇獸時就如兇獸，對手如羊時就如羊！」", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "凡中國所有的，外國也都有。外國人說中國多臭蟲，但西洋也有臭蟲……假使世界上只有一家有臭蟲，而遭別人指摘的時候，實在也不太舒服的……最好還是希望別家也有臭蟲，而竟發現了就更好。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "「自有歷史以來，中國人是一向被同族屠戮、奴隸、敲掠、刑辱、壓迫下來的，非人類所能忍受的楚痛，也都身受過，每一考查，真教人覺得不像活在人間。」", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "「從生活窘迫過來的人，一到了有錢，容易變成兩種情形：一種是理想世界，替處同一境遇的人著想，便成為人道主義；一種是甚麽都是自己掙起來，從前的遭遇，使他覺得甚麽都是冷酷，便流為個人主義。我們中國大概是變成個人主義者多。」", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "許多歷史的教訓，都是用極大的犧牲換來的。譬如吃東西吧，某種是毒物不能吃，我們好象全慣了，很平常了。不過，還一定是以前有多少人吃死了，才知的。所以我想，第一次吃螃蟹的人是很可佩服的，不是勇士誰敢去吃它呢？螃蟹有人吃，蜘蛛一定也有人吃過，不過不好吃，所以後人不吃了，像這種人我們當極端感謝的。」", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "愛國之士又說，中國人是愛和平的。但我殊不解既愛和平，何以國內連年打仗？或者這話應該修正：中國人對外國人是愛和平的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "一見短袖子，立刻想到白臂膊，立刻想到全裸体，立刻想到生殖器，立刻想到性交，立刻想到杂交，立刻想到私生子。中国人的想象惟在這一层能够如此跃进。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "石在，火種是不會絕的。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "希望是附丽于存在的，有存在，便有希望，有希望，便是光明。如果历史家的话不是诳话，则世界上的事物可还没有因为黑暗而长存的先例。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "即使目下还有点逆水行舟，也只好拉纤；顺水固然好得很，然而还是少不得把舵的。这拉纤或把舵的好方法，虽然也可以口谈，但大抵得益于实验，无论怎么看风看水，目的只是一个：向前。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "願中國青年都擺脫冷氣，只是向上走，不必聽自暴自棄者流的話。能做事的做事，能發聲的發聲。有一分熱，發一分光。就令螢火一般，也可以在黑暗裡發一點光，不必等候炬火。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "死者倘不埋在活人的心中,那就真的死掉了。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "真的勇士，敢于直面惨淡的人生，敢于正视淋漓的鲜血。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "这是怎样的哀痛者和幸福者？然而造化又常常为庸人设计，以时间的流驶，来洗涤旧迹，仅使留下淡红的血色和微漠的悲哀。在这淡红的血色和微漠的悲哀中，又给人暂得偷生，维持着这似人非人的世界。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "惨象，已使我目不忍视了；流言，尤使我耳不忍闻。我还有什么话可说呢？我懂得衰亡民族之所以默无声息的缘由了。沉默呵，沉默呵！不在沉默中爆发，就在沉默中灭亡。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "惟有民魂是值得宝贵的，惟有他发扬起来，中国才有真进步。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "唯独革命家，无论他生或死，都能给大家以幸福。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "假如一间铁屋子，是绝无窗户而万难破毁的，里面有许多熟睡的人们，不久都要闷死了，然而是从昏睡入死灭，并不感到就死的悲哀。现在你大嚷起来，惊醒了较为清醒的几个人，使这不幸的少数者来受无可挽救的临终的苦楚，你倒以為對的起他們麼？", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "然而几个人既然起来，你不能说绝没有毁坏这铁屋的希望。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "是的，我雖然自有我的確信，然而說到希望，卻是不能抹殺的，因為希望是在於將來，決不能以我之必無的證明，來折服了他之所謂可有，於是我終於答應他也做文章了，這便是最初的一篇《狂人日記》。", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "遭劫一次，即造成一群不辱的烈女，事過之後，也每每不思懲兇，自衞，卻只顧歌詠那一群烈女。彷彿亡國遭劫的事，反而給中國人發揮『兩間正氣』的機會，增高價值……因為我們已經借死人獲得最上的光榮了", Author = "鲁迅" },
            new Quote { Id = "https://zh.wikiquote.org/wiki/鲁迅", Text = "我們從古以來，就有埋頭苦幹的人，有拼命硬干的人，有为民请命的人，有舍身求法的人，……虽是等于为帝王将相作家谱的所谓“正史”，也往往掩不住他们的光耀，这就是中国的脊梁。", Author = "鲁迅" },
        };
    }
}