export interface ItemIcon {
  defaultName: string;
  filePath: string;
}

export const ICONS: ItemIcon[] = [
  { defaultName: "Alert Shield", filePath: "/futuristic_pixel_icons/Alert Shield.png" },
  { defaultName: "Alien Blue Helmet", filePath: "/futuristic_pixel_icons/Alien Blue Helmet.png" },
  { defaultName: "Alien Egg", filePath: "/futuristic_pixel_icons/Alien Egg.png" },
  { defaultName: "Alien Green Helmet", filePath: "/futuristic_pixel_icons/Alien Green Helmet.png" },
  { defaultName: "Alien Purple Helmet", filePath: "/futuristic_pixel_icons/Alien Purple Helmet.png" },
  { defaultName: "Amber Crystal", filePath: "/futuristic_pixel_icons/Amber Crystal.png" },
  { defaultName: "Amber Gloves", filePath: "/futuristic_pixel_icons/Amber Gloves.png" },
  { defaultName: "Amber Helm", filePath: "/futuristic_pixel_icons/Amber Helm.png" },
  { defaultName: "Amber Neon Shield", filePath: "/futuristic_pixel_icons/Amber Neon Shield.png" },
  { defaultName: "Amber Ring", filePath: "/futuristic_pixel_icons/Amber Ring.png" },
  { defaultName: "Amber Sickle", filePath: "/futuristic_pixel_icons/Amber Sickle.png" },
  { defaultName: "Amber Star Crystal", filePath: "/futuristic_pixel_icons/Amber Star Crystal.png" },
  { defaultName: "Army Crate", filePath: "/futuristic_pixel_icons/Army Crate.png" },
  { defaultName: "Battery", filePath: "/futuristic_pixel_icons/Battery.png" },
  { defaultName: "Big Battery", filePath: "/futuristic_pixel_icons/Big Battery.png" },
  { defaultName: "Black Conveyor Belt", filePath: "/futuristic_pixel_icons/Black Conveyor Belt.png" },
  { defaultName: "Black Mini Pistol", filePath: "/futuristic_pixel_icons/Black Mini Pistol.png" },
  { defaultName: "Blue Axe", filePath: "/futuristic_pixel_icons/Blue Axe.png" },
  { defaultName: "Blue Bacteria", filePath: "/futuristic_pixel_icons/Blue Bacteria.png" },
  { defaultName: "Blue Berries", filePath: "/futuristic_pixel_icons/Blue Berries.png" },
  { defaultName: "Blue Boots", filePath: "/futuristic_pixel_icons/Blue Boots.png" },
  { defaultName: "Blue Button", filePath: "/futuristic_pixel_icons/Blue Button.png" },
  { defaultName: "Blue Chip", filePath: "/futuristic_pixel_icons/Blue Chip.png" },
  { defaultName: "Blue Circuit", filePath: "/futuristic_pixel_icons/Blue Circuit.png" },
  { defaultName: "Blue Conveyor Belt", filePath: "/futuristic_pixel_icons/Blue Conveyor Belt.png" },
  { defaultName: "Blue Core", filePath: "/futuristic_pixel_icons/Blue Core.png" },
  { defaultName: "Blue Corner Potion", filePath: "/futuristic_pixel_icons/Blue Corner Potion.png" },
  { defaultName: "Blue Cosmic Blade", filePath: "/futuristic_pixel_icons/Blue Cosmic Blade.png" },
  { defaultName: "Blue Cosmic Ring", filePath: "/futuristic_pixel_icons/Blue Cosmic Ring.png" },
  { defaultName: "Blue Crate", filePath: "/futuristic_pixel_icons/Blue Crate.png" },
  { defaultName: "Blue Crystal", filePath: "/futuristic_pixel_icons/Blue Crystal.png" },
  { defaultName: "Blue Dark Helmet", filePath: "/futuristic_pixel_icons/Blue Dark Helmet.png" },
  { defaultName: "Blue Data Ring", filePath: "/futuristic_pixel_icons/Blue Data Ring.png" },
  { defaultName: "Blue Datachip", filePath: "/futuristic_pixel_icons/Blue Datachip.png" },
  { defaultName: "Blue Drill", filePath: "/futuristic_pixel_icons/Blue Drill.png" },
  { defaultName: "Blue Gas Canister", filePath: "/futuristic_pixel_icons/Blue Gas Canister.png" },
  { defaultName: "Blue Gatler", filePath: "/futuristic_pixel_icons/Blue Gatler.png" },
  { defaultName: "Blue Glowstick", filePath: "/futuristic_pixel_icons/Blue Glowstick.png" },
  { defaultName: "Blue Leggings", filePath: "/futuristic_pixel_icons/Blue Leggings.png" },
  { defaultName: "Blue Lining Gloves", filePath: "/futuristic_pixel_icons/Blue Lining Gloves.png" },
  { defaultName: "Blue Metal Helmet", filePath: "/futuristic_pixel_icons/Blue Metal Helmet.png" },
  { defaultName: "Blue Meter Tool", filePath: "/futuristic_pixel_icons/Blue Meter Tool.png" },
  { defaultName: "Blue Necklace", filePath: "/futuristic_pixel_icons/Blue Necklace.png" },
  { defaultName: "Blue Neon Boots", filePath: "/futuristic_pixel_icons/Blue Neon Boots.png" },
  { defaultName: "Blue Neon Bullet", filePath: "/futuristic_pixel_icons/Blue Neon Bullet.png" },
  { defaultName: "Blue Neon Claw", filePath: "/futuristic_pixel_icons/Blue Neon Claw.png" },
  { defaultName: "Blue Neon Gloves", filePath: "/futuristic_pixel_icons/Blue Neon Gloves.png" },
  { defaultName: "Blue Neon Helm", filePath: "/futuristic_pixel_icons/Blue Neon Helm.png" },
  { defaultName: "Blue Neon Jetpack", filePath: "/futuristic_pixel_icons/Blue Neon Jetpack.png" },
  { defaultName: "Blue Neon Leggings", filePath: "/futuristic_pixel_icons/Blue Neon Leggings.png" },
  { defaultName: "Blue Neon Shield", filePath: "/futuristic_pixel_icons/Blue Neon Shield.png" },
  { defaultName: "Blue Neon Shovel", filePath: "/futuristic_pixel_icons/Blue Neon Shovel.png" },
  { defaultName: "Blue Night Visor", filePath: "/futuristic_pixel_icons/Blue Night Visor.png" },
  { defaultName: "Blue Pickaxe", filePath: "/futuristic_pixel_icons/Blue Pickaxe.png" },
  { defaultName: "Blue Pocket Data", filePath: "/futuristic_pixel_icons/Blue Pocket Data.png" },
  { defaultName: "Blue Seeds", filePath: "/futuristic_pixel_icons/Blue Seeds.png" },
  { defaultName: "Blue Sickle", filePath: "/futuristic_pixel_icons/Blue Sickle.png" },
  { defaultName: "Blue Space Helmet", filePath: "/futuristic_pixel_icons/Blue Space Helmet.png" },
  { defaultName: "Blue Specs", filePath: "/futuristic_pixel_icons/Blue Specs.png" },
  { defaultName: "Blue Spike Blade", filePath: "/futuristic_pixel_icons/Blue Spike Blade.png" },
  { defaultName: "Blue Spiked Chest", filePath: "/futuristic_pixel_icons/Blue Spiked Chest.png" },
  { defaultName: "Blue Star Crystal", filePath: "/futuristic_pixel_icons/Blue Star Crystal.png" },
  { defaultName: "Blue Star Shards", filePath: "/futuristic_pixel_icons/Blue Star Shards.png" },
  { defaultName: "Blue Striped Jetpack", filePath: "/futuristic_pixel_icons/Blue Striped Jetpack.png" },
  { defaultName: "Blue Sword", filePath: "/futuristic_pixel_icons/Blue Sword.png" },
  { defaultName: "Blue Sword Ring", filePath: "/futuristic_pixel_icons/Blue Sword Ring.png" },
  { defaultName: "Blue Syringe", filePath: "/futuristic_pixel_icons/Blue Syringe.png" },
  { defaultName: "Blue Tank Boots", filePath: "/futuristic_pixel_icons/Blue Tank Boots.png" },
  { defaultName: "Blue Tank Helmet", filePath: "/futuristic_pixel_icons/Blue Tank Helmet.png" },
  { defaultName: "Blue Wire", filePath: "/futuristic_pixel_icons/Blue Wire.png" },
  { defaultName: "Blueprint", filePath: "/futuristic_pixel_icons/Blueprint.png" },
  { defaultName: "Bluerite Berries", filePath: "/futuristic_pixel_icons/Bluerite Berries.png" },
  { defaultName: "Bluerite Bow", filePath: "/futuristic_pixel_icons/Bluerite Bow.png" },
  { defaultName: "Bluerite Bullet", filePath: "/futuristic_pixel_icons/Bluerite Bullet.png" },
  { defaultName: "Bluerite Cell", filePath: "/futuristic_pixel_icons/Bluerite Cell.png" },
  { defaultName: "Bluerite Meteor", filePath: "/futuristic_pixel_icons/Bluerite Meteor.png" },
  { defaultName: "Bluerite Orb", filePath: "/futuristic_pixel_icons/Bluerite Orb.png" },
  { defaultName: "Bluerite Ring", filePath: "/futuristic_pixel_icons/Bluerite Ring.png" },
  { defaultName: "Bluerite Sickle", filePath: "/futuristic_pixel_icons/Bluerite Sickle.png" },
  { defaultName: "Bluerite Visor", filePath: "/futuristic_pixel_icons/Bluerite Visor.png" },
  { defaultName: "Bluescreen", filePath: "/futuristic_pixel_icons/Bluescreen.png" },
  { defaultName: "Bluesteel Helmet", filePath: "/futuristic_pixel_icons/Bluesteel Helmet.png" },
  { defaultName: "Bolt", filePath: "/futuristic_pixel_icons/Bolt.png" },
  { defaultName: "Bombberry", filePath: "/futuristic_pixel_icons/Bombberry.png" },
  { defaultName: "Broken Data Panel", filePath: "/futuristic_pixel_icons/Broken Data Panel.png" },
  { defaultName: "Broken Meter", filePath: "/futuristic_pixel_icons/Broken Meter.png" },
  { defaultName: "Broken Pocket Data", filePath: "/futuristic_pixel_icons/Broken Pocket Data.png" },
  { defaultName: "Broken Screen", filePath: "/futuristic_pixel_icons/Broken Screen.png" },
  { defaultName: "Broken Shield", filePath: "/futuristic_pixel_icons/Broken Shield.png" },
  { defaultName: "Camera", filePath: "/futuristic_pixel_icons/Camera.png" },
  { defaultName: "Candy Pack", filePath: "/futuristic_pixel_icons/Candy Pack.png" },
  { defaultName: "Claw", filePath: "/futuristic_pixel_icons/Claw.png" },
  { defaultName: "Coffee Bean Pack", filePath: "/futuristic_pixel_icons/Coffee Bean Pack.png" },
  { defaultName: "Colorful Boots", filePath: "/futuristic_pixel_icons/Colorful Boots.png" },
  { defaultName: "Colorful Leggings", filePath: "/futuristic_pixel_icons/Colorful Leggings.png" },
  { defaultName: "Controller", filePath: "/futuristic_pixel_icons/Controller.png" },
  { defaultName: "Cross Data Shield", filePath: "/futuristic_pixel_icons/Cross Data Shield.png" },
  { defaultName: "Crystal", filePath: "/futuristic_pixel_icons/Crystal.png" },
  { defaultName: "Cyber Key", filePath: "/futuristic_pixel_icons/Cyber Key.png" },
  { defaultName: "Cyborg Skull", filePath: "/futuristic_pixel_icons/Cyborg Skull.png" },
  { defaultName: "Cyclops Skull", filePath: "/futuristic_pixel_icons/Cyclops Skull.png" },
  { defaultName: "Dark Bluerite Alien Helmet", filePath: "/futuristic_pixel_icons/Dark Bluerite Alien Helmet.png" },
  { defaultName: "Dark Camera", filePath: "/futuristic_pixel_icons/Dark Camera.png" },
  { defaultName: "Dark Claw", filePath: "/futuristic_pixel_icons/Dark Claw.png" },
  { defaultName: "Dark Droid", filePath: "/futuristic_pixel_icons/Dark Droid.png" },
  { defaultName: "Dark Drone", filePath: "/futuristic_pixel_icons/Dark Drone.png" },
  { defaultName: "Dark Helm", filePath: "/futuristic_pixel_icons/Dark Helm.png" },
  { defaultName: "Dark Orange Alien Helmet", filePath: "/futuristic_pixel_icons/Dark Orange Alien Helmet.png" },
  { defaultName: "Dark Pink Revolver", filePath: "/futuristic_pixel_icons/Dark Pink Revolver.png" },
  { defaultName: "Dark Revolver", filePath: "/futuristic_pixel_icons/Dark Revolver.png" },
  { defaultName: "Dark Space Ring", filePath: "/futuristic_pixel_icons/Dark Space Ring.png" },
  { defaultName: "Dark Tentacle", filePath: "/futuristic_pixel_icons/Dark Tentacle.png" },
  { defaultName: "Darkblue Chest", filePath: "/futuristic_pixel_icons/Darkblue Chest.png" },
  { defaultName: "Darkblue Cosmic Ring", filePath: "/futuristic_pixel_icons/Darkblue Cosmic Ring.png" },
  { defaultName: "Darkblue Revolver", filePath: "/futuristic_pixel_icons/Darkblue Revolver.png" },
  { defaultName: "Darkblue Space Helmet", filePath: "/futuristic_pixel_icons/Darkblue Space Helmet.png" },
  { defaultName: "Darkblue Speed Rifle", filePath: "/futuristic_pixel_icons/Darkblue Speed Rifle.png" },
  { defaultName: "Darkgreen Chest", filePath: "/futuristic_pixel_icons/Darkgreen Chest.png" },
  { defaultName: "Darkgreen Cosmic Ring", filePath: "/futuristic_pixel_icons/Darkgreen Cosmic Ring.png" },
  { defaultName: "Darkgreen Revolver", filePath: "/futuristic_pixel_icons/Darkgreen Revolver.png" },
  { defaultName: "Darkgreen Speed Rifle", filePath: "/futuristic_pixel_icons/Darkgreen Speed Rifle.png" },
  { defaultName: "Darkmetal Jetpack", filePath: "/futuristic_pixel_icons/Darkmetal Jetpack.png" },
  { defaultName: "Darkpink Space Helmet", filePath: "/futuristic_pixel_icons/Darkpink Space Helmet.png" },
  { defaultName: "Darkpurple Alien Helm", filePath: "/futuristic_pixel_icons/Darkpurple Alien Helm.png" },
  { defaultName: "Darkpurple Cosmic Ring", filePath: "/futuristic_pixel_icons/Darkpurple Cosmic Ring.png" },
  { defaultName: "Darkred Chest", filePath: "/futuristic_pixel_icons/Darkred Chest.png" },
  { defaultName: "Darkred Cosmic Ring", filePath: "/futuristic_pixel_icons/Darkred Cosmic Ring.png" },
  { defaultName: "Data Panel", filePath: "/futuristic_pixel_icons/Data Panel.png" },
  { defaultName: "Data Panel Off", filePath: "/futuristic_pixel_icons/Data Panel Off.png" },
  { defaultName: "Data Screen", filePath: "/futuristic_pixel_icons/Data Screen.png" },
  { defaultName: "Data Shield", filePath: "/futuristic_pixel_icons/Data Shield.png" },
  { defaultName: "Data Watch", filePath: "/futuristic_pixel_icons/Data Watch.png" },
  { defaultName: "Datascreen", filePath: "/futuristic_pixel_icons/Datascreen.png" },
  { defaultName: "Decayed Brain", filePath: "/futuristic_pixel_icons/Decayed Brain.png" },
  { defaultName: "Down Arrow", filePath: "/futuristic_pixel_icons/Down Arrow.png" },
  { defaultName: "Droid", filePath: "/futuristic_pixel_icons/Droid.png" },
  { defaultName: "Drone", filePath: "/futuristic_pixel_icons/Drone.png" },
  { defaultName: "Embryo", filePath: "/futuristic_pixel_icons/Embryo.png" },
  { defaultName: "Emerald Ring", filePath: "/futuristic_pixel_icons/Emerald Ring.png" },
  { defaultName: "Empty Cell", filePath: "/futuristic_pixel_icons/Empty Cell.png" },
  { defaultName: "Empty Corner Potion", filePath: "/futuristic_pixel_icons/Empty Corner Potion.png" },
  { defaultName: "Empty Data Shield", filePath: "/futuristic_pixel_icons/Empty Data Shield.png" },
  { defaultName: "Empty Meteorite", filePath: "/futuristic_pixel_icons/Empty Meteorite.png" },
  { defaultName: "Empty Potion", filePath: "/futuristic_pixel_icons/Empty Potion.png" },
  { defaultName: "Empty Vial", filePath: "/futuristic_pixel_icons/Empty Vial.png" },
  { defaultName: "Error Icon", filePath: "/futuristic_pixel_icons/Error Icon.png" },
  { defaultName: "Flashlight Off", filePath: "/futuristic_pixel_icons/Flashlight Off.png" },
  { defaultName: "Flashlight On", filePath: "/futuristic_pixel_icons/Flashlight On.png" },
  { defaultName: "Flesh Skull", filePath: "/futuristic_pixel_icons/Flesh Skull.png" },
  { defaultName: "Fruit Pack", filePath: "/futuristic_pixel_icons/Fruit Pack.png" },
  { defaultName: "Gas Can", filePath: "/futuristic_pixel_icons/Gas Can.png" },
  { defaultName: "Gasmask Blue", filePath: "/futuristic_pixel_icons/Gasmask Blue.png" },
  { defaultName: "Gasmask Pink", filePath: "/futuristic_pixel_icons/Gasmask Pink.png" },
  { defaultName: "Gasoline Spray", filePath: "/futuristic_pixel_icons/Gasoline Spray.png" },
  { defaultName: "Giant Berry", filePath: "/futuristic_pixel_icons/Giant Berry.png" },
  { defaultName: "Goldenite Bar", filePath: "/futuristic_pixel_icons/Goldenite Bar.png" },
  { defaultName: "Green Ammo", filePath: "/futuristic_pixel_icons/Green Ammo.png" },
  { defaultName: "Green Bacteria", filePath: "/futuristic_pixel_icons/Green Bacteria.png" },
  { defaultName: "Green Button", filePath: "/futuristic_pixel_icons/Green Button.png" },
  { defaultName: "Green Cell", filePath: "/futuristic_pixel_icons/Green Cell.png" },
  { defaultName: "Green Circuit", filePath: "/futuristic_pixel_icons/Green Circuit.png" },
  { defaultName: "Green Conveyor Belt", filePath: "/futuristic_pixel_icons/Green Conveyor Belt.png" },
  { defaultName: "Green Core", filePath: "/futuristic_pixel_icons/Green Core.png" },
  { defaultName: "Green Corner Potion", filePath: "/futuristic_pixel_icons/Green Corner Potion.png" },
  { defaultName: "Green Cosmic Ring", filePath: "/futuristic_pixel_icons/Green Cosmic Ring.png" },
  { defaultName: "Green Crate", filePath: "/futuristic_pixel_icons/Green Crate.png" },
  { defaultName: "Green Dark Helmet", filePath: "/futuristic_pixel_icons/Green Dark Helmet.png" },
  { defaultName: "Green Data Panel", filePath: "/futuristic_pixel_icons/Green Data Panel.png" },
  { defaultName: "Green Data Ring", filePath: "/futuristic_pixel_icons/Green Data Ring.png" },
  { defaultName: "Green Gatler", filePath: "/futuristic_pixel_icons/Green Gatler.png" },
  { defaultName: "Green Glowstick", filePath: "/futuristic_pixel_icons/Green Glowstick.png" },
  { defaultName: "Green Grenade", filePath: "/futuristic_pixel_icons/Green Grenade.png" },
  { defaultName: "Green Meter Tool", filePath: "/futuristic_pixel_icons/Green Meter Tool.png" },
  { defaultName: "Green Necklace", filePath: "/futuristic_pixel_icons/Green Necklace.png" },
  { defaultName: "Green Neon Chest", filePath: "/futuristic_pixel_icons/Green Neon Chest.png" },
  { defaultName: "Green Neon Gloves", filePath: "/futuristic_pixel_icons/Green Neon Gloves.png" },
  { defaultName: "Green Neon Jetpack", filePath: "/futuristic_pixel_icons/Green Neon Jetpack.png" },
  { defaultName: "Green Night Visor", filePath: "/futuristic_pixel_icons/Green Night Visor.png" },
  { defaultName: "Green Pickaxe", filePath: "/futuristic_pixel_icons/Green Pickaxe.png" },
  { defaultName: "Green Pocket Data", filePath: "/futuristic_pixel_icons/Green Pocket Data.png" },
  { defaultName: "Green Seeds", filePath: "/futuristic_pixel_icons/Green Seeds.png" },
  { defaultName: "Green Space Helmet", filePath: "/futuristic_pixel_icons/Green Space Helmet.png" },
  { defaultName: "Green Star Shards", filePath: "/futuristic_pixel_icons/Green Star Shards.png" },
  { defaultName: "Green Starcrystal", filePath: "/futuristic_pixel_icons/Green Starcrystal.png" },
  { defaultName: "Green Sword", filePath: "/futuristic_pixel_icons/Green Sword.png" },
  { defaultName: "Green Sword Ring", filePath: "/futuristic_pixel_icons/Green Sword Ring.png" },
  { defaultName: "Green Syringe", filePath: "/futuristic_pixel_icons/Green Syringe.png" },
  { defaultName: "Green Up Arrow", filePath: "/futuristic_pixel_icons/Green Up Arrow.png" },
  { defaultName: "Green Wire", filePath: "/futuristic_pixel_icons/Green Wire.png" },
  { defaultName: "Hand Claw", filePath: "/futuristic_pixel_icons/Hand Claw.png" },
  { defaultName: "Health Kit", filePath: "/futuristic_pixel_icons/Health Kit.png" },
  { defaultName: "Health Pack", filePath: "/futuristic_pixel_icons/Health Pack.png" },
  { defaultName: "Healthbullet", filePath: "/futuristic_pixel_icons/Healthbullet.png" },
  { defaultName: "Healthpill", filePath: "/futuristic_pixel_icons/Healthpill.png" },
  { defaultName: "Heavy Gasmask", filePath: "/futuristic_pixel_icons/Heavy Gasmask.png" },
  { defaultName: "Heavy Orange Gatler", filePath: "/futuristic_pixel_icons/Heavy Orange Gatler.png" },
  { defaultName: "Heavy Poison Gatler", filePath: "/futuristic_pixel_icons/Heavy Poison Gatler.png" },
  { defaultName: "Heavy Purple Gatler", filePath: "/futuristic_pixel_icons/Heavy Purple Gatler.png" },
  { defaultName: "Hover Boots", filePath: "/futuristic_pixel_icons/Hover Boots.png" },
  { defaultName: "Ice Pack", filePath: "/futuristic_pixel_icons/Ice Pack.png" },
  { defaultName: "Irrite Axe", filePath: "/futuristic_pixel_icons/Irrite Axe.png" },
  { defaultName: "Irrite Bar", filePath: "/futuristic_pixel_icons/Irrite Bar.png" },
  { defaultName: "Irrite Bow", filePath: "/futuristic_pixel_icons/Irrite Bow.png" },
  { defaultName: "Irrite Bullet", filePath: "/futuristic_pixel_icons/Irrite Bullet.png" },
  { defaultName: "Irrite Cell", filePath: "/futuristic_pixel_icons/Irrite Cell.png" },
  { defaultName: "Irrite Chest", filePath: "/futuristic_pixel_icons/Irrite Chest.png" },
  { defaultName: "Irrite Crystal", filePath: "/futuristic_pixel_icons/Irrite Crystal.png" },
  { defaultName: "Irrite Gloves", filePath: "/futuristic_pixel_icons/Irrite Gloves.png" },
  { defaultName: "Irrite Helmet", filePath: "/futuristic_pixel_icons/Irrite Helmet.png" },
  { defaultName: "Irrite Leggings", filePath: "/futuristic_pixel_icons/Irrite Leggings.png" },
  { defaultName: "Irrite Meteorite", filePath: "/futuristic_pixel_icons/Irrite Meteorite.png" },
  { defaultName: "Irrite Ore", filePath: "/futuristic_pixel_icons/Irrite Ore.png" },
  { defaultName: "Irrite Ring", filePath: "/futuristic_pixel_icons/Irrite Ring.png" },
  { defaultName: "Irrite Sickle", filePath: "/futuristic_pixel_icons/Irrite Sickle.png" },
  { defaultName: "Large Blue Potion", filePath: "/futuristic_pixel_icons/Large Blue Potion.png" },
  { defaultName: "Large Green Potion", filePath: "/futuristic_pixel_icons/Large Green Potion.png" },
  { defaultName: "Large Pink Potion", filePath: "/futuristic_pixel_icons/Large Pink Potion.png" },
  { defaultName: "Large Red Potion", filePath: "/futuristic_pixel_icons/Large Red Potion.png" },
  { defaultName: "Large Ruby Potion", filePath: "/futuristic_pixel_icons/Large Ruby Potion.png" },
  { defaultName: "Laser Pistol", filePath: "/futuristic_pixel_icons/Laser Pistol.png" },
  { defaultName: "Laser Rifle Blue", filePath: "/futuristic_pixel_icons/Laser Rifle Blue.png" },
  { defaultName: "Laser Rifle Pink", filePath: "/futuristic_pixel_icons/Laser Rifle Pink.png" },
  { defaultName: "Lasergrab Tool", filePath: "/futuristic_pixel_icons/Lasergrab Tool.png" },
  { defaultName: "Laserpointer", filePath: "/futuristic_pixel_icons/Laserpointer.png" },
  { defaultName: "Lifeform Scanner1", filePath: "/futuristic_pixel_icons/Lifeform Scanner1.png" },
  { defaultName: "Lifeformscanner2", filePath: "/futuristic_pixel_icons/Lifeformscanner2.png" },
  { defaultName: "Light Crystal", filePath: "/futuristic_pixel_icons/Light Crystal.png" },
  { defaultName: "Light Ring", filePath: "/futuristic_pixel_icons/Light Ring.png" },
  { defaultName: "Light Star Shards", filePath: "/futuristic_pixel_icons/Light Star Shards.png" },
  { defaultName: "Lightning Icon", filePath: "/futuristic_pixel_icons/Lightning Icon.png" },
  { defaultName: "Liquid Irrite Spray", filePath: "/futuristic_pixel_icons/Liquid Irrite Spray.png" },
  { defaultName: "Luminite Bar", filePath: "/futuristic_pixel_icons/Luminite Bar.png" },
  { defaultName: "Luminite Meteor", filePath: "/futuristic_pixel_icons/Luminite Meteor.png" },
  { defaultName: "Luminite Ore", filePath: "/futuristic_pixel_icons/Luminite Ore.png" },
  { defaultName: "Machine Claw", filePath: "/futuristic_pixel_icons/Machine Claw.png" },
  { defaultName: "Magmarite Bar", filePath: "/futuristic_pixel_icons/Magmarite Bar.png" },
  { defaultName: "Magmarite Cell", filePath: "/futuristic_pixel_icons/Magmarite Cell.png" },
  { defaultName: "Med Armor", filePath: "/futuristic_pixel_icons/Med Armor.png" },
  { defaultName: "Med Helmet", filePath: "/futuristic_pixel_icons/Med Helmet.png" },
  { defaultName: "Med Shield", filePath: "/futuristic_pixel_icons/Med Shield.png" },
  { defaultName: "Medkit", filePath: "/futuristic_pixel_icons/Medkit.png" },
  { defaultName: "Metal Bar", filePath: "/futuristic_pixel_icons/Metal Bar.png" },
  { defaultName: "Metal Crate", filePath: "/futuristic_pixel_icons/Metal Crate.png" },
  { defaultName: "Metal Gloves", filePath: "/futuristic_pixel_icons/Metal Gloves.png" },
  { defaultName: "Metal Helmet", filePath: "/futuristic_pixel_icons/Metal Helmet.png" },
  { defaultName: "Metal Plating", filePath: "/futuristic_pixel_icons/Metal Plating.png" },
  { defaultName: "Metal Round Helmet", filePath: "/futuristic_pixel_icons/Metal Round Helmet.png" },
  { defaultName: "Metal Shield", filePath: "/futuristic_pixel_icons/Metal Shield.png" },
  { defaultName: "Metaljunk Helmet", filePath: "/futuristic_pixel_icons/Metaljunk Helmet.png" },
  { defaultName: "Meteorite Chunks", filePath: "/futuristic_pixel_icons/Meteorite Chunks.png" },
  { defaultName: "Meter", filePath: "/futuristic_pixel_icons/Meter.png" },
  { defaultName: "Monster Eye", filePath: "/futuristic_pixel_icons/Monster Eye.png" },
  { defaultName: "Monster Guts", filePath: "/futuristic_pixel_icons/Monster Guts.png" },
  { defaultName: "Monster Tongue", filePath: "/futuristic_pixel_icons/Monster Tongue.png" },
  { defaultName: "Neon Chest Blue", filePath: "/futuristic_pixel_icons/Neon Chest Blue.png" },
  { defaultName: "Neon Claw", filePath: "/futuristic_pixel_icons/Neon Claw.png" },
  { defaultName: "Nitro Can", filePath: "/futuristic_pixel_icons/Nitro Can.png" },
  { defaultName: "Nut", filePath: "/futuristic_pixel_icons/Nut.png" },
  { defaultName: "Old Gas Canister", filePath: "/futuristic_pixel_icons/Old Gas Canister.png" },
  { defaultName: "Old Tech", filePath: "/futuristic_pixel_icons/Old Tech.png" },
  { defaultName: "Onyx Bar", filePath: "/futuristic_pixel_icons/Onyx Bar.png" },
  { defaultName: "Onyx Big Blade", filePath: "/futuristic_pixel_icons/Onyx Big Blade.png" },
  { defaultName: "Onyx Blade", filePath: "/futuristic_pixel_icons/Onyx Blade.png" },
  { defaultName: "Onyx Bullet", filePath: "/futuristic_pixel_icons/Onyx Bullet.png" },
  { defaultName: "Onyx Corner Potion", filePath: "/futuristic_pixel_icons/Onyx Corner Potion.png" },
  { defaultName: "Onyx Crystal", filePath: "/futuristic_pixel_icons/Onyx Crystal.png" },
  { defaultName: "Onyx Cube", filePath: "/futuristic_pixel_icons/Onyx Cube.png" },
  { defaultName: "Onyx Meteorite Shards", filePath: "/futuristic_pixel_icons/Onyx Meteorite Shards.png" },
  { defaultName: "Onyx Ore", filePath: "/futuristic_pixel_icons/Onyx Ore.png" },
  { defaultName: "Onyx Ring", filePath: "/futuristic_pixel_icons/Onyx Ring.png" },
  { defaultName: "Onyx Star Shards", filePath: "/futuristic_pixel_icons/Onyx Star Shards.png" },
  { defaultName: "Onyx Starcrystal", filePath: "/futuristic_pixel_icons/Onyx Starcrystal.png" },
  { defaultName: "Onyx Sword", filePath: "/futuristic_pixel_icons/Onyx Sword.png" },
  { defaultName: "Onyx Visor Helmet", filePath: "/futuristic_pixel_icons/Onyx Visor Helmet.png" },
  { defaultName: "Orange Bacteria", filePath: "/futuristic_pixel_icons/Orange Bacteria.png" },
  { defaultName: "Orange Berries", filePath: "/futuristic_pixel_icons/Orange Berries.png" },
  { defaultName: "Orange Cell", filePath: "/futuristic_pixel_icons/Orange Cell.png" },
  { defaultName: "Orange Chip", filePath: "/futuristic_pixel_icons/Orange Chip.png" },
  { defaultName: "Orange Core", filePath: "/futuristic_pixel_icons/Orange Core.png" },
  { defaultName: "Orange Corner Potion", filePath: "/futuristic_pixel_icons/Orange Corner Potion.png" },
  { defaultName: "Orange Crystal", filePath: "/futuristic_pixel_icons/Orange Crystal.png" },
  { defaultName: "Orange Data Ring", filePath: "/futuristic_pixel_icons/Orange Data Ring.png" },
  { defaultName: "Orange Datachip", filePath: "/futuristic_pixel_icons/Orange Datachip.png" },
  { defaultName: "Orange Drill", filePath: "/futuristic_pixel_icons/Orange Drill.png" },
  { defaultName: "Orange Gatler", filePath: "/futuristic_pixel_icons/Orange Gatler.png" },
  { defaultName: "Orange Gloves", filePath: "/futuristic_pixel_icons/Orange Gloves.png" },
  { defaultName: "Orange Lined Jetpack", filePath: "/futuristic_pixel_icons/Orange Lined Jetpack.png" },
  { defaultName: "Orange Meter Tool", filePath: "/futuristic_pixel_icons/Orange Meter Tool.png" },
  { defaultName: "Orange Necklace", filePath: "/futuristic_pixel_icons/Orange Necklace.png" },
  { defaultName: "Orange Neon Boots", filePath: "/futuristic_pixel_icons/Orange Neon Boots.png" },
  { defaultName: "Orange Power Orb", filePath: "/futuristic_pixel_icons/Orange Power Orb.png" },
  { defaultName: "Orange Shovel", filePath: "/futuristic_pixel_icons/Orange Shovel.png" },
  { defaultName: "Orange Space Helmet", filePath: "/futuristic_pixel_icons/Orange Space Helmet.png" },
  { defaultName: "Orange Specs", filePath: "/futuristic_pixel_icons/Orange Specs.png" },
  { defaultName: "Orange Spike Blade", filePath: "/futuristic_pixel_icons/Orange Spike Blade.png" },
  { defaultName: "Orange Star Shards", filePath: "/futuristic_pixel_icons/Orange Star Shards.png" },
  { defaultName: "Orange Sword", filePath: "/futuristic_pixel_icons/Orange Sword.png" },
  { defaultName: "Orange Visor Helmet", filePath: "/futuristic_pixel_icons/Orange Visor Helmet.png" },
  { defaultName: "Ore Junk", filePath: "/futuristic_pixel_icons/Ore Junk.png" },
  { defaultName: "Pills1", filePath: "/futuristic_pixel_icons/Pills1.png" },
  { defaultName: "Pills2", filePath: "/futuristic_pixel_icons/Pills2.png" },
  { defaultName: "Pills3", filePath: "/futuristic_pixel_icons/Pills3.png" },
  { defaultName: "Pink Bacteria", filePath: "/futuristic_pixel_icons/Pink Bacteria.png" },
  { defaultName: "Pink Cell", filePath: "/futuristic_pixel_icons/Pink Cell.png" },
  { defaultName: "Pink Clawhand", filePath: "/futuristic_pixel_icons/Pink Clawhand.png" },
  { defaultName: "Pink Core", filePath: "/futuristic_pixel_icons/Pink Core.png" },
  { defaultName: "Pink Crystal", filePath: "/futuristic_pixel_icons/Pink Crystal.png" },
  { defaultName: "Pink Gatler", filePath: "/futuristic_pixel_icons/Pink Gatler.png" },
  { defaultName: "Pink Gloves", filePath: "/futuristic_pixel_icons/Pink Gloves.png" },
  { defaultName: "Pink Glowstick", filePath: "/futuristic_pixel_icons/Pink Glowstick.png" },
  { defaultName: "Pink Heart Crystal", filePath: "/futuristic_pixel_icons/Pink Heart Crystal.png" },
  { defaultName: "Pink Meter Tool", filePath: "/futuristic_pixel_icons/Pink Meter Tool.png" },
  { defaultName: "Pink Neon Bullet", filePath: "/futuristic_pixel_icons/Pink Neon Bullet.png" },
  { defaultName: "Pink Neon Claw", filePath: "/futuristic_pixel_icons/Pink Neon Claw.png" },
  { defaultName: "Pink Neon Jetpack", filePath: "/futuristic_pixel_icons/Pink Neon Jetpack.png" },
  { defaultName: "Pink Neon Shield", filePath: "/futuristic_pixel_icons/Pink Neon Shield.png" },
  { defaultName: "Pink Night Visor", filePath: "/futuristic_pixel_icons/Pink Night Visor.png" },
  { defaultName: "Pink Pickaxe", filePath: "/futuristic_pixel_icons/Pink Pickaxe.png" },
  { defaultName: "Pink Space Berry", filePath: "/futuristic_pixel_icons/Pink Space Berry.png" },
  { defaultName: "Pink Space Helmet", filePath: "/futuristic_pixel_icons/Pink Space Helmet.png" },
  { defaultName: "Pink Specs", filePath: "/futuristic_pixel_icons/Pink Specs.png" },
  { defaultName: "Pink Star Shards", filePath: "/futuristic_pixel_icons/Pink Star Shards.png" },
  { defaultName: "Pink Starcrystal", filePath: "/futuristic_pixel_icons/Pink Starcrystal.png" },
  { defaultName: "Pink Syringe", filePath: "/futuristic_pixel_icons/Pink Syringe.png" },
  { defaultName: "Pink Tank Helmet", filePath: "/futuristic_pixel_icons/Pink Tank Helmet.png" },
  { defaultName: "Pink Visor Helmet", filePath: "/futuristic_pixel_icons/Pink Visor Helmet.png" },
  { defaultName: "Pixel", filePath: "/futuristic_pixel_icons/Pixel.png" },
  { defaultName: "Pocket Data", filePath: "/futuristic_pixel_icons/Pocket Data.png" },
  { defaultName: "Poison Gatler", filePath: "/futuristic_pixel_icons/Poison Gatler.png" },
  { defaultName: "Poison Spray", filePath: "/futuristic_pixel_icons/Poison Spray.png" },
  { defaultName: "Powercell", filePath: "/futuristic_pixel_icons/Powercell.png" },
  { defaultName: "Protector Shield", filePath: "/futuristic_pixel_icons/Protector Shield.png" },
  { defaultName: "Purple Ammo", filePath: "/futuristic_pixel_icons/Purple Ammo.png" },
  { defaultName: "Purple Boots", filePath: "/futuristic_pixel_icons/Purple Boots.png" },
  { defaultName: "Purple Brain", filePath: "/futuristic_pixel_icons/Purple Brain.png" },
  { defaultName: "Purple Cosmic Blade", filePath: "/futuristic_pixel_icons/Purple Cosmic Blade.png" },
  { defaultName: "Purple Cosmic Ring", filePath: "/futuristic_pixel_icons/Purple Cosmic Ring.png" },
  { defaultName: "Purple Gatler", filePath: "/futuristic_pixel_icons/Purple Gatler.png" },
  { defaultName: "Purple Grenade", filePath: "/futuristic_pixel_icons/Purple Grenade.png" },
  { defaultName: "Purple Jetpack", filePath: "/futuristic_pixel_icons/Purple Jetpack.png" },
  { defaultName: "Purple Necklace", filePath: "/futuristic_pixel_icons/Purple Necklace.png" },
  { defaultName: "Purple Spiked Chest", filePath: "/futuristic_pixel_icons/Purple Spiked Chest.png" },
  { defaultName: "Purple Starcrystal", filePath: "/futuristic_pixel_icons/Purple Starcrystal.png" },
  { defaultName: "Purple Sword Ring", filePath: "/futuristic_pixel_icons/Purple Sword Ring.png" },
  { defaultName: "Purple Tentacle", filePath: "/futuristic_pixel_icons/Purple Tentacle.png" },
  { defaultName: "Raw Uranium", filePath: "/futuristic_pixel_icons/Raw Uranium.png" },
  { defaultName: "Red Axe", filePath: "/futuristic_pixel_icons/Red Axe.png" },
  { defaultName: "Red Bacteria", filePath: "/futuristic_pixel_icons/Red Bacteria.png" },
  { defaultName: "Red Berries", filePath: "/futuristic_pixel_icons/Red Berries.png" },
  { defaultName: "Red Boots", filePath: "/futuristic_pixel_icons/Red Boots.png" },
  { defaultName: "Red Box", filePath: "/futuristic_pixel_icons/Red Box.png" },
  { defaultName: "Red Button", filePath: "/futuristic_pixel_icons/Red Button.png" },
  { defaultName: "Red Chest", filePath: "/futuristic_pixel_icons/Red Chest.png" },
  { defaultName: "Red Circuit", filePath: "/futuristic_pixel_icons/Red Circuit.png" },
  { defaultName: "Red Conveyor Belt", filePath: "/futuristic_pixel_icons/Red Conveyor Belt.png" },
  { defaultName: "Red Corner potion", filePath: "/futuristic_pixel_icons/Red Corner potion.png" },
  { defaultName: "Red Cosmic Ring", filePath: "/futuristic_pixel_icons/Red Cosmic Ring.png" },
  { defaultName: "Red Crate", filePath: "/futuristic_pixel_icons/Red Crate.png" },
  { defaultName: "Red Cyber Helmet", filePath: "/futuristic_pixel_icons/Red Cyber Helmet.png" },
  { defaultName: "Red Dark Helmet", filePath: "/futuristic_pixel_icons/Red Dark Helmet.png" },
  { defaultName: "Red Data Ring", filePath: "/futuristic_pixel_icons/Red Data Ring.png" },
  { defaultName: "Red Gas Canister", filePath: "/futuristic_pixel_icons/Red Gas Canister.png" },
  { defaultName: "Red Gatler", filePath: "/futuristic_pixel_icons/Red Gatler.png" },
  { defaultName: "Red Heart Crystal", filePath: "/futuristic_pixel_icons/Red Heart Crystal.png" },
  { defaultName: "Red Skull", filePath: "/futuristic_pixel_icons/Red Skull.png" },
  { defaultName: "Red Spiked Chest", filePath: "/futuristic_pixel_icons/Red Spiked Chest.png" },
  { defaultName: "Red Sword Ring", filePath: "/futuristic_pixel_icons/Red Sword Ring.png" },
  { defaultName: "Red Syringe", filePath: "/futuristic_pixel_icons/Red Syringe.png" },
  { defaultName: "Red Tank Helmet", filePath: "/futuristic_pixel_icons/Red Tank Helmet.png" },
  { defaultName: "Red Visor", filePath: "/futuristic_pixel_icons/Red Visor.png" },
  { defaultName: "Red Warning icon", filePath: "/futuristic_pixel_icons/Red Warning icon.png" },
  { defaultName: "Red Wire", filePath: "/futuristic_pixel_icons/Red Wire.png" },
  { defaultName: "Regen Bullet", filePath: "/futuristic_pixel_icons/Regen Bullet.png" },
  { defaultName: "Regen Pill", filePath: "/futuristic_pixel_icons/Regen Pill.png" },
  { defaultName: "Ruby Bar", filePath: "/futuristic_pixel_icons/Ruby Bar.png" },
  { defaultName: "Ruby Big Blade", filePath: "/futuristic_pixel_icons/Ruby Big Blade.png" },
  { defaultName: "Ruby Bullet", filePath: "/futuristic_pixel_icons/Ruby Bullet.png" },
  { defaultName: "Ruby Ring", filePath: "/futuristic_pixel_icons/Ruby Ring.png" },
  { defaultName: "Ruby Spike Blade", filePath: "/futuristic_pixel_icons/Ruby Spike Blade.png" },
  { defaultName: "Rubyrite Meteorite", filePath: "/futuristic_pixel_icons/Rubyrite Meteorite.png" },
  { defaultName: "Rubyrite Ore", filePath: "/futuristic_pixel_icons/Rubyrite Ore.png" },
  { defaultName: "Rusted Companion", filePath: "/futuristic_pixel_icons/Rusted Companion.png" },
  { defaultName: "Rusty Bolt", filePath: "/futuristic_pixel_icons/Rusty Bolt.png" },
  { defaultName: "Rusty Nut", filePath: "/futuristic_pixel_icons/Rusty Nut.png" },
  { defaultName: "Rusty Plating", filePath: "/futuristic_pixel_icons/Rusty Plating.png" },
  { defaultName: "Rusty Screw", filePath: "/futuristic_pixel_icons/Rusty Screw.png" },
  { defaultName: "Rusty Toolbox", filePath: "/futuristic_pixel_icons/Rusty Toolbox.png" },
  { defaultName: "Rusty Wrench", filePath: "/futuristic_pixel_icons/Rusty Wrench.png" },
  { defaultName: "ScifiItems_84", filePath: "/futuristic_pixel_icons/ScifiItems_84.png" },
  { defaultName: "ScifiItems_85", filePath: "/futuristic_pixel_icons/ScifiItems_85.png" },
  { defaultName: "ScifiItems_86", filePath: "/futuristic_pixel_icons/ScifiItems_86.png" },
  { defaultName: "ScifiItems_87", filePath: "/futuristic_pixel_icons/ScifiItems_87.png" },
  { defaultName: "ScifiItems_88", filePath: "/futuristic_pixel_icons/ScifiItems_88.png" },
  { defaultName: "ScifiItems_89", filePath: "/futuristic_pixel_icons/ScifiItems_89.png" },
  { defaultName: "ScifiItems_90", filePath: "/futuristic_pixel_icons/ScifiItems_90.png" },
  { defaultName: "ScifiItems_91", filePath: "/futuristic_pixel_icons/ScifiItems_91.png" },
  { defaultName: "ScifiItems_92", filePath: "/futuristic_pixel_icons/ScifiItems_92.png" },
  { defaultName: "ScifiItems_93", filePath: "/futuristic_pixel_icons/ScifiItems_93.png" },
  { defaultName: "ScifiItems_94", filePath: "/futuristic_pixel_icons/ScifiItems_94.png" },
  { defaultName: "Screen", filePath: "/futuristic_pixel_icons/Screen.png" },
  { defaultName: "Screw", filePath: "/futuristic_pixel_icons/Screw.png" },
  { defaultName: "Seed Pack", filePath: "/futuristic_pixel_icons/Seed Pack.png" },
  { defaultName: "Shield Armor", filePath: "/futuristic_pixel_icons/Shield Armor.png" },
  { defaultName: "Shield Bullet", filePath: "/futuristic_pixel_icons/Shield Bullet.png" },
  { defaultName: "Shield Helmet", filePath: "/futuristic_pixel_icons/Shield Helmet.png" },
  { defaultName: "Shield Pill", filePath: "/futuristic_pixel_icons/Shield Pill.png" },
  { defaultName: "Shieldkit", filePath: "/futuristic_pixel_icons/Shieldkit.png" },
  { defaultName: "Shovel", filePath: "/futuristic_pixel_icons/Shovel.png" },
  { defaultName: "Simple Boots", filePath: "/futuristic_pixel_icons/Simple Boots.png" },
  { defaultName: "Simple Chest Blue", filePath: "/futuristic_pixel_icons/Simple Chest Blue.png" },
  { defaultName: "Simple Chest Orange", filePath: "/futuristic_pixel_icons/Simple Chest Orange.png" },
  { defaultName: "Simple Hand Drill", filePath: "/futuristic_pixel_icons/Simple Hand Drill.png" },
  { defaultName: "Simple Leggings", filePath: "/futuristic_pixel_icons/Simple Leggings.png" },
  { defaultName: "Simple Pistol1", filePath: "/futuristic_pixel_icons/Simple Pistol1.png" },
  { defaultName: "Simple Pistol2", filePath: "/futuristic_pixel_icons/Simple Pistol2.png" },
  { defaultName: "Simple Rifle1", filePath: "/futuristic_pixel_icons/Simple Rifle1.png" },
  { defaultName: "Simple Rifle2", filePath: "/futuristic_pixel_icons/Simple Rifle2.png" },
  { defaultName: "Skull Helmet", filePath: "/futuristic_pixel_icons/Skull Helmet.png" },
  { defaultName: "Small Empty Potion", filePath: "/futuristic_pixel_icons/Small Empty Potion.png" },
  { defaultName: "Space Admiral Leggings", filePath: "/futuristic_pixel_icons/Space Admiral Leggings.png" },
  { defaultName: "Space Bullet", filePath: "/futuristic_pixel_icons/Space Bullet.png" },
  { defaultName: "Space Sapling", filePath: "/futuristic_pixel_icons/Space Sapling.png" },
  { defaultName: "Space Shield1", filePath: "/futuristic_pixel_icons/Space Shield1.png" },
  { defaultName: "Space Shield2", filePath: "/futuristic_pixel_icons/Space Shield2.png" },
  { defaultName: "Speed Rifle Purple", filePath: "/futuristic_pixel_icons/Speed Rifle Purple.png" },
  { defaultName: "Speed Rifle Red", filePath: "/futuristic_pixel_icons/Speed Rifle Red.png" },
  { defaultName: "Spiked Pustol", filePath: "/futuristic_pixel_icons/Spiked Pustol.png" },
  { defaultName: "Stone Meteorite", filePath: "/futuristic_pixel_icons/Stone Meteorite.png" },
  { defaultName: "Tech Bow", filePath: "/futuristic_pixel_icons/Tech Bow.png" },
  { defaultName: "Tiny Blue Potion", filePath: "/futuristic_pixel_icons/Tiny Blue Potion.png" },
  { defaultName: "Tiny Brown Pistol", filePath: "/futuristic_pixel_icons/Tiny Brown Pistol.png" },
  { defaultName: "Tiny Green Potion", filePath: "/futuristic_pixel_icons/Tiny Green Potion.png" },
  { defaultName: "Tiny Orange Potion", filePath: "/futuristic_pixel_icons/Tiny Orange Potion.png" },
  { defaultName: "Tiny Purple Potion", filePath: "/futuristic_pixel_icons/Tiny Purple Potion.png" },
  { defaultName: "Tiny Red Potion", filePath: "/futuristic_pixel_icons/Tiny Red Potion.png" },
  { defaultName: "Toolkit", filePath: "/futuristic_pixel_icons/Toolkit.png" },
  { defaultName: "Turqoise Crystal", filePath: "/futuristic_pixel_icons/Turqoise Crystal.png" },
  { defaultName: "Turqoise Ring", filePath: "/futuristic_pixel_icons/Turqoise Ring.png" },
  { defaultName: "Up Arrow", filePath: "/futuristic_pixel_icons/Up Arrow.png" },
  { defaultName: "Uranium", filePath: "/futuristic_pixel_icons/Uranium.png" },
  { defaultName: "Uranium Bar", filePath: "/futuristic_pixel_icons/Uranium Bar.png" },
  { defaultName: "Uranium Big Blade", filePath: "/futuristic_pixel_icons/Uranium Big Blade.png" },
  { defaultName: "Uranium Bullet", filePath: "/futuristic_pixel_icons/Uranium Bullet.png" },
  { defaultName: "Uranium Cell", filePath: "/futuristic_pixel_icons/Uranium Cell.png" },
  { defaultName: "Uranium Crystal", filePath: "/futuristic_pixel_icons/Uranium Crystal.png" },
  { defaultName: "Uranium Gloves", filePath: "/futuristic_pixel_icons/Uranium Gloves.png" },
  { defaultName: "Uranium Junk", filePath: "/futuristic_pixel_icons/Uranium Junk.png" },
  { defaultName: "Uranium Meteorite", filePath: "/futuristic_pixel_icons/Uranium Meteorite.png" },
  { defaultName: "Uranium Meteorite Shards", filePath: "/futuristic_pixel_icons/Uranium Meteorite Shards.png" },
  { defaultName: "Uranium Neon Shield", filePath: "/futuristic_pixel_icons/Uranium Neon Shield.png" },
  { defaultName: "Uranium Spike Blade", filePath: "/futuristic_pixel_icons/Uranium Spike Blade.png" },
  { defaultName: "Veggie Pack", filePath: "/futuristic_pixel_icons/Veggie Pack.png" },
  { defaultName: "Warning Icon", filePath: "/futuristic_pixel_icons/Warning Icon.png" },
  { defaultName: "Warning Shield", filePath: "/futuristic_pixel_icons/Warning Shield.png" },
  { defaultName: "White Cell", filePath: "/futuristic_pixel_icons/White Cell.png" },
  { defaultName: "White Claw", filePath: "/futuristic_pixel_icons/White Claw.png" },
  { defaultName: "White Jetpack", filePath: "/futuristic_pixel_icons/White Jetpack.png" },
  { defaultName: "White Lining Gloves", filePath: "/futuristic_pixel_icons/White Lining Gloves.png" },
  { defaultName: "White Skull", filePath: "/futuristic_pixel_icons/White Skull.png" },
  { defaultName: "Wrench", filePath: "/futuristic_pixel_icons/Wrench.png" },
  { defaultName: "Yellow Crate", filePath: "/futuristic_pixel_icons/Yellow Crate.png" },
  { defaultName: "Yellow Cyberblade", filePath: "/futuristic_pixel_icons/Yellow Cyberblade.png" },
  { defaultName: "Yellow Stripe Helmet", filePath: "/futuristic_pixel_icons/Yellow Stripe Helmet.png" },
];
