export const startupPhrases: Record<string, string[]> = {
  English500: [
    "glhf",
    "glgl",
    "ready for dust-off",
    "let's go",
    "commence bombardment",
    "ready to plunder",
    "fortune favors the bold",
    "let's get into the fight",
    "systems primed",
    "bring it",
    "oh, it's on",
    "let's do this",
    "it's go time",
    "it's about to get heavy",
    "put me in coach",
  ],
  Spanish500: [
    "adelante",
    "listos para la batalla",
    "vamos allá",
    "a por ellos",
    "preparados",
    "empecemos",
    "suerte a todos",
  ],
  French500: [
    "en avant",
    "prêts pour la bataille",
    "allons-y",
    "bonne chance",
    "c'est parti",
    "commençons",
    "à l'attaque",
  ],
  German500: [
    "los geht's",
    "viel glück",
    "auf in den kampf",
    "bereit",
    "angriff",
    "vorwärts",
    "jetzt geht's los",
  ],
  Italian500: [
    "andiamo",
    "buona fortuna",
    "pronti via",
    "avanti",
    "iniziamo",
    "forza",
    "si parte",
  ],
  Portuguese500: [
    "vamos lá",
    "boa sorte",
    "preparados",
    "começar",
    "avante",
    "força",
    "partiu",
  ],
  Japanese500: [
    "がんばって",
    "行きましょう",
    "準備完了",
    "スタート",
    "よろしく",
  ],
  Korean500: [
    "화이팅",
    "가자",
    "시작하자",
    "준비 완료",
    "파이팅",
  ],
  Chinese500: [
    "加油",
    "开始吧",
    "出发",
    "准备好了",
    "冲",
  ],
  Ukrainian500: [
    "вперед",
    "удачі",
    "готові",
    "почали",
    "за перемогу",
  ],
  Arabic500: [
    "يلا",
    "بالتوفيق",
    "هيا بنا",
    "جاهزون",
    "ابدأ",
  ],
  Hindi500: [
    "चलो",
    "शुभकामनाएं",
    "तैयार हैं",
    "शुरू करें",
    "जीत हमारी",
  ],
  Dutch500: [
    "laten we gaan",
    "veel succes",
    "klaar",
    "vooruit",
    "beginnen maar",
    "op naar de overwinning",
  ],
  Swedish500: [
    "kör hårt",
    "lycka till",
    "vi kör",
    "redo",
    "framåt",
    "nu kör vi",
  ],
  Turkish500: [
    "hadi bakalım",
    "başarılar",
    "hazırız",
    "başlayalım",
    "ileri",
    "haydi",
  ],
  EnglishQuotes: [
    "time for wisdom",
    "words of the wise",
    "quote time",
    "let's get inspired",
    "wisdom awaits",
  ],
  SpanishQuotes: [
    "hora de sabiduría",
    "palabras sabias",
    "citas famosas",
    "inspiración",
  ],
  FrenchQuotes: [
    "paroles de sagesse",
    "citations célèbres",
    "l'heure de la sagesse",
    "inspiration",
  ],
  GermanQuotes: [
    "zeit für weisheit",
    "weise worte",
    "berühmte zitate",
    "inspiration",
  ],
  ItalianQuotes: [
    "tempo di saggezza",
    "parole sagge",
    "citazioni famose",
    "ispirazione",
  ],
  PortugueseQuotes: [
    "hora da sabedoria",
    "palavras sábias",
    "citações famosas",
    "inspiração",
  ],
};

export function getRandomStartupPhrase(gameModeTag: string): string {
  const phrases = startupPhrases[gameModeTag] || startupPhrases.English500;
  const randomIndex = Math.floor(Math.random() * phrases.length);
  return phrases[randomIndex];
}
