namespace StdbModule;

public static partial class CzechQuotes
{
    public static class PavelKosorin
    {
        private const string Source = "https://cs.wikiquote.org/wiki/Pavel_Kosorin";

        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = Source, Text = "Nejlepším důkazem opravdové lásky je, že na vás nevyžaduje žádný důkaz.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Mít jiné srdce, milovali bychom stejné lidi?", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Každý musí platit za chyby, které dělá, ale kdo je udělal z lásky, dostane slevu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když je Bible zakázána, čte se více jako když je kázána.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Všechny módní názory jsem našel ve staré Bibli.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bible je 66 a víc knih pro 66 a víc roků.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bible je v současnosti jediný zlatý poklad, který je celý v oběhu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bible se podobá zlatému dolu - kdo není ochotný kopat, nemá žádnou šanci zbohatnout.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Nikdo nemá tolik poradců jako ten, kdo má Bibli.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Je to skandál, co Bible učí, ale výsledkem je pokoj.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo přestane číst Bibli, stane se nečitelným křesťanem.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Možná by se Bible začala víc číst, kdyby Bůh přišel se soutěží: \"Vyhrej týden v nebi\".", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Špatný politik slibuje úrodné léto – dobrý politik zařídí dostatek kombajnů.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Slovo ministr znamená služebník – jenže latina je mrtvý jazyk.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Malí občané se nikdy nedočkají velkých politiků.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Nejvyšším posláním člověka žijícího v masové společnosti je být sám sebou.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Všude slibují politici hory doly – jen u nás moře.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Politika je hra podle jasných pravidel, které se každý den mění.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Demokracie je tam, kde se většina lidí cítí být svým vlastním pánem.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Svobodu můžete vyměnit za cokoli, ale nikdy to nebude dobrý obchod.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Čím menší rozdíly mezi lidmi, tím diferencovanější závist.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Největším nedostatkem našeho právního řádu je, že nepostihuje zloděje času.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bez kapitalistických peněz by nebylo komunistických snů.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Komunismus se bál, že budeme něco chtít - kapitalismus se snaží, abychom chtěli všechno.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdyby Bůh mluvil jazykem teologů, nikdo by se s ním nebavil.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Přirovnávat Boha k hodnému dědečkovi se mi nezdá úplně špatné – děda byl jediný, kdo si na mne dovedl udělat čas.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh si pečlivě vybírá ty, které vyslyší – a ještě pečlivěji ty, jejichž prosby nechá bez odpovědi.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "O Bohu se nejlépe pobavím s těmi, kteří jsou bez vyznání.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "O Hospodina se musíme opírat jinak než o lopatu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo má problémy s vírou, buď o Bohu nechce ani slyšet, nebo o ničem jiném nemluví.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh chodí po světě v převleku hříšníka.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh drží i ty, kteří se ho pustili.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh je neviditelný, aby mu nikdo nemohl vyčítat přetvářku.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Víra v Boha je berlička, ale raději se do nebe dobelhat, než tam vůbec nedojít.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Boží slovo můžete umlčet, ale ne přemluvit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh vidí všechno, protože si před ničím nezakrývá oči.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh je jediný obsah, pro který člověk neumí vymyslet formu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Musíte vydržet – Bůh nikdy netrhá nezralé ovoce.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Na Bohu se mi líbí, že svoji štědrost neprojevuje jen na Vánoce", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh je tak blízko, že ho člověk snadno přehlédne.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh není klaun, aby pro naše potěšení udělal cokoli.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Náboženská příslušnost je to, co mnoho lidí odděluje od Boha.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh má na všechno copyright, ďábel jen kopirák.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bůh nedělá zázraky, když se člověku nechce pracovat.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Čím výš se člověk dostane, tím snadněji něčemu propadne.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk je dospělý, pokud neváhá převzít odpovědnost za své dětinské jednání.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk má žít tak, aby se necítil jako neplatící divák.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk musí být do moudrosti blázen, aby z ní něco pochytil.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk odpovídá hlavně za to, na co se ptal.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk roste starostí o to, co zasel.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověk se nenaučí padat, dokud má pod zadkem polštář.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Člověka nelze předělat, a přesto přibývá profesí, které se specializují právě na toto.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Dnes je člověk o životě dokonale informován, ale ví toho o něm čím dál méně.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Dnešní člověk si neklade otázky, na které by musel hledat odpověď.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když člověk padá z velké výšky, nezbývá mu nic jiného, než se naučit létat.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když se člověk škrábe na pořádnou horu, alespoň má záruku, že to s ním nepůjde z kopce.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Nejdál člověk doběhne, když utíká sám před sebou.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "O každém člověku si uděláme nějaký obrázek – a většinu z nich pak musíme přemalovat.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Velikost člověka je dána velikostí toho, před čím je ochoten se sklonit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Znám plno čistotných lidí, kteří se neštítí ničeho.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když chybí cíl, zabýváme se otázkou, kterou nohou vykročit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Podezřívám všechny fanatiky, že hlavním důvodem jejich pohledu na svět je nedostatek fantazie.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo svou víru vystavuje jako transparent, měl by se modlit, aby nezačalo foukat.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Mít více svobody, patrně bychom něčemu ještě více otročili.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Vést druhé předpokládá projít cestu jako první.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Pokud lidem říkáte jenom to, co chtějí slyšet, jste zodpovědní za jejich hluchotu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Co se nedá prominout, musí se odpustit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Až najdete odvahu něco udělat, budete se muset vypořádat s těmi, kteří to štěstí neměli.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Jedním z nejčastějších způsobů, jak zamaskovat svůj vnitřní zmatek, je bezvadně srovnaný stůl.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Je poněkud neslušné brát lidi takové, jací jsou – každý se přece snaží změnit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Nebe je nedobytné, ale otevřené.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Čím méně peněz, tím více času na věci, které se nedají koupit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Ke svému rozumu bychom měli být mnohem kritičtější.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Bavte se svými dětmi co nejvíc – hlavně v době, kdy ještě věří pohádkám.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Až budete tvořit svůj svět, nezapomeňte na světlo.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když se někdo příliš snaží, aby neztratil tvář, pravděpodobně tu bude maska.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Dnes pochybujeme o tom, čemu se vždycky věřilo, a věříme tomu, o čem se vždycky pochybovalo.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když vidíme pokaždé trochu jinak, je to oční vada, nebo respekt ke skutečnosti?", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Chcete-li dojít daleko, musíte vyjít ze sebe.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když ptákům začnete sypat zrní, odnaučíte je létat.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když budu chtít, aby mi pták neuletěl z klece, naučím ho zpívat o svobodě.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "O prodloužení života mají zájem především ti, kteří nedosáhli na jeho smysl.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Starosti jsou neřešitelné – na rozdíl od skutečných problémů.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když si malujete budoucnost, používejte všechny barvy.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Jde o to nevzdat se ani poté, co zvítězíme.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Skutečného hrdinu poznáte podle toho, že se dovede bát.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Každá odpověď vzbudí nějakou otázku – a filosof je člověk, který kvůli ní nejde spát.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo nemá křídla, hledá si klec.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo oslavuje předčasně, truchlí pak zbytečně dlouho.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Na náhodu se mohou spoléhat jenom ti, kteří pro ni něco udělali.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Dokud se ve svých názorech rozcházíme, znamená to, že si stále ještě máme co říct.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Své poklesky ochotně vyznáváme, zatímco své pády odmítáme připustit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Padák je dobrá věc, ale nahoru vás nevynese.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Většina poražených nechtěla riskovat vítězství.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Byl jsem překvapen, jak pěkně o něm mluví – než jsem zjistil, že je po smrti.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Strach to se mnou myslí dobře, ale bojím se ho poslechnout.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Obři existují pouze v myslích trpaslíků.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Jedna cesta za humna je cennější než nejbarevnější atlas světa.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "V křesle se nejlépe vzpomíná na to, co nebylo ani trochu pohodlné.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Kdo se hledá, ten se neztratí.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když se snažíme zasáhnout příliš malý cíl, není divu, že se nám třese ruka.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Až si nebudeme muset na nic hrát – to teprve bude divadlo!", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Máte právo být tím, kým jste, ale potřebujete dobrého obhájce.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Jasno má pouze ten, kdo se neustále ptá.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Když nemáte cíl, máte v cestě mnohem více překážek.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Fanatici šíří strach – potřebují se ho nějak zbavit.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "První podmínkou při hledání zlata je nevěřit tomu, co se třpytí.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Dokud nechytíme viníka, nejsme ochotni přiznat svou chybu.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Jakmile vlk kolem sebe shromáždí dostatek oveček, prohlásí se za pastýře.", Author = "Pavel Kosorin" },
            new Quote { Id = Source, Text = "Nikde není tak příjemně rušno jako v ústraní.", Author = "Pavel Kosorin" },
        };
    }
}
