using System;

namespace StdbModule;

public static partial class SpanishQuotes
{
    public static class JacintoBenavente
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "A nadie le importará que no hagas bien a nadie, pero ¡pobre de ti si al hacer bien a todos has hecho bien al enemigo de alguien!", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "¡Bienaventurados nuestros imitadores, porque de ellos serán todos nuestros defectos!", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Bondad y honradez parecen lo mismo; pero la vida nos dice en sus lecciones que, alguna vez, por ser bueno, hay que dejar de ser honrado.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cambiar los nombres, sin cambiar las cosas, es lo primero con que se engaña al pueblo en todas las revoluciones.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Casi todos los grandes capitalistas y nobles improvisados se hacen muy devotos. Acaso como los antiguos criminales, sienten la necesidad de acogerse a lo sagrado.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Creer y crear son palabras distintas. Pero cuando dices con toda tu alma: ¡Creo, creo!, creer y crear es lo mismo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cuando alguien cumple con su deber, no debe preguntársele en nombre de qué ideal lo cumple.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cuando de una persona se dice que es muy buena, lo mismo que cuando de algo se dice que está muy bueno, ya se sabe de lo que se trata en ambos casos: de comérselo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cuando el corazón dice que perdona una ofensa es que ha dicho antes: \"Ya no me importa\".", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cuando la experiencia del pasado ha servido para rectificar nuestra vida, esta rectificación es la mejor prueba de que nada de lo pasado era nuestra verdadera vida.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Cuando no se piensa lo que se dice, es cuando se dice lo que se piensa.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "De lo que se dice en sociedad, lo que importa es que se tenga gracia; lo de menos es que sea verdad.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Dicen que me burlo de todo, que me río de todo, porque me burlo de ellos y me río de ellos, y ellos creen ser todo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El amigo que sabe llegar al fondo de nuestro corazón, ni aconseja ni recrimina; ama y calla.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El día en que cada uno fuéramos un tirano para nosotros mismos, todos los hombres serían igualmente libres, sin revoluciones y sin leyes.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El divorcio es ridículo. Además, suprime la única seguridad del matrimonio, la de no poder volver a casarse", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El hombre sería el más extraño animal del mundo si no existiera la mujer.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El perdón es siempre una humillación y tarde o temprano acabamos por odiar al que ha tenido algo que perdonarnos.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El público comprende siempre cuando se le emociona.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El pretexto para todas las guerras: conseguir la paz.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El ser feliz es cuestión de práctica.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "El único modo de que la gente no crea en algo malo es porque le convenga creer en algo peor.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "En amor sienta bien a los hombres algo de timidez. La timidez del hombre hace más atrevidas a las mujeres.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "En cuestión de árboles genealógicos es más seguro andarse por las ramas que buscar las raíces.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "En la pelea, se conoce al soldado; sólo en la victoria, se conoce al caballero.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "En la vida, lo más triste no es ser del todo desgraciados; es que nos falte muy poco para ser felices y no podamos conseguirlo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Hay silencios discretos que hieren más que una indiscreción imprudente.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La admiración no interroga nunca; con admirar comprende.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La cultura es la buena educación del entendimiento.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La educación no es cosa de un día ni de dos... He conocido familias mal educadas hasta la quinta generación. Es la enfermedad más hereditaria.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La estimación depende de creer o no creer en quien se estima; el amor, ésta es su tragedia, aunque no crea, ama.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La felicidad es mejor imaginarla que tenerla.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La felicidad no existe en la vida. Sólo existen momentos felices.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La ironía es una tristeza que no puede llorar y sonríe.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La risa es la gran enterradora.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La única revolución posible: meter luz en las cabezas y calor en los corazones.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La única tristeza sin consuelo en la vida es la tristeza que se ha merecido.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La vanidad es el feminismo del orgullo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La vanidad hace siempre traición a nuestra prudencia y aún a nuestro interés.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "La verdadera educación se demuestra cuando se pierde la educación.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Lo cruel de la vida no es que lo niegue todo, es que promete mucho [...]. No es que se haga aborrecer, es que se hace amar y no corresponde nunca.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Lo malo de la conciencia es que siempre está hecha a la medida.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Lo más parecido a la mentira es el silencio, cuando se calla lo que no se quiere decir.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Lo peor que hacen los malos es obligarnos a dudar de los buenos.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Los amores son como los niños recién nacidos; hasta que lloran no se saben si viven.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Los dictadores pueden reformar las leyes; pero no las costumbres.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Los hombres han querido someter todas las cosas a su voluntad, y hoy son los hombres esclavos de todas las cosas.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Los pueblos débiles y flojos, sin voluntad y sin conciencia, son los que se complacen en ser mal gobernados.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Medio pueblo con odio vale por un pueblo entero.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Muchas veces, el que nos crean mejores de lo que somos nos obliga a serlo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Nadie confiesa sus culpas si no espera que le sean perdonadas, y las mujeres menos.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No debe despreciarse ninguna ocasión de aparentar que se es muy desgraciado, porque así te odian menos, te compadecen un poco y te atienden algo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No hay nada que desespere tanto como ver mal interpretados nuestros sentimientos.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No hay nadie tan elocuente como uno mismo cuando quiere persuadirse de lo que le conviene estar persuadido.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No hay que pensar mal. El mal pensamiento es semilla en buen terreno, que un día u otro sale por la boca.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No hay sentimiento que valga; el amor es una ocupación como otra cualquiera.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "No hay triunfador que no sea presa de su triunfo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Nuestra vida no es nunca lo que hemos querido, sino lo que hemos tenido que dejar de querer.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "¡Oh, la seriedad! ¡La ropa negra con que se va a todas partes!", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Para comprender el dolor no hay inteligencia como el dolor mismo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Para que se le ocurra a uno algo bueno cuando menos lo piensa, es porque antes ha pensado mucho en ello.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Para salir adelante con todo, mejor que crear afectos, es crear intereses.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Piense usted que siempre es más noble engañarse alguna vez que desconfiar siempre.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Por la inteligencia rara vez nos ponemos de acuerdo; por el corazón, siempre.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "¡Quién sabe cuándo es mayor el cariño: cuando nada perdona o cuando lo perdona todo!", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "¡Quién sabe si cuando creemos imponer más libremente nuestra voluntad es cuando más ciegamente obedecemos a la fatalidad de nuestro destino!", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Se hará lo que se deba, aunque se deba lo que se haga.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Si cada día hallara una nueva verdad en mi espíritu, y al hallarla tuviera que destruir cada día mi vida por completo, sin dudar la destruiría, para vivir cada día una nueva vida con una nueva verdad.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Si hubiésemos de apreciar nuestra bondad por la gratitud de los favorecidos con ella, tendríamos que creer que solo habíamos hecho mal.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Si la gente nos oyera los pensamientos, pocos escaparíamos de estar encerrados por locos.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Si [los hombres] hubiesen triunfado del Dolor y de la Muerte, quizá ya no hubiesen deseado nada, y sin desear algo, ¿vale la pena vivir?", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Si murmurar la verdad aún puede ser la justicia de los débiles, la calumnia no puede ser nunca más que la venganza de los cobardes.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Sólo los pueblos que respetan todas las religiones merecen que las suyas sean respetadas.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Somos demasiado inexorables al juzgar a los demás cuando nos creemos sin culpa; solo el pecador debiera juzgar a los pecadores.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Suprime la vanidad en las mujeres y habrás suprimido la mitad, por lo menos, de ambición en los hombres.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Tan duro es para una mujer ser excepcionalmente bella, que la mayoría fracasan y acaban mal.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Tengo observado que todos los que no pueden tolerar una mala palabra de los superiores son los que más suelen prodigarlas con los inferiores.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Todo el mundo es teatro y todos somos en él comediantes.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Todos creen que tener talento es cuestión de suerte; nadie piensa que la suerte puede ser cuestión de talento.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Triste clase media, que hubiera podido ser una fuerza, si en vez de una caricatura de los de arriba hubiera procurado ser un ejemplo para los de abajo.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Una cosa es continuar la historia y otra repetirla.", Author = "Jacinto Benavente" },
            new Quote { Id = "https://es.wikiquote.org/wiki/Jacinto_Benavente", Text = "Una hora de alegría es algo que robamos al dolor y a la muerte, y el cielo nos recuerda pronto nuestro destino.", Author = "Jacinto Benavente" },
        };
    }
}