using System;

namespace StdbModule;

public static partial class SwedishQuotes
{
    public static class VilhelmMoberg
    {
        public static readonly Quote[] Quotes = new Quote[]
        {
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Icke värderade han friheten lägre därför att de fega kunde vara den förutan.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Bonden ägde handens kunskap. Och dagsverkare med ryggvärk och skinnflådda händer gick tåligt böjda över jorden med sina redskap dagarna i ända. Minnesmärket över sin strävan har de själva rest i stengärdsgårdar, tusentals mil långa. All denna sten är upptagen ur åkrarna och lagd i mur, och det har kostat många svettets dryga dagsverken. Kampen mot stenen, erövringen av landet åt odlingen är ett historiskt drama, ett väldigt epos om fredlig bragd som aldrig satts på pränt.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Om förfädernas krigiska företag är mycket skrivet: det finns stora, officiella generalstabsverk i många band om dem. I jämförelse därmed är det inte mycket upptecknat om deras gärning i fred här hemma. Vi vet vad de gjorde med svärd, gevär och kanon, men föga om det som de har uträttat med arbetes fredliga redskap. Både historia och diktning har varit snåla emot bonden, dagsverkaren och tjänstehjonen och deras verk. Ingen historisk avhandling har ännu skrivits om mödans minnesmärken, stenmurarna, och inte heller har de besjungits av någon poet.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Bondebylagets själva bärande idé om mänsklig samverkan och gemenskap syns mig så pass tidlös, att den skulle kunna förverkligas även i sentida miljöer. Kanske kan den en gång återuppstå i ett annat samhälle än det nuvarande - en samhällsform, där människan intar den självskrivna centrala platsen.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Sverige är vårt, det är sex och en kvarts millioner levande svenskars land. Men det är även de dödas land, deras som byggt upp det åt oss från början och lämnat oss sitt verk att förvalta och förkovra. De döda är åtskilliga millioner flera än vi. De har mycket att säga oss nu, och vi är skyldiga att lyssna till dem. Vi lyssnar till dem genom att minnas vad de uträttat och genom att värdesätta deras strävan. De kan icke mera värja sitt verk. Det åligger oss.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Och man har stundom ett intryck av att svenska ämbetsmän lider av en onaturlig vördnad för sitt eget ämbete. Det är inte alltid deras personlighet och duglighet, som ger dem auktoritet, utan de får sin auktoritet genom själva ämbetet, som liksom i sig självt garanterar för innehavarens oförvitlighet och hederlighet. Och det finns utan tvivel en sammanhållning mellan våra myndighetspersoner av sådan art, att den kan bli en fara för medborgarnas rättssäkerhet. Men man kan konstatera en utbredd benägenhet att ta hänsyn till högt uppsatta personer i samhället. Och varje ämbetsman hat en överordnad, som han ser sig nödsakad att ta hänsyn till. Var och en har sin karriär att tänka på. En självständig man råkar lätt i onåd på högre ort, och då riskerar han sin karriär. Och så är det hänsynen till vännen. På kvällen råkar man sin gode vän i sällskapligt umgänge, dagen efter skall man kanske å ämbetets vägnar yttra sig över klagomål som inkommit över den gode vännens ämbetsåtgärder. Det uppstår en samvetskonflikt, och det är inte alltid som det omutliga samvetet segrar. Så etablerar myndighetspersonerna ett ömsesidigt skydd av varandra. Jag skulle vilja kalla företeelsen vänskapskorruption.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "\"Därför är jag republikan\" är en kampskrift, riktad emot Sveriges statsskick och därmed också emot den del av Sveriges folk, som vill behålla detta statsskick. Den är skriven i avsikt att såra monarkisterna. Den vill komma åt den undersåtlighetens anda, som alltjämt tar sig så starka uttryck hos en mängd svenskar. Den vill förlöjliga servilismen och kryperiet, som frodas i atmosfären kring den kungliga tronen. Den vill fånga in och visa fram de andliga oarter, som det monarkistiska statsskicket alstrar. Skriften vill angripa kungafjäsket och hovmannamentaliteten - allt detta som vi skulle befrias ifrån, om kungligheten och hovet finge avflytta till sin naturliga hemvist: Museet.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Det yttersta upphovet till århundradets rättsskandal är vårt gamla kungadöme av Guds nåde. Före Haijbyaffären hade jag levat i tron att det existerade likhet inför lagen i Sverige, men sedan jag följt dess förlopp från början till slut förlorade jag denna tro.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "Enligt den totalitära ideologin — den nazistiska och den kommunistiska — är vi människor statens egendom, och i egenskap av statsägda varelser uppnår och åtnjuter vi den sanna friheten. Vår uppgift i totalstaten är i första hand att vara medborgare och nyttiga och effektiva delar av ett kollektiv. Men för min del ansluter jag mig till den äldre och ursprungliga tolkningen av innehållet i ordet frihet. Jag ansluter mig till dem som menar att vi människor icke är skapade till att vara objekt för statsnyttan. Ingenting kan rubba mig ur den övertygelsen och tron, att vårt liv är helt vårt eget — att människolivet från vaggan till graven är ett mål i sig självt.", Author = "Vilhelm Moberg" },
            new Quote { Id = "https://sv.wikiquote.org/wiki/Vilhelm_Moberg", Text = "ett odjur utan moral och utan sinne för lyrik", Author = "Vilhelm Moberg" },
        };
    }
}